Repository yunionio/dashboard, pull requests merged in 2021-11, with the labels that each got.

#1414 fix: choose network error for cover physicalmachine to host
  containers/Compute/sections/ServerNetwork/index.vue
Labels: size/XS

#1415 Automated cherry pick of #1414: fix: choose network error for cover physicalmachine to host
  containers/Compute/sections/ServerNetwork/index.vue
Labels: size/XS

#1413 feat: add panel
  containers/Dashboard/extends/VmHistoryCount/index.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/sections/ExtendGallery/config.js
  containers/Dashboard/views/dashboard/config/default.js
Labels: area/dashboard, size/L

#1416 Automated cherry pick of #1413: feat: add panel
  containers/Dashboard/extends/VmHistoryCount/index.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/sections/ExtendGallery/config.js
  containers/Dashboard/views/dashboard/config/default.js
Labels: size/L

#1417 fix: add domain panel link
  containers/Dashboard/extends/NumberCard/components/Server.vue
Labels: area/dashboard, size/S

#1418 Automated cherry pick of #1417: fix: add domain panel link
  containers/Dashboard/extends/NumberCard/components/Server.vue
Labels: size/S

#1419 feat: delete user create limit
  containers/IAM/views/user/components/List.vue
  src/config/limit.js
Labels: size/S

#1429 feat(#3420): update monitor alert
  src/App.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/permission.js
  src/sections/DialogManager/components/MonitorAlertNotify.vue
  src/store/modules/auth.js
  src/store/modules/monitor.js
Labels: size/L

#1421 fix: network status filter
  containers/Network/views/network/components/List.vue
Labels: area/network, size/S

#1422 Automated cherry pick of #1421: fix: network status filter
  containers/Network/views/network/components/List.vue
Labels: size/S

#1423 Automated cherry pick of #1421: fix: network status filter
  containers/Network/views/network/components/List.vue
Labels: size/S

#1424 fix: fetch nofify template when notify type is mobile
  containers/IAM/views/notifyconfig/sidepage/Detail.vue
Labels: size/XS

#1425 Automated cherry pick of #1424: fix: fetch nofify template when notify type is mobile
  containers/IAM/views/notifyconfig/sidepage/Detail.vue
Labels: size/XS

#1426 fix: add domain manager title
  scope/layouts/Navbar/index.vue
Labels: size/XS

#1427 Automated cherry pick of #1426: fix: add domain manager title
  scope/layouts/Navbar/index.vue
Labels: size/XS

#1428 fix: add image caching for vm
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#1430 feat: limit idp type on public platform
  containers/IAM/views/idp/edit/index.vue
Labels: size/XS

#1431 Automated cherry pick of #1430: feat: limit idp type on public platform
  containers/IAM/views/idp/edit/index.vue
Labels: size/XS

#1434 feat: change kvm ceph disk limit
  src/constants/compute.js
Labels: area/compute, size/XS

#1435 Automated cherry pick of #1434: feat: change kvm ceph disk limit
  src/constants/compute.js
Labels: size/XS

#1436 Automated cherry pick of #1434: feat: change kvm ceph disk limit
  src/constants/compute.js
Labels: size/XS

#1438 fix: alert records filter
  containers/Monitor/views/alertrecord/components/List.vue
Labels: size/M, area/monitor

#1439 Automated cherry pick of #1438: fix: alert records filter
  containers/Monitor/views/alertrecord/components/List.vue
Labels: size/M

#1440 fix: nofifyconfig fetchdata params
  containers/IAM/views/notifyconfig/create/index.vue
  containers/IAM/views/robots/components/List.vue
Labels: size/XS

#1441 Automated cherry pick of #1440: fix: nofifyconfig fetchdata params
  containers/IAM/views/notifyconfig/create/index.vue
  containers/IAM/views/robots/components/List.vue
Labels: size/XS

#1445 feat: #3450 优化建议删除需要通过权限判断，如果没有删除权限则隐藏删除操作
  src/constants/permission.js
Labels: size/XS

#1442 fix: disk mount point delete swap type
  src/constants/compute.js
Labels: area/compute, size/XS

#1443 Automated cherry pick of #1442: fix: disk mount point delete swap type
  src/constants/compute.js
Labels: size/XS

#1444 Automated cherry pick of #1442: fix: disk mount point delete swap type
  src/constants/compute.js
Labels: size/XS

#1446 Automated cherry pick of #1445: feat: #3450 优化建议删除需要通过权限判断，如果没有删除权限则隐藏删除操作
  src/constants/permission.js
Labels: size/XS

#1452 fix: network exit true create server error
  containers/Compute/utils/createServer.js
Labels: size/XS

#1447 fix: disk mount point style
  src/sections/DiskMountpoint/index.vue
Labels: area/compute, size/XS

#1448 Automated cherry pick of #1447: fix: disk mount point style
  src/sections/DiskMountpoint/index.vue
Labels: size/XS

#1449 Automated cherry pick of #1447: fix: disk mount point style
  src/sections/DiskMountpoint/index.vue
Labels: size/XS

#1450 feat: split mutiply actions
  containers/Compute/views/webapp/components/List.vue
Labels: size/M, area/compute

#1451 Automated cherry pick of #1450: feat: split mutiply actions
  containers/Compute/views/webapp/components/List.vue
Labels: size/M

#1454 fix: modify servers count trend i18n
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
Labels: area/dashboard, size/XS

#1455 Automated cherry pick of #1454: fix: modify servers count trend i18n
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
Labels: size/XS

#1456 feat: change host dashboard chart color
  containers/Compute/views/host/sidepage/Dashboard.vue
  src/sections/ProgressCard/index.vue
Labels: size/S

#1458 Automated cherry pick of #1456: feat: change host dashboard chart color
  containers/Compute/views/host/sidepage/Dashboard.vue
  src/sections/ProgressCard/index.vue
Labels: size/S

#1463 fix: server create network choose error
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
Labels: size/XS

#1462 feat: disable some actions in redis/rds (azure/aws)
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds-account/components/List.vue
  containers/DB/views/rds-backup/components/List.vue
  containers/DB/views/rds-database/components/List.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/mixins/singleActions.js
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/mixins/singleActions.js
  containers/DB/views/redis/sidepage/AccountList.vue
  containers/DB/views/redis/sidepage/BackupList.vue
  containers/DB/views/redis/sidepage/WhiteList.vue
Labels: area/db, size/L

#1465 feat(#3452): only show user tag
  containers/Cloudenv/views/tag/components/List.vue
Labels: size/XS

#1466 Automated cherry pick of #1465: feat(#3452): only show user tag
  containers/Cloudenv/views/tag/components/List.vue
Labels: size/XS

#1467 Automated cherry pick of #1465: feat(#3452): only show user tag
  containers/Cloudenv/views/tag/components/List.vue
Labels: size/XS

#1468 feature: support change vm machine type(pc or q35)
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/Machine/index.vue
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/M

#1469 Automated cherry pick of #1468: feature: support change vm machine type(pc or q35)
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/Machine/index.vue
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/M

#1472 Automated cherry pick of #1468: feature: support change vm machine type(pc or q35)
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/Machine/index.vue
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/M

#1473 Automated cherry pick of #1290: feature: support setting vdi and vga of vm
  containers/Compute/sections/VDI/index.vue
  containers/Compute/sections/VGA/index.vue
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/M

#1470 fix: GCP billing use bigquery as default source
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
Labels: size/XS

#1471 Automated cherry pick of #1470: fix: GCP billing use bigquery as default source
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
Labels: size/XS

#1476 feat: split mutiply actions
  containers/Network/views/waf/components/List.vue
Labels: size/M, area/network

#1477 Automated cherry pick of #1476: feat: split mutiply actions
  containers/Network/views/waf/components/List.vue
Labels: size/M

#1478 Automated cherry pick of #1428: fix: add image caching for vm
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#1479 fix: set machine type on server create
  containers/Compute/sections/Machine/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/M

#1480 Automated cherry pick of #1479: fix: set machine type on server create
  containers/Compute/sections/Machine/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/M

#1482 feature: allow set network's ntp server, allow multiple dns server,
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/Create.vue
  containers/Network/views/network/EditAttributes.vue
  containers/Network/views/network/mixins/singleActions.js
  containers/Network/views/network/sidepage/Detail.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/L

#1483 Automated cherry pick of #1482: feature: allow set network's ntp server, allow multiple dns server, allow edit vpc network's attributes
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/Create.vue
  containers/Network/views/network/EditAttributes.vue
  containers/Network/views/network/mixins/singleActions.js
  containers/Network/views/network/sidepage/Detail.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/L

#1490 feat: adjust redis monitor sequence
  containers/DB/constants/index.js
Labels: area/db, size/S

#1491 Automated cherry pick of #1490: feat: adjust redis monitor sequence
  containers/DB/constants/index.js
Labels: size/S

#1484 feat: monitor alert status filter
  containers/Monitor/views/alertrecord/components/List.vue
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/monitor, size/S

#1485 Automated cherry pick of #1484: feat: monitor alert status filter
  containers/Monitor/views/alertrecord/components/List.vue
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#1486 google lb backend group add default region
  containers/Network/constants/lb.js
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/constants/index.js
  containers/Network/views/lb/mixins/columns.js
  containers/Network/views/lb/mixins/singleActions.js
  containers/Network/views/lb/sidepage/Detail.vue
  containers/Network/views/loadbalancerbackend/components/List.vue
  containers/Network/views/loadbalancerbackend/mixins/singleActions.js
  containers/Network/views/loadbalancerbackendgroup/components/List.vue
  containers/Network/views/loadbalancerbackendgroup/mixins/singleActions.js
  containers/Network/views/loadbalancerlistener/components/List.vue
  containers/Network/views/loadbalancerlistener/mixins/singleActions.js
  containers/Network/views/loadbalancerlistenerrule/components/List.vue
  containers/Network/views/loadbalancerlistenerrule/mixins/singleActions.js
Labels: area/network, size/L

#1487 Automated cherry pick of #1486: google lb backend group add default region
  containers/Network/constants/lb.js
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/constants/index.js
  containers/Network/views/lb/mixins/columns.js
  containers/Network/views/lb/mixins/singleActions.js
  containers/Network/views/lb/sidepage/Detail.vue
  containers/Network/views/loadbalancerbackend/components/List.vue
  containers/Network/views/loadbalancerbackend/mixins/singleActions.js
  containers/Network/views/loadbalancerbackendgroup/components/List.vue
  containers/Network/views/loadbalancerbackendgroup/mixins/singleActions.js
  containers/Network/views/loadbalancerlistener/components/List.vue
  containers/Network/views/loadbalancerlistener/mixins/singleActions.js
  containers/Network/views/loadbalancerlistenerrule/components/List.vue
  containers/Network/views/loadbalancerlistenerrule/mixins/singleActions.js
Labels: size/L

#1488 fix: dashboard panel suggestalert percent
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
Labels: area/dashboard

#1489 Automated cherry pick of #1488: fix: dashboard panel suggestalert percent
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
Labels: size/XS

#1492 server sidepage details data add have_agent property
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Compute/views/vminstance/components/InstallAgentFormVisible.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  src/utils/common/tableColumn.js
Labels: area/compute, size/S

#1494 Automated cherry pick of #1492: server sidepage details data add have_agent property
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Compute/views/vminstance/components/InstallAgentFormVisible.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  src/utils/common/tableColumn.js
Labels: size/S

#1493 Automated cherry pick of #1492: server sidepage details data add have_agent property
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Compute/views/vminstance/components/InstallAgentFormVisible.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  src/utils/common/tableColumn.js
Labels: size/S

#1495 feat(#2660): add vpc network
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/vpc-network/components/List.vue
  containers/Network/views/vpc-network/dialogs/AssociateVpcForVpcNetworkDialog.vue
  containers/Network/views/vpc-network/dialogs/RemoveVpcForVpcNetworkDialog.vue
  containers/Network/views/vpc-network/index.vue
  containers/Network/views/vpc-network/mixins/columns.js
  containers/Network/views/vpc-network/mixins/singleActions.js
  containers/Network/views/vpc-network/sidepage/Detail.vue
  containers/Network/views/vpc-network/sidepage/RouteSet.vue
  containers/Network/views/vpc-network/sidepage/Vpc.vue
  containers/Network/views/vpc-network/sidepage/index.vue
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableFilter.js
Labels: size/XL

#1496 Bugfix/tb bugfix 110901
  containers/IAM/constants/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/router/index.js
  containers/Monitor/router/index.js
  containers/Network/router/index.js
Labels: area/monitor, size/S

#1497 Automated cherry pick of #1496: hidden menu fix
  containers/IAM/constants/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/router/index.js
  containers/Monitor/router/index.js
  containers/Network/router/index.js
Labels: size/S

#1498 feat: add vpc network actions
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/vpc-network/components/List.vue
  containers/Network/views/vpc-network/mixins/columns.js
  containers/Network/views/vpc-network/mixins/singleActions.js
  containers/Network/views/vpc-network/sidepage/Vpc.vue
  containers/Network/views/vpc-network/sidepage/index.vue
  src/components/SidePageTrigger/config/index.js
Labels: size/M

#1501 fix: #7928 宿主机导出没有平台字段
  containers/Compute/views/host/components/List.vue
Labels: size/XS

#1503 Automated cherry pick of #1501: fix: #7928 宿主机导出没有平台字段
  containers/Compute/views/host/components/List.vue
Labels: size/XS

#1502 Automated cherry pick of #1501: fix: #7928 宿主机导出没有平台字段
  containers/Compute/views/host/components/List.vue
Labels: size/XS

#1504 fix: #7932 宿主机提示优化
  containers/Compute/views/host/mixins/singleActions.js
Labels: size/XS

#1505 Automated cherry pick of #1504: fix: #7932 宿主机提示优化
  containers/Compute/views/host/mixins/singleActions.js
Labels: size/XS

#1507 fix: update public cachedimage interface params
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/XS

#1509 Automated cherry pick of #1507: fix: update public cachedimage interface params
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/XS

#1508 Automated cherry pick of #1507: fix: update public cachedimage interface params
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/XS

#1512 feat: update vpc network
  containers/Network/views/vpc-network/dialogs/AssociateVpcForVpcNetworkDialog.vue
  containers/Network/views/vpc-network/mixins/columns.js
  containers/Network/views/vpc-network/sidepage/Detail.vue
  src/components/Detail/index.js
Labels: size/XS

#1510 support ctyun crm account
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
Labels: size/S

#1511 Automated cherry pick of #1510: support ctyun crm account
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
Labels: size/S

#1515 feat: update image cache storagecache
  containers/Compute/views/image/sidepage/Cache.vue
Labels: size/S

#1516 feat: add cloudpods account doc url
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
Labels: size/XS

#1518 fix: fail to free reserved ip in non-owner project
  containers/Network/views/reserved-ip/components/List.vue
  containers/Network/views/reserved-ip/dialogs/Freed.vue
  containers/Network/views/reserved-ip/mixins/singleActions.js
Labels: size/XS

#1519 fix: fail to free reserved ip in non-owner project
  containers/Network/views/reserved-ip/components/List.vue
  containers/Network/views/reserved-ip/dialogs/Freed.vue
  containers/Network/views/reserved-ip/mixins/singleActions.js
Labels: size/XS

#1520 fix: fail to free reserved ip in non-owner project
  containers/Network/views/reserved-ip/components/List.vue
  containers/Network/views/reserved-ip/dialogs/Freed.vue
  containers/Network/views/reserved-ip/mixins/singleActions.js
Labels: size/XS

#1521 fix: vm_mem_size accuracy
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: area/compute, size/XS

#1522 Automated cherry pick of #1521: fix: vm_mem_size accuracy
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#1523 Automated cherry pick of #1521: fix: vm_mem_size accuracy
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#1524 feat: #3417 镜像缓存中，增加进度提示
  containers/Compute/views/vminstance/mixins/columns.js
  src/components/Status/index.vue
Labels: size/S

#1525 feat: base-chart add export
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
  containers/Monitor/components/MonitorCard/sections/chart/ring.vue
  src/components/BaseChart/index.vue
Labels: area/monitor, size/L

#1528 common alert update fix
  containers/Monitor/views/commonalert/components/alert/form/index.vue
Labels: size/XS

#1530 feat: monitor export excel
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
  containers/Monitor/components/MonitorCard/sections/chart/ring.vue
  containers/Monitor/views/overview/components/index.vue
Labels: size/M

#1531 fix: excluding eip from server creation
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#1532 Automated cherry pick of #1531: fix: excluding eip from server creation
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#1533 feat[3.8]: monitor add export Excel and Pdf
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
  containers/Monitor/components/MonitorCard/sections/chart/ring.vue
  containers/Monitor/views/overview/components/index.vue
  package-lock.json
  package.json
  src/components/BaseChart/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/main.js
  src/utils/echart.js
  yarn.lock
Labels: size/XXL

#1534 fix: modify action tooltip
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  src/locales/zh-CN.json
Labels: size/XS

#1541 feat: update vpc network
  containers/Network/views/vpc-network/components/List.vue
  containers/Network/views/vpc-network/sidepage/RouteSet.vue
  src/utils/common/tableActions.js
Labels: size/M

#1536 fix: cloudgroup add export columns
  containers/Cloudenv/views/cloudgroup/components/List.vue
  containers/Cloudenv/views/cloudgroup/sidepage/CloudpolicyList.vue
  containers/Cloudenv/views/cloudgroup/sidepage/ClouduserList.vue
  containers/Cloudenv/views/cloudgroupcache/components/List.vue
Labels: size/S

#1538 Automated cherry pick of #1536: fix: cloudgroup add export columns
  containers/Cloudenv/views/cloudgroup/components/List.vue
  containers/Cloudenv/views/cloudgroup/sidepage/CloudpolicyList.vue
  containers/Cloudenv/views/cloudgroup/sidepage/ClouduserList.vue
  containers/Cloudenv/views/cloudgroupcache/components/List.vue
Labels: size/S

#1537 Automated cherry pick of #1536: fix: cloudgroup add export columns
  containers/Cloudenv/views/cloudgroup/components/List.vue
  containers/Cloudenv/views/cloudgroup/sidepage/CloudpolicyList.vue
  containers/Cloudenv/views/cloudgroup/sidepage/ClouduserList.vue
  containers/Cloudenv/views/cloudgroupcache/components/List.vue
Labels: size/S

#1539 fix: projectmapping action optimization
  containers/Cloudenv/views/projectmapping/components/List.vue
  containers/Cloudenv/views/projectmapping/components/RuleList/index.vue
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
  containers/Cloudenv/views/projectmapping/sidepage/index.vue
Labels: area/cloudenv

#1540 Automated cherry pick of #1539: fix: projectmapping action optimization
  containers/Cloudenv/views/projectmapping/components/List.vue
  containers/Cloudenv/views/projectmapping/components/RuleList/index.vue
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
  containers/Cloudenv/views/projectmapping/sidepage/index.vue
Labels: size/S

#1543 fix: update docs url
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/idp/constants.js
  containers/IAM/views/idp/edit/OIDC.vue
Labels: size/XS

#1544 Automated cherry pick of #1543: fix: update docs url
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/idp/constants.js
  containers/IAM/views/idp/edit/OIDC.vue
Labels: size/XS

#1545 fix: vminstance memory accuracy
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: area/compute, size/XS

#1546 Automated cherry pick of #1545: fix: vminstance memory accuracy
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#1547 Automated cherry pick of #1545: fix: vminstance memory accuracy
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#1549 fix: export accuracy
  containers/IAM/views/domains/components/List.vue
  containers/IAM/views/group/sidepage/UserList.vue
Labels: size/XS

#1550 Automated cherry pick of #1549: fix: export accuracy
  containers/IAM/views/domains/components/List.vue
  containers/IAM/views/group/sidepage/UserList.vue
Labels: size/XS

#1553 fix: #7959 新增的告警信息通知不允许拖动
  src/components/BaseDialog/index.vue
  src/sections/DialogManager/components/MonitorAlertNotify.vue
Labels: size/M

#1551 fix: action tooltip accuracy
  containers/Compute/views/webapp/components/List.vue
  containers/Compute/views/webapp/mixins/columns.js
  containers/Compute/views/webapp/sidepage/Detail.vue
Labels: area/compute, size/XS

#1552 Automated cherry pick of #1551: fix: action tooltip accuracy
  containers/Compute/views/webapp/components/List.vue
  containers/Compute/views/webapp/mixins/columns.js
  containers/Compute/views/webapp/sidepage/Detail.vue
Labels: size/XS

#1554 fix: action tooptip accuracy
  containers/Network/views/waf/components/List.vue
  containers/Network/views/waf/sidepage/Detail.vue
Labels: area/network, size/XS

#1562 fix: reserved ip free validate
  containers/Network/views/reserved-ip/components/List.vue
  containers/Network/views/reserved-ip/mixins/singleActions.js
Labels: size/S

#1563 Automated cherry pick of #1562: fix: reserved ip free validate
  containers/Network/views/reserved-ip/components/List.vue
  containers/Network/views/reserved-ip/mixins/singleActions.js
Labels: size/S

#1556 fix: action accuracy
  containers/IAM/views/policy/mixins/singleActions.js
Labels: size/XS

#1557 Automated cherry pick of #1556: fix: action accuracy
  containers/IAM/views/policy/mixins/singleActions.js
Labels: size/XS

#1558 fix: date select filter error
  src/components/SearchBox/index.vue
Labels: size/XS

#1560 Automated cherry pick of #1558: fix: date select filter error
  src/components/SearchBox/index.vue
Labels: size/XS

#1559 Automated cherry pick of #1558: fix: date select filter error
  src/components/SearchBox/index.vue
Labels: size/XS

#1561 replace price_info with price show
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/redis/create/components/BottomBar.vue
  containers/Network/views/eip/create/components/BottomBar.vue
  containers/Network/views/nats/create/components/BottomBar.vue
  containers/Storage/views/file-system/create/components/BottomBar.vue
  src/components/PriceFetcher/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/price.js
Labels: size/XXL

#1564 Automated cherry pick of #1562: fix: reserved ip free validate
  containers/Network/views/reserved-ip/components/List.vue
  containers/Network/views/reserved-ip/mixins/singleActions.js
Labels: size/S

#1565 feat: dns action add confirm dialog
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/dns-zone/components/List.vue
  containers/Network/views/dns-zone/mixins/singleActions.js
  containers/Network/views/dns-zonecache/mixins/singleActions.js
Labels: size/M, area/network

#1567 Automated cherry pick of #1565: feat: dns action add confirm dialog
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/dns-zone/components/List.vue
  containers/Network/views/dns-zone/mixins/singleActions.js
  containers/Network/views/dns-zonecache/mixins/singleActions.js
Labels: size/M

#1566 fix: 修复开源项目TopAlert提示问题
  scope/layouts/Navbar/index.vue
  src/sections/Auth/Login/index.vue
Labels: size/M

#1568 Automated cherry pick of #1566: fix: 修复开源项目TopAlert提示问题
  scope/layouts/Navbar/index.vue
  src/sections/Auth/Login/index.vue
Labels: size/M

#1569 feat: 更改同步确认弹框样式
  containers/Network/views/dns-zone/mixins/singleActions.js
Labels: area/network, size/S

#1570 Automated cherry pick of #1569: feat: 更改同步确认弹框样式
  containers/Network/views/dns-zone/mixins/singleActions.js
Labels: size/S

#1575 Automated cherry pick of #1573: create&update secrule add field description
  containers/Compute/views/secgroup/dialogs/EditRules.vue
Labels: size/S

#1571 Bugfix/tb bugfix 111701
  containers/DB/router/index.js
  containers/Middleware/router/index.js
  containers/Monitor/views/alertrecordshields/mixins/columns.js
  containers/Network/router/index.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#1572 Automated cherry pick of #1571: route update
  containers/DB/router/index.js
  containers/Middleware/router/index.js
  containers/Monitor/views/alertrecordshields/mixins/columns.js
  containers/Network/router/index.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#1573 create&update secrule add field description
  containers/Compute/views/secgroup/dialogs/EditRules.vue
Labels: area/compute, size/S

#1574 Automated cherry pick of #1573: create&update secrule add field description
  containers/Compute/views/secgroup/dialogs/EditRules.vue
Labels: size/S

#1586 feat: 云账号创建隐藏掉自动同步
  containers/Cloudenv/views/cloudaccount/components/AutoSync.vue
Labels: size/XS

#1587 feat: export accuracy
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
  containers/Monitor/components/MonitorCard/sections/chart/ring.vue
  containers/Monitor/views/overview/components/index.vue
  scope/assets/excel.svg
  scope/assets/pdf.svg
  src/components/BaseChart/index.vue
Labels: area/monitor, size/S

#1588 Automated cherry pick of #1587: feat: export accuracy
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
  containers/Monitor/components/MonitorCard/sections/chart/ring.vue
  containers/Monitor/views/overview/components/index.vue
  scope/assets/excel.svg
  scope/assets/pdf.svg
  src/components/BaseChart/index.vue
Labels: size/S

#1590 Automated cherry pick of #1589: fix: tag edit tip accuracy
  containers/Network/views/waf/mixins/columns.js
Labels: size/XS

#1591 fix: export projects in group error
  containers/IAM/views/group/sidepage/ProjectList.vue
Labels: size/S

#1592 Automated cherry pick of #1591: fix: export projects in group error
  containers/IAM/views/group/sidepage/ProjectList.vue
Labels: size/S

#1593 feat: #3326 云账号同步优化
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/SelectRegion.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
  containers/Cloudenv/views/cloudaccount/dialogs/SetRegionAutoSync.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/cloudprovider/mixins/singleActions.js
  src/components/PageList/components/Table.vue
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/mixins/step.js
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/XL

#1596 fix: change monitor menu permission
  containers/Monitor/router/index.js
Labels: area/monitor, size/XS

#1597 Automated cherry pick of #1596: fix: change monitor menu permission
  containers/Monitor/router/index.js
Labels: size/XS

#1598 Automated cherry pick of #1595: feat: add global setting dialog
  src/sections/DialogManager/components/GlobalSettingUpdate.vue
Labels: size/L

#1604 fix: add eip filter on set network dialog
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: area/compute

#1605 Automated cherry pick of #1604: fix: add eip filter on set network dialog
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: size/XS

#1606 feat: add i18n
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/XS
