Repository yunionio/dashboard, pull requests merged in 2021-10, with the labels that each got.

#1228 Automated cherry pick of #1227: fix: add sol and jnlp console to converted host
  containers/Compute/utils/hostActions.js
  containers/Compute/utils/webconsole.js
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/components/List.vue
  containers/Compute/views/physicalmachine/mixins/singleActions.js
Labels: size/XL

#1229 fix: close cloud shell when disconnect from server
  src/components/OcTerm/index.vue
  src/components/Xterm/index.vue
Labels: size/S

#1236 Automated cherry pick of #1235: fix: read only capability filter
  src/utils/common/tableFilter.js
Labels: size/XS

#1240 Automated cherry pick of #1239: feat[3.7]: add eip extrnal ID filter
  containers/Network/views/eip/components/List.vue
Labels: size/XS

#1242 fix[3.7]: cloudaccount health status
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/cloudenv, size/XS

#1243 Automated cherry pick of #1242: fix[3.7]: cloudaccount health status
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#1246 Automated cherry pick of #1245: feat[3.7]: wire add cloudenv options
  containers/Network/views/wire/components/List.vue
  containers/Network/views/wire/index.vue
Labels: size/M

#1249 Automated cherry pick of #1248: fix: add mongodb tags
  containers/DB/views/mongodb/mixins/columns.js
  containers/DB/views/mongodb/sidepage/Detail.vue
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#1252 Automated cherry pick of #1250: feat: add robots status and i18n
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#1255 Automated cherry pick of #1254: feat[3.8]: mongodb add tag edit
  containers/DB/views/mongodb/components/List.vue
Labels: size/XS

#1260 fix: network create error
  containers/Network/views/network/Create.vue
Labels: size/XS

#1263 Automated cherry pick of #1262: fix: add cdn and nat tags
  containers/Network/views/cdn/mixins/columns.js
  containers/Network/views/cdn/sidepage/Detail.vue
  containers/Network/views/nats/mixins/columns.js
  containers/Network/views/nats/sidepage/Detail.vue
Labels: size/S

#1266 Automated cherry pick of #1262: fix: add cdn and nat tags
  containers/Network/views/cdn/sidepage/Detail.vue
  containers/Network/views/nats/mixins/columns.js
  containers/Network/views/nats/sidepage/Detail.vue
Labels: size/M

#1274 fix: update feishu app id
  containers/IAM/views/notifyconfig/create/components/Feishu.vue
  containers/IAM/views/notifyconfig/sidepage/Detail.vue
Labels: size/XS

#1275 Automated cherry pick of #1273: feat[3.8]: add tag edit
  containers/Middleware/views/elasticsearch/components/List.vue
  containers/Middleware/views/kafka/components/List.vue
  containers/Network/views/cdn/components/List.vue
  containers/Network/views/lbcerts/components/List.vue
  containers/Network/views/lbcerts/mixins/columns.js
  containers/Network/views/nats/components/List.vue
  containers/Storage/views/file-system/components/List.vue
  src/constants/permission.js
Labels: size/L

#1280 fix[3.8]: change os_arch show
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: area/compute, size/XS

#1282 fix: enable account sync when account auto sync enabled
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/cloudprovider/mixins/singleActions.js
  containers/Cloudenv/views/cloudproviderregion/mixins/singleActions.js
Labels: size/S

#1283 Automated cherry pick of #1282: fix: enable account sync when account auto sync enabled
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/cloudprovider/mixins/singleActions.js
  containers/Cloudenv/views/cloudproviderregion/mixins/singleActions.js
Labels: size/S

#1289 feat[3.8]: cloudaccount create support setting share mode
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/S3CephXsky.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
Labels: area/cloudenv, size/L

#1290 feature: support setting vdi and vga of vm
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/VDI/index.vue
  containers/Compute/sections/VGA/index.vue
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/L

#1291 Automated cherry pick of #1290: feature: support setting vdi and vga of vm
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/VDI/index.vue
  containers/Compute/sections/VGA/index.vue
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/L

#1292 fix[3.7]: hide price info when hasn't meter service
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/redis/create/components/BottomBar.vue
  containers/Network/views/eip/create/components/BottomBar.vue
  containers/Network/views/nats/create/components/BottomBar.vue
  containers/Storage/views/file-system/create/components/BottomBar.vue
  src/utils/auth.js
Labels: size/M

#1293 Automated cherry pick of #1292: fix[3.7]: hide price info when hasn't meter service
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/redis/create/components/BottomBar.vue
  containers/Network/views/eip/create/components/BottomBar.vue
  containers/Network/views/nats/create/components/BottomBar.vue
  containers/Storage/views/file-system/create/components/BottomBar.vue
  src/utils/auth.js
Labels: size/M

#1297 feat[3.9]: change dashboard panel url
  containers/Dashboard/extends/NumberCard/components/Server.vue
Labels: size/XS

#1309 fix[3.8]: public platform filter dashboard panel
  containers/Dashboard/sections/ExtendGallery/index.vue
  containers/Dashboard/views/dashboard/config/public-default.js
Labels: area/dashboard, size/XL

#1313 Fix/glb to 3.8/menu limit
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/user/components/List.vue
  src/config/limit.js
Labels: size/S

#1314 Automated cherry pick of #1313: fix: public platform user create limit
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/user/components/List.vue
  src/config/limit.js
Labels: size/S

#1316 Automated cherry pick of #1315: fix: eslint error
  containers/Compute/sections/VGA/index.vue
Labels: size/XS

#1321 fix: notify topic i18n and layout
  containers/IAM/locales/en.json
  containers/IAM/views/notify-subscriber/components/List.vue
  containers/IAM/views/notify-subscriber/dialogs/SetupNotifyReceiver.vue
  containers/IAM/views/notify-topic/sidepage/Detail.vue
Labels: size/S

#1325 Automated cherry pick of #1323: fix[3.7]: alert recivers add domain filter
  containers/Monitor/views/commonalert/sidepage/Detail.vue
Labels: size/XS

#1327 Automated cherry pick of #1326: feat: add channel feature config
  src/config/channel_setting.js
Labels: size/XS
