Repository yunionio/dashboard, pull requests merged in 2021-07, with the labels that each got.

#520 feat(rds): rds recovery
  containers/DB/views/rds-backup/dialogs/BackupRecovery.vue
Labels: area/db, size/XS

#521 feat(cloudaccount): jdcloud account support bill tasks
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#525 feat(build): add makefile
  Makefile
Labels: size/XS

#526 Automated cherry pick of #525: feat(build): add makefile
  Makefile
Labels: size/XS

#527 Automated cherry pick of #525: feat(build): add makefile
  Makefile
Labels: size/XS

#523 feat(cloudaccount): account column add cloudprovider
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/mixins/columns.js
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/mixins/columns.js
  containers/Network/views/lb/components/List.vue
  containers/Storage/views/bucket/components/List.vue
  src/utils/common/tableColumn.js
  src/utils/common/tableFilter.js
Labels: size/M

#522 fix(rds): After recovery action to refresh rds list
  containers/DB/views/rds-backup/dialogs/BackupRecovery.vue
  containers/DB/views/rds/components/List.vue
Labels: area/db, size/S

#524 Automated cherry pick of #523: feat(cloudaccount): account column add cloudprovider
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/mixins/columns.js
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/mixins/columns.js
  containers/Network/views/lb/components/List.vue
  containers/Storage/views/bucket/components/List.vue
  src/utils/common/tableColumn.js
  src/utils/common/tableFilter.js
Labels: size/M

#528 fix: disk type
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#529 Automated cherry pick of #528: fix: disk type
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#530 Automated cherry pick of #528: fix: disk type
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#531 Automated cherry pick of #528: fix: disk type
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#532 vminstance monitor chart fix
  containers/Compute/views/vminstance/constants.js
  containers/Compute/views/vminstance/sidepage/Monitor.vue
Labels: area/compute, size/XS

#533 Automated cherry pick of #532: vminstance monitor chart fix
  containers/Compute/views/vminstance/constants.js
  containers/Compute/views/vminstance/sidepage/Monitor.vue
Labels: size/XS

#534 fix(k8s): ingresses manager get rawdata
  containers/K8S/views/ingress/mixins/singleActions.js
Labels: size/XS

#535 Automated cherry pick of #534: fix(k8s): ingresses manager get rawdata
  containers/K8S/views/ingress/mixins/singleActions.js
Labels: size/XS

#536 Automated cherry pick of #534: fix(k8s): ingresses manager get rawdata
  containers/K8S/views/ingress/mixins/singleActions.js
Labels: size/XS

#537 feat(Page): change website title
  src/main.js
Labels: size/XS

#538 Automated cherry pick of #537: feat(Page): change website title
  src/main.js
Labels: size/XS

#540 rds jdcloud monitor
  containers/DB/constants/index.js
  containers/DB/views/rds/sidepage/Monitor.vue
Labels: area/db, size/M

#541 fix(k8s): service create selector
  containers/K8S/views/service/create/Form.vue
Labels: size/XS

#542 Automated cherry pick of #541: fix(k8s): service create selector
  containers/K8S/views/service/create/Form.vue
Labels: size/XS

#543 Automated cherry pick of #541: fix(k8s): service create selector
  containers/K8S/views/service/create/Form.vue
Labels: size/XS

#539 support azure elb sync
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/eip/utils/columns.js
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/constants/index.js
  containers/Network/views/lb/mixins/columns.js
  containers/Network/views/lb/sidepage/Detail.vue
  containers/Network/views/lb/sidepage/Properties.vue
  containers/Network/views/lb/sidepage/index.vue
  containers/Network/views/loadbalancerbackendgroup/mixins/columns.js
  containers/Network/views/loadbalancerlistener/sidepage/Detail.vue
  containers/Network/views/loadbalancerlistenerrule/mixins/columns.js
  containers/Network/views/loadbalancerlistenerrule/sidepage/Detail.vue
Labels: approved, area/network, size/L

#544 feat: update logo
  scope/images/cloudpod_login_logo.svg
  scope/images/cloudpod_logo.svg
Labels: size/XXL

#545 Automated cherry pick of #544: feat: update logo
  scope/images/cloudpod_login_logo.svg
  scope/images/cloudpod_logo.svg
Labels: size/XXL

#546 fix: add jdcloud rds trans
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds/constants/index.js
Labels: size/S

#547 扩展列表搜索,添加资源类型搜索条件
  src/utils/common/tableFilter.js
Labels: size/S

#548 license fix
  src/sections/DialogManager/components/UpdateLicense.vue
  src/utils/http.js
Labels: size/XS

#549 fix: add jdcloud disaster category
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds/constants/index.js
Labels: size/XS

#550 修改同步策略详情页icon
  containers/Cloudenv/views/projectmapping/sidepage/index.vue
  scope/assets/projectmapping.svg
Labels: area/cloudenv, size/XS

#551 Automated cherry pick of #550: 修改同步策略详情页icon
  containers/Cloudenv/views/projectmapping/sidepage/index.vue
  scope/assets/projectmapping.svg
Labels: size/XS

#553 azure listener show front ip
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/constants/index.js
  containers/Network/views/lb/mixins/singleActions.js
  containers/Network/views/lb/sidepage/Detail.vue
  containers/Network/views/loadbalancerbackend/components/List.vue
  containers/Network/views/loadbalancerbackend/mixins/singleActions.js
  containers/Network/views/loadbalancerbackendgroup/components/List.vue
  containers/Network/views/loadbalancerbackendgroup/mixins/singleActions.js
  containers/Network/views/loadbalancerlistener/components/List.vue
  containers/Network/views/loadbalancerlistener/mixins/columns.js
  containers/Network/views/loadbalancerlistener/mixins/singleActions.js
  containers/Network/views/loadbalancerlistener/sidepage/Detail.vue
  containers/Network/views/loadbalancerlistenerrule/components/List.vue
  containers/Network/views/loadbalancerlistenerrule/mixins/singleActions.js
Labels: area/network, size/L

#554 feature: support Google OIDC IDP
  src/assets/images/idp-icons/block/google_oidc.png
  src/assets/images/idp-icons/round/google_oidc.png
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#555 Automated cherry pick of #484: add features icons
  containers/Monitor/components/MonitorCard/sections/card/index.vue
  containers/Monitor/views/overview/components/SummaryCards.vue
  src/assets/images/features/monitor.svg
  src/assets/images/providers/lb.svg
  src/components/FeatureSelector/index.vue
  src/constants/feature.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XL

#557 overview card fix
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/OverviewCard/index.vue
  containers/Monitor/components/MonitorCard/OverviewCard/metrics.js
  containers/Monitor/components/MonitorCard/sections/select/basic.vue
  containers/Monitor/components/MonitorCard/sections/select/metric.vue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/views/overview/components/index.vue
Labels: area/monitor, size/L

#558 monitor alert contact channel fix
  containers/Monitor/views/commonalert/components/alert/form/index.vue
Labels: area/monitor, size/XS

#559 Automated cherry pick of #558: monitor alert contact channel fix
  containers/Monitor/views/commonalert/components/alert/form/index.vue
Labels: size/XS

#560 remove feature select from 3.7
  src/assets/images/features/monitor.svg
  src/assets/images/providers/lb.svg
  src/components/FeatureSelector/index.vue
  src/constants/feature.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/monitor, size/XL

#561 feat: update openeuler image icon
  src/components/ImageIcon/assets/openeuler.png
Labels: size/XS

#563 Automated cherry pick of #561: feat: update openeuler image icon
  src/components/ImageIcon/assets/openeuler.png
Labels: size/XS

#564 Automated cherry pick of #561: feat: update openeuler image icon
  src/components/ImageIcon/assets/openeuler.png
Labels: size/XS

#562 fix: refine baremetal nic list info and set up l2 wire logic
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/physicalmachine/dialogs/Setwire.vue
  containers/Compute/views/physicalmachine/sidepage/Detail.vue
  containers/Compute/views/physicalmachine/sidepage/Network.vue
  containers/Compute/views/physicalmachine/sidepage/index.vue
  src/utils/manager.js
Labels: size/L

#565 Automated cherry pick of #562: fix: refine baremetal nic list info and set up l2 wire logic
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/physicalmachine/dialogs/Setwire.vue
  containers/Compute/views/physicalmachine/sidepage/Detail.vue
  containers/Compute/views/physicalmachine/sidepage/Network.vue
  containers/Compute/views/physicalmachine/sidepage/index.vue
  src/utils/manager.js
Labels: size/L

#566 Automated cherry pick of #562: fix: refine baremetal nic list info and set up l2 wire logic
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/physicalmachine/dialogs/Setwire.vue
  containers/Compute/views/physicalmachine/sidepage/Detail.vue
  containers/Compute/views/physicalmachine/sidepage/Network.vue
  containers/Compute/views/physicalmachine/sidepage/index.vue
  src/utils/manager.js
Labels: size/L

#567 monitor overview card fix
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/sections/select/basic.vue
  containers/Monitor/locales/en.json
Labels: area/monitor, size/S

#568 alert history chart fix
  containers/Monitor/views/overview/components/index.vue
Labels: area/monitor, size/S

#569 Automated cherry pick of #568: alert history chart fix
  containers/Monitor/views/overview/components/index.vue
Labels: size/S

#570 忽略证书错误
  src/utils/http.js
Labels: area/dashboard, size/XS

#571 fix: dashboard public default config
  containers/Dashboard/views/dashboard/config/public-default.js
Labels: size/M

#572 Automated cherry pick of #571: fix: dashboard public default config
  containers/Dashboard/views/dashboard/config/public-default.js
Labels: size/M

#573 feat(constants): add exchange rate status in i18n
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#574 Automated cherry pick of #573: feat(constants): add exchange rate status in i18n
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#575 fix(Navbar): no project loading
  scope/layouts/Navbar/index.vue
Labels: size/S

#576 Automated cherry pick of #575: fix(Navbar): no project loading
  scope/layouts/Navbar/index.vue
Labels: size/S

#577 fix: menu i18n
  scope/layouts/Navbar/index.vue
Labels: size/XS

#578 Automated cherry pick of #577: fix: menu i18n
  scope/layouts/Navbar/index.vue
Labels: size/XS

#579 feat(cloudaccount): add account filter
  containers/Compute/views/vminstance/components/List.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
  containers/Network/views/lb/components/List.vue
  containers/Storage/views/bucket/components/List.vue
Labels: size/S

#580 Automated cherry pick of #579: feat(cloudaccount): add account filter
  containers/Compute/views/vminstance/components/List.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
  containers/Network/views/lb/components/List.vue
  containers/Storage/views/bucket/components/List.vue
Labels: size/S

#581 Bugfix/tb bugfix 0701301
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/sections/chart/histogram.vue
  containers/Monitor/views/overview/components/SummaryCards.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/compute, area/monitor, size/M

#582 Automated cherry pick of #581: host overview card fix
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/sections/chart/histogram.vue
  containers/Monitor/views/overview/components/SummaryCards.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#583 fix(bill): fix bill overview overflow tilte
  src/styles/less/global.less
Labels: size/XS

#584 Automated cherry pick of #583: fix(bill): fix bill overview overflow tilte
  src/styles/less/global.less
Labels: size/XS

#585 fix(db): fix db router hidden
  containers/DB/router/index.js
Labels: area/db, size/XS

#586 fix(db): modify db router hidden
  containers/DB/router/index.js
Labels: area/db, size/XS

#587 feat(dashboard): modify more to icon
  containers/Dashboard/extends/AlertsTrend/index.vue
  containers/Dashboard/extends/ConsumptionPercent/components/Brand.vue
  containers/Dashboard/extends/ConsumptionPercent/components/Resource.vue
  containers/Dashboard/extends/ConsumptionTrend/index.vue
  containers/Dashboard/extends/Log/index.vue
  containers/Dashboard/extends/Notify/index.vue
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsOverview/index.vue
  containers/Dashboard/extends/UnrecoveredAlarm/index.vue
  scope/assets/arrow-right.svg
Labels: area/dashboard, size/M

#588 feat: add bill global config
  src/store/modules/common.js
Labels: size/S

#589 Automated cherry pick of #588: feat: add bill global config
  src/store/modules/common.js
Labels: size/S

#590 fix: add qcloud tdsql
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds/constants/index.js
Labels: size/XS

#591 add notify topic page
  src/components/BaseSelect/OptionLabel.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/dashboard, size/S

#592 feat: add kafka
  containers/Middleware/README.md
  containers/Middleware/locales/en.json
  containers/Middleware/locales/zh-CN.json
  containers/Middleware/router/index.js
  containers/Middleware/views/README.md
  containers/Middleware/views/kafka/components/List.vue
  containers/Middleware/views/kafka/constants/index.js
  containers/Middleware/views/kafka/index.vue
  containers/Middleware/views/kafka/mixins/columns.js
  containers/Middleware/views/kafka/mixins/singleActions.js
  containers/Middleware/views/kafka/sidepage/Detail.vue
  containers/Middleware/views/kafka/sidepage/index.vue
  scope/assets/menu-middleware.svg
  scope/assets/res-kafka.svg
  src/components/Detail/index.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XL

#594 dictionary add jenkins
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/dashboard, size/XS

#595 Automated cherry pick of #594: dictionary add jenkins
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#597 Automated cherry pick of #596: fix(cloudenv): add success tip when account sync success
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: area/cloudenv, size/XS

#596 fix(cloudenv): add success tip when account sync success
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: area/cloudenv, size/XS

#598 fix(eslint): update eslint rule
  .eslintrc.js
Labels: size/XS

#599 Automated cherry pick of #598: fix(eslint): update eslint rule
  .eslintrc.js
Labels: size/XS

#600 Automated cherry pick of #598: fix(eslint): update eslint rule
  .eslintrc.js
Labels: size/XS

#606 fix(eslint): update eslint rule
  package.json
  src/components/BaseSelect/index.vue
  src/components/Edit/index.js
  src/components/ImageIcon/index.vue
  src/components/JsonSchemaForm/JComponents/JCloudregionList/JCloudregionList.vue
  src/components/JsonSchemaForm/JComponents/JSKUList/JSKUList.vue
  src/components/JsonSchemaForm/JComponents/JStorageBackendList/JStorageBackendList.vue
  src/components/PageCardList/HorizontalCard.vue
  src/components/PageCardList/VerticalCard.vue
  src/components/PageCardList/index.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/components/Table.vue
  src/components/Scrollbar/bar.js
  src/components/Scrollbar/index.js
  src/components/SearchBox/AutoCompleter.vue
  src/components/SearchBox/index.vue
  src/components/SidePageTrigger/index.vue
  src/directives/loading/index.js
  src/layouts/Default/index.vue
  src/locales/index.js
  src/permission.js
  src/sections/CloudregionZone/index.vue
  src/sections/DomainProject/index.vue
  src/sections/Monitor/index.vue
  src/sections/Navbar/index.vue
  src/sections/OneCloudMap/index.vue
  src/sections/ProductsList/index.vue
  src/utils/common/detailColumn.js
  src/utils/theme/utils.js
  src/views/workflow/all-process/components/List.vue
  src/views/workflow/all-process/mixins/columns.js
  src/views/workflow/all-process/sidepage/index.vue
  src/views/workflow/approval-start/components/List.vue
  src/views/workflow/approval-start/dialogs/EndDialog.vue
  src/views/workflow/approval-start/dialogs/FeedbackDialog.vue
  src/views/workflow/approval-start/dialogs/HandingDialog.vue
  src/views/workflow/approval-start/dialogs/PassDialog.vue
  src/views/workflow/approval-start/dialogs/RejectDialog.vue
  src/views/workflow/approval-start/mixins/columns.js
  src/views/workflow/approval-start/sidepage/index.vue
  src/views/workflow/approved-done/components/List.vue
  src/views/workflow/approved-done/mixins/columns.js
  src/views/workflow/approved-done/sidepage/index.vue
  src/views/workflow/components/ProcessHistory.vue
  src/views/workflow/components/ServerConfig.vue
  src/views/workflow/me-partake/components/List.vue
  src/views/workflow/me-partake/mixins/columns.js
  src/views/workflow/me-partake/sidepage/index.vue
  src/views/workflow/me-process/components/List.vue
  src/views/workflow/me-process/mixins/columns.js
  src/views/workflow/me-process/sidepage/index.vue
  src/views/workflow/mixins/domainQuota.js
  src/views/workflow/mixins/price.js
  src/views/workflow/mixins/projectQuota.js
  src/views/workflow/mixins/serverConf.js
  src/views/workflow/third-process/components/List.vue
  src/views/workflow/third-process/mixins/columns.js
  src/views/workflow/third-process/sidepage/Detail.vue
  src/views/workflow/third-process/sidepage/index.vue
Labels: size/L

#604 add link for top5
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/extends/NumberCard/index.vue
  containers/Dashboard/extends/Top5/index.vue
  scope/assets/arrow-right.svg
Labels: area/dashboard, size/S

#605 feat: add elastic search
  containers/Middleware/locales/en.json
  containers/Middleware/locales/zh-CN.json
  containers/Middleware/router/index.js
  containers/Middleware/views/elasticsearch/components/List.vue
  containers/Middleware/views/elasticsearch/constants/index.js
  containers/Middleware/views/elasticsearch/index.vue
  containers/Middleware/views/elasticsearch/mixins/columns.js
  containers/Middleware/views/elasticsearch/mixins/singleActions.js
  containers/Middleware/views/elasticsearch/sidepage/Detail.vue
  containers/Middleware/views/elasticsearch/sidepage/index.vue
  scope/assets/res-elasticsearch.svg
  src/components/Detail/index.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XL

#607 optimized: middleware
  containers/Middleware/locales/en.json
  containers/Middleware/locales/zh-CN.json
  containers/Middleware/views/elasticsearch/components/List.vue
  containers/Middleware/views/kafka/components/List.vue
  containers/Middleware/views/kafka/mixins/columns.js
  src/locales/en.json
Labels: size/L

#608 fix: hidden bill in public
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#609 Automated cherry pick of #608: fix: hidden bill in public
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#610 Automated cherry pick of #608: fix: hidden bill in public
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#611 fix: eslint rule
  .eslintrc.js
Labels: size/XS

#612 Automated cherry pick of #611: fix: eslint rule
  .eslintrc.js
Labels: size/XS

#613 Automated cherry pick of #611: fix: eslint rule
  .eslintrc.js
Labels: size/XS

#614 Automated cherry pick of #593: feat(BaseDialog): add dialog drag
  src/components/BaseDialog/index.vue
  src/directives/drag.js
Labels: size/M

#615 fix(db): fix can't show network when dependent parameters are updated
  src/sections/NetworkSelects/index.js
Labels: area/db, size/S

#616 Automated cherry pick of #615: fix(db): fix can't show network when dependent parameters are updated (rds-create)
  src/sections/NetworkSelects/index.js
Labels: size/S

#617 fix: support replaceAll for lower broswer
  src/main.js
  src/utils/polyfill/index.js
Labels: size/XS

#618 Automated cherry pick of #617: fix: support replaceAll for lower broswer
  src/main.js
  src/utils/polyfill/index.js
Labels: size/XS

#619 Automated cherry pick of #617: fix: support replaceAll for lower broswer
  src/main.js
  src/utils/polyfill/index.js
Labels: size/XS

#620 Bugfix/tb bugfix navbar 071901
  src/config/vue.config.js
  src/sections/Navbar/index.vue
Labels: area/dashboard, size/S

#621 disable google translator
  public/index.html
Labels: area/dashboard, size/XS

#622 Automated cherry pick of #621: disable google translator
  public/index.html
Labels: size/XS

#623 feat(compute): support modify disk driver and cache mode
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/dialogs/DriverUpdateDialog.vue
  containers/Compute/views/disk/mixins/singleActions.js
  src/utils/manager.js
Labels: area/compute, size/L

#624 fix vue.config.js path errror
  src/config/vue.config.js
Labels: area/dashboard, size/XS

#625 feat: 二次定价支持对账单类型进行限制
  src/store/modules/common.js
Labels: size/XS

#627 feat: add back index time
  src/views/exception/403.vue
  src/views/exception/404.vue
  src/views/exception/500.vue
Labels: size/M

#628 Automated cherry pick of #627: feat: add back index time
  src/views/exception/403.vue
  src/views/exception/404.vue
  src/views/exception/500.vue
Labels: size/M

#626 fix(network): fix waf show text
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/waf/components/List.vue
  containers/Network/views/waf/components/WafRuleStatement.vue
  containers/Network/views/waf/components/statementComponents/MatchField.vue
  containers/Network/views/waf/components/statementComponents/Negation.vue
  containers/Network/views/waf/components/statementComponents/Operator.vue
  containers/Network/views/waf/components/statementList/GeoMatch.vue
  containers/Network/views/waf/components/statementList/RegexSet.vue
  containers/Network/views/waf/index.vue
  containers/Network/views/waf/sidepage/Detail.vue
  containers/Network/views/waf/sidepage/ResourceManage.vue
  containers/Network/views/waf/sidepage/RuleManage.vue
  containers/Network/views/waf/sidepage/index.vue
  src/locales/zh-CN.json
Labels: area/network, size/L

#629 Feat/glb r 3.8 waf
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/waf/components/statementList/ByteMatch.vue
  containers/Network/views/waf/components/statementList/GeoMatch.vue
  containers/Network/views/waf/components/statementList/IPSet.vue
  containers/Network/views/waf/components/statementList/LabelMatch.vue
  containers/Network/views/waf/components/statementList/Rate.vue
  containers/Network/views/waf/components/statementList/RegexSet.vue
  containers/Network/views/waf/components/statementList/Size.vue
  containers/Network/views/waf/components/statementList/SqliMatch.vue
  containers/Network/views/waf/components/statementList/XssMatch.vue
  containers/Network/views/waf/mixins/waf.js
  containers/Network/views/waf/sidepage/ResourceManage.vue
Labels: area/network, size/M

#631 fix fixed time in 403 page
  src/views/exception/403.vue
  src/views/exception/404.vue
  src/views/exception/500.vue
Labels: size/S

#632 Automated cherry pick of #631: 修复错误页因未跳转出现倒计时负数问题
  src/views/exception/403.vue
  src/views/exception/404.vue
  src/views/exception/500.vue
Labels: size/S

#633 添加定时器清除,修改跳转地址
  src/views/exception/403.vue
  src/views/exception/404.vue
  src/views/exception/500.vue
  src/views/exception/components/AutoRouterLink.vue
Labels: size/L

#634 Automated cherry pick of #633: 添加定时器清除,修改跳转地址
  src/views/exception/403.vue
  src/views/exception/404.vue
  src/views/exception/500.vue
  src/views/exception/components/AutoRouterLink.vue
Labels: size/L

#635 fix: storage providers missing generic S3 providers
  containers/Storage/views/blockstorage/components/List.vue
Labels: size/XS

#636 Automated cherry pick of #635: fix: storage providers missing generic S3 providers
  containers/Storage/views/blockstorage/components/List.vue
Labels: size/XS

#637 feat: add cloudpods
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  scope/assets/cloudpods.svg
  scope/locales/zh-CN.json
  src/assets/images/providers/cloudpods.svg
  src/components/Icon/assets/cloudpods.svg
  src/constants/index.js
  src/utils/common/hypervisor.js
Labels: size/XXL

#638 feat(cloudenv): cloudprovider support delete
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudprovider/components/List.vue
  containers/Cloudenv/views/cloudprovider/mixins/singleActions.js
Labels: area/cloudenv, size/M

#639 Automated cherry pick of #638: feat(cloudenv): cloudprovider support delete
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudprovider/components/List.vue
  containers/Cloudenv/views/cloudprovider/mixins/singleActions.js
Labels: area/cloudenv, size/M

#640 fix: remove debug info
  src/utils/common/hypervisor.js
Labels: size/XS

#641 fix: add cloudpods guide
  src/constants/feature.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#642 fix: 配额开关打开，域和项目详情页仍然没有配额信息
  src/store/modules/common.js
Labels: size/S

#643 Automated cherry pick of #642: fix: 配额开关打开，域和项目详情页仍然没有配额信息
  src/store/modules/common.js
Labels: size/S

#647 Automated cherry pick of #646: feat: 优化下拉选择框在内容过多时无法有效查看信息
  src/components/SearchBox/AutoCompleter.vue
Labels: size/XS

#644 fix currency params in dashboard
  containers/Dashboard/extends/ConsumptionPercent/components/Brand.vue
  containers/Dashboard/extends/ConsumptionPercent/components/Resource.vue
  containers/Dashboard/extends/ConsumptionTrend/index.vue
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsOverview/index.vue
  containers/Dashboard/sections/ConsumptionConfig/index.vue
  src/constants/index.js
  src/store/modules/common.js
Labels: area/dashboard, size/L

#645 Automated cherry pick of #644: 修复多币种对控制面板的影响
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsOverview/index.vue
  src/constants/index.js
  src/store/modules/common.js
Labels: area/dashboard, size/M

#648 云订阅启用禁用添加弹框提示
  containers/Cloudenv/views/cloudprovider/components/List.vue
  containers/Cloudenv/views/cloudprovider/mixins/singleActions.js
Labels: area/cloudenv, size/L

#649 Automated cherry pick of #648: 云订阅启用禁用添加弹框提示
  containers/Cloudenv/views/cloudprovider/components/List.vue
  containers/Cloudenv/views/cloudprovider/mixins/singleActions.js
Labels: area/cloudenv, size/L

#650 fix: 管理后台登录时，相应项目寻找失败
  src/sections/Navbar/index.vue
Labels: size/M

#651 Automated cherry pick of #650: fix: 管理后台登录时，相应项目寻找失败
  src/sections/Navbar/index.vue
Labels: size/M

#652 Automated cherry pick of #650: fix: 管理后台登录时，相应项目寻找失败
  src/sections/Navbar/index.vue
Labels: size/M

#653 fix cloudprovider delete tip
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudprovider/components/List.vue
  containers/Cloudenv/views/cloudprovider/mixins/singleActions.js
Labels: area/cloudenv, size/M

#654 Automated cherry pick of #653: 修改云订阅删除验证顺序及提示文案
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudprovider/components/List.vue
  containers/Cloudenv/views/cloudprovider/mixins/singleActions.js
Labels: size/M

#655 fix(dashboard): fix global search pagenation
  src/views/global-search-result/index.vue
Labels: area/dashboard, size/XS

#656 Automated cherry pick of #655: fix(dashboard): fix global search pagenation
  src/views/global-search-result/index.vue
Labels: size/XS

#657 Automated cherry pick of #655: fix(dashboard): fix global search pagenation
  src/views/global-search-result/index.vue
Labels: size/XS

#658 feat: update nav projects
  src/sections/Navbar/index.vue
Labels: size/M

#659 Automated cherry pick of #658: feat: update nav projects
  src/sections/Navbar/index.vue
Labels: size/M

#660 Automated cherry pick of #658: feat: update nav projects
  src/sections/Navbar/index.vue
Labels: size/M

#661 fix: cloudshell UE improvements
  src/components/OcTerm/index.vue
Labels: size/L

#662 Automated cherry pick of #661: fix: cloudShell UE improvements
  src/components/OcTerm/index.vue
Labels: size/L

#663 fix: xterm fit
  src/components/OcTerm/index.vue
Labels: size/S

#668 Feature/mj r master 3223
  containers/Compute/views/baremetal/index.vue
  containers/Compute/views/host/index.vue
Labels: size/L

#666 fix(cloudenv): cloudgroup list add domain filter
  containers/Cloudenv/views/cloudaccount/sidepage/index.vue
Labels: area/cloudenv, size/XS

#667 Automated cherry pick of #666: fix(cloudenv): cloudgroup list add domain filter
  containers/Cloudenv/views/cloudaccount/sidepage/index.vue
Labels: area/cloudenv, size/XS

#669 cloudshell fix
  scope/layouts/Navbar/index.vue
  src/sections/Navbar/index.vue
Labels: area/dashboard, size/XS

#670 Automated cherry pick of #669: cloudshell fix
  scope/layouts/Navbar/index.vue
  src/sections/Navbar/index.vue
Labels: size/XS

#671 fix: vpc创建参数修复，及速度优化
  containers/Network/views/vpc/create/index.vue
Labels: size/S

#672 Automated cherry pick of #671: fix: vpc创建参数修复，及速度优化
  containers/Network/views/vpc/create/index.vue
Labels: size/S

#673 feat: support ext tag control
  src/components/PageList/TagFilter.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/sections/TagSelect/index.vue
Labels: size/S

#674 Automated cherry pick of #673: feat: support ext tag control
  src/components/PageList/TagFilter.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/sections/TagSelect/index.vue
Labels: size/S

#679 Feature/mj r master 2975
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/router/index.js
  containers/Compute/views/webapp/components/List.vue
  containers/Compute/views/webapp/constants/index.js
  containers/Compute/views/webapp/index.vue
  containers/Compute/views/webapp/mixins/columns.js
  containers/Compute/views/webapp/mixins/singleActions.js
  containers/Compute/views/webapp/sidepage/Detail.vue
  containers/Compute/views/webapp/sidepage/EnvironmentsList.vue
  containers/Compute/views/webapp/sidepage/index.vue
  containers/Compute/views/webapp/utils/columns.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#675 fix: optimized distinct filed filter
  src/utils/list.js
Labels: size/S

#676 Automated cherry pick of #675: fix: optimized distinct filed filter
  src/utils/list.js
Labels: size/S

#677 Automated cherry pick of #675: fix: optimized distinct filed filter
  src/utils/list.js
Labels: size/S

#678 Automated cherry pick of #675: fix: optimized distinct filed filter
  src/utils/list.js
Labels: size/S
