Repository yunionio/dashboard, pull requests merged in 2021-04, with the labels that each got.

#29 fix(compute): 修复功能选择vmware，没有显示主机快照菜单
  containers/Compute/router/index.js
Labels: approved, lgtm

#30 Automated cherry pick of #29: fix(compute): 修复功能选择vmware，没有显示主机快照菜单
  containers/Compute/router/index.js
Labels: approved, lgtm

#32 Automated cherry pick of #29: fix(compute): 修复功能选择vmware，没有显示主机快照菜单
  containers/Compute/router/index.js
Labels: approved, lgtm

#31 Automated cherry pick of #29: fix(compute): 修复功能选择vmware，没有显示主机快照菜单
  containers/Compute/router/index.js
Labels: approved, lgtm

#33 feature(cumpute): add cumpute vminstance filter
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
Labels: approved, area/compute, lgtm, size/M

#34 feature(clouduser): add Cloud Account in SamluserList
  src/views/clouduser/components/SamluserList.vue
Labels: approved, lgtm, size/XS

#36 Automated cherry pick of #33: feature(cumpute): add cumpute vminstance filter
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/M

#37 Automated cherry pick of #34: feature(clouduser): add Cloud Account in SamluserList
  src/views/clouduser/components/SamluserList.vue
Labels: size/XS

#38 Automated cherry pick of #34: feature(clouduser): add Cloud Account in SamluserList
  src/views/clouduser/components/SamluserList.vue
Labels: size/XS

#39 fix(host): 宿主机详情的type签应该不变
  containers/Compute/views/host/mixins/columns.js
Labels: approved, size/XS

#40 Automated cherry pick of #39: fix(host): 宿主机详情的type签应该不变
  containers/Compute/views/host/mixins/columns.js
Labels: approved, size/XS

#41 Automated cherry pick of #39: fix(host): 宿主机详情的type签应该不变
  containers/Compute/views/host/mixins/columns.js
Labels: approved, size/XS

#42 Automated cherry pick of #39: fix(host): 宿主机详情的type签应该不变
  containers/Compute/views/host/mixins/columns.js
Labels: approved, size/XS

#43 fix(compute): os select backfill
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
Labels: approved, size/S

#44 Automated cherry pick of #43: fix(compute): os select backfill
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
Labels: approved, size/S

#45 Automated cherry pick of #43: fix(compute): os select backfill
  containers/Compute/sections/OsSelect/index.vue
Labels: approved, size/S

#46 Automated cherry pick of #43: fix(compute): os select backfill
  containers/Compute/sections/OsSelect/index.vue
Labels: approved, size/S

#47 bugfix(vminstance): modify Cumpute vminstance label
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/compute, size/S

#48 Automated cherry pick of #47: bugfix(vminstance): modify Cumpute vminstance label
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#54 feat(TagSelect): #3087 标签的复杂搜索，支持contains, startswith, endswith, not
  src/sections/TagSelect/index.vue
Labels: approved, size/M

#49 fix(compute): transfer i18n
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#50 Automated cherry pick of #49: fix(compute): transfer i18n
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#51 feature(host): add host vm sortable
  containers/Compute/views/host/mixins/columns.js
Labels: size/XS

#52 Automated cherry pick of #51: feature(host): add host vm sortable
  containers/Compute/views/host/mixins/columns.js
Labels: size/XS

#53 fix: enable saml auth for 3.5
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: size/M

#55 Automated cherry pick of #54: feat(TagSelect): #3087 标签的复杂搜索，支持contains, startswith, endswith, not
  src/sections/TagSelect/index.vue
Labels: approved, size/M

#56 fix(OsSelect): #7261 创建vmware虚拟机时，vmware平台镜像vm-test应该归属于RHEL，不应该归属于linux
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: approved, size/XS

#59 fix(OsSelect): #7274 从ISO启动的windows系统vmware虚拟机重装系统选择windows系统时无法选中，前端报错
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
Labels: size/XS

#57 Automated cherry pick of #56: fix(OsSelect): #7261 创建vmware虚拟机时，vmware平台镜像vm-test应该归属于RHEL，不应该归属于linux
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: approved, size/XS

#58 Automated cherry pick of #56: fix(OsSelect): #7261 创建vmware虚拟机时，vmware平台镜像vm-test应该归属于RHEL，不应该归属于linux
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: approved, size/XS

#60 Automated cherry pick of #59: fix(OsSelect): #7274 从ISO启动的windows系统vmware虚拟机重装系统选择windows系统时无法选中，前端报错
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
Labels: approved, size/XS

#61 fix(Network): #7264 1366*768分辨率（14寸）创建VPC页面样式显示不全
  containers/Network/views/vpc/create/index.vue
Labels: approved, size/M

#62 Automated cherry pick of #61: fix(Network): #7264 1366*768分辨率（14寸）创建VPC页面样式显示不全
  containers/Network/views/vpc/create/index.vue
Labels: approved, size/M

#65 feature(dashboard): add dashboard metric url
  containers/Dashboard/constants/index.js
  containers/Dashboard/extends/Quota/index.vue
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/sections/K8sConfig/index.vue
  containers/Dashboard/sections/ProjectQuotaConfig/index.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: area/dashboard, size/L

#66 Automated cherry pick of #65: feature(dashboard): add dashboard metric url
  containers/Dashboard/constants/index.js
  containers/Dashboard/extends/Quota/index.vue
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/sections/K8sConfig/index.vue
  containers/Dashboard/sections/ProjectQuotaConfig/index.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/L

#63 support ssh proxy
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants.js
  containers/Compute/views/vminstance/create/form/SetupSSHForm.vue
  containers/Compute/views/vminstance/dialogs/DetectSSH.vue
  containers/Compute/views/vminstance/dialogs/InstallAgent.vue
  containers/Compute/views/vminstance/dialogs/SetupSSH.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/ssh-agent/components/List.vue
  containers/Network/views/ssh-agent/index.vue
  containers/Network/views/ssh-agent/mixins/columns.js
  containers/Network/views/ssh-agent/mixins/singleActions.js
  containers/Network/views/ssh-agent/sidepage/Detail.vue
  containers/Network/views/ssh-agent/sidepage/index.vue
  containers/Network/views/ssh-proxy-match/components/List.vue
  containers/Network/views/ssh-proxy-match/dialogs/link.vue
  containers/Network/views/ssh-proxy-match/index.vue
  containers/Network/views/ssh-proxy-match/mixins/columns.js
  containers/Network/views/ssh-proxy-match/mixins/singleActions.js
  containers/Network/views/ssh-proxy-match/sidepage/Detail.vue
  containers/Network/views/ssh-proxy-match/sidepage/index.vue
  containers/Network/views/ssh-proxy/components/List.vue
  containers/Network/views/ssh-proxy/form/index.vue
  containers/Network/views/ssh-proxy/index.vue
  containers/Network/views/ssh-proxy/mixins/columns.js
  containers/Network/views/ssh-proxy/mixins/singleActions.js
  containers/Network/views/ssh-proxy/sidepage/Detail.vue
  containers/Network/views/ssh-proxy/sidepage/Scope.vue
  containers/Network/views/ssh-proxy/sidepage/index.vue
  src/components/DialogTable/index.vue
  src/constants/expectStatus.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/AreaSelects/index.js
  src/utils/common/tableFilter.js
Labels: approved, area/dashboard, size/XXL

#64 Automated cherry pick of #63: support ssh proxy
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants.js
  containers/Compute/views/vminstance/create/form/SetupSSHForm.vue
  containers/Compute/views/vminstance/dialogs/DetectSSH.vue
  containers/Compute/views/vminstance/dialogs/InstallAgent.vue
  containers/Compute/views/vminstance/dialogs/SetupSSH.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/ssh-agent/components/List.vue
  containers/Network/views/ssh-agent/index.vue
  containers/Network/views/ssh-agent/mixins/columns.js
  containers/Network/views/ssh-agent/mixins/singleActions.js
  containers/Network/views/ssh-agent/sidepage/Detail.vue
  containers/Network/views/ssh-agent/sidepage/index.vue
  containers/Network/views/ssh-proxy-match/components/List.vue
  containers/Network/views/ssh-proxy-match/dialogs/link.vue
  containers/Network/views/ssh-proxy-match/index.vue
  containers/Network/views/ssh-proxy-match/mixins/columns.js
  containers/Network/views/ssh-proxy-match/mixins/singleActions.js
  containers/Network/views/ssh-proxy-match/sidepage/Detail.vue
  containers/Network/views/ssh-proxy-match/sidepage/index.vue
  containers/Network/views/ssh-proxy/components/List.vue
  containers/Network/views/ssh-proxy/form/index.vue
  containers/Network/views/ssh-proxy/index.vue
  containers/Network/views/ssh-proxy/mixins/columns.js
  containers/Network/views/ssh-proxy/mixins/singleActions.js
  containers/Network/views/ssh-proxy/sidepage/Detail.vue
  containers/Network/views/ssh-proxy/sidepage/Scope.vue
  containers/Network/views/ssh-proxy/sidepage/index.vue
  src/components/DialogTable/index.vue
  src/constants/expectStatus.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/AreaSelects/index.js
  src/utils/common/tableFilter.js
Labels: approved, size/XXL

#67 bugfix(compute): restore arch column
  containers/Compute/views/vminstance/mixins/columns.js
Labels: area/compute, size/XS

#68 Automated cherry pick of #67: bugfix(compute): restore arch column
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#69 fix(dashboard): env,brand,region remove default value
  containers/Dashboard/extends/Ring/components/Server.vue
Labels: approved, size/XS

#70 Automated cherry pick of #69: fix(dashboard): env,brand,region remove default value
  containers/Dashboard/extends/Ring/components/Server.vue
Labels: approved, size/XS

#73 Bugfix/tb bugfix 042501
  containers/Monitor/router/index.js
  containers/Monitor/sections/ExplorerForm/form.vue
Labels: approved, size/XS

#71 feature(bill): add budget tags
  src/utils/common/detailColumn.js
Labels: size/XS

#72 Automated cherry pick of #71: feature(bill): add budget tags
  src/utils/common/detailColumn.js
Labels: size/XS

#74 Automated cherry pick of #73: hidden monitor dashboard fix
  containers/Monitor/router/index.js
  containers/Monitor/sections/ExplorerForm/form.vue
Labels: approved, size/XS

#75 fix(compute): no use network fill error
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  src/components/BaseSelect/index.vue
Labels: approved, size/S

#76 Automated cherry pick of #75: fix(compute): no use network fill error
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  src/components/BaseSelect/index.vue
Labels: approved, size/S

#77 Automated cherry pick of #75: fix(compute): no use network fill error
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  src/components/BaseSelect/index.vue
Labels: approved, size/S

#78 Automated cherry pick of #75: fix(compute): no use network fill error
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  src/components/BaseSelect/index.vue
Labels: approved, size/S

#79 feature(compute): fix compute datadisk type
  containers/Compute/sections/DataDisk/index.vue
Labels: area/compute, size/XS

#80 Automated cherry pick of #79: feature(compute): fix compute datadisk type
  containers/Compute/sections/DataDisk/index.vue
Labels: size/XS

#81 feat(bill): add suggestion i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: approved, size/S

#82 Automated cherry pick of #81: feat(bill): add suggestion i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: approved, size/S

#83 bugfix(compute): fix osselect imageselect
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
Labels: area/compute, size/S

#84 Automated cherry pick of #83: bugfix(compute): fix osselect imageselect
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
Labels: size/S

#85 Bugfix/tb bugfix 042502
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/ssh-proxy-match/components/List.vue
  containers/Network/views/ssh-proxy-match/mixins/columns.js
  containers/Network/views/ssh-proxy/components/List.vue
  containers/Network/views/ssh-proxy/form/index.vue
Labels: approved, area/dashboard, size/M

#86 Automated cherry pick of #85: add ssh proxy batch delete
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/ssh-proxy-match/components/List.vue
  containers/Network/views/ssh-proxy-match/mixins/columns.js
  containers/Network/views/ssh-proxy/components/List.vue
  containers/Network/views/ssh-proxy/form/index.vue
Labels: approved, size/M

#87 fix(compute): 网络切换到自动调度后弹性公网IP使用默认，不支持新建
  containers/Compute/sections/ServerNetwork/index.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: approved, size/XS

#88 Automated cherry pick of #87: fix(compute): 网络切换到自动调度后弹性公网IP使用默认，不支持新建
  containers/Compute/sections/ServerNetwork/index.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: approved, size/XS

#89 Automated cherry pick of #87: fix(compute): 网络切换到自动调度后弹性公网IP使用默认，不支持新建
  containers/Compute/sections/ServerNetwork/index.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: approved, size/XS

#90 fix(workflow): 工单走到系统管理员，待我审批中当前环节错误
  src/views/workflow/approval-start/mixins/columns.js
Labels: size/XS

#91 Automated cherry pick of #90: fix(workflow): 工单走到系统管理员，待我审批中当前环节错误
  src/views/workflow/approval-start/mixins/columns.js
Labels: size/XS

#92 fix(workflow): 通过主机工单创建虚拟机失败，工单详情中缺少查看失败原因的链接
  src/views/workflow/components/ProcessHistory.vue
Labels: approved, size/XS

#93 Automated cherry pick of #92: fix(workflow): 通过主机工单创建虚拟机失败，工单详情中缺少查看失败原因的链接
  src/views/workflow/components/ProcessHistory.vue
Labels: approved

#94 feature(system): add project instance snapshots
  src/utils/common/tableColumn.js
Labels: size/S

#95 Automated cherry pick of #94: feature(system): add project instance snapshots
  src/utils/common/tableColumn.js
Labels: size/S

#96 Automated cherry pick of #94: feature(system): add project instance snapshots
  src/utils/common/tableColumn.js
Labels: size/S

#110 feat(suggestion): update i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: approved, size/XS

#97 Bugfix/tb bugfix 042601
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Monitor/views/commonalert/components/alert/form/index.vue
  containers/Network/views/ssh-proxy-match/components/List.vue
  containers/Network/views/ssh-proxy/form/index.vue
  src/sections/DomainProject/index.vue
Labels: approved, area/dashboard, size/M

#98 Automated cherry pick of #97: ssh proxy bugfix
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Monitor/views/commonalert/components/alert/form/index.vue
  containers/Network/views/ssh-proxy-match/components/List.vue
  containers/Network/views/ssh-proxy/form/index.vue
  src/sections/DomainProject/index.vue
Labels: approved, size/M

#99 feature(cloudenv): config router
  containers/Cloudenv/router/index.js
Labels: area/cloudenv, size/M

#100 feat(meter): add bucket not found warning to cloudaccount
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/BillFileIndex.vue
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
Labels: area/dashboard, size/M

#101 Automated cherry pick of #99: feature(cloudenv): config router
  containers/Cloudenv/router/index.js
Labels: size/M

#102 Automated cherry pick of #100: add bucket not found warning to cloudaccount
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/BillFileIndex.vue
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
Labels: size/M

#103 fix: misc fixed for cloudbox
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Network/views/network/Create.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Auth/AdminRegister.vue
  src/sections/Navbar/index.vue
Labels: approved, size/M

#104 Automated cherry pick of #103: fix: misc fixed for cloudbox
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Network/views/network/Create.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Auth/AdminRegister.vue
  src/sections/Navbar/index.vue
Labels: approved, size/M

#105 Automated cherry pick of #103: fix: misc fixed for cloudbox
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Network/views/network/Create.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Auth/AdminRegister.vue
  src/sections/Navbar/index.vue
Labels: approved, size/M

#106 feature(scope): fix feishu verify
  src/views/user-info/dialogs/VerifyFeishuDialog.vue
Labels: size/S

#107 Automated cherry pick of #106: feature(scope): fix feishu verify
  src/views/user-info/dialogs/VerifyFeishuDialog.vue
Labels: size/S

#108 bugfix(compute): close vminstance filter(vmem_size & disk)
  containers/Compute/views/vminstance/components/List.vue
Labels: area/compute, size/S

#109 Automated cherry pick of #108: bugfix(compute): close vminstance filter(vmem_size & disk)
  containers/Compute/views/vminstance/components/List.vue
Labels: size/S

#111 Automated cherry pick of #110: feat(suggestion): update i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: approved, size/XS

#112 fix: access group details
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/access-group/sidepage/Detail.vue
Labels: size/S

#113 Automated cherry pick of #112: fix: access group details
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/access-group/sidepage/Detail.vue
Labels: size/S

#114 bugfix(navbar): change notifyPopover visiable
  src/sections/Navbar/components/NotifyPopover.vue
Labels: size/XS

#115 Automated cherry pick of #114: bugfix(navbar): change notifyPopover visiable
  src/sections/Navbar/components/NotifyPopover.vue
Labels: size/XS

#116 fix: format gb for nas capacity
  containers/Storage/views/file-system/create/index.vue
Labels: area/storage, size/XS

#117 Automated cherry pick of #116: fix: format gb for nas capacity
  containers/Storage/views/file-system/create/index.vue
Labels: size/XS

#118 Bugfix/tb bugfix 042701
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/SKU/index.vue
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/vminstance/create/form/SetupSSHForm.vue
  containers/Monitor/components/MonitorCard/sections/select/scope.vue
  containers/Monitor/sections/Metric/index.vue
  containers/Monitor/views/explorer/dialogs/create.vue
Labels: area/dashboard, size/M

#119 Automated cherry pick of #118: monitor dashboard domain select style fix
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/SKU/index.vue
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/vminstance/create/form/SetupSSHForm.vue
  containers/Monitor/components/MonitorCard/sections/select/scope.vue
  containers/Monitor/sections/Metric/index.vue
  containers/Monitor/views/explorer/dialogs/create.vue
Labels: size/M

#120 fix(iam): change security optimization to security inspection
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/dashboard, size/XS

#121 Automated cherry pick of #120: change security optimization to security inspection
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#122 feat(cloudenv,monitor): update receivers params for domain mode
  containers/Cloudenv/views/clouduser/components/UserSelect.vue
  containers/Monitor/views/commonalert/components/alert/form/index.vue
Labels: size/S

#123 Automated cherry pick of #122: feat(cloudenv,monitor): update receivers params for domain mode
  containers/Cloudenv/views/clouduser/components/UserSelect.vue
  containers/Monitor/views/commonalert/components/alert/form/index.vue
Labels: size/S

#125 windows not support install agent
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
Labels: area/dashboard, size/M

#126 Automated cherry pick of #125: windows not support install agent
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
Labels: size/M

#127 feat(compute, network): add action permission
  containers/Compute/views/image/mixins/singleActions.js
  containers/Compute/views/instance-group/mixins/singleActions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Network/views/eip/mixins/singleActions.js
  src/constants/permission.js
Labels: size/S

#128 Automated cherry pick of #127: feat(compute, network): add action permission
  containers/Compute/views/image/mixins/singleActions.js
  containers/Compute/views/instance-group/mixins/singleActions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Network/views/eip/mixins/singleActions.js
  src/constants/permission.js
Labels: size/S

#130 Automated cherry pick of #127: feat(compute, network): add action permission
  containers/Compute/views/image/mixins/singleActions.js
  containers/Compute/views/instance-group/mixins/singleActions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Network/views/eip/mixins/singleActions.js
  src/constants/permission.js
Labels: size/S

#131 update help link
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Monitor.vue
Labels: area/dashboard, size/XS

#132 Automated cherry pick of #131: update help link
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Monitor.vue
Labels: size/XS

#133 server-price-comparator capability fix
  containers/Cloudenv/views/server-price-comparator/create/form/IDC.vue
  containers/Cloudenv/views/server-price-comparator/create/form/Private.vue
  containers/Cloudenv/views/server-price-comparator/create/form/Public.vue
Labels: area/dashboard, size/XS

#134 Automated cherry pick of #133: server-price-comparator capability fix
  containers/Cloudenv/views/server-price-comparator/create/form/IDC.vue
  containers/Cloudenv/views/server-price-comparator/create/form/Private.vue
  containers/Cloudenv/views/server-price-comparator/create/form/Public.vue
Labels: size/XS

#135 install agent form i18n fix
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
Labels: area/dashboard, size/XS

#136 Automated cherry pick of #135: install agent form i18n fix
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
Labels: size/XS

#138 Automated cherry pick of #137: feature(scope): config menu list
  src/components/Icon/assets/menu-suggest.svg
Labels: size/XS

#137 feature(scope): config menu list
  src/components/Icon/assets/menu-suggest.svg
Labels: size/XS

#139 Bugfix/tb bugfix 042901
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  src/constants/globalSearch.js
  src/views/global-search-result/index.vue
Labels: area/dashboard, size/M

#140 Automated cherry pick of #139: setup altert for monitor charts fix
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  src/constants/globalSearch.js
  src/views/global-search-result/index.vue
Labels: size/M

#141 global search hidden menus fix
  src/constants/globalSearch.js
  src/views/global-search-result/index.vue
Labels: area/dashboard, size/M

#142 修改图标
  src/components/Icon/assets/menu-suggest.svg
Labels: size/XS

#143 Automated cherry pick of #142: 修改图标
  src/components/Icon/assets/menu-suggest.svg
Labels: size/XS

#145 Automated cherry pick of #144: 修改成本优化英文
  containers/Cloudenv/locales/en.json
Labels: size/XS

#144 修改成本优化英文
  containers/Cloudenv/locales/en.json
Labels: size/XS

#146 feat(cloudenv,monitor): update receivers params for domain mode
  containers/Cloudenv/views/clouduser/components/UserSelect.vue
  containers/Monitor/views/commonalert/components/alert/form/index.vue
Labels: size/XS

#147 Automated cherry pick of #146: feat(cloudenv,monitor): update receivers params for domain mode
  containers/Cloudenv/views/clouduser/components/UserSelect.vue
  containers/Monitor/views/commonalert/components/alert/form/index.vue
Labels: size/XS

#148 instance price comparator fix
  containers/Cloudenv/views/server-price-comparator/create/form/IDC.vue
  containers/Cloudenv/views/server-price-comparator/create/form/Private.vue
Labels: area/dashboard, size/XS

#149 Automated cherry pick of #148: instance price comparator fix
  containers/Cloudenv/views/server-price-comparator/create/form/IDC.vue
  containers/Cloudenv/views/server-price-comparator/create/form/Private.vue
Labels: size/XS

#152 fix(cloudenv): update scope params
  containers/Cloudenv/views/clouduser/components/UserSelect.vue
Labels: size/XS

#153 Automated cherry pick of #152: fix(cloudenv): update scope params
  containers/Cloudenv/views/clouduser/components/UserSelect.vue
Labels: size/XS

#150 public cloud image filter add os_arch
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: area/dashboard, size/M

#154 hidden common alert tips while scope is projct
  containers/Monitor/views/commonalert/components/alert/form/index.vue
Labels: area/dashboard, size/XS

#155 Automated cherry pick of #154: hidden common alert tips while scope is projct
  containers/Monitor/views/commonalert/components/alert/form/index.vue
Labels: size/XS
