Repository yunionio/dashboard, pull requests merged in 2021-05, with the labels that each got.

#157 Automated cherry pick of #156: domain project select fix
  src/sections/DomainProject/index.vue
Labels: approved, lgtm, size/XS

#156 domain project select fix
  src/sections/DomainProject/index.vue
Labels: approved, area/dashboard, lgtm, size/XS

#160 feat(TagSelect): support min-width
  src/sections/TagSelect/index.vue
Labels: size/XS

#161 Automated cherry pick of #160: feat(TagSelect): support min-width
  src/sections/TagSelect/index.vue
Labels: size/XS

#158 fix: init xterm for cloudshell, needs more work
  scope/assets/cloudshell.svg
  scope/layouts/Navbar/index.vue
  src/components/Icon/assets/cloudshell.svg
  src/components/OcTerm/index.vue
  src/sections/Navbar/index.vue
Labels: size/M

#159 Automated cherry pick of #158: fix: init xterm for cloudshell, needs more work
  scope/assets/cloudshell.svg
  scope/layouts/Navbar/index.vue
  src/components/Icon/assets/cloudshell.svg
  src/components/OcTerm/index.vue
  src/sections/Navbar/index.vue
Labels: size/M

#163 Automated cherry pick of #162: feature(dashboard): add quota sort
  containers/Dashboard/extends/Quota/index.vue
Labels: size/XS

#162 feature(dashboard): add quota sort
  containers/Dashboard/extends/Quota/index.vue
Labels: area/dashboard, size/XS

#164 Automated cherry pick of #158: fix: init xterm for cloudshell, needs more work
  src/components/OcTerm/index.vue
  src/sections/Navbar/index.vue
Labels: size/XS

#165 bugfix(dashboard): adjust echart
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
Labels: area/dashboard, size/XS

#166 Automated cherry pick of #165: bugfix(dashboard): adjust echart
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
Labels: size/XS

#167 fix(compute): fix disk price
  containers/Compute/views/disk/create/components/BottomBar.vue
Labels: area/dashboard, size/S

#168 feat(meter): add price info scope
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/redis/create/components/BottomBar.vue
  containers/Network/views/eip/create/components/BottomBar.vue
  containers/Network/views/nats/create/components/BottomBar.vue
  containers/Storage/views/file-system/create/components/BottomBar.vue
Labels: area/dashboard, size/XS

#169 Automated cherry pick of #167: fix disk price
  containers/Compute/views/disk/create/components/BottomBar.vue
Labels: size/S

#170 Automated cherry pick of #168: add price info scope
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/redis/create/components/BottomBar.vue
  containers/Network/views/eip/create/components/BottomBar.vue
  containers/Network/views/nats/create/components/BottomBar.vue
  containers/Storage/views/file-system/create/components/BottomBar.vue
Labels: size/XS

#171 Bugfix/tb bugfix 050601
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/dialogs/DetectSSH.vue
  containers/Monitor/sections/ExplorerForm/form.vue
Labels: area/dashboard, size/M

#172 Automated cherry pick of #171: add tooltips for ssh proxy endpoint create form
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/dialogs/DetectSSH.vue
  containers/Monitor/sections/ExplorerForm/form.vue
Labels: size/M

#173 feat(Compute): server list action add permission
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  src/constants/permission.js
Labels: size/M

#175 Automated cherry pick of #173: feat(Compute): server list action add permission
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  src/constants/permission.js
Labels: size/M

#178 fix(Compute): #10789 baremetal install sys with zone and region error
  containers/Compute/views/baremetal/create/index.vue
Labels: size/XS

#180 Automated cherry pick of #178: fix(Compute): #10789 baremetal install sys with zone and region error
  containers/Compute/views/baremetal/create/index.vue
Labels: size/XS

#176 feature(compute): add #vm sort
  containers/Compute/views/host/mixins/columns.js
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
  src/utils/list.js
Labels: area/compute, size/S

#177 Automated cherry pick of #176: feature(compute): add #vm sort
  containers/Compute/views/host/mixins/columns.js
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
  src/utils/list.js
Labels: size/S

#185 fix(Network): update cloudregion params
  containers/Network/views/network/Create.vue
Labels: size/XS

#187 Automated cherry pick of #186: feat(Tag): add identity tag
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/tag/components/List.vue
  containers/Cloudenv/views/tag/index.vue
Labels: size/S

#188 feat(Tag): add permission support
  containers/Compute/views/vminstance/components/List.vue
  src/sections/TagTableColumn/index.vue
Labels: size/S

#189 Automated cherry pick of #188: feat(Tag): add permission support
  containers/Compute/views/vminstance/components/List.vue
  src/sections/TagTableColumn/index.vue
Labels: size/S

#190 Automated cherry pick of #188: feat(Tag): add permission support
  containers/Compute/views/vminstance/components/List.vue
  src/sections/TagTableColumn/index.vue
Labels: size/S

#191 feat(TagDetailColumn): add permission support
  src/sections/TagDetailColumn/index.vue
Labels: size/S

#192 Automated cherry pick of #191: feat(TagDetailColumn): add permission support
  src/sections/TagDetailColumn/index.vue
Labels: size/S

#193 Automated cherry pick of #191: feat(TagDetailColumn): add permission support
  src/sections/TagDetailColumn/index.vue
Labels: size/S

#195 Automated cherry pick of #194: add agent trans
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Monitor/components/MonitorCard/DashboardCards/index.vue
  containers/Monitor/sections/ExplorerForm/form.vue
  containers/Monitor/sections/ExplorerForm/index.vue
  containers/Monitor/sections/MonitorLine/index.vue
  containers/Monitor/views/dashboard/components/index.vue
  containers/Monitor/views/dashboard/create/index.vue
  containers/Network/router/index.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/crypto.js
Labels: size/L

#196 fix(Network): update cloudregion params
  containers/Network/views/network/Create.vue
Labels: size/XS

#197 Automated cherry pick of #196: fix(Network): update cloudregion params
  containers/Network/views/network/Create.vue
Labels: size/XS

#198 Automated cherry pick of #196: fix(Network): update cloudregion params
  containers/Network/views/network/Create.vue
Labels: size/XS

#199 Automated cherry pick of #196: fix(Network): update cloudregion params
  containers/Network/views/network/Create.vue
Labels: size/XS

#202 fix(Tag): identity tag params
  containers/Cloudenv/views/tag/components/List.vue
Labels: size/XS

#200 fix: close socket when close cloud shell
  src/components/OcTerm/index.vue
  src/components/Xterm/index.vue
Labels: size/M

#201 Automated cherry pick of #200: fix: close socket when close cloud shell
  src/components/OcTerm/index.vue
  src/components/Xterm/index.vue
Labels: size/M

#203 Automated cherry pick of #202: fix(Tag): identity tag params
  containers/Cloudenv/views/tag/components/List.vue
Labels: size/XS

#204 fix(Tag): identity tag details api version
  containers/Cloudenv/views/tag/sidepage/BindResource.vue
Labels: size/XS

#206 Bugfix/tb bugfix 050801
  containers/Compute/router/index.js
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
  containers/Network/router/index.js
  containers/Storage/router/index.js
  src/constants/permission.js
Labels: area/dashboard, size/M

#207 Automated cherry pick of #206: monitor line chart add scale
  containers/Compute/router/index.js
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
  containers/Network/router/index.js
  containers/Storage/router/index.js
  src/constants/permission.js
Labels: size/M

#210 feat(OcTerm): update octerm
  src/components/OcTerm/index.vue
Labels: size/M

#208 monitor line chart add data smooth
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
  containers/Monitor/components/MonitorCard/sections/select/scope.vue
  containers/Monitor/views/dashboard/components/index.vue
Labels: area/dashboard, size/S

#209 Automated cherry pick of #208: monitor line chart add data smooth
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
  containers/Monitor/components/MonitorCard/sections/select/scope.vue
  containers/Monitor/views/dashboard/components/index.vue
Labels: size/S

#212 network route hidden fix
  containers/Network/router/index.js
Labels: area/dashboard, size/XS

#213 Automated cherry pick of #212: network route hidden fix
  containers/Network/router/index.js
Labels: size/XS

#214 feat(OcTerm): update octerm style
  src/components/OcTerm/index.vue
  src/components/Xterm/index.vue
Labels: size/M

#215 Automated cherry pick of #214: feat(OcTerm): update octerm style
  src/components/OcTerm/index.vue
  src/components/Xterm/index.vue
Labels: size/M

#217 Automated cherry pick of #216: fix: init cloudshell in apigateway
  src/components/OcTerm/index.vue
  src/components/Xterm/index.vue
  src/sections/Navbar/index.vue
Labels: size/M

#219 Automated cherry pick of #218: bugfix(k8s): show detail list
  containers/K8S/views/configmap/components/List.vue
  containers/K8S/views/daemonset/components/List.vue
  containers/K8S/views/deployment/components/List.vue
  containers/K8S/views/rbacclusterrolebinding/components/List.vue
  containers/K8S/views/rbacrole/components/List.vue
  containers/K8S/views/secret/components/List.vue
  containers/K8S/views/service-account/components/List.vue
  containers/K8S/views/statefulset/components/List.vue
Labels: size/S

#225 feature(compute): add delete disk&instance options
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/dialogs/DeleteDisk.vue
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
Labels: area/compute, size/L

#226 Automated cherry pick of #224: fix(DiskCreate): fetch cloudregion params
  containers/Compute/views/disk/create/index.vue
Labels: size/XS

#227 fix(DiskCreate): split error
  containers/Compute/views/disk/create/components/BottomBar.vue
Labels: size/S

#228 Automated cherry pick of #227: fix(DiskCreate): split error
  containers/Compute/views/disk/create/components/BottomBar.vue
Labels: size/S

#229 Automated cherry pick of #227: fix(DiskCreate): split error
  containers/Compute/views/disk/create/components/BottomBar.vue
Labels: size/S

#230 Automated cherry pick of #227: fix(DiskCreate): split error
  containers/Compute/views/disk/create/components/BottomBar.vue
Labels: size/S

#231 fix(ServerPassword): 使用主机快照创建主机，不应该显示设置密码的输入框
  containers/Compute/sections/ServerPassword/index.vue
Labels: size/XS

#232 Automated cherry pick of #231: fix(ServerPassword): 使用主机快照创建主机，不应该显示设置密码的输入框
  containers/Compute/sections/ServerPassword/index.vue
Labels: size/XS

#233 Automated cherry pick of #231: fix(ServerPassword): 使用主机快照创建主机，不应该显示设置密码的输入框
  containers/Compute/sections/ServerPassword/index.vue
Labels: size/XS

#234 Automated cherry pick of #231: fix(ServerPassword): 使用主机快照创建主机，不应该显示设置密码的输入框
  containers/Compute/sections/ServerPassword/index.vue
Labels: size/XS

#239 fix(ServerPassword): 选择主机快照默认选中保留镜像设置且不支持更改类型
  containers/Compute/sections/ServerPassword/index.vue
Labels: size/XS

#235 vue router meta add propertity canRenderDefaultLayout
  src/permission.js
Labels: area/dashboard, size/XS

#236 Automated cherry pick of #235: vue router meta add propertity canRenderDefaultLayout
  src/permission.js
Labels: size/XS

#237 vminstall agent install fail reason
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
Labels: area/dashboard, size/XS

#238 Automated cherry pick of #237: vminstall agent install fail reason
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
Labels: size/XS

#240 Automated cherry pick of #239: fix(ServerPassword): 主机快照默认选中保留镜像设置且不支持更改类型
  containers/Compute/sections/ServerPassword/index.vue
Labels: size/XS

#241 Automated cherry pick of #239: fix(ServerPassword): 主机快照默认选中保留镜像设置且不支持更改类型
  containers/Compute/sections/ServerPassword/index.vue
Labels: size/XS

#242 Automated cherry pick of #239: fix(ServerPassword): 主机快照默认选中保留镜像设置且不支持更改类型
  containers/Compute/sections/ServerPassword/index.vue
Labels: size/XS

#243 Bugfix/tb bugfix 051301
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/OverviewCard/index.vue
  containers/Monitor/components/MonitorCard/sections/table/index.vue
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/components/List.vue
Labels: area/dashboard, size/M

#244 Automated cherry pick of #243: network list export add ports used
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/OverviewCard/index.vue
  containers/Monitor/components/MonitorCard/sections/table/index.vue
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/components/List.vue
Labels: size/M

#245 feat(ServerNetwork): add vpc options
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/sections/ServerNetwork/index.vue
  src/components/BaseSelect/index.vue
Labels: size/S

#246 feat(Network): add vlan id filter
  containers/Network/views/network/components/List.vue
Labels: size/XS

#247 Automated cherry pick of #246: feat(Network): add vlan id filter
  containers/Network/views/network/components/List.vue
Labels: size/XS

#248 Automated cherry pick of #246: feat(Network): add vlan id filter
  containers/Network/views/network/components/List.vue
Labels: size/XS

#249 Automated cherry pick of #246: feat(Network): add vlan id filter
  containers/Network/views/network/components/List.vue
Labels: size/XS

#250 login chanllenge after login fix
  src/sections/Auth/Login/components/LoginChallenge.vue
Labels: area/dashboard, size/XS

#251 fix: support update sku postpaid and prepaid status
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/sku/components/List.vue
  containers/Compute/views/sku/dialogs/ServerSkuUpdateDialog.vue
  containers/Compute/views/sku/mixins/columns.js
  containers/Compute/views/sku/mixins/singleActions.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#252 Automated cherry pick of #251: fix: support update sku postpaid and prepaid status
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/sku/components/List.vue
  containers/Compute/views/sku/dialogs/ServerSkuUpdateDialog.vue
  containers/Compute/views/sku/mixins/columns.js
  containers/Compute/views/sku/mixins/singleActions.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#253 Automated cherry pick of #251: fix: support update sku postpaid and prepaid status
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/sku/components/List.vue
  containers/Compute/views/sku/dialogs/ServerSkuUpdateDialog.vue
  containers/Compute/views/sku/mixins/columns.js
  containers/Compute/views/sku/mixins/singleActions.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#254 Automated cherry pick of #251: fix: support update sku postpaid and prepaid status
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/sku/components/List.vue
  containers/Compute/views/sku/dialogs/ServerSkuUpdateDialog.vue
  containers/Compute/views/sku/mixins/columns.js
  containers/Compute/views/sku/mixins/singleActions.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#255 fix: 1. add cloud SSO and update password to user menu 2. fix monitor translation issue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/views/overview/components/index.vue
  scope/layouts/Navbar/index.vue
  src/views/clouduser/index.vue
Labels: size/S

#257 fix(Cloudenv/AwsHuawei): #7431 创建天翼云云账号，开启免密登录时创建报错
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
Labels: size/XS

#258 Automated cherry pick of #257: fix(Cloudenv/AwsHuawei): #7431 创建天翼云云账号，开启免密登录时创建报错
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
Labels: size/XS

#259 Automated cherry pick of #257: fix(Cloudenv/AwsHuawei): #7431 创建天翼云云账号，开启免密登录时创建报错
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
Labels: size/XS

#260 fix(SearchBox): #7430 云上日志使用时间范围过滤，此前、此后这两种情况点击确定前端报错
  src/components/SearchBox/index.vue
Labels: size/XS

#261 Automated cherry pick of #260: fix(SearchBox): #7430 云上日志使用时间范围过滤，此前、此后这两种情况点击确定前端报错
  src/components/SearchBox/index.vue
Labels: size/XS

#262 fix(SearchBox): change date filter error
  src/components/SearchBox/index.vue
Labels: size/XS

#263 Automated cherry pick of #262: fix(SearchBox): change date filter error
  src/components/SearchBox/index.vue
Labels: size/XS

#265 Bugfix/tb bugfix 051801
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/create/form/SetupSSHForm.vue
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: area/dashboard, size/S

#264 ctyun not support create prepaid instance
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: area/dashboard, size/XS

#266 Automated cherry pick of #265: username tranlations fix
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/create/form/SetupSSHForm.vue
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/S

#267 dashboard default name fix
  containers/Monitor/sections/ExplorerForm/form.vue
Labels: area/monitor, size/S

#268 Automated cherry pick of #267: dashboard default name fix
  containers/Monitor/sections/ExplorerForm/form.vue
Labels: size/S

#269 fix(OsSelect): select instance snapshot params and console error
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#270 Automated cherry pick of #269: fix(OsSelect): select instance snapshot params and console error
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#271 Automated cherry pick of #269: fix(OsSelect): select instance snapshot params and console error
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
Labels: size/XS

#272 Automated cherry pick of #269: fix(OsSelect): select instance snapshot params and console error
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#273 fix(Locales): image save fail i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#274 Automated cherry pick of #273: fix(Locales): image save fail i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#275 Automated cherry pick of #273: fix(Locales): image save fail i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#276 Automated cherry pick of #273: fix(Locales): image save fail i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#277 fix(TagTableColumn): #7435 列表鼠标hover标签icon时，只展示user的标签，不展示ext的
  src/sections/TagTableColumn/index.vue
Labels: size/XS

#278 Automated cherry pick of #277: fix(TagTableColumn): #7435 列表鼠标hover标签icon时，只展示user的标签，不展示ext的
  src/sections/TagTableColumn/index.vue
Labels: size/XS

#279 Automated cherry pick of #277: fix(TagTableColumn): #7435 列表鼠标hover标签icon时，只展示user的标签，不展示ext的
  src/sections/TagTableColumn/index.vue
Labels: size/XS

#280 fix(SkuList): #3134 批量设置销售状态位置修改
  containers/Compute/views/sku/components/List.vue
Labels: size/M

#281 Automated cherry pick of #280: fix(SkuList): #3134 批量设置销售状态位置修改
  containers/Compute/views/sku/components/List.vue
Labels: size/M

#282 Automated cherry pick of #280: fix(SkuList): #3134 批量设置销售状态位置修改
  containers/Compute/views/sku/components/List.vue
Labels: size/M

#285 imgLabels fix conficts
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
Labels: area/compute, size/XS

#283 dashboard table sort fix
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: area/monitor, size/XS

#284 dashboard table sort fix
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/XS

#288 feat(Host/Storage): add single actions in host sidepage storage
  containers/Compute/views/host/sidepage/Storage.vue
  containers/Compute/views/host/sidepage/index.vue
  containers/Storage/views/blockstorage/components/List.vue
Labels: size/L

#289 Bugfix/tb bugfix 052103
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
  containers/Cloudenv/views/cloudaccount/dialogs/Update.vue
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/lbcerts/mixins/columns.js
Labels: area/cloudenv, area/network, size/L

#290 Automated cherry pick of #289 upstream release 3.7
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
  containers/Cloudenv/views/cloudaccount/dialogs/Update.vue
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/lbcerts/mixins/columns.js
Labels: size/L

#291 monitor query add metric translations for storage
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: area/monitor, size/XS

#292 monitor query add metric translations for storage
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: size/XS

#293 monitor query add metric translations for storage
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: size/L

#294 monitor query add metric translations for storage
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: size/L

#296 fix(Disk): #7450 VMware主机同步磁盘状态后状态为未知，再次同步主机状态，磁盘状态正常
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/M

#297 Automated cherry pick of #296: fix(Disk): #7450 VMware主机同步磁盘状态后状态为未知，再次同步主机状态，磁盘状态正常
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/M

#298 Automated cherry pick of #296: fix(Disk): #7450 VMware主机同步磁盘状态后状态为未知，再次同步主机状态，磁盘状态正常
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/M

#299 Automated cherry pick of #296: fix(Disk): #7450 VMware主机同步磁盘状态后状态为未知，再次同步主机状态，磁盘状态正常
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/M

#300 fix(Network): #7449 VMware不支持主机修改IP
  containers/Compute/views/networks/mixins/singleActions.js
Labels: size/XS

#302 Automated cherry pick of #300: fix(Network): #7449 VMware不支持主机修改IP
  containers/Compute/views/networks/mixins/singleActions.js
Labels: size/XS

#303 Automated cherry pick of #300: fix(Network): #7449 VMware不支持主机修改IP
  containers/Compute/views/networks/mixins/singleActions.js
Labels: size/XS

#304 Feature/glb r 3.8 project mapping
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/router/index.js
  containers/Cloudenv/views/projectmapping/components/List.vue
  containers/Cloudenv/views/projectmapping/components/RuleList/columns.js
  containers/Cloudenv/views/projectmapping/components/RuleList/index.vue
  containers/Cloudenv/views/projectmapping/components/Tag.vue
  containers/Cloudenv/views/projectmapping/constants.js
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/dialogs/Delete.vue
  containers/Cloudenv/views/projectmapping/dialogs/DeleteResourceOwner.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleCreate.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleUpdate.vue
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/index.vue
  containers/Cloudenv/views/projectmapping/mixins/columns.js
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
  containers/Cloudenv/views/projectmapping/sidepage/Detail.vue
  containers/Cloudenv/views/projectmapping/sidepage/index.vue
  containers/Cloudenv/views/resourceownermanage/components/CommonFormItems.vue
  containers/Cloudenv/views/resourceownermanage/components/List.vue
  containers/Cloudenv/views/resourceownermanage/components/RuleList/columns.js
  containers/Cloudenv/views/resourceownermanage/components/RuleList/index.vue
  containers/Cloudenv/views/resourceownermanage/components/RuleList/singleActions.js
  containers/Cloudenv/views/resourceownermanage/components/Tag.vue
  containers/Cloudenv/views/resourceownermanage/constants.js
  containers/Cloudenv/views/resourceownermanage/dialogs/Create.vue
  containers/Cloudenv/views/resourceownermanage/dialogs/Update.vue
  containers/Cloudenv/views/resourceownermanage/index.vue
  containers/Cloudenv/views/resourceownermanage/mixins/columns.js
  containers/Cloudenv/views/resourceownermanage/mixins/singleActions.js
  containers/Cloudenv/views/resourceownermanage/sidepage/Detail.vue
  containers/Cloudenv/views/resourceownermanage/sidepage/index.vue
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/PasswordFetcher/index.vue
  src/components/PageList/components/Table.vue
  src/constants/expectStatus.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/styles/less/global.less
Labels: area/cloudenv, size/XXL

#307 Automated cherry pick of #306: feat(curency): 巴西币种支持
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsOverview/index.vue
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#306 feat(currency): 巴西币种支持
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsOverview/index.vue
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#305 删除无用文件
  containers/Cloudenv/views/resourceownermanage/components/CommonFormItems.vue
  containers/Cloudenv/views/resourceownermanage/components/List.vue
  containers/Cloudenv/views/resourceownermanage/components/RuleList/columns.js
  containers/Cloudenv/views/resourceownermanage/components/RuleList/index.vue
  containers/Cloudenv/views/resourceownermanage/components/RuleList/singleActions.js
  containers/Cloudenv/views/resourceownermanage/components/Tag.vue
  containers/Cloudenv/views/resourceownermanage/constants.js
  containers/Cloudenv/views/resourceownermanage/dialogs/Create.vue
  containers/Cloudenv/views/resourceownermanage/dialogs/Update.vue
  containers/Cloudenv/views/resourceownermanage/index.vue
  containers/Cloudenv/views/resourceownermanage/mixins/columns.js
  containers/Cloudenv/views/resourceownermanage/mixins/singleActions.js
  containers/Cloudenv/views/resourceownermanage/sidepage/Detail.vue
  containers/Cloudenv/views/resourceownermanage/sidepage/index.vue
Labels: size/XXL

#308 monitor table add storage_name
  containers/Monitor/constants/index.js
Labels: area/monitor, size/XS

#309 Automated cherry pick of #308: monitor table add storage_name
  containers/Monitor/constants/index.js
Labels: size/XS

#310 Automated cherry pick of #308: monitor table add storage_name
  containers/Monitor/constants/index.js
Labels: size/XS

#312 feat(currency): 增加全局币种映射常量
  src/constants/currency.js
Labels: size/S

#314 Automated cherry pick of #312: feat(currency): 增加全局币种映射常量
  src/constants/currency.js
Labels: size/S

#315 feat(i18n): vm instance
  containers/Compute/locales/en.json
Labels: size/XS

#316 Automated cherry pick of #315: feat(i18n): vm instance
  containers/Compute/locales/en.json
Labels: size/XS

#317 Automated cherry pick of #304: feature(cloudenv): add project-mapping function
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/router/index.js
  containers/Cloudenv/views/projectmapping/components/List.vue
  containers/Cloudenv/views/projectmapping/components/RuleList/columns.js
  containers/Cloudenv/views/projectmapping/components/RuleList/index.vue
  containers/Cloudenv/views/projectmapping/components/Tag.vue
  containers/Cloudenv/views/projectmapping/constants.js
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/dialogs/Delete.vue
  containers/Cloudenv/views/projectmapping/dialogs/DeleteResourceOwner.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleCreate.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleUpdate.vue
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/index.vue
  containers/Cloudenv/views/projectmapping/mixins/columns.js
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
  containers/Cloudenv/views/projectmapping/sidepage/Detail.vue
  containers/Cloudenv/views/projectmapping/sidepage/index.vue
  containers/Cloudenv/views/resourceownermanage/components/CommonFormItems.vue
  containers/Cloudenv/views/resourceownermanage/components/List.vue
  containers/Cloudenv/views/resourceownermanage/components/RuleList/columns.js
  containers/Cloudenv/views/resourceownermanage/components/RuleList/index.vue
  containers/Cloudenv/views/resourceownermanage/components/RuleList/singleActions.js
  containers/Cloudenv/views/resourceownermanage/components/Tag.vue
  containers/Cloudenv/views/resourceownermanage/constants.js
  containers/Cloudenv/views/resourceownermanage/dialogs/Create.vue
  containers/Cloudenv/views/resourceownermanage/dialogs/Update.vue
  containers/Cloudenv/views/resourceownermanage/index.vue
  containers/Cloudenv/views/resourceownermanage/mixins/columns.js
  containers/Cloudenv/views/resourceownermanage/mixins/singleActions.js
  containers/Cloudenv/views/resourceownermanage/sidepage/Detail.vue
  containers/Cloudenv/views/resourceownermanage/sidepage/index.vue
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/PasswordFetcher/index.vue
  src/components/PageList/components/Table.vue
  src/constants/expectStatus.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/styles/less/global.less
Labels: area/cloudenv, size/XXL

#318 Automated cherry pick of #264: ctyun not support create prepaid instance
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/XS

#320 monitor query add metric translations for storage
  containers/Monitor/constants/index.js
Labels: area/monitor, size/XS

#321 Automated cherry pick of #320: monitor query add metric translations for storage
  containers/Monitor/constants/index.js
Labels: size/XS

#322 Automated cherry pick of #320: monitor query add metric translations for storage
  containers/Monitor/constants/index.js
Labels: size/XS

#323 Automated cherry pick of #320: monitor query add metric translations for storage
  containers/Monitor/constants/index.js
Labels: size/XS

#319 删除无用文件
  containers/Cloudenv/views/resourceownermanage/components/CommonFormItems.vue
  containers/Cloudenv/views/resourceownermanage/components/List.vue
  containers/Cloudenv/views/resourceownermanage/components/RuleList/columns.js
  containers/Cloudenv/views/resourceownermanage/components/RuleList/index.vue
  containers/Cloudenv/views/resourceownermanage/components/RuleList/singleActions.js
  containers/Cloudenv/views/resourceownermanage/components/Tag.vue
  containers/Cloudenv/views/resourceownermanage/constants.js
  containers/Cloudenv/views/resourceownermanage/dialogs/Create.vue
  containers/Cloudenv/views/resourceownermanage/dialogs/Update.vue
  containers/Cloudenv/views/resourceownermanage/index.vue
  containers/Cloudenv/views/resourceownermanage/mixins/columns.js
  containers/Cloudenv/views/resourceownermanage/mixins/singleActions.js
  containers/Cloudenv/views/resourceownermanage/sidepage/Detail.vue
  containers/Cloudenv/views/resourceownermanage/sidepage/index.vue
Labels: area/cloudenv, size/XXL

#325 bugfix(cloudenv): add project-mapping menu hidden
  containers/Cloudenv/router/index.js
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
Labels: area/cloudenv, size/XS

#326 add month & year price
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/server-price-comparator/mixins/columns.js
Labels: area/cloudenv, size/M

#327 Automated cherry pick of #326: add month & year price
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/server-price-comparator/mixins/columns.js
Labels: size/M

#329 Automated cherry pick of #325: bugfix(cloudenv): add project-mapping menu hidden
  containers/Cloudenv/router/index.js
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
Labels: area/cloudenv, size/XS

#330 Bugfix/glb r 3.7 project mapping
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/projectmapping/components/RuleList/columns.js
  containers/Cloudenv/views/projectmapping/components/RuleList/index.vue
  containers/Cloudenv/views/projectmapping/components/Tag.vue
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleCreate.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleUpdate.vue
  containers/Cloudenv/views/projectmapping/mixins/columns.js
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
  containers/Cloudenv/views/projectmapping/sidepage/Detail.vue
  containers/Cloudenv/views/projectmapping/sidepage/index.vue
Labels: area/cloudenv, size/L

#331 Automated cherry pick of #330: 优化
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/projectmapping/components/RuleList/columns.js
  containers/Cloudenv/views/projectmapping/components/RuleList/index.vue
  containers/Cloudenv/views/projectmapping/components/Tag.vue
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleCreate.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleUpdate.vue
  containers/Cloudenv/views/projectmapping/mixins/columns.js
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
  containers/Cloudenv/views/projectmapping/sidepage/Detail.vue
  containers/Cloudenv/views/projectmapping/sidepage/index.vue
Labels: area/cloudenv, size/L
