Repository yunionio/dashboard, pull requests merged in 2021-09, with the labels that each got.

#938 fix: 全局搜索优化
  src/components/SearchBox/Tag.vue
Labels: size/XS

#939 Automated cherry pick of #938: fix: 全局搜索优化
  src/components/SearchBox/Tag.vue
Labels: size/XS

#940 Automated cherry pick of #938: fix: 全局搜索优化
  src/components/SearchBox/Tag.vue
Labels: size/XS

#941 networks global input error fix
  src/constants/globalSearch.js
Labels: area/dashboard, size/S

#942 Automated cherry pick of #941: networks global input error fix
  src/constants/globalSearch.js
Labels: size/S

#945 Automated cherry pick of #944: 修改top5磁贴单位
  containers/Dashboard/extends/Top5/constants.js
Labels: size/S

#946 Automated cherry pick of #944: 修改top5磁贴单位
  containers/Dashboard/extends/Top5/constants.js
Labels: size/S

#947 feat: #3318 硬盘列表增加存储类型列显示
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/utils/columns.js
Labels: size/S

#948 Automated cherry pick of #947: feat: #3318 硬盘列表增加存储类型列显示
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/utils/columns.js
Labels: size/S

#950 调整币种为通用文案
  src/store/modules/common.js
Labels: size/S

#952 Automated cherry pick of #950: 调整币种为通用文案
  src/store/modules/common.js
Labels: size/S

#955 feat: #3320 云账号资源统计中，磁盘挂载率和eip使用率的颜色反了
  containers/Cloudenv/sections/UsageSidepage/components/UsageRing.vue
  containers/Cloudenv/sections/UsageSidepage/index.vue
  src/constants/color.js
Labels: size/M

#957 华为云监控维度修改
  containers/DB/constants/index.js
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds-backup/dialogs/BackupRecovery.vue
  containers/DB/views/rds/sidepage/Monitor.vue
Labels: area/monitor, size/S

#953 fix(compute): add cloudpods local disk info
  containers/Cloudenv/views/server-price-comparator/create/components/SystemDisk.vue
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/K8S/views/cluster/create/index.vue
Labels: size/S

#956 Automated cherry pick of #955: feat: #3320 云账号资源统计中，磁盘挂载率和eip使用率的颜色反了
  containers/Cloudenv/sections/UsageSidepage/components/UsageRing.vue
  containers/Cloudenv/sections/UsageSidepage/index.vue
  src/constants/color.js
Labels: size/M

#954 Automated cherry pick of #953: fix(compute): add cloudpods local disk info
  containers/Cloudenv/views/server-price-comparator/create/components/SystemDisk.vue
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/K8S/views/cluster/create/index.vue
Labels: size/S

#958 Automated cherry pick of #957: 华为云监控维度修改
  containers/DB/constants/index.js
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds-backup/dialogs/BackupRecovery.vue
  containers/DB/views/rds/sidepage/Monitor.vue
Labels: size/S

#959 Automated cherry pick of #957: 华为云监控维度修改
  containers/DB/constants/index.js
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds/sidepage/Monitor.vue
Labels: size/S

#1005 Bugfix/tb bugfix 090303
  containers/Compute/views/baremetal/sidepage/Detail.vue
  containers/Monitor/views/commonalert/components/alert/index.vue
Labels: size/M

#991 fix[3.8]: 新建eip对云订阅增加过滤条件
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Network/views/eip/create/index.vue
Labels: area/compute

#999 fix[3.7]: 新建公有云磁盘,对provider添加域过滤条件
  containers/Compute/views/disk/create/index.vue
  src/sections/AreaSelects/index.js
Labels: area/compute, size/XS

#1000 Automated cherry pick of #999: fix[3.7]: 新建公有云磁盘,对provider添加域过滤条件
  containers/Compute/views/disk/create/index.vue
  src/sections/AreaSelects/index.js
Labels: size/XS

#1001 Automated cherry pick of #999: fix[3.7]: 新建公有云磁盘,对provider添加域过滤条件
  containers/Compute/views/disk/create/index.vue
  src/sections/AreaSelects/index.js
Labels: size/XS

#1002 fix[3.7]: 修复rds备份操作按钮与详情状态不一致
  containers/DB/views/rds-backup/mixins/singleActions.js
Labels: area/db, size/XS

#1003 Automated cherry pick of #1002: fix[3.7]: 修复rds备份操作按钮与详情状态不一致
  containers/DB/views/rds-backup/mixins/singleActions.js
Labels: size/XS

#1004 Automated cherry pick of #1002: fix[3.7]: 修复rds备份操作按钮与详情状态不一致
  containers/DB/views/rds-backup/mixins/singleActions.js
Labels: size/XS

#1007 fix[3.7]: 修正翻译
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: size/XS

#1008 Automated cherry pick of #1007: fix[3.7]: 修正翻译
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: size/XS

#1009 fix[3.7]: 修改BRL币种文案
  src/store/modules/common.js
Labels: size/S

#1010 Automated cherry pick of #1009: fix[3.7]: 修改BRL币种文案
  src/store/modules/common.js
Labels: size/S

#1011 Automated cherry pick of #1009: fix[3.7]: 修改BRL币种文案
  src/store/modules/common.js
Labels: size/S

#1012 feat(kvm): adjust local storage max disk size to 20T
  src/constants/compute.js
Labels: lgtm, approved, area/compute, size/S

#1013 Automated cherry pick of #1012: feat(kvm): adjust local storage max disk size to 20T
  src/constants/compute.js
Labels: lgtm, approved, size/S

#1015 Automated cherry pick of #1012: feat(kvm): adjust local storage max disk size to 20T
  src/constants/compute.js
Labels: lgtm, approved, size/XS

#1014 Automated cherry pick of #1012: feat(kvm): adjust local storage max disk size to 20T
  src/constants/compute.js
Labels: lgtm, approved, size/XS

#1016 fix: update user metadata interface params
  src/sections/DialogManager/components/SetTag.vue
Labels: size/XS

#1017 Automated cherry pick of #1016: fix: update user metadata interface params
  src/sections/DialogManager/components/SetTag.vue
Labels: size/XS

#1018 Automated cherry pick of #1016: fix: update user metadata interface params
  src/sections/DialogManager/components/SetTag.vue
Labels: size/XS

#1022 feat: 如果是开源版本则取消调用meter服务
  containers/Compute/views/vminstance/create/components/BottomBar.vue
Labels: size/XS

#1023 Automated cherry pick of #1022: feat: 如果是开源版本则取消调用meter服务
  containers/Compute/views/vminstance/create/components/BottomBar.vue
Labels: size/XS

#1024 Automated cherry pick of #1022: feat: 如果是开源版本则取消调用meter服务
  containers/Compute/views/vminstance/create/components/BottomBar.vue
Labels: size/XS

#1019 fix: add nas export field
  containers/Storage/views/file-system/components/List.vue
  containers/Storage/views/mount-target/components/List.vue
Labels: size/XS

#1020 Automated cherry pick of #1019: fix: add nas export field
  containers/Storage/views/file-system/components/List.vue
  containers/Storage/views/mount-target/components/List.vue
Labels: size/XS

#1021 Automated cherry pick of #1019: fix: add nas export field
  containers/Storage/views/file-system/components/List.vue
  containers/Storage/views/mount-target/components/List.vue
Labels: size/XS

#1025 fix[3.8]: 修改驱动操作添加平台过滤
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/dialogs/DriverUpdateDialog.vue
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/M, area/compute

#1026 Automated cherry pick of #1025: fix[3.8]: 修改驱动操作添加平台过滤
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/dialogs/DriverUpdateDialog.vue
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/M

#1028 Automated cherry pick of #1027: monitor overview add disk used percent
  containers/Monitor/components/MonitorCard/OverviewCard/metrics.js
Labels: size/XS

#1031 fix: server ip loading
  src/utils/common/tableColumn.js
Labels: size/XS

#1032 Automated cherry pick of #1031: fix: server ip loading
  src/utils/common/tableColumn.js
Labels: size/XS

#1030 fix[3.6]: block storage change tab fix
  containers/Storage/views/blockstorage/components/List.vue
  containers/Storage/views/blockstorage/mixins/singleActions.js
  containers/Storage/views/blockstorage/sidepage/index.vue
Labels: area/storage, size/S

#1033 fix: add apsara default region
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
Labels: size/M

#1034 Automated cherry pick of #1033: fix: add apsara default region
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
Labels: size/M

#1036 Automated cherry pick of #1033: fix: add apsara default region
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
Labels: size/M

#1035 Automated cherry pick of #1033: fix: add apsara default region
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
Labels: size/M

#1037 monitor overview add mem used percent
  containers/Monitor/components/MonitorCard/OverviewCard/metrics.js
Labels: area/monitor, size/S

#1038 Automated cherry pick of #1037: monitor overview add mem used percent
  containers/Monitor/components/MonitorCard/OverviewCard/metrics.js
Labels: size/S

#1039 Automated cherry pick of #1037: monitor overview add mem used percent
  containers/Monitor/components/MonitorCard/OverviewCard/metrics.js
Labels: size/S

#1040 monitor charts fix
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: area/monitor, size/S

#1041 Automated cherry pick of #1040: monitor charts fix
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/S

#1042 Automated cherry pick of #1040: monitor charts fix
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/S

#1043 monitor charts fix
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: area/monitor, size/XS

#1044 Automated cherry pick of #1043: monitor charts fix
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/XS

#1045 Automated cherry pick of #1043: monitor charts fix
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/XS

#1046 monitor charts fix
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: area/monitor, size/XS

#1047 Automated cherry pick of #1046: monitor charts fix
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/XS

#1048 Automated cherry pick of #1046: monitor charts fix
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/XS

#1049 fix: #7738 新建虚拟机且添加数据盘时CPU架构不应该从X86自动跳到aarch64
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#1050 Automated cherry pick of #1049: fix: #7738 新建虚拟机且添加数据盘时CPU架构不应该从X86自动跳到aarch64
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#1051 Automated cherry pick of #1049: fix: #7738 新建虚拟机且添加数据盘时CPU架构不应该从X86自动跳到aarch64
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#1052 fix: minor alignment format error
  containers/Cloudenv/views/cloudaccount/constants.js
Labels: size/XS

#1053 feat: update login page
  src/layouts/Auth/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Auth/Login/assets/bg2.png
  src/sections/Auth/Login/assets/login-bg.png
  src/sections/Auth/Login/components/LoginChallenge.vue
  src/sections/Auth/Login/components/LoginChooser.vue
  src/sections/Auth/Login/index.vue
Labels: size/L

#1054 feature monitor ignore
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/router/index.js
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/alertrecord/dialogs/shieldAlertrecord.vue
  containers/Monitor/views/alertrecord/mixins/columns.js
  containers/Monitor/views/alertrecord/mixins/singleActions.js
  containers/Monitor/views/alertrecordshields/components/List.vue
  containers/Monitor/views/alertrecordshields/index.vue
  containers/Monitor/views/alertrecordshields/mixins/columns.js
  containers/Monitor/views/alertrecordshields/mixins/singleActions.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/CustomDate/index.vue
  src/utils/common/tableColumn.js
Labels: area/monitor, size/XL

#1055 Automated cherry pick of #1054: feature monitor ignore
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/router/index.js
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/alertrecord/dialogs/shieldAlertrecord.vue
  containers/Monitor/views/alertrecord/mixins/columns.js
  containers/Monitor/views/alertrecord/mixins/singleActions.js
  containers/Monitor/views/alertrecordshields/components/List.vue
  containers/Monitor/views/alertrecordshields/index.vue
  containers/Monitor/views/alertrecordshields/mixins/columns.js
  containers/Monitor/views/alertrecordshields/mixins/singleActions.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/CustomDate/index.vue
  src/utils/common/tableColumn.js
Labels: size/XL

#1056 Automated cherry pick of #1053: feat: update login page
  src/layouts/Auth/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Auth/Login/assets/bg2.png
  src/sections/Auth/Login/assets/login-bg.png
  src/sections/Auth/Login/components/LoginChallenge.vue
  src/sections/Auth/Login/components/LoginChooser.vue
  src/sections/Auth/Login/index.vue
Labels: size/L

#1057 Automated cherry pick of #1053: feat: update login page
  src/layouts/Auth/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Auth/Login/assets/bg2.png
  src/sections/Auth/Login/assets/login-bg.png
  src/sections/Auth/Login/components/LoginChallenge.vue
  src/sections/Auth/Login/components/LoginChooser.vue
  src/sections/Auth/Login/index.vue
Labels: size/L

#1058 feat: update login icon
  scope/assets/code.svg
  scope/assets/password.svg
  scope/assets/user-del.svg
  scope/assets/user.svg
Labels: size/S

#1059 Automated cherry pick of #1058: feat: update login icon
  scope/assets/code.svg
  scope/assets/password.svg
  scope/assets/user-del.svg
  scope/assets/user.svg
Labels: size/S

#1060 Automated cherry pick of #1058: feat: update login icon
  scope/assets/code.svg
  scope/assets/password.svg
  scope/assets/user-del.svg
  scope/assets/user.svg
Labels: size/S

#1063 feat: update login bg and font
  src/sections/Auth/Login/index.vue
Labels: size/S

#1064 Automated cherry pick of #1063: feat: update login bg and font
  src/sections/Auth/Login/index.vue
Labels: size/S

#1065 Automated cherry pick of #1063: feat: update login bg and font
  src/sections/Auth/Login/index.vue
Labels: size/S

#1061 add monitor resource page
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/router/index.js
  containers/Monitor/views/monitorresource/components/List.vue
  containers/Monitor/views/monitorresource/index.vue
  containers/Monitor/views/monitorresource/mixins/columns.js
  containers/Monitor/views/monitorresource/mixins/singleActions.js
  containers/Monitor/views/monitorresource/sidepage/index.vue
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/monitor, size/L

#1062 Automated cherry pick of #1061: add monitor resource page
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/router/index.js
  containers/Monitor/views/monitorresource/components/List.vue
  containers/Monitor/views/monitorresource/index.vue
  containers/Monitor/views/monitorresource/mixins/columns.js
  containers/Monitor/views/monitorresource/mixins/singleActions.js
  containers/Monitor/views/monitorresource/sidepage/index.vue
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#1069 fix: #7767 新建云账号，当项目为“自动创建项目”时，如果项目列表为空，表单会校验失败
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/S3CephXsky.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
Labels: size/L

#1066 fix: 添加网卡选择子网去除host筛选
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: area/compute, size/XS

#1067 Automated cherry pick of #1066: fix: 添加网卡选择子网去除host筛选
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: size/XS

#1068 Automated cherry pick of #1066: fix: 添加网卡选择子网去除host筛选
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: size/XS

#1070 Automated cherry pick of #1069: fix: #7767 新建云账号，当项目为“自动创建项目”时，如果项目列表为空，表单会校验失败
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/S3CephXsky.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
Labels: size/L

#1071 fix: 新建虚拟机和价格清单过滤掉京东云和移动云等只读的云平台
  containers/Cloudenv/views/server-price-comparator/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: area/compute, size/XS

#1072 Automated cherry pick of #1071: fix: 新建虚拟机和价格清单过滤掉京东云和移动云等只读的云平台
  containers/Cloudenv/views/server-price-comparator/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/XS

#1073 fix: add lb create region filter
  containers/Network/views/lb/create/form/Public.vue
Labels: area/network, size/S

#1074 Automated cherry pick of #1073: fix: add lb create region filter
  containers/Network/views/lb/create/form/Public.vue
Labels: size/S

#1075 Automated cherry pick of #1073: fix: add lb create region filter
  containers/Network/views/lb/create/form/Public.vue
Labels: size/S

#1076 aliyun default backend group list fix
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/lb/sidepage/index.vue
  containers/Network/views/loadbalancerbackend/components/List.vue
  containers/Network/views/loadbalancerbackend/mixins/singleActions.js
  containers/Network/views/loadbalancerbackendgroup/components/List.vue
  containers/Network/views/loadbalancerbackendgroup/mixins/singleActions.js
Labels: size/M, area/network

#1077 Automated cherry pick of #1076: aliyun default backend group list fix
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/lb/sidepage/index.vue
  containers/Network/views/loadbalancerbackend/components/List.vue
  containers/Network/views/loadbalancerbackend/mixins/singleActions.js
  containers/Network/views/loadbalancerbackendgroup/components/List.vue
  containers/Network/views/loadbalancerbackendgroup/mixins/singleActions.js
Labels: size/M

#1078 Automated cherry pick of #1076: aliyun default backend group list fix
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/lb/sidepage/index.vue
  containers/Network/views/loadbalancerbackend/components/List.vue
  containers/Network/views/loadbalancerbackend/mixins/singleActions.js
  containers/Network/views/loadbalancerbackendgroup/components/List.vue
  containers/Network/views/loadbalancerbackendgroup/mixins/singleActions.js
Labels: size/M

#1079 feat: update custome font color
  src/sections/Auth/Login/index.vue
  src/utils/i18n.js
Labels: size/S

#1080 Automated cherry pick of #1079: feat: update custome font color
  src/sections/Auth/Login/index.vue
  src/utils/i18n.js
Labels: size/S

#1081 Automated cherry pick of #1079: feat: update custome font color
  src/sections/Auth/Login/index.vue
  src/utils/i18n.js
Labels: size/S

#1082 fix: #7754 腾讯云RDS列表点击刷新前端报错
  containers/DB/views/rds/mixins/columns.js
Labels: size/XS

#1083 Automated cherry pick of #1082: fix: #7754 腾讯云RDS列表点击刷新前端报错
  containers/DB/views/rds/mixins/columns.js
Labels: size/XS

#1084 fix: #7755 redis列表，IP复制icon不应该一直显示
  containers/DB/views/redis/mixins/columns.js
Labels: size/S

#1085 Automated cherry pick of #1084: fix: #7755 redis列表，IP复制icon不应该一直显示
  containers/DB/views/redis/mixins/columns.js
Labels: size/S

#1086 feat: update oem info
  containers/Compute/views/disk/mixins/singleActions.js
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
Labels: size/XS

#1087 Automated cherry pick of #1086: feat: update oem info
  containers/Compute/views/disk/mixins/singleActions.js
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
Labels: size/XS

#1088 Automated cherry pick of #1086: feat: update oem info
  containers/Compute/views/disk/mixins/singleActions.js
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
Labels: size/XS

#1089 fix: #7756 mongodb的批量设置删除保护的文案需要修改
  containers/DB/views/mongodb/components/List.vue
Labels: size/XS

#1090 Automated cherry pick of #1089: fix: #7756 mongodb的批量设置删除保护的文案需要修改
  containers/DB/views/mongodb/components/List.vue
Labels: size/XS

#1091 fix: #7765 应用程序服务-详情：环境是否支持点击的优化
  containers/Compute/views/webapp/sidepage/EnvironmentsList.vue
Labels: size/XS

#1092 Automated cherry pick of #1091: fix: #7765 应用程序服务-详情：环境是否支持点击的优化
  containers/Compute/views/webapp/sidepage/EnvironmentsList.vue
Labels: size/XS

#1093 fix: #7750 开启防盗链优化：类型无默认值但是可创建，创建后会显示默认值‘白名单’
  containers/Storage/views/bucket/dialogs/SetAntiLeechDialog.vue
Labels: size/XS

#1094 Automated cherry pick of #1093: fix: #7750 开启防盗链优化：类型无默认值但是可创建，创建后会显示默认值‘白名单’
  containers/Storage/views/bucket/dialogs/SetAntiLeechDialog.vue
Labels: size/XS

#1095 fix: #12046 在系统镜像点击新建虚拟机后应该加上cpu架构的参数
  containers/Compute/views/image/dialogs/ImageCreateServer.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/M

#1096 Automated cherry pick of #1095: fix: #12046 在系统镜像点击新建虚拟机后应该加上cpu架构的参数
  containers/Compute/views/image/dialogs/ImageCreateServer.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/M

#1097 Automated cherry pick of #1095: fix: #12046 在系统镜像点击新建虚拟机后应该加上cpu架构的参数
  containers/Compute/views/image/dialogs/ImageCreateServer.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/M

#1098 Automated cherry pick of #1095: fix: #12046 在系统镜像点击新建虚拟机后应该加上cpu架构的参数
  containers/Compute/views/image/dialogs/ImageCreateServer.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/M

#1099 feat: #3344 update login page
  src/layouts/Auth/index.vue
  src/sections/Auth/Login/components/LoginChallenge.vue
  src/sections/Auth/Login/components/LoginChooser.vue
  src/sections/Auth/Login/index.vue
Labels: size/L

#1100 Automated cherry pick of #1099: feat: #3344 update login page
  src/layouts/Auth/index.vue
  src/sections/Auth/Login/components/LoginChallenge.vue
  src/sections/Auth/Login/components/LoginChooser.vue
  src/sections/Auth/Login/index.vue
Labels: size/L

#1101 Automated cherry pick of #1099: feat: #3344 update login page
  src/layouts/Auth/index.vue
  src/sections/Auth/Login/components/LoginChallenge.vue
  src/sections/Auth/Login/components/LoginChooser.vue
  src/sections/Auth/Login/index.vue
Labels: size/L

#1102 fix[3.7]: area-selects component fetch param fix
  src/sections/AreaSelects/index.js
Labels: area/compute, size/S

#1103 Automated cherry pick of #1102: fix[3.7]: area-selects component fetch param fix
  src/sections/AreaSelects/index.js
Labels: size/S

#1104 Automated cherry pick of #1102: fix[3.7]: area-selects component fetch param fix
  src/sections/AreaSelects/index.js
Labels: size/S

#1105 fix: bucket policy create
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/bucket/dialogs/CreatePolicyDialog.vue
  containers/Storage/views/bucket/sidepage/Policies.vue
Labels: size/M, area/storage

#1106 Automated cherry pick of #1105: fix: bucket policy create
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/bucket/dialogs/CreatePolicyDialog.vue
  containers/Storage/views/bucket/sidepage/Policies.vue
Labels: size/M

#1107 Automated cherry pick of #1105: fix: bucket policy create
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/bucket/dialogs/CreatePolicyDialog.vue
  containers/Storage/views/bucket/sidepage/Policies.vue
Labels: size/M

#1108 feat: update login page layout
  src/sections/Auth/Login/assets/login-bg.png
  src/sections/Auth/Login/index.vue
Labels: size/S

#1109 Automated cherry pick of #1108: feat: update login page layout
  src/sections/Auth/Login/assets/login-bg.png
  src/sections/Auth/Login/index.vue
Labels: size/S

#1110 Automated cherry pick of #1108: feat: update login page layout
  src/sections/Auth/Login/assets/login-bg.png
  src/sections/Auth/Login/index.vue
Labels: size/S

#1113 fix(baremetal): mpt2sas driver raid not display
  containers/Compute/views/baremetal/dialogs/Create.vue
Labels: lgtm, approved, size/M, area/compute

#1114 Automated cherry pick of #1113: fix(baremetal): mpt2sas driver raid not display
  containers/Compute/views/baremetal/dialogs/Create.vue
Labels: lgtm, size/M

#1116 Automated cherry pick of #1113: fix(baremetal): mpt2sas driver raid not display
  containers/Compute/views/baremetal/dialogs/Create.vue
Labels: size/M

#1115 Automated cherry pick of #1113: fix(baremetal): mpt2sas driver raid not display
  containers/Compute/views/baremetal/dialogs/Create.vue
Labels: lgtm, size/M

#1117 fix: monitor commonalert create table pager show NaN
  containers/Monitor/views/commonalert/components/alert/index.vue
Labels: area/monitor, size/XS

#1118 Automated cherry pick of #1117: fix: monitor commonalert create table pager show NaN
  containers/Monitor/views/commonalert/components/alert/index.vue
Labels: size/XS

#1119 fix: optimize os select component
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
Labels: area/compute, size/S

#1120 Automated cherry pick of #1119: fix: optimize os select component
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
Labels: size/S

#1121 Automated cherry pick of #1119: fix: optimize os select component
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
Labels: size/S

#1122 fix: create eip provider filter
  containers/Network/views/eip/create/index.vue
Labels: area/compute, size/S

#1123 Automated cherry pick of #1122: fix: create eip provider filter
  containers/Network/views/eip/create/index.vue
Labels: size/S

#1124 [WIP] feat(baremetal): support adaptec raid
  containers/Compute/views/baremetal/dialogs/Create.vue
Labels: size/S, do-not-merge/work-in-progress

#1125 Automated cherry pick of #1124: feat(baremetal): support adaptec raid
  containers/Compute/views/baremetal/dialogs/Create.vue
Labels: size/S

#1126 fix[3.7]: fix price comparator sku filter
  containers/Cloudenv/views/server-price-comparator/create/form/Public.vue
  containers/Cloudenv/views/server-price-comparator/create/form/mixin.js
Labels: area/cloudenv, size/XS

#1127 Automated cherry pick of #1126: fix[3.7]: fix price comparator sku filter
  containers/Cloudenv/views/server-price-comparator/create/form/Public.vue
  containers/Cloudenv/views/server-price-comparator/create/form/mixin.js
Labels: size/XS

#1128 Automated cherry pick of #1126: fix[3.7]: fix price comparator sku filter
  containers/Cloudenv/views/server-price-comparator/create/form/Public.vue
  containers/Cloudenv/views/server-price-comparator/create/form/mixin.js
Labels: size/XS

#1130 fix: login padding
  src/sections/Auth/Login/index.vue
Labels: size/XS

#1131 Automated cherry pick of #1130: fix: login padding
  src/sections/Auth/Login/index.vue
Labels: size/XS

#1132 Automated cherry pick of #1130: fix: login padding
  src/sections/Auth/Login/index.vue
Labels: size/XS

#1133 fix: login padding top
  src/sections/Auth/Login/index.vue
Labels: size/XS

#1134 Automated cherry pick of #1133: fix: login padding top
  src/sections/Auth/Login/index.vue
Labels: size/XS

#1135 Automated cherry pick of #1133: fix: login padding top
  src/sections/Auth/Login/index.vue
Labels: size/XS
