Repository yunionio/dashboard, pull requests merged in 2021-08, with the labels that each got.

#665 Feature/tb baremetal install monitor agent
  containers/Compute/views/baremetal/sidepage/Monitor.vue
  containers/Compute/views/baremetal/sidepage/index.vue
Labels: size/M

#691 fix: 项目选项更新时，显示不全
  src/components/SearchBox/Tag.vue
Labels: size/XS

#692 Automated cherry pick of #691: fix: 项目选项更新时，显示不全
  src/components/SearchBox/Tag.vue
Labels: size/XS

#694 Feat/glb r 3.8 mongodb
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/router/index.js
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/mongodb/constants/index.js
  containers/DB/views/mongodb/index.vue
  containers/DB/views/mongodb/mixins/columns.js
  containers/DB/views/mongodb/mixins/singleActions.js
  containers/DB/views/mongodb/sidepage/BackupList.vue
  containers/DB/views/mongodb/sidepage/Detail.vue
  containers/DB/views/mongodb/sidepage/index.vue
  scope/assets/mongodb.svg
  src/constants/expectStatus.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/db, size/XL

#696 feat: webapp只有选择azure平台展示及UI策略支持
  containers/Compute/router/index.js
Labels: size/XS

#697 feat: 物理机列表增加状态统计
  containers/Compute/views/physicalmachine/components/List.vue
  containers/Compute/views/physicalmachine/index.vue
  src/mixins/resStatisticsMixin.js
Labels: size/L

#695 新建免密登录用户,默认显示自己
  containers/Cloudenv/views/clouduser/components/List.vue
  containers/Cloudenv/views/clouduser/dialogs/Create.vue
  containers/Cloudenv/views/samluser/components/List.vue
  containers/Cloudenv/views/samluser/dialogs/Create.vue
Labels: area/cloudenv, size/M

#698 feat: update 计算模块资源增加状态统计条
  containers/Compute/views/baremetal/components/List.vue
  containers/Compute/views/baremetal/index.vue
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/index.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/index.vue
  src/mixins/resStatusFilterMixin.js
Labels: size/L

#699 fix: 云账号导出的参数项应与自定义列表的参数项一致，目前缺少域、项目等信息
  containers/Cloudenv/views/cloudaccount/components/List.vue
Labels: size/S

#700 Automated cherry pick of #699: fix: 云账号导出的参数项应与自定义列表的参数项一致，目前缺少域、项目等信息
  containers/Cloudenv/views/cloudaccount/components/List.vue
Labels: size/S

#706 feat: RDS、REDIS列表增加状态统计
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/index.vue
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/index.vue
Labels: size/M

#707 feat: 支持数据自定义处理
  src/mixins/resStatisticsMixin.js
Labels: size/M

#701 fix: enable openstack vm migrate
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Compute/views/vminstance/utils.js
Labels: size/S

#702 Automated cherry pick of #701: fix: enable openstack vm migrate
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Compute/views/vminstance/utils.js
Labels: size/S

#704 fix: show file system tags
  containers/Storage/views/file-system/mixins/columns.js
  containers/Storage/views/file-system/sidepage/Detail.vue
Labels: size/XS

#705 Automated cherry pick of #704: fix: show file system tags
  containers/Storage/views/file-system/mixins/columns.js
  containers/Storage/views/file-system/sidepage/Detail.vue
Labels: size/XS

#708 feat(dashboard): add userinfo panel
  containers/Dashboard/extends/UserInfo/index.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/sections/ExtendGallery/config.js
  scope/assets/res-user2.svg
Labels: area/dashboard, size/L

#713 totp qr image display fix
  src/sections/Auth/BindSecret.vue
  src/store/modules/auth.js
Labels: area/dashboard, size/XS

#714 Automated cherry pick of #713: totp qr image display fix
  src/sections/Auth/BindSecret.vue
  src/store/modules/auth.js
Labels: size/XS

#711 fix(cloudenv): add account domain check
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
Labels: area/cloudenv, size/XS

#712 Feat/glb r 3.8 add userinfo panel
  containers/Dashboard/locales/en.json
Labels: size/XS

#715 feat: hidden yaml tpl
  containers/Helm/views/chart/create/index.vue
Labels: size/XS

#717 fix: 修复主机创建系统盘容量检测问题
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/M

#718 Automated cherry pick of #717: fix: 修复主机创建系统盘容量检测问题
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/M

#719 Automated cherry pick of #717: fix: 修复主机创建系统盘容量检测问题
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/M

#720 feat(#2212): 新建主机时，选择平台，过滤相应的宿主机，用宿主机的网络来过滤可用的虚拟机网络
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#721 Automated cherry pick of #720: feat(#2212): 新建主机时，选择平台，过滤相应的宿主机，用宿主机的网络来过滤可用的虚拟机网络
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#724 Automated cherry pick of #722: fix: update redis status i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#723 Automated cherry pick of #722: fix: update redis status i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#722 fix: update redis status i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#725 feat(dashboard): modify currency opts
  containers/Dashboard/extends/ConsumptionPercent/components/Brand.vue
  containers/Dashboard/extends/ConsumptionPercent/components/Resource.vue
  containers/Dashboard/extends/ConsumptionTrend/index.vue
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsOverview/index.vue
  containers/Dashboard/sections/ConsumptionConfig/index.vue
  src/constants/currency.js
  src/store/modules/common.js
  src/utils/common/cookie.js
Labels: area/dashboard, size/L

#726 Automated cherry pick of #725: feat(dashboard): modify currency opts
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsOverview/index.vue
  src/constants/currency.js
  src/store/modules/common.js
  src/utils/common/cookie.js
Labels: size/L

#727 Feat/glb r 3.8 add userinfo panel
  containers/Dashboard/extends/UserInfo/index.vue
Labels: area/dashboard, size/XS

#728 feat(bill): adjust bill currency opts
  src/store/modules/common.js
Labels: size/S

#729 Automated cherry pick of #728: feat(bill): adjust bill currency opts
  src/store/modules/common.js
Labels: size/S

#731 fix: change route global config repeat relod
  src/permission.js
Labels: size/XS

#732 Automated cherry pick of #731: fix: change route global config repeat relod
  src/permission.js
Labels: size/XS

#736 add huawei private cloud account create page
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HuaweiCloudStack.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
  scope/assets/huaweicloudstack.svg
  scope/locales/en.json
  scope/locales/zh-CN.json
  src/assets/images/providers/huaweicloudstack.svg
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/dashboard, size/L

#734 fix(dashboard): modify userInfo panel username
  containers/Dashboard/extends/UserInfo/index.vue
Labels: area/dashboard, size/XS

#735 Feat/glb r 3.8 extend alert record
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/alertrecord/mixins/columns.js
  containers/Monitor/views/commonalert/sidepage/index.vue
Labels: area/monitor, size/L

#733 fix(utils): add details check before the secend fetch
  src/utils/list.js
Labels: size/XS

#739 Automated cherry pick of #736: add huawei private cloud account create page
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HuaweiCloudStack.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
  scope/assets/huaweicloudstack.svg
  scope/locales/en.json
  scope/locales/zh-CN.json
  src/assets/images/providers/huaweicloudstack.svg
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XL

#741 feat: add hcso
  containers/DB/sections/ItemArea.vue
  containers/Network/views/nats/create/index.vue
Labels: size/XS

#743 fix(cloudenv): bind local user
  containers/Cloudenv/views/clouduser/components/UserSelect.vue
  containers/Cloudenv/views/clouduser/dialogs/ChangeOwner.vue
  containers/Cloudenv/views/samluser/components/UserSelect.vue
Labels: size/M, area/cloudenv

#745 修复个人信息查询权限
  src/views/clouduser/components/ClouduserList.vue
  src/views/clouduser/components/SamluserList.vue
  src/views/clouduser/index.vue
Labels: size/XS

#746 Automated cherry pick of #745: 修复个人信息查询权限
  src/views/clouduser/components/ClouduserList.vue
  src/views/clouduser/components/SamluserList.vue
  src/views/clouduser/index.vue
Labels: size/XS

#747 Automated cherry pick of #745: 修复个人信息查询权限
  src/views/clouduser/components/ClouduserList.vue
  src/views/clouduser/components/SamluserList.vue
  src/views/clouduser/index.vue
Labels: size/XS

#744 feat: server data sync loading
  containers/Compute/views/disk-recovery/mixins/columns.js
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/utils/columns.js
  containers/Compute/views/gpu/mixins/columns.js
  containers/Compute/views/host-image/mixins/columns.js
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/instance-group/mixins/columns.js
  containers/Compute/views/physicalmachine/mixins/columns.js
  containers/Compute/views/scaling-group/mixins/columns.js
  containers/Compute/views/secgroup/mixins/columns.js
  containers/Compute/views/server-recovery/mixins/columns.js
  containers/Compute/views/servertemplate/mixins/columns.js
  containers/Compute/views/sku/mixins/columns.js
  containers/Compute/views/snapshot-instance/mixins/columns.js
  containers/Compute/views/snapshot/mixins/columns.js
  containers/Compute/views/snapshotpolicy/mixins/columns.js
  containers/Compute/views/snapshotpolicy/sidepage/Cache.vue
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/webapp/mixins/columns.js
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/utils/columns.js
  containers/Network/views/network/mixins/columns.js
  src/components/DataLoading/index.js
  src/components/Icon/assets/loading.svg
  src/mixins/list.js
  src/utils/common/tableColumn.js
  src/utils/list.js
Labels: size/L

#748 fix(cloudenv): modify api for clouduser userselect
  containers/Cloudenv/views/clouduser/components/UserSelect.vue
  containers/Cloudenv/views/samluser/components/UserSelect.vue
Labels: size/M, area/cloudenv

#751 huawei private resources create actions
  containers/Cloudenv/views/cloudaccount/create/index.vue
  containers/Cloudenv/views/server-price-comparator/create/form/Private.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/utils.js
  containers/Network/views/eip/create/components/BottomBar.vue
  containers/Network/views/eip/create/index.vue
  containers/Network/views/lb/create/form/Private.vue
  containers/Network/views/lb/create/form/mixin.js
  containers/Network/views/loadbalancerbackend/components/List.vue
  containers/Network/views/loadbalancerbackendgroup/components/List.vue
  containers/Network/views/loadbalancerlistener/components/List.vue
  containers/Network/views/loadbalancerlistener/constants.js
  containers/Network/views/loadbalancerlistener/dialogs/Form.vue
  containers/Network/views/loadbalancerlistenerrule/components/List.vue
Labels: lgtm, area/dashboard, size/L

#749 fix: variable errors when list without details
  containers/Compute/views/disk/mixins/columns.js
  containers/K8S/views/nodes/mixins/columns.js
  containers/Network/views/lb/mixins/singleActions.js
  containers/Network/views/vpc/mixins/singleActions.js
Labels: size/S

#753 feat: server data sync loading
  containers/Cloudenv/views/dynamicschedtag/mixins/columns.js
  containers/Cloudenv/views/schedpolicy/mixins/columns.js
  containers/Cloudenv/views/schedtag/mixins/columns.js
  containers/Cloudenv/views/schedtag/utils/columns.js
  containers/Compute/views/disk-recovery/mixins/columns.js
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/utils/columns.js
  containers/Compute/views/gpu/mixins/columns.js
  containers/Compute/views/host-image/mixins/columns.js
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/keypair/mixins/columns.js
  containers/Compute/views/physicalmachine/mixins/columns.js
  containers/Compute/views/server-recovery/mixins/columns.js
  containers/Compute/views/snapshot/mixins/columns.js
  containers/Compute/views/snapshot/utils/columns.js
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/utils/columns.js
  containers/Network/views/network/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/L

#755 huawei cloud stack fix
  containers/Compute/constants/index.js
  containers/Compute/sections/SchedPolicy/index.vue
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Network/views/network/Create.vue
  containers/Network/views/vpc/create/index.vue
  src/constants/compute.js
Labels: area/dashboard, size/L

#756 Automated cherry pick of #755: huawei cloud stack fix
  containers/Compute/constants/index.js
  containers/Compute/sections/SchedPolicy/index.vue
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Network/views/network/Create.vue
  containers/Network/views/vpc/create/index.vue
  src/constants/compute.js
Labels: size/L

#757 huawei cloud stack fix
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: area/dashboard, size/XS

#761 Automated cherry pick of #750: feature: add a eip sidepage to server
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/vminstance/sidepage/EipList.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/Network/views/eip/components/List.vue
Labels: size/L

#750 Feature/qj server add eip sidepage
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/vminstance/sidepage/EipList.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/Network/views/eip/components/List.vue
Labels: size/L

#759 Temperature monitor
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/monitor/AgentMonitor.vue
  containers/Compute/sections/monitor/AgentTemperatureMonitor.vue
  containers/Compute/sections/monitor/BaseMonitor.vue
  containers/Compute/views/baremetal/sidepage/Monitor.vue
  containers/Compute/views/vminstance/components/InstallAgentFormVisible.vue
  containers/Compute/views/vminstance/constants.js
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  src/sections/Charts/Lines.vue
  src/sections/Monitor/List.vue
  src/sections/Monitor/index.vue
  src/utils/monitor.js
Labels: lgtm, size/XXL

#760 Automated cherry pick of #759: feat(monitor): temperature monitor
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/monitor/AgentMonitor.vue
  containers/Compute/sections/monitor/AgentTemperatureMonitor.vue
  containers/Compute/sections/monitor/BaseMonitor.vue
  containers/Compute/views/baremetal/sidepage/Monitor.vue
  containers/Compute/views/vminstance/components/InstallAgentFormVisible.vue
  containers/Compute/views/vminstance/constants.js
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  src/sections/Charts/Lines.vue
  src/sections/Monitor/List.vue
  src/sections/Monitor/index.vue
  src/utils/monitor.js
Labels: size/XXL

#762 mongodb去除访问方式
  containers/DB/views/mongodb/sidepage/Detail.vue
Labels: area/db, size/XS

#763 fix: enable hcso saml auth
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#764 Automated cherry pick of #763: fix: enable hcso saml auth
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#765 调整mongodb实例类型
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/mongodb/constants/index.js
  containers/DB/views/mongodb/sidepage/BackupList.vue
  containers/DB/views/mongodb/sidepage/Detail.vue
Labels: area/db, size/S

#766 huawei private cloud adjust config
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/SKU/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/M, area/dashboard

#767 Automated cherry pick of #766: huawei private cloud adjust config
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/SKU/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/M

#768 object download
  containers/Storage/views/bucket/sidepage/Objects.vue
Labels: area/storage

#772 add route for hcso
  containers/DB/router/index.js
  containers/Monitor/router/index.js
  containers/Network/router/index.js
  containers/Storage/router/index.js
Labels: area/dashboard, size/S

#773 Automated cherry pick of #772: add route for hcso
  containers/DB/router/index.js
  containers/Monitor/router/index.js
  containers/Network/router/index.js
  containers/Storage/router/index.js
Labels: size/S

#770 修复编排-虚拟机实例无数据时默认值问题
  containers/Helm/views/vm-release/sidepage/index.vue
Labels: area/helm, size/XS

#771 Automated cherry pick of #770: 修复编排-虚拟机实例无数据时默认值问题
  containers/Helm/views/vm-release/sidepage/index.vue
Labels: size/XS

#774 修复硬盘操作对华为私有云平台的验证
  containers/Compute/views/disk/utils/index.js
Labels: area/compute, size/S

#775 Automated cherry pick of #774: 修复硬盘操作对华为私有云平台的验证
  containers/Compute/views/disk/utils/index.js
Labels: size/S

#776 adjust config fix
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: area/dashboard, size/XS

#778 server price compare fix
  containers/Cloudenv/views/server-price-comparator/create/components/SystemDisk.vue
Labels: area/dashboard, size/XS

#780 Bugfix/tb bugfix 0811502
  containers/Cloudenv/router/index.js
  containers/Helm/router/index.js
Labels: area/k8s, size/XS

#781 Automated cherry pick of #780: add cloudgroup for huaweicloudstack
  containers/Cloudenv/router/index.js
  containers/Helm/router/index.js
Labels: size/XS

#783 fix(db): mongodb event-drawer add filter
  containers/DB/views/mongodb/sidepage/BackupList.vue
  containers/DB/views/mongodb/sidepage/index.vue
Labels: area/db, size/XS

#785 Automated cherry pick of #784: fix(cloudenv): change cloudenv resource_name field
  containers/Cloudenv/views/cloudevent/components/List.vue
Labels: area/cloudenv

#784 Fix/glb r 3.7 modify cloudevent resourcename field
  containers/Cloudenv/views/cloudevent/components/List.vue
Labels: area/cloudenv, size/S

#786 add monitor resource i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/monitor, size/S

#787 Automated cherry pick of #786: 添加资源翻译
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#788 add default dns setting
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/HuaweiCloudStack.vue
Labels: area/dashboard, size/S

#789 Automated cherry pick of #788: add default dns setting
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/HuaweiCloudStack.vue
Labels: size/S

#790 ajust config fix
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: area/dashboard, size/XS

#792 修改MongoDB备份列表展示
  containers/DB/views/mongodb/sidepage/BackupList.vue
Labels: size/M, area/db

#793 调整dashboard磁贴样式
  containers/Dashboard/extends/Log/index.vue
  containers/Dashboard/extends/NumberCard/components/K8s.vue
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/extends/Ring/components/K8s.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
  containers/Dashboard/styles/index.less
  containers/Dashboard/views/dashboard/components/Content.vue
  containers/Dashboard/views/edit/index.vue
Labels: area/dashboard, size/L

#794 Automated cherry pick of #793: 调整dashboard磁贴样式
  containers/Dashboard/extends/Log/index.vue
  containers/Dashboard/extends/NumberCard/components/K8s.vue
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/extends/Ring/components/K8s.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
  containers/Dashboard/styles/index.less
  containers/Dashboard/views/dashboard/components/Content.vue
  containers/Dashboard/views/edit/index.vue
Labels: size/L

#795 fix(helm): get chart by version
  containers/Helm/views/chart/create/index.vue
Labels: area/helm, size/S

#798 feat(compute): add medium_type for kvm local disk
  containers/Cloudenv/views/server-price-comparator/create/components/SystemDisk.vue
  containers/Compute/constants/index.js
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/K8S/views/cluster/create/index.vue
  src/constants/compute.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/compute, size/L

#799 fix: azure dtu
  containers/DB/views/rds/mixins/columns.js
Labels: size/XS

#800 fix: 账单访问信息引用字段错误，应为关联账号
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
Labels: size/XS

#801 Automated cherry pick of #800: fix: 账单访问信息引用字段错误，应为关联账号
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
Labels: size/XS

#804 add capacity
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/lb/sidepage/Detail.vue
Labels: area/network, size/S

#805 update setup ssh form
  containers/Compute/views/vminstance/create/form/SetupSSHForm.vue
Labels: area/network, size/XS

#807 batch install agent
  containers/Compute/views/baremetal/components/List.vue
  src/constants/permission.js
Labels: area/compute, size/S

#808 Automated cherry pick of #807: batch install agent
  containers/Compute/views/baremetal/components/List.vue
  src/constants/permission.js
Labels: size/S

#809 monitor query data add limit offset
  containers/Monitor/sections/MonitorLine/index.vue
  containers/Monitor/views/dashboard/create/index.vue
  containers/Monitor/views/explorer/components/index.vue
Labels: size/M, area/monitor

#810 Automated cherry pick of #809: monitor query data add limit offset
  containers/Monitor/sections/MonitorLine/index.vue
  containers/Monitor/views/dashboard/create/index.vue
  containers/Monitor/views/explorer/components/index.vue
Labels: size/M

#811 monitor query data add limit offset
  containers/Monitor/views/dashboard/create/index.vue
Labels: area/monitor, size/XS

#815 feat: update menu icon and refresh i18n
  containers/Cloudenv/router/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#816 Automated cherry pick of #815: feat: update menu icon and refresh i18n
  containers/Cloudenv/router/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#813 修磁贴内容多溢出问题
  containers/Dashboard/extends/Ring/components/Server.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M, area/dashboard

#814 Automated cherry pick of #813: 修磁贴内容多溢出问题
  containers/Dashboard/extends/Ring/components/Server.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#817 feat: remove refresh
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#818 Automated cherry pick of #817: feat: remove refresh
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#819 Bugfix/tb bugfix 082001
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Network/views/ssh-proxy/form/index.vue
Labels: size/S

#820 Automated cherry pick of #819: monitoroverview watch scope change
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Network/views/ssh-proxy/form/index.vue
Labels: size/M

#821 feat: add cdn
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/cdn/components/List.vue
  containers/Network/views/cdn/index.vue
  containers/Network/views/cdn/mixins/columns.js
  containers/Network/views/cdn/mixins/singleActions.js
  containers/Network/views/cdn/sidepage/Detail.vue
  containers/Network/views/cdn/sidepage/index.vue
  scope/assets/res-cdn-domain.svg
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XL

#824 feat: update params and i18n
  src/utils/http.js
  src/utils/i18n.js
Labels: size/S

#822 robots label
  src/components/BaseSelect/OptionLabel.js
Labels: area/dashboard, size/S

#823 fix: cdn domain info
  containers/Network/views/cdn/components/List.vue
  src/components/Detail/index.js
  src/components/Status/index.vue
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#826 Bugfix/tb bugfix 082401
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/vminstance/constants.js
  src/utils/common/tableFilter.js
Labels: size/M, area/compute

#827 Automated cherry pick of #826: basic monitor chart add mem used percent
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/vminstance/constants.js
  src/utils/common/tableFilter.js
Labels: size/M

#828 image overview summary
  containers/Monitor/views/overview/components/SummaryCards.vue
Labels: area/monitor, size/S

#829 Automated cherry pick of #828: image overview summary
  containers/Monitor/views/overview/components/SummaryCards.vue
Labels: size/S

#830 fix: menu icon
  scope/assets/menu-multicloud.svg
Labels: size/XS

#831 Automated cherry pick of #830: fix: menu icon
  scope/assets/menu-multicloud.svg
Labels: size/XS

#832 Automated cherry pick of #830: fix: menu icon
  scope/assets/menu-multicloud.svg
Labels: size/XS

#839 Automated cherry pick of #838: fix: menu icon
  scope/assets/copy.svg
  scope/assets/dashboard-fee.svg
  scope/assets/dashboard-log.svg
  scope/assets/dashboard-notice.svg
  scope/assets/dashboard-number.svg
  scope/assets/dashboard-resource.svg
  scope/assets/dashboard-suggest-detail.svg
  scope/assets/dashboard-suggest-overview.svg
  scope/assets/dashboard-top5.svg
  scope/assets/dashboard-usage.svg
  scope/assets/data-empty.svg
  scope/assets/download.svg
  scope/assets/help.svg
  scope/assets/refresh.svg
  scope/assets/search.svg
  scope/assets/setting.svg
Labels: size/M

#840 Automated cherry pick of #838: fix: menu icon
  scope/assets/copy.svg
  scope/assets/dashboard-fee.svg
  scope/assets/dashboard-log.svg
  scope/assets/dashboard-notice.svg
  scope/assets/dashboard-number.svg
  scope/assets/dashboard-resource.svg
  scope/assets/dashboard-suggest-detail.svg
  scope/assets/dashboard-suggest-overview.svg
  scope/assets/dashboard-top5.svg
  scope/assets/dashboard-usage.svg
  scope/assets/data-empty.svg
  scope/assets/download.svg
  scope/assets/help.svg
  scope/assets/refresh.svg
  scope/assets/search.svg
  scope/assets/setting.svg
Labels: size/M

#836 fit: add cloudpods vm op
  containers/Compute/views/vminstance/utils.js
Labels: size/S

#837 Automated cherry pick of #836: fit: add cloudpods vm op
  containers/Compute/views/vminstance/utils.js
Labels: size/S

#842 Automated cherry pick of #841: feat: update icon
  src/styles/less/global.less
Labels: size/XS

#843 Automated cherry pick of #841: feat: update icon
  src/styles/less/global.less
Labels: size/XS

#896 fix(rds): fix rds rds_conn param
  containers/DB/constants/index.js
Labels: size/XS

#897 Automated cherry pick of #896: fix(rds): fix rds rds_conn param
  containers/DB/constants/index.js
Labels: size/XS

#898 Automated cherry pick of #896: fix(rds): fix rds rds_conn param
  containers/DB/constants/index.js
Labels: size/XS

#899 Automated cherry pick of #896: fix(rds): fix rds rds_conn param
  containers/DB/constants/index.js
Labels: size/XS

#900 fix: update dashboard theme color
  containers/Dashboard/extends/UserInfo/index.vue
  containers/Dashboard/views/dashboard/components/Header.vue
Labels: size/S

#901 Automated cherry pick of #900: fix: update dashboard theme color
  containers/Dashboard/extends/UserInfo/index.vue
  containers/Dashboard/views/dashboard/components/Header.vue
Labels: size/S

#902 Automated cherry pick of #900: fix: update dashboard theme color
  containers/Dashboard/views/dashboard/components/Header.vue
Labels: size/XS

#903 fix: 功能选择文案优化
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#904 Automated cherry pick of #903: fix: 功能选择文案优化
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#905 Automated cherry pick of #903: fix: 功能选择文案优化
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#906 feat: Error Message 增加time字段用来方便定位问题具体发生的时间
  src/sections/DialogManager/components/Error.vue
Labels: size/XS

#908 feat: 全局搜索范围增加LB支持
  src/constants/globalSearch.js
Labels: size/XS

#909 Automated cherry pick of #908: feat: 全局搜索范围增加LB支持
  src/constants/globalSearch.js
Labels: size/XS

#911 扩展名字列表列
  scope/assets/res-month.svg
  scope/assets/res-resourcetype.svg
  src/utils/common/tableColumn.js
Labels: size/XS

#912 Automated cherry pick of #911: 扩展名字列表列
  scope/assets/res-month.svg
  scope/assets/res-resourcetype.svg
  src/utils/common/tableColumn.js
Labels: size/XS

#916 fix: 渠道下放到域预算告警机器人改为下拉列表
  src/sections/NotifyTypes/index.vue
Labels: size/M

#917 Automated cherry pick of #916: fix: 渠道下放到域预算告警机器人改为下拉列表
  src/sections/NotifyTypes/index.vue
Labels: size/M

#913 fix(dashboard): modify top5 30 minutes
  containers/Dashboard/views/dashboard/config/default.js
  containers/Dashboard/views/dashboard/config/public-default.js
Labels: area/dashboard, size/S

#914 Automated cherry pick of #913: fix(dashboard): modify top5 30 minutes
  containers/Dashboard/views/dashboard/config/default.js
  containers/Dashboard/views/dashboard/config/public-default.js
Labels: size/S

#915 Automated cherry pick of #913: fix(dashboard): modify top5 30 minutes
  containers/Dashboard/views/dashboard/config/default.js
  containers/Dashboard/views/dashboard/config/public-default.js
Labels: size/S

#921 fix(dashboard): modfify dashboard userinfo color
  containers/Dashboard/extends/Ring/components/K8s.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/UserInfo/index.vue
Labels: area/dashboard, size/XS

#922 Automated cherry pick of #921: fix(dashboard): modfify dashboard userinfo color
  containers/Dashboard/extends/Ring/components/K8s.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/UserInfo/index.vue
Labels: size/XS

#918 fix(dashboard): fix top5 host
  containers/Dashboard/extends/Top5/index.vue
Labels: area/dashboard, size/S

#919 Automated cherry pick of #918: fix(dashboard): fix top5 host
  containers/Dashboard/extends/Top5/index.vue
Labels: size/S

#920 Automated cherry pick of #918: fix(dashboard): fix top5 host
  containers/Dashboard/extends/Top5/index.vue
Labels: size/S

#923 Automated cherry pick of #921: fix(dashboard): modfify dashboard userinfo color
  containers/Dashboard/extends/Ring/components/K8s.vue
  containers/Dashboard/extends/Ring/components/Server.vue
Labels: size/XS
