Repository yunionio/dashboard, pull requests merged in 2021-12, with the labels that each got.

#1629 feat: add hypervisors and update hypervisor map
  src/constants/index.js
Labels: size/M

#1631 feat: server support hostname
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/HostName/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/M

#1632 feat: pairs tags
  containers/Compute/views/vminstance/components/List.vue
  containers/IAM/views/policy/Update.vue
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/mixins/columns.js
  containers/IAM/views/projects/components/List.vue
  src/components/DraggableTransfer/index.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/TreeConfig.vue
  src/sections/TreeProject/index copy.vue
  src/sections/TreeProject/index.vue
  src/store/getters.js
  src/store/modules/projectTags.js
  src/utils/common/tableColumn.js
  src/utils/list.js
Labels: area/compute, size/XXL

#1634 fix(vminstance): wrong default machine type of aarch64 vm
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/S

#1635 Automated cherry pick of #1634: fix(vminstance): wrong default machine type of aarch64 vm
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/S

#1636 feat: pairs tags
  containers/Compute/views/vminstance/components/List.vue
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/projects/components/List.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/PairsTag/index.vue
  src/sections/TreeProject/index copy.vue
  src/sections/TreeProject/index.vue
Labels: area/compute, size/L

#1637 fix: page list checkbox show
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
Labels: area/helm, size/XS

#1638 Automated cherry pick of #1637: fix: page list checkbox show
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
Labels: size/XS

#1639 feat: pairs tags
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/TreeProject/index.vue
Labels: area/compute, size/S

#1640 Fix/glb to 3.8/helm
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
Labels: size/XS

#1641 Automated cherry pick of #1640: fix: pageList checkbox show
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
Labels: size/XS

#1642 Fix/glb to 3.8/helm
  containers/Compute/views/image/dialogs/Create.vue
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
  src/views/workflow-technical-support/me-process/components/List.vue
Labels: area/helm, size/S

#1643 Automated cherry pick of #1642: fix: pageList checkbox show
  containers/Compute/views/image/dialogs/Create.vue
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
  src/views/workflow-technical-support/me-process/components/List.vue
Labels: size/S

#1646 fix: #8017 开源版目前还是使用的原来路径，需修改为开源网站的路径
  containers/Cloudenv/views/cloudaccount/constants.js
  src/utils/utils.js
Labels: size/S

#1647 Automated cherry pick of #1646: fix: #8017 开源版目前还是使用的原来路径，需修改为开源网站的路径
  containers/Cloudenv/views/cloudaccount/constants.js
  src/utils/utils.js
Labels: size/S

#1645 feat: timeout auto logout
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/App.vue
  src/mixins/logout.js
  src/store/modules/auth.js
  src/store/modules/common.js
Labels: size/L

#1649 feat: baremetal description
  containers/Compute/views/baremetal/create/index.vue
  containers/Network/views/waf/mixins/columns.js
  src/components/PageList/components/Header.vue
Labels: area/compute, size/XS

#1651 fix: user tag tree should not use user-metaddata filter
  src/sections/TagSelect/index.vue
  src/sections/TreeProject/index.vue
Labels: size/XS

#1652 fix: helm license check
  containers/Helm/router/index.js
Labels: area/helm, size/S

#1653 Automated cherry pick of #1652: fix: helm license check
  containers/Helm/router/index.js
Labels: size/S

#1655 fix: #8019 导入安全组规则时下载模板报错
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/mixins/singleActions.js
  containers/Compute/views/secgroup/utils/index.js
Labels: size/M

#1656 Automated cherry pick of #1655: fix: #8019 导入安全组规则时下载模板报错
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/mixins/singleActions.js
  containers/Compute/views/secgroup/utils/index.js
Labels: size/M

#1657 Automated cherry pick of #1655: fix: #8019 导入安全组规则时下载模板报错
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/mixins/singleActions.js
  containers/Compute/views/secgroup/utils/index.js
Labels: size/M

#1659 feat: pairs tag
  src/components/PageList/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/TreeProject/index.vue
Labels: size/M, area/compute

#1660 feat: #3505 安全组列表增加缓存数量信息，方便删除判断
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/secgroup/mixins/columns.js
Labels: size/S

#1661 Automated cherry pick of #1660: feat: #3505 安全组列表增加缓存数量信息，方便删除判断
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/secgroup/mixins/columns.js
Labels: size/S

#1662 feat: pairs tag
  containers/IAM/views/policy/sidepage/Detail.vue
  src/sections/TagSelect/index.vue
  src/sections/TreeProject/index.vue
  src/utils/list.js
Labels: size/M, area/compute

#1663 feat: waf description filter
  containers/Network/views/waf/components/List.vue
  src/components/PageList/components/Header.vue
Labels: area/network, size/XS

#1664 feat: create secgroup support set tags
  containers/Compute/views/secgroup/components/Direction.vue
  containers/Compute/views/secgroup/dialogs/Create.vue
  containers/Compute/views/secgroup/sidepage/Cache.vue
  containers/Compute/views/secgroup/sidepage/InDirection.vue
  containers/Compute/views/secgroup/sidepage/OutDirection.vue
  containers/Compute/views/secgroup/sidepage/Server.vue
  containers/Compute/views/secgroup/sidepage/index.vue
Labels: size/M, area/compute

#1666 Automated cherry pick of #1664: feat: create secgroup support set tags
  containers/Compute/views/secgroup/components/Direction.vue
  containers/Compute/views/secgroup/dialogs/Create.vue
  containers/Compute/views/secgroup/sidepage/Cache.vue
  containers/Compute/views/secgroup/sidepage/InDirection.vue
  containers/Compute/views/secgroup/sidepage/OutDirection.vue
  containers/Compute/views/secgroup/sidepage/Server.vue
  containers/Compute/views/secgroup/sidepage/index.vue
Labels: size/M

#1667 fix: checkbox flag condition
  src/components/PageList/components/Table.vue
Labels: size/XS

#1668 Automated cherry pick of #1667: fix: checkbox flag condition
  src/components/PageList/components/Table.vue
Labels: size/XS

#1670 fix: add network options to sync
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/XS

#1672 fix: add more sync range options
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/XS

#1673 feat[3.9]: compute action hidden
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/M, area/compute

#1674 fix: monitor overview data show
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: area/monitor, size/S

#1675 Automated cherry pick of #1674: fix: monitor overview data show
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/S

#1676 fix: project tags first render
  src/utils/list.js
Labels: area/compute, size/XS

#1677 feat: #3499 add vpc peer connect
  containers/Network/router/index.js
  containers/Network/views/vpc-peer-connect/components/List.vue
  containers/Network/views/vpc-peer-connect/index.vue
  containers/Network/views/vpc-peer-connect/mixins/columns.js
  containers/Network/views/vpc-peer-connect/mixins/singleActions.js
  containers/Network/views/vpc-peer-connect/sidepage/Detail.vue
  containers/Network/views/vpc-peer-connect/sidepage/Vpc.vue
  containers/Network/views/vpc-peer-connect/sidepage/index.vue
  src/components/Detail/index.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XL

#1680 feat: #3523 将block_stream状态的主机的状态标记为运行中
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#1682 Automated cherry pick of #1680: feat: #3523 将block_stream状态的主机的状态标记为运行中
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#1679 feat: action add tooltip
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/dialogs/Delete.vue
  containers/Compute/views/image/mixins/singleActions.js
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/mixins/singleActions.js
  containers/Compute/views/secgroup/sidepage/Cache.vue
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
  containers/Compute/views/vminstance/dialogs/ResourceFee.vue
  containers/Compute/views/vminstance/dialogs/ResourceRenewFee.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/mixins/singleActions.js
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/dialogs/ClearData.vue
  containers/DB/views/redis/mixins/singleActions.js
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/lbacls/components/List.vue
  containers/Network/views/lbacls/mixins/singleActions.js
  containers/Network/views/lbcerts/components/List.vue
  containers/Network/views/lbcerts/mixins/singleActions.js
  containers/Network/views/nats/components/List.vue
  containers/Network/views/nats/mixins/singleActions.js
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/access-group/components/List.vue
  containers/Storage/views/access-group/mixins/singleActions.js
  containers/Storage/views/access-group/sidepage/Cache.vue
  src/sections/DialogManager/components/AutoRenew.vue
  src/sections/DialogManager/components/Renew.vue
  src/sections/DialogManager/components/SetDuration.vue
Labels: area/compute, size/L

#1681 Automated cherry pick of #1680: feat: #3523 将block_stream状态的主机的状态标记为运行中
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#1683 fix: logout refresh
  src/mixins/logout.js
Labels: size/XS

#1684 feat: pairs tags config
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/TreeConfig.vue
Labels: area/compute, size/L

#1686 Automated cherry pick of #1679: feat: action add tooltip
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/dialogs/Delete.vue
  containers/Compute/views/image/mixins/singleActions.js
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/mixins/singleActions.js
  containers/Compute/views/secgroup/sidepage/Cache.vue
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
  containers/Compute/views/vminstance/dialogs/ResourceFee.vue
  containers/Compute/views/vminstance/dialogs/ResourceRenewFee.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/mixins/singleActions.js
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/dialogs/ClearData.vue
  containers/DB/views/redis/mixins/singleActions.js
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/lbacls/components/List.vue
  containers/Network/views/lbacls/mixins/singleActions.js
  containers/Network/views/lbcerts/components/List.vue
  containers/Network/views/lbcerts/mixins/singleActions.js
  containers/Network/views/nats/components/List.vue
  containers/Network/views/nats/mixins/singleActions.js
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/access-group/components/List.vue
  containers/Storage/views/access-group/mixins/singleActions.js
  containers/Storage/views/access-group/sidepage/Cache.vue
  src/sections/DialogManager/components/AutoRenew.vue
  src/sections/DialogManager/components/Renew.vue
  src/sections/DialogManager/components/SetDuration.vue
Labels: size/L

#1690 fix: pairs tags config
  src/sections/DialogManager/components/TreeConfig.vue
Labels: area/compute, size/XS

#1691 feat: globalvpc support create
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/global-vpc/components/List.vue
  containers/Network/views/global-vpc/create/index.vue
  containers/Network/views/global-vpc/mixins/columns.js
  containers/Network/views/global-vpc/sidepage/Detail.vue
  containers/Network/views/network/Create.vue
  containers/Network/views/vpc/create/index.vue
Labels: area/network, size/L

#1692 Automated cherry pick of #1691: feat: globalvpc support create
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/global-vpc/components/List.vue
  containers/Network/views/global-vpc/create/index.vue
  containers/Network/views/global-vpc/mixins/columns.js
  containers/Network/views/global-vpc/sidepage/Detail.vue
  containers/Network/views/network/Create.vue
  containers/Network/views/vpc/create/index.vue
Labels: size/L

#1693 feat: auto renewal tooltip
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/dns-zonecache/mixins/singleActions.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/compute, size/S

#1694 Automated cherry pick of #1693: feat: auto renewal tooltip
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/dns-zonecache/mixins/singleActions.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#1695 feat: #3219 调用vmrc软件是否可以兼容edge浏览器
  containers/Compute/views/vminstance/mixins/singleActions.js
  package.json
  yarn.lock
Labels: size/XXL

#1696 Automated cherry pick of #1695: feat: #3219 调用vmrc软件是否可以兼容edge浏览器
  containers/Compute/views/vminstance/mixins/singleActions.js
  package.json
  yarn.lock
Labels: size/XXL

#1697 Automated cherry pick of #1695: feat: #3219 调用vmrc软件是否可以兼容edge浏览器
  containers/Compute/views/vminstance/mixins/singleActions.js
  package.json
  yarn.lock
Labels: size/M

#1698 feat: globalvpc support tags-filter
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/global-vpc/components/List.vue
  containers/Network/views/global-vpc/create/index.vue
  containers/Network/views/global-vpc/mixins/columns.js
  containers/Network/views/global-vpc/mixins/singleActions.js
  containers/Network/views/global-vpc/sidepage/Detail.vue
Labels: area/network, size/L

#1699 Automated cherry pick of #1698: feat: globalvpc support tags-filter
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/global-vpc/components/List.vue
  containers/Network/views/global-vpc/create/index.vue
  containers/Network/views/global-vpc/mixins/columns.js
  containers/Network/views/global-vpc/mixins/singleActions.js
  containers/Network/views/global-vpc/sidepage/Detail.vue
Labels: size/L

#1702 fix: #8045 全量同步文案修改
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/cloudprovider/mixins/singleActions.js
  containers/Cloudenv/views/cloudproviderregion/mixins/singleActions.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#1705 Automated cherry pick of #1704: fix: waf scope
  containers/Network/router/index.js
Labels: size/XS

#1706 fix: i18n accuracy
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host-image/components/List.vue
  containers/Compute/views/host-image/mixins/singleActions.js
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/DB/locales/en.json
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Storage/locales/en.json
Labels: size/M, area/compute

#1707 Automated cherry pick of #1706: fix: i18n accuracy
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host-image/components/List.vue
  containers/Compute/views/host-image/mixins/singleActions.js
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/DB/locales/en.json
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Storage/locales/en.json
Labels: size/M

#1708 feat: globalvpc support multiple tags edit
  containers/Network/views/global-vpc/components/List.vue
  containers/Network/views/global-vpc/mixins/singleActions.js
  src/constants/permission.js
Labels: size/M, area/network

#1709 Automated cherry pick of #1708: feat: globalvpc support multiple tags edit
  containers/Network/views/global-vpc/components/List.vue
  containers/Network/views/global-vpc/mixins/singleActions.js
  src/constants/permission.js
Labels: size/M

#1710 fix: #8047 区域同步增加资源类型选择
  containers/Cloudenv/views/cloudproviderregion/mixins/singleActions.js
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/M

#1711 feat: i18n accuracy
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
Labels: area/network, size/S

#1712 Automated cherry pick of #1711: feat: i18n accuracy
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
Labels: size/S

#1714 feat: add route i18n
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/route-table/constants.js
  containers/Network/views/route-table/sidepage/RouteSet.vue
Labels: size/L

#1715 feat: #3519 vpc对接连接路由对接
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/vpc-peer-connect/constants.js
  containers/Network/views/vpc-peer-connect/sidepage/RouteSet.vue
  containers/Network/views/vpc-peer-connect/sidepage/index.vue
Labels: size/L

#1717 fix: update agent install status
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/sidepage/Monitor.vue
  containers/Compute/views/baremetal/sidepage/index.vue
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Compute/views/vminstance/components/InstallAgentFormVisible.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/Monitor/views/monitorresource/sidepage/Monitor.vue
  containers/Monitor/views/monitorresource/sidepage/index.vue
  src/utils/common/tableColumn.js
Labels: area/compute, size/L

#1718 Automated cherry pick of #1717: fix: update agent install status
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/sidepage/Monitor.vue
  containers/Compute/views/baremetal/sidepage/index.vue
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Compute/views/vminstance/components/InstallAgentFormVisible.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  src/utils/common/tableColumn.js
Labels: size/L

#1719 feat: sku add public cloud check
  containers/Compute/router/index.js
Labels: size/XS

#1720 Automated cherry pick of #1719: feat: sku add public cloud check
  containers/Compute/router/index.js
Labels: size/XS

#1723 feat: cloudprovider region support enable switch
  containers/Cloudenv/views/cloudproviderregion/components/List.vue
  containers/Cloudenv/views/cloudproviderregion/mixins/singleActions.js
Labels: size/M, area/cloudenv

#1724 fix: change secgroup create tags required false
  containers/Compute/views/secgroup/dialogs/Create.vue
Labels: area/compute, size/XS

#1725 Automated cherry pick of #1724: fix: change secgroup create tags required false
  containers/Compute/views/secgroup/dialogs/Create.vue
Labels: size/XS

#1729 feat: #3524 aws支持同步natgateway资源
  containers/Network/views/nats/components/List.vue
  containers/Network/views/nats/create/index.vue
  containers/Network/views/nats/mixins/singleActions.js
  containers/Network/views/nats/sidepage/Detail.vue
  containers/Network/views/nats/sidepage/Dnat.vue
  containers/Network/views/nats/sidepage/Snat.vue
  containers/Network/views/nats/sidepage/index.vue
  containers/Network/views/nats/utils/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#1726 fix: name repeated
  containers/Network/views/ssh-proxy-match/dialogs/link.vue
Labels: area/network, size/XS

#1727 Automated cherry pick of #1726: fix: name repeated
  containers/Network/views/ssh-proxy-match/dialogs/link.vue
Labels: size/XS

#1728 Automated cherry pick of #1726: fix: name repeated
  containers/Network/views/ssh-proxy-match/dialogs/link.vue
Labels: size/XS

#1731 Automated cherry pick of #1729: feat: #3524 aws支持同步natgateway资源
  containers/Network/views/nats/components/List.vue
  containers/Network/views/nats/create/index.vue
  containers/Network/views/nats/mixins/singleActions.js
  containers/Network/views/nats/sidepage/Detail.vue
  containers/Network/views/nats/sidepage/Dnat.vue
  containers/Network/views/nats/sidepage/Snat.vue
  containers/Network/views/nats/sidepage/index.vue
  containers/Network/views/nats/utils/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#1730 feat: #3524 aws支持同步natgateway资源
  containers/Network/views/eip/mixins/singleActions.js
  containers/Network/views/nats/components/List.vue
  containers/Network/views/nats/mixins/singleActions.js
Labels: size/S

#1732 Automated cherry pick of #1730: feat: #3524 aws支持同步natgateway资源
  containers/Network/views/eip/mixins/singleActions.js
  containers/Network/views/nats/components/List.vue
  containers/Network/views/nats/mixins/singleActions.js
Labels: size/S

#1734 feat: node and pod support monitor
  containers/K8S/constants/index.js
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/views/nodes/sidepage/Monitor.vue
  containers/K8S/views/nodes/sidepage/index.vue
  containers/K8S/views/pod/sidepage/Monitor.vue
  containers/K8S/views/pod/sidepage/index.vue
Labels: area/k8s, size/L

#1735 fix: add eip action tooltip
  containers/Network/views/eip/mixins/singleActions.js
Labels: size/XS

#1736 Automated cherry pick of #1735: fix: add eip action tooltip
  containers/Network/views/eip/mixins/singleActions.js
Labels: size/XS

#1737 feat: domain detail add resources data
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/domains/sidepage/Detail.vue
Labels: size/L

#1738 Automated cherry pick of #1737: feat: domain detail add resources data
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/domains/sidepage/Detail.vue
Labels: size/L

#1740 fix: delete vm refresh
  containers/Compute/views/server-recovery/components/List.vue
  containers/Compute/views/server-recovery/mixins/singleActions.js
Labels: area/compute, size/XS

#1741 fix: host action refresh list
  containers/Compute/views/host/components/List.vue
Labels: area/compute, size/XS

#1742 Automated cherry pick of #1741: fix: host action refresh list
  containers/Compute/views/host/components/List.vue
Labels: size/XS

#1743 Automated cherry pick of #1741: fix: host action refresh list
  containers/Compute/views/host/components/List.vue
Labels: size/XS

#1744 fix: fix agent status error
  containers/Compute/views/baremetal/sidepage/index.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/S

#1745 Automated cherry pick of #1744: fix: fix agent status error
  containers/Compute/views/baremetal/sidepage/index.vue
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/S

#1746 feat: domain detail add resource data
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/domains/sidepage/Detail.vue
Labels: size/S

#1747 Automated cherry pick of #1746: feat: domain detail add resource data
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/domains/sidepage/Detail.vue
Labels: size/S

#1748 feat: #3532 公有云区域和可用区详情页优化
  containers/Cloudenv/views/cloudregion/sidepage/index.vue
  containers/Cloudenv/views/zone/sidepage/index.vue
Labels: size/M

#1749 增加硬盘类型翻译
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#1750 Automated cherry pick of #1749: 增加硬盘类型翻译
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#1751 fix: vga auto checked
  containers/Compute/sections/VGA/index.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: area/compute, size/S

#1752 Automated cherry pick of #1751: fix: vga auto checked
  containers/Compute/sections/VGA/index.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/S

#1753 Automated cherry pick of #1751: fix: vga auto checked
  containers/Compute/sections/VGA/index.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/S

#1755 feat: #3517 修改IP后支持同时重启网卡
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/ChangeIp.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#1756 Automated cherry pick of #1755: feat: #3517 修改IP后支持同时重启网卡
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/ChangeIp.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#1757 feat: cloudprovider region action accuracy
  containers/Cloudenv/views/cloudproviderregion/components/List.vue
  containers/Cloudenv/views/cloudproviderregion/mixins/singleActions.js
Labels: size/M, area/cloudenv

#1758 Automated cherry pick of #1754: fix: unbind nat gateway i18n
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/eip/mixins/singleActions.js
Labels: size/XS

#1759 fix: cloudprovider region action accuracy
  containers/Cloudenv/views/cloudproviderregion/components/List.vue
  containers/Cloudenv/views/cloudproviderregion/mixins/singleActions.js
Labels: area/cloudenv, size/L

#1760 feat: add i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#1761 Automated cherry pick of #1760: feat: add i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#1764 feat: resource create support set tag
  containers/Compute/views/baremetal/create/index.vue
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/physicalmachine/add/ISOAdd.vue
  containers/Compute/views/physicalmachine/add/PXEAdd.vue
  containers/Compute/views/physicalmachine/add/PreAdd.vue
  containers/Compute/views/physicalmachine/add/index.vue
  containers/Network/views/agent/form/index.vue
  containers/Network/views/dns-zone/create/components/Step1.vue
  containers/Network/views/dns-zone/create/index.vue
  containers/Network/views/eip/create/index.vue
  containers/Network/views/lbcerts/dialogs/Create.vue
  containers/Network/views/loadbalancercluster/dialogs/Create.vue
  containers/Network/views/nats/constants/index.js
  containers/Network/views/nats/create/components/BottomBar.vue
  containers/Network/views/nats/create/index.vue
  containers/Network/views/network/Create.vue
  containers/Network/views/vpc/create/index.vue
  containers/Network/views/wire/dialogs/Create.vue
  containers/Storage/views/blockstorage/dialogs/Create.vue
Labels: area/compute, size/L

#1767 fix: block steam refresh
  src/constants/expectStatus.js
Labels: lgtm, approved, size/XS

#1768 Automated cherry pick of #1767: fix: block steam refresh
  src/constants/expectStatus.js
Labels: lgtm, approved

#1765 fix: cloudaccount create error
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: area/cloudenv, size/XS

#1766 feat: agent status
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Compute/views/vminstance/components/InstallAgentFormVisible.vue
Labels: area/compute, size/S

#1769 fix: change ip tooltip
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/ChangeIp.vue
Labels: area/compute

#1771 Automated cherry pick of #1765: fix: cloudaccount create error
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
Labels: size/XS

#1772 fix: #8066 云账号公有云详情页的资源统计tab
  containers/Cloudenv/views/cloudaccount/sidepage/index.vue
Labels: area/cloudenv, size/XS

#1773 feat: add vpc topology
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/vpc/components/ResTopology/ResCommon.vue
  containers/Network/views/vpc/components/ResTopology/ResIpsubnet.vue
  containers/Network/views/vpc/components/ResTopology/ResMixin.js
  containers/Network/views/vpc/components/ResTopology/ResVpc.vue
  containers/Network/views/vpc/components/ResTopology/ResWire.vue
  containers/Network/views/vpc/components/ResTopology/Vpc/index.vue
  containers/Network/views/vpc/components/ResTopology/Wire/index.vue
  containers/Network/views/vpc/components/ResTopology/constants.js
  containers/Network/views/vpc/components/ResTopology/index.scss
  containers/Network/views/vpc/components/ResTopology/index.vue
  containers/Network/views/vpc/sidepage/Topology.vue
  containers/Network/views/vpc/sidepage/index.vue
Labels: size/XL

#1774 Automated cherry pick of #1773: feat: add vpc topology
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/vpc/components/ResTopology/ResCommon.vue
  containers/Network/views/vpc/components/ResTopology/ResIpsubnet.vue
  containers/Network/views/vpc/components/ResTopology/ResMixin.js
  containers/Network/views/vpc/components/ResTopology/ResVpc.vue
  containers/Network/views/vpc/components/ResTopology/ResWire.vue
  containers/Network/views/vpc/components/ResTopology/Vpc/index.vue
  containers/Network/views/vpc/components/ResTopology/Wire/index.vue
  containers/Network/views/vpc/components/ResTopology/constants.js
  containers/Network/views/vpc/components/ResTopology/index.scss
  containers/Network/views/vpc/components/ResTopology/index.vue
  containers/Network/views/vpc/sidepage/Topology.vue
  containers/Network/views/vpc/sidepage/index.vue
Labels: size/XL

#1775 fix: 修复角色和权限备注修改问题
  containers/IAM/views/policy/mixins/columns.js
  src/components/ListBodyCellWrap/index.vue
Labels: size/XS

#1776 Automated cherry pick of #1775: fix: 修复角色和权限备注修改问题
  containers/IAM/views/policy/mixins/columns.js
  src/components/ListBodyCellWrap/index.vue
Labels: size/XS

#1777 Feature/r 3.8 diankeyun
  containers/IAM/views/policy/mixins/columns.js
  src/components/ListBodyCellWrap/index.vue
Labels: size/XS

#1779 feat: update topology
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/vpc/components/ResTopology/ResCommon.vue
  containers/Network/views/vpc/components/ResTopology/ResIpsubnet.vue
  containers/Network/views/vpc/components/ResTopology/ResVpc.vue
  containers/Network/views/vpc/components/ResTopology/ResWire.vue
  containers/Network/views/vpc/components/ResTopology/Vpc/index.vue
  containers/Network/views/vpc/components/ResTopology/Wire/index.vue
  containers/Network/views/vpc/sidepage/Topology.vue
Labels: size/L

#1780 Automated cherry pick of #1779: feat: update topology
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/vpc/components/ResTopology/ResCommon.vue
  containers/Network/views/vpc/components/ResTopology/ResIpsubnet.vue
  containers/Network/views/vpc/components/ResTopology/ResVpc.vue
  containers/Network/views/vpc/components/ResTopology/ResWire.vue
  containers/Network/views/vpc/components/ResTopology/Vpc/index.vue
  containers/Network/views/vpc/components/ResTopology/Wire/index.vue
  containers/Network/views/vpc/sidepage/Topology.vue
Labels: size/L

#1778 fix: 修复角色与全选备注修改
  src/components/ListBodyCellWrap/index.vue
Labels: size/XS

#1783 Automated cherry pick of #1779: feat: update topology
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/vpc/components/ResTopology/ResCommon.vue
  containers/Network/views/vpc/components/ResTopology/ResIpsubnet.vue
  containers/Network/views/vpc/components/ResTopology/ResVpc.vue
  containers/Network/views/vpc/components/ResTopology/ResWire.vue
  containers/Network/views/vpc/components/ResTopology/Vpc/index.vue
  containers/Network/views/vpc/components/ResTopology/Wire/index.vue
  containers/Network/views/vpc/sidepage/Topology.vue
Labels: size/L

#1781 fix: 修复角色权限备注修改
  src/components/ListBodyCellWrap/index.vue
Labels: size/XS

#1782 Automated cherry pick of #1781: fix: 修复角色权限备注修改
  src/components/ListBodyCellWrap/index.vue
Labels: size/XS

#1785 fix: 角色备注
  src/components/ListBodyCellWrap/index.vue
Labels: size/XS

#1788 feat: update topology server status
  containers/Network/views/vpc/components/ResTopology/ResCommon.vue
Labels: size/S

#1789 Automated cherry pick of #1788: feat: update topology server status
  containers/Network/views/vpc/components/ResTopology/ResCommon.vue
Labels: size/S

#1790 Automated cherry pick of #1788: feat: update topology server status
  containers/Network/views/vpc/components/ResTopology/ResCommon.vue
Labels: size/S

#1787 feat: clone add process
  src/locales/zh-CN.json
Labels: size/XS

#1792 Automated cherry pick of #1787: feat: clone add process
  src/locales/zh-CN.json
Labels: size/XS

#1791 Automated cherry pick of #1787: feat: clone add process
  src/locales/zh-CN.json
Labels: size/XS

#1793 feat(Compute): isolated device hotplug supported
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/gpu/dialogs/AttachDialog.vue
  containers/Compute/views/gpu/mixins/singleActions.js
Labels: size/XS

#1794 Automated cherry pick of #1793: feat(Compute): isolated device hotplug supported
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/gpu/dialogs/AttachDialog.vue
  containers/Compute/views/gpu/mixins/singleActions.js
Labels: size/XS

#1795 feat: #3549 部分菜单增加权限校验
  containers/Compute/router/index.js
  containers/IAM/router/index.js
  containers/Monitor/router/index.js
  containers/Network/router/index.js
  src/constants/permission.js
Labels: size/M, area/compute

#1798 feat: #3556 RDS monitor support apsara
  containers/DB/constants/index.js
  containers/DB/views/rds/sidepage/Monitor.vue
Labels: size/M, area/db

#1796 feat: #3548 虚拟机更换IP提示优化
  containers/Compute/views/vminstance/dialogs/ChangeIp.vue
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: area/compute, size/S

#1797 Automated cherry pick of #1796: feat: #3548 虚拟机更换IP提示优化
  containers/Compute/views/vminstance/dialogs/ChangeIp.vue
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/S

#1802 fix: #8072 vminstance create sku list error
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: area/compute, size/S

#1803 Automated cherry pick of #1802: fix: #8072 vminstance create sku list error
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/S

#1804 fix: query forcast when transfer vminstance
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: area/compute, size/XS

#1806 fix: chang ip status error
  containers/Compute/views/vminstance/dialogs/ChangeIp.vue
Labels: size/XS

#1807 Automated cherry pick of #1806: fix: chang ip status error
  containers/Compute/views/vminstance/dialogs/ChangeIp.vue
Labels: size/XS

#1808 Automated cherry pick of #1806: fix: chang ip status error
  containers/Compute/views/vminstance/dialogs/ChangeIp.vue
Labels: size/XS

#1809 Automated cherry pick of #1524: feat: #3417 镜像缓存中，增加进度提示
  containers/Compute/views/vminstance/mixins/columns.js
  src/components/Status/index.vue
Labels: size/S

#1810 Automated cherry pick of #1524: feat: #3417 镜像缓存中，增加进度提示
  containers/Compute/views/vminstance/mixins/columns.js
  src/components/Status/index.vue
Labels: size/S

#1811 feat: server running hidden process
  src/components/Status/index.vue
Labels: size/XS

#1813 Automated cherry pick of #1811: feat: server running hidden process
  src/components/Status/index.vue
Labels: size/XS

#1812 Automated cherry pick of #1811: feat: server running hidden process
  src/components/Status/index.vue
Labels: size/XS
