Repository yunionio/dashboard, pull requests merged in 2021-06, with the labels that each got.

#399 Automated cherry pick of #398: fix(Compute/vminstance): #7471 移动云链接vnc按钮不应该禁用，且提示信息不对
  containers/Compute/views/vminstance/utils.js
Labels: size/XS

#398 fix(Compute/vminstance): #7471 移动云链接vnc按钮不应该禁用，且提示信息不对
  containers/Compute/views/vminstance/utils.js
Labels: size/XS

#400 添加平台-列的排序筛选项
  src/utils/common/tableColumn.js
Labels: size/XS

#401 Automated cherry pick of #400: 添加平台-列的排序筛选项
  src/utils/common/tableColumn.js
Labels: size/XS

#402 Automated cherry pick of #400: 添加平台-列的排序筛选项
  src/utils/common/tableColumn.js
Labels: size/XS

#403 修改磁盘-已挂载的磁盘-扩容接口
  containers/Compute/views/disk/dialogs/CapacityUpdateDialog.vue
Labels: area/compute, size/S

#404 Automated cherry pick of #403: 修改磁盘-已挂载的磁盘-扩容接口
  containers/Compute/views/disk/dialogs/CapacityUpdateDialog.vue
Labels: size/S

#405 Automated cherry pick of #403: 修改磁盘-已挂载的磁盘-扩容接口
  containers/Compute/views/disk/dialogs/CapacityUpdateDialog.vue
Labels: size/S

#406 feat(Compute): update transfer host i18n
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
Labels: size/XS

#407 Automated cherry pick of #406: feat(Compute): update transfer host i18n
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
Labels: size/XS

#408 Automated cherry pick of #406: feat(Compute): update transfer host i18n
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
Labels: size/XS

#409 redis&rds network select fix
  containers/Cloudenv/router/index.js
  containers/Cloudenv/views/cloudproviderregion/components/List.vue
  containers/Cloudenv/views/cloudproviderregion/mixins/columns.js
  src/sections/NetworkSelects/index.js
  src/utils/auth.js
Labels: area/cloudenv, area/network, size/L

#413 Automated cherry pick of #411: fix: improve prompt when no host/accoutns available
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#414 change network select helplink style
  src/sections/NetworkSelects/index.js
Labels: area/db, size/S

#415 Automated cherry pick of #414: change network select helplink style
  src/sections/NetworkSelects/index.js
Labels: size/S

#419 删除虚拟机时增加可选项
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/dialogs/DeleteDisk.vue
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: area/compute, size/L

#420 Automated cherry pick of #419: 删除虚拟机时增加可选项
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/dialogs/DeleteDisk.vue
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: area/compute, size/L

#427 feat(image): update web-base image to v3.6.1
  Dockerfile
Labels: size/XS

#428 Automated cherry pick of #427: feat(image): update web-base image to v3.6.1
  Dockerfile
Labels: size/XS

#429 Automated cherry pick of #427: feat(image): update web-base image to v3.6.1
  Dockerfile
Labels: size/XS

#425 Automated cherry pick of #424: bugfix(cloudenv): project mapping
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/projectmapping/components/List.vue
  containers/Cloudenv/views/projectmapping/components/RuleList/index.vue
  containers/Cloudenv/views/projectmapping/components/Tag.vue
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleCreate.vue
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
  containers/Cloudenv/views/projectmapping/sidepage/index.vue
Labels: size/M

#421 费用添加负数说明
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/XS

#422 feature(cloudenv): delete-pricecomparator-list-sync
  containers/Cloudenv/views/server-price-comparator/components/List.vue
  src/components/PageList/Actions/index.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
Labels: area/cloudenv, size/S

#423 Automated cherry pick of #422: feature(cloudenv): delete-pricecomparator-list-sync
  containers/Cloudenv/views/server-price-comparator/components/List.vue
  src/components/PageList/Actions/index.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
Labels: size/S

#424 bugfix(cloudenv): project mapping
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/projectmapping/components/List.vue
  containers/Cloudenv/views/projectmapping/components/RuleList/index.vue
  containers/Cloudenv/views/projectmapping/components/Tag.vue
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleCreate.vue
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
  containers/Cloudenv/views/projectmapping/sidepage/index.vue
Labels: area/cloudenv, size/M

#426 调换磁贴位置
  containers/Dashboard/sections/ExtendGallery/config.js
Labels: area/dashboard, size/M

#430 Feature/glb r 3.8 vminstance shutdown no charging
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/ShutDown.vue
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: area/compute, size/M

#431 修改样式
  containers/Cloudenv/views/projectmapping/components/RuleList/index.vue
Labels: area/cloudenv, size/XS

#432 调整磁贴展示
  containers/Dashboard/extends/ConsumptionPercent/components/Brand.vue
  containers/Dashboard/extends/ConsumptionPercent/components/Resource.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
Labels: area/dashboard, size/S

#433 Feature/add ocSelect component
  src/components/OcSelect/README.md
  src/components/OcSelect/index.vue
Labels: size/XL

#435 Automated cherry pick of #434: 修改宿主机及物理机导出列
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/physicalmachine/components/List.vue
  containers/Compute/views/physicalmachine/mixins/columns.js
Labels: size/M

#439 Automated cherry pick of #437: 宿主机.云账号添加 删除 启用 禁用后同步刷新云资源信息
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#437 宿主机.云账号添加 删除 启用 禁用后同步刷新云资源信息
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/compute, size/L

#438 Automated cherry pick of #437: 宿主机.云账号添加 删除 启用 禁用后同步刷新云资源信息
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XL

#440 fix: name filter
  src/utils/common/tableFilter.js
Labels: size/XS

#441 Automated cherry pick of #440: fix: name filter
  src/utils/common/tableFilter.js
Labels: size/XS

#444 install agent pe help link fix
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Compute/views/vminstance/dialogs/DetectSSH.vue
Labels: area/compute, size/S

#445 Automated cherry pick of #444: install agent pe help link fix
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Compute/views/vminstance/dialogs/DetectSSH.vue
Labels: size/S

#446 Feature/mj r master 3117
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  src/components/OcSelect/index.vue
Labels: size/L

#448 lb style update
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lbacls/mixins/columns.js
  containers/Network/views/lbcerts/mixins/columns.js
Labels: area/network, size/S

#447 add jd cloud docs link
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
Labels: area/cloudenv, size/XS

#450 修复云账号详情页启用禁用
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
Labels: area/cloudenv, size/S

#451 Automated cherry pick of #450: 修复云账号详情页启用禁用
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
Labels: size/S

#452 Automated cherry pick of #450: 修复云账号详情页启用禁用
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
Labels: size/S

#453 feat: add external_id support
  containers/Compute/views/vminstance/components/List.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
  containers/Network/views/lb/components/List.vue
  containers/Storage/views/bucket/components/List.vue
  src/components/Detail/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#454 Automated cherry pick of #453: feat: add external_id support
  containers/Compute/views/vminstance/components/List.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
  containers/Network/views/lb/components/List.vue
  containers/Storage/views/bucket/components/List.vue
  src/components/Detail/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#455 修改磁贴位置
  containers/Dashboard/sections/ExtendGallery/config.js
Labels: area/dashboard, size/M

#456 云账号-更新账单文件-azure添加账单分析范围
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
Labels: area/cloudenv, size/S

#457 Automated cherry pick of #456: 云账号-更新账单文件-azure添加账单分析范围
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
Labels: size/S

#458 fix(TagSelect): add max-width
  src/sections/TagSelect/index.vue
Labels: size/XS

#459 Automated cherry pick of #458: fix(TagSelect): add max-width
  src/sections/TagSelect/index.vue
Labels: size/XS

#460 Feature/mj r master 3185
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/projectmapping/components/ApplicationScope.vue
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/mixins/accountProps.js
  containers/Cloudenv/views/projectmapping/mixins/cloudprovidersProps.js
  containers/Cloudenv/views/projectmapping/mixins/columns.js
  containers/Cloudenv/views/projectmapping/utils/columns.js
  containers/Cloudenv/views/projectmapping/utils/index.js
  src/components/DialogTable/index.vue
  src/sections/ListSelect/index.vue
Labels: size/XL

#461 Automated cherry pick of #460: feat(ProjectMapping): sync policysupport bind subscription
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/projectmapping/components/ApplicationScope.vue
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/mixins/accountProps.js
  containers/Cloudenv/views/projectmapping/mixins/cloudprovidersProps.js
  containers/Cloudenv/views/projectmapping/mixins/columns.js
  containers/Cloudenv/views/projectmapping/utils/columns.js
  containers/Cloudenv/views/projectmapping/utils/index.js
  src/components/DialogTable/index.vue
  src/sections/ListSelect/index.vue
Labels: size/XL

#462 多币种
  src/constants/currency.js
  src/constants/permission.js
  src/store/modules/common.js
  src/utils/common/cookie.js
Labels: size/M

#463 feat(ProjectMapping): update sync policy support bind subscription
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/mixins/cloudprovidersProps.js
Labels: size/M

#465 fix(TagFilter): update tag filter
  src/components/PageList/TagFilter.vue
Labels: size/XS

#467 修改云账号-azure/aws-billing_scpte未选择时默认为managed
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
Labels: area/cloudenv, size/XS

#468 Automated cherry pick of #467: 修改云账号-azure/aws-billing_scpte未选择时默认为managed
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
Labels: size/XS

#471 修改-资源消费占比磁贴首次添加不展示问题
  containers/Dashboard/extends/ConsumptionPercent/components/Brand.vue
  containers/Dashboard/extends/ConsumptionPercent/components/Resource.vue
  containers/Dashboard/extends/ConsumptionTrend/index.vue
Labels: area/dashboard, size/M

#472 fix(i18n): add ecloud i18n
  scope/locales/en.json
  scope/locales/zh-CN.json
Labels: size/XS

#474 Automated cherry pick of #472: fix(i18n): add ecloud i18n
  scope/locales/en.json
  scope/locales/zh-CN.json
Labels: size/XS

#475 fix(Notify): notice refresh
  containers/Dashboard/extends/Notify/index.vue
Labels: size/M

#476 Automated cherry pick of #475: fix(Notify): notice refresh
  containers/Dashboard/extends/Notify/index.vue
Labels: size/M

#473 support license v4.0
  containers/Monitor/router/index.js
  scope/locales/en.json
  scope/locales/zh-CN.json
  src/assets/images/features/auth.svg
  src/assets/images/features/baremetal.svg
  src/assets/images/features/bill.svg
  src/assets/images/features/k8s.svg
  src/assets/images/features/lb.svg
  src/assets/images/features/monitor.svg
  src/assets/images/providers/ctyun.svg
  src/assets/images/providers/onestack.svg
  src/components/FeatureSelector/index.vue
  src/constants/feature.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/auth.js
Labels: area/dashboard, size/XL

#477 多币种3.7
  src/constants/currency.js
  src/constants/permission.js
  src/store/modules/common.js
  src/utils/common/cookie.js
Labels: size/M

#479 Automated cherry pick of #478: 权限-扩展按钮权限验证
  src/utils/auth.js
Labels: approved, lgtm, size/S

#480 monitor overview add resource summary
  containers/Monitor/components/MonitorCard/sections/card/index.vue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/views/overview/components/SummaryCards.vue
  containers/Monitor/views/overview/components/index.vue
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/help-en.js
  src/locales/help-zh-CN.js
  src/locales/zh-CN.json
Labels: area/monitor, size/L

#481 Automated cherry pick of #480: monitor overview add resource summary
  containers/Monitor/components/MonitorCard/sections/card/index.vue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/views/overview/components/SummaryCards.vue
  containers/Monitor/views/overview/components/index.vue
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/help-en.js
  src/locales/help-zh-CN.js
  src/locales/zh-CN.json
Labels: size/L

#478 权限-扩展按钮权限验证
  src/utils/auth.js
Labels: size/XS

#482 Automated cherry pick of #478: 权限-扩展按钮权限验证
  src/utils/auth.js
Labels: size/XS

#484 add features icons
  containers/Monitor/components/MonitorCard/sections/card/index.vue
  containers/Monitor/views/overview/components/SummaryCards.vue
  src/assets/images/features/bill.svg
  src/assets/images/features/monitor.svg
  src/components/FeatureSelector/index.vue
  src/constants/feature.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/dashboard, area/monitor, size/S

#485 Bugfix/tb bugfix 062202
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Network/views/lbcerts/components/List.vue
  containers/Network/views/lbcerts/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: area/compute, area/network, size/M

#486 Automated cherry pick of #485: lbcert status icon fix
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Network/views/lbcerts/components/List.vue
  containers/Network/views/lbcerts/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/M

#487 adjust system route order
  containers/Helm/router/index.js
  src/assets/images/features/monitor.svg
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/auth.js
Labels: area/dashboard, size/M

#488 Automated cherry pick of #448: lb style update
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lbacls/mixins/columns.js
  containers/Network/views/lbcerts/mixins/columns.js
Labels: size/XS

#489 Automated cherry pick of #449: lbacl source ip desc fix
  containers/Network/views/lbacls/mixins/columns.js
Labels: size/XS

#490 Feature/mj r master 3194
  containers/Compute/views/vminstance/index.vue
  src/components/PageHeader/index.vue
  src/sections/ResStatusTab/index.vue
Labels: size/L

#491 fix: rds details
  containers/DB/views/rds-account/components/List.vue
  containers/DB/views/rds-account/mixins/singleActions.js
  containers/DB/views/rds-database/components/List.vue
Labels: size/S

#492 Automated cherry pick of #491: fix: rds details
  containers/DB/views/rds-account/components/List.vue
  containers/DB/views/rds-account/mixins/singleActions.js
  containers/DB/views/rds-database/components/List.vue
Labels: size/S

#493 Bugfix/tb bugfix 062401
  containers/Monitor/views/commonalert/components/alert/form/index.vue
  containers/Monitor/views/overview/components/index.vue
Labels: area/monitor, size/XS

#494 Automated cherry pick of #493: update metric alert database fix
  containers/Monitor/views/commonalert/components/alert/form/index.vue
  containers/Monitor/views/overview/components/index.vue
Labels: size/XS

#495 feat(ResStatusTab): update res status tab
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/index.vue
  src/sections/ResStatusTab/index.vue
Labels: size/M

#498 fix(ThirdProcess): comment show empty
  src/views/workflow-technical-support/third-process/mixins/columns.js
Labels: size/S

#499 Automated cherry pick of #498: fix(ThirdProcess): comment show empty
  src/views/workflow-technical-support/third-process/mixins/columns.js
Labels: size/S

#500 feat(TagFilter): 标签增加优化，支持选择同一个key不同的value
  src/components/PageList/TagFilter.vue
  src/utils/list.js
Labels: size/M

#502 vminstance detail monitor page update
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/constants.js
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  src/sections/Monitor/List.vue
Labels: area/compute, size/L

#503 Automated cherry pick of #502: vminstance detail monitor page update
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/constants.js
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  src/sections/Monitor/List.vue
Labels: size/L

#504 Bugfix/tb bugfix 062502
  containers/Compute/views/vminstance/constants.js
  containers/Monitor/views/commonalert/components/alert/form/Condition.vue
  containers/Monitor/views/commonalert/components/alert/form/index.vue
Labels: area/compute, area/monitor, size/S

#505 fix(SearchBox): search mutiple error
  src/components/SearchBox/index.vue
Labels: size/XS

#506 Automated cherry pick of #504: commonalerts update fix
  containers/Compute/views/vminstance/constants.js
  containers/Monitor/views/commonalert/components/alert/form/Condition.vue
  containers/Monitor/views/commonalert/components/alert/form/index.vue
Labels: size/S

#507 Automated cherry pick of #505: fix(SearchBox): search mutiple error
  src/components/SearchBox/index.vue
Labels: size/XS

#508 fix(SearchInput): update search input placehoder i18n
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Navbar/components/GlobalSearch.vue
Labels: size/XS

#509 Automated cherry pick of #508: fix(SearchInput): update search input placehoder i18n
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Navbar/components/GlobalSearch.vue
Labels: size/XS

#510 Automated cherry pick of #508: fix(SearchInput): update search input placehoder i18n
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Navbar/components/GlobalSearch.vue
Labels: size/XS

#511 列表扩展
  src/components/PageList/index.vue
  src/constants/permission.js
  src/utils/list.js
Labels: size/S

#512 Automated cherry pick of #511: 列表扩展
  src/components/PageList/index.vue
  src/constants/permission.js
  src/utils/list.js
Labels: size/S

#513 fetch monitor pannel fix
  containers/Monitor/views/dashboard/create/index.vue
Labels: area/monitor, size/XS

#514 Automated cherry pick of #513: fetch monitor pannel fix
  containers/Monitor/views/dashboard/create/index.vue
Labels: size/XS

#515 Bugfix/mj r master 7518
  containers/Network/views/network/Create.vue
  containers/Network/views/vpc/create/index.vue
Labels: size/S

#516 Automated cherry pick of #515 upstream release 3.7
  containers/Network/views/network/Create.vue
  containers/Network/views/vpc/create/index.vue
Labels: size/S

#517 Automated cherry pick of #515 upstream release 3.6
  containers/Network/views/network/Create.vue
  containers/Network/views/vpc/create/index.vue
Labels: size/S

#518 feat(Logo): 开源版logo替换为cloudpod的logo
  scope/images/cloudpod_login_logo.svg
  scope/images/cloudpod_logo.svg
  scope/images/onecloud.svg
  scope/store/modules/app.js
Labels: size/XXL

#519 Automated cherry pick of #518: feat(Logo): 开源版logo替换为cloudpod的logo
  scope/images/cloudpod_login_logo.svg
  scope/images/cloudpod_logo.svg
  scope/images/onecloud.svg
  scope/store/modules/app.js
Labels: size/XXL
