Repository yunionio/dashboard, pull requests merged in 2022-12, with the labels that each got.

#3791 fix: hcs eip emulated
  containers/Network/views/eip/create/index.vue
Labels: size/XS

#3792 Automated cherry pick of #3791: fix: hcs eip emulated
  containers/Network/views/eip/create/index.vue
Labels: size/XS

#3794 Automated cherry pick of #3793: feat: update vpc peer connect filter
  containers/Network/views/vpc-peer-connect/components/List.vue
Labels: size/XS

#3795 feat: add proxmox
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Proxmox.vue
  src/assets/images/providers/proxmox.svg
  src/components/Icon/assets/proxmox.svg
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#3796 Automated cherry pick of #3795: feat: add proxmox
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Proxmox.vue
  src/assets/images/providers/proxmox.svg
  src/components/Icon/assets/proxmox.svg
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#3797 feat: #3939 add report i18n
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#3798 Automated cherry pick of #3797: feat: #3939 add report i18n
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#3801 add: wire metric
  containers/Network/views/wire/constants.js
  containers/Network/views/wire/sidepage/Monitor.vue
  containers/Network/views/wire/sidepage/index.vue
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/blockstorage/constants.js
  containers/Storage/views/blockstorage/sidepage/Monitor.vue
  containers/Storage/views/blockstorage/sidepage/index.vue
Labels: size/L

#3802 Automated cherry pick of #3801: add: wire metric
  containers/Network/views/wire/constants.js
  containers/Network/views/wire/sidepage/Monitor.vue
  containers/Network/views/wire/sidepage/index.vue
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/blockstorage/constants.js
  containers/Storage/views/blockstorage/sidepage/Monitor.vue
  containers/Storage/views/blockstorage/sidepage/index.vue
Labels: size/L

#3803 fix: unit transer function error
  src/utils/utils.js
Labels: size/S

#3804 Automated cherry pick of #3803: fix: unit transer function error
  src/utils/utils.js
Labels: size/S

#3805 Automated cherry pick of #3803: fix: unit transer function error
  src/utils/utils.js
Labels: size/S

#3808 feat: #4080 projectmapping add rule condition(match to resource tag)
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/projectmapping/components/ApplicationScope.vue
  containers/Cloudenv/views/projectmapping/components/List.vue
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/mixins/columns.js
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
  containers/Cloudenv/views/projectmapping/sidepage/Detail.vue
Labels: area/cloudenv, size/L

#3809 Automated cherry pick of #3808: feat: #4080 projectmapping add rule condition(match to resource tag)
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/projectmapping/components/ApplicationScope.vue
  containers/Cloudenv/views/projectmapping/components/List.vue
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/mixins/columns.js
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
  containers/Cloudenv/views/projectmapping/sidepage/Detail.vue
Labels: size/L

#3810 fix: #8681 compute set-boot-index params error
  containers/Compute/views/vminstance/dialogs/VmChangeBootIndex.vue
Labels: area/compute, size/XS

#3811 feat: create samluser do not checkek account status
  containers/Cloudenv/views/samluser/components/List.vue
Labels: area/cloudenv, size/XS

#3812 Automated cherry pick of #3811: feat: create samluser do not checkek account status
  containers/Cloudenv/views/samluser/components/List.vue
Labels: size/XS

#3813 Automated cherry pick of #3811: feat: create samluser do not checkek account status
  containers/Cloudenv/views/samluser/components/List.vue
Labels: size/XS

#3814 Automated cherry pick of #3810: fix: #8681 compute set-boot-index params error
  containers/Compute/views/vminstance/dialogs/VmChangeBootIndex.vue
Labels: size/XS

#3815 feat: #4077 compute add backup info
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/AddBackup.vue
  containers/Compute/views/vminstance/dialogs/StartBackup.vue
  containers/Compute/views/vminstance/dialogs/SwitchBackup2.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Compute/views/vminstance/utils.js
  src/components/Icon/assets/start.svg
  src/components/Icon/assets/switch.svg
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/compute, size/L

#3816 Automated cherry pick of #3815: feat: #4077 compute add backup info
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/AddBackup.vue
  containers/Compute/views/vminstance/dialogs/StartBackup.vue
  containers/Compute/views/vminstance/dialogs/SwitchBackup2.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Compute/views/vminstance/utils.js
  src/components/Icon/assets/start.svg
  src/components/Icon/assets/switch.svg
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#3817 fix: #8693 rds set config error
  containers/DB/views/rds/dialogs/SetConfig.vue
Labels: size/XS

#3819 Automated cherry pick of #3817: fix: #8693 rds set config error
  containers/DB/views/rds/dialogs/SetConfig.vue
Labels: size/XS

#3818 Automated cherry pick of #3815: feat: #4077 compute add backup info
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/AddBackup.vue
  containers/Compute/views/vminstance/dialogs/StartBackup.vue
  containers/Compute/views/vminstance/dialogs/SwitchBackup2.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Compute/views/vminstance/utils.js
  src/components/Icon/assets/start.svg
  src/components/Icon/assets/switch.svg
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#3820 Automated cherry pick of #3817: fix: #8693 rds set config error
  containers/DB/views/rds/dialogs/SetConfig.vue
Labels: size/XS

#3827 feat: refactor policy
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/Group.vue
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/index.vue
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/constants.js
  src/components/PageList/Actions/ActionButton.vue
  src/constants/policy/compute.js
  src/constants/policy/index.js
  src/constants/policy/policy-res-list.js
  src/utils/policy/policy-options.js
  src/utils/policy/policy-res-list.js
Labels: size/XXL

#3828 Automated cherry pick of #3827: feat: refactor policy
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/Group.vue
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/index.vue
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/constants.js
  src/components/PageList/Actions/ActionButton.vue
  src/constants/policy/compute.js
  src/constants/policy/index.js
  src/constants/policy/policy-res-list.js
  src/utils/policy/policy-options.js
  src/utils/policy/policy-res-list.js
Labels: size/XXL

#3821 fix: #8697 shceduled task set time error
  containers/Cloudenv/views/cloudaccount/create/form/ScheduledSettings.vue
  containers/Cloudenv/views/cloudaccount/dialogs/ScheduledtaskCreate.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
Labels: size/XS

#3822 Automated cherry pick of #3821: fix: #8697 shceduled task set time error
  containers/Cloudenv/views/cloudaccount/create/form/ScheduledSettings.vue
  containers/Cloudenv/views/cloudaccount/dialogs/ScheduledtaskCreate.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
Labels: size/XS

#3823 Automated cherry pick of #3821: fix: #8697 shceduled task set time error
  containers/Cloudenv/views/cloudaccount/create/form/ScheduledSettings.vue
  containers/Cloudenv/views/cloudaccount/dialogs/ScheduledtaskCreate.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
Labels: size/XS

#3824 fix: #8592 baremetal action check for status admin
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/components/List.vue
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/vminstance/sidepage/Snapshot.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/Compute/views/vminstance/utils.js
Labels: size/M, area/compute

#3825 Automated cherry pick of #3824: fix: #8592 baremetal action check for status admin
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/components/List.vue
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/vminstance/sidepage/Snapshot.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/Compute/views/vminstance/utils.js
Labels: size/M

#3826 Automated cherry pick of #3824: fix: #8592 baremetal action check for status admin
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/components/List.vue
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/vminstance/sidepage/Snapshot.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/Compute/views/vminstance/utils.js
Labels: size/M

#3829 feat: add containers alias
  vue.config.js
Labels: size/XS

#3830 Automated cherry pick of #3829: feat: add containers alias
  vue.config.js
Labels: size/XS

#3833 fix: #8698 新建CDN域名界面 不应该缺少加速域名
  containers/Network/locales/zh-CN.json
  containers/Network/views/cdn/create/index.vue
  containers/Network/views/cdn/locales/en.json
  containers/Network/views/cdn/locales/zh-CN.json
Labels: size/XS

#3834 Automated cherry pick of #3833: fix: #8698 新建CDN域名界面 不应该缺少加速域名
  containers/Network/locales/zh-CN.json
  containers/Network/views/cdn/create/index.vue
  containers/Network/views/cdn/locales/en.json
  containers/Network/views/cdn/locales/zh-CN.json
Labels: size/XS

#3835 fix: i18n error
  src/locales/zh-CN.json
Labels: size/XS

#3836 Automated cherry pick of #3835: fix: i18n error
  src/locales/zh-CN.json
Labels: size/XS

#3837 Automated cherry pick of #3835: fix: i18n error
  src/locales/zh-CN.json
Labels: size/XS

#3838 feat: kvm虚拟机新建支持SR-IOV网卡透传
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/sections/ServerNetwork/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/M

#3839 fix: #8711 vminstance sidepage detail lost statusTableColumn
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: area/compute, size/XS

#3840 feat: #4089 careate account support set project mapping
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/cloudprovider/components/List.vue
  containers/Cloudenv/views/cloudprovider/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudprovider/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/mixins/singleActions.js
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/mixins/accountProps.js
  containers/Cloudenv/views/projectmapping/mixins/columns.js
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
  containers/Cloudenv/views/projectmapping/utils/index.js
  src/constants/permission.js
Labels: area/cloudenv, size/XL

#3841 Automated cherry pick of #3840: feat: #4089 careate account support set project mapping
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/cloudprovider/components/List.vue
  containers/Cloudenv/views/cloudprovider/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudprovider/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/mixins/singleActions.js
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/mixins/accountProps.js
  containers/Cloudenv/views/projectmapping/mixins/columns.js
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
  containers/Cloudenv/views/projectmapping/utils/index.js
  src/constants/permission.js
Labels: size/XL

#3842 fix: #8715 vminstance switch to backup add auto start param
  containers/Compute/views/vminstance/dialogs/SwitchBackup2.vue
Labels: area/compute, size/S

#3843 Automated cherry pick of #3842: fix: #8715 vminstance switch to backup add auto start param
  containers/Compute/views/vminstance/dialogs/SwitchBackup2.vue
Labels: size/S

#3844 Automated cherry pick of #3842: fix: #8715 vminstance switch to backup add auto start param
  containers/Compute/views/vminstance/dialogs/SwitchBackup2.vue
Labels: size/S

#3848 feat: #4093 storage support set schedtag (multiple)
  containers/Storage/views/blockstorage/components/List.vue
Labels: area/storage, size/S

#3849 Automated cherry pick of #3848: feat: #4093 storage support set schedtag (multiple)
  containers/Storage/views/blockstorage/components/List.vue
Labels: size/S

#3850 Automated cherry pick of #3848: feat: #4093 storage support set schedtag (multiple)
  containers/Storage/views/blockstorage/components/List.vue
Labels: size/S

#3851 fix: #8712 挂在iso镜像后，详情页iso镜像对应显示为空
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#3852 Automated cherry pick of #3851: fix: #8712 挂在iso镜像后，详情页iso镜像对应显示为空
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#3853 Automated cherry pick of #3851: fix: #8712 挂在iso镜像后，详情页iso镜像对应显示为空
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#3854 fix: #8699 新建CDN域名界面指定云订阅应该只显示腾讯云
  containers/Network/views/cdn/create/index.vue
Labels: size/XS

#3856 fix: #8701 新建CDN域名界面 无法添加源地址
  containers/Network/views/cdn/create/index.vue
Labels: size/XS

#3858 fix: #8706 新建cdn关于源地址问题处理
  containers/Network/views/cdn/create/index.vue
  containers/Network/views/cdn/locales/en.json
  containers/Network/views/cdn/locales/zh-CN.json
Labels: size/M

#3859 Automated cherry pick of #3858: fix: #8706 新建cdn关于源地址问题处理
  containers/Network/views/cdn/create/index.vue
  containers/Network/views/cdn/locales/en.json
  containers/Network/views/cdn/locales/zh-CN.json
Labels: size/M

#3860 fix: #8707 隐藏掉cos源
  containers/Network/views/cdn/constants/index.js
Labels: size/XS

#3861 Automated cherry pick of #3860: fix: #8707 隐藏掉cos源
  containers/Network/views/cdn/constants/index.js
Labels: size/XS

#3864 fix: #8720 配置SRIOV网卡按钮无响应
  containers/Compute/utils/createServer.js
Labels: size/XS

#3865 Automated cherry pick of #3864: fix: #8720 配置SRIOV网卡按钮无响应
  containers/Compute/utils/createServer.js
Labels: size/XS

#3862 fix: #8619 cloudshell support drag and resize
  src/components/OcTerm/index.vue
  src/directives/cloudshellDrag.js
Labels: size/L

#3863 Automated cherry pick of #3862: fix: #8619 cloudshell support drag and resize
  src/components/OcTerm/index.vue
  src/directives/cloudshellDrag.js
Labels: size/L

#3867 Automated cherry pick of #3866: fix: #8718 vminstance vnc render error
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#3866 fix: #8718 vminstance vnc render error
  containers/Compute/views/vminstance/constants/actions.js
Labels: area/compute, size/XS

#3868 fix: #8720 网络选择指定调度标签-没有配置sriov网卡按钮
  containers/Compute/sections/ServerNetwork/NetworkSchedtag.vue
  containers/Compute/sections/ServerNetwork/index.vue
  containers/Compute/utils/createServer.js
Labels: size/M

#3869 Automated cherry pick of #3868: fix: #8720 网络选择指定调度标签-没有配置sriov网卡按钮
  containers/Compute/sections/ServerNetwork/NetworkSchedtag.vue
  containers/Compute/sections/ServerNetwork/index.vue
  containers/Compute/utils/createServer.js
Labels: size/M

#3870 fix: #8710 接入地址提示信息
  containers/Cloudenv/views/cloudaccount/create/form/components/Proxmox.vue
Labels: size/XS

#3871 Automated cherry pick of #3870: fix: #8710 接入地址提示信息
  containers/Cloudenv/views/cloudaccount/create/form/components/Proxmox.vue
Labels: size/XS

#3872 fix: #8681 close dialog after vm set-boot-index successed
  containers/Compute/views/vminstance/dialogs/VmChangeBootIndex.vue
Labels: size/XS

#3873 Automated cherry pick of #3872: fix: #8681 close dialog after vm set-boot-index successed
  containers/Compute/views/vminstance/dialogs/VmChangeBootIndex.vue
Labels: size/XS

#3874 fix: #8717 change vminstance detail cmdline place
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: area/compute, size/XS

#3875 Automated cherry pick of #3874: fix: #8717 change vminstance detail cmdline place
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#3876 Automated cherry pick of #3874: fix: #8717 change vminstance detail cmdline place
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#3877 feat: #4089 extrnalproject add tag filter
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/projectmapping/mixins/columns.js
  src/components/PageList/TagFilter.vue
Labels: size/M, area/cloudenv

#3878 Automated cherry pick of #3877: feat: #4089 extrnalproject add tag filter
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/projectmapping/mixins/columns.js
  src/components/PageList/TagFilter.vue
Labels: size/M

#3879 fix: #8722 account linked projectmapping use secondary text color
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/mixins/columns.js
Labels: area/cloudenv, size/XS

#3880 Automated cherry pick of #3879: fix: #8722 account linked projectmapping use secondary text color
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/mixins/columns.js
Labels: size/XS

#3881 fix(k8s): use cluster_id as log params
  containers/K8S/views/pod/sidepage/Log.vue
Labels: area/k8s, size/XS

#3882 Automated cherry pick of #3881: fix(k8s): use cluster_id as log params
  containers/K8S/views/pod/sidepage/Log.vue
Labels: size/XS

#3883 Automated cherry pick of #3881: fix(k8s): use cluster_id as log params
  containers/K8S/views/pod/sidepage/Log.vue
Labels: size/XS

#3885 feat: #3735 主机模块状态为失败时，增加查看日志的快捷入口
  containers/Compute/views/baremetal/components/List.vue
  containers/Compute/views/baremetal/mixins/columns.js
  containers/Compute/views/disk-backup/components/List.vue
  containers/Compute/views/disk-backup/mixins/columns.js
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/host-image/components/List.vue
  containers/Compute/views/host-image/mixins/columns.js
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/image/mixins/columns.js
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/mixins/columns.js
  containers/Compute/views/instance-group/components/List.vue
  containers/Compute/views/instance-group/mixins/columns.js
  containers/Compute/views/physicalmachine/components/List.vue
  containers/Compute/views/physicalmachine/mixins/columns.js
  containers/Compute/views/scaling-group/components/List.vue
  containers/Compute/views/scaling-group/mixins/columns.js
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/mixins/columns.js
  containers/Compute/views/servertemplate/components/List.vue
  containers/Compute/views/servertemplate/mixins/columns.js
  containers/Compute/views/snapshot-instance/components/List.vue
  containers/Compute/views/snapshot-instance/mixins/columns.js
  containers/Compute/views/snapshot/components/List.vue
  containers/Compute/views/snapshot/mixins/columns.js
  containers/Compute/views/snapshotpolicy/components/List.vue
  containers/Compute/views/snapshotpolicy/mixins/columns.js
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/webapp/components/List.vue
  containers/Compute/views/webapp/mixins/columns.js
  src/mixins/sidePage.js
  src/utils/common/tableColumn.js
Labels: size/L

#3886 Automated cherry pick of #3885: feat: #3735 主机模块状态为失败时，增加查看日志的快捷入口
  containers/Compute/views/baremetal/components/List.vue
  containers/Compute/views/baremetal/mixins/columns.js
  containers/Compute/views/disk-backup/components/List.vue
  containers/Compute/views/disk-backup/mixins/columns.js
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/host-image/components/List.vue
  containers/Compute/views/host-image/mixins/columns.js
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/image/mixins/columns.js
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/mixins/columns.js
  containers/Compute/views/instance-group/components/List.vue
  containers/Compute/views/instance-group/mixins/columns.js
  containers/Compute/views/physicalmachine/components/List.vue
  containers/Compute/views/physicalmachine/mixins/columns.js
  containers/Compute/views/scaling-group/components/List.vue
  containers/Compute/views/scaling-group/mixins/columns.js
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/mixins/columns.js
  containers/Compute/views/servertemplate/components/List.vue
  containers/Compute/views/servertemplate/mixins/columns.js
  containers/Compute/views/snapshot-instance/components/List.vue
  containers/Compute/views/snapshot-instance/mixins/columns.js
  containers/Compute/views/snapshot/components/List.vue
  containers/Compute/views/snapshot/mixins/columns.js
  containers/Compute/views/snapshotpolicy/components/List.vue
  containers/Compute/views/snapshotpolicy/mixins/columns.js
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/webapp/components/List.vue
  containers/Compute/views/webapp/mixins/columns.js
  src/mixins/sidePage.js
  src/utils/common/tableColumn.js
Labels: size/L

#3888 Automated cherry pick of #3885: feat: #3735 主机模块状态为失败时，增加查看日志的快捷入口
  containers/Compute/views/baremetal/components/List.vue
  containers/Compute/views/baremetal/mixins/columns.js
  containers/Compute/views/disk-backup/components/List.vue
  containers/Compute/views/disk-backup/mixins/columns.js
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/host-image/components/List.vue
  containers/Compute/views/host-image/mixins/columns.js
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/image/mixins/columns.js
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/mixins/columns.js
  containers/Compute/views/instance-group/components/List.vue
  containers/Compute/views/instance-group/mixins/columns.js
  containers/Compute/views/physicalmachine/components/List.vue
  containers/Compute/views/physicalmachine/mixins/columns.js
  containers/Compute/views/scaling-group/components/List.vue
  containers/Compute/views/scaling-group/mixins/columns.js
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/mixins/columns.js
  containers/Compute/views/servertemplate/components/List.vue
  containers/Compute/views/servertemplate/mixins/columns.js
  containers/Compute/views/snapshot-instance/components/List.vue
  containers/Compute/views/snapshot-instance/mixins/columns.js
  containers/Compute/views/snapshot/components/List.vue
  containers/Compute/views/snapshot/mixins/columns.js
  containers/Compute/views/snapshotpolicy/components/List.vue
  containers/Compute/views/snapshotpolicy/mixins/columns.js
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/webapp/components/List.vue
  containers/Compute/views/webapp/mixins/columns.js
  src/mixins/sidePage.js
  src/utils/common/tableColumn.js
Labels: size/L

#3887 Automated cherry pick of #3885: feat: #3735 主机模块状态为失败时，增加查看日志的快捷入口
  containers/Compute/views/baremetal/components/List.vue
  containers/Compute/views/baremetal/mixins/columns.js
  containers/Compute/views/disk-backup/components/List.vue
  containers/Compute/views/disk-backup/mixins/columns.js
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/host-image/components/List.vue
  containers/Compute/views/host-image/mixins/columns.js
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/image/mixins/columns.js
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/mixins/columns.js
  containers/Compute/views/instance-group/components/List.vue
  containers/Compute/views/instance-group/mixins/columns.js
  containers/Compute/views/physicalmachine/components/List.vue
  containers/Compute/views/physicalmachine/mixins/columns.js
  containers/Compute/views/scaling-group/components/List.vue
  containers/Compute/views/scaling-group/mixins/columns.js
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/mixins/columns.js
  containers/Compute/views/servertemplate/components/List.vue
  containers/Compute/views/servertemplate/mixins/columns.js
  containers/Compute/views/snapshot-instance/components/List.vue
  containers/Compute/views/snapshot-instance/mixins/columns.js
  containers/Compute/views/snapshot/components/List.vue
  containers/Compute/views/snapshot/mixins/columns.js
  containers/Compute/views/snapshotpolicy/components/List.vue
  containers/Compute/views/snapshotpolicy/mixins/columns.js
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/webapp/components/List.vue
  containers/Compute/views/webapp/mixins/columns.js
  src/mixins/sidePage.js
  src/utils/common/tableColumn.js
Labels: size/L

#3889 feat(3735): 网络模块状态为失败时，增加查看日志的快捷入口
  containers/Network/views/cdn/components/List.vue
  containers/Network/views/cdn/mixins/columns.js
  containers/Network/views/dns-zone/components/List.vue
  containers/Network/views/dns-zone/mixins/columns.js
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/global-vpc/components/List.vue
  containers/Network/views/global-vpc/mixins/columns.js
  containers/Network/views/ipv6-gateway/components/List.vue
  containers/Network/views/ipv6-gateway/mixins/columns.js
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/mixins/columns.js
  containers/Network/views/nats/components/List.vue
  containers/Network/views/nats/mixins/columns.js
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/mixins/columns.js
  containers/Network/views/route-table/components/List.vue
  containers/Network/views/route-table/mixins/columns.js
  containers/Network/views/vpc-network/components/List.vue
  containers/Network/views/vpc-network/mixins/columns.js
  containers/Network/views/vpc-peer-connect/components/List.vue
  containers/Network/views/vpc-peer-connect/mixins/columns.js
  containers/Network/views/vpc/components/List.vue
  containers/Network/views/vpc/mixins/columns.js
  containers/Network/views/waf/components/List.vue
  containers/Network/views/waf/mixins/columns.js
  containers/Network/views/wire/components/List.vue
  containers/Network/views/wire/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/M

#3890 Automated cherry pick of #3889: feat(3735): 网络模块状态为失败时，增加查看日志的快捷入口
  containers/Network/views/cdn/components/List.vue
  containers/Network/views/cdn/mixins/columns.js
  containers/Network/views/dns-zone/components/List.vue
  containers/Network/views/dns-zone/mixins/columns.js
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/global-vpc/components/List.vue
  containers/Network/views/global-vpc/mixins/columns.js
  containers/Network/views/ipv6-gateway/components/List.vue
  containers/Network/views/ipv6-gateway/mixins/columns.js
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/mixins/columns.js
  containers/Network/views/nats/components/List.vue
  containers/Network/views/nats/mixins/columns.js
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/mixins/columns.js
  containers/Network/views/route-table/components/List.vue
  containers/Network/views/route-table/mixins/columns.js
  containers/Network/views/vpc-network/components/List.vue
  containers/Network/views/vpc-network/mixins/columns.js
  containers/Network/views/vpc-peer-connect/components/List.vue
  containers/Network/views/vpc-peer-connect/mixins/columns.js
  containers/Network/views/vpc/components/List.vue
  containers/Network/views/vpc/mixins/columns.js
  containers/Network/views/waf/components/List.vue
  containers/Network/views/waf/mixins/columns.js
  containers/Network/views/wire/components/List.vue
  containers/Network/views/wire/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/M

#3891 Automated cherry pick of #3889: feat(3735): 网络模块状态为失败时，增加查看日志的快捷入口
  containers/Network/views/cdn/components/List.vue
  containers/Network/views/cdn/mixins/columns.js
  containers/Network/views/dns-zone/components/List.vue
  containers/Network/views/dns-zone/mixins/columns.js
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/global-vpc/components/List.vue
  containers/Network/views/global-vpc/mixins/columns.js
  containers/Network/views/ipv6-gateway/components/List.vue
  containers/Network/views/ipv6-gateway/mixins/columns.js
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/mixins/columns.js
  containers/Network/views/nats/components/List.vue
  containers/Network/views/nats/mixins/columns.js
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/mixins/columns.js
  containers/Network/views/route-table/components/List.vue
  containers/Network/views/route-table/mixins/columns.js
  containers/Network/views/vpc-network/components/List.vue
  containers/Network/views/vpc-network/mixins/columns.js
  containers/Network/views/vpc-peer-connect/components/List.vue
  containers/Network/views/vpc-peer-connect/mixins/columns.js
  containers/Network/views/vpc/components/List.vue
  containers/Network/views/vpc/mixins/columns.js
  containers/Network/views/waf/components/List.vue
  containers/Network/views/waf/mixins/columns.js
  containers/Network/views/wire/components/List.vue
  containers/Network/views/wire/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/M

#3894 fix: create server sriov params
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/sections/ServerNetwork/NetworkSchedtag.vue
  containers/Compute/utils/createServer.js
Labels: size/XS

#3896 feat(storage#3735): 存储模块状态为失败时，增加查看日志的快捷入口
  containers/Storage/views/access-group/components/List.vue
  containers/Storage/views/access-group/mixins/columns.js
  containers/Storage/views/backup-storage/components/List.vue
  containers/Storage/views/backup-storage/mixins/columns.js
  containers/Storage/views/blockstorage/components/List.vue
  containers/Storage/views/blockstorage/mixins/columns.js
  containers/Storage/views/bucket/components/List.vue
  containers/Storage/views/bucket/mixins/columns.js
  containers/Storage/views/file-system/components/List.vue
  containers/Storage/views/file-system/mixins/columns.js
  containers/Storage/views/tablestore/components/List.vue
  containers/Storage/views/tablestore/mixins/columns.js
Labels: size/M

#3897 Automated cherry pick of #3896: feat(storage#3735): 存储模块状态为失败时，增加查看日志的快捷入口
  containers/Storage/views/access-group/components/List.vue
  containers/Storage/views/access-group/mixins/columns.js
  containers/Storage/views/backup-storage/components/List.vue
  containers/Storage/views/backup-storage/mixins/columns.js
  containers/Storage/views/blockstorage/components/List.vue
  containers/Storage/views/blockstorage/mixins/columns.js
  containers/Storage/views/bucket/components/List.vue
  containers/Storage/views/bucket/mixins/columns.js
  containers/Storage/views/file-system/components/List.vue
  containers/Storage/views/file-system/mixins/columns.js
  containers/Storage/views/tablestore/components/List.vue
  containers/Storage/views/tablestore/mixins/columns.js
Labels: size/M

#3899 Automated cherry pick of #3896: feat(storage#3735): 存储模块状态为失败时，增加查看日志的快捷入口
  containers/Storage/views/access-group/components/List.vue
  containers/Storage/views/access-group/mixins/columns.js
  containers/Storage/views/blockstorage/components/List.vue
  containers/Storage/views/blockstorage/mixins/columns.js
  containers/Storage/views/bucket/components/List.vue
  containers/Storage/views/bucket/mixins/columns.js
  containers/Storage/views/file-system/components/List.vue
  containers/Storage/views/file-system/mixins/columns.js
Labels: size/M

#3900 feat(DB#3735): 数据库模块状态为失败时，增加查看日志的快捷入口
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/mongodb/mixins/columns.js
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/mixins/columns.js
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/mixins/columns.js
Labels: size/S

#3901 Automated cherry pick of #3900: feat(DB#3735): 数据库模块状态为失败时，增加查看日志的快捷入口
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/mongodb/mixins/columns.js
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/mixins/columns.js
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/mixins/columns.js
Labels: size/S

#3903 Automated cherry pick of #3900: feat(DB#3735): 数据库模块状态为失败时，增加查看日志的快捷入口
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/mongodb/mixins/columns.js
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/mixins/columns.js
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/mixins/columns.js
Labels: size/S

#3904 fix: status error view log
  src/utils/common/tableColumn.js
Labels: size/XS

#3905 Automated cherry pick of #3904: fix: status error view log
  src/utils/common/tableColumn.js
Labels: size/XS

#3907 Automated cherry pick of #3904: fix: status error view log
  src/utils/common/tableColumn.js
Labels: size/XS

#3908 feat: account project mapping show resource or project
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/mixins/columns.js
Labels: area/cloudenv, size/S

#3909 Automated cherry pick of #3908: feat: account project mapping show resource or project
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/mixins/columns.js
Labels: size/S

#3910 fix: #8728 云管内新建cdn传参问题
  containers/Network/views/cdn/create/index.vue
Labels: size/S

#3911 Automated cherry pick of #3910: fix: #8728 云管内新建cdn传参问题
  containers/Network/views/cdn/create/index.vue
Labels: size/S

#3912 fix: #8728 云管内新建cdn传参将generate_name修改为name
  containers/Network/views/cdn/create/index.vue
Labels: size/XS

#3913 Automated cherry pick of #3912: fix: #8728 云管内新建cdn传参将generate_name修改为name
  containers/Network/views/cdn/create/index.vue
Labels: size/XS

#3914 feat: #4107 account detail add resource tenant info
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  containers/Cloudenv/views/cloudprovider/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudprovider/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/sidepage/Detail.vue
  containers/Cloudenv/views/cloudprovider/utils/columns.js
  containers/Cloudenv/views/projectmapping/components/List.vue
  containers/Cloudenv/views/projectmapping/components/RuleList/columns.js
  containers/Cloudenv/views/projectmapping/components/RuleList/index.vue
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/dialogs/Delete.vue
  containers/Cloudenv/views/projectmapping/dialogs/DeleteResourceOwner.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleCreate.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleEdit.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleUpdate.vue
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
Labels: area/cloudenv, size/XXL

#3915 Automated cherry pick of #3914: fix: #8726 projectmapping rules setting add tag_key
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  containers/Cloudenv/views/cloudprovider/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudprovider/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/sidepage/Detail.vue
  containers/Cloudenv/views/cloudprovider/utils/columns.js
  containers/Cloudenv/views/projectmapping/components/List.vue
  containers/Cloudenv/views/projectmapping/components/RuleList/columns.js
  containers/Cloudenv/views/projectmapping/components/RuleList/index.vue
  containers/Cloudenv/views/projectmapping/dialogs/Create.vue
  containers/Cloudenv/views/projectmapping/dialogs/Delete.vue
  containers/Cloudenv/views/projectmapping/dialogs/DeleteResourceOwner.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleCreate.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleEdit.vue
  containers/Cloudenv/views/projectmapping/dialogs/ProjectMappingRuleUpdate.vue
  containers/Cloudenv/views/projectmapping/dialogs/Update.vue
  containers/Cloudenv/views/projectmapping/mixins/singleActions.js
Labels: size/XXL

#3916 fix: #8675 设置宿主机预留资源文案修改
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
Labels: size/XS

#3918 feat: #4052 详情页增加刷新按钮
  src/components/BaseSidePage/index.vue
Labels: size/S

#3919 Automated cherry pick of #3918: feat: #4052 详情页增加刷新按钮
  src/components/BaseSidePage/index.vue
Labels: size/S

#3920 feat: #4091 磁盘类型文案Ceph RBD 修改为Ceph分布式存储
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  src/constants/compute.js
Labels: size/XS

#3921 Automated cherry pick of #3920: feat: #4091 磁盘类型文案Ceph RBD 修改为Ceph分布式存储
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  src/constants/compute.js
Labels: size/XS

#3922 feat: cloudaccount detail add tooltip for resource project
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  containers/Cloudenv/views/cloudprovider/sidepage/Detail.vue
  src/components/HelpTooltip/index.vue
Labels: area/cloudenv, size/S

#3923 Automated cherry pick of #3922: feat: cloudaccount detail add tooltip for resource project
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  containers/Cloudenv/views/cloudprovider/sidepage/Detail.vue
  src/components/HelpTooltip/index.vue
Labels: size/S
