Repository yunionio/dashboard, pull requests merged in 2022-01, with the labels that each got.

#1839 Automated cherry pick of #1820: feature: vpc vip support
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/EipConfig/index.vue
  containers/Compute/views/instance-group/dialogs/AttachNetwork.vue
  containers/Compute/views/instance-group/dialogs/BindEip.vue
  containers/Compute/views/instance-group/dialogs/DetachNetwork.vue
  containers/Compute/views/instance-group/dialogs/UnbindEip.vue
  containers/Compute/views/instance-group/mixins/columns.js
  containers/Compute/views/instance-group/mixins/singleActions.js
  containers/Compute/views/instance-group/mixins/vipcolumns.js
  containers/Compute/views/instance-group/mixins/vipsingleActions.js
  containers/Compute/views/instance-group/sidepage/VIPList.vue
  containers/Compute/views/instance-group/sidepage/VMInstanceListForInstanceGroup.vue
  containers/Compute/views/instance-group/sidepage/index.vue
  containers/Compute/views/networks/mixins/columns.js
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/XL

#1840 feat: #3567 进度信息优化
  src/components/Status/index.vue
Labels: size/XS

#1841 Automated cherry pick of #1840: feat: #3567 进度信息优化
  src/components/Status/index.vue
Labels: size/XS

#1842 fix: #8078 add progress for detail
  src/components/Detail/index.js
Labels: size/XS

#1846 Automated cherry pick of #1842: fix: #8078 add progress for detail
  src/components/Detail/index.js
Labels: size/XS

#1844 Automated cherry pick of #1842: fix: #8078 add progress for detail
  src/components/Detail/index.js
Labels: size/XS

#1843 Automated cherry pick of #1838: feat: update topology style
  containers/Network/sections/Topology/index.scss
  containers/Network/views/vpc/components/ResTopology/ResWire.vue
  containers/Network/views/vpc/components/ResTopology/Wire/index.vue
  containers/Network/views/vpc/components/ResTopology/index.vue
  containers/Network/views/wire/components/ResTopology/Wire/index.vue
Labels: size/M

#1845 Automated cherry pick of #1838: feat: update topology style
  containers/Network/sections/Topology/index.scss
  containers/Network/views/vpc/components/ResTopology/ResWire.vue
  containers/Network/views/vpc/components/ResTopology/Wire/index.vue
  containers/Network/views/vpc/components/ResTopology/index.vue
  containers/Network/views/wire/components/ResTopology/Wire/index.vue
Labels: size/M

#1848 feat: #3557 update progress for save image
  containers/Compute/views/image/mixins/columns.js
  src/components/Status/index.vue
Labels: size/XS

#1850 Automated cherry pick of #1836: feat: #3558 vminstance acttatch usb api
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
  containers/Compute/views/vminstance/dialogs/AttachUsb.vue
Labels: size/L

#1851 feat: accuracy usb passthrough i18n
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/gpu/dialogs/AttachDialog.vue
Labels: area/compute, size/S

#1852 Automated cherry pick of #1851: feat: accuracy usb passthrough i18n
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/gpu/dialogs/AttachDialog.vue
Labels: size/S

#1855 Automated cherry pick of #1852: feat: accuracy usb passthrough i18n
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/gpu/dialogs/AttachDialog.vue
Labels: size/M

#1856 Automated cherry pick of #1824: fix: cherry pick error
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/XS

#1857 fix: #8078 日志加载已经完毕了，加载更多仍然可以点击，但是数据无更新
  src/components/PageList/components/Table.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/list.js
Labels: size/S

#1858 Automated cherry pick of #1857: fix: #8078 日志加载已经完毕了，加载更多仍然可以点击，但是数据无更新
  src/components/PageList/components/Table.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/list.js
Labels: size/S

#1859 Automated cherry pick of #1857: fix: #8078 日志加载已经完毕了，加载更多仍然可以点击，但是数据无更新
  src/components/PageList/components/Table.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/list.js
Labels: size/S

#1860 fix: i18n for load no more
  src/components/PageList/components/Table.vue
Labels: size/XS

#1861 Automated cherry pick of #1860: fix: i18n for load no more
  src/components/PageList/components/Table.vue
Labels: size/XS

#1862 Automated cherry pick of #1860: fix: i18n for load no more
  src/components/PageList/components/Table.vue
Labels: size/XS

#1863 fix: vm set usb error
  containers/Compute/views/vminstance/dialogs/AttachUsb.vue
Labels: area/compute, size/S

#1864 Automated cherry pick of #1796: feat: #3548 虚拟机更换IP提示优化
  containers/Compute/views/vminstance/dialogs/ChangeIp.vue
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/S

#1865 Automated cherry pick of #1818: feat: #3551 blockstorage add amount status
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#1866 Fix/glb to 3.8/compute
  containers/Compute/views/host/sidepage/index.vue
  containers/Compute/views/instance-group/mixins/singleActions.js
  containers/Compute/views/instance-group/sidepage/VIPList.vue
Labels: area/compute, size/XS

#1867 Automated cherry pick of #1866: fix: disassociate vip refresh instancesgroup
  containers/Compute/views/host/sidepage/index.vue
  containers/Compute/views/instance-group/mixins/singleActions.js
  containers/Compute/views/instance-group/sidepage/VIPList.vue
Labels: size/XS

#1869 fix: load more
  src/components/PageList/components/Table.vue
Labels: size/XS

#1870 Automated cherry pick of #1869: fix: load more
  src/components/PageList/components/Table.vue
Labels: size/XS

#1871 Automated cherry pick of #1869: fix: load more
  src/components/PageList/components/Table.vue
Labels: size/XS

#1868 feat: #3569 accuracy gpu i18n
  containers/Compute/views/host/sidepage/index.vue
Labels: area/compute, size/XS

#1872 fix: #8079 eip列表关联资源点击无效
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/utils/columns.js
Labels: size/XS

#1873 Automated cherry pick of #1872: fix: #8079 eip列表关联资源点击无效
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/utils/columns.js
Labels: size/XS

#1874 Automated cherry pick of #1872: fix: #8079 eip列表关联资源点击无效
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/utils/columns.js
Labels: size/XS

#1876 fix: #8081 已经绑定反亲和组的eip，在绑定资源列表 应该加上 反亲和组
  containers/Network/views/eip/constants.js
  containers/Network/views/eip/utils/columns.js
Labels: size/M

#1878 Automated cherry pick of #1876: fix: #8081 已经绑定反亲和组的eip，在绑定资源列表 应该加上 反亲和组
  containers/Network/views/eip/constants.js
  containers/Network/views/eip/utils/columns.js
Labels: size/M

#1877 Automated cherry pick of #1876: fix: #8081 已经绑定反亲和组的eip，在绑定资源列表 应该加上 反亲和组
  containers/Network/views/eip/constants.js
  containers/Network/views/eip/utils/columns.js
Labels: size/M

#1875 feat: #3570 externalproject support export
  containers/Cloudenv/views/externalproject/components/List.vue
Labels: size/M, area/cloudenv

#1879 fix: #8085 新建本地IDC的弹性eip时计费方式应该是按带宽计费
  containers/Network/views/eip/create/index.vue
Labels: size/XS

#1880 Automated cherry pick of #1879: fix: #8085 新建本地IDC的弹性eip时计费方式应该是按带宽计费
  containers/Network/views/eip/create/index.vue
Labels: size/XS

#1885 fix: #8088 批量操作增加跳过CPU检查
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#1886 Automated cherry pick of #1885: fix: #8088 批量操作增加跳过CPU检查
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#1883 fix: passthrough device for host
  containers/Compute/views/host/sidepage/Gpu.vue
  containers/Compute/views/host/sidepage/index.vue
Labels: area/compute, size/XS

#1884 Automated cherry pick of #1883: fix: passthrough device for host
  containers/Compute/views/host/sidepage/Gpu.vue
  containers/Compute/views/host/sidepage/index.vue
Labels: size/XS

#1887 fix: data copying i18n
  src/locales/en.json
Labels: size/XS

#1888 Automated cherry pick of #1887: fix: data copying i18n
  src/locales/en.json
Labels: size/XS

#1890 fix: cloudenv empty error
  src/utils/common/hypervisor.js
Labels: size/XS

#1892 fix: #8091 dashboard error
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/sections/ConsumptionConfig/index.vue
Labels: area/dashboard, size/XS

#1893 Automated cherry pick of #1892: fix: #8091 dashboard error
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/sections/ConsumptionConfig/index.vue
Labels: size/XS

#1894 fix: #8090 搜索优化
  src/components/SearchBox/AutoCompleter.vue
Labels: size/XS

#1895 Automated cherry pick of #1894: fix: #8090 搜索优化
  src/components/SearchBox/AutoCompleter.vue
Labels: size/XS

#1896 fix: edit server name change status refresh
  containers/Compute/views/vminstance/mixins/columns.js
  src/components/Detail/index.js
  src/utils/common/tableColumn.js
Labels: size/XS

#1898 feat: #3549 add menu policy
  containers/Helm/views/repo/mixins/singleActions.js
  containers/IAM/views/contact/components/List.vue
  containers/IAM/views/contact/mixins/singleActions.js
  containers/IAM/views/notifyconfig/components/List.vue
  containers/IAM/views/notifyconfig/mixins/singleActions.js
  containers/IAM/views/robots/components/List.vue
  containers/IAM/views/robots/mixins/singleActions.js
  containers/Monitor/views/alertrecordshields/components/List.vue
  src/constants/permission.js
Labels: size/M

#1901 feat: #3576 安全组名称支持中文输入
  containers/Compute/views/secgroup/dialogs/CloneSecgroup.vue
  containers/Compute/views/secgroup/dialogs/Create.vue
  containers/Compute/views/secgroup/mixins/columns.js
Labels: size/XS

#1902 Automated cherry pick of #1901: feat: #3576 安全组名称支持中文输入
  containers/Compute/views/secgroup/dialogs/CloneSecgroup.vue
  containers/Compute/views/secgroup/dialogs/Create.vue
  containers/Compute/views/secgroup/mixins/columns.js
Labels: size/XS

#1903 feat: disk resource add statistics
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/index.vue
Labels: size/M

#1904 feat: disk snapshot resource add statistics
  containers/Compute/views/snapshot/components/List.vue
  containers/Compute/views/snapshot/index.vue
Labels: size/M

#1905 feat: add menu policy
  containers/Cloudenv/views/cloudprovider/components/List.vue
  containers/Cloudenv/views/cloudprovider/mixins/singleActions.js
  containers/Cloudenv/views/projectmapping/components/RuleList/columns.js
  containers/Cloudenv/views/samluser/components/List.vue
  containers/Cloudenv/views/samluser/mixins/singleActions.js
  containers/Compute/views/image/sidepage/Cache.vue
  containers/Compute/views/instance-group/mixins/vipsingleActions.js
  containers/Compute/views/instance-group/sidepage/VIPList.vue
  containers/Compute/views/networks/components/List.vue
  containers/Compute/views/networks/mixins/singleActions.js
  containers/Compute/views/node-alert/components/List.vue
  containers/Compute/views/scaling-group/sidepage/ServerList.vue
  containers/Compute/views/secgroup/sidepage/Cache.vue
  containers/Compute/views/snapshotpolicy/sidepage/Cache.vue
  containers/DB/views/rds-account/mixins/singleActions.js
  containers/DB/views/rds-backup/components/List.vue
  containers/DB/views/rds-backup/mixins/singleActions.js
  containers/DB/views/redis/sidepage/AccountList.vue
  containers/DB/views/redis/sidepage/BackupList.vue
  containers/DB/views/redis/sidepage/WhiteList.vue
  containers/IAM/views/group/sidepage/ProjectList.vue
  containers/IAM/views/group/sidepage/UserList.vue
  containers/IAM/views/projects/sidepage/DirectlyUnderUserList.vue
  containers/IAM/views/role/sidepage/Policies.vue
  containers/IAM/views/user/mixins/singleActions.js
  containers/IAM/views/user/sidepage/Groups.vue
  containers/IAM/views/user/sidepage/Projects.vue
  containers/IAM/views/user/sidepage/SamluserList.vue
  containers/Network/views/dns-recordset/components/List.vue
  containers/Network/views/dns-recordset/mixins/singleActions.js
  containers/Network/views/lbcerts/sidepage/Cache.vue
  containers/Network/views/reserved-ip/components/List.vue
  containers/Network/views/reserved-ip/mixins/singleActions.js
  containers/Network/views/vpc-network/sidepage/RouteSet.vue
  containers/Network/views/vpc-network/sidepage/Vpc.vue
  containers/Storage/views/access-group/components/AccessGroupRule.vue
  containers/Storage/views/access-group/sidepage/Cache.vue
  containers/Storage/views/blockstorage/sidepage/CachedImages.vue
  containers/Storage/views/bucket/sidepage/CrossDomainRules.vue
  containers/Storage/views/bucket/sidepage/Policies.vue
  containers/Storage/views/mount-target/mixins/singleActions.js
  src/constants/permission.js
Labels: size/L

#1908 feat: network resource add statistics
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/index.vue
  src/sections/ResStatusTab/index.vue
Labels: size/M

#1909 Automated cherry pick of #1908: feat: network resource add statistics
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/index.vue
  src/sections/ResStatusTab/index.vue
Labels: size/M

#1910 feat: eip resource add statistics
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/index.vue
Labels: size/M

#1911 Automated cherry pick of #1910: feat: eip resource add statistics
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/index.vue
Labels: size/M

#1912 feat: host resource update statistics
  containers/Compute/views/host/index.vue
Labels: size/M

#1914 feat: physicalmachine resource update statistics
  containers/Compute/views/physicalmachine/index.vue
Labels: size/M

#1916 feat: rds resource update statistics
  containers/DB/views/rds/index.vue
Labels: size/S

#1917 Automated cherry pick of #1916: feat: rds resource update statistics
  containers/DB/views/rds/index.vue
Labels: size/S

#1923 feat: #3574 bill form select date format month
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
Labels: size/M, area/cloudenv

#1924 Automated cherry pick of #1923: feat: #3574 bill form select date format month
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
Labels: size/M

#1920 feat: add error dialog i18n
  src/constants/error.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/error.js
Labels: size/M

#1921 Automated cherry pick of #1920: feat: add error dialog i18n
  src/constants/error.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/error.js
Labels: size/M

#1922 Automated cherry pick of #1920: feat: add error dialog i18n
  src/constants/error.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/error.js
Labels: size/M

#1925 fix: #8097 blockstorage status error
  containers/Storage/views/blockstorage/sidepage/index.vue
Labels: area/storage, size/XS

#1926 Automated cherry pick of #1925: fix: #8097 blockstorage status error
  containers/Storage/views/blockstorage/sidepage/index.vue
Labels: size/XS

#1927 Automated cherry pick of #1925: fix: #8097 blockstorage status error
  containers/Storage/views/blockstorage/sidepage/index.vue
Labels: size/XS

#1928 fix: #8086 secgroup action check
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/instance-group/mixins/vipsingleActions.js
  containers/Compute/views/instance-group/sidepage/VIPList.vue
Labels: area/compute, size/S

#1929 Automated cherry pick of #1928: fix: #8086 secgroup action check
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/instance-group/mixins/vipsingleActions.js
  containers/Compute/views/instance-group/sidepage/VIPList.vue
Labels: size/S

#1930 Automated cherry pick of #1928: fix: #8086 secgroup action check
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/instance-group/mixins/vipsingleActions.js
  containers/Compute/views/instance-group/sidepage/VIPList.vue
Labels: size/S

#1934 fix: helm repo delete i18n
  containers/Helm/locales/en.json
  containers/Helm/locales/zh-CN.json
Labels: size/XS

#1935 Automated cherry pick of #1934: fix: helm repo delete i18n
  containers/Helm/locales/en.json
  containers/Helm/locales/zh-CN.json
Labels: size/XS

#1931 fix: #8093 add server status
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/compute, size/XS

#1932 Automated cherry pick of #1931: fix: #8093 add server status
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#1933 Automated cherry pick of #1931: fix: #8093 add server status
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#1936 feat: vpc resource add statistics
  containers/Network/views/vpc/components/List.vue
  containers/Network/views/vpc/index.vue
  src/sections/ResStatusTab/index.vue
Labels: size/M

#1938 feat: mongodb resource add statistics
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/mongodb/index.vue
Labels: size/M

#1939 Automated cherry pick of #1938: feat: mongodb resource add statistics
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/mongodb/index.vue
Labels: size/M

#1941 Automated cherry pick of #1940: feat: cdn resource add statistics
  containers/Network/views/cdn/components/List.vue
  containers/Network/views/cdn/index.vue
  src/sections/ResStatusTab/index.vue
Labels: size/M

#1942 feat: wire resource add statistics
  containers/Network/views/wire/components/List.vue
  containers/Network/views/wire/index.vue
Labels: size/M

#1944 fix: add nutanix account create
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Nutanix.vue
  scope/assets/nutanix.svg
  scope/locales/en.json
  src/assets/images/providers/nutanix.svg
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#1945 Automated cherry pick of #1944: fix: add nutanix account create
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Nutanix.vue
  scope/assets/nutanix.svg
  scope/locales/en.json
  src/assets/images/providers/nutanix.svg
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#1946 Automated cherry pick of #1944: fix: add nutanix account create
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Nutanix.vue
  scope/assets/nutanix.svg
  scope/locales/en.json
  src/assets/images/providers/nutanix.svg
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#1947 fix: nutanix guide
  src/constants/feature.js
Labels: size/XS

#1948 Automated cherry pick of #1947: fix: nutanix guide
  src/constants/feature.js
Labels: size/XS

#1949 Automated cherry pick of #1947: fix: nutanix guide
  src/constants/feature.js
Labels: size/XS

#1951 Automated cherry pick of #1950: fix: add nutanix trans
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#1952 Automated cherry pick of #1950: fix: add nutanix trans
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#1954 Automated cherry pick of #1953: feat: add disk backup
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/router/index.js
  containers/Compute/views/disk-backup/components/List.vue
  containers/Compute/views/disk-backup/constants.js
  containers/Compute/views/disk-backup/dialogs/RollbackDiskBackup.vue
  containers/Compute/views/disk-backup/index.vue
  containers/Compute/views/disk-backup/mixins/columns.js
  containers/Compute/views/disk-backup/mixins/singleActions.js
  containers/Compute/views/disk-backup/sidepage/Detail.vue
  containers/Compute/views/disk-backup/sidepage/index.vue
  containers/Compute/views/disk-backup/utils/columns.js
  containers/Compute/views/disk/dialogs/CreateBackupDialog.vue
  containers/Compute/views/disk/mixins/singleActions.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XL

#1955 feat: #3583 accuracy components
  src/components/PageList/index.vue
Labels: size/XS

#1956 Automated cherry pick of #1955: feat: #3583 accuracy components
  src/components/PageList/index.vue
Labels: size/XS

#1957 fix: k8s doc url
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/views/cluster/constants/index.js
Labels: size/XS

#1958 Automated cherry pick of #1957: fix: k8s doc url
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/views/cluster/constants/index.js
Labels: size/XS

#1960 fix: #8103 vpc互联详情路由tab中应该去掉状态列
  containers/Network/views/vpc-network/sidepage/RouteSet.vue
Labels: size/XS

#1961 Automated cherry pick of #1960: fix: #8103 vpc互联详情路由tab中应该去掉状态列
  containers/Network/views/vpc-network/sidepage/RouteSet.vue
Labels: size/XS

#1962 fix: storage name the same rules
  containers/Storage/views/blockstorage/dialogs/Create.vue
  containers/Storage/views/blockstorage/mixins/columns.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/S

#1963 Automated cherry pick of #1962: fix: storage name the same rules
  containers/Storage/views/blockstorage/dialogs/Create.vue
  containers/Storage/views/blockstorage/mixins/columns.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/S

#1965 Automated cherry pick of #1962: fix: storage name the same rules
  containers/Storage/views/blockstorage/dialogs/Create.vue
  containers/Storage/views/blockstorage/mixins/columns.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/S

#1964 Automated cherry pick of #1962: fix: storage name the same rules
  containers/Storage/views/blockstorage/dialogs/Create.vue
  containers/Storage/views/blockstorage/mixins/columns.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/S

#1966 fix: #8106 instancegroup error
  containers/Compute/views/instance-group/components/List.vue
  containers/Compute/views/instance-group/dialogs/BindEip.vue
  containers/Compute/views/instance-group/dialogs/UnbindServer.vue
  containers/Compute/views/instance-group/mixins/singleActions.js
  containers/Compute/views/instance-group/sidepage/VIPList.vue
Labels: size/M

#1967 Automated cherry pick of #1966: fix: #8106 instancegroup error
  containers/Compute/views/instance-group/components/List.vue
  containers/Compute/views/instance-group/dialogs/BindEip.vue
  containers/Compute/views/instance-group/dialogs/UnbindServer.vue
  containers/Compute/views/instance-group/mixins/singleActions.js
  containers/Compute/views/instance-group/sidepage/VIPList.vue
Labels: size/M

#1968 Automated cherry pick of #1966: fix: #8106 instancegroup error
  containers/Compute/views/instance-group/components/List.vue
  containers/Compute/views/instance-group/dialogs/BindEip.vue
  containers/Compute/views/instance-group/dialogs/UnbindServer.vue
  containers/Compute/views/instance-group/mixins/singleActions.js
  containers/Compute/views/instance-group/sidepage/VIPList.vue
Labels: size/M

#1969 feat: #3585 主机新建，调度标签优化
  containers/Compute/utils/createServer.js
  src/sections/SchedtagPolicy/index.vue
Labels: size/XS

#1970 Automated cherry pick of #1969: feat: #3585 主机新建，调度标签优化
  containers/Compute/utils/createServer.js
  src/sections/SchedtagPolicy/index.vue
Labels: size/XS

#1972 fix: add brand for route table detail
  containers/Network/views/route-table/sidepage/Detail.vue
Labels: size/XS

#1973 Automated cherry pick of #1972: fix: add brand for route table detail
  containers/Network/views/route-table/sidepage/Detail.vue
Labels: size/XS

#1974 fix: apsara support bucket
  containers/Storage/router/index.js
Labels: area/storage, size/XS

#1975 Automated cherry pick of #1974: fix: apsara support bucket
  containers/Storage/router/index.js
Labels: size/XS

#1976 Automated cherry pick of #1974: fix: apsara support bucket
  containers/Storage/router/index.js
Labels: size/XS

#1977 fix: instance group bind server accuracy
  containers/Compute/views/instance-group/dialogs/BindServer.vue
Labels: size/M, area/compute

#1979 Automated cherry pick of #1977: fix: instance group bind server accuracy
  containers/Compute/views/instance-group/dialogs/BindServer.vue
Labels: size/M

#1978 Automated cherry pick of #1977: fix: instance group bind server accuracy
  containers/Compute/views/instance-group/dialogs/BindServer.vue
Labels: size/M

#1980 feat: create instance backup
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/dialogs/CreateBackupDialog.vue
  containers/Compute/views/vminstance/dialogs/BackupCreate.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Compute/views/vminstance/utils.js
Labels: size/L

#1981 Automated cherry pick of #1980: feat: create instance backup
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/dialogs/CreateBackupDialog.vue
  containers/Compute/views/vminstance/dialogs/BackupCreate.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Compute/views/vminstance/utils.js
Labels: size/L

#1982 feat: add permission
  src/constants/permission.js
Labels: size/XS

#1983 Automated cherry pick of #1982: feat: add permission
  src/constants/permission.js
Labels: size/XS

#1984 Automated cherry pick of #1982: feat: add permission
  src/constants/permission.js
Labels: size/XS

#1985 fix: monitor line chart error
  containers/Monitor/views/overview/components/index.vue
Labels: area/monitor, size/XS

#1986 fix[3.9]: add tree-project no value count number
  src/sections/TreeProject/index.vue
Labels: area/compute, size/XS

#1987 Automated cherry pick of #1986: fix[3.9]: add tree-project no value count number
  src/sections/TreeProject/index.vue
Labels: size/XS

#1988 fix[3.8]: #8116 base-select component load more error
  src/components/BaseSelect/index.vue
Labels: area/compute, size/XS

#1989 Automated cherry pick of #1988: fix[3.8]: #8116 base-select component load more error
  src/components/BaseSelect/index.vue
Labels: size/XS

#1990 Automated cherry pick of #1988: fix[3.8]: #8116 base-select component load more error
  src/components/BaseSelect/index.vue
Labels: size/XS

#1991 fix: k8s asbook text
  containers/Network/views/agent/dialogs/Asbook.vue
Labels: size/XS

#1992 Automated cherry pick of #1991: fix: k8s asbook text
  containers/Network/views/agent/dialogs/Asbook.vue
Labels: size/XS

#1994 Automated cherry pick of #1991: fix: k8s asbook text
  containers/Network/views/agent/dialogs/Asbook.vue
Labels: size/XS

#1993 Automated cherry pick of #1991: fix: k8s asbook text
  containers/Network/views/agent/dialogs/Asbook.vue
Labels: size/XS

#1995 feat: add global style
  src/styles/less/global.less
Labels: size/XS

#1996 Automated cherry pick of #1995: feat: add global style
  src/styles/less/global.less
Labels: size/XS

#1999 feat: support logout clear user info
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/App.vue
  src/sections/Auth/Login/components/LoginChallenge.vue
  src/sections/Auth/Login/index.vue
  src/store/modules/auth.js
Labels: size/M

#2000 Automated cherry pick of #1999: feat: support logout clear user info
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/App.vue
  src/sections/Auth/Login/components/LoginChallenge.vue
  src/sections/Auth/Login/index.vue
  src/store/modules/auth.js
Labels: size/M

#2001 Automated cherry pick of #1999: feat: support logout clear user info
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/App.vue
  src/sections/Auth/Login/components/LoginChallenge.vue
  src/sections/Auth/Login/index.vue
  src/store/modules/auth.js
Labels: size/M

#2002 Automated cherry pick of #1645: feat: timeout auto logout
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/App.vue
  src/mixins/logout.js
  src/store/modules/auth.js
  src/store/modules/common.js
Labels: size/L

#2004 feat: notifyconfig email add sender email address
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/notifyconfig/create/components/Email.vue
  containers/IAM/views/notifyconfig/sidepage/Detail.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#2005 Automated cherry pick of #2004: feat: notifyconfig email add sender email address
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/notifyconfig/create/components/Email.vue
  containers/IAM/views/notifyconfig/sidepage/Detail.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#2006 Automated cherry pick of #2004: feat: notifyconfig email add sender email address
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/notifyconfig/create/components/Email.vue
  containers/IAM/views/notifyconfig/sidepage/Detail.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#2008 fix: #8118 新增功能-功能选择
  containers/Compute/router/index.js
  containers/Network/router/index.js
Labels: size/XS

#2007 fix: error commit
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/App.vue
  src/mixins/logout.js
  src/store/modules/auth.js
  src/store/modules/common.js
Labels: size/L

#2009 Automated cherry pick of #2008: fix: #8118 新增功能-功能选择
  containers/Compute/router/index.js
  containers/Network/router/index.js
Labels: size/XS

#2012 fix: #8101 云账号第一次新建定时任务后 后端返回值不应该为空
  containers/Cloudenv/views/cloudaccount/dialogs/ScheduledtaskCreate.vue
Labels: size/XS

#2010 fix: error commit
  src/App.vue
Labels: size/XS

#2011 Automated cherry pick of #2010: fix: error commit
  src/App.vue
Labels: size/XS

#2014 feat: #3593 lb and bucket support apsara monitor
  containers/Network/constants/lb.js
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/lb/sidepage/Monitor.vue
  containers/Storage/constants/index.js
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/bucket/sidepage/Monitor.vue
Labels: size/M, area/network

#2015 Automated cherry pick of #2014: feat: #3593 lb and bucket support apsara monitor
  containers/Network/constants/lb.js
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/lb/sidepage/Monitor.vue
  containers/Storage/constants/index.js
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/bucket/sidepage/Monitor.vue
Labels: size/M

#2016 fix: lb monitor request params error
  containers/Network/views/lb/sidepage/Monitor.vue
Labels: area/monitor, size/XS
