Repository yunionio/dashboard, pull requests merged in 2022-05, with the labels that each got.

#2877 fix: #8366 下载方式修改
  containers/Storage/views/bucket/sidepage/Objects.vue
Labels: area/storage, size/XS

#2878 Automated cherry pick of #2877: fix: #8366 下载方式修改
  containers/Storage/views/bucket/sidepage/Objects.vue
Labels: size/XS

#2879 Automated cherry pick of #2877: fix: #8366 下载方式修改
  containers/Storage/views/bucket/sidepage/Objects.vue
Labels: size/XS

#2880 fix: #8385 物理机转换宿主机时指定IP子网时样式不应该错乱
  containers/Compute/views/physicalmachine/dialogs/Convert.vue
Labels: size/XS

#2881 Automated cherry pick of #2880: fix: #8385 物理机转换宿主机时指定IP子网时样式不应该错乱
  containers/Compute/views/physicalmachine/dialogs/Convert.vue
Labels: size/XS

#2882 Automated cherry pick of #2880: fix: #8385 物理机转换宿主机时指定IP子网时样式不应该错乱
  containers/Compute/views/physicalmachine/dialogs/Convert.vue
Labels: size/XS

#2883 fix: #8372 云账号新建账单分析范围
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: area/cloudenv, size/S

#2884 Automated cherry pick of #2883: fix: #8372 云账号新建账单分析范围
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: size/S

#2885 Automated cherry pick of #2883: fix: #8372 云账号新建账单分析范围
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: size/S

#2886 fix: #8369 安全组-缓存列表展示vpc云上id
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/secgroup/sidepage/Cache.vue
Labels: area/compute, size/S

#2887 Automated cherry pick of #2886: fix: #8369 安全组-缓存列表展示vpc云上id
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/secgroup/sidepage/Cache.vue
Labels: size/S

#2888 Automated cherry pick of #2886: fix: #8369 安全组-缓存列表展示vpc云上id
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/secgroup/sidepage/Cache.vue
Labels: size/S

#2889 feature: support daemon server
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Update.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/M

#2890 Automated cherry pick of #2889: feature: support daemon server
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Update.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/M

#2891 fix: #8366 下载方式优化
  containers/Storage/views/bucket/sidepage/Objects.vue
Labels: area/storage, size/XS

#2892 Automated cherry pick of #2891: fix: #8366 下载方式优化
  containers/Storage/views/bucket/sidepage/Objects.vue
Labels: size/XS

#2893 Automated cherry pick of #2891: fix: #8366 下载方式优化
  containers/Storage/views/bucket/sidepage/Objects.vue
Labels: size/XS

#2894 fix: 新增功能的兼容性判断
  src/mixins/step.js
Labels: size/XS

#2895 Automated cherry pick of #2894: fix: 新增功能的兼容性判断
  src/mixins/step.js
Labels: size/XS

#2896 fix: #8414 价格计算-线路类型传参错误
  containers/Network/views/eip/utils/columns.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/price.js
Labels: size/M, area/compute

#2897 Automated cherry pick of #2896: fix: #8414 价格计算-线路类型传参错误
  containers/Network/views/eip/utils/columns.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/price.js
Labels: size/M

#2900 fix: 云账号支持品高云的批量禁用删除
  containers/Cloudenv/views/cloudaccount/components/List.vue
Labels: area/cloudenv, size/S

#2901 fix: 云账号支持品高云的批量禁用删除
  containers/Cloudenv/views/cloudaccount/components/List.vue
Labels: size/S

#2902 fix: #8419 VMware主机更换镜像后，不会更新系统盘的大小
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/S

#2903 Automated cherry pick of #2902: fix: #8419 VMware主机更换镜像后，不会更新系统盘的大小
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/S

#2904 Automated cherry pick of #2902: fix: #8419 VMware主机更换镜像后，不会更新系统盘的大小
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/S

#2905 feat: #3672 全局配置-系统标签文案优化
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/sections/DialogManager/components/GlobalSettingUpdate.vue
Labels: size/S

#2906 feat: #3672 全局配置-系统标签文案优化
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/sections/DialogManager/components/GlobalSettingUpdate.vue
Labels: size/S

#2907 fix: create backup by unpack
  containers/Compute/views/instance-backup/dialogs/ImportUnpackDialog.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#2908 Automated cherry pick of #2907: fix: create backup by unpack
  containers/Compute/views/instance-backup/dialogs/ImportUnpackDialog.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#2909 fix: lb操作验证错误
  containers/Network/views/loadbalancerlistener/mixins/singleActions.js
Labels: area/network, size/XS

#2911 Automated cherry pick of #2909: fix: lb操作验证错误
  containers/Network/views/loadbalancerlistener/mixins/singleActions.js
Labels: size/XS

#2910 feat: #2893 lb支持vpc网络
  containers/Compute/sections/EipConfig/index.vue
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/eip/dialogs/BindServerDialog.vue
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/create/form/IDC.vue
  containers/Network/views/lb/create/form/Private.vue
  containers/Network/views/lb/create/form/Public.vue
  containers/Network/views/lb/create/form/mixin.js
  containers/Network/views/lb/dialogs/BindEip.vue
  containers/Network/views/lb/dialogs/DeleteLb.vue
  containers/Network/views/lb/dialogs/UnbindEip.vue
  containers/Network/views/lb/mixins/singleActions.js
  containers/Network/views/loadbalancerbackend/dialogs/Create.vue
  containers/Network/views/loadbalancerlistener/create/form/onecloud/Protocol.vue
  src/components/OcSelect/index.vue
  src/constants/permission.js
Labels: area/network, size/XL

#2912 Automated cherry pick of #2909: fix: lb操作验证错误
  containers/Network/views/loadbalancerlistener/mixins/singleActions.js
Labels: size/XS

#2913 fix: #8362 包年包月的虚拟机调整配置时，磁盘返写不应该为空
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/S

#2914 Automated cherry pick of #2913: fix: #8362 包年包月的虚拟机调整配置时，磁盘返写不应该为空
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/S

#2915 fix: remove debugger console
  containers/Compute/sections/DataDisk/index.vue
Labels: size/XS

#2916 Automated cherry pick of #2915: fix: remove debugger console
  containers/Compute/sections/DataDisk/index.vue
Labels: size/XS

#2917 Automated cherry pick of #2913: fix: #8362 包年包月的虚拟机调整配置时，磁盘返写不应该为空
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/S

#2919 fix: #8421 新建cloudpods云账号时，点击获取密钥的详情文档时url应该传递正确
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
Labels: size/XS

#2920 fix: #8425 kvm的宿主机上虚拟机数量0，进入维护模式模式按钮应该置灰不可点击
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/dialogs/MaintenanceIn.vue
Labels: size/XS

#2924 fix: lb新建监听错误
  containers/Network/views/loadbalancerlistener/create/form/onecloud/Protocol.vue
Labels: area/network, size/XS

#2921 fix: #8405 修复 按固定单位转换数值函数-无法像高级单位转换问题
  src/utils/utils.js
Labels: size/XS

#2922 Automated cherry pick of #2921: fix: #8405 修复 按固定单位转换数值函数-无法像高级单位转换问题
  src/utils/utils.js
Labels: size/XS

#2923 Automated cherry pick of #2921: fix: #8405 修复 按固定单位转换数值函数-无法像高级单位转换问题
  src/utils/utils.js
Labels: size/XS

#2925 Automated cherry pick of #2920: fix: #8425 kvm的宿主机上虚拟机数量0，进入维护模式模式按钮应该置灰不可点击
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/dialogs/MaintenanceIn.vue
Labels: size/XS

#2927 fix: lb绑定eip状态优化
  containers/Network/views/lb/dialogs/BindEip.vue
  containers/Network/views/lb/dialogs/UnbindEip.vue
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/network, size/S

#2928 feat: #3757 eip绑定资源提示优化
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/eip/dialogs/BindServerDialog.vue
Labels: area/network, size/XS

#2929 Automated cherry pick of #2928: feat: #3757 eip绑定资源提示优化
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/eip/dialogs/BindServerDialog.vue
Labels: size/XS

#2930 Automated cherry pick of #2928: feat: #3757 eip绑定资源提示优化
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/eip/dialogs/BindServerDialog.vue
Labels: size/XS

#2935 feat: #3716 增加云上项目名称校验规则
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/externalproject/dialogs/Create.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: area/cloudenv, size/S

#2936 Automated cherry pick of #2935: feat: #3716 增加云上项目名称校验规则
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/externalproject/dialogs/Create.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/S
