Repository yunionio/dashboard, pull requests merged in 2022-07, with the labels that each got.

#3129 fix: 时间格式化时区问题
  containers/Cloudenv/views/cloudaccount/sidepage/BillSync.vue
  src/utils/common/tableColumn.js
Labels: size/XS

#3130 Automated cherry pick of #3129: fix: 时间格式化时区问题
  containers/Cloudenv/views/cloudaccount/sidepage/BillSync.vue
  src/utils/common/tableColumn.js
Labels: size/XS

#3131 feat: #3788 kvm虚拟机新建支持传入自定义数据
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/components/CustomData.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: area/compute, size/L

#3132 fix: #8467 调整新建套餐规格
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/sku/dialogs/Create.vue
Labels: area/compute, size/S

#3134 Automated cherry pick of #3132: fix: #8467 调整新建套餐规格
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/sku/dialogs/Create.vue
Labels: size/S

#3133 Automated cherry pick of #3132: fix: #8467 调整新建套餐规格
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/sku/dialogs/Create.vue
Labels: size/S

#3137 fix: 资源统计切换路由调用异常的问题
  src/mixins/list.js
  src/mixins/resStatisticsMixin.js
Labels: size/S

#3135 feat: #3833 redis 磁盘增加展示字段
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/redis/sidepage/Detail.vue
Labels: size/M, area/compute, area/db

#3136 Automated cherry pick of #3135: feat: #3833 redis 磁盘增加展示字段
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/redis/sidepage/Detail.vue
Labels: size/M

#3138 fix: 标签未归类扩展
  src/components/PageList/TagFilter.vue
  src/sections/TagSelect/index.vue
  src/utils/common/tag.js
Labels: size/S

#3141 Automated cherry pick of #3140: fix: 标签未归类扩展
  src/sections/TagSelect/index.vue
  src/utils/common/tag.js
Labels: size/XS

#3142 fix: 组件参数优化
  src/components/Loader/index.vue
Labels: size/XS

#3143 Automated cherry pick of #3142: fix: 组件参数优化
  src/components/Loader/index.vue
Labels: size/XS

#3144 Automated cherry pick of #3142: fix: 组件参数优化
  src/components/Loader/index.vue
Labels: size/XS

#3146 fix: allow set datetime table column width
  src/utils/common/tableColumn.js
Labels: size/XS

#3149 Automated cherry pick of #3146: fix: allow set datetime table column width
  src/utils/common/tableColumn.js
Labels: size/XS

#3147 feat: update icons
  src/components/Icon/assets/menu-compute.svg
  src/components/Icon/assets/menu-dashboard.svg
  src/components/Icon/assets/menu-db.svg
  src/components/Icon/assets/menu-helm.svg
  src/components/Icon/assets/menu-iam.svg
  src/components/Icon/assets/menu-k8s.svg
  src/components/Icon/assets/menu-meter.svg
  src/components/Icon/assets/menu-middleware.svg
  src/components/Icon/assets/menu-monitor.svg
  src/components/Icon/assets/menu-multicloud.svg
  src/components/Icon/assets/menu-network.svg
  src/components/Icon/assets/menu-setting.svg
  src/components/Icon/assets/menu-storage.svg
  src/components/Icon/assets/menu-suggest.svg
Labels: size/M

#3148 Automated cherry pick of #3147: feat: update icons
  src/components/Icon/assets/menu-compute.svg
  src/components/Icon/assets/menu-dashboard.svg
  src/components/Icon/assets/menu-db.svg
  src/components/Icon/assets/menu-helm.svg
  src/components/Icon/assets/menu-iam.svg
  src/components/Icon/assets/menu-k8s.svg
  src/components/Icon/assets/menu-meter.svg
  src/components/Icon/assets/menu-middleware.svg
  src/components/Icon/assets/menu-monitor.svg
  src/components/Icon/assets/menu-multicloud.svg
  src/components/Icon/assets/menu-network.svg
  src/components/Icon/assets/menu-setting.svg
  src/components/Icon/assets/menu-storage.svg
  src/components/Icon/assets/menu-suggest.svg
Labels: size/M

#3150 fix: #8473 硬盘修改驱动的接口guestdisks应该加上scope的参数
  containers/Compute/views/disk/dialogs/DriverUpdateDialog.vue
Labels: size/XS

#3152 Automated cherry pick of #3150: fix: #8473 硬盘修改驱动的接口guestdisks应该加上scope的参数
  containers/Compute/views/disk/dialogs/DriverUpdateDialog.vue
Labels: size/XS

#3153 feat: update menu icons
  src/components/Icon/assets/menu-compute.svg
  src/components/Icon/assets/menu-dashboard.svg
  src/components/Icon/assets/menu-db.svg
  src/components/Icon/assets/menu-helm.svg
  src/components/Icon/assets/menu-iam.svg
  src/components/Icon/assets/menu-k8s.svg
  src/components/Icon/assets/menu-meter.svg
  src/components/Icon/assets/menu-middleware.svg
  src/components/Icon/assets/menu-monitor.svg
  src/components/Icon/assets/menu-multicloud.svg
  src/components/Icon/assets/menu-network.svg
  src/components/Icon/assets/menu-setting.svg
  src/components/Icon/assets/menu-storage.svg
  src/components/Icon/assets/menu-suggest.svg
Labels: size/M

#3155 fix: 勾选迁移权限后同时支持冷热迁移
  containers/IAM/views/policy/components/Form/index.vue
Labels: size/XS

#3156 Automated cherry pick of #3155: fix: 勾选迁移权限后同时支持冷热迁移
  containers/IAM/views/policy/components/Form/index.vue
Labels: size/XS

#3157 fix: host monitor query params
  containers/Compute/views/host/sidepage/Monitor.vue
Labels: size/XS

#3158 Automated cherry pick of #3157: fix: host monitor query params
  containers/Compute/views/host/sidepage/Monitor.vue
Labels: size/XS

#3162 Automated cherry pick of #3161: fix: #8476 宿主机监控调整
  containers/Compute/views/host/constants.js
  src/sections/Charts/Lines.vue
  src/sections/Monitor/index.vue
Labels: size/M

#3163 Automated cherry pick of #3161: fix: #8476 宿主机监控调整
  containers/Compute/views/host/constants.js
  src/sections/Charts/Lines.vue
  src/sections/Monitor/index.vue
Labels: size/M

#3164 fix: 标签未归集展示条件
  src/components/PageList/TagFilter.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
Labels: size/XS

#3166 feat: #3833 redis最大私网带宽优化
  containers/DB/views/redis/sidepage/Detail.vue
Labels: area/db, size/XS

#3167 Automated cherry pick of #3166: feat: #3833 redis最大私网带宽优化
  containers/DB/views/redis/sidepage/Detail.vue
Labels: size/XS

#3168 feat: #3850 云账号名称取消限制
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/BingoCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Nutanix.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/S3CephXsky.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
Labels: size/M, area/cloudenv

#3169 Automated cherry pick of #3168: feat: #3850 云账号名称取消限制
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/BingoCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Nutanix.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/S3CephXsky.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
Labels: size/M

#3170 Automated cherry pick of #3168: feat: #3850 云账号名称取消限制
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Nutanix.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/S3CephXsky.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
Labels: size/M

#3171 feat: #3850 云账号名称取消限制
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
Labels: area/cloudenv, size/XS

#3172 Automated cherry pick of #3171: feat: #3850 云账号名称取消限制
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
Labels: size/XS

#3173 fix: locale issues 20220713
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#3174 Automated cherry pick of #3173: fix: locale issues 20220713
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#3175 fix: #8350 ip正则校验更正
  src/components/SearchBox/index.vue
Labels: size/XS

#3176 Automated cherry pick of #3175: fix: #8350 ip正则校验更正
  src/components/SearchBox/index.vue
Labels: size/XS

#3177 fix: #8480 rds 监控使用内存使用率指标
  containers/DB/constants/index.js
Labels: area/db, size/S

#3178 Automated cherry pick of #3177: fix: #8480 rds 监控使用内存使用率指标
  containers/DB/constants/index.js
Labels: size/S

#3179 Automated cherry pick of #3177: fix: #8480 rds 监控使用内存使用率指标
  containers/DB/constants/index.js
Labels: size/S

#3180 feat: 导出扩展-支持本地导出, 新增 时间选择组件
  src/components/DateTime/CustomDate.vue
  src/components/DateTime/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XL

#3181 Automated cherry pick of #3180: feat: 导出扩展-支持本地导出
  src/components/DateTime/CustomDate.vue
  src/components/DateTime/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XL

#3182 feat: #3850 云账号名称校验规则
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: area/cloudenv, size/XS

#3183 Automated cherry pick of #3182: feat: #3850 云账号名称校验规则
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: size/XS

#3184 Automated cherry pick of #3182: feat: #3850 云账号名称校验规则
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: size/XS

#3185 feat: vpc classic topology support storage
  containers/Network/sections/Topology/ResCommon.vue
  containers/Network/sections/Topology/constants.js
  containers/Network/sections/Topology/index.scss
  containers/Network/views/vpc/components/ResTopology/ResShareStorage.vue
  containers/Network/views/vpc/components/ResTopology/Vpc/index.vue
Labels: size/M

#3189 fix: 列表数据为空时重置资源概览及统计信息
  src/mixins/resStatisticsMixin.js
Labels: size/S

#3188 feat: #3818 告警接收人支持指定角色
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/views/commonalert/components/alert/form/index.vue
  containers/Monitor/views/commonalert/components/alert/index.vue
  containers/Monitor/views/commonalert/sidepage/Detail.vue
  containers/Monitor/views/commonalert/utils/index.js
Labels: area/monitor

#3192 fix: #8483 物理机-存储过滤条件增加host_id
  containers/Compute/views/physicalmachine/sidepage/index.vue
Labels: area/compute, size/XS

#3193 Automated cherry pick of #3192: fix: #8483 物理机-存储过滤条件增加host_id
  containers/Compute/views/physicalmachine/sidepage/index.vue
Labels: size/XS

#3194 Automated cherry pick of #3192: fix: #8483 物理机-存储过滤条件增加host_id
  containers/Compute/views/physicalmachine/sidepage/index.vue
Labels: size/XS

#3195 fix: 权限关闭视图模式
  containers/IAM/views/policy/components/Form/index.vue
Labels: size/XS

#3196 fix: 导出优化
  src/components/DateTime/index.vue
  src/components/Icon/assets/menu-report.svg
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/M

#3197 Automated cherry pick of #3196: fix: 导出优化
  src/components/DateTime/index.vue
  src/components/Icon/assets/menu-report.svg
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/M

#3198 feat: #3849 权限支持搜索
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/policy/Create.vue
  containers/IAM/views/policy/Update.vue
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/Group.vue
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/index.vue
  containers/IAM/views/policy/components/Form/index.vue
Labels: size/M

#3199 Automated cherry pick of #3198: feat: #3849 权限支持搜索
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/policy/Create.vue
  containers/IAM/views/policy/Update.vue
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/Group.vue
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/index.vue
  containers/IAM/views/policy/components/Form/index.vue
Labels: size/M

#3200 Automated cherry pick of #3188: feat: #3818 告警接收人支持指定角色
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/views/commonalert/components/alert/form/index.vue
  containers/Monitor/views/commonalert/components/alert/index.vue
  containers/Monitor/views/commonalert/sidepage/Detail.vue
  containers/Monitor/views/commonalert/utils/index.js
Labels: size/L

#3201 feat: #3438 虚拟机详情页tab增加定时任务
  containers/Cloudenv/views/scheduledtask/components/List.vue
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/M, area/compute

#3202 feat: support vmware transfer kvm
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/dialogs/V2vTransfer.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Compute/views/vminstance/utils.js
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/L

#3203 fix: remove sm4 encryptio support
  containers/Compute/sections/encryptkeys/index.vue
Labels: size/XS

#3204 Automated cherry pick of #3203: fix: remove sm4 encryptio support
  containers/Compute/sections/encryptkeys/index.vue
Labels: size/XS

#3205 fix: #8468 开启MFA后，App下载找不到
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Auth/BindSecret.vue
Labels: size/S

#3207 Automated cherry pick of #2587: feat: 增加无权限提示框
  src/constants/permission.js
  src/sections/DialogManager/components/NoPermission.vue
Labels: size/M

#3209 Automated cherry pick of #3208: fix: 无权限登录后退出时清空当前登录信息
  src/sections/DialogManager/components/NoPermission.vue
Labels: size/XS

#3210 Automated cherry pick of #3208: fix: 无权限登录后退出时清空当前登录信息
  src/sections/DialogManager/components/NoPermission.vue
Labels: size/XS

#3211 feat: #3841 虚拟机监控暂时隐藏内存使用率
  containers/Compute/views/vminstance/constants.js
Labels: area/compute, size/XS

#3212 Automated cherry pick of #3211: feat: #3841 虚拟机监控暂时隐藏内存使用率
  containers/Compute/views/vminstance/constants.js
Labels: size/XS

#3214 feat: #3844 v2v迁移预调度处理
  containers/Compute/views/vminstance/dialogs/V2vTransfer.vue
  containers/Compute/views/vminstance/mixins/resourceProps.js
Labels: size/XS

#3215 feat: #3846 安全组关联虚拟机时，同时支持名称及IP搜索
  containers/Compute/views/secgroup/dialogs/SetServer.vue
  src/components/BaseSelect/index.vue
Labels: size/S

#3216 Automated cherry pick of #3215: feat: #3846 安全组关联虚拟机时，同时支持名称及IP搜索
  containers/Compute/views/secgroup/dialogs/SetServer.vue
  src/components/BaseSelect/index.vue
Labels: size/S

#3217 Automated cherry pick of #3215: feat: #3846 安全组关联虚拟机时，同时支持名称及IP搜索
  containers/Compute/views/secgroup/dialogs/SetServer.vue
  src/components/BaseSelect/index.vue
Labels: size/S

#3221 feat: VPC拓扑存储展示优化
  containers/Network/views/vpc/components/ResTopology/Vpc/index.vue
  src/constants/storage.js
Labels: size/M

#3222 Automated cherry pick of #3221: feat: VPC拓扑存储展示优化
  containers/Network/views/vpc/components/ResTopology/Vpc/index.vue
  src/constants/storage.js
Labels: size/M

#3218 fix: ip正则规则校验
  src/components/SearchBox/index.vue
Labels: size/XS

#3219 Automated cherry pick of #3218: fix: ip正则规则校验
  src/components/SearchBox/index.vue
Labels: size/XS

#3220 Automated cherry pick of #3218: fix: ip正则规则校验
  src/components/SearchBox/index.vue
Labels: size/XS

#3223 fix: syslog webservice locale
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#3224 Automated cherry pick of #3223: fix: syslog webservice locale
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#3225 feat: VPC拓扑共享存储宿主机展示优化
  containers/Network/views/vpc/components/ResTopology/Vpc/index.vue
Labels: size/S

#3226 Automated cherry pick of #3225: feat: VPC拓扑共享存储宿主机展示优化
  containers/Network/views/vpc/components/ResTopology/Vpc/index.vue
Labels: size/S

#3227 feat: #3680 物理机转宿主机，新建分区优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/dialogs/DiskOptionsUpdate.vue
Labels: size/XS

#3228 Automated cherry pick of #3227: feat: #3680 物理机转宿主机，新建分区优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/dialogs/DiskOptionsUpdate.vue
Labels: size/XS

#3229 Automated cherry pick of #3227: feat: #3680 物理机转宿主机，新建分区优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/dialogs/DiskOptionsUpdate.vue
Labels: size/XS

#3230 fix: 云账号新建根据功能选择校验
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
Labels: size/M, area/cloudenv

#3231 fix: license add incloudsphere
  src/constants/feature.js
Labels: size/XS

#3232 fix: 浪潮融合云license图标
  src/assets/images/providers/incloudsphere.svg
Labels: size/XS

#3233 fix: 流量镜像路由平台验证
  containers/Compute/router/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: area/compute, size/S

#3234 Automated cherry pick of #3233: fix: 流量镜像路由平台验证
  containers/Compute/router/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/S

#3235 feat: #3847 mongodb/rds详情增加展示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/mongodb/sidepage/Detail.vue
  containers/DB/views/rds/mixins/columns.js
  containers/DB/views/rds/sidepage/Detail.vue
Labels: size/M, area/compute, area/db

#3236 Automated cherry pick of #3235: feat: #3847 mongodb/rds详情增加展示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/mongodb/sidepage/Detail.vue
  containers/DB/views/rds/mixins/columns.js
  containers/DB/views/rds/sidepage/Detail.vue
Labels: size/M

#3237 fix: 补充浪潮融合云文案
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#3239 fix: 浪潮云增加翻译
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#3240 fix: 浪潮云翻译
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#3241 feat: #3861 浪潮云支持主机新建
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/utils.js
Labels: area/compute, size/XS

#3242 feat: #3846 安全组关联虚拟机
  containers/Compute/views/secgroup/dialogs/SetServer.vue
  containers/Compute/views/secgroup/mixins/serverListPropsForSetServer.js
Labels: size/M

#3243 Automated cherry pick of #3242: feat: #3846 安全组关联虚拟机
  containers/Compute/views/secgroup/dialogs/SetServer.vue
  containers/Compute/views/secgroup/mixins/serverListPropsForSetServer.js
Labels: size/M

#3244 Automated cherry pick of #3242: feat: #3846 安全组关联虚拟机
  containers/Compute/views/secgroup/dialogs/SetServer.vue
  containers/Compute/views/secgroup/mixins/serverListPropsForSetServer.js
Labels: size/M

#3245 feat: #3861 浪潮云新建虚拟机优化
  containers/Compute/sections/SecgroupConfig/index.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/utils.js
Labels: size/M, area/compute

#3246 feat: #3861 浪潮云新建虚拟机优化
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/Private.vue
Labels: area/compute, size/XS

#3247 feat: #3841 虚拟机监控暂时隐藏内存使用率
  containers/Compute/views/vminstance/constants.js
Labels: area/compute, size/S

#3248 Automated cherry pick of #3247: feat: #3841 虚拟机监控暂时隐藏内存使用率
  containers/Compute/views/vminstance/constants.js
Labels: size/S
