Repository yunionio/dashboard, pull requests merged in 2022-09, with the labels that each got.

#3394 Automated cherry pick of #3393: feature: support huasei sms service
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/notifyconfig/create/components/Mobile.vue
  containers/IAM/views/notifyconfig/create/components/smsaliyun.vue
  containers/IAM/views/notifyconfig/create/components/smshuawei.vue
  containers/IAM/views/notifyconfig/create/index.vue
  containers/IAM/views/notifyconfig/sidepage/Detail.vue
Labels: size/XL

#3396 fix: 消息通知渠道 短信参数文档地址更正
  containers/IAM/views/notifyconfig/create/components/smsaliyun.vue
  containers/IAM/views/notifyconfig/create/components/smshuawei.vue
  containers/IAM/views/notifyconfig/utils/docs.js
Labels: size/S

#3397 feat: Rds/Redis 监控参数更正
  containers/DB/constants/index.js
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds/sidepage/Monitor.vue
  containers/DB/views/redis/sidepage/Monitor.vue
Labels: area/db, size/XL

#3398 Automated cherry pick of #3397: feat: Rds/Redis 监控参数更正
  containers/DB/constants/index.js
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds/sidepage/Monitor.vue
  containers/DB/views/redis/sidepage/Monitor.vue
Labels: size/XL

#3399 feat: sku list distinct
  containers/Compute/sections/SKU/index.vue
Labels: size/XS

#3401 feat: #3899 MFA认证Android App增加从阿里云OSS下载链接
  src/components/Icon/assets/chrome.svg
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Auth/BindSecret.vue
Labels: size/M

#3402 Automated cherry pick of #3401: feat: #3899 MFA认证Android App增加从阿里云OSS下载链接
  src/components/Icon/assets/chrome.svg
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Auth/BindSecret.vue
Labels: size/M

#3403 Automated cherry pick of #3401: feat: #3899 MFA认证Android App增加从阿里云OSS下载链接
  src/components/Icon/assets/chrome.svg
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Auth/BindSecret.vue
Labels: size/M

#3405 fix: rds 监控参数报错
  containers/DB/views/rds/sidepage/Monitor.vue
  containers/DB/views/redis/sidepage/Monitor.vue
Labels: area/db, size/XS

#3406 Automated cherry pick of #3405: fix: rds 监控参数报错
  containers/DB/views/rds/sidepage/Monitor.vue
  containers/DB/views/redis/sidepage/Monitor.vue
Labels: size/XS

#3407 fix: update locale texts for resource update webhook
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#3408 Automated cherry pick of #3407: fix: update locale texts for resource update webhook
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#3409 fix: 项目详情-RDS取值错误 #14909
  containers/IAM/views/policy/constants.js
  containers/IAM/views/projects/sidepage/Detail.vue
Labels: size/XS

#3410 Automated cherry pick of #3409: fix: 项目详情-RDS取值错误 #14909
  containers/IAM/views/policy/constants.js
  containers/IAM/views/projects/sidepage/Detail.vue
Labels: size/XS

#3411 Automated cherry pick of #3409: fix: 项目详情-RDS取值错误 #14909
  containers/IAM/views/policy/constants.js
  containers/IAM/views/projects/sidepage/Detail.vue
Labels: size/XS

#3412 fix: huawei sms bugfixes
  containers/IAM/constants/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/idp/sidepage/Detail.vue
  containers/IAM/views/notifyconfig/create/components/smsaliyun.vue
  containers/IAM/views/notifyconfig/create/components/smshuawei.vue
  containers/IAM/views/notifyconfig/create/index.vue
  src/locales/zh-CN.json
Labels: size/L

#3413 Automated cherry pick of #3412: fix: huawei sms bugfixes
  containers/IAM/constants/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/idp/sidepage/Detail.vue
  containers/IAM/views/notifyconfig/create/components/smsaliyun.vue
  containers/IAM/views/notifyconfig/create/components/smshuawei.vue
  containers/IAM/views/notifyconfig/create/index.vue
  src/locales/zh-CN.json
Labels: size/L

#3414 feat: #3920 迁移UI改进
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#3416 feat: #3919 快速恢复
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/dialogs/QuickRecovery.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/L

#3417 Automated cherry pick of #3416: feat: #3919 快速恢复
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/dialogs/QuickRecovery.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/L

#3418 fix: 文档地址更正
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Dashboard/constants/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/idp/constants.js
  containers/IAM/views/mail-config/components/DingTalk.vue
  containers/IAM/views/mail-config/components/FlyBook.vue
  containers/IAM/views/mail-config/components/Workwx.vue
  containers/IAM/views/notifyconfig/create/components/Dingtalk.vue
  containers/IAM/views/notifyconfig/create/components/Feishu.vue
  containers/IAM/views/notifyconfig/create/components/Workwx.vue
  containers/IAM/views/notifyconfig/utils/docs.js
  containers/IAM/views/robots/utils/docs.js
  containers/K8S/views/cluster/constants/index.js
Labels: size/M

#3420 Automated cherry pick of #3419: feat: #3912 support qga
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/dialogs/ResetPassword.vue
  containers/Compute/views/vminstance/utils.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/docs.js
Labels: size/M

#3421 Automated cherry pick of #3418: fix: 文档地址更正
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Dashboard/constants/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/idp/constants.js
  containers/IAM/views/mail-config/components/DingTalk.vue
  containers/IAM/views/mail-config/components/FlyBook.vue
  containers/IAM/views/mail-config/components/Workwx.vue
  containers/IAM/views/notifyconfig/create/components/Dingtalk.vue
  containers/IAM/views/notifyconfig/create/components/Feishu.vue
  containers/IAM/views/notifyconfig/create/components/Workwx.vue
  containers/K8S/views/cluster/constants/index.js
Labels: size/M

#3423 Automated cherry pick of #3422: fix(compute): gpu for IDC VM creation
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/S

#3422 fix(compute): gpu for IDC VM creation
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/S

#3424 Automated cherry pick of #3422: fix(compute): gpu for IDC VM creation
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/S

#3426 Automated cherry pick of #3425: fix: #3912 修复qga问题
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/dialogs/ResetPassword.vue
Labels: size/M

#3427 fix: metadata null error
  containers/Compute/views/vminstance/dialogs/ResetPassword.vue
Labels: size/XS

#3430 fix: 文档链接更正
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/idp/constants.js
Labels: size/M

#3431 Automated cherry pick of #3430: fix: 文档链接更正
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/idp/constants.js
Labels: size/M

#3432 fix: 文档地址更正
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/idp/constants.js
  containers/Network/views/ssh-proxy/form/index.vue
Labels: size/M

#3433 Automated cherry pick of #3432: fix: 文档地址更正
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/idp/constants.js
  containers/Network/views/ssh-proxy/form/index.vue
Labels: size/M

#3435 fix: #8531 控制面板-配额磁贴权限检查
  containers/Dashboard/extends/Top5/constants.js
  containers/Dashboard/views/dashboard/components/Content.vue
  containers/Dashboard/views/edit/index.vue
Labels: area/dashboard, size/S

#3436 Automated cherry pick of #3435: fix: #8531 控制面板-配额磁贴权限检查
  containers/Dashboard/extends/Top5/constants.js
  containers/Dashboard/views/dashboard/components/Content.vue
  containers/Dashboard/views/edit/index.vue
Labels: size/S

#3437 Automated cherry pick of #3435: fix: #8531 控制面板-配额磁贴权限检查
  containers/Dashboard/extends/Top5/constants.js
  containers/Dashboard/views/dashboard/components/Content.vue
  containers/Dashboard/views/edit/index.vue
Labels: size/S

#3438 feat: #3894 云订阅支持备注搜索
  containers/Cloudenv/views/cloudprovider/components/List.vue
Labels: area/cloudenv, size/XS

#3439 Automated cherry pick of #3438: feat: #3894 云订阅支持备注搜索
  containers/Cloudenv/views/cloudprovider/components/List.vue
Labels: size/XS

#3440 Automated cherry pick of #3438: feat: #3894 云订阅支持备注搜索
  containers/Cloudenv/views/cloudprovider/components/List.vue
Labels: size/XS

#3441 fix: remove irrelevant common options
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/locales/en.json
  src/locales/zh-CN.json
  src/store/modules/common.js
Labels: size/S

#3442 Automated cherry pick of #3441: fix: remove irrelevant common options
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/locales/en.json
  src/locales/zh-CN.json
  src/store/modules/common.js
Labels: size/S

#3443 Automated cherry pick of #3434: feat: #3923 Linux主机支持新建支持安装agent
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/S

#3444 feat: 通用时间组件扩展-支持自定义时间展示格式设置
  src/components/DateTime/CustomDate.vue
  src/components/DateTime/index.vue
Labels: size/S

#3446 feat: #3870 【磁盘】支持使用资源状态来过滤磁盘
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/components/List.vue
  src/utils/common/tableFilter.js
Labels: size/S

#3447 Automated cherry pick of #3446: feat: #3870 【磁盘】支持使用资源状态来过滤磁盘
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/components/List.vue
  src/utils/common/tableFilter.js
Labels: size/S

#3449 feat: #3912 优化批量操作,只有kvm才提示信息
  containers/Compute/views/vminstance/dialogs/ResetPassword.vue
Labels: size/XS

#3450 Automated cherry pick of #3449: feat: #3912 优化批量操作,只有kvm才提示信息
  containers/Compute/views/vminstance/dialogs/ResetPassword.vue
Labels: size/XS

#3451 fix: #8525 项目标签更正请求参数
  containers/IAM/views/projects/mixins/columns.js
  containers/IAM/views/projects/sidepage/Detail.vue
  src/sections/TagDetailColumn/index.vue
  src/sections/TagTableColumn/index.vue
  src/utils/common/detailColumn.js
  src/utils/common/tableColumn.js
Labels: size/S

#3452 Automated cherry pick of #3451: fix: #8525 项目标签更正请求参数
  containers/IAM/views/projects/mixins/columns.js
  containers/IAM/views/projects/sidepage/Detail.vue
  src/sections/TagDetailColumn/index.vue
  src/sections/TagTableColumn/index.vue
  src/utils/common/detailColumn.js
  src/utils/common/tableColumn.js
Labels: size/S

#3453 Automated cherry pick of #3451: fix: #8525 项目标签更正请求参数
  containers/IAM/views/projects/mixins/columns.js
  containers/IAM/views/projects/sidepage/Detail.vue
  src/sections/TagDetailColumn/index.vue
  src/sections/TagTableColumn/index.vue
  src/utils/common/detailColumn.js
  src/utils/common/tableColumn.js
Labels: size/S

#3455 fix: #8528 新建接收人,接收人选择搜索不生效问题
  containers/IAM/views/notify-subscriber/dialogs/SetupNotifyReceiver.vue
  src/components/BaseSelect/OptionLabelPrefix.vue
  src/components/BaseSelect/index.vue
Labels: size/M

#3456 Automated cherry pick of #3455: fix: #8528 新建接收人,接收人选择搜索不生效问题
  containers/IAM/views/notify-subscriber/dialogs/SetupNotifyReceiver.vue
  src/components/BaseSelect/OptionLabelPrefix.vue
  src/components/BaseSelect/index.vue
Labels: size/M

#3457 feat: #3933 azure windows 虚拟机磁盘使用率监控增加groupBy: device
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  src/sections/Monitor/index.vue
Labels: area/compute, size/S

#3458 Automated cherry pick of #3457: feat: #3933 azure windows 虚拟机磁盘使用率监控增加groupBy: device
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  src/sections/Monitor/index.vue
Labels: size/S

#3459 feat: #3911 监控查询,增加指标中文映射
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/Filters/index.vue
  containers/Monitor/sections/Metric/index.vue
Labels: area/db, size/S

#3460 Automated cherry pick of #3459: feat: #3911 监控查询,增加指标中文映射
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/Filters/index.vue
  containers/Monitor/sections/Metric/index.vue
Labels: size/S

#3462 feat: add modelarts monitor
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/router/index.js
  containers/Compute/views/modelarts/sidepage/Monitor.vue
  containers/Compute/views/modelarts/sidepage/index.vue
  containers/Compute/views/node-alert/constants.js
  src/constants/expectStatus.js
Labels: size/L

#3463 Automated cherry pick of #3461: feat: add modelarts
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/router/index.js
  containers/Compute/views/modelarts/components/List.vue
  containers/Compute/views/modelarts/constants/index.js
  containers/Compute/views/modelarts/create/index.vue
  containers/Compute/views/modelarts/index.vue
  containers/Compute/views/modelarts/mixins/columns.js
  containers/Compute/views/modelarts/mixins/singleActions.js
  containers/Compute/views/modelarts/sidepage/Detail.vue
  containers/Compute/views/modelarts/sidepage/index.vue
  containers/Compute/views/modelarts/utils/columns.js
  src/components/Detail/index.js
  src/components/Icon/assets/res-modelarts.svg
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XL

#3465 fix: #8549 宿主机设置超售比上限问题
  containers/Compute/views/host/dialogs/AdjustOversoldRatio.vue
Labels: size/XS

#3466 Automated cherry pick of #3465: fix: #8549 宿主机设置超售比上限问题
  containers/Compute/views/host/dialogs/AdjustOversoldRatio.vue
Labels: size/XS

#3467 Automated cherry pick of #3465: fix: #8549 宿主机设置超售比上限问题
  containers/Compute/views/host/dialogs/AdjustOversoldRatio.vue
Labels: size/XS

#3468 feat: add modelarts module i18n
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/modelarts/locales/en.json
  containers/Compute/views/modelarts/locales/zh-CN.json
Labels: size/M

#3469 Automated cherry pick of #3468: feat: add modelarts module i18n
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/modelarts/locales/en.json
  containers/Compute/views/modelarts/locales/zh-CN.json
Labels: size/M

#3470 feat: modelarts add region
  containers/Compute/views/modelarts/create/index.vue
Labels: size/M

#3471 Automated cherry pick of #3470: feat: modelarts add region
  containers/Compute/views/modelarts/create/index.vue
Labels: size/M

#3474 feat: #3923 兼容agent安装提示信息
  containers/Compute/views/vminstance/components/InstallAgentFormVisible.vue
Labels: size/XS

#3475 Automated cherry pick of #3474: feat: #3923 兼容agent安装提示信息
  containers/Compute/views/vminstance/components/InstallAgentFormVisible.vue
Labels: size/XS

#3476 fix: modelarts monitor
  containers/Compute/views/modelarts/create/index.vue
  containers/Compute/views/modelarts/sidepage/Monitor.vue
Labels: size/S

#3477 Automated cherry pick of #3476: fix: modelarts monitor
  containers/Compute/views/modelarts/create/index.vue
  containers/Compute/views/modelarts/sidepage/Monitor.vue
Labels: size/S

#3480 fix: #8559 新建每天触发时且未填有效时间的定时任务时前端不应该少传参数
  containers/Cloudenv/views/cloudaccount/dialogs/ScheduledtaskCreate.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
Labels: size/M

#3481 Automated cherry pick of #3480: fix: #8559 新建每天触发时且未填有效时间的定时任务时前端不应该少传参数
  containers/Cloudenv/views/cloudaccount/dialogs/ScheduledtaskCreate.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
Labels: size/M

#3482 fix: host detail mem_commit_bound
  containers/Compute/views/host/sidepage/Detail.vue
Labels: size/XS

#3483 Automated cherry pick of #3482: fix: host detail mem_commit_bound
  containers/Compute/views/host/sidepage/Detail.vue
Labels: size/XS

#3484 Automated cherry pick of #3482: fix: host detail mem_commit_bound
  containers/Compute/views/host/sidepage/Detail.vue
Labels: size/XS

#3485 feat: #3922 kvm支持更换磁盘块存储
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/ChangeBlockStorage.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Compute/views/vminstance/mixins/storageResourceProps.js
  containers/Compute/views/vminstance/utils.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#3487 fix: host service status
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/XS

#3488 Automated cherry pick of #3487: fix: host service status
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/XS

#3490 fix: vm quick recovery
  containers/Compute/views/vminstance/dialogs/QuickRecovery.vue
Labels: size/XS

#3492 feat: #3943 云账号新建-华为去除全球区类型
  containers/Cloudenv/views/cloudaccount/constants.js
Labels: area/cloudenv, size/XS

#3493 Automated cherry pick of #3492: feat: #3943 云账号新建-华为去除全球区类型
  containers/Cloudenv/views/cloudaccount/constants.js
Labels: size/XS

#3497 fix: quick recovery forecast add is_rescue_mode
  containers/Compute/views/vminstance/dialogs/QuickRecovery.vue
Labels: size/XS

#3499 feat: update modelarts monitor
  containers/Compute/views/modelarts/sidepage/Monitor.vue
Labels: size/S

#3501 feat: add disk change block storage
  containers/Compute/views/disk/dialogs/ChangeBlockStorage.vue
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/mixins/storageResourceProps.js
Labels: size/L

#3502 Automated cherry pick of #3501: feat: add disk change block storage
  containers/Compute/views/disk/dialogs/ChangeBlockStorage.vue
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/mixins/storageResourceProps.js
Labels: size/L

#3503 fix: 配额开关全局参数更正
  src/store/modules/common.js
Labels: size/S

#3504 Automated cherry pick of #3503: fix: 配额开关全局参数更正
  src/store/modules/common.js
Labels: size/S

#3505 fix: #8569 新建云账号定时任务与设置不符合，时间固定8:00
  containers/Cloudenv/views/cloudaccount/create/form/ScheduledSettings.vue
  containers/Cloudenv/views/cloudaccount/dialogs/ScheduledtaskCreate.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
Labels: size/XS

#3506 Automated cherry pick of #3505: fix: #8569 新建云账号定时任务与设置不符合，时间固定8:00
  containers/Cloudenv/views/cloudaccount/create/form/ScheduledSettings.vue
  containers/Cloudenv/views/cloudaccount/dialogs/ScheduledtaskCreate.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
Labels: size/XS

#3507 feat: #3938 块存储增加分类：物理机、宿主机
  containers/Storage/views/blockstorage/components/List.vue
  containers/Storage/views/blockstorage/index.vue
Labels: size/M

#3508 Automated cherry pick of #3507: feat: #3938 块存储增加分类：物理机、宿主机
  containers/Storage/views/blockstorage/components/List.vue
  containers/Storage/views/blockstorage/index.vue
Labels: size/M

#3509 Automated cherry pick of #3507: feat: #3938 块存储增加分类：物理机、宿主机
  containers/Storage/views/blockstorage/components/List.vue
  containers/Storage/views/blockstorage/index.vue
Labels: size/M

#3510 feat: add server status
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#3514 Automated cherry pick of #3512: fix: #8576 虚拟机挂载ISO时前端查询filter中search.contains改为name.contains
  containers/Compute/views/vminstance/dialogs/MountIso.vue
Labels: size/XS

#3512 fix: #8576 虚拟机挂载ISO时前端查询filter中search.contains改为name.contains
  containers/Compute/views/vminstance/dialogs/MountIso.vue
Labels: size/XS

#3513 Automated cherry pick of #3512: fix: #8576 虚拟机挂载ISO时前端查询filter中search.contains改为name.contains
  containers/Compute/views/vminstance/dialogs/MountIso.vue
Labels: size/XS

#3515 feat(Compute): windows server install agent
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#3519 feat(Cloudenv/Compute): add remotefile
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/RemoteFile.vue
  containers/Compute/views/vminstance/utils.js
  src/assets/images/providers/remotefile.svg
  src/components/Icon/assets/remotefile.svg
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#3522 feat: auth login error i18n
  src/constants/error.js
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/XS

#3529 feat: add server stop status
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS
