Repository yunionio/dashboard, pull requests merged in 2022-02, with the labels that each got.

#2108 feat: #3611 set discount precision
  containers/Cloudenv/views/cloudaccount/dialogs/SetDiscount.vue
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: area/cloudenv, size/S

#2109 Automated cherry pick of #2108: feat: #3611 set discount precision
  containers/Cloudenv/views/cloudaccount/dialogs/SetDiscount.vue
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: size/S

#2110 Automated cherry pick of #2108: feat: #3611 set discount precision
  containers/Cloudenv/views/cloudaccount/dialogs/SetDiscount.vue
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: size/S

#2111 fix: #8172 add permission for instancebackup and diskbackup
  containers/Compute/router/index.js
  containers/Compute/views/disk-backup/components/List.vue
  containers/Compute/views/disk-backup/mixins/singleActions.js
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/mixins/singleActions.js
  src/constants/permission.js
Labels: size/M, area/compute

#2112 Automated cherry pick of #2111: fix: #8172 add permission for instancebackup and diskbackup
  containers/Compute/router/index.js
  containers/Compute/views/disk-backup/components/List.vue
  containers/Compute/views/disk-backup/mixins/singleActions.js
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/mixins/singleActions.js
  src/constants/permission.js
Labels: size/M

#2113 Automated cherry pick of #2111: fix: #8172 add permission for instancebackup and diskbackup
  containers/Compute/router/index.js
  containers/Compute/views/disk-backup/components/List.vue
  containers/Compute/views/disk-backup/mixins/singleActions.js
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/mixins/singleActions.js
  src/constants/permission.js
Labels: size/M

#2114 feat: #3616 add i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2115 Automated cherry pick of #2114: feat: #3616 add i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2116 Automated cherry pick of #2114: feat: #3616 add i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2117 fix: #8138 虚拟机CPU32核，调整配置时CPU选项应该自动展开
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#2118 Automated cherry pick of #2117: fix: #8138 虚拟机CPU32核，调整配置时CPU选项应该自动展开
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#2119 Automated cherry pick of #2117: fix: #8138 虚拟机CPU32核，调整配置时CPU选项应该自动展开
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#2120 fix: #8144 format scheduletask utc time
  containers/Cloudenv/views/scheduledtask/components/List.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
Labels: area/helm, size/XS

#2121 Automated cherry pick of #2120: fix: #8144 format scheduletask utc time
  containers/Cloudenv/views/scheduledtask/components/List.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
Labels: size/XS

#2122 Automated cherry pick of #2120: fix: #8144 format scheduletask utc time
  containers/Cloudenv/views/scheduledtask/components/List.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
Labels: size/XS

#2123 Feat/glb to 3.9/src
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/XS

#2124 Automated cherry pick of #2123: feat: #3609 add i18n
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/XS

#2125 feat: #3601 add project tags switch
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/components/PageList/index.vue
  src/store/modules/common.js
  src/store/modules/projectTags.js
Labels: size/S

#2126 Automated cherry pick of #2125: feat: #3601 add project tags switch
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/components/PageList/index.vue
  src/store/modules/common.js
  src/store/modules/projectTags.js
Labels: size/S

#2128 feat: modify i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2129 Automated cherry pick of #2128: feat: modify i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2130 Automated cherry pick of #2128: feat: modify i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2131 fix: #8173 打开镜像市场前端不应该报错
  src/assets/images/os-images/kylin.svg
Labels: size/XS

#2132 Automated cherry pick of #2131: fix: #8173 打开镜像市场前端不应该报错
  src/assets/images/os-images/kylin.svg
Labels: size/XS

#2133 fix: #8176 裸金属服务器没有重置按钮，应去掉
  containers/Compute/utils/hostActions.js
Labels: size/S

#2134 Automated cherry pick of #2133: fix: #8176 裸金属服务器没有重置按钮，应去掉
  containers/Compute/utils/hostActions.js
Labels: size/S

#2135 Automated cherry pick of #2133: fix: #8176 裸金属服务器没有重置按钮，应去掉
  containers/Compute/utils/hostActions.js
Labels: size/S

#2136 fix: #8136 sku action permission
  containers/Compute/views/sku/mixins/singleActions.js
Labels: area/compute, size/XS

#2138 Automated cherry pick of #2136: fix: #8136 sku action permission
  containers/Compute/views/sku/mixins/singleActions.js
Labels: size/XS

#2139 feat: #3609 modify i18n
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/XS

#2140 Automated cherry pick of #2139: feat: #3609 modify i18n
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/XS

#2141 feat: #3601 modify i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2142 Automated cherry pick of #2141: feat: #3601 modify i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2143 feat: #3615 add i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#2144 Automated cherry pick of #2143: feat: #3615 add i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#2146 Automated cherry pick of #2145: feat: #3615 add i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#2147 fix: #8177 日志列表优化
  containers/Cloudenv/views/cloudevent/components/List.vue
  src/components/PageList/components/Table.vue
  src/sections/DialogManager/components/CustomList.vue
  src/sections/EventList/index.vue
Labels: size/M

#2148 Automated cherry pick of #2147: fix: #8177 日志列表优化
  containers/Cloudenv/views/cloudevent/components/List.vue
  src/components/PageList/components/Table.vue
  src/sections/DialogManager/components/CustomList.vue
  src/sections/EventList/index.vue
Labels: size/M

#2149 Automated cherry pick of #2147: fix: #8177 日志列表优化
  containers/Cloudenv/views/cloudevent/components/List.vue
  src/components/PageList/components/Table.vue
  src/sections/DialogManager/components/CustomList.vue
  src/sections/EventList/index.vue
Labels: size/M

#2150 fix: vm instance create support discount
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  src/utils/common/price.js
Labels: area/compute, size/S

#2152 fix: eslint error
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/S

#2153 Automated cherry pick of #2152: fix: eslint error
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/S

#2154 Automated cherry pick of #2152: fix: eslint error
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/S

#2155 feat: #3577 优化虚拟机、硬盘备份恢复
  containers/Compute/views/disk-backup/mixins/singleActions.js
  containers/Compute/views/disk-backup/sidepage/Detail.vue
  containers/Compute/views/disk/dialogs/CreateBackupDialog.vue
  containers/Compute/views/instance-backup/mixins/singleActions.js
  containers/Compute/views/instance-backup/sidepage/Detail.vue
  containers/Compute/views/vminstance/dialogs/BackupCreate.vue
Labels: size/M

#2156 Automated cherry pick of #2155: feat: #3577 优化虚拟机、硬盘备份恢复
  containers/Compute/views/disk-backup/mixins/singleActions.js
  containers/Compute/views/disk-backup/sidepage/Detail.vue
  containers/Compute/views/disk/dialogs/CreateBackupDialog.vue
  containers/Compute/views/instance-backup/mixins/singleActions.js
  containers/Compute/views/instance-backup/sidepage/Detail.vue
  containers/Compute/views/vminstance/dialogs/BackupCreate.vue
Labels: size/M

#2159 Automated cherry pick of #2158: fix: close skip password check
  containers/IAM/views/user/dialogs/UpdatePassword.vue
Labels: size/XS

#2160 Automated cherry pick of #2158: fix: close skip password check
  containers/IAM/views/user/dialogs/UpdatePassword.vue
Labels: size/XS

#2161 fix: user create close skip password check
  containers/IAM/views/user/create/index.vue
Labels: size/XS

#2162 Automated cherry pick of #2161: fix: user create close skip password check
  containers/IAM/views/user/create/index.vue
Labels: size/XS

#2163 Automated cherry pick of #2161: fix: user create close skip password check
  containers/IAM/views/user/create/index.vue
Labels: size/XS

#2164 fix: vm instance create support discount
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: area/compute, size/S

#2165 Automated cherry pick of #2164: fix: vm instance create support discount
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/S

#2166 feat: #3594 虚拟机详情页网络tab合并
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Network.vue
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/M

#2167 Automated cherry pick of #2166: feat: #3594 虚拟机详情页网络tab合并
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Network.vue
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/M

#2168 Automated cherry pick of #2166: feat: #3594 虚拟机详情页网络tab合并
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Network.vue
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/M

#2169 fix: network list params
  containers/Compute/views/vminstance/sidepage/Network.vue
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/S

#2170 Automated cherry pick of #2169: fix: network list params
  containers/Compute/views/vminstance/sidepage/Network.vue
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/S

#2171 Automated cherry pick of #2169: fix: network list params
  containers/Compute/views/vminstance/sidepage/Network.vue
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/S

#2172 fix: misc fixes, vip, evip, passthrough, etc.
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/dialogs/SetHostReserveResource.vue
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/host/sidepage/Detail.vue
  containers/Compute/views/host/utils/columns.js
  containers/Compute/views/physicalmachine/sidepage/Detail.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/M

#2173 Automated cherry pick of #2172: fix: misc fixes, vip, evip, passthrough, etc.
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/dialogs/SetHostReserveResource.vue
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/host/sidepage/Detail.vue
  containers/Compute/views/host/utils/columns.js
  containers/Compute/views/physicalmachine/sidepage/Detail.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/M

#2174 Automated cherry pick of #2172: fix: misc fixes, vip, evip, passthrough, etc.
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/dialogs/SetHostReserveResource.vue
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/host/sidepage/Detail.vue
  containers/Compute/views/host/utils/columns.js
  containers/Compute/views/physicalmachine/sidepage/Detail.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/M

#2175 fix: network list action error
  containers/Compute/views/vminstance/sidepage/Network.vue
Labels: size/S

#2176 Automated cherry pick of #2175: fix: network list action error
  containers/Compute/views/vminstance/sidepage/Network.vue
Labels: size/S

#2177 Automated cherry pick of #2175: fix: network list action error
  containers/Compute/views/vminstance/sidepage/Network.vue
Labels: size/S

#2178 fix: #8192 arm架构的虚拟机传参应该是os_arch=arm
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/XS

#2179 Automated cherry pick of #2178: fix: #8192 arm架构的虚拟机传参应该是os_arch=arm
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/XS

#2181 Automated cherry pick of #2178: fix: #8192 arm架构的虚拟机传参应该是os_arch=arm
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/XS

#2180 Automated cherry pick of #2178: fix: #8192 arm架构的虚拟机传参应该是os_arch=arm
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/XS

#2182 fix: #8188 login password show
  src/sections/Auth/Login/components/LoginChallenge.vue
Labels: size/S

#2183 Automated cherry pick of #2182: fix: #8188 login password show
  src/sections/Auth/Login/components/LoginChallenge.vue
Labels: size/S

#2185 feat: #3637 用户登录后，如果user信息中 need_reset_password 为true，则强制要求用户设置密码
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/UpdateUserPassword.vue
Labels: size/S

#2186 Automated cherry pick of #2185: feat: #3637 用户登录后，如果user信息中 need_reset_password 为true，则强制要求用户设置密码
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/UpdateUserPassword.vue
Labels: size/S

#2187 Automated cherry pick of #2185: feat: #3637 用户登录后，如果user信息中 need_reset_password 为true，则强制要求用户设置密码
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/UpdateUserPassword.vue
Labels: size/S

#2188 feat: open skip password check
  containers/IAM/views/user/create/index.vue
  containers/IAM/views/user/dialogs/UpdatePassword.vue
Labels: size/XS

#2189 Automated cherry pick of #2188: feat: open skip password check
  containers/IAM/views/user/create/index.vue
  containers/IAM/views/user/dialogs/UpdatePassword.vue
Labels: size/XS

#2190 Automated cherry pick of #2188: feat: open skip password check
  containers/IAM/views/user/create/index.vue
  containers/IAM/views/user/dialogs/UpdatePassword.vue
Labels: size/XS

#2191 fix: #8187 modify i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/store/modules/common.js
Labels: size/XS

#2192 Automated cherry pick of #2191: fix: #8187 modify i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/store/modules/common.js
Labels: size/XS

#2193 fix: #8201 login password input show repeat
  src/sections/Auth/Login/components/LoginChallenge.vue
Labels: size/XS

#2194 Automated cherry pick of #2193: fix: #8201 login password input show repeat
  src/sections/Auth/Login/components/LoginChallenge.vue
Labels: size/XS

#2195 Automated cherry pick of #2193: fix: #8201 login password input show repeat
  src/sections/Auth/Login/components/LoginChallenge.vue
Labels: size/XS

#2196 fix: #8182 price show discount
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/DB/sections/ItemNetwork.vue
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/rds/create/index.vue
  containers/DB/views/redis/create/components/BottomBar.vue
  containers/DB/views/redis/create/index.vue
  containers/Network/views/eip/create/components/BottomBar.vue
  containers/Network/views/eip/create/index.vue
  containers/Network/views/nats/create/changeMinxin.js
  containers/Network/views/nats/create/components/BottomBar.vue
  containers/Network/views/nats/create/index.vue
  containers/Storage/views/file-system/create/components/BottomBar.vue
  containers/Storage/views/file-system/create/index.vue
  src/components/PriceFetcher/index.vue
  src/utils/common/price.js
Labels: area/db, size/L

#2197 Automated cherry pick of #2196: fix: #8182 price show discount
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/DB/sections/ItemNetwork.vue
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/rds/create/index.vue
  containers/DB/views/redis/create/components/BottomBar.vue
  containers/DB/views/redis/create/index.vue
  containers/Network/views/eip/create/components/BottomBar.vue
  containers/Network/views/eip/create/index.vue
  containers/Network/views/nats/create/changeMinxin.js
  containers/Network/views/nats/create/components/BottomBar.vue
  containers/Network/views/nats/create/index.vue
  containers/Storage/views/file-system/create/components/BottomBar.vue
  containers/Storage/views/file-system/create/index.vue
  src/components/PriceFetcher/index.vue
  src/utils/common/price.js
Labels: size/L

#2198 feat: #3612 nutanix menu permission for eip
  containers/Compute/router/index.js
  containers/Network/router/index.js
Labels: area/compute, size/XS

#2199 Automated cherry pick of #2198: feat: #3612 nutanix menu permission for eip
  containers/Compute/router/index.js
  containers/Network/router/index.js
Labels: size/XS

#2200 Automated cherry pick of #2198: feat: #3612 nutanix menu permission for eip
  containers/Compute/router/index.js
  containers/Network/router/index.js
Labels: size/XS

#2201 feat: instance snapshot resource add statistics
  containers/Compute/views/snapshot-instance/components/List.vue
  containers/Compute/views/snapshot-instance/index.vue
Labels: size/M

#2202 Automated cherry pick of #2201: feat: instance snapshot resource add statistics
  containers/Compute/views/snapshot-instance/components/List.vue
  containers/Compute/views/snapshot-instance/index.vue
Labels: size/M

#2203 fix: #8203 add i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#2204 Automated cherry pick of #2203: fix: #8203 add i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#2205 Automated cherry pick of #2203: fix: #8203 add i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#2207 Automated cherry pick of #2206: feat: host image resource add statistics
  containers/Compute/views/host-image/components/List.vue
  containers/Compute/views/host-image/index.vue
  src/mixins/resStatisticsMixin.js
  src/sections/ResStatusTab/index.vue
Labels: size/M

#2208 feat: image resource add statistics
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/index.vue
Labels: size/M

#2210 Automated cherry pick of #2201: feat: instance snapshot resource add statistics
  containers/Compute/views/snapshot-instance/components/List.vue
  containers/Compute/views/snapshot-instance/index.vue
Labels: size/M

#2212 Automated cherry pick of #2208: feat: image resource add statistics
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/index.vue
Labels: size/M

#2211 Automated cherry pick of #2206: feat: host image resource add statistics
  containers/Compute/views/host-image/components/List.vue
  containers/Compute/views/host-image/index.vue
  src/mixins/resStatisticsMixin.js
  src/sections/ResStatusTab/index.vue
Labels: size/M

#2216 feat: #3643 镜像增加中国方德logo
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/views/image/dialogs/EditAttributes.vue
  src/assets/images/os-images/nfs.svg
  src/components/ImageIcon/assets/nfs.png
  src/components/ImageIcon/constants.js
  src/components/ImageIcon/index.vue
Labels: size/S

#2217 Automated cherry pick of #2216: feat: #3643 镜像增加中国方德logo
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/views/image/dialogs/EditAttributes.vue
  src/assets/images/os-images/nfs.svg
  src/components/ImageIcon/assets/nfs.png
  src/components/ImageIcon/constants.js
  src/components/ImageIcon/index.vue
Labels: size/S

#2218 Automated cherry pick of #2216: feat: #3643 镜像增加中国方德logo
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/views/image/dialogs/EditAttributes.vue
  src/assets/images/os-images/nfs.svg
  src/components/ImageIcon/assets/nfs.png
  src/components/ImageIcon/constants.js
  src/components/ImageIcon/index.vue
Labels: size/M

#2219 Feat/glb to 3.9/cloudenv
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/externalproject/components/List.vue
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
Labels: size/L

#2220 Automated cherry pick of #2219: feat[3.9]: external project support batch modify
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/externalproject/components/List.vue
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
Labels: size/L

#2221 fix: #8205 三级权限关闭时，调度标签应用范围显示错误
  containers/Cloudenv/views/schedtag/mixins/columns.js
Labels: size/XS

#2222 Automated cherry pick of #2221: fix: #8205 三级权限关闭时，调度标签应用范围显示错误
  containers/Cloudenv/views/schedtag/mixins/columns.js
Labels: size/XS

#2223 Automated cherry pick of #2221: fix: #8205 三级权限关闭时，调度标签应用范围显示错误
  containers/Cloudenv/views/schedtag/mixins/columns.js
Labels: size/XS

#2224 fix: image resource add statistics
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/index.vue
Labels: size/S

#2225 Automated cherry pick of #2224: fix: image resource add statistics
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/index.vue
Labels: size/S

#2226 Automated cherry pick of #2224: fix: image resource add statistics
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/index.vue
Labels: size/S

#2228 Automated cherry pick of #2227: fix: get stats error when router beforeeach to check permission
  src/store/getters.js
Labels: size/XS

#2229 Automated cherry pick of #2227: fix: get stats error when router beforeeach to check permission
  src/store/getters.js
Labels: size/XS

#2230 fix: #8202 域下没有项目，在该域下新建云账号不应该报错
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: size/XS

#2231 Automated cherry pick of #2230: fix: #8202 域下没有项目，在该域下新建云账号不应该报错
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: size/XS

#2232 Automated cherry pick of #2230: fix: #8202 域下没有项目，在该域下新建云账号不应该报错
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: size/XS

#2233 fix: #8213 文案修改
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk-backup/dialogs/RollbackDiskBackup.vue
  containers/Compute/views/instance-backup/dialogs/RollbackInstanceBackup.vue
Labels: size/XS

#2235 Automated cherry pick of #2233: fix: #8213 文案修改
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk-backup/dialogs/RollbackDiskBackup.vue
  containers/Compute/views/instance-backup/dialogs/RollbackInstanceBackup.vue
Labels: size/XS

#2236 fix: set default tag filter
  src/sections/TagSelect/index.vue
Labels: size/XS

#2237 Automated cherry pick of #2236: fix: set default tag filter
  src/sections/TagSelect/index.vue
Labels: size/XS

#2238 Automated cherry pick of #2236: fix: set default tag filter
  src/sections/TagSelect/index.vue
Labels: size/XS

#2242 fix: add description filter
  src/utils/common/tableFilter.js
Labels: size/S

#2243 feature: role add policy set time range
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/role/components/SetPolicies.vue
  containers/IAM/views/role/sidepage/Policies.vue
  src/utils/common/tableColumn.js
Labels: size/M

#2244 Automated cherry pick of #2243: feature: role add policy set time range
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/role/components/SetPolicies.vue
  containers/IAM/views/role/sidepage/Policies.vue
  src/utils/common/tableColumn.js
Labels: size/M

#2246 feat: #3631 反亲和组关联虚拟机，搜索框支持IP或名称同时搜索
  containers/Compute/views/instance-group/dialogs/BindServer.vue
Labels: size/S

#2247 Automated cherry pick of #2246: feat: #3631 反亲和组关联虚拟机，搜索框支持IP或名称同时搜索
  containers/Compute/views/instance-group/dialogs/BindServer.vue
Labels: size/S

#2248 Automated cherry pick of #2246: feat: #3631 反亲和组关联虚拟机，搜索框支持IP或名称同时搜索
  containers/Compute/views/instance-group/dialogs/BindServer.vue
Labels: size/S

#2250 feat: #3599 拓扑图标及状态异常兼容处理
  containers/Network/sections/Topology/constants.js
Labels: size/XS

#2251 Automated cherry pick of #2250: feat: #3599 拓扑图标及状态异常兼容处理
  containers/Network/sections/Topology/constants.js
Labels: size/XS

#2252 Automated cherry pick of #2250: feat: #3599 拓扑图标及状态异常兼容处理
  containers/Network/sections/Topology/constants.js
Labels: size/XS

#2253 fix: #8220 反亲和组关联虚拟机时，输入字符时过滤条件应该用filter
  containers/Compute/views/instance-group/dialogs/BindServer.vue
Labels: size/XS

#2254 Automated cherry pick of #2253: fix: #8220 反亲和组关联虚拟机时，输入字符时过滤条件应该用filter
  containers/Compute/views/instance-group/dialogs/BindServer.vue
Labels: size/XS

#2255 Automated cherry pick of #2253: fix: #8220 反亲和组关联虚拟机时，输入字符时过滤条件应该用filter
  containers/Compute/views/instance-group/dialogs/BindServer.vue
Labels: size/XS

#2256 feat: #3647 虚拟机磁铁支持项目过滤
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/S

#2257 Automated cherry pick of #2256: feat: #3647 虚拟机磁铁支持项目过滤
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/S

#2258 fix: 修复清空下拉框选择项目报错问题
  src/sections/DomainProject/components/Domain.vue
  src/sections/DomainProject/components/Project.vue
Labels: size/XS

#2261 Automated cherry pick of #2258: fix: 修复清空下拉框选择项目报错问题
  src/sections/DomainProject/components/Domain.vue
  src/sections/DomainProject/components/Project.vue
Labels: size/XS

#2260 Automated cherry pick of #2258: fix: 修复清空下拉框选择项目报错问题
  src/sections/DomainProject/components/Domain.vue
  src/sections/DomainProject/components/Project.vue
Labels: size/XS

#2262 feat: #3658 add policy create checkbox
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/Group.vue
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/Item.vue
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/index.vue
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/constants.js
  containers/IAM/views/policy/utils.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#2263 Automated cherry pick of #2262: feat: #3658 add policy create checkbox
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/Group.vue
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/Item.vue
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/index.vue
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/constants.js
  containers/IAM/views/policy/utils.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#2264 Automated cherry pick of #2262: feat: #3658 add policy create checkbox
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/Group.vue
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/Item.vue
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/index.vue
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/constants.js
  containers/IAM/views/policy/utils.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#2265 fix: modify i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2266 Automated cherry pick of #2265: fix: modify i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2267 Automated cherry pick of #2265: fix: modify i18n
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2268 fix: modify i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/policy/utils.js
Labels: size/XS

#2269 Automated cherry pick of #2268: fix: modify i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/policy/utils.js
Labels: size/XS

#2270 Automated cherry pick of #2268: fix: modify i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/policy/utils.js
Labels: size/S

#2274 feat: #3652 迁移时，跳过CPU检查增加不检查内核版本
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#2275 Automated cherry pick of #2274: feat: #3652 迁移时，跳过CPU检查增加不检查内核版本
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#2276 fix: policy create error
  containers/IAM/views/policy/components/Form/index.vue
Labels: size/XS

#2277 feat: #3630 新建主机--选择网络优化
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
Labels: size/XS

#2278 Automated cherry pick of #2277: feat: #3630 新建主机--选择网络优化
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
Labels: size/XS

#2279 Automated cherry pick of #2277: feat: #3630 新建主机--选择网络优化
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
Labels: size/XS

#2280 fix: support aws rds
  containers/DB/sections/ItemArea.vue
  containers/DB/views/rds/create/index.vue
Labels: size/XS
