Repository yunionio/dashboard, pull requests merged in 2022-03, with the labels that each got.

#2308 Fix/glb to 3.9/iam
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/IAM/views/role/components/SetPolicies.vue
  containers/IAM/views/role/sidepage/Policies.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/M

#2309 Automated cherry pick of #2308: feat: #3667 policy effect time format to minute
  containers/IAM/views/role/components/SetPolicies.vue
  containers/IAM/views/role/sidepage/Policies.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/S

#2310 feat: add unpack
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/dialogs/UnpackDialog.vue
  containers/Compute/views/instance-backup/mixins/singleActions.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#2312 feat: update unpack
  containers/Compute/views/instance-backup/dialogs/UnpackDialog.vue
Labels: size/XS

#2313 Automated cherry pick of #2312: feat: update unpack
  containers/Compute/views/instance-backup/dialogs/UnpackDialog.vue
Labels: size/XS

#2314 feat: add import unpack
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/dialogs/ImportUnpackDialog.vue
  containers/Compute/views/instance-backup/dialogs/UnpackDialog.vue
Labels: size/L

#2315 Automated cherry pick of #2314: feat: add import unpack
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/dialogs/ImportUnpackDialog.vue
  containers/Compute/views/instance-backup/dialogs/UnpackDialog.vue
Labels: size/L

#2316 fix: password i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#2317 Automated cherry pick of #2316: fix: password i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#2318 fix: import unpack params
  containers/Compute/views/instance-backup/dialogs/ImportUnpackDialog.vue
Labels: size/XS

#2320 fix: regx cause safari error
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: area/compute, size/XS

#2323 fix: import unpack interface
  containers/Compute/views/instance-backup/dialogs/ImportUnpackDialog.vue
Labels: size/XS

#2326 Automated cherry pick of #2325: fix: #3585 主机新建，调度标签优化
  containers/Compute/utils/createServer.js
Labels: size/XS

#2328 fix: #8234 虚拟机添加网卡样式不应该错乱
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/sections/ServerNetwork/index.vue
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: size/S

#2329 Automated cherry pick of #2328: fix: #8234 虚拟机添加网卡样式不应该错乱
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/sections/ServerNetwork/index.vue
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: size/S

#2330 Automated cherry pick of #2328: fix: #8234 虚拟机添加网卡样式不应该错乱
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/sections/ServerNetwork/index.vue
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: size/S

#2331 fix: #8236 域、项目、组等详情页修改名称规则不统一
  containers/IAM/views/domains/sidepage/Detail.vue
  containers/IAM/views/group/sidepage/Detail.vue
  containers/IAM/views/projects/sidepage/Detail.vue
Labels: size/S

#2332 Automated cherry pick of #2331: fix: #8236 域、项目、组等详情页修改名称规则不统一
  containers/IAM/views/domains/sidepage/Detail.vue
  containers/IAM/views/group/sidepage/Detail.vue
  containers/IAM/views/projects/sidepage/Detail.vue
Labels: size/S

#2333 Automated cherry pick of #2331: fix: #8236 域、项目、组等详情页修改名称规则不统一
  containers/IAM/views/domains/sidepage/Detail.vue
  containers/IAM/views/group/sidepage/Detail.vue
  containers/IAM/views/projects/sidepage/Detail.vue
Labels: size/S

#2334 Fix/glb to 3.9/cloudenv
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Compute/router/index.js
  containers/Compute/utils/webconsole.js
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/DB/router/index.js
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#2335 Automated cherry pick of #2334: feat: 云上项目增加本地项目和订阅过滤
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Compute/router/index.js
  containers/Compute/utils/webconsole.js
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/DB/router/index.js
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#2336 Automated cherry pick of #2334: feat: 云上项目增加本地项目和订阅过滤
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Compute/router/index.js
  containers/Compute/utils/webconsole.js
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/DB/router/index.js
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#2338 Automated cherry pick of #2337: fix: global search error
  src/components/SearchBox/index.vue
Labels: size/XS

#2337 fix: global search error
  src/components/SearchBox/index.vue
Labels: size/XS

#2339 Automated cherry pick of #2337: fix: global search error
  src/components/SearchBox/index.vue
Labels: size/XS

#2340 Automated cherry pick of #2295: feat: #3614 迁移优化
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/mixins/resourceProps.js
Labels: size/L

#2341 Automated cherry pick of #2295: feat: #3614 迁移优化
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/mixins/resourceProps.js
Labels: size/L

#2342 fix: remove statistics refresh
  src/mixins/resStatisticsMixin.js
Labels: size/XS

#2344 Automated cherry pick of #2342: fix: remove statistics refresh
  src/mixins/resStatisticsMixin.js
Labels: size/XS

#2345 fix: #8250 虚拟机添加网卡，IP子网列表展示不正确
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: size/XS

#2346 Automated cherry pick of #2345: fix: #8250 虚拟机添加网卡，IP子网列表展示不正确
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: size/XS

#2347 Automated cherry pick of #2345: fix: #8250 虚拟机添加网卡，IP子网列表展示不正确
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: size/XS

#2348 fix: #8249 新建公有云IP子网时获取zone的接口应该加上排序的参数
  containers/Network/views/network/Create.vue
Labels: size/XS

#2349 Automated cherry pick of #2348: fix: #8249 新建公有云IP子网时获取zone的接口应该加上排序的参数
  containers/Network/views/network/Create.vue
Labels: size/XS

#2353 fix: transfer filter
  containers/Compute/views/vminstance/mixins/resourceProps.js
Labels: size/XS

#2354 Automated cherry pick of #2353: fix: transfer filter
  containers/Compute/views/vminstance/mixins/resourceProps.js
Labels: size/XS

#2355 Automated cherry pick of #2353: fix: transfer filter
  containers/Compute/views/vminstance/mixins/resourceProps.js
Labels: size/XS

#2350 fix: #8231 修改密码加密
  src/sections/DialogManager/components/UpdateUserPassword.vue
Labels: size/XS

#2351 Automated cherry pick of #2350: fix: #8231 修改密码加密
  src/sections/DialogManager/components/UpdateUserPassword.vue
Labels: size/XS

#2352 Automated cherry pick of #2350: fix: #8231 修改密码加密
  src/sections/DialogManager/components/UpdateUserPassword.vue
Labels: size/XS

#2356 fix: 修正云上项目的订阅过滤条件
  containers/Cloudenv/views/externalproject/components/List.vue
Labels: area/cloudenv, size/XS

#2357 Automated cherry pick of #2356: fix: 修正云上项目的订阅过滤条件
  containers/Cloudenv/views/externalproject/components/List.vue
Labels: size/XS

#2358 Automated cherry pick of #2274: feat: #3652 迁移时，跳过CPU检查增加不检查内核版本
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#2359 fix: 绑定物理cpu增加权限校验
  containers/Compute/views/vminstance/mixins/singleActions.js
  src/constants/permission.js
Labels: area/compute, size/XS

#2360 Automated cherry pick of #2359: fix: 绑定物理cpu增加权限校验
  containers/Compute/views/vminstance/mixins/singleActions.js
  src/constants/permission.js
Labels: size/XS

#2362 feat: #3676 云账号新建展示为选择的云平台
  containers/Cloudenv/router/index.js
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
Labels: size/M

#2363 Automated cherry pick of #2362: feat: #3676 云账号新建展示为选择的云平台
  containers/Cloudenv/router/index.js
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
Labels: size/M

#2367 feat: #3678 新建虚拟机设置网卡支持同时设置mac地址
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/sections/ServerNetwork/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
Labels: size/M

#2368 Automated cherry pick of #2367: feat: #3678 新建虚拟机设置网卡支持同时设置mac地址
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/sections/ServerNetwork/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
Labels: size/M

#2364 feat: 增加全局开关翻译字段
  containers/Compute/utils/createServer.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/store/getters.js
Labels: size/S

#2365 Automated cherry pick of #2364: feat: 增加全局开关翻译字段
  containers/Compute/utils/createServer.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/store/getters.js
Labels: size/S

#2366 fix: #8144 云账号同步定时任务时区问题
  containers/Cloudenv/views/cloudaccount/dialogs/ScheduledtaskCreate.vue
  containers/Cloudenv/views/cloudaccount/sidepage/Schedule.vue
  containers/Compute/views/scaling-group/dialogs/RuleListCreate.vue
  containers/Compute/views/scaling-group/sidepage/RuleList.vue
Labels: size/S

#2369 Automated cherry pick of #2366: fix: #8144 云账号同步定时任务时区问题
  containers/Cloudenv/views/cloudaccount/dialogs/ScheduledtaskCreate.vue
  containers/Cloudenv/views/cloudaccount/sidepage/Schedule.vue
  containers/Compute/views/scaling-group/dialogs/RuleListCreate.vue
  containers/Compute/views/scaling-group/sidepage/RuleList.vue
Labels: size/S

#2370 Automated cherry pick of #2366: fix: #8144 云账号同步定时任务时区问题
  containers/Cloudenv/views/scheduledtask/components/List.vue
  containers/Compute/views/scaling-group/dialogs/RuleListCreate.vue
  containers/Compute/views/scaling-group/sidepage/RuleList.vue
Labels: size/S

#2371 Automated cherry pick of #2296: fix: #8228 全局搜索切换路由后清空搜索条件
  src/sections/Navbar/components/GlobalSearch.vue
Labels: size/XS

#2372 Automated cherry pick of #2296: fix: #8228 全局搜索切换路由后清空搜索条件
  src/sections/Navbar/components/GlobalSearch.vue
Labels: size/XS

#2373 fix: #8258 全局搜索RDS和Redis没有过滤
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
Labels: size/S

#2374 Automated cherry pick of #2373: fix: #8258 全局搜索RDS和Redis没有过滤
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
Labels: size/S

#2375 Automated cherry pick of #2373: fix: #8258 全局搜索RDS和Redis没有过滤
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
Labels: size/S

#2376 fix: 定时任务描述采用api信息
  containers/Cloudenv/views/cloudaccount/sidepage/Schedule.vue
Labels: area/cloudenv, size/S

#2377 Automated cherry pick of #2376: fix: 定时任务描述采用api信息
  containers/Cloudenv/views/cloudaccount/sidepage/Schedule.vue
Labels: size/S

#2378 feat: #3681 宿主机-资源统计展示调整
  containers/Compute/views/host/sidepage/Dashboard.vue
  src/sections/CommonDashboard/index.vue
Labels: area/compute, size/S

#2379 Automated cherry pick of #2378: feat: #3681 宿主机-资源统计展示调整
  containers/Compute/views/host/sidepage/Dashboard.vue
  src/sections/CommonDashboard/index.vue
Labels: size/S

#2380 feat[3.9]: #3684 主机快照新建和回滚操作同时支持内存快照
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/snapshot-instance/components/List.vue
  containers/Compute/views/snapshot-instance/dialogs/RollbackHostDialog.vue
  containers/Compute/views/snapshot-instance/mixins/columns.js
  containers/Compute/views/vminstance/dialogs/SnapshotCreate.vue
Labels: size/M, area/compute

#2381 Automated cherry pick of #2380: feat[3.9]: #3684 主机快照新建和回滚操作同时支持内存快照
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/snapshot-instance/components/List.vue
  containers/Compute/views/snapshot-instance/dialogs/RollbackHostDialog.vue
  containers/Compute/views/snapshot-instance/mixins/columns.js
  containers/Compute/views/vminstance/dialogs/SnapshotCreate.vue
Labels: size/M

#2382 feat: #3688 迁移选择宿主机框优化
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/mixins/resourceProps.js
  src/components/SearchBox/index.vue
Labels: size/M

#2383 Automated cherry pick of #2382: feat: #3688 迁移选择宿主机框优化
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/mixins/resourceProps.js
  src/components/SearchBox/index.vue
Labels: size/M

#2384 Automated cherry pick of #2382: feat: #3688 迁移选择宿主机框优化
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/mixins/resourceProps.js
  src/components/SearchBox/index.vue
Labels: size/M

#2385 feat: #3606 批量迁移优化-提示同宿主机情况
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/S

#2386 Automated cherry pick of #2385: feat: #3606 批量迁移优化-提示同宿主机情况
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/S

#2387 Automated cherry pick of #2385: feat: #3606 批量迁移优化-提示同宿主机情况
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/S

#2388 fix: #8247 主机备份失败的虚拟机无法删除，应可以强制删除记录
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/mixins/singleActions.js
Labels: size/S

#2389 Automated cherry pick of #2388: fix: #8247 主机备份失败的虚拟机无法删除，应可以强制删除记录
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/mixins/singleActions.js
Labels: size/S

#2390 fix: instance backup delete alert i18n
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/mixins/singleActions.js
Labels: size/XS

#2392 fix: #8256 列表下拉过滤框修改时也支持搜索
  src/components/SearchBox/Tag.vue
Labels: size/S

#2393 Automated cherry pick of #2392: fix: #8256 列表下拉过滤框修改时也支持搜索
  src/components/SearchBox/Tag.vue
Labels: size/S

#2395 fix: nfs mirror fill error
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
Labels: size/XS

#2396 Automated cherry pick of #2395: fix: nfs mirror fill error
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
Labels: size/XS

#2399 Automated cherry pick of #2397: fix: transfer search ip
  src/components/SearchBox/index.vue
Labels: size/XS

#2397 fix: transfer search ip
  src/components/SearchBox/index.vue
Labels: size/XS

#2398 Automated cherry pick of #2397: fix: transfer search ip
  src/components/SearchBox/index.vue
Labels: size/XS

#2403 fix: transfer dialog host tips
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#2404 Automated cherry pick of #2403: fix: transfer dialog host tips
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#2405 Automated cherry pick of #2403: fix: transfer dialog host tips
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#2400 fix: #8227 近30天告警趋势磁贴展示修复
  containers/Dashboard/extends/AlertsTrend/index.vue
Labels: area/dashboard, size/S

#2401 Automated cherry pick of #2400: fix: #8227 近30天告警趋势磁贴展示修复
  containers/Dashboard/extends/AlertsTrend/index.vue
Labels: size/S

#2402 Automated cherry pick of #2400: fix: #8227 近30天告警趋势磁贴展示修复
  containers/Dashboard/extends/AlertsTrend/index.vue
Labels: size/S

#2406 fix: rds detail name edit
  containers/DB/views/rds-account/sidepage/Detail.vue
  containers/DB/views/rds-database/sidepage/Detail.vue
Labels: size/XS

#2407 Automated cherry pick of #2406: fix: rds detail name edit
  containers/DB/views/rds-account/sidepage/Detail.vue
  containers/DB/views/rds-database/sidepage/Detail.vue
Labels: size/XS

#2408 Automated cherry pick of #2406: fix: rds detail name edit
  containers/DB/views/rds-account/sidepage/Detail.vue
  containers/DB/views/rds-database/sidepage/Detail.vue
Labels: size/XS

#2411 feat: #3641 新建云账号，项目列表增加刷新按钮
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
Labels: size/S

#2412 Automated cherry pick of #2411: feat: #3641 新建云账号，项目列表增加刷新按钮
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
Labels: size/S

#2413 Automated cherry pick of #2411: feat: #3641 新建云账号，项目列表增加刷新按钮
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
Labels: size/S

#2409 fix: 弹框内表格展示优化
  src/components/DialogTable/index.vue
Labels: size/XS

#2410 Automated cherry pick of #2409: fix: 弹框内表格展示优化
  src/components/DialogTable/index.vue
Labels: size/XS

#2414 fix: #8216 云上项目导出参数优化
  containers/Cloudenv/views/externalproject/components/List.vue
Labels: area/cloudenv, size/XS

#2415 Automated cherry pick of #2414: fix: #8216 云上项目导出参数优化
  containers/Cloudenv/views/externalproject/components/List.vue
Labels: size/XS

#2416 feat: #8267 主机名提示太长
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/S

#2417 Automated cherry pick of #2416: feat: #8267 主机名提示太长
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/S

#2418 feat: #3681 宿主机-资源统计展示优化
  containers/Compute/views/host/sidepage/Dashboard.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M, area/compute

#2419 Automated cherry pick of #2418: feat: #3681 宿主机-资源统计展示优化
  containers/Compute/views/host/sidepage/Dashboard.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#2420 fix: #8215 数字图/使用率磁贴增加默认指标
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/Ring/components/mixin.js
  containers/Dashboard/extends/Ring/index.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/M, area/dashboard

#2421 Automated cherry pick of #2420: fix: #8215 数字图/使用率磁贴增加默认指标
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/Ring/components/mixin.js
  containers/Dashboard/extends/Ring/index.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/M

#2422 Automated cherry pick of #2420: fix: #8215 数字图/使用率磁贴增加默认指标
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/Ring/components/mixin.js
  containers/Dashboard/extends/Ring/index.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/M

#2423 fix: #8265 腾讯云rds账号新建,主机ip限制为单个
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds-account/dialogs/Create.vue
  containers/DB/views/rds-account/dialogs/UpdatePrivilege.vue
Labels: area/db, size/S

#2424 Automated cherry pick of #2423: fix: #8265 腾讯云rds账号新建,主机ip限制为单个
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds-account/dialogs/Create.vue
  containers/DB/views/rds-account/dialogs/UpdatePrivilege.vue
Labels: size/S

#2425 Automated cherry pick of #2423: fix: #8265 腾讯云rds账号新建,主机ip限制为单个
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds-account/dialogs/Create.vue
  containers/DB/views/rds-account/dialogs/UpdatePrivilege.vue
Labels: size/S

#2426 feat: 扩展base-select组件,增加下拉框选项换行
  scope/locales/zh-CN.json
  src/components/BaseSelect/index.vue
Labels: size/S

#2427 Automated cherry pick of #2426: feat: 扩展base-select组件,增加下拉框选项换行
  scope/locales/zh-CN.json
  src/components/BaseSelect/index.vue
Labels: size/S

#2428 Automated cherry pick of #2426: feat: 扩展base-select组件,增加下拉框选项换行
  scope/locales/zh-CN.json
  src/components/BaseSelect/index.vue
Labels: size/S

#2429 feat: #3691 add backupstorage
  containers/Storage/router/index.js
  containers/Storage/views/backup-storage/components/List.vue
  containers/Storage/views/backup-storage/dialogs/BackupStorageCreate.vue
  containers/Storage/views/backup-storage/index.vue
  containers/Storage/views/backup-storage/mixins/columns.js
  containers/Storage/views/backup-storage/mixins/singleActions.js
  containers/Storage/views/backup-storage/sidepage/Detail.vue
  containers/Storage/views/backup-storage/sidepage/index.vue
  containers/Storage/views/backup-storage/utils/columns.js
  src/components/Icon/assets/res-backup-storage.svg
  src/components/Icon/index.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XL

#2430 Automated cherry pick of #2429: feat: #3691 add backupstorage
  containers/Storage/router/index.js
  containers/Storage/views/backup-storage/components/List.vue
  containers/Storage/views/backup-storage/dialogs/BackupStorageCreate.vue
  containers/Storage/views/backup-storage/index.vue
  containers/Storage/views/backup-storage/mixins/columns.js
  containers/Storage/views/backup-storage/mixins/singleActions.js
  containers/Storage/views/backup-storage/sidepage/Detail.vue
  containers/Storage/views/backup-storage/sidepage/index.vue
  containers/Storage/views/backup-storage/utils/columns.js
  src/components/Icon/assets/res-backup-storage.svg
  src/components/Icon/index.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XL

#2431 fix: set image properties of uefi_support, vdi_protocol
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/BIOS/index.vue
  containers/Compute/views/image/dialogs/EditAttributes.vue
  containers/Compute/views/image/sidepage/Detail.vue
Labels: size/M

#2432 Automated cherry pick of #2431: fix: set image properties of uefi_support, vdi_protocol
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/BIOS/index.vue
  containers/Compute/views/image/dialogs/EditAttributes.vue
  containers/Compute/views/image/sidepage/Detail.vue
Labels: size/M

#2433 fix: fail to update lb listener when lbredirect=off
  containers/Network/views/loadbalancerbackendgroup/mixins/singleActions.js
  containers/Network/views/loadbalancerlistener/dialogs/Form.vue
  containers/Network/views/loadbalancerlistener/mixins/singleActions.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#2434 Automated cherry pick of #2433: fix: fail to update lb listener when lbredirect=off
  containers/Network/views/loadbalancerbackendgroup/mixins/singleActions.js
  containers/Network/views/loadbalancerlistener/dialogs/Form.vue
  containers/Network/views/loadbalancerlistener/mixins/singleActions.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#2435 Automated cherry pick of #2433: fix: fail to update lb listener when lbredirect=off
  containers/Network/views/loadbalancerbackendgroup/mixins/singleActions.js
  containers/Network/views/loadbalancerlistener/dialogs/Form.vue
  containers/Network/views/loadbalancerlistener/mixins/singleActions.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#2436 Automated cherry pick of #2433: fix: fail to update lb listener when lbredirect=off
  containers/Network/views/loadbalancerlistener/dialogs/Form.vue
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#2437 fix: #8280 区域切换,cpu未被默认选中
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: area/compute, size/XS

#2438 Automated cherry pick of #2437: fix: #8280 区域切换,cpu未被默认选中
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#2439 Automated cherry pick of #2437: fix: #8280 区域切换,cpu未被默认选中
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#2440 fix: save ticky_session configure fail
  containers/Network/views/loadbalancerlistener/dialogs/Form.vue
Labels: size/XS

#2441 Automated cherry pick of #2440: fix: save ticky_session configure fail
  containers/Network/views/loadbalancerlistener/dialogs/Form.vue
Labels: size/XS

#2443 Automated cherry pick of #2440: fix: save ticky_session configure fail
  containers/Network/views/loadbalancerlistener/dialogs/Form.vue
Labels: size/XS

#2442 Automated cherry pick of #2440: fix: save ticky_session configure fail
  containers/Network/views/loadbalancerlistener/dialogs/Form.vue
Labels: size/XS

#2444 feat: #3545 aws rds support create
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/sections/ItemNetwork.vue
  containers/DB/views/rds/constants/index.js
  containers/DB/views/rds/create/changeMinxin.js
  containers/DB/views/rds/create/components/SKU/components/List.vue
  containers/DB/views/rds/create/components/SKU/components/SizeFilters.vue
  containers/DB/views/rds/create/components/SKU/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M, area/db

#2445 Automated cherry pick of #2444: feat: #3545 aws rds support create
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/sections/ItemNetwork.vue
  containers/DB/views/rds/constants/index.js
  containers/DB/views/rds/create/changeMinxin.js
  containers/DB/views/rds/create/components/SKU/components/List.vue
  containers/DB/views/rds/create/components/SKU/components/SizeFilters.vue
  containers/DB/views/rds/create/components/SKU/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#2446 feat: #3654 数据盘支持选择存储
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/utils/createServer.js
Labels: size/S

#2447 Automated cherry pick of #2446: feat: #3654 数据盘支持选择存储
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/utils/createServer.js
Labels: size/S

#2448 Automated cherry pick of #2446: feat: #3654 数据盘支持选择存储
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/utils/createServer.js
Labels: size/S

#2449 fix: data disk storage
  containers/Compute/sections/DataDisk/index.vue
Labels: size/XS

#2452 feat: #3691 备份存储优化
  containers/Compute/views/vminstance/dialogs/BackupCreate.vue
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/backup-storage/dialogs/BackupStorageCreate.vue
  containers/Storage/views/backup-storage/sidepage/Detail.vue
  containers/Storage/views/backup-storage/utils/columns.js
Labels: size/M

#2453 Automated cherry pick of #2452: feat: #3691 备份存储优化
  containers/Compute/views/vminstance/dialogs/BackupCreate.vue
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/backup-storage/dialogs/BackupStorageCreate.vue
  containers/Storage/views/backup-storage/sidepage/Detail.vue
  containers/Storage/views/backup-storage/utils/columns.js
Labels: size/M

#2454 feat: #3691 隐藏备份存储的容量信息，接口默认传0
  containers/Storage/views/backup-storage/dialogs/BackupStorageCreate.vue
Labels: size/XS

#2455 Automated cherry pick of #2454: feat: #3691 隐藏备份存储的容量信息，接口默认传0
  containers/Storage/views/backup-storage/dialogs/BackupStorageCreate.vue
Labels: size/XS

#2456 feat: #3691 隐藏备份存储列表及详情的容量信息
  containers/Storage/views/backup-storage/mixins/columns.js
  containers/Storage/views/backup-storage/sidepage/Detail.vue
Labels: size/XS

#2457 Automated cherry pick of #2456: feat: #3691 隐藏备份存储列表及详情的容量信息
  containers/Storage/views/backup-storage/mixins/columns.js
  containers/Storage/views/backup-storage/sidepage/Detail.vue
Labels: size/XS

#2460 fix: 云账号新建限制
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
Labels: size/M

#2461 Automated cherry pick of #2460: fix: 云账号新建限制
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
Labels: size/M

#2462 feat: 字典增加调度标签
  containers/Cloudenv/locales/zh-CN.json
  containers/Compute/constants/index.js
  containers/Compute/locales/zh-CN.json
  containers/Compute/router/index.js
  containers/Compute/sections/SchedPolicy/index.vue
  containers/Compute/sections/ServerNetwork/index.vue
  containers/IAM/locales/zh-CN.json
  containers/Network/locales/zh-CN.json
  containers/Storage/locales/zh-CN.json
  src/constants/index.js
  src/locales/zh-CN.json
Labels: size/M, area/compute

#2463 Automated cherry pick of #2462: feat: 字典增加调度标签
  containers/Cloudenv/locales/zh-CN.json
  containers/Compute/constants/index.js
  containers/Compute/locales/zh-CN.json
  containers/Compute/router/index.js
  containers/Compute/sections/SchedPolicy/index.vue
  containers/Compute/sections/ServerNetwork/index.vue
  containers/IAM/locales/zh-CN.json
  containers/Network/locales/zh-CN.json
  containers/Storage/locales/zh-CN.json
  src/constants/index.js
  src/locales/zh-CN.json
Labels: size/M

#2464 Automated cherry pick of #2462: feat: 字典增加调度标签
  containers/Cloudenv/locales/zh-CN.json
  containers/Compute/constants/index.js
  containers/Compute/locales/zh-CN.json
  containers/Compute/router/index.js
  containers/Compute/sections/SchedPolicy/index.vue
  containers/Compute/sections/ServerNetwork/index.vue
  containers/IAM/locales/zh-CN.json
  containers/Network/locales/zh-CN.json
  containers/Storage/locales/zh-CN.json
  src/constants/index.js
  src/locales/zh-CN.json
Labels: size/M

#2466 fix: license add bingocloud
  src/constants/feature.js
Labels: size/XS

#2465 feat: 权限支持中文名称
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/mixins/columns.js
  containers/IAM/views/policy/sidepage/Detail.vue
Labels: size/S

#2467 Automated cherry pick of #2465: feat: 权限支持中文名称
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/mixins/columns.js
  containers/IAM/views/policy/sidepage/Detail.vue
Labels: size/S

#2468 Automated cherry pick of #2465: feat: 权限支持中文名称
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/mixins/columns.js
  containers/IAM/views/policy/sidepage/Detail.vue
Labels: size/S

#2469 fix: add bingocloud.svg
  scope/assets/bingocloud.svg
  src/assets/images/providers/bingocloud.svg
Labels: size/XS

#2470 fix: add license bingocloud i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#2471 fix: #8247 主机备份失败的虚拟机无法删除，应可以强制删除记录
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/mixins/singleActions.js
Labels: area/compute, size/XS

#2472 Automated cherry pick of #2471: fix: #8247 主机备份失败的虚拟机无法删除，应可以强制删除记录
  containers/Compute/views/instance-backup/components/List.vue
  containers/Compute/views/instance-backup/mixins/singleActions.js
Labels: size/XS
