Repository yunionio/dashboard, pull requests merged in 2022-06, with the labels that each got.

#2937 feat: #3767 拉取账单时间选择由月改为日期
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
Labels: size/M, area/cloudenv

#2938 Automated cherry pick of #2937: feat: #3767 拉取账单时间选择由月改为日期
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
Labels: size/M

#2940 feat: #3784 增加翻译
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2941 Automated cherry pick of #2940: feat: #3784 增加翻译
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2943 feat: 组件扩展
  src/components/ListBodyCellWrap/index.vue
Labels: size/XS

#2944 Automated cherry pick of #2943: feat: 组件扩展
  src/components/ListBodyCellWrap/index.vue
Labels: size/XS

#2945 feat: 支持图标扫描文件夹下的子文件中的图标
  src/components/Icon/index.js
Labels: size/XS

#2947 feat: #3783 短信页面的进入控制台统一都改成 登录阿里云控制台
  containers/IAM/locales/zh-CN.json
Labels: size/S

#2948 Automated cherry pick of #2947: feat: #3783 短信页面的进入控制台统一都改成 登录阿里云控制台
  containers/IAM/locales/zh-CN.json
Labels: size/S

#2949 Automated cherry pick of #2947: feat: #3783 短信页面的进入控制台统一都改成 登录阿里云控制台
  containers/IAM/locales/zh-CN.json
Labels: size/S

#2950 feat: #3807 监控增加指标 磁盘使用率，cpu使用率(agent)
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Monitor/components/MonitorCard/OverviewCard/metrics.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: area/dashboard, size/S

#2951 Automated cherry pick of #2950: feat: #3807 监控增加指标 磁盘使用率，cpu使用率(agent)
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Monitor/components/MonitorCard/OverviewCard/metrics.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: size/S

#2952 feat: #3808 设置代理文案修改
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
Labels: area/cloudenv, size/XS

#2953 Automated cherry pick of #2952: feat: #3808 设置代理文案修改
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
Labels: size/XS

#2954 Automated cherry pick of #2952: feat: #3808 设置代理文案修改
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
Labels: size/XS

#2955 fix: #8440 eip 飞天支持带宽展示
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/sidepage/Detail.vue
Labels: area/network, size/XS

#2956 Automated cherry pick of #2955: fix: #8440 eip 飞天支持带宽展示
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/sidepage/Detail.vue
Labels: size/XS

#2957 Automated cherry pick of #2955: fix: #8440 eip 飞天支持带宽展示
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/sidepage/Detail.vue
Labels: size/XS

#2958 feat: #3809 rds增加ip搜索
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/mixins/columns.js
Labels: area/db, size/S

#2959 Automated cherry pick of #2958: feat: #3809 rds增加ip搜索
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/mixins/columns.js
Labels: size/S

#2962 feat: 调整菜单样式
  src/components/Icon/assets/change-password.svg
  src/components/Icon/assets/close.svg
  src/components/Icon/assets/language.svg
  src/components/Icon/assets/open.svg
  src/components/SearchBox/index.vue
  src/layouts/Sidebar/Menu.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Navbar/index.vue
  src/sections/ProductsList/Sub.vue
  src/styles/less/theme.less
  src/utils/theme/utils.js
Labels: size/L

#2963 Automated cherry pick of #2962: feat: 调整菜单样式
  src/components/Icon/assets/change-password.svg
  src/components/Icon/assets/close.svg
  src/components/Icon/assets/language.svg
  src/components/Icon/assets/open.svg
  src/components/SearchBox/index.vue
  src/layouts/Sidebar/Menu.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Navbar/index.vue
  src/sections/ProductsList/Sub.vue
  src/styles/less/theme.less
  src/utils/theme/utils.js
Labels: size/L

#2964 feat: update logo style
  src/sections/Navbar/index.vue
Labels: size/XS

#2969 Automated cherry pick of #2968: feat: 更新菜单样式
  src/layouts/Sidebar/Drawer.vue
  src/sections/ProductsList/Sub.vue
Labels: size/S

#2966 feat: #3798 云账号拉取账单优化
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/sidepage/BillSync.vue
  containers/Cloudenv/views/cloudaccount/sidepage/ResSync.vue
  containers/Cloudenv/views/cloudaccount/sidepage/Schedule.vue
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/cloudenv, size/XL

#2970 fix: 控制面板计费服务条件报错
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsOverview/index.vue
Labels: size/XS

#2971 Automated cherry pick of #2970: fix: 控制面板计费服务条件报错
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsOverview/index.vue
Labels: size/XS

#2974 feat: 更新控制面板样式
  containers/Dashboard/extends/AccountHealth/index.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsOverview/index.vue
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/sections/QuotaConfig/index.vue
  src/components/PageList/components/Header.vue
  src/constants/index.js
Labels: size/M

#2975 Automated cherry pick of #2974: feat: 更新控制面板样式
  containers/Dashboard/extends/AccountHealth/index.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsOverview/index.vue
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/sections/QuotaConfig/index.vue
  src/components/PageList/components/Header.vue
  src/constants/index.js
Labels: size/M

#2972 feat: #3741 云账号-订阅-区域 增加同步资源变化详情
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudproviderregion/dialogs/SyncResourceInfo.vue
  containers/Cloudenv/views/cloudproviderregion/mixins/singleActions.js
Labels: size/M, area/cloudenv

#2973 Automated cherry pick of #2972: feat: #3741 云账号-订阅-区域 增加同步资源变化详情
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudproviderregion/dialogs/SyncResourceInfo.vue
  containers/Cloudenv/views/cloudproviderregion/mixins/singleActions.js
Labels: size/M

#2976 feat: 标签扩展 支持同一个key多选
  src/sections/Tag/index.vue
  src/utils/common/tag.js
Labels: size/M

#2977 Automated cherry pick of #2976: feat: 标签扩展 支持同一个key多选
  src/sections/Tag/index.vue
  src/utils/common/tag.js
Labels: size/M

#2978 feat: 调整控制面板样式
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/extends/Ring/components/K8s.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/UserInfo/index.vue
  containers/Dashboard/styles/index.less
  containers/Dashboard/views/dashboard/components/Content.vue
  containers/Dashboard/views/dashboard/components/Header.vue
  src/constants/index.js
  src/sections/Navbar/index.vue
Labels: size/M

#2980 feat: #3757 eip绑定资源提示优化
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
Labels: area/network, size/XS

#2981 Automated cherry pick of #2980: feat: #3757 eip绑定资源提示优化
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
Labels: size/XS

#2982 Automated cherry pick of #2980: feat: #3757 eip绑定资源提示优化
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
Labels: size/XS

#2984 feat: 更新拓扑图样式
  containers/Network/sections/Topology/index.scss
  containers/Network/views/vpc/components/ResTopology/ResIpsubnet.vue
  containers/Network/views/vpc/components/ResTopology/ResWire.vue
  containers/Network/views/wire/components/ResTopology/ResIpsubnet.vue
Labels: size/M

#2985 Automated cherry pick of #2984: feat: 更新拓扑图样式
  containers/Network/sections/Topology/index.scss
  containers/Network/views/vpc/components/ResTopology/ResIpsubnet.vue
  containers/Network/views/vpc/components/ResTopology/ResWire.vue
  containers/Network/views/wire/components/ResTopology/ResIpsubnet.vue
Labels: size/M

#2986 feat: 调整Ring组件配色
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/M

#2987 Automated cherry pick of #2986: feat: 调整Ring组件配色
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/M

#2988 feat: 调整控制面板指标样式
  containers/Dashboard/extends/NumberCard/components/Server.vue
Labels: size/XS

#2990 feat: #3803 主机重装系统增加mfa验证
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: area/compute, size/S

#2991 Automated cherry pick of #2990: feat: #3803 主机重装系统增加mfa验证
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/S

#2992 Automated cherry pick of #2990: feat: #3803 主机重装系统增加mfa验证
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/S

#2996 fix: delete temp icon file
  src/components/Icon/assets/._dashboard-alert-sum.svg
  src/components/Icon/assets/._dashboard-alerts-trend.svg
  src/components/Icon/assets/._dashboard-cloud-account-health.svg
  src/components/Icon/assets/._dashboard-consmption-trend.svg
  src/components/Icon/assets/._dashboard-consumption-percent.svg
  src/components/Icon/assets/._dashboard-log.svg
  src/components/Icon/assets/._dashboard-notice.svg
  src/components/Icon/assets/._dashboard-number.svg
  src/components/Icon/assets/._dashboard-suggest-detail.svg
  src/components/Icon/assets/._dashboard-suggest-overview.svg
  src/components/Icon/assets/._dashboard-top5.svg
  src/components/Icon/assets/._dashboard-usage.svg
  src/components/Icon/assets/._dashboard-user-info.svg
  src/components/Icon/assets/._dashboard-vmhistory-count-trend.svg
Labels: size/XS

#2999 feat: 更新系统图标
  src/components/Icon/assets/auth/password.svg
  src/components/Icon/assets/auth/safety-certificate.svg
  src/components/Icon/assets/auth/user-delete.svg
  src/components/Icon/assets/auth/user.svg
  src/components/Icon/assets/change-password.svg
  src/components/Icon/assets/close.svg
  src/components/Icon/assets/daping.svg
  src/components/Icon/assets/dashboard-fee.svg
  src/components/Icon/assets/dashboard-resource.svg
  src/components/Icon/assets/dashboard-trend.svg
  src/components/Icon/assets/dollar.svg
  src/components/Icon/assets/menu-compute.svg
  src/components/Icon/assets/menu-dashboard.svg
  src/components/Icon/assets/menu-db.svg
  src/components/Icon/assets/menu-helm.svg
  src/components/Icon/assets/menu-iam.svg
  src/components/Icon/assets/menu-k8s.svg
  src/components/Icon/assets/menu-meter.svg
  src/components/Icon/assets/menu-middleware.svg
  src/components/Icon/assets/menu-monitor.svg
  src/components/Icon/assets/menu-multicloud.svg
  src/components/Icon/assets/menu-network.svg
  src/components/Icon/assets/menu-setting.svg
  src/components/Icon/assets/menu-storage.svg
  src/components/Icon/assets/menu-suggest.svg
  src/components/Icon/assets/navbar-more.svg
  src/components/Icon/assets/navbar-notify.svg
  src/components/Icon/assets/navbar-process.svg
  src/components/Icon/assets/navbar-setting.svg
  src/components/Icon/assets/navbar-view-switch.svg
  src/components/Icon/assets/open.svg
  src/components/Icon/assets/res-smaluser.svg
  src/components/Icon/assets/res-user2.svg
  src/components/Icon/assets/search.svg
  src/components/Icon/assets/setting.svg
  src/components/Icon/assets/theme-setting.svg
  src/components/Icon/assets/zizhanghao.svg
Labels: size/L

#3005 fix: 正则验证调整
  src/utils/validate.js
Labels: size/XS

#3006 Automated cherry pick of #3005: fix: 正则验证调整
  src/utils/validate.js
Labels: size/XS

#3007 fix: #8441 修改VNC连接禁用文案提示信息
  containers/Compute/views/vminstance/utils.js
Labels: size/XS

#3008 Automated cherry pick of #3007: fix: #8441 修改VNC连接禁用文案提示信息
  containers/Compute/views/vminstance/utils.js
Labels: size/XS

#3009 Automated cherry pick of #3007: fix: #8441 修改VNC连接禁用文案提示信息
  containers/Compute/views/vminstance/utils.js
Labels: size/XS

#3012 Feat/glb to 3.9/tap
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/router/index.js
  containers/Compute/views/tap-service/components/List.vue
  containers/Compute/views/tap-service/create/index.vue
  containers/Compute/views/tap-service/dialogs/TapFlowCreate.vue
  containers/Compute/views/tap-service/index.vue
  containers/Compute/views/tap-service/mixins/columns.js
  containers/Compute/views/tap-service/mixins/singleActions.js
  containers/Compute/views/tap-service/sidepage/Detail.vue
  containers/Compute/views/tap-service/sidepage/TapFlow.vue
  containers/Compute/views/tap-service/sidepage/index.vue
  src/locales/zh-CN.json
Labels: area/compute, size/XXL

#3013 Automated cherry pick of #3012: feat: 流量镜像
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/router/index.js
  containers/Compute/views/tap-service/components/List.vue
  containers/Compute/views/tap-service/create/index.vue
  containers/Compute/views/tap-service/dialogs/TapFlowCreate.vue
  containers/Compute/views/tap-service/index.vue
  containers/Compute/views/tap-service/mixins/columns.js
  containers/Compute/views/tap-service/mixins/singleActions.js
  containers/Compute/views/tap-service/sidepage/Detail.vue
  containers/Compute/views/tap-service/sidepage/TapFlow.vue
  containers/Compute/views/tap-service/sidepage/index.vue
  src/locales/zh-CN.json
Labels: size/XXL

#3017 Automated cherry pick of #3016: feat: #3825 私有云虚拟机网卡多队列支持
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/networks/mixins/columns.js
  containers/Compute/views/networks/mixins/singleActions.js
  containers/Compute/views/vminstance/dialogs/VmUpdateNetworkAttr.vue
Labels: size/L

#3018 Automated cherry pick of #3016: feat: #3825 私有云虚拟机网卡多队列支持
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/networks/mixins/columns.js
  containers/Compute/views/networks/mixins/singleActions.js
  containers/Compute/views/vminstance/dialogs/VmUpdateNetworkAttr.vue
Labels: size/L

#3019 feat: 补全系统图标
  src/components/Icon/assets/arrow-right.svg
  src/components/Icon/assets/bill-resource.svg
  src/components/Icon/assets/bingocloud.svg
  src/components/Icon/assets/code.svg
  src/components/Icon/assets/copy.svg
  src/components/Icon/assets/data-empty.svg
  src/components/Icon/assets/delete.svg
  src/components/Icon/assets/dimension.svg
  src/components/Icon/assets/ecloud.svg
  src/components/Icon/assets/excel.svg
  src/components/Icon/assets/hcso.svg
  src/components/Icon/assets/help.svg
  src/components/Icon/assets/jdcloud.svg
  src/components/Icon/assets/mongodb.svg
  src/components/Icon/assets/nutanix.svg
  src/components/Icon/assets/passthrough.svg
  src/components/Icon/assets/password.svg
  src/components/Icon/assets/pdf.svg
  src/components/Icon/assets/projectmapping.svg
  src/components/Icon/assets/pull-down.svg
  src/components/Icon/assets/res-access-group.svg
  src/components/Icon/assets/res-brand.svg
  src/components/Icon/assets/res-broadcast.svg
  src/components/Icon/assets/res-cdn-domain.svg
  src/components/Icon/assets/res-disk-backup.svg
  src/components/Icon/assets/res-elasticsearch.svg
  src/components/Icon/assets/res-file-system.svg
  src/components/Icon/assets/res-instance-backup.svg
  src/components/Icon/assets/res-ip.svg
  src/components/Icon/assets/res-ipv6-gateway.svg
  src/components/Icon/assets/res-kafka.svg
  src/components/Icon/assets/res-month.svg
  src/components/Icon/assets/res-mount-target.svg
  src/components/Icon/assets/res-networkinterfaces.svg
  src/components/Icon/assets/res-resourcetype.svg
  src/components/Icon/assets/res-route-table.svg
  src/components/Icon/assets/res-topic.svg
  src/components/Icon/assets/res-vpc-network.svg
  src/components/Icon/assets/res-vpc-peer-connect.svg
  src/components/Icon/assets/res-webapp.svg
  src/components/Icon/assets/up.svg
  src/components/Icon/assets/user-del.svg
  src/components/Icon/assets/user.svg
  src/components/Icon/assets/waf.svg
Labels: size/M

#3020 Automated cherry pick of #3019: feat: 补全系统图标
  src/components/Icon/assets/arrow-right.svg
  src/components/Icon/assets/bill-resource.svg
  src/components/Icon/assets/bingocloud.svg
  src/components/Icon/assets/code.svg
  src/components/Icon/assets/copy.svg
  src/components/Icon/assets/data-empty.svg
  src/components/Icon/assets/delete.svg
  src/components/Icon/assets/dimension.svg
  src/components/Icon/assets/ecloud.svg
  src/components/Icon/assets/excel.svg
  src/components/Icon/assets/hcso.svg
  src/components/Icon/assets/help.svg
  src/components/Icon/assets/jdcloud.svg
  src/components/Icon/assets/mongodb.svg
  src/components/Icon/assets/nutanix.svg
  src/components/Icon/assets/passthrough.svg
  src/components/Icon/assets/password.svg
  src/components/Icon/assets/pdf.svg
  src/components/Icon/assets/projectmapping.svg
  src/components/Icon/assets/pull-down.svg
  src/components/Icon/assets/res-access-group.svg
  src/components/Icon/assets/res-brand.svg
  src/components/Icon/assets/res-broadcast.svg
  src/components/Icon/assets/res-cdn-domain.svg
  src/components/Icon/assets/res-disk-backup.svg
  src/components/Icon/assets/res-elasticsearch.svg
  src/components/Icon/assets/res-file-system.svg
  src/components/Icon/assets/res-instance-backup.svg
  src/components/Icon/assets/res-ip.svg
  src/components/Icon/assets/res-ipv6-gateway.svg
  src/components/Icon/assets/res-kafka.svg
  src/components/Icon/assets/res-month.svg
  src/components/Icon/assets/res-mount-target.svg
  src/components/Icon/assets/res-networkinterfaces.svg
  src/components/Icon/assets/res-resourcetype.svg
  src/components/Icon/assets/res-route-table.svg
  src/components/Icon/assets/res-topic.svg
  src/components/Icon/assets/res-vpc-network.svg
  src/components/Icon/assets/res-vpc-peer-connect.svg
  src/components/Icon/assets/res-webapp.svg
  src/components/Icon/assets/up.svg
  src/components/Icon/assets/user-del.svg
  src/components/Icon/assets/user.svg
  src/components/Icon/assets/waf.svg
Labels: size/M

#3021 Feat/glb to 3.9/tap
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/tap-service/components/List.vue
  containers/Compute/views/tap-service/create/index.vue
  containers/Compute/views/tap-service/dialogs/TapFlowCreate.vue
  containers/Compute/views/tap-service/mixins/columns.js
  containers/Compute/views/tap-service/sidepage/Detail.vue
  containers/Compute/views/tap-service/sidepage/TapFlow.vue
  src/constants/permission.js
  src/locales/zh-CN.json
Labels: size/L

#3023 feat: #3822 给资源统计加一个刷新按钮（云账号，可用区，区域等）
  containers/Cloudenv/sections/UsageSidepage/index.vue
  src/sections/CommonDashboard/index.vue
Labels: size/M

#3024 Automated cherry pick of #3023: feat: #3822 给资源统计加一个刷新按钮（云账号，可用区，区域等）
  containers/Cloudenv/sections/UsageSidepage/index.vue
  src/sections/CommonDashboard/index.vue
Labels: size/M

#3026 Feat/glb to 3.9/tap
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/tap-service/dialogs/TapFlowCreate.vue
  containers/Compute/views/tap-service/mixins/singleActions.js
  containers/Compute/views/tap-service/sidepage/TapFlow.vue
  containers/Compute/views/tap-service/sidepage/index.vue
  src/components/Icon/assets/res-tapservice.svg
Labels: size/M, area/compute

#3027 Automated cherry pick of #3026: feat: 流量镜像优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/tap-service/dialogs/TapFlowCreate.vue
  containers/Compute/views/tap-service/mixins/singleActions.js
  containers/Compute/views/tap-service/sidepage/TapFlow.vue
  containers/Compute/views/tap-service/sidepage/index.vue
  src/components/Icon/assets/res-tapservice.svg
Labels: size/M

#3030 Automated cherry pick of #3028: feat: 更新多网卡队列增加条件限制
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/networks/mixins/singleActions.js
  containers/Compute/views/vminstance/dialogs/VmUpdateNetworkAttr.vue
Labels: size/S

#3032 Automated cherry pick of #3031: fix: i18n
  containers/Compute/views/vminstance/dialogs/VmUpdateNetworkAttr.vue
Labels: size/XS

#3036 feat: #3827 流量镜像优化
  containers/Compute/views/tap-service/dialogs/TapFlowCreate.vue
  containers/Compute/views/tap-service/sidepage/Detail.vue
  containers/Compute/views/tap-service/sidepage/TapFlow.vue
Labels: size/M, area/compute

#3037 Automated cherry pick of #3036: feat: #3827 流量镜像优化
  containers/Compute/views/tap-service/dialogs/TapFlowCreate.vue
  containers/Compute/views/tap-service/sidepage/Detail.vue
  containers/Compute/views/tap-service/sidepage/TapFlow.vue
Labels: size/M

#3038 fix: 调整监控数据参数
  src/utils/monitor.js
Labels: size/S

#3040 Automated cherry pick of #3038: fix: 调整监控数据参数
  src/utils/monitor.js
Labels: size/S

#3041 feat: 控制面板磁贴部分个性化处理
  containers/Dashboard/extends/AccountHealth/index.vue
  containers/Dashboard/extends/AlertsTrend/index.vue
  containers/Dashboard/extends/BillHistoryLine/index.vue
  containers/Dashboard/extends/ConsumptionPercent/components/Brand.vue
  containers/Dashboard/extends/ConsumptionPercent/components/Resource.vue
  containers/Dashboard/extends/ConsumptionPercent/components/mixin.js
  containers/Dashboard/extends/ConsumptionPercent/index.vue
  containers/Dashboard/extends/ConsumptionTrend/index.vue
  containers/Dashboard/extends/Log/index.vue
  containers/Dashboard/extends/Notify/index.vue
  containers/Dashboard/extends/NumberCard/components/K8s.vue
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/extends/NumberCard/components/mixin.js
  containers/Dashboard/extends/NumberCard/index.vue
  containers/Dashboard/extends/ProjectQuota/components/Common.vue
  containers/Dashboard/extends/ProjectQuota/components/Image.vue
  containers/Dashboard/extends/ProjectQuota/components/Region.vue
  containers/Dashboard/extends/ProjectQuota/components/mixin.js
  containers/Dashboard/extends/ProjectQuota/index.vue
  containers/Dashboard/extends/Quota/index.vue
  containers/Dashboard/extends/ResourceHistoryLine/index.vue
  containers/Dashboard/extends/Ring/components/K8s.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/Ring/components/mixin.js
  containers/Dashboard/extends/Ring/index.vue
  containers/Dashboard/extends/ServerNumberDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsOverview/index.vue
  containers/Dashboard/extends/Top5/constants.js
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/extends/UnrecoveredAlarm/index.vue
  containers/Dashboard/extends/UserInfo/index.vue
  containers/Dashboard/extends/VmHistoryCount/index.vue
  containers/Dashboard/extends/index.js
  containers/Dashboard/sections/ExtendGallery/config.js
  containers/Dashboard/sections/ExtendGallery/index.vue
  containers/Dashboard/views/dashboard/components/Content.vue
  containers/Dashboard/views/edit/index.vue
Labels: size/XXL

#3042 feat: 流量镜像优化
  containers/Compute/views/tap-service/create/index.vue
  containers/Compute/views/tap-service/dialogs/TapFlowCreate.vue
Labels: size/M, area/compute

#3043 Automated cherry pick of #3042: feat: 流量镜像优化
  containers/Compute/views/tap-service/create/index.vue
  containers/Compute/views/tap-service/dialogs/TapFlowCreate.vue
Labels: size/M

#3049 feat(k8s): select image for kvm node
  containers/K8S/sections/serverConfig/index.vue
  containers/K8S/views/cluster/create/index.vue
Labels: size/M

#3050 Automated cherry pick of #3049: feat(k8s): select image for kvm node
  containers/K8S/sections/serverConfig/index.vue
  containers/K8S/views/cluster/create/index.vue
Labels: size/M

#3051 fix: missing instance group text in ip list
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/sidepage/IPList.vue
Labels: size/XS

#3052 Automated cherry pick of #3051: fix: missing instance group text in ip list
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/sidepage/IPList.vue
Labels: size/XS

#3053 Automated cherry pick of #3051: fix: missing instance group text in ip list
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/sidepage/IPList.vue
Labels: size/XS

#3054 feat: 资源统计接口数据结构调整
  src/mixins/resStatisticsMixin.js
Labels: size/XS

#3055 Automated cherry pick of #3054: feat: 资源统计接口数据结构调整
  src/mixins/resStatisticsMixin.js
Labels: size/XS

#3056 feat: #3788 ipv6网关增加阿里云平台展示
  containers/Network/router/index.js
Labels: area/network, size/XS

#3057 Automated cherry pick of #3056: feat: #3788 ipv6网关增加阿里云平台展示
  containers/Network/router/index.js
Labels: size/XS

#3058 feat: #3817 虚拟机列表返回当前列表的CPU、内存和存储量
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/index.vue
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/mixins/resStatisticsMixin.js
Labels: size/M

#3059 Automated cherry pick of #3058: feat: #3817 虚拟机列表返回当前列表的CPU、内存和存储量
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/index.vue
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/mixins/resStatisticsMixin.js
Labels: size/M

#3061 feat: #3811 主机快照增加ui策略隐藏逻辑
  containers/Compute/views/vminstance/sidepage/Snapshot.vue
Labels: area/compute, size/S

#3062 Automated cherry pick of #3061: feat: #3811 主机快照增加ui策略隐藏逻辑
  containers/Compute/views/vminstance/sidepage/Snapshot.vue
Labels: size/S

#3064 feat: #3817 虚拟机列表返回当前列表的CPU、内存和存储量
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/index.vue
  src/mixins/list.js
  src/mixins/resStatisticsMixin.js
  src/sections/ResStatusTab/index.vue
Labels: size/M

#3065 Automated cherry pick of #3064: feat: #3817 虚拟机列表返回当前列表的CPU、内存和存储量
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/index.vue
  src/mixins/list.js
  src/mixins/resStatisticsMixin.js
  src/sections/ResStatusTab/index.vue
Labels: size/M

#3068 feat: #3817 资源状态统计支持过滤
  containers/Compute/views/baremetal/index.vue
  containers/Compute/views/disk/index.vue
  containers/Compute/views/host-image/index.vue
  containers/Compute/views/host/index.vue
  containers/Compute/views/image/index.vue
  containers/Compute/views/physicalmachine/index.vue
  containers/Compute/views/snapshot-instance/index.vue
  containers/Compute/views/snapshot/index.vue
  containers/Compute/views/vminstance/index.vue
  containers/DB/views/mongodb/index.vue
  containers/DB/views/rds/index.vue
  containers/DB/views/redis/index.vue
  containers/Network/views/cdn/index.vue
  containers/Network/views/eip/index.vue
  containers/Network/views/network/index.vue
  containers/Network/views/vpc/index.vue
  containers/Network/views/wire/index.vue
  src/mixins/resStatisticsMixin.js
Labels: size/L

#3066 fix: #8450 云账号-定时任务增加缓存
  containers/Cloudenv/views/cloudaccount/sidepage/Schedule.vue
Labels: area/cloudenv, size/S

#3067 Automated cherry pick of #3066: fix: #8450 云账号-定时任务增加缓存
  containers/Cloudenv/views/cloudaccount/sidepage/Schedule.vue
Labels: size/S

#3070 feat: #3823 增加资源 表格存储
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/router/index.js
  containers/Storage/views/tablestore/components/List.vue
  containers/Storage/views/tablestore/index.vue
  containers/Storage/views/tablestore/mixins/columns.js
  containers/Storage/views/tablestore/mixins/singleActions.js
  containers/Storage/views/tablestore/sidepage/Detail.vue
  containers/Storage/views/tablestore/sidepage/index.vue
  src/components/Icon/assets/res-tablestore.svg
  src/constants/expectStatus.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/storage, size/L

#3073 feat: #3832 表格存储详情展示
  containers/Storage/views/tablestore/components/List.vue
  containers/Storage/views/tablestore/sidepage/Detail.vue
  containers/Storage/views/tablestore/sidepage/index.vue
Labels: area/storage, size/S

#3075 Automated cherry pick of #3073: feat: #3832 表格存储详情展示
  containers/Storage/views/tablestore/components/List.vue
  containers/Storage/views/tablestore/sidepage/Detail.vue
  containers/Storage/views/tablestore/sidepage/index.vue
Labels: size/S

#3063 监控信息组件拓展,列表增加字段,表格更加fixed模式
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Dashboard/constants/index.js
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/DashboardCards/index.vue
  containers/Monitor/components/MonitorCard/layout/index.vue
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
  src/components/Icon/assets/icon_add.svg
  src/components/Icon/assets/icon_after_shutdown.svg
  src/components/Icon/assets/icon_ascent.svg
  src/components/Icon/assets/icon_baremetal.svg
  src/components/Icon/assets/icon_cloudsell.svg
  src/components/Icon/assets/icon_cpu.svg
  src/components/Icon/assets/icon_decline.svg
  src/components/Icon/assets/icon_dropdown.svg
  src/components/Icon/assets/icon_menu.svg
  src/components/Icon/assets/icon_monitor.svg
  src/components/Icon/assets/icon_monitor_vnc.svg
  src/components/Icon/assets/icon_more.svg
  src/components/Icon/assets/icon_next.svg
  src/components/Icon/assets/icon_notice.svg
  src/components/Icon/assets/icon_off.svg
  src/components/Icon/assets/icon_open.svg
  src/components/Icon/assets/icon_optimization.svg
  src/components/Icon/assets/icon_ram.svg
  src/components/Icon/assets/icon_reboot.svg
  src/components/Icon/assets/icon_remote.svg
  src/components/Icon/assets/icon_running.svg
  src/components/Icon/assets/icon_search.svg
  src/components/Icon/assets/icon_shuttingdown.svg
  src/components/Icon/assets/icon_stop.svg
  src/components/Icon/assets/icon_tenant.svg
  src/components/Icon/assets/icon_vnc.svg
  src/components/IconPicker/index.vue
  src/components/PageList/Actions/index.vue
  src/components/PageList/components/Table_fixed.vue
  src/components/PageList/index.vue
  src/constants/generalUsage.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/XXL

#3077 Automated cherry pick of #3063 upstream release 3.9
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Dashboard/constants/index.js
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/DashboardCards/index.vue
  containers/Monitor/components/MonitorCard/layout/index.vue
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
  src/components/Icon/assets/icon_add.svg
  src/components/Icon/assets/icon_after_shutdown.svg
  src/components/Icon/assets/icon_ascent.svg
  src/components/Icon/assets/icon_baremetal.svg
  src/components/Icon/assets/icon_cloudsell.svg
  src/components/Icon/assets/icon_cpu.svg
  src/components/Icon/assets/icon_decline.svg
  src/components/Icon/assets/icon_dropdown.svg
  src/components/Icon/assets/icon_menu.svg
  src/components/Icon/assets/icon_monitor.svg
  src/components/Icon/assets/icon_monitor_vnc.svg
  src/components/Icon/assets/icon_more.svg
  src/components/Icon/assets/icon_next.svg
  src/components/Icon/assets/icon_notice.svg
  src/components/Icon/assets/icon_off.svg
  src/components/Icon/assets/icon_open.svg
  src/components/Icon/assets/icon_optimization.svg
  src/components/Icon/assets/icon_ram.svg
  src/components/Icon/assets/icon_reboot.svg
  src/components/Icon/assets/icon_remote.svg
  src/components/Icon/assets/icon_running.svg
  src/components/Icon/assets/icon_search.svg
  src/components/Icon/assets/icon_shuttingdown.svg
  src/components/Icon/assets/icon_stop.svg
  src/components/Icon/assets/icon_tenant.svg
  src/components/Icon/assets/icon_vnc.svg
  src/components/IconPicker/index.vue
  src/components/PageList/Actions/index.vue
  src/components/PageList/components/Table_fixed.vue
  src/components/PageList/index.vue
  src/constants/generalUsage.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/XXL

#3078 fix: #8457 通过api新建的虚拟机开机状态下调整配置，套餐列表不应该显示加载中
  containers/Compute/sections/SKU/index.vue
Labels: size/XS

#3081 fix: #8457 通过api新建的虚拟机开机状态下调整配置，套餐列表不应该显示加载中
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#3082 Automated cherry pick of #3081: fix: #8457 通过api新建的虚拟机开机状态下调整配置，套餐列表不应该显示加载中
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#3083 Automated cherry pick of #3081: fix: #8457 通过api新建的虚拟机开机状态下调整配置，套餐列表不应该显示加载中
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#3084 feat: #3817 优化虚拟机列表返回当前列表的CPU、内存和存储量
  src/components/PageList/components/Table_fixed.vue
  src/mixins/resStatisticsMixin.js
Labels: size/M

#3085 Automated cherry pick of #3084: feat: #3817 优化虚拟机列表返回当前列表的CPU、内存和存储量
  src/components/PageList/components/Table_fixed.vue
  src/mixins/resStatisticsMixin.js
Labels: size/M

#3086 fix: table fixed error
  containers/Compute/views/vminstance/components/List.vue
  src/components/PageList/components/Table_fixed.vue
  src/components/PageList/index.vue
  src/utils/common/tableColumn.js
Labels: size/S

#3091 Automated cherry pick of #3090: fix: #8426 虚拟机新建vpc修改对eip配置显隐问题
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Storage/views/tablestore/sidepage/index.vue
Labels: size/XS

#3092 feat: #3829 license申请跳转路径问题
  src/sections/DialogManager/components/UpdateLicense.vue
Labels: size/XS

#3093 Automated cherry pick of #3092: feat: #3829 license申请跳转路径问题
  src/sections/DialogManager/components/UpdateLicense.vue
Labels: size/XS

#3094 Automated cherry pick of #3092: feat: #3829 license申请跳转路径问题
  src/sections/DialogManager/components/UpdateLicense.vue
Labels: size/XS

#3097 fix(monitor): no data in response
  src/utils/monitor.js
Labels: area/monitor, size/XS

#3098 Automated cherry pick of #3097: fix(monitor): no data in response
  src/utils/monitor.js
Labels: size/XS

#3099 Automated cherry pick of #3097: fix(monitor): no data in response
  src/utils/monitor.js
Labels: size/XS

#3100 feat: #3831 去除列表页底部白条
  containers/Cloudenv/views/cloudaccount/create/BillFileIndex.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
  containers/Compute/views/physicalmachine/add/index.vue
  containers/Compute/views/scaling-group/create/index.vue
  containers/Compute/views/tap-service/create/index.vue
  containers/DB/views/redis/create/index.vue
  containers/Helm/views/chart/create/index.vue
  containers/Helm/views/k8s-release/update/index.vue
  containers/IAM/views/domains/create/index.vue
  containers/IAM/views/notifyconfig/create/index.vue
  containers/IAM/views/projects/create/index.vue
  containers/IAM/views/user/create/index.vue
  containers/K8S/views/configmap/create/index.vue
  containers/K8S/views/cronjob/create/index.vue
  containers/K8S/views/daemonset/create/index.vue
  containers/K8S/views/deployment/create/index.vue
  containers/K8S/views/federatedclusterrole/create/index.vue
  containers/K8S/views/federatedclusterrolebinding/create/index.vue
  containers/K8S/views/federatedrole/create/index.vue
  containers/K8S/views/federatedrolebinding/create/index.vue
  containers/K8S/views/ingress/create/index.vue
  containers/K8S/views/job/create/index.vue
  containers/K8S/views/persistentvolumeclaim/create/index.vue
  containers/K8S/views/pod/create/index.vue
  containers/K8S/views/rbacclusterrole/create/index.vue
  containers/K8S/views/rbacclusterrolebinding/create/index.vue
  containers/K8S/views/rbacrole/create/index.vue
  containers/K8S/views/rbacrolebinding/create/index.vue
  containers/K8S/views/secret/create/index.vue
  containers/K8S/views/service/create/index.vue
  containers/K8S/views/statefulset/create/index.vue
  containers/Monitor/views/commonalert/create/index.vue
  containers/Monitor/views/commonalert/update/index.vue
  containers/Monitor/views/dashboard/create/index.vue
  containers/Network/views/eip/create/index.vue
  containers/Network/views/global-vpc/create/index.vue
  containers/Network/views/lb/create/index.vue
  containers/Network/views/loadbalancerlistener/create/index.vue
  containers/Network/views/nats/create/index.vue
  containers/Network/views/vpc/create/index.vue
  containers/Storage/views/bucket/create/index.vue
  containers/Storage/views/file-system/create/index.vue
  src/components/PageBody/index.vue
  src/components/PageList/components/Table.vue
Labels: size/M

#3101 Automated cherry pick of #3100: feat: #3831 去除列表页底部白条
  containers/Cloudenv/views/cloudaccount/create/BillFileIndex.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
  containers/Compute/views/physicalmachine/add/index.vue
  containers/Compute/views/scaling-group/create/index.vue
  containers/Compute/views/tap-service/create/index.vue
  containers/DB/views/redis/create/index.vue
  containers/Helm/views/chart/create/index.vue
  containers/Helm/views/k8s-release/update/index.vue
  containers/IAM/views/domains/create/index.vue
  containers/IAM/views/notifyconfig/create/index.vue
  containers/IAM/views/projects/create/index.vue
  containers/IAM/views/user/create/index.vue
  containers/K8S/views/configmap/create/index.vue
  containers/K8S/views/cronjob/create/index.vue
  containers/K8S/views/daemonset/create/index.vue
  containers/K8S/views/deployment/create/index.vue
  containers/K8S/views/federatedclusterrole/create/index.vue
  containers/K8S/views/federatedclusterrolebinding/create/index.vue
  containers/K8S/views/federatedrole/create/index.vue
  containers/K8S/views/federatedrolebinding/create/index.vue
  containers/K8S/views/ingress/create/index.vue
  containers/K8S/views/job/create/index.vue
  containers/K8S/views/persistentvolumeclaim/create/index.vue
  containers/K8S/views/pod/create/index.vue
  containers/K8S/views/rbacclusterrole/create/index.vue
  containers/K8S/views/rbacclusterrolebinding/create/index.vue
  containers/K8S/views/rbacrole/create/index.vue
  containers/K8S/views/rbacrolebinding/create/index.vue
  containers/K8S/views/secret/create/index.vue
  containers/K8S/views/service/create/index.vue
  containers/K8S/views/statefulset/create/index.vue
  containers/Monitor/views/commonalert/create/index.vue
  containers/Monitor/views/commonalert/update/index.vue
  containers/Monitor/views/dashboard/create/index.vue
  containers/Network/views/eip/create/index.vue
  containers/Network/views/global-vpc/create/index.vue
  containers/Network/views/lb/create/index.vue
  containers/Network/views/loadbalancerlistener/create/index.vue
  containers/Network/views/nats/create/index.vue
  containers/Network/views/vpc/create/index.vue
  containers/Storage/views/bucket/create/index.vue
  containers/Storage/views/file-system/create/index.vue
  src/components/PageBody/index.vue
  src/components/PageList/components/Table.vue
Labels: size/M

#3102 feat: #3433 控制面板增加趋势图
  src/plugins/trendChart.js
Labels: size/XS

#3104 feat: 新增 InCloudSphere
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/InCloudSphere.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
  src/assets/images/providers/incloudsphere.svg
  src/components/Icon/assets/incloudsphere.svg
  src/components/PageList/components/Table.vue
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#3105 feat: InCloudSphere去除同步资源区域配置
  containers/Cloudenv/views/cloudaccount/constants.js
Labels: area/cloudenv, size/XS

#3106 feat: #3781 权限-项目标签交互优化
  containers/IAM/views/policy/Update.vue
  src/sections/PairsTag/index.vue
  src/utils/common/tag.js
Labels: size/S

#3107 Automated cherry pick of #3106: feat: #3781 权限-项目标签交互优化
  containers/IAM/views/policy/Update.vue
  src/sections/PairsTag/index.vue
  src/utils/common/tag.js
Labels: size/S

#3110 feat: #3835 新建定时任务增加类型
  containers/Cloudenv/views/cloudaccount/create/form/ScheduledSettings.vue
  containers/Cloudenv/views/cloudaccount/dialogs/ScheduledtaskCreate.vue
Labels: size/XS

#3111 Automated cherry pick of #3110: feat: #3835 新建定时任务增加类型
  containers/Cloudenv/views/cloudaccount/create/form/ScheduledSettings.vue
  containers/Cloudenv/views/cloudaccount/dialogs/ScheduledtaskCreate.vue
Labels: size/XS

#3114 fix: #8462 镜像市场从ISO导入arm的镜像后，该ISO的cpu架构不应该是x86的
  containers/Compute/views/image/mixins/columns.js
Labels: size/XS

#3115 Automated cherry pick of #3114: fix: #8462 镜像市场从ISO导入arm的镜像后，该ISO的cpu架构不应该是x86的
  containers/Compute/views/image/mixins/columns.js
Labels: size/XS

#3116 Automated cherry pick of #3114: fix: #8462 镜像市场从ISO导入arm的镜像后，该ISO的cpu架构不应该是x86的
  containers/Compute/views/image/mixins/columns.js
Labels: size/XS

#3112 feat: add global style
  src/styles/less/global.less
Labels: size/XS

#3113 Automated cherry pick of #3112: feat: add global style
  src/styles/less/global.less
Labels: size/XS

#3117 feat: #3644 增加镜像logo
  src/components/ImageIcon/assets/android.png
  src/components/ImageIcon/assets/cirros.png
  src/components/ImageIcon/assets/uos.svg
  src/components/ImageIcon/assets/vmware.png
  src/components/ImageIcon/constants.js
  src/components/ImageIcon/index.vue
Labels: size/XL

#3118 Automated cherry pick of #3117: feat: #3644 增加镜像logo
  src/components/ImageIcon/assets/android.png
  src/components/ImageIcon/assets/cirros.png
  src/components/ImageIcon/assets/uos.svg
  src/components/ImageIcon/assets/vmware.png
  src/components/ImageIcon/constants.js
  src/components/ImageIcon/index.vue
Labels: size/XL

#3119 Automated cherry pick of #3117: feat: #3644 增加镜像logo
  src/components/ImageIcon/assets/android.png
  src/components/ImageIcon/assets/cirros.png
  src/components/ImageIcon/assets/uos.svg
  src/components/ImageIcon/assets/vmware.png
  src/components/ImageIcon/constants.js
  src/components/ImageIcon/index.vue
Labels: size/XL

#3121 Automated cherry pick of #3120: feat: #3727 全局搜索框居中展示
  src/sections/Navbar/index.vue
Labels: size/XS

#3122 fix: #8463 项目-详情页-管理用户/组按钮失效
  containers/IAM/views/projects/sidepage/index.vue
Labels: size/XS

#3123 Automated cherry pick of #3122: fix: #8463 项目-详情页-管理用户/组按钮失效
  containers/IAM/views/projects/sidepage/index.vue
Labels: size/XS

#3125 Automated cherry pick of #3124: fix: 修改驱动无磁盘信息时禁止提交
  containers/Compute/views/disk/dialogs/DriverUpdateDialog.vue
Labels: size/XS

#3127 fix: 表格分页展示逻辑调整
  src/components/PageList/components/Table.vue
Labels: size/XS
