Repository yunionio/dashboard, pull requests merged in 2022-11, with the labels that each got.

#3630 feat(host): create host without BMC
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/physicalmachine/add/PreAdd.vue
  containers/Compute/views/physicalmachine/add/index.vue
Labels: size/M

#3631 Automated cherry pick of #3630: feat(host): create host without BMC
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/physicalmachine/add/PreAdd.vue
  containers/Compute/views/physicalmachine/add/index.vue
Labels: size/M

#3632 feat: The pageList component adds singleactions monitoring
  src/components/PageList/components/Table.vue
Labels: size/S

#3633 Automated cherry pick of #3632: feat: The pageList component adds singleactions monitoring
  src/components/PageList/components/Table.vue
Labels: size/S

#3634 feat: add common status i18n
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#3635 Automated cherry pick of #3634: feat: add common status i18n
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#3638 fix: status show error
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#3639 Automated cherry pick of #3638: fix: status fix
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#3636 fix: filter change disk storage by server_id
  containers/Compute/views/disk/dialogs/ChangeBlockStorage.vue
  containers/Compute/views/disk/mixins/storageResourceProps.js
Labels: size/S

#3637 Automated cherry pick of #3636: fix: filter change disk storage by server_id
  containers/Compute/views/disk/dialogs/ChangeBlockStorage.vue
  containers/Compute/views/disk/mixins/storageResourceProps.js
Labels: size/S

#3640 fix: adjust lb column width
  containers/Network/views/agent/mixins/columns.js
  containers/Network/views/lbacls/mixins/columns.js
Labels: size/XS

#3641 Automated cherry pick of #3640: fix: adjust lb column width
  containers/Network/views/agent/mixins/columns.js
  containers/Network/views/lbacls/mixins/columns.js
Labels: size/XS

#3642 Automated cherry pick of #3640: fix: adjust lb column width
  containers/Network/views/agent/mixins/columns.js
  containers/Network/views/lbacls/mixins/columns.js
Labels: size/XS

#3644 Automated cherry pick of #3643: fix: disable disk change storage in project view
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/XS

#3643 fix: disable disk change storage in project view
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/XS

#3647 feat: add expectstatus i18n
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#3648 Automated cherry pick of #3647: feat: add expectstatus i18n
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#3645 fix: server disabled detail tabs before get server detail
  containers/Compute/sections/VncInfoFetcher/index.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  src/components/BaseSidePage/index.vue
  src/components/SecurityCode/index.vue
Labels: area/compute, size/L

#3649 fix: #8638 image detail create server not match image type
  containers/Compute/views/image/dialogs/ImageCreateServer.vue
Labels: area/compute, size/XS

#3650 Automated cherry pick of #3649: fix: #8638 image detail create server not match image type
  containers/Compute/views/image/dialogs/ImageCreateServer.vue
Labels: size/XS

#3651 Automated cherry pick of #3649: fix: #8638 image detail create server not match image type
  containers/Compute/views/image/dialogs/ImageCreateServer.vue
Labels: size/XS

#3652 fix: #8639 create local disk check prefer_host_id param
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/create/components/HostServer.vue
  containers/Compute/views/disk/create/index.vue
Labels: area/compute, size/L

#3653 Automated cherry pick of #3652: fix: #8639 create local disk check prefer_host_id param
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/create/components/HostServer.vue
  containers/Compute/views/disk/create/index.vue
Labels: size/L

#3654 feat: #3929 support create disk from disk snapshot
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/snapshot/dialogs/CreateDisk.vue
  containers/Compute/views/snapshot/mixins/singleActions.js
Labels: area/compute, size/L

#3655 Automated cherry pick of #3654: feat: #3929 support create disk from disk snapshot
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/snapshot/dialogs/CreateDisk.vue
  containers/Compute/views/snapshot/mixins/singleActions.js
Labels: size/L

#3656 fix: remove empty feild in detail sidepage
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/agent/components/List.vue
  containers/Network/views/agent/mixins/columns.js
  containers/Network/views/agent/sidepage/Detail.vue
  src/components/Detail/index.js
Labels: size/L

#3662 Automated cherry pick of #3661: fix(Network): deploy lb-agent yum url for v3.9
  containers/Network/views/agent/dialogs/Deploy.vue
Labels: size/S

#3657 feat: #3993 server transfer quickly_finish change to switch component
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/utils.js
Labels: area/compute, size/XS

#3658 Automated cherry pick of #3657: feat: #3993 server transfer quickly_finish change to switch component
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/utils.js
Labels: size/XS

#3659 feat: #3983 add system config i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#3663 feat: #4007 liquid fill component add style for value >= 100%
  src/components/LiquidFill/index.vue
Labels: size/XS

#3664 Automated cherry pick of #3663: feat: #4007 liquid fill component add style for value >= 100%
  src/components/LiquidFill/index.vue
Labels: size/XS

#3669 K8s kylin
  containers/K8S/sections/serverConfig/index.vue
Labels: size/XS

#3670 Automated cherry pick of #3669: feat(k8s): allow kylin image as node
  containers/K8S/sections/serverConfig/index.vue
Labels: size/XS

#3667 feat: #4007 liquid fill component style
  src/components/LiquidFill/index.vue
Labels: size/XS

#3668 Automated cherry pick of #3667: feat: #4007 liquid fill component style
  src/components/LiquidFill/index.vue
Labels: size/XS

#3665 feat: #4006 add docs and app version info
  scope/layouts/Navbar/index.vue
  scope/router/routes.js
  scope/store/modules/app.js
  scope/views/licenses/index.vue
  src/assets/contact.png
  src/sections/Navbar/components/MorePopover.vue
Labels: size/L

#3666 Automated cherry pick of #3665: feat: #4006 add docs and app version info
  scope/layouts/Navbar/index.vue
  scope/router/routes.js
  scope/store/modules/app.js
  scope/views/licenses/index.vue
  src/assets/contact.png
  src/sections/Navbar/components/MorePopover.vue
Labels: size/L

#3671 feat: base select component dropdown item style
  src/components/BaseSelect/index.vue
Labels: size/XS

#3673 Automated cherry pick of #3671: feat: base select component dropdown item style
  src/components/BaseSelect/index.vue
Labels: size/XS

#3672 Automated cherry pick of #3671: feat: base select component dropdown item style
  src/components/BaseSelect/index.vue
Labels: size/XS

#3675 fix: vmware server with sync_ips
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/S

#3676 Automated cherry pick of #3675: fix: vmware server with sync_ips
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/S

#3679 fix(k8s): tooltip of service port
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/sections/PortMapping/Port.vue
  containers/K8S/views/service/mixins/columns.js
Labels: size/M

#3680 Automated cherry pick of #3679: fix(k8s): tooltip of service port
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/sections/PortMapping/Port.vue
  containers/K8S/views/service/mixins/columns.js
Labels: size/M

#3681 feat(k8s): create nodePort service
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/sections/PortMapping/Port.vue
  containers/K8S/sections/PortMapping/index.vue
  containers/K8S/utils/index.js
  containers/K8S/views/cronjob/create/Form.vue
  containers/K8S/views/daemonset/create/Form.vue
  containers/K8S/views/deployment/create/Form.vue
  containers/K8S/views/service/create/Form.vue
  containers/K8S/views/statefulset/create/Form.vue
Labels: size/L

#3682 Automated cherry pick of #3681: feat(k8s): create nodePort service
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/sections/PortMapping/Port.vue
  containers/K8S/sections/PortMapping/index.vue
  containers/K8S/utils/index.js
  containers/K8S/views/cronjob/create/Form.vue
  containers/K8S/views/daemonset/create/Form.vue
  containers/K8S/views/deployment/create/Form.vue
  containers/K8S/views/service/create/Form.vue
  containers/K8S/views/statefulset/create/Form.vue
Labels: size/L

#3677 fix: cloudaccount status of sync_network
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#3678 Automated cherry pick of #3677: fix: cloudaccount status of sync_network
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#3674 feat: #3970 import extra permission file to config menu permission
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#3683 feat: del app version error request
  scope/store/modules/app.js
  src/sections/Navbar/components/MorePopover.vue
Labels: size/S

#3684 Automated cherry pick of #3683: feat: del app version error request
  scope/store/modules/app.js
  src/sections/Navbar/components/MorePopover.vue
Labels: size/S

#3691 Automated cherry pick of #3690: fix: #8652 qga docs url
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/ResetPassword.vue
  src/utils/docs.js
Labels: size/S

#3685 fix: #8650 refresh network after change reserved ip
  containers/Network/views/reserved-ip/components/List.vue
  containers/Network/views/reserved-ip/mixins/singleActions.js
Labels: area/compute, size/S

#3686 Automated cherry pick of #3685: fix: #8650 refresh network after change reserved ip
  containers/Network/views/reserved-ip/components/List.vue
  containers/Network/views/reserved-ip/mixins/singleActions.js
Labels: size/S

#3687 Automated cherry pick of #3685: fix: #8650 refresh network after change reserved ip
  containers/Network/views/reserved-ip/components/List.vue
  containers/Network/views/reserved-ip/mixins/singleActions.js
Labels: size/S

#3688 feat: #3937 aksk support download after created success
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/clouduser/dialogs/AkSkCreate.vue
  containers/Cloudenv/views/clouduser/dialogs/AkSkDownload.vue
  containers/Cloudenv/views/clouduser/sidepage/AkSkList.vue
Labels: size/M, area/cloudenv

#3689 Automated cherry pick of #3688: feat: #3937 aksk support download after created success
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/clouduser/dialogs/AkSkCreate.vue
  containers/Cloudenv/views/clouduser/dialogs/AkSkDownload.vue
  containers/Cloudenv/views/clouduser/sidepage/AkSkList.vue
Labels: size/M

#3694 feat: #4009 global search support external id
  src/constants/globalSearch.js
  src/sections/Navbar/components/GlobalSearch.vue
Labels: size/L

#3695 Automated cherry pick of #3694: feat: #4009 global search support external id
  src/constants/globalSearch.js
  src/sections/Navbar/components/GlobalSearch.vue
Labels: size/L

#3696 fix: #8653 oc-select params watcher
  src/components/OcSelect/index.vue
Labels: size/XS

#3692 fix(k8s): lb-network should be filtered by vpc_id of cluster
  containers/K8S/sections/PortMapping/LbNetwork.vue
  containers/K8S/sections/PortMapping/index.vue
  containers/K8S/views/daemonset/create/Form.vue
  containers/K8S/views/deployment/create/Form.vue
  containers/K8S/views/service/create/Form.vue
  containers/K8S/views/statefulset/create/Form.vue
Labels: size/M

#3693 Automated cherry pick of #3692: fix(k8s): lb-network should be filtered by vpc_id of cluster
  containers/K8S/sections/PortMapping/LbNetwork.vue
  containers/K8S/sections/PortMapping/index.vue
  containers/K8S/views/daemonset/create/Form.vue
  containers/K8S/views/deployment/create/Form.vue
  containers/K8S/views/service/create/Form.vue
  containers/K8S/views/statefulset/create/Form.vue
Labels: size/M

#3697 fix(k8s): select daemonsets as service's backend
  containers/K8S/views/service/create/Form.vue
Labels: area/k8s, size/S

#3698 Automated cherry pick of #3697: fix(k8s): select daemonsets as service's backend
  containers/K8S/views/service/create/Form.vue
Labels: size/S

#3699 fix: acess metadata.sync_ips may fail
  src/utils/common/tableColumn.js
Labels: size/XS

#3704 feat(k8s): specify address of lb
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/sections/PortMapping/LbNetwork.vue
  containers/K8S/sections/PortMapping/index.vue
  containers/K8S/utils/index.js
  containers/K8S/views/ingress/create/index.vue
  containers/K8S/views/service/create/Form.vue
Labels: size/L

#3705 Automated cherry pick of #3704: feat(k8s): specify address of lb
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/sections/PortMapping/LbNetwork.vue
  containers/K8S/sections/PortMapping/index.vue
  containers/K8S/utils/index.js
  containers/K8S/views/ingress/create/index.vue
  containers/K8S/views/service/create/Form.vue
Labels: size/L

#3706 feat(k8s): sticky session of ingress
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/views/ingress/create/Form.vue
Labels: size/M

#3707 Automated cherry pick of #3706: feat(k8s): sticky session of ingress
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/views/ingress/create/Form.vue
Labels: size/M

#3701 feat: add normal distinct table filter
  src/utils/common/tableFilter.js
Labels: size/M

#3702 Automated cherry pick of #3701: feat: add normal distinct table filter
  src/utils/common/tableFilter.js
Labels: size/M

#3703 feat: #4001 server (running) support acttach gpu remove from 3.9
  containers/Compute/views/vminstance/utils.js
Labels: area/compute, size/XS

#3708 feat: #4033 account schedule task auto fill name and time
  containers/Cloudenv/views/cloudaccount/create/form/ScheduledSettings.vue
Labels: area/cloudenv, size/S

#3709 Automated cherry pick of #3708: feat: #4033 account schedule task auto fill name and time
  containers/Cloudenv/views/cloudaccount/create/form/ScheduledSettings.vue
Labels: size/S

#3710 feat: #4025 vminstance support set boot index
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Update.vue
  containers/Compute/views/vminstance/dialogs/VmChangeBootIndex.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  src/constants/permission.js
Labels: area/compute, size/L, do-not-merge/hold

#3715 fix: #8658 update change block storage
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/dialogs/ChangeBlockStorage.vue
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/vminstance/dialogs/ChangeBlockStorage.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/M

#3716 Automated cherry pick of #3715: fix: #8658 update change block storage
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/dialogs/ChangeBlockStorage.vue
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/vminstance/dialogs/ChangeBlockStorage.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/M

#3717 fix: #8640 虚拟机热迁移时应该显示迁移进度
  src/components/Status/index.vue
Labels: size/XS

#3720 Automated cherry pick of #3719: fix: #8642 域管理后台 虚拟机批量迁移按钮应该可以点击的
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#3719 fix: #8642 域管理后台 虚拟机批量迁移按钮应该可以点击的
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#3721 feat: #4031 menu sidebar style (hover) add linked bgcolor
  src/sections/ProductsList/index.vue
Labels: size/S

#3722 Automated cherry pick of #3721: feat: #4031 menu sidebar style (hover) add linked bgcolor
  src/sections/ProductsList/index.vue
Labels: size/S

#3725 feat(k8s): configure ip address of cluster node
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/sections/serverConfig/index.vue
  containers/K8S/views/kube-machines/dialogs/CreateKubemachinesDialog.vue
Labels: area/k8s, size/S

#3726 Automated cherry pick of #3725: feat(k8s): configure ip address of cluster node
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/sections/serverConfig/index.vue
  containers/K8S/views/kube-machines/dialogs/CreateKubemachinesDialog.vue
Labels: size/S

#3727 fix: add usb details of vm
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/M

#3730 fix: ldap user/group dn should be optional
  containers/IAM/views/idp/edit/MSADMulti.vue
  containers/IAM/views/idp/edit/MSADOne.vue
  containers/IAM/views/idp/edit/OpenLdapOne.vue
  containers/IAM/views/idp/sidepage/Detail.vue
Labels: size/S

#3728 Automated cherry pick of #3727: fix: add usb details of vm
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/M

#3729 Automated cherry pick of #3727: fix: add usb details of vm
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/M

#3731 Automated cherry pick of #3730: fix: ldap user/group dn should be optional
  containers/IAM/views/idp/edit/MSADMulti.vue
  containers/IAM/views/idp/edit/MSADOne.vue
  containers/IAM/views/idp/edit/OpenLdapOne.vue
  containers/IAM/views/idp/sidepage/Detail.vue
Labels: size/S

#3732 feat: #4056 rds monitor support remotefile
  containers/DB/constants/index.js
  containers/DB/views/rds/sidepage/Monitor.vue
Labels: area/db, size/S

#3735 fix: hcs lb and redis
  containers/DB/views/redis/mixins/singleActions.js
  containers/Network/views/lb/create/form/Private.vue
Labels: size/XS

#3736 Automated cherry pick of #3735: fix: hcs lb and redis
  containers/DB/views/redis/mixins/singleActions.js
  containers/Network/views/lb/create/form/Private.vue
Labels: size/XS

#3737 feat: #4025 vminstance update tips
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/XS

#3739 Automated cherry pick of #3737: feat: #4025 vminstance update tips
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/XS

#3738 feat: #4025 vminstance set boot index style
  containers/Compute/views/vminstance/dialogs/VmChangeBootIndex.vue
Labels: area/compute, size/S

#3740 Automated cherry pick of #3737: feat: #4025 vminstance update tips
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/XS

#3741 fix: #8663 rds/redis private platform donot support price calc
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/redis/create/components/BottomBar.vue
Labels: area/db, size/S

#3742 Automated cherry pick of #3741: fix: #8663 rds/redis private platform donot support price calc
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/redis/create/components/BottomBar.vue
Labels: size/S

#3744 fix: hcs disk
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/snapshot/validate.js
Labels: size/S

#3746 fix: #8663 rds/redis private platform donot support price calc
  containers/DB/views/rds/create/changeMinxin.js
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/rds/create/index.vue
  containers/DB/views/redis/create/changeMinxin.js
  containers/DB/views/redis/create/components/BottomBar.vue
  containers/DB/views/redis/create/index.vue
Labels: size/M, area/db

#3748 Automated cherry pick of #3746: fix: #8663 rds/redis private platform donot support price calc
  containers/DB/views/rds/create/changeMinxin.js
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/rds/create/index.vue
  containers/DB/views/redis/create/changeMinxin.js
  containers/DB/views/redis/create/components/BottomBar.vue
  containers/DB/views/redis/create/index.vue
Labels: size/M

#3747 Automated cherry pick of #3746: fix: #8663 rds/redis private platform donot support price calc
  containers/DB/views/rds/create/changeMinxin.js
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/rds/create/index.vue
  containers/DB/views/redis/create/changeMinxin.js
  containers/DB/views/redis/create/components/BottomBar.vue
  containers/DB/views/redis/create/index.vue
Labels: size/M

#3749 fix(k8s): nodePort validator
  containers/K8S/sections/PortMapping/Port.vue
  containers/K8S/utils/index.js
Labels: area/k8s

#3753 feat: add status
  src/constants/expectStatus.js
Labels: size/XS

#3754 Automated cherry pick of #3753: feat: add status
  src/constants/expectStatus.js
Labels: size/XS

#3751 feat: add cdn create
  containers/Network/router/index.js
  containers/Network/views/cdn/components/List.vue
  containers/Network/views/cdn/constants/index.js
  containers/Network/views/cdn/create/index.vue
  containers/Network/views/cdn/locales/en.json
  containers/Network/views/cdn/locales/zh-CN.json
Labels: size/L

#3752 Automated cherry pick of #3751: feat: add cdn create
  containers/Network/router/index.js
  containers/Network/views/cdn/components/List.vue
  containers/Network/views/cdn/constants/index.js
  containers/Network/views/cdn/create/index.vue
  containers/Network/views/cdn/locales/en.json
  containers/Network/views/cdn/locales/zh-CN.json
Labels: size/L

#3755 fix: i18n error
  containers/Network/views/cdn/constants/index.js
Labels: size/S

#3757 feat: add status
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#3759 feat: #4006 ce appversion text
  src/sections/Navbar/components/MorePopover.vue
Labels: size/XS

#3760 Automated cherry pick of #3759: feat: #4006 ce appversion text
  src/sections/Navbar/components/MorePopover.vue
Labels: size/XS

#3761 Automated cherry pick of #3759: feat: #4006 ce appversion text
  src/sections/Navbar/components/MorePopover.vue
Labels: size/XS

#3763 Automated cherry pick of #3762: feat: #3971 更换默认管理后台、域管理后台、项目视图的磁铁
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/Top5/constants.js
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/views/dashboard/config/default.js
  src/components/Icon/assets/dashboard-alert-sum.svg
  src/components/Icon/assets/dashboard-alerts-trend.svg
  src/components/Icon/assets/dashboard-cloud-account-health.svg
  src/components/Icon/assets/dashboard-consmption-trend.svg
  src/components/Icon/assets/dashboard-consumption-percent.svg
  src/components/Icon/assets/dashboard-log.svg
  src/components/Icon/assets/dashboard-notice.svg
  src/components/Icon/assets/dashboard-number.svg
  src/components/Icon/assets/dashboard-suggest-detail.svg
  src/components/Icon/assets/dashboard-suggest-overview.svg
  src/components/Icon/assets/dashboard-top5.svg
  src/components/Icon/assets/dashboard-usage.svg
  src/components/Icon/assets/dashboard-user-info.svg
  src/components/Icon/assets/dashboard-vmhistory-count-trend.svg
Labels: size/XXL

#3762 #3971 默认磁铁优化
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/Top5/constants.js
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/views/dashboard/config/default.js
  src/components/Icon/assets/dashboard-alert-sum.svg
  src/components/Icon/assets/dashboard-alerts-trend.svg
  src/components/Icon/assets/dashboard-cloud-account-health.svg
  src/components/Icon/assets/dashboard-consmption-trend.svg
  src/components/Icon/assets/dashboard-consumption-percent.svg
  src/components/Icon/assets/dashboard-log.svg
  src/components/Icon/assets/dashboard-notice.svg
  src/components/Icon/assets/dashboard-number.svg
  src/components/Icon/assets/dashboard-suggest-detail.svg
  src/components/Icon/assets/dashboard-suggest-overview.svg
  src/components/Icon/assets/dashboard-top5.svg
  src/components/Icon/assets/dashboard-usage.svg
  src/components/Icon/assets/dashboard-user-info.svg
  src/components/Icon/assets/dashboard-vmhistory-count-trend.svg
Labels: size/XXL

#3764 fix: login add logged tenant check for issue#15444
  src/store/modules/auth.js
Labels: size/XS

#3765 Automated cherry pick of #3764: fix: login add logged tenant check for issue#15444
  src/store/modules/auth.js
Labels: size/XS

#3766 Automated cherry pick of #3764: fix: login add logged tenant check for issue#15444
  src/store/modules/auth.js
Labels: size/XS

#3767 Automated cherry pick of #3764: fix: login add logged tenant check for issue#15444
  src/store/modules/auth.js
Labels: size/XS

#3768 feat: #4035 zstack录入文案优化
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#3769 Automated cherry pick of #3768: feat: #4035 zstack录入文案优化
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#3770 Automated cherry pick of #3768: feat: #4035 zstack录入文案优化
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#3771 Automated cherry pick of #3768: feat: #4035 zstack录入文案优化
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#3772 fix(k8s): yaml edit params
  containers/K8S/sections/SourceInformationSidepage/index.vue
  containers/K8S/views/configmap/mixins/singleActions.js
  containers/K8S/views/cronjob/mixins/singleActions.js
  containers/K8S/views/daemonset/mixins/singleActions.js
  containers/K8S/views/deployment/mixins/singleActions.js
  containers/K8S/views/ingress/mixins/singleActions.js
  containers/K8S/views/job/mixins/singleActions.js
  containers/K8S/views/namespace/mixins/singleActions.js
  containers/K8S/views/nodes/mixins/singleActions.js
  containers/K8S/views/persistentvolumeclaim/mixins/singleActions.js
  containers/K8S/views/pod/mixins/singleActions.js
  containers/K8S/views/rbacclusterrole/mixins/singleActions.js
  containers/K8S/views/rbacclusterrolebinding/mixins/singleActions.js
  containers/K8S/views/rbacrole/mixins/singleActions.js
  containers/K8S/views/rbacrolebinding/mixins/singleActions.js
  containers/K8S/views/secret/mixins/singleActions.js
  containers/K8S/views/service-account/mixins/singleActions.js
  containers/K8S/views/service/mixins/singleActions.js
  containers/K8S/views/statefulset/mixins/singleActions.js
  containers/K8S/views/storage-class/mixins/singleActions.js
  jsconfig.json
Labels: size/M, area/k8s

#3773 Automated cherry pick of #3772: fix(k8s): yaml edit params
  containers/K8S/sections/SourceInformationSidepage/index.vue
  containers/K8S/views/configmap/mixins/singleActions.js
  containers/K8S/views/cronjob/mixins/singleActions.js
  containers/K8S/views/daemonset/mixins/singleActions.js
  containers/K8S/views/deployment/mixins/singleActions.js
  containers/K8S/views/ingress/mixins/singleActions.js
  containers/K8S/views/job/mixins/singleActions.js
  containers/K8S/views/namespace/mixins/singleActions.js
  containers/K8S/views/nodes/mixins/singleActions.js
  containers/K8S/views/persistentvolumeclaim/mixins/singleActions.js
  containers/K8S/views/pod/mixins/singleActions.js
  containers/K8S/views/rbacclusterrole/mixins/singleActions.js
  containers/K8S/views/rbacclusterrolebinding/mixins/singleActions.js
  containers/K8S/views/rbacrole/mixins/singleActions.js
  containers/K8S/views/rbacrolebinding/mixins/singleActions.js
  containers/K8S/views/secret/mixins/singleActions.js
  containers/K8S/views/service-account/mixins/singleActions.js
  containers/K8S/views/service/mixins/singleActions.js
  containers/K8S/views/statefulset/mixins/singleActions.js
  containers/K8S/views/storage-class/mixins/singleActions.js
  jsconfig.json
Labels: size/M

#3774 Automated cherry pick of #3772: fix(k8s): yaml edit params
  containers/K8S/sections/SourceInformationSidepage/index.vue
  containers/K8S/views/configmap/mixins/singleActions.js
  containers/K8S/views/cronjob/mixins/singleActions.js
  containers/K8S/views/daemonset/mixins/singleActions.js
  containers/K8S/views/deployment/mixins/singleActions.js
  containers/K8S/views/ingress/mixins/singleActions.js
  containers/K8S/views/job/mixins/singleActions.js
  containers/K8S/views/namespace/mixins/singleActions.js
  containers/K8S/views/nodes/mixins/singleActions.js
  containers/K8S/views/persistentvolumeclaim/mixins/singleActions.js
  containers/K8S/views/pod/mixins/singleActions.js
  containers/K8S/views/rbacclusterrole/mixins/singleActions.js
  containers/K8S/views/rbacclusterrolebinding/mixins/singleActions.js
  containers/K8S/views/rbacrole/mixins/singleActions.js
  containers/K8S/views/rbacrolebinding/mixins/singleActions.js
  containers/K8S/views/secret/mixins/singleActions.js
  containers/K8S/views/service-account/mixins/singleActions.js
  containers/K8S/views/service/mixins/singleActions.js
  containers/K8S/views/statefulset/mixins/singleActions.js
  containers/K8S/views/storage-class/mixins/singleActions.js
  jsconfig.json
Labels: size/M

#3775 feat: #4063 HCS功能选择对应菜单优化
  containers/Cloudenv/router/index.js
  containers/DB/router/index.js
  containers/Network/router/index.js
  containers/Storage/router/index.js
Labels: size/S

#3776 Automated cherry pick of #3775: feat: #4063 HCS功能选择对应菜单优化
  containers/Cloudenv/router/index.js
  containers/DB/router/index.js
  containers/Network/router/index.js
  containers/Storage/router/index.js
Labels: size/S

#3777 fix: hcs eip and snapshot misc fix
  containers/Compute/views/snapshot/validate.js
  containers/Network/views/eip/create/index.vue
Labels: size/XS

#3778 Automated cherry pick of #3777: fix: hcs eip and snapshot misc fix
  containers/Compute/views/snapshot/validate.js
  containers/Network/views/eip/create/index.vue
Labels: size/XS

#3780 Automated cherry pick of #3779: fix: #8666 手工上传arm的镜像后，镜像列表中架构不应该显示x86_64
  src/utils/common/tableColumn.js
Labels: size/XS

#3782 Automated cherry pick of #3779: fix: #8666 手工上传arm的镜像后，镜像列表中架构不应该显示x86_64
  src/utils/common/tableColumn.js
Labels: size/XS

#3784 Automated cherry pick of #3783: fix: image details os_arch
  containers/Compute/views/image/sidepage/Detail.vue
Labels: size/XS

#3786 Automated cherry pick of #3783: fix: image details os_arch
  containers/Compute/views/image/sidepage/Detail.vue
Labels: size/XS

#3785 Automated cherry pick of #3783: fix: image details os_arch
  containers/Compute/views/image/sidepage/Detail.vue
Labels: size/XS

#3787 feat: #4066 vpc新建对等连接
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/vpc-peer-connect/components/List.vue
  containers/Network/views/vpc-peer-connect/constants.js
  containers/Network/views/vpc-peer-connect/create/index.vue
  src/constants/permission.js
Labels: size/L

#3788 Automated cherry pick of #3787: feat: #4066 vpc新建对等连接
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/vpc-peer-connect/components/List.vue
  containers/Network/views/vpc-peer-connect/constants.js
  containers/Network/views/vpc-peer-connect/create/index.vue
  src/constants/permission.js
Labels: size/L

#3789 fix: cdn create i18n error
  containers/Network/views/cdn/create/index.vue
  containers/Network/views/cdn/locales/en.json
  containers/Network/views/cdn/locales/zh-CN.json
Labels: size/XS

#3790 Automated cherry pick of #3789: fix: cdn create i18n error
  containers/Network/views/cdn/create/index.vue
  containers/Network/views/cdn/locales/en.json
  containers/Network/views/cdn/locales/zh-CN.json
Labels: size/XS
