Repository yunionio/dashboard, pull requests merged in 2022-08, with the labels that each got.

#3249 feat: #3838 使用率增加水球图,调整控制面板组件复用逻辑
  containers/Dashboard/extends/AccountHealth/index.vue
  containers/Dashboard/extends/AlertsTrend/index.vue
  containers/Dashboard/extends/Notify copy/index.vue
  containers/Dashboard/extends/Notify/index.vue
  containers/Dashboard/extends/NumberCard/components/K8s.vue
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/extends/NumberCard/components/mixin.js
  containers/Dashboard/extends/NumberCard/index.vue
  containers/Dashboard/extends/Ring/components/K8s.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/Ring/components/mixin.js
  containers/Dashboard/extends/Ring/index.vue
  containers/Dashboard/extends/ServerNumberDetail/index.vue
  containers/Dashboard/extends/Top5/constants.js
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/extends/UnrecoveredAlarm/index.vue
  containers/Dashboard/extends/UserInfo/index.vue
  containers/Dashboard/extends/VmHistoryCount/index.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/sections/K8sConfig/index.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
  package-lock.json
  package.json
  scope/extends/Ring/components/mixin.js
  scope/extends/index.js
  src/components/LiquidFill/index.vue
  yarn.lock
Labels: area/dashboard, size/XXL

#3250 feat: #3867 token过期提示
  src/locales/en.json
  src/locales/zh-CN.json
  src/mixins/logout.js
  src/sections/Auth/Login/components/LoginChallengeInDialog.vue
  src/sections/Auth/Login/components/LoginChooserInDialog.vue
  src/sections/DialogManager/components/Login.vue
Labels: size/XL

#3251 fix: 隐藏云账号健康状态磁贴
  containers/Dashboard/sections/ExtendGallery/index.vue
Labels: area/dashboard, size/XS

#3252 Automated cherry pick of #3251: fix: 隐藏云账号健康状态磁贴
  containers/Dashboard/sections/ExtendGallery/index.vue
Labels: size/XS

#3253 Automated cherry pick of #3251: fix: 隐藏云账号健康状态磁贴
  containers/Dashboard/sections/ExtendGallery/index.vue
Labels: size/XS

#3270 feat: #3873 CPU和内存增加不限的选项，支持用户可以根据套餐类型选购
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/CpuRadio/index.vue
  containers/Compute/sections/MemRadio/index.vue
  containers/Compute/sections/SKU/index.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/L

#3271 Automated cherry pick of #3270: feat: #3873 CPU和内存增加不限的选项，支持用户可以根据套餐类型选购
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/CpuRadio/index.vue
  containers/Compute/sections/MemRadio/index.vue
  containers/Compute/sections/SKU/index.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/L

#3272 Automated cherry pick of #3270: feat: #3873 CPU和内存增加不限的选项，支持用户可以根据套餐类型选购
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/CpuRadio/index.vue
  containers/Compute/sections/MemRadio/index.vue
  containers/Compute/sections/SKU/index.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/L

#3277 Automated cherry pick of #3250: feat: #3867 token过期提示
  src/locales/en.json
  src/locales/zh-CN.json
  src/mixins/logout.js
  src/sections/Auth/Login/components/LoginChallengeInDialog.vue
  src/sections/Auth/Login/components/LoginChooserInDialog.vue
  src/sections/DialogManager/components/Login.vue
Labels: size/XL

#3276 Automated cherry pick of #3250: feat: #3867 token过期提示
  src/locales/en.json
  src/locales/zh-CN.json
  src/mixins/logout.js
  src/sections/Auth/Login/components/LoginChallengeInDialog.vue
  src/sections/Auth/Login/components/LoginChooserInDialog.vue
  src/sections/DialogManager/components/Login.vue
Labels: size/XL

#3274 feat: #3876 vpc互联与对等连接ui策略限制
  containers/Network/router/index.js
Labels: area/network, size/XS

#3275 Automated cherry pick of #3274: feat: #3876 vpc互联与对等连接ui策略限制
  containers/Network/router/index.js
Labels: size/XS

#3273 feat: 控制面板布局优化
  containers/Dashboard/components/GridShadow/index.vue
  containers/Dashboard/styles/index.less
  containers/Dashboard/styles/index.scss
  containers/Dashboard/views/dashboard/components/Content.vue
  containers/Dashboard/views/dashboard/config/default.js
  containers/Dashboard/views/dashboard/config/public-default.js
  containers/Dashboard/views/edit/index.vue
  scope/extends/config.js
  src/styles/less/global.less
Labels: area/dashboard, size/XXL

#3278 Automated cherry pick of #3265: feat: #3867 token过期提示优化
  src/locales/en.json
  src/locales/zh-CN.json
  src/mixins/logout.js
  src/sections/DialogManager/components/Login.vue
Labels: size/M

#3279 Automated cherry pick of #3265: feat: #3867 token过期提示优化
  src/locales/en.json
  src/locales/zh-CN.json
  src/mixins/logout.js
  src/sections/DialogManager/components/Login.vue
Labels: size/M

#3280 feat: #3838 控制面板使用率增加水球图样式
  containers/Dashboard/extends/Ring/components/K8s.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/Ring/components/mixin.js
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/sections/K8sConfig/index.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
  package-lock.json
  package.json
  src/components/LiquidFill/index.vue
  yarn.lock
Labels: area/dashboard, size/XXL

#3281 feat: #3258 硬盘排序字段优化
  containers/Compute/views/disk/utils/columns.js
Labels: area/compute, size/XS

#3282 Automated cherry pick of #3281: feat: #3258 硬盘排序字段优化
  containers/Compute/views/disk/utils/columns.js
Labels: size/XS

#3283 Automated cherry pick of #3281: feat: #3258 硬盘排序字段优化
  containers/Compute/views/disk/utils/columns.js
Labels: size/XS

#3285 fix: token过期验证优化
  src/App.vue
  src/sections/Auth/Login/components/LoginChallengeInDialog.vue
Labels: size/XS

#3286 feat: 增加全局翻译
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/XS

#3287 feat: #3879 增加指标图翻译信息
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
Labels: size/XS

#3288 feature: license v4 support
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#3289 Automated cherry pick of #3288: feature: license v4 support
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#3290 Automated cherry pick of #3288: feature: license v4 support
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#3291 feat: 增加版本展示配置
  src/config/channel_setting.js
Labels: size/XS

#3292 Automated cherry pick of #3291: feat: 增加版本展示配置
  src/config/channel_setting.js
Labels: size/XS

#3293 Automated cherry pick of #3291: feat: 增加版本展示配置
  src/config/channel_setting.js
Labels: size/XS

#3294 feat: 版本信息取值于process变量
  src/config/setting.js
Labels: size/XS

#3295 Automated cherry pick of #3294: feat: 版本信息取值于process变量
  src/config/setting.js
Labels: size/XS

#3296 Automated cherry pick of #3294: feat: 版本信息取值于process变量
  src/config/setting.js
Labels: size/XS

#3299 fix: 安全组的过滤
  containers/Compute/views/secgroup/dialogs/SetServer.vue
Labels: size/M

#3300 Automated cherry pick of #3299: fix: 安全组的过滤
  containers/Compute/views/secgroup/dialogs/SetServer.vue
Labels: size/M

#3301 feat: 增加全局变量env
  src/config/setting.js
  src/main.js
Labels: size/XS

#3302 Automated cherry pick of #3301: feat: 增加全局变量env
  src/config/setting.js
  src/main.js
Labels: size/XS

#3303 Automated cherry pick of #3301: feat: 增加全局变量env
  src/config/setting.js
  src/main.js
Labels: size/XS

#3304 fix: #8511 存储ui策略优化
  containers/Storage/router/index.js
Labels: area/storage, size/XS

#3305 Automated cherry pick of #3304: fix: #8511 存储ui策略优化
  containers/Storage/router/index.js
Labels: size/XS

#3306 fix: 虚拟机/磁盘排序优化
  containers/Compute/views/disk/utils/columns.js
  containers/Compute/views/vminstance/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/XS

#3307 Automated cherry pick of #3306: fix: 虚拟机/磁盘排序优化
  containers/Compute/views/disk/utils/columns.js
  containers/Compute/views/vminstance/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/XS

#3308 Automated cherry pick of #3306: fix: 虚拟机/磁盘排序优化
  containers/Compute/views/disk/utils/columns.js
  containers/Compute/views/vminstance/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/S

#3311 feat: 通用列表列增加云环境
  src/components/Icon/assets/menu-operation.svg
  src/constants/permission.js
  src/utils/common/tableColumn.js
Labels: size/S

#3312 fix: 磁盘 挂载状态及挂载虚拟机排序优化
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/utils/columns.js
Labels: size/XS

#3313 Automated cherry pick of #3312: fix: 磁盘 挂载状态及挂载虚拟机排序优化
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/utils/columns.js
Labels: size/XS

#3317 fix: #8514 新建本地IDC虚拟机，CPU和内存选择不限时，套餐列表不应该为空
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
Labels: size/S

#3318 Automated cherry pick of #3317: fix: #8514 新建本地IDC虚拟机，CPU和内存选择不限时，套餐列表不应该为空
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
Labels: size/S

#3315 fix: 共用组件 DateTime props中函数this指向问题
  src/components/DateTime/index.vue
Labels: size/XS

#3316 Automated cherry pick of #3315: fix: 共用组件 DateTime props中函数this指向问题
  src/components/DateTime/index.vue
Labels: size/XS

#3319 Automated cherry pick of #3317: fix: #8514 新建本地IDC虚拟机，CPU和内存选择不限时，套餐列表不应该为空
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
Labels: size/S

#3323 fix: secgroup params
  containers/Compute/views/secgroup/dialogs/SetServer.vue
  containers/Compute/views/secgroup/mixins/serverListPropsForSetServer.js
Labels: size/XS

#3320 fix: #8516 资源列表增加只读云 云环境的展示
  src/utils/common/hypervisor.js
Labels: size/XS

#3321 Automated cherry pick of #3320: fix: #8516 资源列表增加只读云 云环境的展示
  src/utils/common/hypervisor.js
Labels: size/XS

#3322 Automated cherry pick of #3320: fix: #8516 资源列表增加只读云 云环境的展示
  src/utils/common/hypervisor.js
Labels: size/XS

#3328 feat: 增加翻译
  src/locales/en.json
  src/locales/zh-CN.json
  src/styles/less/global.less
Labels: size/S

#3330 fix: #8510 使用率图表展示<1%比例优化
  containers/Dashboard/extends/Ring/components/K8s.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  src/components/LiquidFill/index.vue
Labels: size/M, area/dashboard

#3332 Automated cherry pick of #3330: fix: #8510 使用率图表展示<1%比例优化
  containers/Dashboard/extends/Ring/components/K8s.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  src/components/LiquidFill/index.vue
Labels: size/M

#3333 feat: #3898 列表标签过滤默认展示 未归集
  containers/DB/views/rds/components/List.vue
  containers/Network/views/lb/components/List.vue
  containers/Storage/views/bucket/components/List.vue
  src/components/PageList/index.vue
Labels: size/M

#3334 Automated cherry pick of #3333: feat: #3898 列表标签过滤默认展示 未归集
  containers/DB/views/rds/components/List.vue
  containers/Network/views/lb/components/List.vue
  containers/Storage/views/bucket/components/List.vue
  src/components/PageList/index.vue
Labels: size/M

#3335 feat: #3751 文档链接可以自定义
  src/permission.js
  src/sections/Navbar/components/MorePopover.vue
Labels: size/XS

#3336 Automated cherry pick of #3335: feat: #3751 文档链接可以自定义
  src/permission.js
  src/sections/Navbar/components/MorePopover.vue
Labels: size/XS

#3337 Automated cherry pick of #3335: feat: #3751 文档链接可以自定义
  src/permission.js
  src/sections/Navbar/components/MorePopover.vue
Labels: size/XS

#3338 fix: fix import error
  containers/Dashboard/extends/Ring/components/K8s.vue
Labels: size/XS

#3339 fix: #8521 虚拟机/宿主机详情页名称修改校验
  containers/Compute/views/host/sidepage/Detail.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: area/compute, size/XS

#3341 fix(k8s): add machine error
  containers/K8S/views/kube-machines/dialogs/CreateKubemachinesDialog.vue
Labels: size/M

#3343 fix(build): make cherry_pick_pull script work on macos
  scripts/cherry_pick_pull.sh
Labels: size/XS

#3345 feat: #3877 层级标签展示优化(样式)
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/redis/components/List.vue
  src/components/Icon/assets/organization.svg
  src/sections/TreeProject/index.vue
  src/styles/less/global.less
Labels: size/M

#3346 Automated cherry pick of #3345: feat: #3877 层级标签展示优化(样式)
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/redis/components/List.vue
  src/components/Icon/assets/organization.svg
  src/sections/TreeProject/index.vue
  src/styles/less/global.less
Labels: size/M

#3350 feat: #3902 RDS实例监控azure平台的SQLServer数据增加group_by参数
  containers/DB/views/rds/sidepage/Monitor.vue
Labels: area/db, size/S

#3351 Automated cherry pick of #3350: feat: #3902 RDS实例监控azure平台的SQLServer数据增加group_by参数
  containers/DB/views/rds/sidepage/Monitor.vue
Labels: size/S

#3352 feat: #3902 阿里/飞天 虚拟机磁盘使用率增加groupBy: device
  containers/Compute/views/vminstance/sidepage/Monitor.vue
Labels: area/compute, size/S

#3353 Automated cherry pick of #3352: feat: #3902 阿里/飞天 虚拟机磁盘使用率增加groupBy: device
  containers/Compute/views/vminstance/sidepage/Monitor.vue
Labels: size/S

#3354 feat: #3902 rds 监控优化
  containers/DB/views/rds/sidepage/Monitor.vue
  src/sections/Monitor/index.vue
Labels: size/S

#3355 Automated cherry pick of #3354: feat: #3902 rds 监控优化
  containers/DB/views/rds/sidepage/Monitor.vue
  src/sections/Monitor/index.vue
Labels: size/S

#3358 Automated cherry pick of #3356: fix: #8523 RDS监控数据增加数据库引擎过滤
  containers/DB/views/rds/sidepage/Monitor.vue
Labels: size/S

#3357 Automated cherry pick of #3356: fix: #8523 RDS监控数据增加数据库引擎过滤
  containers/DB/views/rds/sidepage/Monitor.vue
Labels: size/S

#3356 fix: #8523 RDS监控数据增加数据库引擎过滤
  containers/DB/views/rds/sidepage/Monitor.vue
Labels: area/db, size/S

#3360 feature: sms auth
  containers/IAM/views/contact/dialogs/Create.vue
  containers/IAM/views/contact/dialogs/Update.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Auth/Login/components/LoginMobile.vue
  src/sections/Auth/Login/index.vue
  src/store/modules/auth.js
Labels: size/L

#3361 Automated cherry pick of #3360: feature: sms auth
  containers/IAM/views/contact/dialogs/Create.vue
  containers/IAM/views/contact/dialogs/Update.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Auth/Login/components/LoginMobile.vue
  src/sections/Auth/Login/index.vue
  src/store/modules/auth.js
Labels: size/L

#3362 feat: #3856 kvm主机增加远程连接信息展示
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/VncInfo.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/M, area/compute

#3363 feat: #3905 手机号登录UI交互改进
  src/sections/Auth/Login/components/LoginMobile.vue
  src/sections/Auth/Login/index.vue
  src/store/modules/auth.js
  src/utils/auth.js
Labels: size/M

#3366 Automated cherry pick of #3363: feat: #3905 手机号登录UI交互改进
  src/sections/Auth/Login/components/LoginMobile.vue
  src/sections/Auth/Login/index.vue
  src/store/modules/auth.js
  src/utils/auth.js
Labels: size/M

#3371 feat: #3856 vnc信息展示优化
  containers/Compute/views/vminstance/dialogs/VncInfo.vue
Labels: area/compute, size/XS

#3377 feat: 资源状态统计增加统计资源白名单
  src/constants/statisticsRes.js
  src/mixins/list.js
Labels: size/M

#3375 feat: #3856 虚拟机远程连接信息展示优化
  containers/Compute/sections/VncInfoFetcher/index.vue
  containers/Compute/views/vminstance/dialogs/VncInfo.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  src/components/PageList/Actions/ActionButton.vue
Labels: size/L

#3376 Automated cherry pick of #3375: feat: #3856 虚拟机远程连接信息展示优化
  containers/Compute/sections/VncInfoFetcher/index.vue
  containers/Compute/views/vminstance/dialogs/VncInfo.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  src/components/PageList/Actions/ActionButton.vue
Labels: size/L

#3379 feat: #3910 增加中标麒麟图标
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/views/image/dialogs/EditAttributes.vue
  src/components/ImageIcon/assets/neokylin.png
  src/components/ImageIcon/constants.js
  src/components/ImageIcon/index.vue
Labels: size/S

#3380 Automated cherry pick of #3379: feat: #3910 增加中标麒麟图标
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/views/image/dialogs/EditAttributes.vue
  src/components/ImageIcon/assets/neokylin.png
  src/components/ImageIcon/constants.js
  src/components/ImageIcon/index.vue
Labels: size/S

#3381 fix: top5 time error
  containers/Dashboard/extends/Top5/index.vue
Labels: size/S

#3382 Automated cherry pick of #3381: fix: top5 time error
  containers/Dashboard/extends/Top5/index.vue
Labels: size/S

#3383 Automated cherry pick of #3381: fix: top5 time error
  containers/Dashboard/extends/Top5/index.vue
Labels: size/S

#3384 fix: top5 time init error
  containers/Dashboard/extends/Top5/index.vue
Labels: size/XS

#3385 Automated cherry pick of #3384: fix: top5 time init error
  containers/Dashboard/extends/Top5/index.vue
Labels: size/XS

#3386 Automated cherry pick of #3384: fix: top5 time init error
  containers/Dashboard/extends/Top5/index.vue
Labels: size/XS

#3387 fix: 手机号验证码发送提示信息优化及禁用控制
  src/locales/help-en.js
  src/locales/help-zh-CN.js
  src/sections/Auth/Login/components/LoginMobile.vue
  src/utils/error.js
  src/utils/http.js
Labels: size/S

#3388 Automated cherry pick of #3387: fix: 手机号验证码发送提示信息优化及禁用控制
  src/locales/help-en.js
  src/locales/help-zh-CN.js
  src/sections/Auth/Login/components/LoginMobile.vue
  src/utils/error.js
  src/utils/http.js
Labels: size/S

#3391 fix: start count enable
  src/sections/Auth/Login/components/LoginMobile.vue
Labels: size/XS
