Repository yunionio/dashboard, pull requests merged in 2022-04, with the labels that each got.

#2538 feat: #3654 调整配置，数据盘支持指定存储
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/M

#2539 Automated cherry pick of #2538: feat: #3654 调整配置，数据盘支持指定存储
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/M

#2541 fix: #8334 定时任务-活动历史api接口应该用v1版本
  containers/Cloudenv/views/scheduledtask/sidepage/TaskHistory.vue
Labels: size/XS

#2543 fix: #8319 硬盘备份应该也加上强制删除的选项
  containers/Compute/views/disk-backup/components/List.vue
  containers/Compute/views/disk-backup/mixins/singleActions.js
  containers/Compute/views/instance-backup/mixins/singleActions.js
Labels: size/S

#2544 Automated cherry pick of #2543: fix: #8319 硬盘备份应该也加上强制删除的选项
  containers/Compute/views/disk-backup/components/List.vue
  containers/Compute/views/disk-backup/mixins/singleActions.js
  containers/Compute/views/instance-backup/mixins/singleActions.js
Labels: size/S

#2545 fix: #8306 已经被占用的需置灰禁止选择
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/BindPhysicalCpu.vue
Labels: size/S

#2547 feat: #3712 权限支持详细配置
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/Item.vue
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/components/PolicyViewer/Group.vue
  containers/IAM/views/policy/constants.js
  containers/IAM/views/policy/dialogs/ActionConfig.vue
Labels: size/L

#2548 Automated cherry pick of #2547: feat: #3712 权限支持详细配置
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/Item.vue
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/components/PolicyViewer/Group.vue
  containers/IAM/views/policy/constants.js
  containers/IAM/views/policy/dialogs/ActionConfig.vue
Labels: size/L

#2549 fix: #8337 网络拓扑重复的没有置灰
  containers/Network/views/vpc/components/ResTopology/Vpc/index.vue
Labels: size/XS

#2550 Automated cherry pick of #2549: fix: #8337 网络拓扑重复的没有置灰
  containers/Network/views/vpc/components/ResTopology/Vpc/index.vue
Labels: size/XS

#2551 fix: #8274 公有云硬盘更多操作中 新建备份 按钮应该禁用
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/XS

#2553 fix: isArm should use aarch64 not arm
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/XS

#2556 Automated cherry pick of #2553: fix: isArm should use aarch64 not arm
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/XS

#2555 Automated cherry pick of #2553: fix: isArm should use aarch64 not arm
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/XS

#2554 Automated cherry pick of #2553: fix: isArm should use aarch64 not arm
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/XS

#2557 fix: #8271 GPSSD没有翻译中文
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  src/constants/compute.js
Labels: size/S

#2558 Automated cherry pick of #2557: fix: #8271 GPSSD没有翻译中文
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  src/constants/compute.js
Labels: size/S

#2559 fix: support event log severity and kind
  containers/Compute/views/vminstance/components/List.vue
  src/components/Status/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/EventList/index.vue
Labels: size/S

#2560 Automated cherry pick of #2559: fix: support event log severity and kind
  containers/Compute/views/vminstance/components/List.vue
  src/components/Status/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/EventList/index.vue
Labels: size/S

#2561 feat: #3722 云账号展示缺失权限
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: size/M

#2562 Automated cherry pick of #2561: feat: #3722 云账号展示缺失权限
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: size/M

#2563 Automated cherry pick of #2561: feat: #3722 云账号展示缺失权限
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: size/M

#2564 fix: #8276 新建公有云账号时，资源归属项目和代理不应该显示为空
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: size/S

#2565 Automated cherry pick of #2564: fix: #8276 新建公有云账号时，资源归属项目和代理不应该显示为空
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: size/S

#2566 feat: 扩展 表格同一列支持多个字段排序
  containers/Compute/views/host/mixins/columns.js
  src/components/PageList/components/MultipleSort.vue
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: area/compute, size/L

#2567 Automated cherry pick of #2566: feat: 扩展 表格同一列支持多个字段排序
  containers/Compute/views/host/mixins/columns.js
  src/components/PageList/components/MultipleSort.vue
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#2568 fix: backupstorage add permission
  src/constants/permission.js
Labels: size/S

#2569 Automated cherry pick of #2568: fix: backupstorage add permission
  src/constants/permission.js
Labels: size/S

#2570 Automated cherry pick of #2566: feat: 扩展 表格同一列支持多个字段排序
  containers/Compute/views/host/mixins/columns.js
  src/components/PageList/components/MultipleSort.vue
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#2572 fix: #8291 新建OpenStack、DStack、ZStack、飞天、CloudPods和HCSO云账号时应该去掉 配置同步资源…
  containers/Cloudenv/views/cloudaccount/constants.js
Labels: size/XS

#2573 Automated cherry pick of #2572: fix: #8291 新建OpenStack、DStack、ZStack、飞天、CloudPods和HCSO云账号时应该去掉 配置同步资源区域的操作
  containers/Cloudenv/views/cloudaccount/constants.js
Labels: size/XS

#2571 fix: server attributes default options
  containers/Compute/sections/BIOS/index.vue
  containers/Compute/sections/Machine/index.vue
  containers/Compute/sections/VDI/index.vue
  containers/Compute/sections/VGA/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/M

#2575 fix: #8344 保存api_server时候，需要注意去掉最后的slash
  src/sections/TopAlert/index.js
Labels: size/XS

#2576 Automated cherry pick of #2575: fix: #8344 保存api_server时候，需要注意去掉最后的slash
  src/sections/TopAlert/index.js
Labels: size/XS

#2577 Automated cherry pick of #2575: fix: #8344 保存api_server时候，需要注意去掉最后的slash
  src/sections/TopAlert/index.js
Labels: size/XS

#2574 Automated cherry pick of #2571: fix: server attributes default options
  containers/Compute/sections/BIOS/index.vue
  containers/Compute/sections/Machine/index.vue
  containers/Compute/sections/VDI/index.vue
  containers/Compute/sections/VGA/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/M

#2579 Automated cherry pick of #2578: fix: #8340 logout cloudshell open
  src/components/OcTerm/index.vue
Labels: size/XS

#2581 Automated cherry pick of #2578: fix: #8340 logout cloudshell open
  src/components/OcTerm/index.vue
Labels: size/XS

#2580 Automated cherry pick of #2578: fix: #8340 logout cloudshell open
  src/components/OcTerm/index.vue
Labels: size/XS

#2584 fix: set first disk driver of ide for windows only
  containers/Compute/utils/createServer.js
Labels: size/S

#2583 Automated cherry pick of #2582: fix: allow encrypt with new key
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/encryptkeys/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/Compute/views/host-image/sidepage/Detail.vue
  containers/Compute/views/image/dialogs/Upload.vue
  containers/Compute/views/image/sidepage/Detail.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/L

#2582 fix: allow encrypt with new key
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/encryptkeys/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/Compute/views/host-image/sidepage/Detail.vue
  containers/Compute/views/image/dialogs/Upload.vue
  containers/Compute/views/image/sidepage/Detail.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/L

#2585 fix: allow create key with resource
  containers/Compute/sections/encryptkeys/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/image/dialogs/Upload.vue
Labels: size/M

#2587 feat: 增加无权限提示框
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/NoPermission.vue
Labels: size/M

#2588 feat: 增加无权限提示框
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/NoPermission.vue
Labels: size/M

#2589 fix: #3735 当虚拟机状态为失败时，增加查看日志的快捷入口
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/vminstance/sidepage/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#2590 Automated cherry pick of #2589: fix: #3735 当虚拟机状态为失败时，增加查看日志的快捷入口
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/vminstance/sidepage/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#2591 Automated cherry pick of #2589: fix: #3735 当虚拟机状态为失败时，增加查看日志的快捷入口
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/vminstance/sidepage/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#2592 fix: #8348 更改密码验证新旧密码一致性
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/UpdateUserPassword.vue
Labels: size/S

#2593 fix: #8348 更改密码验证新旧密码一致性
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/UpdateUserPassword.vue
Labels: size/S

#2594 fix: #8348 更改密码验证新旧密码一致性
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/UpdateUserPassword.vue
Labels: size/S

#2595 feat: #3647 虚拟机磁铁优化
  containers/Dashboard/extends/ServerNumberDetail/index.vue
Labels: size/S

#2597 fix: #8350 IP子网页面直接输入ID，匹配到IP报错了
  src/components/SearchBox/index.vue
Labels: size/XS

#2598 Automated cherry pick of #2597: fix: #8350 IP子网页面直接输入ID，匹配到IP报错了
  src/components/SearchBox/index.vue
Labels: size/XS

#2601 feat: #3695 消息订阅添加翻译
  containers/IAM/constants/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#2602 Automated cherry pick of #2601: feat: #3695 消息订阅添加翻译
  containers/IAM/constants/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#2599 fix: #8338 虚拟机增加命令行展示,块存储-共享存储增加配置信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Storage/views/blockstorage/sidepage/Detail.vue
Labels: size/M, area/compute

#2600 fix: #8338 虚拟机增加命令行展示,块存储-共享存储增加配置信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Storage/views/blockstorage/sidepage/Detail.vue
Labels: size/M

#2608 feat: #3719 安全告警优化
  containers/IAM/views/notification/components/List.vue
  containers/IAM/views/security-alerts/components/List.vue
Labels: size/M

#2609 Automated cherry pick of #2608: feat: #3719 安全告警优化
  containers/IAM/views/notification/components/List.vue
  containers/IAM/views/security-alerts/components/List.vue
Labels: size/M

#2603 fix: #8343 文案优化
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/group/mixins/singleActions.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#2604 fix: #8343 文案优化
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/group/mixins/singleActions.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#2605 fix: #8343 文案优化
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/group/mixins/singleActions.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#2606 fix: 虚拟机qemu cmdline为空时隐藏
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: area/compute, size/XS

#2607 fix: 虚拟机qemu cmdline为空时隐藏
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#2610 create encrypt key with specific user id
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk-backup/mixins/columns.js
  containers/Compute/views/disk-backup/sidepage/Detail.vue
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/Compute/views/host-image/sidepage/Detail.vue
  containers/Compute/views/image/dialogs/Upload.vue
  containers/Compute/views/image/sidepage/Detail.vue
  containers/Compute/views/instance-backup/mixins/columns.js
  containers/Compute/views/instance-backup/sidepage/Detail.vue
  containers/Compute/views/snapshot-instance/mixins/columns.js
  containers/Compute/views/snapshot-instance/sidepage/Detail.vue
  containers/Compute/views/snapshot/mixins/columns.js
  containers/Compute/views/snapshot/sidepage/Detail.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/L

#2611 Automated cherry pick of #2610: create encrypt key with specific user id
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk-backup/mixins/columns.js
  containers/Compute/views/disk-backup/sidepage/Detail.vue
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/Compute/views/host-image/sidepage/Detail.vue
  containers/Compute/views/image/dialogs/Upload.vue
  containers/Compute/views/image/sidepage/Detail.vue
  containers/Compute/views/instance-backup/mixins/columns.js
  containers/Compute/views/instance-backup/sidepage/Detail.vue
  containers/Compute/views/snapshot-instance/mixins/columns.js
  containers/Compute/views/snapshot-instance/sidepage/Detail.vue
  containers/Compute/views/snapshot/mixins/columns.js
  containers/Compute/views/snapshot/sidepage/Detail.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/L

#2615 feat: #3469 云账号新增权限控制--新增只读模式
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/ReadOnly.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/dialogs/SetReadOnly.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: size/L

#2612 fix: #8344 保存api_server时候，需要注意去掉最后的slash
  src/sections/TopAlert/index.js
Labels: size/S

#2613 Automated cherry pick of #2612: fix: #8344 保存api_server时候，需要注意去掉最后的slash
  src/sections/TopAlert/index.js
Labels: size/S

#2614 Automated cherry pick of #2612: fix: #8344 保存api_server时候，需要注意去掉最后的slash
  src/sections/TopAlert/index.js
Labels: size/S

#2616 Automated cherry pick of #2615: feat: #3469 云账号新增权限控制--新增只读模式
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/ReadOnly.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/dialogs/SetReadOnly.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: size/L

#2617 feat: update notify params
  containers/IAM/views/security-alerts/components/List.vue
Labels: size/XS

#2618 Automated cherry pick of #2617: feat: update notify params
  containers/IAM/views/security-alerts/components/List.vue
Labels: size/XS

#2621 feat: #3469 云账号只读模式支持批量及权限控制
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/S

#2622 Automated cherry pick of #2621: feat: #3469 云账号只读模式支持批量及权限控制
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/S

#2619 feat: #3579 页面允许缓存
  src/layouts/RouterView/index.vue
Labels: size/S

#2620 feat: #3579 页面允许缓存
  src/layouts/RouterView/index.vue
Labels: size/S

#2623 feat: #3705 宿主机内存/存储/cpu等支持使用率排序
  containers/Compute/views/host/mixins/columns.js
  src/components/PageList/components/MultipleSort.vue
Labels: size/M, area/compute

#2624 feat: #3705 宿主机内存/存储/cpu等支持使用率排序
  containers/Compute/views/host/mixins/columns.js
  src/components/PageList/components/MultipleSort.vue
Labels: size/M

#2625 feat: #3705 宿主机内存/存储/cpu等支持使用率排序
  containers/Compute/views/host/mixins/columns.js
  src/components/PageList/components/MultipleSort.vue
Labels: size/M

#2626 feat: 增加站内信消息类型
  containers/IAM/views/notification/components/List.vue
Labels: size/M

#2627 Automated cherry pick of #2626: feat: 增加站内信消息类型
  containers/IAM/views/notification/components/List.vue
Labels: size/M

#2630 fix: 域新建增加权限控制
  containers/IAM/views/domains/components/List.vue
  src/constants/permission.js
Labels: size/XS

#2628 fix: 域新建增加权限控制
  containers/IAM/views/domains/components/List.vue
  src/constants/permission.js
Labels: size/XS

#2629 fix: 域新建增加权限控制
  containers/IAM/views/domains/components/List.vue
  src/constants/permission.js
Labels: size/XS

#2633 fix: #8342 选择窗不应该根据选择的多少移动位置
  src/components/SearchBox/AutoCompleter.vue
  src/components/SearchBox/index.vue
Labels: size/XS

#2634 Automated cherry pick of #2633: fix: #8342 选择窗不应该根据选择的多少移动位置
  src/components/SearchBox/AutoCompleter.vue
  src/components/SearchBox/index.vue
Labels: size/XS

#2635 Automated cherry pick of #2633: fix: #8342 选择窗不应该根据选择的多少移动位置
  src/components/SearchBox/AutoCompleter.vue
  src/components/SearchBox/index.vue
Labels: size/XS

#2636 Automated cherry pick of #2633: fix: #8342 选择窗不应该根据选择的多少移动位置
  src/components/SearchBox/AutoCompleter.vue
  src/components/SearchBox/index.vue
Labels: size/XS

#2631 fix: schedtag default none strategy
  containers/Cloudenv/views/schedtag/dialogs/Create.vue
Labels: size/XS

#2632 Automated cherry pick of #2631: fix: schedtag default none strategy
  containers/Cloudenv/views/schedtag/dialogs/Create.vue
Labels: size/XS

#2637 feat: #3705 迁移支持内存、存储和CPU及使用率的排序
  containers/Compute/views/vminstance/mixins/resourceProps.js
Labels: size/XS

#2638 Automated cherry pick of #2637: feat: #3705 迁移支持内存、存储和CPU及使用率的排序
  containers/Compute/views/vminstance/mixins/resourceProps.js
Labels: size/XS

#2639 Automated cherry pick of #2637: feat: #3705 迁移支持内存、存储和CPU及使用率的排序
  containers/Compute/views/vminstance/mixins/resourceProps.js
Labels: size/XS

#2640 fix: wrong sys disk size if multiple sys disks attached
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#2641 Automated cherry pick of #2640: fix: wrong sys disk size if multiple sys disks attached
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#2642 Automated cherry pick of #2640: fix: wrong sys disk size if multiple sys disks attached
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#2643 fix: create key with specified alg
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/image/dialogs/Upload.vue
Labels: size/S

#2645 fix: #8354 采集账单时间精确到月
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
Labels: size/M, area/cloudenv

#2646 fix: #8354 采集账单时间精确到月
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
Labels: size/M

#2647 fix: #8359 标签增加对cloud_default的翻译
  src/sections/TagSelect/index.vue
  src/utils/common/tag.js
Labels: size/S

#2648 fix: #8359 标签增加对cloud_default的翻译
  src/sections/TagSelect/index.vue
  src/utils/common/tag.js
Labels: size/S

#2651 feat: #3693 云账号同步资源翻译映射
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/M

#2652 feat: #3693 云账号同步资源翻译映射
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/M

#2653 fix: encrypt algorithm value
  containers/Compute/sections/encryptkeys/index.vue
Labels: size/XS

#2657 fix: log shows user's owner events
  containers/Dashboard/extends/BillHistoryLine/index.vue
  containers/Dashboard/extends/ConsumptionTrend/index.vue
  containers/Dashboard/extends/Log/index.vue
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsOverview/index.vue
Labels: size/M

#2658 Automated cherry pick of #2657: fix: log shows user's owner events
  containers/Dashboard/extends/BillHistoryLine/index.vue
  containers/Dashboard/extends/ConsumptionTrend/index.vue
  containers/Dashboard/extends/Log/index.vue
  containers/Dashboard/extends/SuggestsysAlertsDetail/index.vue
  containers/Dashboard/extends/SuggestsysAlertsOverview/index.vue
Labels: size/M

#2660 fix: guest detach disk
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/S

#2662 Automated cherry pick of #2660: fix: guest detach disk
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/S

#2661 Automated cherry pick of #2660: fix: guest detach disk
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/S

#2663 fix: backup status check
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk-backup/mixins/singleActions.js
  containers/Compute/views/instance-backup/mixins/singleActions.js
  containers/Compute/views/vminstance/dialogs/BackupCreate.vue
Labels: size/S

#2664 Automated cherry pick of #2663: fix: backup status check
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk-backup/mixins/singleActions.js
  containers/Compute/views/instance-backup/mixins/singleActions.js
  containers/Compute/views/vminstance/dialogs/BackupCreate.vue
Labels: size/S

#2665 feat: #3672 增加翻译
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2666 Automated cherry pick of #2665: feat: #3672 增加翻译
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#2669 feat: #3742 定时任务有效时间非必填
  containers/Cloudenv/views/cloudaccount/dialogs/ScheduledtaskCreate.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
Labels: area/helm, size/S

#2670 Automated cherry pick of #2669: feat: #3742 定时任务有效时间非必填
  containers/Cloudenv/views/cloudaccount/dialogs/ScheduledtaskCreate.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
Labels: size/S

#2667 feat: #3716 云上项目支持新建及名称修改
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/externalproject/dialogs/Create.vue
  src/constants/permission.js
Labels: area/cloudenv, size/L

#2668 Automated cherry pick of #2667: feat: #3716 云上项目支持新建及名称修改
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/externalproject/dialogs/Create.vue
  src/constants/permission.js
Labels: size/L

#2671 fix: remove useless endpoint for apsara
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
Labels: size/M

#2672 Automated cherry pick of #2671: fix: remove useless endpoint for apsara
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
Labels: size/M

#2673 fix: #14104 public禁用云账号删除同时删除账单
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#2674 Automated cherry pick of #2673: fix: #14104 public禁用云账号删除同时删除账单
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#2675 Automated cherry pick of #2673: fix: #14104 public禁用云账号删除同时删除账单
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#2676 fix: 安全组操作权限优化
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/mixins/columns.js
  containers/Compute/views/secgroup/mixins/singleActions.js
  src/constants/permission.js
Labels: area/compute, size/S

#2677 Automated cherry pick of #2676: fix: 安全组操作权限优化
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/mixins/columns.js
  containers/Compute/views/secgroup/mixins/singleActions.js
  src/constants/permission.js
Labels: size/S

#2678 Automated cherry pick of #2676: fix: 安全组操作权限优化
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/mixins/columns.js
  containers/Compute/views/secgroup/mixins/singleActions.js
  src/constants/permission.js
Labels: size/S

#2679 feat: #3743 ssh连接增加type参数
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#2680 Automated cherry pick of #2679: feat: #3743 ssh连接增加type参数
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#2681 feat: 增加一些方法注释
  src/utils/utils.js
Labels: size/M

#2682 Automated cherry pick of #2681: feat: 增加一些方法注释
  src/utils/utils.js
Labels: size/M

#2687 feat: #3738 新增ipv6网关
  containers/Network/router/index.js
  src/constants/expectStatus.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M, area/network

#2688 Automated cherry pick of #2687: feat: #3738 新增ipv6网关
  containers/Network/router/index.js
  src/constants/expectStatus.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#2689 fix: #8376 增加管理安全组展示
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/sidepage/Detail.vue
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/S

#2690 Automated cherry pick of #2689: fix: #8376 增加管理安全组展示
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/sidepage/Detail.vue
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/S

#2691 fix: #8378 修正创建告警策略,告警接收人提示文案
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: size/XS

#2692 Automated cherry pick of #2691: fix: #8378 修正创建告警策略,告警接收人提示文案
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: size/XS

#2693 Automated cherry pick of #2691: fix: #8378 修正创建告警策略,告警接收人提示文案
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: size/XS

#2694 fix: #8374 指定调度标签时，偏好不与调度标签的默认偏好联动
  containers/Compute/sections/Disk/index.vue
  containers/Compute/sections/SchedPolicy/PolicySchedtag.vue
  containers/Compute/sections/ServerNetwork/NetworkSchedtag.vue
  src/sections/SchedtagPolicy/index.vue
Labels: area/compute, size/S

#2695 Automated cherry pick of #2694: fix: #8374 指定调度标签时，偏好不与调度标签的默认偏好联动
  containers/Compute/sections/Disk/index.vue
  containers/Compute/sections/SchedPolicy/PolicySchedtag.vue
  containers/Compute/sections/ServerNetwork/NetworkSchedtag.vue
  src/sections/SchedtagPolicy/index.vue
Labels: size/S

#2696 Automated cherry pick of #2689: fix: #8376 增加管理安全组展示
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/secgroup/sidepage/Detail.vue
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/S
