Repository yunionio/dashboard, pull requests merged in 2022-10, with the labels that each got.

#3531 fix: #8594 新建虚拟机，平台信息需根据计费方式来刷新
  src/sections/AreaSelects/index.js
Labels: size/XS

#3532 Automated cherry pick of #3531: fix: #8594 新建虚拟机，平台信息需根据计费方式来刷新
  src/sections/AreaSelects/index.js
Labels: size/XS

#3533 fix: remove usable for cloudgroup
  containers/Cloudenv/views/cloudgroup/components/List.vue
Labels: size/XS

#3534 Automated cherry pick of #3533: fix: remove usable for cloudgroup
  containers/Cloudenv/views/cloudgroup/components/List.vue
Labels: size/XS

#3535 feat: 框架过滤扩展
  src/utils/common/tableFilter.js
  src/utils/list.js
Labels: size/S

#3536 Automated cherry pick of #3535: feat: 框架过滤扩展
  src/utils/common/tableFilter.js
  src/utils/list.js
Labels: size/S

#3537 feat: #3955 windows支持安装agent优化
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
Labels: size/M

#3538 Automated cherry pick of #3537: feat: #3955 windows支持安装agent优化
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
Labels: size/M

#3539 fix: #8594 公有云获取套餐时，计费方式要根据选择来，只能是按量付费或包年包月
  containers/Compute/sections/SKU/index.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/XS

#3540 Automated cherry pick of #3539: fix: #8594 公有云获取套餐时，计费方式要根据选择来，只能是按量付费或包年包月
  containers/Compute/sections/SKU/index.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/XS

#3541 fix: cdrom substring error
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#3542 Automated cherry pick of #3541: fix: cdrom substring error
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#3544 Automated cherry pick of #3543: fix: #8578 云订阅新建条件优化
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudprovider/components/List.vue
Labels: size/XS

#3545 Automated cherry pick of #3543: fix: #8578 云订阅新建条件优化
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudprovider/components/List.vue
Labels: size/XS

#3546 feat: #3965 steps组件兼容小屏
  src/components/Steps/index.vue
  src/styles/less/global.less
Labels: area/cloudenv, size/S

#3547 Automated cherry pick of #3546: feat: #3965 steps组件兼容小屏
  src/components/Steps/index.vue
  src/styles/less/global.less
Labels: size/S

#3548 Automated cherry pick of #3546: feat: #3965 steps组件兼容小屏
  src/components/Steps/index.vue
  src/styles/less/global.less
Labels: size/S

#3550 fix: #8575 监控策略监控时间优化
  containers/Monitor/views/commonalert/components/alert/index.vue
Labels: area/monitor, size/S

#3551 Automated cherry pick of #3550: fix: #8575 监控策略监控时间优化
  containers/Monitor/views/commonalert/components/alert/index.vue
Labels: size/S

#3552 Automated cherry pick of #3550: fix: #8575 监控策略监控时间优化
  containers/Monitor/views/commonalert/components/alert/index.vue
Labels: size/S

#3553 fix: #8573 主机调整配置 异步请求顺序问题导致加载异常
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: area/compute, size/S

#3554 Automated cherry pick of #3553: fix: #8573 主机调整配置 异步请求顺序问题导致加载异常
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/S

#3555 Automated cherry pick of #3553: fix: #8573 主机调整配置 异步请求顺序问题导致加载异常
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/S

#3559 fix: login error i18n
  src/constants/error.js
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/XS

#3556 fix: #8548 云用户切换本地用户选择框联动失效问题
  containers/Cloudenv/views/clouduser/components/UserSelect.vue
Labels: area/cloudenv, size/XS

#3557 Automated cherry pick of #3556: fix: #8548 云用户切换本地用户选择框联动失效问题
  containers/Cloudenv/views/clouduser/components/UserSelect.vue
Labels: size/XS

#3558 Automated cherry pick of #3556: fix: #8548 云用户切换本地用户选择框联动失效问题
  containers/Cloudenv/views/clouduser/components/UserSelect.vue
Labels: size/XS

#3561 [WIP]feat: hcs support
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCS.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/server-price-comparator/create/form/Private.vue
  containers/Compute/constants/index.js
  containers/Compute/sections/SchedPolicy/index.vue
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/disk/utils/index.js
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Compute/views/vminstance/utils.js
  containers/DB/constants/index.js
  containers/DB/router/index.js
  containers/DB/sections/ItemArea.vue
  containers/DB/views/rds/sidepage/Monitor.vue
  containers/Helm/router/index.js
  containers/Monitor/router/index.js
  containers/Network/router/index.js
  containers/Network/views/eip/create/components/BottomBar.vue
  containers/Network/views/eip/create/index.vue
  containers/Network/views/lb/create/form/Private.vue
  containers/Network/views/lb/create/form/mixin.js
  containers/Network/views/loadbalancerlistener/constants.js
  containers/Network/views/loadbalancerlistener/dialogs/Form.vue
  containers/Network/views/network/Create.vue
  containers/Network/views/vpc/create/index.vue
  containers/Storage/router/index.js
  scope/locales/en.json
  scope/locales/zh-CN.json
  src/assets/images/providers/hcs.svg
  src/constants/compute.js
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
  yarn.lock
Labels: size/XXL, do-not-merge/work-in-progress

#3564 feat: add login error i18n
  src/constants/error.js
  src/locales/help-zh-CN.js
  src/utils/error.js
Labels: size/XS

#3565 Automated cherry pick of #3564: feat: add login error i18n
  src/constants/error.js
  src/locales/help-zh-CN.js
  src/utils/error.js
Labels: size/S

#3567 Automated cherry pick of #3566: fix: skip duplicate account check
  .gitignore
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/SkipDuplicateAccountCheck.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
  yarn.lock
Labels: size/XXL

#3568 feat: 应用市场套餐请求增加分页
  src/components/JsonSchemaForm/JComponents/JSKUList/JSKUList.vue
Labels: area/helm, size/XS

#3569 Automated cherry pick of #3568: feat: 应用市场套餐请求增加分页
  src/components/JsonSchemaForm/JComponents/JSKUList/JSKUList.vue
Labels: size/XS

#3573 fix: #8603 openstack虚拟机 vnc连接时 请求参数加上origin=true
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/XS

#3571 feat: 列表扩展
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
Labels: size/XS

#3572 Automated cherry pick of #3571: feat: 列表扩展
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
Labels: size/XS

#3575 fix: vnc params
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/XS

#3576 Automated cherry pick of #3575: fix: vnc params
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/XS

#3577 Automated cherry pick of #3562: feat: update transfer
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/MigrationBandwidth/index.vue
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/dialogs/VmLiveMigrateCancel.vue
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/L

#3578 Automated cherry pick of #3254: feat: #3848 本地盘支持新建硬盘并指定虚拟机
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/create/components/HostServer.vue
  containers/Compute/views/disk/create/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#3579 feat: add aksk
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/clouduser/dialogs/AkSkCreate.vue
  containers/Cloudenv/views/clouduser/sidepage/AkSkList.vue
  containers/Cloudenv/views/clouduser/sidepage/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/views/clouduser/components/ClouduserList.vue
Labels: size/L

#3580 Automated cherry pick of #3579: feat: add aksk
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/clouduser/dialogs/AkSkCreate.vue
  containers/Cloudenv/views/clouduser/sidepage/AkSkList.vue
  containers/Cloudenv/views/clouduser/sidepage/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/views/clouduser/components/ClouduserList.vue
Labels: size/L

#3581 feature: mark disk as ssd or hdd
  containers/Compute/views/disk/dialogs/DriverUpdateDialog.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/mixins/singleActions.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#3582 Automated cherry pick of #3581: feature: mark disk as ssd or hdd
  containers/Compute/views/disk/dialogs/DriverUpdateDialog.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/mixins/singleActions.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#3583 Automated cherry pick of #3581: feature: mark disk as ssd or hdd
  containers/Compute/views/disk/dialogs/DriverUpdateDialog.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/mixins/singleActions.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#3584 feat: update transfer extra
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/S

#3585 Automated cherry pick of #3584: feat: update transfer extra
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/S

#3588 Automated cherry pick of #3587: feat: modelarts sku order asc
  containers/Compute/views/modelarts/create/index.vue
Labels: size/XS

#3589 feat: #3831 去除列表页底部白条 优化
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Network/views/network/Create.vue
  containers/Network/views/network/EditAttributes.vue
  containers/Storage/views/bucket/components/SetStaticWebsit.vue
Labels: size/XS

#3590 Automated cherry pick of #3589: feat: #3831 去除列表页底部白条 优化
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Network/views/network/Create.vue
  containers/Network/views/network/EditAttributes.vue
  containers/Storage/views/bucket/components/SetStaticWebsit.vue
Labels: size/XS

#3591 fix: support change config for running incloudsphere vm
  containers/Compute/views/vminstance/utils.js
Labels: size/XS

#3592 hcs logo
  containers/Cloudenv/views/cloudaccount/constants.js
  scope/assets/hcs.svg
  src/assets/images/providers/hcs.svg
  src/components/Icon/assets/hcs.svg
Labels: size/XS

#3594 fix: ip to int
  src/utils/validate.js
Labels: size/M

#3596 feat: 应用市场套餐增加cpu核数排序
  src/components/JsonSchemaForm/JComponents/JSKUList/JSKUList.vue
Labels: size/S

#3597 Automated cherry pick of #3596: feat: 应用市场套餐增加cpu核数排序
  src/components/JsonSchemaForm/JComponents/JSKUList/JSKUList.vue
Labels: size/S

#3595 fix: docker push script
  scripts/docker-push.sh
  scripts/docker_push.sh
  src/utils/validate.js
Labels: size/L

#3598 Automated cherry pick of #3596: feat: 应用市场套餐增加cpu核数排序
  src/components/JsonSchemaForm/JComponents/JSKUList/JSKUList.vue
Labels: size/S

#3599 feat: #3931 增加调度、项目及标签的过滤
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/M

#3600 Automated cherry pick of #3599: feat: #3931 增加调度、项目及标签的过滤
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/M

#3601 feat: #3931 增加调度、项目及标签的过滤
  containers/Dashboard/extends/NumberCard/components/Server.vue
Labels: size/M

#3602 fix: incloudsphere vnc
  containers/Compute/views/vminstance/utils.js
  scripts/docker_push.sh
Labels: size/XS

#3603 fix: login error and hidden notify link
  src/constants/error.js
  src/locales/help-en.js
  src/locales/help-zh-CN.js
  src/utils/error.js
  src/utils/http.js
Labels: size/S

#3604 Automated cherry pick of #3603: fix: login error and hidden notify link
  src/constants/error.js
  src/locales/help-en.js
  src/locales/help-zh-CN.js
  src/utils/error.js
  src/utils/http.js
Labels: size/S

#3605 feat: #3974 增加错误信息查看按钮控制开关
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/utils/http.js
Labels: size/S

#3609 feat: login error transfer user locked
  src/constants/error.js
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/XS

#3610 Automated cherry pick of #3609: feat: login error transfer user locked
  src/constants/error.js
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/XS

#3611 feat: #3972 KVM私有云虚拟机增加power_status的字段
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/M

#3612 feat: #3931 控制面板使用量支持项目标签过滤
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/S

#3615 feat: ModelArts 的UI策略实现
  containers/Compute/router/index.js
Labels: size/XS

#3617 fix: hcs misc fix
  containers/Compute/constants/index.js
  containers/DB/sections/ItemArea.vue
  containers/DB/views/redis/create/components/SKU/components/ItemFilters.vue
  containers/DB/views/utils/index.js
  containers/Storage/views/blockstorage/mixins/singleActions.js
Labels: size/M

#3618 feat: #3984 ModelArt迁移到企业版
  containers/Compute/router/index.js
  containers/Compute/views/modelarts/components/List.vue
  containers/Compute/views/modelarts/constants/index.js
  containers/Compute/views/modelarts/create/index.vue
  containers/Compute/views/modelarts/index.vue
  containers/Compute/views/modelarts/locales/en.json
  containers/Compute/views/modelarts/locales/zh-CN.json
  containers/Compute/views/modelarts/mixins/columns.js
  containers/Compute/views/modelarts/mixins/singleActions.js
  containers/Compute/views/modelarts/sidepage/Detail.vue
  containers/Compute/views/modelarts/sidepage/Monitor.vue
  containers/Compute/views/modelarts/sidepage/index.vue
  containers/Compute/views/modelarts/utils/columns.js
  containers/DB/router/index.js
  containers/Middleware/router/index.js
  src/components/Icon/assets/menu-ai.svg
Labels: size/XXL

#3619 Automated cherry pick of #3618: feat: #3984 ModelArt迁移到企业版
  containers/Compute/router/index.js
  containers/Compute/views/modelarts/components/List.vue
  containers/Compute/views/modelarts/constants/index.js
  containers/Compute/views/modelarts/create/index.vue
  containers/Compute/views/modelarts/index.vue
  containers/Compute/views/modelarts/locales/en.json
  containers/Compute/views/modelarts/locales/zh-CN.json
  containers/Compute/views/modelarts/mixins/columns.js
  containers/Compute/views/modelarts/mixins/singleActions.js
  containers/Compute/views/modelarts/sidepage/Detail.vue
  containers/Compute/views/modelarts/sidepage/Monitor.vue
  containers/Compute/views/modelarts/sidepage/index.vue
  containers/Compute/views/modelarts/utils/columns.js
  containers/DB/router/index.js
  containers/Middleware/router/index.js
  src/components/Icon/assets/menu-ai.svg
Labels: size/XXL

#3622 fix: 内跑工单支持多个审批人
  src/constants/workflow.js
Labels: size/XS

#3623 fix: allow reinstall monitor agent
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Compute/views/vminstance/components/InstallAgentFormVisible.vue
Labels: size/S

#3624 Automated cherry pick of #3623: fix: allow reinstall monitor agent
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Compute/views/vminstance/components/InstallAgentFormVisible.vue
Labels: size/S

#3625 fix: eip bandwidth
  containers/Network/views/eip/mixins/columns.js
Labels: size/XS

#3626 Automated cherry pick of #3625: fix: eip bandwidth
  containers/Network/views/eip/mixins/columns.js
Labels: size/XS

#3628 fix: add monitor url on server details page
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/S

#3629 Automated cherry pick of #3628: fix: add monitor url on server details page
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/S

#3627 feat: #3991 内跑工单展示优化
  src/locales/en.json
  src/locales/zh-CN.json
  src/views/workflow-apply-internal-resource/components/WorkflowTips.vue
  src/views/workflow-apply-internal-resource/components/form/BasicSecurityServices.vue
  src/views/workflow-apply-internal-resource/components/form/CloudSecurityTable.vue
  src/views/workflow-apply-internal-resource/components/form/Ecs.vue
  src/views/workflow-apply-internal-resource/components/form/Rds.vue
  src/views/workflow-apply-internal-resource/components/form/Server.vue
  src/views/workflow-apply-internal-resource/components/form/unitInfo.vue
  src/views/workflow-apply-internal-resource/constants.js
  src/views/workflow-apply-internal-resource/dialogs/AddInfo.vue
  src/views/workflow-apply-internal-resource/index.vue
  src/views/workflow/components/ApplyInternalResource.vue
  src/views/workflow/me-process/mixins/singleActions.js
Labels: size/L
