Repository yunionio/dashboard, pull requests merged in 2023-11, with the labels that each got.

#5604 feat(4607): update list brand icon
  src/components/Icon/assets/jdcloud.svg
Labels: size/XS

#5605 Automated cherry pick of #5604: feat(4607): update list brand icon
  src/components/Icon/assets/jdcloud.svg
Labels: size/XS

#5606 fix(9415): 多云管理菜单权限校验方式更新
  containers/Cloudenv/router/index.js
Labels: size/M

#5607 Automated cherry pick of #5606: fix(9415): 多云管理菜单权限校验方式更新
  containers/Cloudenv/router/index.js
Labels: size/M

#5608 Automated cherry pick of #5606: fix(9415): 多云管理菜单权限校验方式更新
  containers/Cloudenv/router/index.js
Labels: size/M

#5609 fix(9420): 修复 cloudregion按启用平台过滤方式
  containers/Storage/views/bucket/create/index.vue
  src/utils/common/capability.js
Labels: size/S

#5610 Automated cherry pick of #5609: fix(9420): 修复 cloudregion按启用平台过滤方式
  containers/Storage/views/bucket/create/index.vue
  src/utils/common/capability.js
Labels: size/S

#5611 Automated cherry pick of #5609: fix(9420): 修复 cloudregion按启用平台过滤方式
  containers/Storage/views/bucket/create/index.vue
  src/utils/common/capability.js
Labels: size/S

#5612 fix: host network throw error when there is no nick_info
  containers/Compute/views/physicalmachine/sidepage/Network.vue
Labels: size/XS

#5613 Automated cherry pick of #5612: fix: host network throw error when there is no nick_info
  containers/Compute/views/physicalmachine/sidepage/Network.vue
Labels: size/XS

#5614 Automated cherry pick of #5612: fix: host network throw error when there is no nick_info
  containers/Compute/views/physicalmachine/sidepage/Network.vue
Labels: size/XS

#5616 fix: ramda.type函数使用修复
  src/sections/DialogManager/components/SmartForm.vue
Labels: size/XS

#5619 Automated cherry pick of #5616: fix: ramda.type函数使用修复
  src/sections/DialogManager/components/SmartForm.vue
Labels: size/XS

#5617 fix(9421): volcengine accuracy
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/utils/index.js
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/Compute/views/vminstance/utils.js
  containers/Storage/constants/index.js
  containers/Storage/locales/en.json
  containers/Storage/locales/ja-JP.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/bucket/mixins/columns.js
  containers/Storage/views/bucket/sidepage/Objects.vue
  scope/locales/en.json
  scope/locales/ja-JP.json
  scope/locales/zh-CN.json
Labels: size/L

#5618 Automated cherry pick of #5617: fix(9421): volcengine accuracy
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/utils/index.js
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/Compute/views/vminstance/utils.js
  containers/Storage/constants/index.js
  containers/Storage/locales/en.json
  containers/Storage/locales/ja-JP.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/bucket/mixins/columns.js
  containers/Storage/views/bucket/sidepage/Objects.vue
  scope/locales/en.json
  scope/locales/ja-JP.json
  scope/locales/zh-CN.json
Labels: size/L

#5620 feat(4535): cloudaccount create selecte platform accuracy
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
  src/constants/feature.js
Labels: size/XS

#5621 Automated cherry pick of #5620: feat(4535): cloudaccount create selecte platform accuracy
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
  src/constants/feature.js
Labels: size/XS

#5622 Automated cherry pick of #5620: feat(4535): cloudaccount create selecte platform accuracy
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
  src/constants/feature.js
Labels: size/XS

#5623 feat(4607): update platform icons
  src/assets/images/providers/baidu.svg
  src/assets/images/providers/huawei.svg
  src/assets/images/providers/vmware.svg
  src/assets/images/providers/zstack.svg
  src/components/Icon/assets/aws.svg
  src/components/Icon/assets/baidu.svg
  src/components/Icon/assets/ceph.svg
  src/components/Icon/assets/ecloud.svg
  src/components/Icon/assets/k8s.svg
  src/components/Icon/assets/s3.svg
  src/components/Icon/assets/vmware.svg
  src/components/Icon/assets/zstack.svg
  src/constants/feature.js
Labels: size/M

#5624 Automated cherry pick of #5623: feat(4607): update platform icons
  src/assets/images/providers/baidu.svg
  src/assets/images/providers/huawei.svg
  src/assets/images/providers/vmware.svg
  src/assets/images/providers/zstack.svg
  src/components/Icon/assets/aws.svg
  src/components/Icon/assets/baidu.svg
  src/components/Icon/assets/ceph.svg
  src/components/Icon/assets/ecloud.svg
  src/components/Icon/assets/k8s.svg
  src/components/Icon/assets/s3.svg
  src/components/Icon/assets/vmware.svg
  src/components/Icon/assets/zstack.svg
  src/constants/feature.js
Labels: size/M

#5625 feat(4613): vmware(running status) disk support resize
  containers/Compute/views/disk/utils/index.js
Labels: size/XS

#5627 Automated cherry pick of #5625: feat(4613): vmware(running status) disk support resize
  containers/Compute/views/disk/utils/index.js
Labels: size/XS

#5628 feat: 优化CPU性能，提升10%左右，去掉告警动画
  src/sections/Navbar/components/Alertresource.vue
Labels: size/XS

#5629 Automated cherry pick of #5628: feat: 优化CPU性能，去掉告警动画
  src/sections/Navbar/components/Alertresource.vue
Labels: size/XS

#5630 Automated cherry pick of #5628: feat: 优化CPU性能，去掉告警动画
  src/sections/Navbar/components/Alertresource.vue
Labels: size/XS

#5631 feat(4614): proxmox support select iso from private iso
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/Private.vue
  src/constants/compute.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#5633 fix(9421): volcengine added status check for ssh operation
  containers/Compute/views/vminstance/utils.js
Labels: size/XS

#5634 Automated cherry pick of #5633: fix(9421): volcengine added status check for ssh operation
  containers/Compute/views/vminstance/utils.js
Labels: size/XS

#5636 Automated cherry pick of #5635: feat: 虚拟机详情页透传设备页签不调用探测接口
  containers/Compute/views/gpu/components/List.vue
Labels: size/XS

#5639 Automated cherry pick of #5638: feat(4610): 负载均衡增加修改项目操作
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/mixins/singleActions.js
  src/sections/DialogManager/components/ChangeOwenr.vue
Labels: size/M

#5641 Automated cherry pick of #5638: feat(4610): 负载均衡增加修改项目操作
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/mixins/singleActions.js
  src/sections/DialogManager/components/ChangeOwenr.vue
Labels: size/M

#5640 Automated cherry pick of #5638: feat(4610): 负载均衡增加修改项目操作
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/mixins/singleActions.js
  src/sections/DialogManager/components/ChangeOwenr.vue
Labels: size/M

#5642 Automated cherry pick of #5635: feat: 虚拟机详情页透传设备页签不调用探测接口
  containers/Compute/views/gpu/components/List.vue
Labels: size/XS

#5643 fix(9420): 修复 cloudregion按启用平台过滤方式
  src/utils/common/capability.js
Labels: size/XS

#5644 Automated cherry pick of #5643: fix(9420): 修复 cloudregion按启用平台过滤方式
  src/utils/common/capability.js
Labels: size/XS

#5645 Automated cherry pick of #5643: fix(9420): 修复 cloudregion按启用平台过滤方式
  src/utils/common/capability.js
Labels: size/XS

#5646 feat: time filter accuracy
  src/components/SearchBox/index.vue
  src/utils/common/tableFilter.js
Labels: size/XS

#5647 Automated cherry pick of #5646: feat: time filter accuracy
  src/components/SearchBox/index.vue
  src/utils/common/tableFilter.js
Labels: size/XS

#5648 fix: allow switch any wire of same vpc
  containers/Network/views/network/dialogs/SwitchWire.vue
Labels: size/XS

#5649 Automated cherry pick of #5648: fix: allow switch any wire of same vpc
  containers/Network/views/network/dialogs/SwitchWire.vue
Labels: size/XS

#5650 feat(4621): add pagelist tag filter option
  src/components/PageList/TagFilter.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/common/tableFilter.js
  src/utils/list.js
Labels: size/L

#5651 Automated cherry pick of #5650: feat(4621): add pagelist tag filter option
  src/components/PageList/TagFilter.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/common/tableFilter.js
  src/utils/list.js
Labels: size/L

#5652 fix(9446): vminstance list export error
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#5653 Automated cherry pick of #5652: fix(9446): vminstance list export error
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#5654 Automated cherry pick of #5652: fix(9446): vminstance list export error
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#5655 fix(9444): support export list data from front
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#5656 Automated cherry pick of #5655: fix(9444): support export list data from front
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#5657 Automated cherry pick of #5655: fix(9444): support export list data from front
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#5658 feat(4607): 更换平台图标
  src/assets/images/providers/aliyun.svg
  src/components/Icon/assets/aliyun.svg
  src/components/Icon/assets/baidu.svg
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/utils/utils.js
Labels: size/M

#5659 Automated cherry pick of #5658: feat(4607): 更换平台图标
  src/assets/images/providers/aliyun.svg
  src/components/Icon/assets/aliyun.svg
  src/components/Icon/assets/baidu.svg
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/utils/utils.js
Labels: size/M

#5660 feat(4633): add favicon.ico
  public/favicon.ico
  public/index.html
Labels: size/XS

#5661 Automated cherry pick of #5660: feat(4633): add favicon.ico
  public/favicon.ico
  public/index.html
Labels: size/XS

#5662 Automated cherry pick of #5660: feat(4633): add favicon.ico
  public/favicon.ico
  public/index.html
Labels: size/XS

#5663 feat: cloud provider support export list data
  containers/Cloudenv/views/cloudprovider/components/List.vue
  containers/Cloudenv/views/cloudprovider/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/utils/columns.js
Labels: size/M

#5664 Automated cherry pick of #5663: cloud provider support export list data
  containers/Cloudenv/views/cloudprovider/components/List.vue
  containers/Cloudenv/views/cloudprovider/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/utils/columns.js
Labels: size/M

#5665 fix: rename price info
  containers/Cloudenv/views/cloudaccount/dialogs/SetDiscount.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  src/constants/permission.js
Labels: size/L

#5666 Automated cherry pick of #5665: fix: rename price info
  containers/Cloudenv/views/cloudaccount/dialogs/SetDiscount.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  src/constants/permission.js
Labels: size/L

#5667 feat: cloudprovider export add cloudaccount params
  containers/Cloudenv/views/cloudprovider/components/List.vue
Labels: size/XS

#5668 Automated cherry pick of #5667: feat: cloudprovider export add cloudaccount params
  containers/Cloudenv/views/cloudprovider/components/List.vue
Labels: size/XS

#5669 feat(4552): 跨集群迁移
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/dialogs/V2vTransfer.vue
  containers/Compute/views/vminstance/utils.js
Labels: size/XL

#5670 Automated cherry pick of #5669: feat(4552): 跨集群迁移
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/dialogs/V2vTransfer.vue
  containers/Compute/views/vminstance/utils.js
Labels: size/XL

#5671 Automated cherry pick of #5669: feat(4552): 跨集群迁移
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/dialogs/V2vTransfer.vue
  containers/Compute/views/vminstance/utils.js
Labels: size/XL

#5672 fix(9441): 新建kvm虚拟机时 高级配置没有主备机选项
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#5673 Automated cherry pick of #5672: fix(9441): 新建kvm虚拟机时 高级配置没有主备机选项
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#5674 Automated cherry pick of #5672: fix(9441): 新建kvm虚拟机时 高级配置没有主备机选项
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#5675 feat(972): add prediction
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#5676 Automated cherry pick of #5675: feat(972): add prediction
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#5677 fix: cloudaccount disable sync action when syncing
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/S

#5678 Automated cherry pick of #5677: fix: cloudaccount disable sync action when syncing
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/S

#5679 Automated cherry pick of #5677: fix: cloudaccount disable sync action when syncing
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/S

#5680 feat(4624): 虚拟机列表增加系统的过滤，目前过滤不细，同时支持通过系统排序
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  src/utils/common/tableFilter.js
Labels: size/M

#5681 Automated cherry pick of #5680: feat(4624): 虚拟机列表增加系统的过滤，目前过滤不细，同时支持通过系统排序
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  src/utils/common/tableFilter.js
Labels: size/M

#5682 fix(9452): 新建主机操作系统列，镜像类型增加一个全部的选项，镜像列表不过滤
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/S

#5683 Automated cherry pick of #5682: fix(9452): 新建主机操作系统列，镜像类型增加一个全部的选项，镜像列表不过滤
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/S

#5684 Automated cherry pick of #5682: fix(9452): 新建主机操作系统列，镜像类型增加一个全部的选项，镜像列表不过滤
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/S

#5685 fix: vnc禁用优先看平台禁用条件
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#5686 Automated cherry pick of #5685: fix: vnc禁用优先看平台禁用条件
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#5687 feat: 虚拟机列表查询，调整系统distinct字段
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#5688 Automated cherry pick of #5687: feat: 虚拟机列表查询，调整系统distinct字段
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#5689 Automated cherry pick of #5687: feat: 虚拟机列表查询，调整系统distinct字段
  containers/Compute/views/vminstance/components/List.vue
Labels: size/S

#5690 feat: 虚拟机列表查询，支持根据发行版过滤
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#5691 Automated cherry pick of #5690: feat: 虚拟机列表查询，支持根据发行版过滤
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#5692 Automated cherry pick of #5690: feat: 虚拟机列表查询，支持根据发行版过滤
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#5693 feat: 虚拟机列表，支持根据发行版排序
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#5695 Automated cherry pick of #5693: feat: 虚拟机列表，支持根据发行版排序
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#5694 Automated cherry pick of #5693: feat: 虚拟机列表，支持根据发行版排序
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#5696 feature: support createing server from instance backup
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Storage/locales/en.json
  containers/Storage/locales/ja-JP.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/router/index.js
  containers/Storage/views/backup-storage/dialogs/BackupStorageCreate.vue
  containers/Storage/views/backup-storage/mixins/columns.js
  containers/Storage/views/backup-storage/sidepage/Detail.vue
  containers/Storage/views/backup-storage/utils/columns.js
  containers/Storage/views/blockstorage/components/FormItems.vue
  src/constants/compute.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#5697 Automated cherry pick of #5696: feature: support createing server from instance backup
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Storage/locales/en.json
  containers/Storage/locales/ja-JP.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/router/index.js
  containers/Storage/views/backup-storage/dialogs/BackupStorageCreate.vue
  containers/Storage/views/backup-storage/mixins/columns.js
  containers/Storage/views/backup-storage/sidepage/Detail.vue
  containers/Storage/views/backup-storage/utils/columns.js
  containers/Storage/views/blockstorage/components/FormItems.vue
  src/constants/compute.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#5698 feat(4615): 域管理后台和项目视图也支持共享，仅限管理员操作
  containers/Dashboard/views/dashboard/components/Header.vue
Labels: size/XS

#5699 Automated cherry pick of #5698: feat(4615): 域管理后台和项目视图也支持共享，仅限管理员操作
  containers/Dashboard/views/dashboard/components/Header.vue
Labels: size/XS

#5700 feat(4622): edit commponent support input number
  src/components/Edit/Form.vue
  src/components/Edit/index.js
  src/components/ListBodyCellWrap/index.vue
Labels: size/S

#5704 Automated cherry pick of #5702: feat(4652): 增加隐藏费用聚合项策略
  src/permission.js
Labels: size/XS

#5705 feat(4622): add i18n
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#5706 Automated cherry pick of #5705: feat(4622): add i18n
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#5708 feat(4658): windows系统支持RDP及SSH优化
  containers/Compute/views/vminstance/constants/actions.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/RdpAuth.vue
Labels: size/L

#5709 fix: 主机创建备份操作隐藏
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#5710 Automated cherry pick of #5709: fix: 主机创建备份操作隐藏
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#5713 fix: esxi secondary ip support
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/networks/mixins/columns.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/M

#5714 Automated cherry pick of #5713: fix: esxi secondary ip support
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/networks/mixins/columns.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/M

#5715 feat: 增加字典映射
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/router/index.js
  containers/Compute/views/disk/mixins/singleActions.js
  containers/DB/locales/en.json
  containers/DB/locales/ja-JP.json
  containers/DB/locales/zh-CN.json
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/ja-JP.json
  containers/Dashboard/locales/zh-CN.json
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XL

#5716 Automated cherry pick of #5715: feat: 增加字典映射
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/router/index.js
  containers/Compute/views/disk/mixins/singleActions.js
  containers/DB/locales/en.json
  containers/DB/locales/ja-JP.json
  containers/DB/locales/zh-CN.json
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/ja-JP.json
  containers/Dashboard/locales/zh-CN.json
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XL

#5717 Automated cherry pick of #5715: feat: 增加字典映射
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/router/index.js
  containers/Compute/views/disk/mixins/singleActions.js
  containers/DB/locales/en.json
  containers/DB/locales/zh-CN.json
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#5719 feat: 主机快照信息从字典获取值
  containers/Compute/sections/OsSelect/index.vue
  src/constants/compute.js
Labels: size/XS
