Repository yunionio/dashboard, pull requests merged in 2023-03, with the labels that each got.

#4232 fix: fix side effects caused by ListSelect component expansion
  src/sections/DialogManager/components/ListSelect.vue
Labels: size/XS

#4233 Automated cherry pick of #4232: fix: fix side effects caused by ListSelect component expansion
  src/sections/DialogManager/components/ListSelect.vue
Labels: size/XS

#4234 Automated cherry pick of #4232: fix: fix side effects caused by ListSelect component expansion
  src/sections/DialogManager/components/ListSelect.vue
Labels: size/XS

#4235 fix(8790): ldap认证源禁用后，提示信息不明确
  src/constants/error.js
  src/locales/help-en.js
  src/locales/help-zh-CN.js
  src/utils/error.js
Labels: size/S

#4236 Automated cherry pick of #4235: fix(8790): ldap认证源禁用后，提示信息不明确
  src/constants/error.js
  src/locales/help-en.js
  src/locales/help-zh-CN.js
  src/utils/error.js
Labels: size/S

#4239 Automated cherry pick of #4237: feat(4194): tag value is required for create resource
  containers/Compute/views/baremetal/create/index.vue
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/secgroup/dialogs/Create.vue
  containers/Compute/views/vminstance/create/components/Tag.vue
  containers/DB/views/rds/create/index.vue
  containers/DB/views/redis/create/index.vue
  containers/Network/views/dns-recordset/dialogs/Create.vue
  containers/Network/views/eip/create/index.vue
  containers/Network/views/lb/create/form/IDC.vue
  containers/Network/views/lb/create/form/Private.vue
  containers/Network/views/lb/create/form/Public.vue
  containers/Storage/views/blockstorage/dialogs/Create.vue
  containers/Storage/views/bucket/create/index.vue
  containers/Storage/views/file-system/create/index.vue
  src/sections/Tag/index.vue
  src/sections/TagSelect/index.vue
Labels: size/M

#4243 Automated cherry pick of #4240: feat(4203): 图形GPU支持
  containers/Compute/constants/index.js
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/GPU/index.vue
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/constants/compute.js
Labels: size/L

#4240 feat(4203): 图形GPU支持
  containers/Compute/constants/index.js
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/GPU/index.vue
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/constants/compute.js
Labels: size/L

#4249 feat(4198): 打开宿主机详情透传设备页面时，也应该调用 probe-isolated-devices 刷新宿主机透传设备列表
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/host/sidepage/Gpu.vue
Labels: size/M

#4250 Automated cherry pick of #4249: feat(4198): 打开宿主机详情透传设备页面时，也应该调用 probe-isolated-devices 刷新宿主机透传设备列表
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/host/sidepage/Gpu.vue
Labels: size/M

#4251 Automated cherry pick of #4249: feat(4198): 打开宿主机详情透传设备页面时，也应该调用 probe-isolated-devices 刷新宿主机透传设备列表
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/host/sidepage/Gpu.vue
Labels: size/M

#4247 fix(8825): server name filter error
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: area/monitor, size/XS

#4248 Automated cherry pick of #4247: fix(8825): server name filter error
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/XS

#4252 feat(4206): 增加翻译信息：虚拟机异常
  containers/IAM/constants/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#4254 feat(4209): 新建虚拟机网络的交互适配大小屏
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
Labels: size/M

#4256 Automated cherry pick of #4255: feat(4198): 打开虚拟机详情透传设备页面时，也应该调用 probe-isolated-devices 刷新透传设备列表
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/S

#4257 Automated cherry pick of #4255: feat(4198): 打开虚拟机详情透传设备页面时，也应该调用 probe-isolated-devices 刷新透传设备列表
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/S

#4258 feat: 虚拟机支持整机更换块存储
  containers/Compute/views/vminstance/dialogs/ChangeBlockStorage.vue
Labels: size/M

#4259 Automated cherry pick of #4258: feat: 虚拟机支持整机更换块存储
  containers/Compute/views/vminstance/dialogs/ChangeBlockStorage.vue
Labels: size/M

#4260 Automated cherry pick of #4258: feat: 虚拟机支持整机更换块存储
  containers/Compute/views/vminstance/dialogs/ChangeBlockStorage.vue
Labels: size/M

#4261 fix(8826): 主机关联安全组更新后，应该主动刷新主机详情的安全组列表
  containers/Compute/views/vminstance/dialogs/SetSecgroup.vue
  containers/Compute/views/vminstance/sidepage/Secgroup.vue
  src/constants/event-bus.js
Labels: size/S

#4264 Automated cherry pick of #4261: fix(8826): 主机关联安全组更新后，应该主动刷新主机详情的安全组列表
  containers/Compute/views/vminstance/dialogs/SetSecgroup.vue
  containers/Compute/views/vminstance/sidepage/Secgroup.vue
  src/constants/event-bus.js
Labels: size/S

#4262 Automated cherry pick of #4261: fix(8826): 主机关联安全组更新后，应该主动刷新主机详情的安全组列表
  containers/Compute/views/vminstance/dialogs/SetSecgroup.vue
  containers/Compute/views/vminstance/sidepage/Secgroup.vue
  src/constants/event-bus.js
Labels: size/S

#4263 Automated cherry pick of #4261: fix(8826): 主机关联安全组更新后，应该主动刷新主机详情的安全组列表
  containers/Compute/views/vminstance/dialogs/SetSecgroup.vue
  containers/Compute/views/vminstance/sidepage/Secgroup.vue
  src/constants/event-bus.js
Labels: size/S

#4265 fix: workflow apply resource details
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/XS

#4267 feat(4211): 新建块存储增加”本地存储“选项，用户选择后告知配置设置文案
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/blockstorage/dialogs/Create.vue
Labels: size/S

#4268 Automated cherry pick of #4267: feat(4211): 新建块存储增加”本地存储“选项，用户选择后告知配置设置文案
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/blockstorage/dialogs/Create.vue
Labels: size/S

#4269 Automated cherry pick of #4267: feat(4211): 新建块存储增加”本地存储“选项，用户选择后告知配置设置文案
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/blockstorage/dialogs/Create.vue
Labels: size/S

#4273 fix(8790): ldap认证源禁用后，提示信息不明确
  src/utils/error.js
Labels: size/XS

#4270 fix: lbbackend action error
  containers/Network/views/loadbalancerbackend/mixins/singleActions.js
  containers/Network/views/loadbalancerbackendgroup/mixins/singleActions.js
  containers/Network/views/loadbalancerlistenerrule/mixins/singleActions.js
Labels: area/network, size/S

#4271 Automated cherry pick of #4270: fix: lbbackend action error
  containers/Network/views/loadbalancerbackend/mixins/singleActions.js
  containers/Network/views/loadbalancerbackendgroup/mixins/singleActions.js
  containers/Network/views/loadbalancerlistenerrule/mixins/singleActions.js
Labels: size/S

#4272 Automated cherry pick of #4270: fix: lbbackend action error
  containers/Network/views/loadbalancerbackend/mixins/singleActions.js
  containers/Network/views/loadbalancerbackendgroup/mixins/singleActions.js
  containers/Network/views/loadbalancerlistenerrule/mixins/singleActions.js
Labels: size/S

#4275 feat(4186): 项目及组操作用户提示用户可能存在删除后无法使用系统的风险
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/group/dialogs/LeaveUser.vue
  containers/IAM/views/projects/dialogs/DeleteRes.vue
Labels: size/XS

#4276 Automated cherry pick of #4275: feat(4186): 项目及组操作用户提示用户可能存在删除后无法使用系统的风险
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/group/dialogs/LeaveUser.vue
  containers/IAM/views/projects/dialogs/DeleteRes.vue
Labels: size/XS

#4277 fix(8829): account show log error
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/XS

#4278 Automated cherry pick of #4277: fix(8829): account show log error
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/XS

#4279 Automated cherry pick of #4277: fix(8829): account show log error
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/XS

#4280 Automated cherry pick of #4277: fix(8829): account show log error
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/XS

#4282 fix: vm calc price error for kvm local-medimu disk
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: area/compute, size/XS

#4283 Automated cherry pick of #4282: fix: vm calc price error for kvm local-medimu disk
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#4285 fix: 修复开源引用商业i18n翻译问题
  containers/Cloudenv/views/cloudgroup/mixins/columns.js
  containers/Cloudenv/views/cloudgroup/sidepage/Detail.vue
  containers/Cloudenv/views/server-price-comparator/components/List.vue
  containers/Dashboard/sections/ConsumptionConfig/index.vue
  containers/IAM/views/policy/constants.js
  containers/Monitor/sections/KindTabs/index.vue
  containers/Monitor/views/alertrecord/dialogs/ViewAlertrecordDetail.vue
  src/components/BaseChart/index.vue
  src/constants/currency.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/NotifyTypes/index.vue
  src/utils/common/tableFilter.js
Labels: size/L

#4286 Automated cherry pick of #4285: fix: 修复开源引用商业i18n翻译问题
  containers/Cloudenv/views/cloudgroup/mixins/columns.js
  containers/Cloudenv/views/cloudgroup/sidepage/Detail.vue
  containers/Cloudenv/views/server-price-comparator/components/List.vue
  containers/Dashboard/sections/ConsumptionConfig/index.vue
  containers/IAM/views/policy/constants.js
  containers/Monitor/sections/KindTabs/index.vue
  containers/Monitor/views/alertrecord/dialogs/ViewAlertrecordDetail.vue
  src/components/BaseChart/index.vue
  src/constants/currency.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/NotifyTypes/index.vue
  src/utils/common/tableFilter.js
Labels: size/L

#4290 feat(4190): vminstance export add elastic ip
  containers/Cloudenv/views/scheduledtask/mixins/resourceProps.js
  containers/Compute/views/gpu/sidepage/Servers.vue
  containers/Compute/views/instance-group/sidepage/VMInstanceListForInstanceGroup.vue
  containers/Compute/views/scaling-group/sidepage/ServerList.vue
  containers/Compute/views/secgroup/mixins/serverListPropsForSetServer.js
  containers/Compute/views/secgroup/mixins/serverProps.js
  containers/Compute/views/server-recovery/mixins/columns.js
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
  containers/Compute/views/vminstance/dialogs/AttachUsb.vue
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/sections/table/index.vue
  src/utils/common/tableColumn.js
Labels: size/M, area/compute

#4281 feat(4212): 网络新增”更换二层网络“的菜单
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/dialogs/SwitchWire.vue
  containers/Network/views/network/mixins/singleActions.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#4292 Automated cherry pick of #4281: feat(4212): 网络新增”更换二层网络“的菜单
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/dialogs/SwitchWire.vue
  containers/Network/views/network/mixins/singleActions.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#4293 feat(8826): 除OneCloud平台之外不展示透传设备页签
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/XS

#4294 Automated cherry pick of #4293: feat(8826): 除OneCloud平台之外不展示透传设备页签
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/XS

#4296 Automated cherry pick of #4293: feat(8826): 除OneCloud平台之外不展示透传设备页签
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/XS

#4295 Automated cherry pick of #4293: feat(8826): 除OneCloud平台之外不展示透传设备页签
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/XS

#4299 Automated cherry pick of #4281: feat(4212): 网络新增”更换二层网络“的菜单
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/dialogs/SwitchWire.vue
  containers/Network/views/network/mixins/singleActions.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#4297 feat(4169): add project_sharings
  containers/IAM/views/policy/constants.js
  src/components/Icon/assets/res-project-sharing.svg
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#4303 fix(8841): image recovery delete guest images error
  containers/Compute/views/image-recovery/components/List.vue
  containers/Compute/views/image-recovery/dialogs/Restore.vue
  containers/Compute/views/image-recovery/mixins/singleActions.js
Labels: area/compute, size/S

#4300 feat(4220): server recovery add id and external_id columns
  containers/Compute/views/server-recovery/components/List.vue
  containers/Compute/views/server-recovery/mixins/columns.js
Labels: area/compute, size/S

#4301 Automated cherry pick of #4300: feat(4220): server recovery add id and external_id columns
  containers/Compute/views/server-recovery/components/List.vue
  containers/Compute/views/server-recovery/mixins/columns.js
Labels: size/S

#4302 Automated cherry pick of #4300: feat(4220): server recovery add id and external_id columns
  containers/Compute/views/server-recovery/components/List.vue
  containers/Compute/views/server-recovery/mixins/columns.js
Labels: size/S

#4304 Automated cherry pick of #4303: fix(8841): image recovery delete guest images error
  containers/Compute/views/image-recovery/components/List.vue
  containers/Compute/views/image-recovery/dialogs/Restore.vue
  containers/Compute/views/image-recovery/mixins/singleActions.js
Labels: size/S

#4305 Automated cherry pick of #4303: fix(8841): image recovery delete guest images error
  containers/Compute/views/image-recovery/components/List.vue
  containers/Compute/views/image-recovery/dialogs/Restore.vue
  containers/Compute/views/image-recovery/mixins/singleActions.js
Labels: size/S

#4306 fix(8841): image recovery restore guest images error
  containers/Compute/views/image-recovery/components/List.vue
Labels: area/compute, size/XS

#4307 Automated cherry pick of #4306: fix(8841): image recovery restore guest images error
  containers/Compute/views/image-recovery/components/List.vue
Labels: size/XS

#4308 Automated cherry pick of #4306: fix(8841): image recovery restore guest images error
  containers/Compute/views/image-recovery/components/List.vue
Labels: size/XS

#4310 Automated cherry pick of #4309: fix: 创建虚机的时候镜像列表这里，镜像是非uefi的，展示成uefi的了
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
Labels: size/XS

#4313 feat(4162): cloudaccount update bill router jump params
  containers/Cloudenv/views/cloudaccount/create/BillFileIndex.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: area/cloudenv, size/XS

#4314 Automated cherry pick of #4313: feat(4162): cloudaccount update bill router jump params
  containers/Cloudenv/views/cloudaccount/create/BillFileIndex.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#4315 feat(4043): dns-zone add filter params
  containers/Network/views/dns-zone/components/List.vue
Labels: area/network, size/S

#4316 Automated cherry pick of #4315: feat(4043): dns-zone add filter params
  containers/Network/views/dns-zone/components/List.vue
Labels: size/S

#4317 Automated cherry pick of #4315: feat(4043): dns-zone add filter params
  containers/Network/views/dns-zone/components/List.vue
Labels: size/S

#4318 fix: 配置vga的时候默认过滤uefi镜像，镜像选择默认值错误问题
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#4319 Automated cherry pick of #4318: fix: 配置vga的时候默认过滤uefi镜像，镜像选择默认值错误问题
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#4320 Automated cherry pick of #4318: fix: 配置vga的时候默认过滤uefi镜像，镜像选择默认值错误问题
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#4321 Automated cherry pick of #4318: fix: 配置vga的时候默认过滤uefi镜像，镜像选择默认值错误问题
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#4322 feat(4227): add min-width for page list column
  src/components/PageList/components/Table.vue
  src/components/PageList/components/Table_fixed.vue
Labels: size/S

#4323 Automated cherry pick of #4322: feat(4227): add min-width for page list column
  src/components/PageList/components/Table.vue
  src/components/PageList/components/Table_fixed.vue
Labels: size/S

#4327 fix: 修复存储选择本地存储点击新建一直loading的状态
  containers/Storage/views/blockstorage/dialogs/Create.vue
Labels: size/XS

#4328 Automated cherry pick of #4327: fix: 修复存储选择本地存储点击新建一直loading的状态
  containers/Storage/views/blockstorage/dialogs/Create.vue
Labels: size/XS

#4329 Automated cherry pick of #4327: fix: 修复存储选择本地存储点击新建一直loading的状态
  containers/Storage/views/blockstorage/dialogs/Create.vue
Labels: size/XS

#4330 fix(itsm): remove user_id query when third-process's system scope
  src/views/workflow-technical-support/third-process/components/List.vue
Labels: size/XS

#4331 Automated cherry pick of #4330: fix(itsm): remove user_id query when third-process's system scope
  src/views/workflow-technical-support/third-process/components/List.vue
Labels: size/XS

#4332 Automated cherry pick of #4330: fix(itsm): remove user_id query when third-process's system scope
  src/views/workflow-technical-support/third-process/components/List.vue
Labels: size/XS

#4324 fix(8846): vminstance disk add medium type
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Cloudenv/views/server-price-comparator/create/form/IDC.vue
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: area/compute, size/L

#4326 Automated cherry pick of #4324: fix(8846): vminstance disk add medium type
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Cloudenv/views/server-price-comparator/create/form/IDC.vue
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/M

#4333 feat(4211): 新建存储，本地存储增加提示信息
  containers/Storage/constants/index.js
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/blockstorage/dialogs/Create.vue
Labels: size/S

#4334 Automated cherry pick of #4333: feat(4211): 新建存储，本地存储增加提示信息
  containers/Storage/constants/index.js
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/blockstorage/dialogs/Create.vue
Labels: size/S

#4335 Automated cherry pick of #4333: feat(4211): 新建存储，本地存储增加提示信息
  containers/Storage/constants/index.js
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/blockstorage/dialogs/Create.vue
Labels: size/S

#4336 feat: add status i18n
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#4337 Automated cherry pick of #4336: feat: add status i18n
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#4340 feat(4225): 主机创建安装监控Agent显示优化
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#4341 Automated cherry pick of #4340: feat(4225): 主机创建安装监控Agent显示优化
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#4343 feat(4222): 硬盘去掉ssd列
  containers/Compute/views/disk/mixins/columns.js
Labels: size/XS

#4344 Automated cherry pick of #4343: feat(4222): 硬盘去掉ssd列
  containers/Compute/views/disk/mixins/columns.js
Labels: size/XS

#4345 Automated cherry pick of #4343: feat(4222): 硬盘去掉ssd列
  containers/Compute/views/disk/mixins/columns.js
Labels: size/XS

#4346 fix(8849): list export column width is 0
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#4347 Automated cherry pick of #4346: fix(8849): list export column width is 0
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#4348 Automated cherry pick of #4346: fix(8849): list export column width is 0
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#4349 feat: cloudaccount update bill
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  src/constants/permission.js
Labels: size/L

#4356 fix: update locale 20230320
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#4357 Automated cherry pick of #4356: fix: update locale 20230320
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#4350 feat(4037): login captcha is timed refresh
  src/mixins/captcha.js
  src/sections/Auth/Login/components/LoginChallenge.vue
  src/sections/Auth/Login/components/LoginMobile.vue
Labels: size/M

#4351 Automated cherry pick of #4350: feat(4037): login captcha is timed refresh
  src/mixins/captcha.js
  src/sections/Auth/Login/components/LoginChallenge.vue
  src/sections/Auth/Login/components/LoginMobile.vue
Labels: size/M

#4352 Automated cherry pick of #4350: feat(4037): login captcha is timed refresh
  src/mixins/captcha.js
  src/sections/Auth/Login/components/LoginChallenge.vue
  src/sections/Auth/Login/components/LoginMobile.vue
Labels: size/M

#4353 fix(8859): policy search add scope check
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/index.vue
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#4354 Automated cherry pick of #4353: fix(8859): policy search add scope check
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/index.vue
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#4355 Automated cherry pick of #4353: fix(8859): policy search add scope check
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/index.vue
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#4358 fix: brand default value
  src/utils/common/tableColumn.js
Labels: size/XS

#4359 Automated cherry pick of #4358: fix: brand default value
  src/utils/common/tableColumn.js
Labels: size/XS

#4360 Automated cherry pick of #4358: fix: brand default value
  src/utils/common/tableColumn.js
Labels: size/XS

#4361 feat(4241): monitor overview show vm ip
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/OverviewCard/index.vue
  containers/Monitor/components/MonitorCard/OverviewCard/metrics.js
  containers/Monitor/components/MonitorCard/sections/table/index.vue
Labels: area/monitor, size/L

#4362 Automated cherry pick of #4361: feat(4241): monitor overview show vm ip
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/OverviewCard/index.vue
  containers/Monitor/components/MonitorCard/OverviewCard/metrics.js
  containers/Monitor/components/MonitorCard/sections/table/index.vue
Labels: size/L

#4365 fix: 修复HCS虚拟机详情数据盘展示为空问题
  containers/Compute/constants/index.js
Labels: size/XS

#4366 Automated cherry pick of #4365: fix: 修复HCS虚拟机详情数据盘展示为空问题
  containers/Compute/constants/index.js
Labels: size/XS

#4363 feat(4236): monitor overview add rds monitor
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: area/monitor, size/L

#4364 Automated cherry pick of #4363: feat(4236): monitor overview add rds monitor
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/L

#4368 feat(4243): vm disk show disk medium
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Cloudenv/views/server-price-comparator/create/components/SystemDisk.vue
  containers/Cloudenv/views/server-price-comparator/create/form/IDC.vue
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  src/utils/common/hypervisor.js
Labels: area/compute, size/L

#4369 Automated cherry pick of #4368: feat(4243): vm disk show disk medium
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Cloudenv/views/server-price-comparator/create/components/SystemDisk.vue
  containers/Cloudenv/views/server-price-comparator/create/form/IDC.vue
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  src/utils/common/hypervisor.js
Labels: size/L

#4370 Automated cherry pick of #4368: feat(4243): vm disk show disk medium
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Cloudenv/views/server-price-comparator/create/components/SystemDisk.vue
  containers/Cloudenv/views/server-price-comparator/create/form/IDC.vue
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  src/utils/common/hypervisor.js
Labels: size/L

#4371 feat(4241): monitor overview rds metric
  containers/Monitor/components/MonitorCard/OverviewCard/metrics.js
Labels: area/monitor, size/XS

#4372 Automated cherry pick of #4371: feat(4241): monitor overview rds metric
  containers/Monitor/components/MonitorCard/OverviewCard/metrics.js
Labels: size/XS

#4373 feat: update ctyun logo
  src/assets/images/providers/ctyun.svg
  src/assets/images/providers/tianyi.svg
  src/components/Icon/assets/ctyun.svg
Labels: area/compute, size/XS

#4374 Automated cherry pick of #4373: feat: update ctyun logo
  src/assets/images/providers/ctyun.svg
  src/assets/images/providers/tianyi.svg
  src/components/Icon/assets/ctyun.svg
Labels: size/XS

#4375 Automated cherry pick of #4373: feat: update ctyun logo
  src/assets/images/providers/ctyun.svg
  src/assets/images/providers/tianyi.svg
  src/components/Icon/assets/ctyun.svg
Labels: size/XS

#4376 feat(4142): 增加巡检权限
  src/constants/permission.js
Labels: size/XS

#4377 Automated cherry pick of #4376: feat(4142): 增加巡检权限
  src/constants/permission.js
Labels: size/XS

#4378 Automated cherry pick of #4376: feat(4142): 增加巡检权限
  src/constants/permission.js
Labels: size/XS

#4379 fix(8869): 块存储详情页面前端展示存储类型为空
  containers/Storage/views/blockstorage/sidepage/Detail.vue
Labels: size/XS

#4380 Automated cherry pick of #4379: fix(8869): 块存储详情页面前端展示存储类型为空
  containers/Storage/views/blockstorage/sidepage/Detail.vue
Labels: size/XS

#4381 Automated cherry pick of #4379: fix(8869): 块存储详情页面前端展示存储类型为空
  containers/Storage/views/blockstorage/sidepage/Detail.vue
Labels: size/XS

#4384 feat: monitor add rds id export
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/sections/table/index.vue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: size/L

#4385 Automated cherry pick of #4384: feat: monitor add rds id export
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/sections/table/index.vue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: size/L

#4386 fix: vm adjust config data disk show empty when there is no sysdisk
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: area/compute, size/XS

#4387 Automated cherry pick of #4386: fix: vm adjust config data disk show empty when there is no sysdisk
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#4388 Automated cherry pick of #4386: fix: vm adjust config data disk show empty when there is no sysdisk
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#4389 fix: h3c feature
  src/constants/feature.js
Labels: size/XS

#4392 fix: workflow detail show style
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/S

#4394 fix: 修复列表回调函数回传参数问题
  src/utils/list.js
Labels: size/XS

#4395 feat: cloudaccount update bill
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
  src/components/BaseSelect/index.vue
  src/components/Icon/assets/res-billtask.svg
Labels: size/L

#4396 Automated cherry pick of #4395: feat: cloudaccount update bill
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
  src/components/BaseSelect/index.vue
  src/components/Icon/assets/res-billtask.svg
Labels: size/L

#4397 fix(8873): vmware adjust config can't show data disk
  containers/Compute/sections/DataDisk/index.vue
Labels: area/compute, size/XS

#4398 Automated cherry pick of #4397: fix(8873): vmware adjust config can't show data disk
  containers/Compute/sections/DataDisk/index.vue
Labels: size/XS

#4399 Automated cherry pick of #4397: fix(8873): vmware adjust config can't show data disk
  containers/Compute/sections/DataDisk/index.vue
Labels: size/XS

#4401 Automated cherry pick of #4400: fix(8884): 从磁盘点击磁盘更换存储的UI，存储名称是undefined
  containers/Compute/views/disk/dialogs/ChangeBlockStorage.vue
Labels: size/XS

#4404 Automated cherry pick of #4403: fix: 修复热扩容状态字段取值问题
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#4406 Automated cherry pick of #4403: fix: 修复热扩容状态字段取值问题
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#4409 feat: cloudaccount delete bill task type
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#4410 Automated cherry pick of #4409: feat: cloudaccount delete bill task type
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#4412 Automated cherry pick of #4411: fix: 开源版本不检查是否已注册
  src/layouts/Auth/index.vue
Labels: size/XS

#4415 feat: 工单支持转单
  containers/Network/constants/lb.js
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/lb/sidepage/Monitor.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/mixins/monitorTime.js
  src/views/workflow-technical-support/all-process/sidepage/Detail.vue
  src/views/workflow-technical-support/approval-start/sidepage/Detail.vue
  src/views/workflow-technical-support/approved-done/sidepage/Detail.vue
  src/views/workflow-technical-support/me-process/sidepage/Detail.vue
  src/views/workflow/all-process/sidepage/Detail.vue
  src/views/workflow/approval-start/dialogs/PassDialog.vue
  src/views/workflow/approval-start/dialogs/RejectDialog.vue
  src/views/workflow/approval-start/mixins/singleActions.js
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/approved-done/sidepage/Detail.vue
  src/views/workflow/me-partake/sidepage/Detail.vue
  src/views/workflow/me-process/sidepage/Detail.vue
  src/views/workflow/utils/columns.js
Labels: size/L

#4416 Automated cherry pick of #4415: feat: 工单支持转单
  containers/Network/constants/lb.js
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/lb/sidepage/Monitor.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/mixins/monitorTime.js
  src/views/workflow-technical-support/all-process/sidepage/Detail.vue
  src/views/workflow-technical-support/approval-start/sidepage/Detail.vue
  src/views/workflow-technical-support/approved-done/sidepage/Detail.vue
  src/views/workflow-technical-support/me-process/sidepage/Detail.vue
  src/views/workflow/all-process/sidepage/Detail.vue
  src/views/workflow/approval-start/dialogs/PassDialog.vue
  src/views/workflow/approval-start/dialogs/RejectDialog.vue
  src/views/workflow/approval-start/mixins/singleActions.js
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/approved-done/sidepage/Detail.vue
  src/views/workflow/me-partake/sidepage/Detail.vue
  src/views/workflow/me-process/sidepage/Detail.vue
  src/views/workflow/utils/columns.js
Labels: size/L

#4417 fix(8878): 添加网卡框溢出修复
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: size/XS

#4418 Automated cherry pick of #4417: fix(8878): 添加网卡框溢出修复
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: size/M
