Repository yunionio/dashboard, pull requests merged in 2023-08, with the labels that each got.

#5031 fix(9236): 新建硬盘，需校验硬盘容量数字为必填
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/create/index.vue
Labels: size/S

#5032 Automated cherry pick of #5031: fix(9236): 新建硬盘，需校验硬盘容量数字为必填
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/create/index.vue
Labels: size/S

#5033 Automated cherry pick of #5031: fix(9236): 新建硬盘，需校验硬盘容量数字为必填
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/create/index.vue
Labels: size/S

#5034 fix(9232): 日志管理导出报错NotSupportedError
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/http.js
  src/utils/utils.js
Labels: size/M

#5035 Automated cherry pick of #5034: fix(9232): 日志管理导出报错NotSupportedError
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/http.js
  src/utils/utils.js
Labels: size/M

#5037 Automated cherry pick of #5036: fix: 去掉容器实例更新名称规则校验
  containers/Helm/views/k8s-release/update/index.vue
Labels: size/XS

#5039 Automated cherry pick of #5038: feat(4477): cloudaccount balance monitor alert show currency sign
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/Metric/index.vue
  containers/Monitor/sections/MonitorLine/index.vue
  containers/Monitor/views/commonalert/components/alert/form/index.vue
  containers/Monitor/views/commonalert/components/alert/form/thresholdInput.js
  containers/Monitor/views/commonalert/components/alert/index.vue
  containers/Monitor/views/commonalert/utils/index.js
Labels: size/L

#5040 feat(4459): 优化合并镜像支持拖拽排序
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/dialogs/MergeMirror.vue
  containers/Compute/views/image/locales/en.json
  containers/Compute/views/image/locales/zh-CN.json
Labels: size/M

#5041 Automated cherry pick of #5040: feat(4459): 优化合并镜像支持拖拽排序
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/dialogs/MergeMirror.vue
  containers/Compute/views/image/locales/en.json
  containers/Compute/views/image/locales/zh-CN.json
Labels: size/M

#5042 Automated cherry pick of #5040: feat(4459): 优化合并镜像支持拖拽排序
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/dialogs/MergeMirror.vue
  containers/Compute/views/image/locales/en.json
  containers/Compute/views/image/locales/zh-CN.json
Labels: size/M

#5045 feat(4459): 优化合并镜像校验提示
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/dialogs/MergeMirror.vue
  containers/Compute/views/image/locales/en.json
  containers/Compute/views/image/locales/zh-CN.json
Labels: size/S

#5046 Automated cherry pick of #5045: feat(4459): 优化合并镜像校验提示
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/dialogs/MergeMirror.vue
  containers/Compute/views/image/locales/en.json
  containers/Compute/views/image/locales/zh-CN.json
Labels: size/S

#5047 Automated cherry pick of #5045: feat(4459): 优化合并镜像校验提示
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/dialogs/MergeMirror.vue
  containers/Compute/views/image/locales/en.json
  containers/Compute/views/image/locales/zh-CN.json
Labels: size/S

#5049 Automated cherry pick of #5048: fix(9254): nat list export change to local download
  containers/Network/views/nats/components/List.vue
  containers/Network/views/nats/mixins/columns.js
  src/utils/utils.js
Labels: size/M

#5050 fix(9120): 公有云虚拟机创建相同配置时，镜像列表不应该显示为空
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#5051 Automated cherry pick of #5050: fix(9120): 公有云虚拟机创建相同配置时，镜像列表不应该显示为空
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#5052 fix(9254): nat export add id column
  containers/Network/views/nats/components/List.vue
Labels: size/XS

#5053 Automated cherry pick of #5052: fix(9254): nat export add id column
  containers/Network/views/nats/components/List.vue
Labels: size/XS

#5054 feat: base select add dropdown change event
  src/components/BaseSelect/index.vue
Labels: size/XS

#5055 Automated cherry pick of #5054: feat: base select add dropdown change event
  src/components/BaseSelect/index.vue
Labels: size/XS

#5056 fix: 去掉单条数据的迁移预检，保持与多条数据的逻辑统一
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#5060 fix(9259): 虚拟机新建磁盘不显示磁盘大小
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/S

#5061 Automated cherry pick of #5060: fix(9259): 虚拟机新建磁盘不显示磁盘大小
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/S

#5058 feat: support ksyun
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ksyun.vue
  scope/assets/ksyun.svg
  scope/locales/en.json
  scope/locales/zh-CN.json
  src/assets/images/providers/ksyun.svg
  src/components/Icon/assets/ksyun.svg
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#5059 feat(4488): add watermark params
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/M

#5064 feat: 调整设置磁盘速率tooltip及默认值
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/SetSpeed.vue
Labels: size/S

#5065 Automated cherry pick of #5064: feat: 调整设置磁盘速率tooltip及默认值
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/SetSpeed.vue
Labels: size/S

#5062 fix(K8s): wrong getting k8s-versions params
  containers/K8S/views/cluster/create/index.vue
  containers/K8S/views/kube-machines/dialogs/CreateKubemachinesDialog.vue
Labels: area/k8s, size/S

#5063 Automated cherry pick of #5062: fix(K8s): wrong getting k8s-versions params
  containers/K8S/views/cluster/create/index.vue
  containers/K8S/views/kube-machines/dialogs/CreateKubemachinesDialog.vue
Labels: size/S

#5066 Automated cherry pick of #4876: fix(9156): add local export params for export all datas
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#5067 fix: auto build docker image
  .github/workflows/docker.yml
  .github/workflows/nodejs.yml
  Makefile
  scripts/docker_push.sh
Labels: size/M

#5068 Automated cherry pick of #5067: fix: auto build docker image
  .github/workflows/docker.yml
  .github/workflows/nodejs.yml
  Makefile
  scripts/docker_push.sh
Labels: size/M

#5069 feat: temp change
  containers/Compute/views/disk/index.vue
  containers/Compute/views/snapshot-instance/index.vue
  containers/Compute/views/snapshot/index.vue
  containers/Compute/views/vminstance/index.vue
  containers/Network/views/eip/index.vue
  containers/Network/views/lb/index.vue
  containers/Network/views/network/index.vue
  containers/Network/views/vpc/index.vue
  containers/Network/views/wire/index.vue
Labels: size/M

#5070 feat: temp change
  containers/Storage/views/bucket/index.vue
Labels: size/XS

#5071 feat: temp change
  src/locales/zh-CN.json
Labels: size/S

#5075 feat(4494): 新建虚拟机自定义数据优化
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/create/components/CustomData.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  src/components/Icon/assets/res-bastion-host.svg
Labels: size/S

#5072 feat: temp change recovery
  containers/Compute/views/disk/index.vue
  containers/Compute/views/snapshot-instance/index.vue
  containers/Compute/views/snapshot/index.vue
  containers/Compute/views/vminstance/index.vue
  containers/Network/views/eip/index.vue
  containers/Network/views/lb/index.vue
  containers/Network/views/network/index.vue
  containers/Network/views/vpc/index.vue
  containers/Network/views/wire/index.vue
  containers/Storage/views/bucket/index.vue
  src/locales/zh-CN.json
Labels: size/M

#5073 fix(9264): baseselect default select includes extraopts
  src/components/BaseSelect/index.vue
Labels: size/XS

#5074 Automated cherry pick of #5073: fix(9264): baseselect default select includes extraopts
  src/components/BaseSelect/index.vue
Labels: size/XS

#5077 feat: export resource from local
  containers/Compute/views/disk-backup/components/List.vue
  containers/Compute/views/disk-backup/utils/columns.js
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/utils/columns.js
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/servertemplate/components/List.vue
  containers/Compute/views/servertemplate/mixins/columns.js
  containers/Compute/views/snapshot-instance/components/List.vue
  containers/Compute/views/snapshot-instance/mixins/columns.js
  containers/Compute/views/snapshot/components/List.vue
  containers/Compute/views/snapshot/mixins/columns.js
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/utils/columns.js
  containers/Network/views/route-table/components/List.vue
  containers/Network/views/wire/components/List.vue
  containers/Network/views/wire/mixins/columns.js
  containers/Network/views/wire/utils/columns.js
  src/utils/common/tableColumn.js
Labels: size/L

#5078 Automated cherry pick of #5077: feat: export resource from local
  containers/Compute/views/disk-backup/components/List.vue
  containers/Compute/views/disk-backup/utils/columns.js
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/utils/columns.js
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/servertemplate/components/List.vue
  containers/Compute/views/servertemplate/mixins/columns.js
  containers/Compute/views/snapshot-instance/components/List.vue
  containers/Compute/views/snapshot-instance/mixins/columns.js
  containers/Compute/views/snapshot/components/List.vue
  containers/Compute/views/snapshot/mixins/columns.js
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/utils/columns.js
  containers/Network/views/route-table/components/List.vue
  containers/Network/views/wire/components/List.vue
  containers/Network/views/wire/mixins/columns.js
  containers/Network/views/wire/utils/columns.js
  src/utils/common/tableColumn.js
Labels: size/L

#5079 fix: add time to search for whitelist
  src/components/SearchBox/index.vue
Labels: size/XS

#5080 Automated cherry pick of #5079: fix: add time to search for whitelist
  src/components/SearchBox/index.vue
Labels: size/XS

#5082 fix: description edit debug
  src/components/Edit/Form.vue
  src/components/Edit/index.js
  src/components/ListBodyCellWrap/index.vue
Labels: size/S

#5083 Automated cherry pick of #5082: fix: description edit debug
  src/components/Edit/Form.vue
  src/components/Edit/index.js
  src/components/ListBodyCellWrap/index.vue
Labels: size/S

#5081 feat(4444): add bastion host
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/components/BastionHost.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/dialogs/VmAddBastionHostDialog.vue
Labels: size/L

#5084 Automated cherry pick of #5081: feat(4444): add bastion host
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/components/BastionHost.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/dialogs/VmAddBastionHostDialog.vue
Labels: size/L

#5085 fix: description edit no reaction
  src/components/Edit/Form.vue
  src/components/Edit/index.js
  src/components/ListBodyCellWrap/index.vue
Labels: size/M

#5086 Automated cherry pick of #5085: fix: description edit no reaction
  src/components/Edit/Form.vue
  src/components/Edit/index.js
  src/components/ListBodyCellWrap/index.vue
Labels: size/M

#5087 Automated cherry pick of #5085: fix: description edit no reaction
  src/components/Edit/Form.vue
  src/components/ListBodyCellWrap/index.vue
  src/utils/validate.js
Labels: size/M

#5088 feat: update i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#5090 fix(9266): 项目详情删除用户后不会主动刷新，还是无法删除项目
  containers/IAM/views/projects/sidepage/DirectlyUnderUserList.vue
Labels: size/XS

#5091 Automated cherry pick of #5090: fix(9266): 项目详情删除用户后不会主动刷新，还是无法删除项目
  containers/IAM/views/projects/sidepage/DirectlyUnderUserList.vue
Labels: size/XS

#5092 fix(9267): 认证资源改为伪删除后，应兼容伪删除的资源
  src/components/Detail/index.js
Labels: size/S

#5093 Automated cherry pick of #5092: fix(9267): 认证资源改为伪删除后，应兼容伪删除的资源
  src/components/Detail/index.js
Labels: size/S

#5095 Automated cherry pick of #5094: fix: export list data add description check
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#5096 feat(4503): 主机相关统计，增加主机类型的过滤器
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/S

#5097 Automated cherry pick of #5096: feat(4503): 主机相关统计，增加主机类型的过滤器
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/S

#5098 fix: workflow push
  .github/workflows/docker.yml
Labels: size/S

#5099 Automated cherry pick of #5098: fix: workflow push
  .github/workflows/docker.yml
Labels: size/S

#5100 fix: 自定义数据除KVM外不进行数据格式校验
  containers/Compute/views/vminstance/create/components/CustomData.vue
Labels: size/S

#5102 fix: 自定义数据上传文件除KVM外不进行数据格式校验
  containers/Compute/views/vminstance/create/components/CustomData.vue
Labels: size/S

#5104 feat: GPU设备允许更新设备类型
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/gpu/dialogs/UpdateDeviceType.vue
  containers/Compute/views/gpu/locales/en.json
  containers/Compute/views/gpu/locales/zh-CN.json
  containers/Compute/views/gpu/mixins/singleActions.js
Labels: size/L

#5105 fix: docker push
  .github/workflows/docker.yml
  scripts/docker_push.sh
Labels: size/S

#5106 Automated cherry pick of #5105: fix: docker push
  .github/workflows/docker.yml
  scripts/docker_push.sh
Labels: size/S

#5107 Automated cherry pick of #5104: feat: add GPU设备允许更新设备类型
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/gpu/dialogs/UpdateDeviceType.vue
  containers/Compute/views/gpu/locales/en.json
  containers/Compute/views/gpu/locales/zh-CN.json
  containers/Compute/views/gpu/mixins/singleActions.js
Labels: size/L

#5111 fix: add user data params
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/create/components/CustomData.vue
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/S

#5108 fix(9275): resource enable action use post method
  containers/IAM/views/policy/components/List.vue
  containers/IAM/views/policy/mixins/singleActions.js
  containers/IAM/views/user/components/List.vue
  containers/IAM/views/user/mixins/singleActions.js
Labels: size/M

#5109 Automated cherry pick of #5108: fix(9275): resource enable action use post method
  containers/IAM/views/policy/components/List.vue
  containers/IAM/views/policy/mixins/singleActions.js
  containers/IAM/views/user/components/List.vue
  containers/IAM/views/user/mixins/singleActions.js
Labels: size/M

#5113 fix: Nat去掉删除保护校验
  containers/Network/views/nats/mixins/singleActions.js
Labels: size/XS

#5117 fix: console error
  containers/Compute/sections/ServerNetwork/index.vue
Labels: size/XS

#5115 feat(4465): cloudaccount support create project for provider
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/M

#5116 Automated cherry pick of #5115: feat(4465): cloudaccount support create project for provider
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/M

#5119 feat(4278): sku add private cloudenv
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/sku/components/List.vue
  containers/Compute/views/sku/index.vue
  containers/Compute/views/sku/mixins/singleActions.js
Labels: size/L

#5120 Automated cherry pick of #5119: feat(4278): sku add private cloudenv
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/sku/components/List.vue
  containers/Compute/views/sku/index.vue
  containers/Compute/views/sku/mixins/singleActions.js
Labels: size/L

#5121 feat(4338): tag filter add with_user_meta param
  src/components/PageList/TagFilter.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/TagSelect/index.vue
  src/utils/common/tag.js
  src/utils/list.js
Labels: size/M

#5122 Automated cherry pick of #5121: feat(4338): tag filter add with_user_meta param
  src/components/PageList/TagFilter.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/TagSelect/index.vue
  src/utils/common/tag.js
  src/utils/list.js
Labels: size/M

#5123 feat(4502): update ksyun
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/components/Ksyun.vue
Labels: size/M

#5124 feat(4502): add baidu cloud
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/BaiduCloud.vue
  scope/locales/en.json
  scope/locales/zh-CN.json
  src/assets/images/providers/baidu.svg
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#5128 feat(4508): table load more add page-size param
  src/components/PageList/components/Table.vue
  src/components/PageList/components/Table_fixed.vue
  src/components/PageList/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/EventList/index.vue
  src/utils/list.js
Labels: size/M

#5130 Automated cherry pick of #5128: feat(4508): table load more add page-size param
  src/components/PageList/components/Table.vue
  src/components/PageList/components/Table_fixed.vue
  src/components/PageList/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/EventList/index.vue
  src/utils/list.js
Labels: size/M

#5131 feat(4250): domain remote quota from ce
  containers/IAM/views/domains/mixins/singleActions.js
  containers/IAM/views/domains/sidepage/index.vue
  containers/IAM/views/projects/mixins/singleActions.js
  containers/IAM/views/projects/sidepage/index.vue
Labels: size/S

#5132 Automated cherry pick of #5131: feat(4250): domain remote quota from ce
  containers/IAM/views/domains/mixins/singleActions.js
  containers/IAM/views/domains/sidepage/index.vue
  containers/IAM/views/projects/mixins/singleActions.js
  containers/IAM/views/projects/sidepage/index.vue
Labels: size/S

#5133 Automated cherry pick of #5131: feat(4250): domain remote quota from ce
  containers/IAM/views/domains/mixins/singleActions.js
  containers/IAM/views/domains/sidepage/index.vue
  containers/IAM/views/projects/mixins/singleActions.js
  containers/IAM/views/projects/sidepage/index.vue
Labels: size/S

#5135 Automated cherry pick of #5134: feat(4510): create cloudprovider tips accuracy
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
Labels: size/XS

#5136 feat: 优化迁移逻辑控制及校验提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/dialogs/V2vTransfer.vue
  containers/Compute/views/vminstance/utils.js
Labels: size/L

#5137 Automated cherry pick of #5136: feat: 优化迁移逻辑控制及校验提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/dialogs/V2vTransfer.vue
  containers/Compute/views/vminstance/utils.js
Labels: size/L

#5139 Automated cherry pick of #5138: fix: unknown 状态的机器不支持迁移
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/utils.js
Labels: size/S

#5141 feat(4508): log export add scope param
  src/sections/EventList/index.vue
Labels: size/XS

#5142 Automated cherry pick of #5141: feat(4508): log export add scope param
  src/sections/EventList/index.vue
Labels: size/XS

#5144 feat(4502): add china union
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/ChinaUnion.vue
  scope/locales/en.json
  scope/locales/zh-CN.json
  src/assets/images/providers/chinaunion.svg
  src/components/Icon/assets/chinaunion.svg
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/BrandIcon/index.js
  src/utils/common/tableColumn.js
Labels: size/L

#5145 Automated cherry pick of #5136: feat: 优化迁移逻辑控制及校验提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/dialogs/QuickRecovery.vue
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/utils.js
Labels: size/L

#5148 Automated cherry pick of #5147: feat(4420): 修复系统盘和数据盘过滤逻辑不一致问题
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/S

#5149 fix(9279): 托管的机器不支持操作增加提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/mixins/singleActions.js
Labels: size/M

#5150 Automated cherry pick of #5149: fix(9279): 托管的机器不支持操作增加提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/mixins/singleActions.js
Labels: size/M

#5151 Automated cherry pick of #5149: fix(9279): 托管的机器不支持操作增加提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/mixins/singleActions.js
Labels: size/M

#5153 feat(4309): add time zone global config
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/time.js
Labels: size/XL

#5154 fix(9283): 执行脚本优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/S

#5156 fix(9275): user disabled method error
  containers/IAM/views/policy/components/List.vue
  containers/IAM/views/policy/mixins/singleActions.js
  containers/IAM/views/user/components/List.vue
  containers/IAM/views/user/mixins/singleActions.js
Labels: size/M

#5158 Automated cherry pick of #5156: fix(9275): user disabled method error
  containers/IAM/views/policy/components/List.vue
  containers/IAM/views/policy/mixins/singleActions.js
  containers/IAM/views/user/components/List.vue
  containers/IAM/views/user/mixins/singleActions.js
Labels: size/M

#5161 fix: network change wire scope param
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/dialogs/SwitchWire.vue
  containers/Network/views/network/mixins/singleActions.js
Labels: size/S

#5162 fix: network change wire scope param
  containers/Network/views/network/dialogs/SwitchWire.vue
Labels: size/XS

#5163 fix(9283): 公有云执行脚本脚本优化
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#5164 Automated cherry pick of #5163: fix(9283): 公有云执行脚本脚本优化
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#5165 feat(4513): list load more enable virtual scroll
  src/components/EventDrawer/index.vue
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
  src/sections/EventList/index.vue
  src/styles/less/global.less
Labels: size/M

#5166 Automated cherry pick of #5165: feat(4513): list load more enable virtual scroll
  src/components/EventDrawer/index.vue
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
  src/sections/EventList/index.vue
  src/styles/less/global.less
Labels: size/M

#5167 Automated cherry pick of #5165: feat(4513): list load more enable virtual scroll
  src/components/EventDrawer/index.vue
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
  src/sections/EventList/index.vue
  src/styles/less/global.less
Labels: size/M

#5168 fix: 重置密码规则校验提示信息
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#5169 Automated cherry pick of #5168: fix: 重置密码规则校验提示信息
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#5170 Automated cherry pick of #5168: fix: 重置密码规则校验提示信息
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#5171 fix: 重置密码手工输入密码框规则校验提示信息
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#5172 Automated cherry pick of #5171: fix: 重置密码手工输入密码框规则校验提示信息
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#5173 Automated cherry pick of #5171: fix: 重置密码手工输入密码框规则校验提示信息
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#5176 feat: 执行脚本优化，调整类型限制及逻辑处理
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/create/components/CustomData.vue
Labels: size/M

#5174 feat(4506): 透传设备支持vGPU
  containers/Compute/constants/index.js
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/PCI/index.vue
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/gpu/locales/en.json
  containers/Compute/views/gpu/locales/zh-CN.json
  containers/Compute/views/gpu/mixins/singleActions.js
  containers/Compute/views/gpu/sidepage/Detail.vue
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
Labels: size/M

#5175 Automated cherry pick of #5174: feat(4506): 透传设备支持vGPU
  containers/Compute/constants/index.js
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/PCI/index.vue
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/gpu/locales/en.json
  containers/Compute/views/gpu/locales/zh-CN.json
  containers/Compute/views/gpu/mixins/singleActions.js
  containers/Compute/views/gpu/sidepage/Detail.vue
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
Labels: size/M

#5178 feat(4518): hidden resource action column and detail column
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/Compute/views/disk/sidepage/index.vue
  containers/Compute/views/snapshot/components/List.vue
  containers/Compute/views/snapshot/sidepage/Detail.vue
  containers/Compute/views/snapshot/sidepage/index.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/mongodb/sidepage/Detail.vue
  containers/DB/views/mongodb/sidepage/index.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/sidepage/Detail.vue
  containers/DB/views/rds/sidepage/index.vue
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/sidepage/Detail.vue
  containers/DB/views/redis/sidepage/index.vue
  containers/Network/views/eip/sidepage/Detail.vue
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/sidepage/Detail.vue
  containers/Network/views/lb/sidepage/index.vue
  containers/Network/views/vpc/components/List.vue
  containers/Network/views/vpc/mixins/columns.js
  containers/Network/views/vpc/sidepage/Detail.vue
  containers/Network/views/vpc/sidepage/index.vue
  containers/Storage/views/bucket/components/List.vue
  containers/Storage/views/bucket/sidepage/Detail.vue
  containers/Storage/views/bucket/sidepage/index.vue
  src/components/Detail/index.js
  src/components/PageList/components/Header.vue
  src/permission.js
  src/sections/Navbar/index.vue
  src/utils/common/detailColumn.js
  src/utils/common/tableColumn.js
  src/utils/list.js
Labels: size/L

#5179 Automated cherry pick of #5178: feat(4518): hidden resource action column and detail column
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/Compute/views/disk/sidepage/index.vue
  containers/Compute/views/snapshot/components/List.vue
  containers/Compute/views/snapshot/sidepage/Detail.vue
  containers/Compute/views/snapshot/sidepage/index.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/mongodb/sidepage/Detail.vue
  containers/DB/views/mongodb/sidepage/index.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/sidepage/Detail.vue
  containers/DB/views/rds/sidepage/index.vue
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/sidepage/Detail.vue
  containers/DB/views/redis/sidepage/index.vue
  containers/Network/views/eip/sidepage/Detail.vue
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/sidepage/Detail.vue
  containers/Network/views/lb/sidepage/index.vue
  containers/Network/views/vpc/components/List.vue
  containers/Network/views/vpc/mixins/columns.js
  containers/Network/views/vpc/sidepage/Detail.vue
  containers/Network/views/vpc/sidepage/index.vue
  containers/Storage/views/bucket/components/List.vue
  containers/Storage/views/bucket/sidepage/Detail.vue
  containers/Storage/views/bucket/sidepage/index.vue
  src/components/Detail/index.js
  src/components/PageList/components/Header.vue
  src/permission.js
  src/sections/Navbar/index.vue
  src/utils/common/detailColumn.js
  src/utils/common/tableColumn.js
  src/utils/list.js
Labels: size/L

#5180 feat(4518): hidden resource filter
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/snapshot/components/List.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/sidepage/index.vue
  containers/Network/views/lb/components/List.vue
  containers/Network/views/vpc/components/List.vue
  containers/Storage/views/bucket/components/List.vue
  src/utils/common/tableFilter.js
  src/utils/list.js
Labels: size/M

#5181 Automated cherry pick of #5180: feat(4518): hidden resource filter
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/snapshot/components/List.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/sidepage/index.vue
  containers/Network/views/lb/components/List.vue
  containers/Network/views/vpc/components/List.vue
  containers/Storage/views/bucket/components/List.vue
  src/utils/common/tableFilter.js
  src/utils/list.js
Labels: size/M

#5182 fix: 修复虚拟机添加网卡网络参数问题
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: size/XS

#5183 Automated cherry pick of #5182: fix: 修复虚拟机添加网卡网络参数问题
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: size/XS

#5184 Automated cherry pick of #5182: fix: 修复虚拟机添加网卡网络参数问题
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
Labels: size/XS

#5187 fix(9283): 修复文件上传参数问题
  containers/Compute/views/vminstance/create/components/CustomData.vue
Labels: size/M

#5186 Automated cherry pick of #5185: fix(9290): 删除工单列表，资源名称列表为空
  src/utils/utils.js
Labels: size/XS

#5189 add dictionary items for cloud env
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/sidepage/snapshot.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/K8S/locales/zh-CN.json
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/mixins/columns.js
  containers/Network/views/network/sidepage/Detail.vue
  containers/Network/views/network/sidepage/index.vue
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/permission.js
Labels: size/L

#5190 Automated cherry pick of #5189: add dictionary items for cloud env
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/sidepage/snapshot.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/K8S/locales/zh-CN.json
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/mixins/columns.js
  containers/Network/views/network/sidepage/Detail.vue
  containers/Network/views/network/sidepage/index.vue
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/permission.js
Labels: size/L

#5193 fix(9282): server numbers panel link path error
  containers/Dashboard/extends/ServerNumberDetail/index.vue
Labels: size/XS

#5195 Automated cherry pick of #5193: fix(9282): server numbers panel link path error
  containers/Dashboard/extends/ServerNumberDetail/index.vue
Labels: size/XS

#5194 Automated cherry pick of #5193: fix(9282): server numbers panel link path error
  containers/Dashboard/extends/ServerNumberDetail/index.vue
Labels: size/XS

#5196 add mutiple base select style
  src/styles/less/global.less
Labels: size/XS

#5197 Automated cherry pick of #5196: add mutiple base select style
  src/styles/less/global.less
Labels: size/XS

#5198 feat: add vxe-table style
  src/styles/less/global.less
Labels: size/XS

#5199 Automated cherry pick of #5198: feat: add vxe-table style
  src/styles/less/global.less
Labels: size/XS

#5200 Automated cherry pick of #5198: feat: add vxe-table style
  src/styles/less/global.less
Labels: size/XS

#5202 Automated cherry pick of #5201: fix(9292): 系统镜像中按系统过滤应该加上nfs的选项支持查询方德的镜像
  src/utils/common/tableFilter.js
Labels: size/XS

#5203 Automated cherry pick of #5201: fix(9292): 系统镜像中按系统过滤应该加上nfs的选项支持查询方德的镜像
  src/utils/common/tableFilter.js
Labels: size/XS

#5205 Automated cherry pick of #5204: fix: 调整校验提示信息避免产生歧义
  src/locales/zh-CN.json
Labels: size/S

#5206 Automated cherry pick of #5204: fix: 调整校验提示信息避免产生歧义
  src/locales/zh-CN.json
Labels: size/S

#5207 feat(4406): notify add silent param
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/notify-subscriber/components/List.vue
  containers/IAM/views/notify-subscriber/dialogs/SetupNotifyReceiver.vue
  containers/IAM/views/notify-subscriber/mixins/columns.js
Labels: size/M

#5208 fix: remove console log
  src/components/Detail/index.js
Labels: size/XS

#5209 Automated cherry pick of #5208: fix: remove console log
  src/components/Detail/index.js
Labels: size/XS

#5210 fix(9285): 重置密码MFA交互需要统一
  containers/Compute/views/vminstance/dialogs/ResetPassword.vue
Labels: size/M

#5211 Automated cherry pick of #5210: fix(9285): 重置密码MFA交互需要统一
  containers/Compute/views/vminstance/dialogs/ResetPassword.vue
Labels: size/M

#5212 fix: storage used capacity by medium type
  containers/Dashboard/constants/index.js
  containers/Dashboard/sections/QuotaConfig/index.vue
  src/constants/generalUsage.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#5213 Automated cherry pick of #5212: fix: storage used capacity by medium type
  containers/Dashboard/constants/index.js
  containers/Dashboard/sections/QuotaConfig/index.vue
  src/constants/generalUsage.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#5214 fix: 初始化页面请求接口及开源版本增加限制
  containers/Compute/views/vminstance/create/components/BastionHost.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/S

#5216 Automated cherry pick of #5207: feat(4406): notify add silent param
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/notify-subscriber/components/List.vue
  containers/IAM/views/notify-subscriber/dialogs/SetupNotifyReceiver.vue
  containers/IAM/views/notify-subscriber/mixins/columns.js
Labels: size/M

#5217 feat(4442): notify add notification time
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/notify-topic/dialogs/UpdateNotifyTime.vue
  containers/IAM/views/notify-topic/sidepage/Detail.vue
Labels: size/L

#5218 Automated cherry pick of #5217: feat(4442): notify add notification time
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/notify-topic/dialogs/UpdateNotifyTime.vue
  containers/IAM/views/notify-topic/sidepage/Detail.vue
Labels: size/L
