Repository yunionio/dashboard, pull requests merged in 2023-06, with the labels that each got.

#4735 feat(4351): 列表搜索支持多个IP及ID
  src/components/SearchBox/AutoCompleter.vue
  src/components/SearchBox/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#4737 Automated cherry pick of #4735: feat(4351): 列表搜索支持多个IP及ID
  src/components/SearchBox/AutoCompleter.vue
  src/components/SearchBox/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#4740 Automated cherry pick of #4739: feat: 更新列表增加同时查询多个IP、多个UUID
  src/components/SearchBox/AutoCompleter.vue
  src/components/SearchBox/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#4741 Automated cherry pick of #4739: feat: 更新列表增加同时查询多个IP、多个UUID
  src/components/SearchBox/AutoCompleter.vue
  src/components/SearchBox/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#4743 feat: name-description table column extend
  src/utils/common/tableColumn.js
Labels: size/XS

#4744 Automated cherry pick of #4743: feat: name-description table column extend
  src/utils/common/tableColumn.js
Labels: size/XS

#4747 Automated cherry pick of #4690: feat: add permission
  src/constants/permission.js
Labels: size/XS

#4748 feat: 调整列表同时查询多个IP、多个UUID
  src/components/SearchBox/AutoCompleter.vue
  src/components/SearchBox/index.vue
Labels: size/S

#4749 Automated cherry pick of #4748: feat: 调整列表同时查询多个IP、多个UUID
  src/components/SearchBox/AutoCompleter.vue
  src/components/SearchBox/index.vue
Labels: size/S

#4764 feat(4308): 新建vmware云账号，建议用户先配置网络
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
Labels: size/S

#4765 Automated cherry pick of #4764: feat(4308): 新建vmware云账号，建议用户先配置网络
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
Labels: size/S

#4766 Automated cherry pick of #4764: feat(4308): 新建vmware云账号，建议用户先配置网络
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
Labels: size/S

#4824 fix(build): use web-base:v3.10.3-20230619.1
  Dockerfile
Labels: size/XS

#4825 Automated cherry pick of #4824: fix(build): use web-base:v3.10.3-20230619.1
  Dockerfile
Labels: size/XS

#4823 feat: workflow support export attachment
  src/views/workflow/components/ApplyInternalResource.vue
  src/views/workflow/me-process/components/List.vue
Labels: size/M

#4826 Automated cherry pick of #4823: feat: workflow support export attachment
  src/views/workflow/components/ApplyInternalResource.vue
  src/views/workflow/me-process/components/List.vue
Labels: size/M

#4827 fix: ssh params error
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#4828 Automated cherry pick of #4827: fix: ssh params error
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#4829 feat(4371): 云账号-资源统计修改为开机率指标
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/sections/UsageSidepage/constants.js
  src/constants/color.js
Labels: size/S

#4830 Automated cherry pick of #4829: feat(4371): 云账号-资源统计修改为开机率指标
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/sections/UsageSidepage/constants.js
  src/constants/color.js
Labels: size/S

#4831 Automated cherry pick of #4829: feat(4371): 云账号-资源统计修改为开机率指标
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/sections/UsageSidepage/constants.js
  src/constants/color.js
Labels: size/S

#4834 Automated cherry pick of #4832: feat(4051): 项目列表增加过滤条件：用户，组，认证源。域，组，用户列表增加过滤条件：认证源
  containers/IAM/views/domains/components/List.vue
  containers/IAM/views/group/components/List.vue
  containers/IAM/views/projects/components/List.vue
  containers/IAM/views/user/components/List.vue
Labels: size/S

#4835 feat(4152): 虚拟机过滤项：区域、云订阅、类型、vpc、cpu架构支持多选
  containers/Compute/views/vminstance/components/List.vue
  src/utils/common/tableFilter.js
Labels: size/XS

#4836 Automated cherry pick of #4835: feat(4152): 虚拟机过滤项：区域、云订阅、类型、vpc、cpu架构支持多选
  containers/Compute/views/vminstance/components/List.vue
  src/utils/common/tableFilter.js
Labels: size/XS

#4837 fix(9108): monitor overview use id for data set key
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: area/monitor, size/S

#4838 Automated cherry pick of #4837: fix(9108): monitor overview use id for data set key
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/S

#4839 fix(9126): 有定时任务权限的用户，在新建定时任务时不应该报权限不足
  src/constants/permission.js
Labels: size/S

#4840 Automated cherry pick of #4839: fix(9126): 有定时任务权限的用户，在新建定时任务时不应该报权限不足
  src/constants/permission.js
Labels: size/S

#4841 fix(4359): workflow type show error
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/XS

#4842 Automated cherry pick of #4841: fix(4359): workflow type show error
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/XS

#4843 feat(4392): 主机导出列表增加初始账号和密码两列
  containers/Compute/views/vminstance/components/List.vue
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/components/PageList/components/Header.vue
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/M

#4844 Automated cherry pick of #4843: feat(4392): 主机导出列表增加初始账号和密码两列
  containers/Compute/views/vminstance/components/List.vue
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/components/PageList/components/Header.vue
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/M

#4845 feat(4398): workflow hidden status column
  src/components/FixedLabelFilter/index.vue
  src/sections/Navbar/index.vue
  src/views/workflow/all-process/mixins/columns.js
  src/views/workflow/all-process/sidepage/Detail.vue
  src/views/workflow/all-process/sidepage/index.vue
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/approval-start/sidepage/index.vue
  src/views/workflow/approved-done/sidepage/Detail.vue
  src/views/workflow/approved-done/sidepage/index.vue
  src/views/workflow/me-partake/sidepage/Detail.vue
  src/views/workflow/me-partake/sidepage/index.vue
  src/views/workflow/me-process/sidepage/Detail.vue
  src/views/workflow/me-process/sidepage/index.vue
Labels: size/M

#4846 Automated cherry pick of #4845: feat(4398): workflow hidden status column
  src/components/FixedLabelFilter/index.vue
  src/sections/Navbar/index.vue
  src/views/workflow/all-process/mixins/columns.js
  src/views/workflow/all-process/sidepage/Detail.vue
  src/views/workflow/all-process/sidepage/index.vue
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/approval-start/sidepage/index.vue
  src/views/workflow/approved-done/sidepage/Detail.vue
  src/views/workflow/approved-done/sidepage/index.vue
  src/views/workflow/me-partake/sidepage/Detail.vue
  src/views/workflow/me-partake/sidepage/index.vue
  src/views/workflow/me-process/sidepage/Detail.vue
  src/views/workflow/me-process/sidepage/index.vue
Labels: size/M

#4847 fix(9136): GCP账单设置改进
  containers/Cloudenv/views/cloudaccount/create/BillFileIndex.vue
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
Labels: size/XS

#4848 fix(baremetal): baremetal ssh login
  containers/Compute/views/physicalmachine/mixins/singleActions.js
Labels: area/compute, size/XS

#4849 Automated cherry pick of #4848: fix(baremetal): baremetal ssh login
  containers/Compute/views/physicalmachine/mixins/singleActions.js
Labels: size/XS

#4850 Automated cherry pick of #4848: fix(baremetal): baremetal ssh login
  containers/Compute/views/physicalmachine/mixins/singleActions.js
Labels: size/XS

#4851 feat: workflow support update info
  src/views/workflow/all-process/sidepage/Detail.vue
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/approved-done/sidepage/Detail.vue
  src/views/workflow/components/ApplyInternalResource.vue
  src/views/workflow/me-partake/sidepage/Detail.vue
  src/views/workflow/me-process/sidepage/Detail.vue
  src/views/workflow/utils/columns.js
Labels: size/S

#4852 Automated cherry pick of #4851: feat: workflow support update info
  src/views/workflow/all-process/sidepage/Detail.vue
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/approved-done/sidepage/Detail.vue
  src/views/workflow/components/ApplyInternalResource.vue
  src/views/workflow/me-partake/sidepage/Detail.vue
  src/views/workflow/me-process/sidepage/Detail.vue
  src/views/workflow/utils/columns.js
Labels: size/S

#4853 fix(9142): 虚拟机导出Excel文件IP列宽度不应该为0
  containers/Compute/views/vminstance/components/List.vue
  src/sections/DialogManager/components/ExportListData.vue
  src/utils/common/tableColumn.js
Labels: size/S

#4854 Automated cherry pick of #4853: fix(9142): 虚拟机导出Excel文件IP列宽度不应该为0
  containers/Compute/views/vminstance/components/List.vue
  src/sections/DialogManager/components/ExportListData.vue
  src/utils/common/tableColumn.js
Labels: size/S

#4857 fix: support pve create
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/utils.js
  containers/Storage/router/index.js
Labels: size/M

#4858 Automated cherry pick of #4857: fix: support pve create
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/utils.js
  containers/Storage/router/index.js
Labels: size/M

#4855 feat: workflow update info
  src/sections/DialogManager/components/ExportListData.vue
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/M

#4856 Automated cherry pick of #4855: feat: workflow update info
  src/sections/DialogManager/components/ExportListData.vue
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/M

#4859 fix(9141): 系统镜像筛选系统优化
  src/components/ImageIcon/constants.js
  src/utils/common/tableFilter.js
Labels: size/XS

#4860 Automated cherry pick of #4859: fix(9141): 系统镜像筛选系统优化
  src/components/ImageIcon/constants.js
  src/utils/common/tableFilter.js
Labels: size/XS

#4861 feat: workflow donot support update info
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/XS

#4862 Automated cherry pick of #4861: feat: workflow donot support update info
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/XS
