Repository yunionio/dashboard, pull requests merged in 2023-04, with the labels that each got.

#4419 feat: workflow details
  src/views/workflow/all-process/sidepage/Detail.vue
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/approved-done/sidepage/Detail.vue
  src/views/workflow/components/ApplyInternalResource.vue
  src/views/workflow/me-partake/sidepage/Detail.vue
  src/views/workflow/me-process/sidepage/Detail.vue
Labels: size/S

#4420 Automated cherry pick of #4419: feat: workflow details
  src/views/workflow/all-process/sidepage/Detail.vue
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/approved-done/sidepage/Detail.vue
  src/views/workflow/components/ApplyInternalResource.vue
  src/views/workflow/me-partake/sidepage/Detail.vue
  src/views/workflow/me-process/sidepage/Detail.vue
Labels: size/S

#4421 fix: lb cluster update desc params
  containers/Network/views/loadbalancercluster/update/index.vue
Labels: size/XS

#4422 Automated cherry pick of #4421: fix: lb cluster update desc params
  containers/Network/views/loadbalancercluster/update/index.vue
Labels: size/XS

#4423 fix: lb agent update desc params
  containers/Network/views/agent/form/index.vue
Labels: size/XS

#4424 Automated cherry pick of #4423: fix: lb agent update desc params
  containers/Network/views/agent/form/index.vue
Labels: size/XS

#4425 fix(8890): 使用主机快照或主机镜像新建虚拟机时，系统盘容量不应该为空
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/S

#4426 Automated cherry pick of #4425: fix(8890): 使用主机快照或主机镜像新建虚拟机时，系统盘容量不应该为空
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/S

#4427 Automated cherry pick of #4425: fix(8890): 使用主机快照或主机镜像新建虚拟机时，系统盘容量不应该为空
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/S

#4429 Automated cherry pick of #4428: fix: show last sync cost
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  containers/Cloudenv/views/cloudprovider/mixins/columns.js
  containers/Cloudenv/views/cloudproviderregion/mixins/columns.js
Labels: size/M

#4430 Automated cherry pick of #4428: fix: show last sync cost
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  containers/Cloudenv/views/cloudprovider/mixins/columns.js
  containers/Cloudenv/views/cloudproviderregion/mixins/columns.js
Labels: size/M

#4431 feat: event list filter
  src/sections/EventList/index.vue
Labels: size/M

#4432 Automated cherry pick of #4431: feat: event list filter
  src/sections/EventList/index.vue
Labels: size/M

#4433 feat: add component tag-group
  src/components/TagGroup/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/L

#4434 Automated cherry pick of #4433: feat: add component tag-group
  src/components/TagGroup/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/L

#4436 Automated cherry pick of #4435: feat: add common dialog import-data
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/ImportData.vue
Labels: size/L

#4437 fix: common tablefilter i18n error
  src/utils/common/tableFilter.js
Labels: size/XS

#4440 Automated cherry pick of #4437: fix: common tablefilter i18n error
  src/utils/common/tableFilter.js
Labels: size/XS

#4439 Automated cherry pick of #4437: fix: common tablefilter i18n error
  src/utils/common/tableFilter.js
Labels: size/XS

#4438 Automated cherry pick of #4437: fix: common tablefilter i18n error
  src/utils/common/tableFilter.js
Labels: size/XS

#4441 feat: workflow support send email
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/M

#4442 Automated cherry pick of #4441: feat: workflow support send email
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/M

#4443 fix: cloudaccount double import columns.js
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
Labels: size/XS

#4445 Automated cherry pick of #4443: fix: cloudaccount double import columns.js
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
Labels: size/XS

#4446 fix: allow no prelaod list data
  src/utils/list.js
Labels: size/XS

#4447 Automated cherry pick of #4446: fix: allow no prelaod list data
  src/utils/list.js
Labels: size/XS

#4448 fix: time select accuracy
  containers/Monitor/sections/KindTabs/index.vue
  src/components/DateTime/CustomDate.vue
  src/components/DateTime/index.vue
Labels: size/XS

#4450 Automated cherry pick of #4448: fix: time select accuracy
  containers/Monitor/sections/KindTabs/index.vue
  src/components/DateTime/CustomDate.vue
  src/components/DateTime/index.vue
Labels: size/XS

#4449 Automated cherry pick of #4448: fix: time select accuracy
  containers/Monitor/sections/KindTabs/index.vue
  src/components/DateTime/CustomDate.vue
  src/components/DateTime/index.vue
Labels: size/XS

#4451 feat: common dialog import-data accuracy
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/ImportData.vue
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/S

#4452 Automated cherry pick of #4451: feat: add common dialog import-data
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/ImportData.vue
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/S

#4454 fix: hcso do not show host
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#4455 Automated cherry pick of #4454: fix: hcso do not show host
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#4456 feat: cloudaccount set project-mapping
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
Labels: area/cloudenv, size/L

#4457 Automated cherry pick of #4456: feat: cloudaccount set project-mapping
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
Labels: size/L

#4459 Automated cherry pick of #4458: feat(4256): 宿主机详情页增加预留核数
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/sidepage/Detail.vue
Labels: size/S

#4462 feat: 去掉错误源信息中的时间由后端统一提供
  src/sections/DialogManager/components/Error.vue
Labels: size/XS

#4463 Automated cherry pick of #4462: feat: 去掉错误源信息中的时间由后端统一提供
  src/sections/DialogManager/components/Error.vue
Labels: size/XS

#4465 Automated cherry pick of #4462: feat: 去掉错误源信息中的时间由后端统一提供
  src/sections/DialogManager/components/Error.vue
Labels: size/XS

#4464 Automated cherry pick of #4462: feat: 去掉错误源信息中的时间由后端统一提供
  src/sections/DialogManager/components/Error.vue
Labels: size/XS

#4467 Automated cherry pick of #4466: feat: update gitignore file
  .gitignore
Labels: size/XS

#4469 Automated cherry pick of #4466: feat: update gitignore file
  .gitignore
Labels: size/XS

#4468 Automated cherry pick of #4466: feat: update gitignore file
  .gitignore
Labels: size/XS

#4470 feat(4279): 项目费用分摊开关应有分摊策略才展示
  src/main.js
Labels: size/XS

#4471 Automated cherry pick of #4470: feat(4279): 项目费用分摊开关应有分摊策略才展示
  src/main.js
Labels: size/XS

#4472 fix(k8s): resources is missing
  containers/K8S/utils/index.js
Labels: area/k8s, size/XS

#4473 Automated cherry pick of #4472: fix(k8s): resources is missing
  containers/K8S/utils/index.js
Labels: size/XS

#4474 Automated cherry pick of #4472: fix(k8s): resources is missing
  containers/K8S/utils/index.js
Labels: size/XS

#4475 fix(8902): domain-project select add limit 20
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/BingoCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/H3C.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCS.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSOP.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/InCloudSphere.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Nutanix.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Proxmox.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/RemoteFile.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/S3CephXsky.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  src/components/BaseSelect/index.vue
  src/sections/DialogManager/components/ChangeOwenr.vue
  src/sections/DomainProject/index.vue
  src/sections/DomainProject/last.vue
  src/sections/ScopeRadio/index.vue
Labels: area/cloudenv, size/XXL

#4476 Automated cherry pick of #4475: fix(8902): domain-project select add limit 20
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/BingoCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/H3C.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCS.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSOP.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/InCloudSphere.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Nutanix.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Proxmox.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/RemoteFile.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/S3CephXsky.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  src/components/BaseSelect/index.vue
  src/sections/DialogManager/components/ChangeOwenr.vue
  src/sections/DomainProject/index.vue
  src/sections/DomainProject/last.vue
  src/sections/ScopeRadio/index.vue
Labels: size/XXL

#4477 feat: add bill tasks
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/billtasks/components/List.vue
  containers/Cloudenv/views/billtasks/dialogs/Cancel.vue
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
  containers/Cloudenv/views/billtasks/index.vue
  containers/Cloudenv/views/billtasks/mixins/columns.js
  containers/Cloudenv/views/billtasks/mixins/singleActions.js
  containers/Cloudenv/views/billtasks/sidepage/Detail.vue
  containers/Cloudenv/views/billtasks/sidepage/index.vue
  containers/Cloudenv/views/cloudaccount/sidepage/Schedule.vue
  src/utils/auth.js
Labels: area/cloudenv, size/XL

#4478 Automated cherry pick of #4477: feat: add bill tasks
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/billtasks/components/List.vue
  containers/Cloudenv/views/billtasks/dialogs/Cancel.vue
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
  containers/Cloudenv/views/billtasks/index.vue
  containers/Cloudenv/views/billtasks/mixins/columns.js
  containers/Cloudenv/views/billtasks/mixins/singleActions.js
  containers/Cloudenv/views/billtasks/sidepage/Detail.vue
  containers/Cloudenv/views/billtasks/sidepage/index.vue
  containers/Cloudenv/views/cloudaccount/sidepage/Schedule.vue
  src/utils/auth.js
Labels: size/XL

#4479 feat(4280): refresh billtasks after rerun bill
  containers/Cloudenv/views/billtasks/components/List.vue
Labels: area/cloudenv, size/XS

#4480 Automated cherry pick of #4479: feat(4280): refresh billtasks after rerun bill
  containers/Cloudenv/views/billtasks/components/List.vue
Labels: size/XS

#4481 fix(8934): billtask time select change to range
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
Labels: size/M, area/cloudenv

#4482 Automated cherry pick of #4481: fix(8934): billtask time select change to range
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
Labels: size/M

#4483 fix(8935): create cloudaccount show success info when test post success just one time
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: area/cloudenv, size/XS

#4484 Automated cherry pick of #4483: fix(8935): create cloudaccount show success info when test post success just one time
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: size/XS

#4485 Automated cherry pick of #4483: fix(8935): create cloudaccount show success info when test post success just one time
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: size/XS

#4488 fix(K8S): wrong backend and medium setting for disk
  containers/K8S/views/cluster/create/index.vue
  containers/K8S/views/kube-machines/dialogs/CreateKubemachinesDialog.vue
Labels: area/k8s, size/S

#4491 fix(monitor): use skip_check_series for host monitor
  containers/Compute/views/host/sidepage/Monitor.vue
Labels: size/XS

#4492 Automated cherry pick of #4491: fix(monitor): use skip_check_series for host monitor
  containers/Compute/views/host/sidepage/Monitor.vue
Labels: size/XS

#4493 Automated cherry pick of #4491: fix(monitor): use skip_check_series for host monitor
  containers/Compute/views/host/sidepage/Monitor.vue
Labels: size/XS

#4486 feat: import data dialog add data validator
  src/sections/DialogManager/components/ImportData.vue
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/M

#4487 Automated cherry pick of #4486: feat: import data dialog add data validator
  src/sections/DialogManager/components/ImportData.vue
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/M

#4494 fix(8945): 新建Proxmox云账号时端口默认值应该改为8006
  containers/Cloudenv/views/cloudaccount/create/form/components/Proxmox.vue
Labels: size/XS

#4495 Automated cherry pick of #4494: fix(8945): 新建Proxmox云账号时端口默认值应该改为8006
  containers/Cloudenv/views/cloudaccount/create/form/components/Proxmox.vue
Labels: size/XS

#4507 feat(4295): 新建 内置私有云 虚拟机系统盘及数据盘的大小需要遵循 instance_capability 返回的大小
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/S

#4508 Automated cherry pick of #4507: feat(4295): 新建 内置私有云 虚拟机系统盘及数据盘的大小需要遵循 instance_capability 返回的大小
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/S

#4509 Automated cherry pick of #4507: feat(4295): 新建 内置私有云 虚拟机系统盘及数据盘的大小需要遵循 instance_capability 返回的大小
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/S

#4496 fix(8888): common table add pager type
  src/components/PageList/components/Table.vue
  src/components/PageList/components/Table_fixed.vue
  src/components/PageList/index.vue
  src/utils/list.js
Labels: size/S

#4497 Automated cherry pick of #4496: fix(8888): common table add pager type
  src/components/PageList/components/Table.vue
  src/components/PageList/components/Table_fixed.vue
  src/components/PageList/index.vue
  src/utils/list.js
Labels: size/S

#4498 Automated cherry pick of #4496: fix(8888): common table add pager type
  src/components/PageList/components/Table.vue
  src/components/PageList/components/Table_fixed.vue
  src/components/PageList/index.vue
  src/utils/list.js
Labels: size/S

#4499 fix(8940): eip bandwidth do not limit brand
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/sidepage/Detail.vue
Labels: area/network, size/XS

#4501 Automated cherry pick of #4499: fix(8940): eip bandwidth do not limit brand
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/sidepage/Detail.vue
Labels: size/XS

#4502 feat: billtasks list add id column
  containers/Cloudenv/views/billtasks/mixins/columns.js
Labels: area/cloudenv, size/XS

#4503 Automated cherry pick of #4502: feat: billtasks list add id column
  containers/Cloudenv/views/billtasks/mixins/columns.js
Labels: size/XS

#4504 fix(8940): host resources show usage detail
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/sidepage/Dashboard.vue
  src/sections/ProgressCard/index.vue
Labels: area/compute, size/S

#4505 Automated cherry pick of #4504: fix(8940): host resources show usage detail
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/sidepage/Dashboard.vue
  src/sections/ProgressCard/index.vue
Labels: size/S

#4506 Automated cherry pick of #4504: fix(8940): host resources show usage detail
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/sidepage/Dashboard.vue
  src/sections/ProgressCard/index.vue
Labels: size/S

#4512 fix(8950): vminstance detail iso copy message
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/M, area/compute

#4513 Automated cherry pick of #4512: fix(8950): vminstance detail iso copy message
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/M

#4514 Automated cherry pick of #4512: fix(8950): vminstance detail iso copy message
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/M

#4515 feat(4296): add dictionary key rate
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#4516 Automated cherry pick of #4515: feat(4296): add dictionary key rate
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#4510 feat(4299): bill task add task id
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/billtasks/mixins/columns.js
Labels: area/cloudenv, size/XS

#4511 Automated cherry pick of #4510: feat(4299): bill task add task id
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/billtasks/mixins/columns.js
Labels: size/XS

#4521 fix: 修复套餐为空时，sku值为空对象导致非空校验失效问题
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#4522 Automated cherry pick of #4521: fix: 修复套餐为空时，sku值为空对象导致非空校验失效问题
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#4519 feat(4286): add account sync quickly method
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/M, area/cloudenv

#4520 Automated cherry pick of #4519: feat(4286): add account sync quickly method
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/M

#4523 Automated cherry pick of #4521: fix: 修复套餐为空时，sku值为空对象导致非空校验失效问题
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#4524 Automated cherry pick of #4521: fix: 修复套餐为空时，sku值为空对象导致非空校验失效问题
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#4530 feat: Proxmox 连接测试参数调整
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: size/XS

#4531 Automated cherry pick of #4530: feat: Proxmox 连接测试参数调整
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: size/XS

#4525 fix(8931): monitor overview data unit formatter
  containers/Monitor/components/MonitorCard/sections/chart/formatters.js
Labels: area/monitor, size/XS

#4526 Automated cherry pick of #4525: fix(8931): monitor overview data unit formatter
  containers/Monitor/components/MonitorCard/sections/chart/formatters.js
Labels: size/XS

#4527 Automated cherry pick of #4525: fix(8931): monitor overview data unit formatter
  containers/Monitor/components/MonitorCard/sections/chart/formatters.js
Labels: size/XS

#4528 fix(8902): domain-project select add limit 20
  containers/Cloudenv/sections/ConditionSelect/index.vue
  containers/Cloudenv/views/schedpolicy/components/Form.vue
  src/components/BaseSelect/index.vue
  src/sections/ScopeRadio/index.vue
Labels: size/M

#4529 Automated cherry pick of #4528: fix(8902): domain-project select add limit 20
  containers/Cloudenv/sections/ConditionSelect/index.vue
  containers/Cloudenv/views/schedpolicy/components/Form.vue
  src/components/BaseSelect/index.vue
  src/sections/ScopeRadio/index.vue
Labels: size/M

#4532 fix(8954): external project name edit limit brand
  containers/Cloudenv/views/externalproject/components/List.vue
Labels: area/cloudenv, size/XS

#4534 Automated cherry pick of #4532: fix(8954): external project name edit limit brand
  containers/Cloudenv/views/externalproject/components/List.vue
Labels: size/XS

#4535 fix(h3c): rds metric
  containers/DB/constants/index.js
  containers/DB/views/rds/sidepage/Monitor.vue
Labels: size/XS

#4536 Automated cherry pick of #4535: fix(h3c): rds metric
  containers/DB/constants/index.js
  containers/DB/views/rds/sidepage/Monitor.vue
Labels: size/XS

#4537 fix(8956): cloudenv bill-task add account_id params
  containers/Cloudenv/views/cloudaccount/sidepage/Schedule.vue
  containers/Cloudenv/views/cloudaccount/sidepage/index.vue
Labels: area/cloudenv, size/XS

#4538 Automated cherry pick of #4537: fix(8956): cloudenv bill-task add account_id params
  containers/Cloudenv/views/cloudaccount/sidepage/Schedule.vue
  containers/Cloudenv/views/cloudaccount/sidepage/index.vue
Labels: size/XS

#4539 fix(8940): host resource-dashboard show reserved cpus
  containers/Compute/views/host/sidepage/Dashboard.vue
Labels: area/compute, size/S

#4540 Automated cherry pick of #4539: fix(8940): host resource-dashboard show reserved cpus
  containers/Compute/views/host/sidepage/Dashboard.vue
Labels: size/S

#4541 Automated cherry pick of #4539: fix(8940): host resource-dashboard show reserved cpus
  containers/Compute/views/host/sidepage/Dashboard.vue
Labels: size/S

#4542 fix(8902): user join project add limit 20 param for projects
  containers/IAM/views/projects/dialogs/Add.vue
  containers/IAM/views/user/dialogs/ProjectJoin.vue
Labels: size/L

#4543 Automated cherry pick of #4542: fix(8902): user join project add limit 20 param for projects
  containers/IAM/views/projects/dialogs/Add.vue
  containers/IAM/views/user/dialogs/ProjectJoin.vue
Labels: size/L

#4544 feat(4286): cloudaccount sync add sync mode
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/M, area/cloudenv

#4545 Automated cherry pick of #4544: feat(4286): cloudaccount sync add sync mode
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/M

#4546 feat(4283): 迁移最大带宽限制改进
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/S

#4547 Automated cherry pick of #4546: feat(4283): 迁移最大带宽限制改进
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/S

#4548 Automated cherry pick of #4546: feat(4283): 迁移最大带宽限制改进
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/S

#4555 feat(4303): SaaS的注册页和重置密码页，改几处placeholder的文案
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#4556 Automated cherry pick of #4555: feat(4303): SaaS的注册页和重置密码页，改几处placeholder的文案
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#4557 Automated cherry pick of #4555: feat(4303): SaaS的注册页和重置密码页，改几处placeholder的文案
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#4549 fix(8960): secgroup detail show status
  containers/Compute/views/secgroup/sidepage/Detail.vue
Labels: area/compute, size/XS

#4550 Automated cherry pick of #4549: fix(8960): secgroup detail show status
  containers/Compute/views/secgroup/sidepage/Detail.vue
Labels: size/XS

#4551 Automated cherry pick of #4549: fix(8960): secgroup detail show status
  containers/Compute/views/secgroup/sidepage/Detail.vue
Labels: size/XS

#4552 fix(8960): lbcert detail show status
  containers/Network/views/lbcerts/components/List.vue
  containers/Network/views/lbcerts/sidepage/Detail.vue
Labels: area/network

#4553 Automated cherry pick of #4552: fix(8960): lbcert detail show status
  containers/Network/views/lbcerts/components/List.vue
  containers/Network/views/lbcerts/sidepage/Detail.vue
Labels: size/M

#4554 Automated cherry pick of #4552: fix(8960): lbcert detail show status
  containers/Network/views/lbcerts/components/List.vue
  containers/Network/views/lbcerts/sidepage/Detail.vue
Labels: size/M

#4559 Automated cherry pick of #4558: bugfix(8963): 通知渠道邮箱不应该展示2个
  src/utils/utils.js
Labels: size/XS

#4561 Automated cherry pick of #4558: bugfix(8963): 通知渠道邮箱不应该展示2个
  src/utils/utils.js
Labels: size/XS

#4560 Automated cherry pick of #4558: bugfix(8963): 通知渠道邮箱不应该展示2个
  src/utils/utils.js
Labels: size/XS

#4562 fix(8969): 申请主机工单时报错
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#4563 Automated cherry pick of #4562: fix(8969): 申请主机工单时报错
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#4564 fix(8968): 虚拟机转换失败状态应该为中文
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#4565 Automated cherry pick of #4564: fix(8968): 虚拟机转换失败状态应该为中文
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#4566 feat(4306): project admin support select user
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/projects/components/ProjectAdmin.vue
  containers/IAM/views/projects/sidepage/Detail.vue
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/L

#4567 Automated cherry pick of #4566: feat(4306): project admin support select user
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/projects/components/ProjectAdmin.vue
  containers/IAM/views/projects/sidepage/Detail.vue
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/L

#4568 fix: physical machine ssh info repeat #16881
  containers/Compute/views/physicalmachine/mixins/singleActions.js
Labels: area/compute, size/XS

#4571 fix(8957): 主机详情安全组对安全组的修改逻辑
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/vminstance/dialogs/RevokeSecgroup.vue
  containers/Compute/views/vminstance/dialogs/SetSecgroup.vue
  containers/Compute/views/vminstance/sidepage/Secgroup.vue
  src/utils/error.js
Labels: size/L

#4572 Automated cherry pick of #4571: fix(8957): 主机详情安全组对安全组的修改逻辑
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/secgroup/components/List.vue
  containers/Compute/views/vminstance/dialogs/RevokeSecgroup.vue
  containers/Compute/views/vminstance/dialogs/SetSecgroup.vue
  containers/Compute/views/vminstance/sidepage/Secgroup.vue
  src/utils/error.js
Labels: size/L

#4573 feat: project admin user params
  containers/IAM/views/projects/components/ProjectAdmin.vue
Labels: size/XS

#4574 Automated cherry pick of #4573: feat: project admin user params
  containers/IAM/views/projects/components/ProjectAdmin.vue
Labels: size/XS

#4575 feat: 安全组优化增加校验提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Secgroup.vue
Labels: size/S
