Repository yunionio/dashboard, pull requests merged in 2023-12, with the labels that each got.

#5724 fix: 开源版本隐藏添加到堡垒机操作
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#5727 feat: 扩展标签批量编辑功能
  containers/IAM/views/projects/components/List.vue
  src/sections/DialogManager/components/SetTag.vue
Labels: size/XS

#5729 fixes: 1. reserved ip expiration fields, 2. cluster details, 3. ...
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudprovider/components/List.vue
  containers/Compute/views/networks/mixins/columns.js
  containers/K8S/views/cluster/components/List.vue
  containers/K8S/views/cluster/mixins/columns.js
  containers/K8S/views/cluster/sidepage/Detail.vue
  containers/K8S/views/cluster/sidepage/index.vue
  containers/K8S/views/cluster/utils/columns.js
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/sidepage/IPList.vue
  containers/Network/views/reserved-ip/mixins/columns.js
  src/utils/common/tableColumn.js
  src/utils/common/tableFilter.js
Labels: size/L

#5730 Automated cherry pick of #5729: fixes: 1. reserved ip expiration fields, 2. cluster details, 3. ...
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudprovider/components/List.vue
  containers/Compute/views/networks/mixins/columns.js
  containers/K8S/views/cluster/components/List.vue
  containers/K8S/views/cluster/mixins/columns.js
  containers/K8S/views/cluster/sidepage/Detail.vue
  containers/K8S/views/cluster/sidepage/index.vue
  containers/K8S/views/cluster/utils/columns.js
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/sidepage/IPList.vue
  containers/Network/views/reserved-ip/mixins/columns.js
  src/utils/common/tableColumn.js
  src/utils/common/tableFilter.js
Labels: size/L

#5731 fix: reserved ip status
  containers/Network/views/reserved-ip/mixins/columns.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#5735 feat(4625): 磁盘增加磁盘置备选项
  containers/Compute/constants/index.js
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/Compute/views/disk/utils/columns.js
Labels: size/M

#5737 feat(4625): vmware新建虚拟机磁盘支持指定磁盘置备
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/Disk/index.vue
  containers/Compute/utils/createServer.js
Labels: size/M

#5739 feat(4625): vmware新建虚拟机磁盘支持指定磁盘置备
  containers/Compute/sections/Disk/index.vue
Labels: size/S

#5741 Automated cherry pick of #5616: fix: ramda.type函数使用修复
  src/sections/DialogManager/components/SmartForm.vue
Labels: size/XS

#5744 Automated cherry pick of #5718: feat(4658): windows系统支持RDP及SSH优化调整
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/L

#5748 feat(4676): 虚拟机详情页监控增加skip_check_series 参数，加快查询速度
  containers/Compute/sections/monitor/BaseMonitor.vue
  src/utils/monitor.js
Labels: size/S

#5749 Automated cherry pick of #5748: feat(4676): 虚拟机详情页监控增加skip_check_series 参数，加快查询速度
  containers/Compute/sections/monitor/BaseMonitor.vue
  src/utils/monitor.js
Labels: size/S

#5756 Automated cherry pick of #5754: feat(4671): 显存和分辨率的展示加一下判断，只有是 dev_type是 LEGACY-VGPU 的时候才展示
  containers/Compute/views/gpu/sidepage/Detail.vue
Labels: size/XS

#5750 fix(9454): add function to calc tooltip position
  src/utils/echart.js
Labels: size/S

#5758 Automated cherry pick of #5757: feat: cpu sockets
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/CpuRadio/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/L

#5759 feat: rdp scale fit
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#5764 Automated cherry pick of #5763: fix: nat brand filter error
  containers/Network/views/nats/create/index.vue
Labels: size/XS

#5765 Automated cherry pick of #5763: fix: nat brand filter error
  containers/Network/views/nats/create/index.vue
Labels: size/XS

#5766 fix: init usb isolated devices error
  containers/Compute/views/vminstance/dialogs/AttachUsb.vue
Labels: size/XS

#5767 Automated cherry pick of #5766: fix: init usb isolated devices error
  containers/Compute/views/vminstance/dialogs/AttachUsb.vue
Labels: size/XS

#5768 Automated cherry pick of #5766: fix: init usb isolated devices error
  containers/Compute/views/vminstance/dialogs/AttachUsb.vue
Labels: size/XS

#5769 fix: no need to resolve forwards of OneCloud vpc server
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/M

#5770 Automated cherry pick of #5769: fix: no need to resolve forwards of OneCloud vpc server
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/M

#5771 fix: webconsole ssh request payload update
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/S

#5772 Automated cherry pick of #5771: fix: webconsole ssh request payload update
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/S

#5774 fix(9498): 只能power_status=on的时候才能打开ssh或rdp
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/M

#5775 Automated cherry pick of #5774: fix(9498): 只能power_status=on的时候才能打开ssh或rdp
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/M

#5776 fix: update power_states
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#5773 fix: snapshot policy operator
  containers/Compute/views/snapshotpolicy/dialogs/AttachDisk.vue
  containers/Compute/views/snapshotpolicy/dialogs/UnbindDisks.vue
  containers/Compute/views/snapshotpolicy/mixins/columns.js
  containers/Compute/views/snapshotpolicy/mixins/diskProps.js
  containers/Compute/views/snapshotpolicy/sidepage/Cache.vue
  containers/Compute/views/snapshotpolicy/sidepage/index.vue
Labels: size/L

#5779 feat: add bill predict analysis
  src/utils/group.js
Labels: size/S

#5781 feat: add extdb i18n
  src/components/Icon/assets/extdb.svg
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#5782 Automated cherry pick of #5781: feat: add extdb i18n
  src/components/Icon/assets/extdb.svg
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#5783 fix: snapshot policy expect status
  src/constants/expectStatus.js
Labels: size/XS

#5784 Automated cherry pick of #5783: fix: snapshot policy expect status
  src/constants/expectStatus.js
Labels: size/XS

#5785 feat(4667): 调整VMware设置插槽内核数
  containers/Compute/sections/CpuRadio/index.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/S

#5787 feat: 调整指定磁盘置备类型
  containers/Compute/sections/Disk/index.vue
  containers/Compute/utils/createServer.js
Labels: size/XS

#5789 feat: 水印开关更换服务为webconsole
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
Labels: size/L

#5790 Automated cherry pick of #5789: feat: 水印开关更换服务为webconsole
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
Labels: size/L

#5791 feat: 自定义时间控件二次选择失效问题
  src/components/DateTime/CustomDate.vue
Labels: size/XS

#5792 Automated cherry pick of #5791: feat: 自定义时间控件二次选择失效问题
  src/components/DateTime/CustomDate.vue
Labels: size/XS

#5794 Automated cherry pick of #5793: feat: 日语更正
  src/locales/ja-JP.json
Labels: size/S

#5793 feat: 日语更正
  src/locales/ja-JP.json
Labels: size/S

#5795 feat: 日语更正
  src/locales/ja-JP.json
Labels: size/S

#5797 feat: 调整指定磁盘置备类型
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/utils/createServer.js
Labels: size/S

#5801 fix(9465): 添加物理机需要改为缺省是 PXE启动，并且要求MAC地址必填
  containers/Compute/views/physicalmachine/add/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#5802 Automated cherry pick of #5801: fix(9465): 添加物理机需要改为缺省是 PXE启动，并且要求MAC地址必填
  containers/Compute/views/physicalmachine/add/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#5803 Automated cherry pick of #5801: fix(9465): 添加物理机需要改为缺省是 PXE启动，并且要求MAC地址必填
  containers/Compute/views/physicalmachine/add/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#5799 fix: set time column formatter
  src/utils/common/tableColumn.js
Labels: size/S

#5800 Automated cherry pick of #5799: fix: set time column formatter
  src/utils/common/tableColumn.js
Labels: size/S

#5804 feat(4667): 限制除vmware以外，其他平台不展示磁盘置备类型
  containers/Compute/views/disk/mixins/columns.js
Labels: size/XS

#5808 fix: 修改PXE启动Mac地址提示文案信息
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#5809 Automated cherry pick of #5808: fix: 修改PXE启动Mac地址提示文案信息
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#5806 fix: bill task check brand param
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
Labels: size/XS

#5807 Automated cherry pick of #5806: fix: bill task check brand param
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
Labels: size/XS

#5811 fix: web-console url error
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/S

#5812 Automated cherry pick of #5811: fix: web-console url error
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/S

#5813 feat(4667): 开机状态，调整cpu，vmware上每个插槽内核数是不能变
  containers/Compute/sections/CpuRadio/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/M

#5815 feat: 更新日语翻译
  src/locales/ja-JP.json
Labels: size/S

#5816 Automated cherry pick of #5815: feat: 更新日语翻译
  src/locales/ja-JP.json
Labels: size/S

#5817 feat: 调整配置支持精简置备类型
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#5819 feat: Optimize the data processing function before exporting the excel
  src/utils/xlsx.js
Labels: size/M

#5820 Automated cherry pick of #5819: feat: Optimize the data processing function before exporting the excel
  src/utils/xlsx.js
Labels: size/M

#5821 feat(4625): 磁盘精简置备导出及添加与系统盘置备类型一致
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/views/disk/mixins/columns.js
Labels: size/S

#5823 Automated cherry pick of #5680: feat(4624): 虚拟机列表增加系统的过滤，目前过滤不细，同时支持通过系统排序
  .vscode/settings.json
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  src/utils/common/tableFilter.js
Labels: size/M

#5824 fix: do forcast when migrate vms
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/M

#5825 Automated cherry pick of #5824: fix: do forcast when migrate vms
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/M

#5826 Automated cherry pick of #5824: fix: do forcast when migrate vms
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/M

#5827 fix: zone filter params
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#5828 Automated cherry pick of #5827: fix: zone filter params
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#5829 Automated cherry pick of #5827: fix: zone filter params
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#5830 feat: 更新日语修正
  .vscode/settings.json
  containers/Monitor/locales/ja-JP.json
  src/locales/ja-JP.json
Labels: size/S

#5832 fix: keep-alive set
  src/layouts/RouterView/index.vue
  src/mixins/keepAlive.js
  src/store/modules/keepAlive.js
Labels: size/M

#5833 Automated cherry pick of #5832: fix: keep-alive set
  src/layouts/RouterView/index.vue
  src/mixins/keepAlive.js
  src/store/modules/keepAlive.js
Labels: size/M

#5834 Automated cherry pick of #5832: fix: keep-alive set
  src/layouts/RouterView/index.vue
  src/mixins/keepAlive.js
  src/store/modules/keepAlive.js
Labels: size/M

#5835 feat(4702): network config support select ip
  containers/Compute/sections/ServerNetwork/IpSelect.vue
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
Labels: size/L

#5836 Automated cherry pick of #5835: feat(4702): network config support select ip
  containers/Compute/sections/ServerNetwork/IpSelect.vue
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
Labels: size/L

#5837 Automated cherry pick of #5835: feat(4702): network config support select ip
  containers/Compute/sections/ServerNetwork/IpSelect.vue
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
Labels: size/L

#5838 feat: disk type add ssd genric v2 for huawei
  containers/Compute/constants/index.js
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  src/constants/compute.js
Labels: size/S

#5839 Automated cherry pick of #5838: feat: disk type add ssd genric v2 for huawei
  containers/Compute/constants/index.js
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  src/constants/compute.js
Labels: size/S

#5841 feat: 更新日语修正
  src/locales/ja-JP.json
Labels: size/S

#5840 feature: support default nic
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/networks/mixins/columns.js
  containers/Compute/views/snapshotpolicy/dialogs/AttachDisk.vue
  containers/Compute/views/snapshotpolicy/mixins/columns.js
  containers/Compute/views/snapshotpolicy/sidepage/index.vue
  containers/Compute/views/vminstance/dialogs/DetachNetwork.vue
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
  containers/Compute/views/vminstance/dialogs/VmUpdateNetworkAttr.vue
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/sidepage/Detail.vue
  containers/Network/views/wire/sidepage/index.vue
Labels: size/M

#5842 Automated cherry pick of #5840: feature: support default nic
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/networks/mixins/columns.js
  containers/Compute/views/snapshotpolicy/dialogs/AttachDisk.vue
  containers/Compute/views/snapshotpolicy/mixins/columns.js
  containers/Compute/views/snapshotpolicy/sidepage/index.vue
  containers/Compute/views/vminstance/dialogs/DetachNetwork.vue
  containers/Compute/views/vminstance/dialogs/SetNetwork.vue
  containers/Compute/views/vminstance/dialogs/VmUpdateNetworkAttr.vue
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/sidepage/Detail.vue
  containers/Network/views/wire/sidepage/index.vue
Labels: size/M

#5844 feat(4702): vm change ip support select
  containers/Compute/views/vminstance/dialogs/ChangeIp.vue
Labels: size/S

#5845 Automated cherry pick of #5844: feat(4702): vm change ip support select
  containers/Compute/views/vminstance/dialogs/ChangeIp.vue
Labels: size/S

#5846 Automated cherry pick of #5844: feat(4702): vm change ip support select
  containers/Compute/views/vminstance/dialogs/ChangeIp.vue
Labels: size/S

#5848 Automated cherry pick of #5847: feat: 更新日语修正
  src/locales/ja-JP.json
Labels: size/XS

#5849 fix: 修复调整配置每个插槽内核数错误问题
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#5850 Automated cherry pick of #5849: fix: 修复调整配置每个插槽内核数错误问题
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#5851 feat: add i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
Labels: size/S
