Repository yunionio/dashboard, pull requests merged in 2023-09, with the labels that each got.

#5241 feat(4194): set tag dialog add tag value check
  src/sections/DialogManager/components/SetTag.vue
Labels: size/XS

#5242 Automated cherry pick of #5241: feat(4194): set tag dialog add tag value check
  src/sections/DialogManager/components/SetTag.vue
Labels: size/XS

#5243 Automated cherry pick of #5241: feat(4194): set tag dialog add tag value check
  src/sections/DialogManager/components/SetTag.vue
Labels: size/XS

#5244 fix(8995): range scope project select limit 20
  src/sections/RangeScope/index.vue
Labels: size/L

#5245 Automated cherry pick of #5244: fix(8995): range scope project select limit 20
  src/sections/RangeScope/index.vue
Labels: size/L

#5247 feat(4515): add global config i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#5248 feat(4481): 工单增加关机工单流程
  containers/Compute/views/vminstance/dialogs/ShutDown.vue
  src/constants/workflow.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#5250 fix(9299): change project filter params when doamin changed
  containers/IAM/views/user/components/DomainProjectSelect.vue
Labels: size/XS

#5251 Automated cherry pick of #5250: fix(9299): change project filter params when doamin changed
  containers/IAM/views/user/components/DomainProjectSelect.vue
Labels: size/XS

#5252 feat: 调整kvm custom data参数
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#5254 feat: 调整custom data提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
Labels: size/XS

#5256 feat: onecloud dns zone do not support associate vpc
  containers/Network/views/dns-zone/create/index.vue
  containers/Network/views/dns-zone/dialogs/AssociateVpcDialog.vue
  containers/Network/views/dns-zone/index.vue
  containers/Network/views/dns-zone/mixins/singleActions.js
  containers/Network/views/dns-zone/sidepage/index.vue
Labels: size/M

#5257 Automated cherry pick of #5256: feat: onecloud dns zone do not support associate vpc
  containers/Network/views/dns-zone/create/index.vue
  containers/Network/views/dns-zone/dialogs/AssociateVpcDialog.vue
  containers/Network/views/dns-zone/index.vue
  containers/Network/views/dns-zone/mixins/singleActions.js
  containers/Network/views/dns-zone/sidepage/index.vue
Labels: size/M

#5260 feat(4481): 工单增加重启工单流程
  containers/Compute/views/vminstance/dialogs/Restart.vue
  src/constants/workflow.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#5261 Automated cherry pick of #5260: feat(4481): 工单增加重启工单流程
  containers/Compute/views/vminstance/dialogs/Restart.vue
  src/constants/workflow.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#5258 feat(4531): delete environment param in huawei cloudaccount
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
Labels: size/XS

#5259 Automated cherry pick of #5258: feat(4531): delete environment param in huawei cloudaccount
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
Labels: size/XS

#5262 feat(4534): admin suuport apply work order support
  src/sections/Navbar/components/WorkOrderPopover.vue
Labels: size/XS

#5264 feat: dashboard support hidden actions
  containers/Dashboard/views/dashboard/components/Header.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/permission.js
Labels: size/M

#5265 Automated cherry pick of #5264: feat: dashboard support hidden actions
  containers/Dashboard/views/dashboard/components/Header.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/permission.js
Labels: size/M

#5266 feat: 调整kvm custom data与其他平台保持一致
  containers/Compute/views/vminstance/create/components/CustomData.vue
Labels: size/M

#5267 Automated cherry pick of #5266: feat: 调整kvm custom data与其他平台保持一致
  containers/Compute/views/vminstance/create/components/CustomData.vue
Labels: size/M

#5268 feat: 堡垒机增加标签信息
  containers/Compute/views/vminstance/create/components/BastionHost.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/S

#5269 Automated cherry pick of #5268: feat: 堡垒机增加标签信息
  containers/Compute/views/vminstance/create/components/BastionHost.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/S

#5272 fix(9297): 新建虚拟机指定块存储后调整磁盘大小超过剩余会导致页面无响应
  containers/Compute/sections/Disk/components/Storage.vue
Labels: size/S

#5273 Automated cherry pick of #5272: fix(9297): 新建虚拟机指定块存储后调整磁盘大小超过剩余会导致页面无响应
  containers/Compute/sections/Disk/components/Storage.vue
Labels: size/S

#5270 feat(4424): keypair support set public scope
  containers/Compute/views/keypair/mixins/columns.js
  containers/Compute/views/keypair/mixins/singleActions.js
  containers/Compute/views/keypair/sidepage/Detail.vue
  src/constants/permission.js
  src/sections/DialogManager/components/SetPublic.vue
  src/utils/common/tableActions.js
Labels: size/M

#5274 fix(9299): 新建项目用户根据当前选择域过滤,新建用户项目根据当前选择域过滤
  containers/IAM/views/projects/components/DomainUserSelect.vue
  containers/IAM/views/user/components/DomainProjectSelect.vue
  containers/IAM/views/user/create/form/JoinProject.vue
Labels: size/XS

#5275 Automated cherry pick of #5274: fix(9299): 新建项目用户根据当前选择域过滤,新建用户项目根据当前选择域过滤
  containers/IAM/views/projects/components/DomainUserSelect.vue
  containers/IAM/views/user/components/DomainProjectSelect.vue
  containers/IAM/views/user/create/form/JoinProject.vue
Labels: size/XS

#5276 fix: dashboard show running server cpu/mem usage percentage
  containers/Compute/views/vminstance/utils.js
  src/constants/generalUsage.js
Labels: size/S

#5277 Automated cherry pick of #5276: fix: dashboard show running server cpu/mem usage percentage
  containers/Compute/views/vminstance/utils.js
  src/constants/generalUsage.js
Labels: size/S

#5278 Automated cherry pick of #5276: fix: dashboard show running server cpu/mem usage percentage
  containers/Compute/views/vminstance/utils.js
  src/constants/generalUsage.js
Labels: size/S

#5281 fix: batch transfer add max_bandwidth_mb params
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#5282 Automated cherry pick of #5281: fix: batch transfer add max_bandwidth_mb params
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#5279 feat(4518): hidden vminstance sidepage
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/S

#5280 Automated cherry pick of #5279: feat(4518): hidden vminstance sidepage
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/S

#5283 Automated cherry pick of #5281: fix: batch transfer add max_bandwidth_mb params
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#5284 feat(4531): delete environment param in huawei cloudaccount
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/utils/columns.js
Labels: size/XS

#5285 Automated cherry pick of #5284: feat(4531): delete environment param in huawei cloudaccount
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/utils/columns.js
Labels: size/XS

#5286 feat: notify silent time
  containers/IAM/views/notify-subscriber/dialogs/SetupNotifyReceiver.vue
  containers/IAM/views/notify-subscriber/mixins/columns.js
Labels: size/S

#5287 Automated cherry pick of #5286: feat: notify silent time
  containers/IAM/views/notify-subscriber/dialogs/SetupNotifyReceiver.vue
  containers/IAM/views/notify-subscriber/mixins/columns.js
Labels: size/S

#5290 fix(9252): bill tasks default select current month
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
Labels: size/XS

#5291 Automated cherry pick of #5290: fix(9252): bill tasks default select current month
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
Labels: size/XS

#5292 fix(9300): 订阅不支持批量搜索
  containers/Cloudenv/views/cloudprovider/components/List.vue
  src/utils/list.js
Labels: size/XS

#5293 Automated cherry pick of #5292: fix(9300): 订阅不支持批量搜索
  containers/Cloudenv/views/cloudprovider/components/List.vue
  src/utils/list.js
Labels: size/XS

#5294 fix(9262): 监控总览导出近30天告警没数据
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
Labels: size/XS

#5295 Automated cherry pick of #5294: fix(9262): 监控总览导出近30天告警没数据
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
Labels: size/XS

#5296 feat(5270): remove keypair support set public scope
  containers/Compute/views/keypair/mixins/columns.js
  containers/Compute/views/keypair/mixins/singleActions.js
  containers/Compute/views/keypair/sidepage/Detail.vue
  src/constants/permission.js
  src/sections/DialogManager/components/SetPublic.vue
  src/utils/common/tableActions.js
Labels: size/M

#5297 fix(9139): 自定义资源标签列的值无法导出
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#5298 Automated cherry pick of #5297: fix(9139): 自定义资源标签列的值无法导出
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#5299 fix: 修复迁移带宽数据
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#5300 Automated cherry pick of #5299: fix: 修复迁移带宽数据
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#5302 fix(9308): 虚拟机列表设置告警过滤接收人应该和监控处一致
  containers/Compute/views/node-alert/components/Form.vue
Labels: size/XS

#5303 Automated cherry pick of #5302: fix(9308): 虚拟机列表设置告警过滤接收人应该和监控处一致
  containers/Compute/views/node-alert/components/Form.vue
Labels: size/XS

#5304 fix: 自定义带宽校验及参数处理
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/S

#5305 Automated cherry pick of #5304: fix: 自定义带宽校验及参数处理
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/S

#5306 Automated cherry pick of #5304: fix: 自定义带宽校验及参数处理
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/S

#5308 Automated cherry pick of #5307: fix: 虚拟机抽屉透传设备列表操作隐藏及关联虚拟机自动启动逻辑控制
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/gpu/dialogs/AttachDialog.vue
  containers/Compute/views/gpu/dialogs/DetachDialog.vue
  containers/Compute/views/gpu/mixins/singleActions.js
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/M

#5310 feat(4541): add icon
  src/components/Icon/assets/bill-set.svg
Labels: size/XS

#5311 feat(4269): ssh login error message
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/SshAuth.vue
Labels: size/S

#5312 Automated cherry pick of #5311: feat(4269): ssh login error message
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/SshAuth.vue
Labels: size/S

#5313 fix(9311): bucket objects set default search key
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/bucket/sidepage/Objects.vue
Labels: size/S

#5315 feat(4541): add icon
  src/components/Icon/assets/bill-set-cny.svg
  src/components/Icon/assets/bill-set-usd.svg
  src/components/Icon/assets/bill-set.svg
Labels: size/M

#5317 Automated cherry pick of #5316: feat: VGPU与物理GPU互斥，NVIDIA的VGPU增加限制只能绑定一块
  containers/Compute/constants/index.js
  containers/Compute/sections/PCI/index.vue
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
Labels: size/M

#5318 feat: 设置透传设备增加提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
Labels: size/S

#5319 Automated cherry pick of #5318: feat: 设置透传设备增加提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
Labels: size/S

#5320 feat(4535): license add bill items
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
  src/constants/feature.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#5321 Automated cherry pick of #5320: feat(4535): license add bill items
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
  src/constants/feature.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#5322 Automated cherry pick of #5313: fix(9311): bucket objects set default search key
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/bucket/sidepage/Objects.vue
Labels: size/S

#5325 fix(9320): 新建虚拟机，指定调度标签，偏好应该必填
  containers/Compute/utils/createServer.js
Labels: size/XS

#5326 Automated cherry pick of #5325: fix(9320): 新建虚拟机，指定调度标签，偏好应该必填
  containers/Compute/utils/createServer.js
Labels: size/XS

#5328 Automated cherry pick of #5327: fix(9314): 阿里云磁盘扩容，类型放开
  containers/Compute/views/disk/utils/index.js
Labels: size/XS

#5331 feat(4478): create aws vminstance support set iops and throughput
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/L

#5329 fix(9320): schedpolicy policy is required
  containers/Compute/utils/createServer.js
Labels: size/XS

#5330 Automated cherry pick of #5329: fix(9320): schedpolicy policy is required
  containers/Compute/utils/createServer.js
Labels: size/XS

#5332 fix(9308): 虚拟机列表设置告警过滤接收人应该和监控处一致
  containers/Compute/views/node-alert/components/Form.vue
  containers/Compute/views/node-alert/dialogs/Create.vue
Labels: size/XS

#5333 Automated cherry pick of #5332: fix(9308): 虚拟机列表设置告警过滤接收人应该和监控处一致
  containers/Compute/views/node-alert/components/Form.vue
  containers/Compute/views/node-alert/dialogs/Create.vue
Labels: size/XS

#5335 Automated cherry pick of #5334: fix: 渠道用户不支持版本更新
  src/config/setting.js
Labels: size/XS

#5337 feat(4538): kvm和vmware都应该支持安装监控agent，重装系统时也应该支持
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/M

#5338 Automated cherry pick of #5337: feat(4538): kvm和vmware都应该支持安装监控agent，重装系统时也应该支持
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/M

#5339 feat: 增加系统埋点信息
  src/config/appBuryPoint.js
  src/main.js
Labels: size/XS

#5340 Automated cherry pick of #5339: feat: 增加系统埋点信息
  src/config/appBuryPoint.js
  src/main.js
Labels: size/XS

#5341 Automated cherry pick of #5339: feat: 增加系统埋点信息
  src/config/appBuryPoint.js
  src/main.js
Labels: size/XS

#5343 Automated cherry pick of #5342: feat: 渠道用户不显示升级图标
  src/config/setting.js
  src/sections/Navbar/components/MorePopover.vue
Labels: size/S

#5342 feat: 渠道用户不显示升级图标
  src/config/setting.js
  src/sections/Navbar/components/MorePopover.vue
Labels: size/S

#5344 Automated cherry pick of #5342: feat: 渠道用户不显示升级图标
  src/config/setting.js
  src/sections/Navbar/components/MorePopover.vue
Labels: size/S

#5346 Automated cherry pick of #5345: feat(4556): update yarn package version
  containers/Dashboard/views/edit/index.vue
  package.json
  src/config/plugin.config.js
  src/utils/theme/colors.js
  yarn.lock
Labels: size/XXL

#5347 fix(9321): date time add disableLocalTimeSet prop
  src/components/DateTime/index.vue
Labels: size/XS

#5348 Automated cherry pick of #5347: fix(9321): date time add disableLocalTimeSet prop
  src/components/DateTime/index.vue
Labels: size/XS

#5350 Automated cherry pick of #5349: fix(9303): add permissions for policy
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/utils.js
  src/constants/permission.js
Labels: size/M

#5351 feat: 优化路由懒加载模块分包策略
  containers/Cloudenv/router/index.js
  containers/Compute/router/index.js
  containers/DB/router/index.js
  containers/Helm/router/index.js
  containers/IAM/router/index.js
  containers/K8S/router/index.js
  containers/Middleware/router/index.js
  containers/Monitor/router/index.js
  containers/Network/router/index.js
  containers/Storage/router/index.js
Labels: size/L

#5352 Automated cherry pick of #5345: feat(4556): update yarn package version
  containers/Dashboard/views/edit/index.vue
  package.json
  src/config/plugin.config.js
  src/utils/theme/colors.js
  yarn.lock
Labels: size/XXL

#5354 feat(4533): 部署虚拟机应用实例支持选择镜像
  containers/Helm/views/chart/create/index.vue
  src/components/JsonSchemaForm/JComponents/JImageList/JImageList.vue
  src/components/JsonSchemaForm/JComponents/JImageList/index.js
  src/components/JsonSchemaForm/JComponents/JSKUList/JSKUList.vue
  src/components/JsonSchemaForm/JComponents/mixin.js
  src/components/JsonSchemaForm/form/Form.js
  src/components/JsonSchemaForm/index.js
Labels: size/L

#5355 Automated cherry pick of #5354: feat(4533): 部署虚拟机应用实例支持选择镜像
  containers/Helm/views/chart/create/index.vue
  src/components/JsonSchemaForm/JComponents/JImageList/JImageList.vue
  src/components/JsonSchemaForm/JComponents/JImageList/index.js
  src/components/JsonSchemaForm/JComponents/JSKUList/JSKUList.vue
  src/components/JsonSchemaForm/JComponents/mixin.js
  src/components/JsonSchemaForm/form/Form.js
  src/components/JsonSchemaForm/index.js
Labels: size/L

#5358 feat(4546): event list add params watch
  src/sections/EventList/index.vue
Labels: size/XS

#5359 Automated cherry pick of #5358: feat(4546): event list add params watch
  src/sections/EventList/index.vue
Labels: size/XS

#5357 feat(4441): 增加容器镜像仓库
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/router/index.js
  containers/K8S/views/repos/components/List.vue
  containers/K8S/views/repos/constants/index.js
  containers/K8S/views/repos/dialogs/Create.vue
  containers/K8S/views/repos/index.vue
  containers/K8S/views/repos/mixins/columns.js
  containers/K8S/views/repos/mixins/singleActions.js
  containers/K8S/views/repos/sidepage/ContainerRegistry.vue
  containers/K8S/views/repos/sidepage/Detail.vue
  containers/K8S/views/repos/sidepage/index.vue
  containers/K8S/views/repos/utils/columns.js
  src/components/Detail/index.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XL

#5360 fix(9321): keep alive page change rule
  src/layouts/RouterView/index.vue
  src/mixins/keepAlive.js
Labels: size/S

#5361 Automated cherry pick of #5360: fix(9321): keep alive page change rule
  src/layouts/RouterView/index.vue
  src/mixins/keepAlive.js
Labels: size/S

#5363 feat(4448): dns zone create set vpc required
  containers/Network/views/dns-recordset/components/List.vue
  containers/Network/views/dns-recordset/mixins/columns.js
  containers/Network/views/dns-zone/create/index.vue
Labels: size/XS

#5364 Automated cherry pick of #5363: feat(4448): dns zone create set vpc required
  containers/Network/views/dns-recordset/components/List.vue
  containers/Network/views/dns-recordset/mixins/columns.js
  containers/Network/views/dns-zone/create/index.vue
Labels: size/XS

#5365 Automated cherry pick of #5363: feat(4448): dns zone create set vpc required
  containers/Network/views/dns-recordset/components/List.vue
  containers/Network/views/dns-recordset/mixins/columns.js
  containers/Network/views/dns-zone/create/index.vue
Labels: size/XS

#5367 Automated cherry pick of #5366: feat(4548): external project support view log
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/externalproject/dialogs/ExternalProjectLogDialog.vue
Labels: size/L

#5368 Automated cherry pick of #5366: feat(4548): external project support view log
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/externalproject/dialogs/ExternalProjectLogDialog.vue
Labels: size/L

#5369 fix: 云上项目修改本地项目,项目反显错误
  containers/Cloudenv/views/externalproject/dialogs/ChangeProject.vue
Labels: size/XS

#5370 Automated cherry pick of #5369: fix: 云上项目修改本地项目,项目反显错误
  containers/Cloudenv/views/externalproject/dialogs/ChangeProject.vue
Labels: size/XS

#5371 Automated cherry pick of #5369: fix: 云上项目修改本地项目,项目反显错误
  containers/Cloudenv/views/externalproject/dialogs/ChangeProject.vue
Labels: size/XS

#5373 Automated cherry pick of #5372: feat(4441): 容器应用增加镜像仓库选择功能
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/sections/Dialogs/SetImage.vue
  containers/K8S/sections/MirrorRegistry/index.vue
  containers/K8S/sections/SpecContainer/Form.vue
  containers/K8S/utils/index.js
  containers/K8S/views/deployment/components/List.vue
  src/utils/url.js
Labels: size/L

#5374 Automated cherry pick of #5372: feat(4441): 容器应用增加镜像仓库选择功能
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
  containers/K8S/sections/Dialogs/SetImage.vue
  containers/K8S/sections/MirrorRegistry/index.vue
  containers/K8S/sections/SpecContainer/Form.vue
  containers/K8S/utils/index.js
  containers/K8S/views/deployment/components/List.vue
  src/utils/url.js
Labels: size/L

#5375 fix(9355): idc dns-zone do not support attach vpc
  containers/Network/views/dns-zone/sidepage/Detail.vue
Labels: size/XS

#5376 Automated cherry pick of #5375: fix(9355): idc dns-zone do not support attach vpc
  containers/Network/views/dns-zone/sidepage/Detail.vue
Labels: size/XS

#5377 Automated cherry pick of #5375: fix(9355): idc dns-zone do not support attach vpc
  containers/Network/views/dns-zone/sidepage/Detail.vue
Labels: size/XS
