Repository yunionio/dashboard, pull requests merged in 2023-05, with the labels that each got.

#4577 feat: event-drawer add params
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/mixins/columns.js
  containers/IAM/views/policy/sidepage/Detail.vue
  src/components/EventDrawer/index.vue
  src/sections/EventList/index.vue
  src/utils/common/tableColumn.js
Labels: size/L

#4578 Automated cherry pick of #4577: feat: event-drawer add params
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/mixins/columns.js
  containers/IAM/views/policy/sidepage/Detail.vue
  src/components/EventDrawer/index.vue
  src/sections/EventList/index.vue
  src/utils/common/tableColumn.js
Labels: size/L

#4579 fix(8965): 控制面板个人信息调小后样式错乱的问题
  containers/Dashboard/views/edit/index.vue
Labels: size/XS

#4581 fix(8985): 点击同步账号，确定之后没有返回列表页面问题
  .vscode/extensions.json
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/XS

#4582 Automated cherry pick of #4581: fix(8985): 点击同步账号，确定之后没有返回列表页面问题
  .vscode/extensions.json
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/XS

#4583 fix: user join project limit 20
  containers/IAM/views/user/components/DomainProjectSelect.vue
  containers/IAM/views/user/create/form/CreateUser.vue
  containers/IAM/views/user/create/form/JoinProject.vue
Labels: size/L

#4585 fix: 修复K8S集群新建磁盘报错的问题
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/XS

#4586 Automated cherry pick of #4585: fix: 修复K8S集群新建磁盘报错的问题
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/XS

#4584 Automated cherry pick of #4583: fix: user join project limit 20
  containers/IAM/views/user/components/DomainProjectSelect.vue
  containers/IAM/views/user/create/form/CreateUser.vue
  containers/IAM/views/user/create/form/JoinProject.vue
Labels: size/L

#4587 fix: 修复K8S集群新建磁盘报错的问题
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/XS

#4589 Automated cherry pick of #4585: fix: 修复K8S集群新建磁盘报错的问题
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/XS

#4591 fix(8996): policy domain tags change service param
  containers/IAM/views/policy/components/Form/index.vue
Labels: size/XS

#4592 Automated cherry pick of #4591: fix(8996): policy domain tags change service param
  containers/IAM/views/policy/components/Form/index.vue
Labels: size/XS

#4594 fix(8988): 主机新建支持磁盘存储根据介质过滤
  containers/Compute/views/vminstance/create/form/IDC.vue
  src/utils/common/hypervisor.js
Labels: size/S

#4595 Automated cherry pick of #4594: fix(8988): 主机新建支持磁盘存储根据介质过滤
  containers/Compute/views/vminstance/create/form/IDC.vue
  src/utils/common/hypervisor.js
Labels: size/S

#4593 feat(4310): secgroup direction remote peer_secgroup from source param
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/secgroup/components/Direction.vue
  containers/Compute/views/secgroup/dialogs/EditRules.vue
  containers/Compute/views/secgroup/mixins/columns.js
Labels: size/M, area/compute

#4597 fix(8988): 主机新建报错原因中英文不符
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
Labels: size/XS

#4596 Automated cherry pick of #4593: feat(4310): secgroup direction remote peer_secgroup from source param
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/secgroup/components/Direction.vue
  containers/Compute/views/secgroup/dialogs/EditRules.vue
  containers/Compute/views/secgroup/mixins/columns.js
Labels: size/M

#4599 feat(4318): 自定义的PCI设备类型
  containers/Compute/views/gpu/index.vue
  containers/Compute/views/pci/components/PciList.vue
  containers/Compute/views/pci/dialogs/create.vue
  containers/Compute/views/pci/locales/en.json
  containers/Compute/views/pci/locales/zh-CN.json
  containers/Compute/views/pci/mixins/columns.js
  containers/Compute/views/pci/mixins/singleActions.js
  containers/Compute/views/pci/sidepage/Detail.vue
  containers/Compute/views/pci/sidepage/index.vue
  containers/Compute/views/pci/utils/columns.js
Labels: size/XL

#4601 feat: add show error notify method
  src/utils/http.js
Labels: size/S

#4602 Automated cherry pick of #4601: feat: add show error notify method
  src/utils/http.js
Labels: size/S

#4603 fix(9010): create cluster params error
  containers/Network/views/loadbalancercluster/dialogs/Create.vue
Labels: area/network, size/XS

#4604 Automated cherry pick of #4603: fix(9010): create cluster params error
  containers/Network/views/loadbalancercluster/dialogs/Create.vue
Labels: size/XS

#4605 Automated cherry pick of #4603: fix(9010): create cluster params error
  containers/Network/views/loadbalancercluster/dialogs/Create.vue
Labels: size/XS

#4606 feat(4318): 更新自定义的PCI设备类型
  containers/Compute/views/pci/components/PciList.vue
  containers/Compute/views/pci/dialogs/create.vue
  containers/Compute/views/pci/locales/en.json
  containers/Compute/views/pci/locales/zh-CN.json
  containers/Compute/views/pci/mixins/columns.js
  containers/Compute/views/pci/mixins/resourceProps.js
  containers/Compute/views/pci/mixins/singleActions.js
  containers/Compute/views/pci/sidepage/Detail.vue
  containers/Compute/views/pci/sidepage/index.vue
  containers/Compute/views/pci/utils/columns.js
Labels: size/L

#4609 feat(4318): 自定义的PCI设备类型权限
  containers/Compute/views/pci/components/PciList.vue
  containers/Compute/views/pci/mixins/singleActions.js
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#4607 feat: status column expand
  src/utils/common/tableColumn.js
Labels: size/XS

#4608 Automated cherry pick of #4607: feat: status column expand
  src/utils/common/tableColumn.js
Labels: size/XS

#4613 fix(9018): fetch project-sharing to adjust after login
  src/main.js
  src/sections/Navbar/index.vue
Labels: size/XS

#4614 Automated cherry pick of #4613: fix(9018): fetch project-sharing to adjust after login
  src/main.js
  src/sections/Navbar/index.vue
Labels: size/XS

#4615 fix(8978): policy compatible with full permissions
  src/utils/policy/policy-res-list.js
Labels: size/M

#4616 Automated cherry pick of #4615: fix(8978): policy compatible with full permissions
  src/utils/policy/policy-res-list.js
Labels: size/M

#4620 feat(4318): 虚拟机新建支持选择多个透传设备
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/PCI/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/L

#4617 fix(8902): vminstance create log error "loadDefaultSelectOpts undefined"
  src/sections/DomainProject/index.vue
Labels: area/compute, size/XS

#4618 Automated cherry pick of #4617: fix(8902): vminstance create log error "loadDefaultSelectOpts undefined"
  src/sections/DomainProject/index.vue
Labels: size/XS

#4619 feat(4269): ssh auth dialog show operation dialog
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/constants/actions.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/SshAuth.vue
Labels: area/compute, size/S

#4622 feat(4318): 虚拟机设置透传设备
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
Labels: size/M

#4623 Automated cherry pick of #4622: feat(4318): 虚拟机设置透传设备
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
Labels: size/M

#4624 feat(4318): 虚拟机列表类型过滤数据处理
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#4626 feat: 修正标签列展示参数
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/schedtag/mixins/columns.js
  containers/Compute/views/baremetal/mixins/columns.js
  containers/Compute/views/disk-backup/mixins/columns.js
  containers/Compute/views/disk-backup/sidepage/Detail.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/gpu/sidepage/Servers.vue
  containers/Compute/views/host-image/mixins/columns.js
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/image/mixins/columns.js
  containers/Compute/views/image/sidepage/Detail.vue
  containers/Compute/views/instance-backup/mixins/columns.js
  containers/Compute/views/instance-backup/sidepage/Detail.vue
  containers/Compute/views/physicalmachine/mixins/columns.js
  containers/Compute/views/secgroup/mixins/columns.js
  containers/Compute/views/snapshot-instance/mixins/columns.js
  containers/Compute/views/snapshot/mixins/columns.js
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/webapp/mixins/columns.js
  containers/DB/views/mongodb/mixins/columns.js
  containers/DB/views/rds-backup/mixins/columns.js
  containers/DB/views/rds/mixins/columns.js
  containers/DB/views/redis/mixins/columns.js
  containers/IAM/views/domains/mixins/columns.js
  containers/IAM/views/projects/mixins/columns.js
  containers/Middleware/views/elasticsearch/mixins/columns.js
  containers/Middleware/views/kafka/mixins/columns.js
  containers/Network/views/agent/mixins/columns.js
  containers/Network/views/cdn/mixins/columns.js
  containers/Network/views/dns-recordset/mixins/columns.js
  containers/Network/views/dns-zone/mixins/columns.js
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/flex-network/mixins/columns.js
  containers/Network/views/lb/mixins/columns.js
  containers/Network/views/lbcerts/mixins/columns.js
  containers/Network/views/loadbalancercluster/mixins/columns.js
  containers/Network/views/nats/mixins/columns.js
  containers/Network/views/network/mixins/columns.js
  containers/Network/views/vpc-network/mixins/columns.js
  containers/Network/views/vpc-peer-connect/mixins/columns.js
  containers/Network/views/vpc/mixins/columns.js
  containers/Network/views/waf/mixins/columns.js
  containers/Network/views/wire/mixins/columns.js
  containers/Storage/views/backup-storage/mixins/columns.js
  containers/Storage/views/backup-storage/sidepage/Detail.vue
  containers/Storage/views/blockstorage/mixins/columns.js
  containers/Storage/views/bucket/mixins/columns.js
  containers/Storage/views/file-system/mixins/columns.js
  src/sections/TagTableColumn/index.vue
Labels: size/M

#4627 Automated cherry pick of #4626: feat: 修正标签列展示参数
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/schedtag/mixins/columns.js
  containers/Compute/views/baremetal/mixins/columns.js
  containers/Compute/views/disk-backup/mixins/columns.js
  containers/Compute/views/disk-backup/sidepage/Detail.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/gpu/sidepage/Servers.vue
  containers/Compute/views/host-image/mixins/columns.js
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/image/mixins/columns.js
  containers/Compute/views/image/sidepage/Detail.vue
  containers/Compute/views/instance-backup/mixins/columns.js
  containers/Compute/views/instance-backup/sidepage/Detail.vue
  containers/Compute/views/physicalmachine/mixins/columns.js
  containers/Compute/views/secgroup/mixins/columns.js
  containers/Compute/views/snapshot-instance/mixins/columns.js
  containers/Compute/views/snapshot/mixins/columns.js
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/webapp/mixins/columns.js
  containers/DB/views/mongodb/mixins/columns.js
  containers/DB/views/rds-backup/mixins/columns.js
  containers/DB/views/rds/mixins/columns.js
  containers/DB/views/redis/mixins/columns.js
  containers/IAM/views/domains/mixins/columns.js
  containers/IAM/views/projects/mixins/columns.js
  containers/Middleware/views/elasticsearch/mixins/columns.js
  containers/Middleware/views/kafka/mixins/columns.js
  containers/Network/views/agent/mixins/columns.js
  containers/Network/views/cdn/mixins/columns.js
  containers/Network/views/dns-recordset/mixins/columns.js
  containers/Network/views/dns-zone/mixins/columns.js
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/flex-network/mixins/columns.js
  containers/Network/views/lb/mixins/columns.js
  containers/Network/views/lbcerts/mixins/columns.js
  containers/Network/views/loadbalancercluster/mixins/columns.js
  containers/Network/views/nats/mixins/columns.js
  containers/Network/views/network/mixins/columns.js
  containers/Network/views/vpc-network/mixins/columns.js
  containers/Network/views/vpc-peer-connect/mixins/columns.js
  containers/Network/views/vpc/mixins/columns.js
  containers/Network/views/waf/mixins/columns.js
  containers/Network/views/wire/mixins/columns.js
  containers/Storage/views/backup-storage/mixins/columns.js
  containers/Storage/views/backup-storage/sidepage/Detail.vue
  containers/Storage/views/blockstorage/mixins/columns.js
  containers/Storage/views/bucket/mixins/columns.js
  containers/Storage/views/file-system/mixins/columns.js
  src/sections/TagTableColumn/index.vue
Labels: size/M

#4628 feat(4239): table filter add customDistinctFieldFilter method
  src/utils/common/tableFilter.js
Labels: size/M

#4629 Automated cherry pick of #4628: feat(4239): table filter add customDistinctFieldFilter method
  src/utils/common/tableFilter.js
Labels: size/M

#4630 Automated cherry pick of #4628: feat(4239): table filter add customDistinctFieldFilter method
  src/utils/common/tableFilter.js
Labels: size/M

#4631 fix(9013): 控制面板对应资源数据没有权限时右的跳转置灰
  containers/Dashboard/extends/NumberCard/components/Server.vue
  src/utils/auth.js
Labels: size/S

#4633 Automated cherry pick of #4631: fix(9013): 控制面板对应资源数据没有权限时右的跳转置灰
  containers/Dashboard/extends/NumberCard/components/Server.vue
  src/utils/auth.js
Labels: size/S

#4634 fix: VendorId校验有问题，只有提交的时候校验错误
  containers/Compute/views/pci/dialogs/create.vue
  containers/Compute/views/pci/locales/en.json
  containers/Compute/views/pci/locales/zh-CN.json
Labels: size/S

#4635 Automated cherry pick of #4634: fix: VendorId校验有问题，只有提交的时候校验错误
  containers/Compute/views/pci/dialogs/create.vue
  containers/Compute/views/pci/locales/en.json
  containers/Compute/views/pci/locales/zh-CN.json
Labels: size/S

#4636 feat(4332): bill task show time duration
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/billtasks/mixins/columns.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: area/cloudenv

#4638 fix(9012): 补充权限信息
  src/constants/permission.js
Labels: size/M

#4642 Automated cherry pick of #4641: fix: 虚拟机详情显示透传设备信息undefined问题
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#4643 fix(9008): clear dashboard cache after logout
  containers/Dashboard/utils/cache.js
  src/store/modules/auth.js
Labels: area/dashboard, size/XS

#4644 Automated cherry pick of #4643: fix(9008): clear dashboard cache after logout
  containers/Dashboard/utils/cache.js
  src/store/modules/auth.js
Labels: size/XS

#4645 fix(9026): 新建用户时，如果管理员没有添加项目用户的权限，则不应该展示设置项目的下一页，否则会报错
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/user/create/index.vue
Labels: size/S

#4646 Automated cherry pick of #4645: fix(9026): 新建用户时，如果管理员没有添加项目用户的权限，则不应该展示设置项目的下一页，否则会报错
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/user/create/index.vue
Labels: size/S

#4647 fix(9035): tag filter value set default value ""
  src/sections/TagSelect/index.vue
Labels: size/XS

#4648 Automated cherry pick of #4647: fix(9035): tag filter value set default value ""
  src/sections/TagSelect/index.vue
Labels: size/XS

#4649 fix: 调整device和vendor的正则表达式
  containers/Compute/views/pci/dialogs/create.vue
Labels: size/XS

#4650 Automated cherry pick of #4649: fix: 调整device和vendor的正则表达式
  containers/Compute/views/pci/dialogs/create.vue
Labels: size/XS

#4651 fix(9028): 以安全管理员登录，无主机操作权限，但是一些菜单还是可以点击
  containers/Compute/views/vminstance/constants/actions.js
  src/constants/permission.js
Labels: size/XS

#4652 Automated cherry pick of #4651: fix(9028): 以安全管理员登录，无主机操作权限，但是一些菜单还是可以点击
  containers/Compute/views/vminstance/constants/actions.js
  src/constants/permission.js
Labels: size/XS

#4653 feat(4332): time duration show < 1s when start equals end
  src/utils/common/tableColumn.js
Labels: size/XS

#4655 fix: 虚拟机类型当是透传设备时，显示透传设备虚拟机
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#4656 Automated cherry pick of #4655: fix: 虚拟机类型当是透传设备时，显示透传设备虚拟机
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#4657 fix(9028): 调整主机操作权限
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  src/constants/permission.js
Labels: size/XS

#4658 Automated cherry pick of #4657: fix(9028): 调整主机操作权限
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  src/constants/permission.js
Labels: size/XS

#4661 feat(4320): 开启大页内存禁止调整内存超售比/预留内存
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/dialogs/AdjustOversoldRatio.vue
Labels: size/M

#4659 feat(4339): bill tasks add task type i18n
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
  containers/Cloudenv/views/billtasks/mixins/columns.js
  containers/Cloudenv/views/billtasks/sidepage/Detail.vue
Labels: size/S

#4660 Automated cherry pick of #4659: feat(4339): bill tasks add task type i18n
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
  containers/Cloudenv/views/billtasks/mixins/columns.js
  containers/Cloudenv/views/billtasks/sidepage/Detail.vue
Labels: size/S

#4663 fix(9032): name column extend formatter method for local export
  src/utils/common/tableColumn.js
Labels: size/XS

#4664 Automated cherry pick of #4663: fix(9032): name column extend formatter method for local export
  src/utils/common/tableColumn.js
Labels: size/XS

#4665 feat: 透传设备支持全局搜索
  src/constants/globalSearch.js
  src/views/global-search-result/index.vue
Labels: size/S

#4666 Automated cherry pick of #4665: feat: 透传设备支持全局搜索
  src/constants/globalSearch.js
  src/views/global-search-result/index.vue
Labels: size/S

#4669 feat(4321): openstack需支持硬盘快照回滚
  containers/Compute/views/snapshot/validate.js
Labels: size/XS

#4670 Automated cherry pick of #4669: feat(4321): openstack需支持硬盘快照回滚
  containers/Compute/views/snapshot/validate.js
Labels: size/XS

#4671 Automated cherry pick of #4669: feat(4321): openstack需支持硬盘快照回滚
  containers/Compute/views/snapshot/validate.js
Labels: size/XS

#4667 fix(9008): dashboard monitor params error
  containers/Dashboard/utils/cache.js
Labels: size/XS

#4668 Automated cherry pick of #4667: fix(9008): dashboard monitor params error
  containers/Dashboard/utils/cache.js
Labels: size/XS

#4672 fix(8877): 物理机详情页面GPU卡报错
  containers/Compute/views/host/sidepage/Gpu.vue
Labels: size/M

#4674 fix(9026): 国际化信息报错
  containers/IAM/views/user/create/index.vue
Labels: size/XS

#4676 feat(4321): openstack支持硬盘快照回滚操作增加条件限制
  containers/Compute/views/snapshot/validate.js
Labels: size/S

#4677 Automated cherry pick of #4676: feat(4321): openstack支持硬盘快照回滚操作增加条件限制
  containers/Compute/views/snapshot/validate.js
Labels: size/S

#4678 Automated cherry pick of #4676: feat(4321): openstack支持硬盘快照回滚操作增加条件限制
  containers/Compute/views/snapshot/validate.js
Labels: size/S

#4679 feat(4335): 通过上传镜像文件上传，新增操作系统选项
  containers/Compute/views/image/dialogs/Upload.vue
Labels: size/XS

#4680 Automated cherry pick of #4679: feat(4335): 通过上传镜像文件上传，新增操作系统选项
  containers/Compute/views/image/dialogs/Upload.vue
Labels: size/XS

#4681 Automated cherry pick of #4679: feat(4335): 通过上传镜像文件上传，新增操作系统选项
  containers/Compute/views/image/dialogs/Upload.vue
Labels: size/XS

#4684 feat: 调整透传设备提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
Labels: size/XS

#4685 Automated cherry pick of #4684: feat: 调整透传设备提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
Labels: size/XS

#4686 feat: PCI更新文档链接地址
  containers/Compute/views/pci/dialogs/create.vue
Labels: size/S

#4688 feat(4345): 开机状态设置透传设备，不应该有开机启动操作（默认关闭），批量需判断是否显示
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
Labels: size/S

#4689 Automated cherry pick of #4688: feat(4345): 开机状态设置透传设备，不应该有开机启动操作（默认关闭），批量需判断是否显示
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
Labels: size/S

#4691 feat(4344): 负载均衡节点功能改进
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/agent/form/index.vue
  containers/Network/views/agent/mixins/columns.js
  containers/Network/views/agent/sidepage/Detail.vue
Labels: size/M

#4692 Automated cherry pick of #4691: feat(4344): 负载均衡节点功能改进
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/agent/form/index.vue
  containers/Network/views/agent/mixins/columns.js
  containers/Network/views/agent/sidepage/Detail.vue
Labels: size/M

#4690 feat: add permission
  src/constants/permission.js
Labels: size/XS

#4693 feat(4344): 负载均衡节点功能改进
  containers/Network/views/agent/form/index.vue
Labels: size/S

#4695 feat(4345): 透传设备相关优化
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
Labels: size/S

#4696 Automated cherry pick of #4695: feat(4345): 透传设备相关优化
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
Labels: size/S

#4699 fix(9055): 域管理后台订阅数据范围显示错误
  src/sections/RangeScope/index.vue
  src/utils/rangeScope.js
Labels: size/M

#4705 fix(9059): 记忆的镜像如果不存在，应该恢复默认的行为
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#4706 Automated cherry pick of #4705: fix(9059): 记忆的镜像如果不存在，应该恢复默认的行为
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#4707 Automated cherry pick of #4705: fix(9059): 记忆的镜像如果不存在，应该恢复默认的行为
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#4713 fix(9061): 套餐新建限制大小去掉
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/sku/dialogs/CloneSkuUpdateDialog.vue
  containers/Compute/views/sku/dialogs/Create.vue
Labels: size/S

#4717 feat(4310): secgroup direction fix cidr validate rules
  containers/Compute/views/secgroup/dialogs/AddRules.vue
  containers/Compute/views/secgroup/dialogs/EditRules.vue
Labels: area/compute, size/XS

#4718 Automated cherry pick of #4717: feat(4310): secgroup direction fix cidr validate rules
  containers/Compute/views/secgroup/dialogs/AddRules.vue
  containers/Compute/views/secgroup/dialogs/EditRules.vue
Labels: size/XS

#4721 feat: 自定义设备类型支持热插拔
  containers/Compute/views/pci/dialogs/create.vue
  containers/Compute/views/pci/locales/en.json
  containers/Compute/views/pci/locales/zh-CN.json
  containers/Compute/views/pci/mixins/columns.js
  containers/Compute/views/pci/sidepage/Detail.vue
  containers/Compute/views/pci/utils/columns.js
Labels: size/M

#4722 Automated cherry pick of #4721: feat: 自定义设备类型支持热插拔
  containers/Compute/views/pci/dialogs/create.vue
  containers/Compute/views/pci/locales/en.json
  containers/Compute/views/pci/locales/zh-CN.json
  containers/Compute/views/pci/mixins/columns.js
  containers/Compute/views/pci/sidepage/Detail.vue
  containers/Compute/views/pci/utils/columns.js
Labels: size/M

#4725 feat: 透传设备类型支持修改热插拔及增加提示信息
  containers/Compute/views/pci/dialogs/UpdateHotPluggable.vue
  containers/Compute/views/pci/dialogs/create.vue
  containers/Compute/views/pci/locales/en.json
  containers/Compute/views/pci/locales/zh-CN.json
  containers/Compute/views/pci/mixins/columns.js
  containers/Compute/views/pci/mixins/singleActions.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#4726 Automated cherry pick of #4725: feat: 透传设备类型支持修改热插拔及增加提示信息
  containers/Compute/views/pci/dialogs/UpdateHotPluggable.vue
  containers/Compute/views/pci/dialogs/create.vue
  containers/Compute/views/pci/locales/en.json
  containers/Compute/views/pci/locales/zh-CN.json
  containers/Compute/views/pci/mixins/columns.js
  containers/Compute/views/pci/mixins/singleActions.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#4731 fix: bill task check error
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
Labels: area/cloudenv, size/XS
