Repository yunionio/dashboard, pull requests merged in 2023-10, with the labels that each got.

#5378 fix(9329): 数字显示需优化，如果是0，应该显示0%即可，如果值很小，但是比0大，才显示<1%
  containers/Dashboard/extends/Ring/components/Server.vue
Labels: size/XS

#5379 Automated cherry pick of #5378: fix(9329): 数字显示需优化，如果是0，应该显示0%即可，如果值很小，但是比0大，才显示<1%
  containers/Dashboard/extends/Ring/components/Server.vue
Labels: size/XS

#5380 Automated cherry pick of #5378: fix(9329): 数字显示需优化，如果是0，应该显示0%即可，如果值很小，但是比0大，才显示<1%
  containers/Dashboard/extends/Ring/components/Server.vue
Labels: size/XS

#5381 feat(9329): 开源版使用率默认修改为水位图
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/views/dashboard/config/public-default.js
Labels: size/S

#5382 Automated cherry pick of #5381: feat(9329): 开源版使用率默认修改为水位图
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/views/dashboard/config/public-default.js
Labels: size/S

#5383 Automated cherry pick of #5381: feat(9329): 开源版使用率默认修改为水位图
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/extends/Top5/index.vue
  containers/Dashboard/views/dashboard/config/public-default.js
Labels: size/S

#5384 fix(9332): kvm挂起操作，支持批量与单个操作统一
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/S

#5385 Automated cherry pick of #5384: fix(9332): kvm挂起操作，支持批量与单个操作统一
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/S

#5386 Automated cherry pick of #5384: fix(9332): kvm挂起操作，支持批量与单个操作统一
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/S

#5387 feat: 通过工单创建机器增加堡垒机相关信息
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/S

#5388 Automated cherry pick of #5387: feat: 通过工单创建机器增加堡垒机相关信息
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/S

#5389 Automated cherry pick of #5387: feat: 通过工单创建机器增加堡垒机相关信息
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/S

#5390 feat(itsm): create bastion server
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/M

#5391 Automated cherry pick of #5390: feat(itsm): create bastion server
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/M

#5392 Automated cherry pick of #5390: feat(itsm): create bastion server
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/M

#5393 fix: sidepage text color
  src/sections/ProductsList/index.vue
Labels: size/S

#5396 Automated cherry pick of #5351: feat: 优化路由懒加载模块分包策略
  containers/Cloudenv/router/index.js
  containers/Compute/router/index.js
  containers/DB/router/index.js
  containers/Helm/router/index.js
  containers/IAM/router/index.js
  containers/K8S/router/index.js
  containers/Middleware/router/index.js
  containers/Monitor/router/index.js
  containers/Network/router/index.js
  containers/Storage/router/index.js
Labels: size/L

#5397 Automated cherry pick of #5351: feat: 优化路由懒加载模块分包策略
  containers/Cloudenv/router/index.js
  containers/Compute/router/index.js
  containers/DB/router/index.js
  containers/Helm/router/index.js
  containers/IAM/router/index.js
  containers/K8S/router/index.js
  containers/Middleware/router/index.js
  containers/Monitor/router/index.js
  containers/Network/router/index.js
  containers/Storage/router/index.js
Labels: size/L

#5398 fix(9347): 从快照创建磁盘的时候应该可以指定归属项目
  containers/Compute/views/snapshot/dialogs/CreateDisk.vue
Labels: size/S

#5399 Automated cherry pick of #5398: fix(9347): 从快照创建磁盘的时候应该可以指定归属项目
  containers/Compute/views/snapshot/dialogs/CreateDisk.vue
Labels: size/S

#5400 Automated cherry pick of #5398: fix(9347): 从快照创建磁盘的时候应该可以指定归属项目
  containers/Compute/views/snapshot/dialogs/CreateDisk.vue
Labels: size/S

#5401 feat(4562): VMware主机支持创建相同配置
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#5406 Automated cherry pick of #5401: feat(4562): VMware主机支持创建相同配置
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#5403 feat: add rich-editor component
  package.json
  src/components/RichEditor/index.vue
  src/styles/less/global.less
  yarn.lock
Labels: size/XXL

#5404 Automated cherry pick of #5403: feat: add rich-editor component
  package.json
  src/components/RichEditor/index.vue
  src/styles/less/global.less
  yarn.lock
Labels: size/XXL

#5405 Automated cherry pick of #5403: feat: add rich-editor component
  package.json
  src/components/RichEditor/index.vue
  src/styles/less/global.less
  yarn.lock
Labels: size/XXL

#5407 feat(4545): 新建KVM虚拟机支持设置自动启动
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/S

#5408 Automated cherry pick of #5407: feat(4545): 新建KVM虚拟机支持设置自动启动
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/S

#5409 Automated cherry pick of #5407: feat(4545): 新建KVM虚拟机支持设置自动启动
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/S

#5410 fix(9075): monitor table support resizable
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/sections/table/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#5411 Automated cherry pick of #5410: fix(9075): monitor table support resizable
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/sections/table/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#5412 Automated cherry pick of #5410: fix(9075): monitor table support resizable
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/sections/table/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#5414 Automated cherry pick of #5413: fix: 修复私有云及公有云堡垒机展示异常问题
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/XS

#5419 feat(4545): 虚拟机创建自动启动增加kvm限制
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#5420 Automated cherry pick of #5419: feat(4545): 虚拟机创建自动启动增加kvm限制
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#5416 fix(9353): groupActions permission check
  src/components/PageList/Actions/ActionButton.vue
  src/components/PageList/Actions/index.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
Labels: size/S

#5417 Automated cherry pick of #5416: fix(9353): groupActions permission check
  src/components/PageList/Actions/ActionButton.vue
  src/components/PageList/Actions/index.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
Labels: size/S

#5418 Automated cherry pick of #5416: fix(9353): groupActions permission check
  src/components/PageList/Actions/ActionButton.vue
  src/components/PageList/Actions/index.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
Labels: size/S

#5422 fix: 修复osType取值为undefined问题
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#5423 Automated cherry pick of #5422: fix: 修复osType取值为undefined问题
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#5425 fix: 修复计费服务开启并且是商业版才进行价格计算逻辑处理
  containers/Compute/views/vminstance/create/components/BottomBar.vue
Labels: size/XS

#5426 Automated cherry pick of #5425: fix: 修复计费服务开启并且是商业版才进行价格计算逻辑处理
  containers/Compute/views/vminstance/create/components/BottomBar.vue
Labels: size/XS

#5427 Automated cherry pick of #5425: fix: 修复计费服务开启并且是商业版才进行价格计算逻辑处理
  containers/Compute/views/vminstance/create/components/BottomBar.vue
Labels: size/XS

#5428 feat(4505): 新建硬盘支持指定块存储，宿主机列表需要根据磁盘介质过滤
  containers/Compute/views/disk/create/components/HostServer.vue
  containers/Compute/views/disk/create/index.vue
Labels: size/M

#5429 Automated cherry pick of #5428: feat(4505): 新建硬盘支持指定块存储，宿主机列表需要根据磁盘介质过滤
  containers/Compute/views/disk/create/components/HostServer.vue
  containers/Compute/views/disk/create/index.vue
Labels: size/M

#5430 Automated cherry pick of #5428: feat(4505): 新建硬盘支持指定块存储，宿主机列表需要根据磁盘介质过滤
  containers/Compute/views/disk/create/components/HostServer.vue
  containers/Compute/views/disk/create/index.vue
Labels: size/M

#5432 feat(4560): 新建主机调度标签选择处增加提示信息
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/SchedtagPolicy/index.vue
Labels: size/S

#5433 Automated cherry pick of #5432: feat(4560): 新建主机调度标签选择处增加提示信息
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/SchedtagPolicy/index.vue
Labels: size/S

#5434 Automated cherry pick of #5432: feat(4560): 新建主机调度标签选择处增加提示信息
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/SchedtagPolicy/index.vue
Labels: size/S

#5431 feat: add method to format xlsx sheet data
  src/utils/xlsx.js
Labels: size/L

#5435 Automated cherry pick of #5431: feat: add method to format xlsx sheet data
  src/utils/xlsx.js
Labels: size/L

#5436 Automated cherry pick of #5431: feat: add method to format xlsx sheet data
  src/utils/xlsx.js
Labels: size/L

#5437 Automated cherry pick of #5357: feat(4441): 增加容器镜像仓库
  containers/K8S/router/index.js
  containers/K8S/views/repos/components/List.vue
  containers/K8S/views/repos/constants/index.js
  containers/K8S/views/repos/dialogs/Create.vue
  containers/K8S/views/repos/index.vue
  containers/K8S/views/repos/mixins/columns.js
  containers/K8S/views/repos/mixins/singleActions.js
  containers/K8S/views/repos/sidepage/ContainerRegistry.vue
  containers/K8S/views/repos/sidepage/Detail.vue
  containers/K8S/views/repos/sidepage/index.vue
  containers/K8S/views/repos/utils/columns.js
  src/components/Detail/index.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XL

#5440 Automated cherry pick of #5439: fix: 修复操作禁用文案提示信息
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#5442 feat: k8s repo新建用户名和密码修改为非必填项
  containers/K8S/views/repos/dialogs/Create.vue
Labels: size/XS

#5443 Automated cherry pick of #5442: feat: k8s repo新建用户名和密码修改为非必填项
  containers/K8S/views/repos/dialogs/Create.vue
Labels: size/XS

#5444 Automated cherry pick of #5442: feat: k8s repo新建用户名和密码修改为非必填项
  containers/K8S/views/repos/dialogs/Create.vue
Labels: size/XS

#5446 fix(9373): 新建镜像仓库，仓库地址增加示例
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
Labels: size/XS

#5447 Automated cherry pick of #5446: fix(9373): 新建镜像仓库，仓库地址增加示例
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
Labels: size/XS

#5448 Automated cherry pick of #5446: fix(9373): 新建镜像仓库，仓库地址增加示例
  containers/K8S/locales/en.json
  containers/K8S/locales/zh-CN.json
Labels: size/XS

#5452 fix: 修复硬盘新建报错问题
  containers/Compute/views/disk/create/index.vue
Labels: size/S

#5462 fix: 修复容器设置镜像集群信息参数错误
  containers/K8S/sections/Dialogs/SetImage.vue
Labels: size/XS

#5463 Automated cherry pick of #5462: fix: 修复容器设置镜像集群信息参数错误
  containers/K8S/sections/Dialogs/SetImage.vue
Labels: size/XS

#5464 Automated cherry pick of #5462: fix: 修复容器设置镜像集群信息参数错误
  containers/K8S/sections/Dialogs/SetImage.vue
Labels: size/XS

#5465 Automated cherry pick of #5462: fix: 修复容器设置镜像集群信息参数错误
  containers/K8S/sections/Dialogs/SetImage.vue
Labels: size/XS

#5455 fix: data export params add force_no_paging
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/S

#5456 Automated cherry pick of #5455: fix: data export params add force_no_paging
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/S

#5457 Automated cherry pick of #5455: fix: data export params add force_no_paging
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/S

#5459 fix: ctyun
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Compute/constants/index.js
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/utils.js
  src/constants/compute.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#5460 Automated cherry pick of #5459: fix: ctyun
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Compute/constants/index.js
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/utils.js
  src/constants/compute.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#5461 Automated cherry pick of #5459: fix: ctyun
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Compute/constants/index.js
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/utils.js
  src/constants/compute.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#5466 fix(9375): 块存储存储类型搜索优化，类型从接口拉取数据
  containers/Storage/views/blockstorage/components/List.vue
Labels: size/M

#5467 Automated cherry pick of #5466: fix(9375): 块存储存储类型搜索优化，类型从接口拉取数据
  containers/Storage/views/blockstorage/components/List.vue
Labels: size/M

#5468 Automated cherry pick of #5466: fix(9375): 块存储存储类型搜索优化，类型从接口拉取数据
  containers/Storage/views/blockstorage/components/List.vue
Labels: size/M

#5469 feat(4581): 主机关机状态下部署agent
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
Labels: size/S

#5470 Automated cherry pick of #5469: feat(4581): 主机关机状态下部署agent
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
Labels: size/S

#5471 Automated cherry pick of #5469: feat(4581): 主机关机状态下部署agent
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
Labels: size/S

#5472 Automated cherry pick of #5469: feat(4581): 主机关机状态下部署agent
  containers/Compute/views/vminstance/components/InstallAgentForm.vue
Labels: size/S

#5473 fix(9348): 主机详情增加取消迁移
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/components/Detail/index.js
Labels: size/S

#5474 Automated cherry pick of #5473: fix(9348): 主机详情增加取消迁移
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/components/Detail/index.js
Labels: size/S

#5475 Automated cherry pick of #5473: fix(9348): 主机详情增加取消迁移
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/components/Detail/index.js
Labels: size/S

#5476 feat(4582): 主机详情增加引导模式
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/S

#5477 Automated cherry pick of #5476: feat(4582): 主机详情增加引导模式
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/S

#5479 Automated cherry pick of #5476: feat(4582): 主机详情增加引导模式
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/S

#5478 Automated cherry pick of #5476: feat(4582): 主机详情增加引导模式
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/S

#5480 fix(9345): 重装系统限制只能是关机状态
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#5481 Automated cherry pick of #5480: fix(9345): 重装系统限制只能是关机状态
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#5482 Automated cherry pick of #5480: fix(9345): 重装系统限制只能是关机状态
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#5483 feat(4520): optimization of cloud account synchronization strategy
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  src/sections/CloudregionZone/index.vue
Labels: size/L

#5484 Automated cherry pick of #5483: feat(4520): optimization of cloud account synchronization strategy
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  src/sections/CloudregionZone/index.vue
Labels: size/L

#5485 Automated cherry pick of #5483: feat(4520): optimization of cloud account synchronization strategy
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/create/index.vue
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  src/sections/CloudregionZone/index.vue
Labels: size/L

#5486 feat(4583): 设置USB透传弹窗修改文案
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
Labels: size/XS

#5488 feat(4520): account proxy set accuracy
  containers/Cloudenv/views/cloudaccount/components/ProxySetting.vue
Labels: size/S

#5489 Automated cherry pick of #5488: feat(4520): account proxy set accuracy
  containers/Cloudenv/views/cloudaccount/components/ProxySetting.vue
Labels: size/S

#5490 Automated cherry pick of #5488: feat(4520): account proxy set accuracy
  containers/Cloudenv/views/cloudaccount/components/ProxySetting.vue
Labels: size/S

#5491 fix: add oemVersion
  src/config/setting.js
Labels: size/XS

#5492 Automated cherry pick of #5491: fix: add oemVersion
  src/config/setting.js
Labels: size/XS

#5493 Automated cherry pick of #5491: fix: add oemVersion
  src/config/setting.js
Labels: size/XS

#5494 Automated cherry pick of #5491: fix: add oemVersion
  src/config/setting.js
Labels: size/XS

#5495 fix(9387): add name edit rule
  containers/Cloudenv/views/cloudregion/mixins/columns.js
  src/components/Edit/Form.vue
Labels: size/XS

#5496 Automated cherry pick of #5495: fix(9387): add name edit rule
  containers/Cloudenv/views/cloudregion/mixins/columns.js
  src/components/Edit/Form.vue
Labels: size/XS

#5497 Automated cherry pick of #5495: fix(9387): add name edit rule
  containers/Cloudenv/views/cloudregion/mixins/columns.js
  src/components/Edit/Form.vue
Labels: size/XS

#5498 feat(4530): KVM虚拟机支持磁盘限速
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/SetSpeed.vue
Labels: size/L

#5499 Automated cherry pick of #5498: feat(4530): KVM虚拟机支持磁盘限速
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/SetSpeed.vue
Labels: size/L

#5500 Automated cherry pick of #5498: feat(4530): KVM虚拟机支持磁盘限速
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/SetSpeed.vue
Labels: size/L

#5501 feat(4543): 项目管理员支持虚拟机续费和自动续费设置
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#5502 Automated cherry pick of #5501: feat(4543): 项目管理员支持虚拟机续费和自动续费设置
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#5503 Automated cherry pick of #5501: feat(4543): 项目管理员支持虚拟机续费和自动续费设置
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#5505 Automated cherry pick of #5504: fix(9364): 容器云新建定时任务前端报错
  containers/K8S/utils/index.js
Labels: size/S

#5506 Automated cherry pick of #5504: fix(9364): 容器云新建定时任务前端报错
  containers/K8S/utils/index.js
Labels: size/S

#5507 fix(9346): 域管理员新建应用报错，权限不足
  containers/Helm/views/chart/create/index.vue
Labels: size/S

#5508 Automated cherry pick of #5507: fix(9346): 域管理员新建应用报错，权限不足
  containers/Helm/views/chart/create/index.vue
Labels: size/S

#5509 Automated cherry pick of #5507: fix(9346): 域管理员新建应用报错，权限不足
  containers/Helm/views/chart/create/index.vue
Labels: size/S

#5510 fix: 应用市场监控配置数据回填信息不准确，需要清空
  containers/Helm/views/chart/create/index.vue
Labels: size/S

#5515 Automated cherry pick of #5510: fix: 应用市场监控配置数据回填信息不准确，需要清空
  containers/Helm/views/chart/create/index.vue
Labels: size/S

#5511 fix(9333): add time filter white list
  src/components/SearchBox/index.vue
Labels: size/XS

#5512 Automated cherry pick of #5511: fix(9333): add time filter white list
  src/components/SearchBox/index.vue
Labels: size/XS

#5517 feat(4520): account set project mapping accuracy
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
  containers/Cloudenv/views/cloudaccount/sidepage/index.vue
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  src/sections/DialogManager/components/CustomList.vue
Labels: size/L

#5518 Automated cherry pick of #5517: feat(4520): account set project mapping accuracy
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
  containers/Cloudenv/views/cloudaccount/sidepage/index.vue
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  src/sections/DialogManager/components/CustomList.vue
Labels: size/L

#5519 Automated cherry pick of #5517: feat(4520): account set project mapping accuracy
  containers/Cloudenv/views/cloudaccount/components/List.vue
  containers/Cloudenv/views/cloudaccount/mixins/columns.js
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
  containers/Cloudenv/views/cloudaccount/sidepage/index.vue
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  src/sections/DialogManager/components/CustomList.vue
Labels: size/L

#5520 fix: disk and instance backup add ui hidden check
  containers/Compute/router/index.js
Labels: size/XS

#5521 Automated cherry pick of #5520: fix: disk and instance backup add ui hidden check
  containers/Compute/router/index.js
Labels: size/XS

#5522 Automated cherry pick of #5520: fix: disk and instance backup add ui hidden check
  containers/Compute/router/index.js
Labels: size/XS

#5523 feat(4520): cloudaccount set project mapping accuracy
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/L

#5524 Automated cherry pick of #5523: feat(4520): cloudaccount set project mapping accuracy
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/L

#5525 Automated cherry pick of #5523: feat(4520): cloudaccount set project mapping accuracy
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/L

#5526 fix(18333): 透传设备页外链文档资源失效
  containers/Compute/views/pci/dialogs/create.vue
Labels: size/S

#5527 Automated cherry pick of #5526: fix(18333): 透传设备页外链文档资源失效
  containers/Compute/views/pci/dialogs/create.vue
Labels: size/S

#5528 Automated cherry pick of #5526: fix(18333): 透传设备页外链文档资源失效
  containers/Compute/views/pci/dialogs/create.vue
Labels: size/S

#5529 fix: support network additional wires
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/sidepage/Detail.vue
  containers/Network/views/wire/components/List.vue
  containers/Network/views/wire/sidepage/Detail.vue
  containers/Storage/views/blockstorage/sidepage/Monitor.vue
  containers/Storage/views/blockstorage/sidepage/index.vue
  containers/Storage/views/bucket/index.vue
  containers/Storage/views/file-system/components/List.vue
  containers/Storage/views/file-system/sidepage/Detail.vue
  containers/Storage/views/file-system/sidepage/index.vue
  containers/Storage/views/mount-target/sidepage/index.vue
  containers/Storage/views/tablestore/sidepage/index.vue
Labels: size/L

#5530 Automated cherry pick of #5529: fix: support network additional wires
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/sidepage/Detail.vue
  containers/Network/views/wire/components/List.vue
  containers/Network/views/wire/sidepage/Detail.vue
  containers/Storage/views/blockstorage/sidepage/Monitor.vue
  containers/Storage/views/blockstorage/sidepage/index.vue
  containers/Storage/views/bucket/index.vue
  containers/Storage/views/file-system/components/List.vue
  containers/Storage/views/file-system/sidepage/Detail.vue
  containers/Storage/views/file-system/sidepage/index.vue
  containers/Storage/views/mount-target/sidepage/index.vue
  containers/Storage/views/tablestore/sidepage/index.vue
Labels: size/L

#5531 feat(4588): recovery list add event log
  containers/Compute/views/disk-recovery/components/List.vue
  containers/Compute/views/disk-recovery/mixins/columns.js
  containers/Compute/views/disk-recovery/sidepage/index.vue
  containers/Compute/views/image-recovery/components/List.vue
  containers/Compute/views/image-recovery/mixins/columns.js
  containers/Compute/views/image-recovery/mixins/singleActions.js
  containers/Compute/views/image-recovery/sidepage/index.vue
  containers/Compute/views/server-recovery/components/List.vue
  containers/Compute/views/server-recovery/mixins/columns.js
  containers/Compute/views/server-recovery/sidepage/index.vue
Labels: size/L

#5532 Automated cherry pick of #5531: feat(4588): recovery list add event log
  containers/Compute/views/disk-recovery/components/List.vue
  containers/Compute/views/disk-recovery/mixins/columns.js
  containers/Compute/views/disk-recovery/sidepage/index.vue
  containers/Compute/views/image-recovery/components/List.vue
  containers/Compute/views/image-recovery/mixins/columns.js
  containers/Compute/views/image-recovery/mixins/singleActions.js
  containers/Compute/views/image-recovery/sidepage/index.vue
  containers/Compute/views/server-recovery/components/List.vue
  containers/Compute/views/server-recovery/mixins/columns.js
  containers/Compute/views/server-recovery/sidepage/index.vue
Labels: size/L

#5533 Automated cherry pick of #5531: feat(4588): recovery list add event log
  containers/Compute/views/disk-recovery/components/List.vue
  containers/Compute/views/disk-recovery/mixins/columns.js
  containers/Compute/views/disk-recovery/sidepage/index.vue
  containers/Compute/views/image-recovery/components/List.vue
  containers/Compute/views/image-recovery/mixins/columns.js
  containers/Compute/views/image-recovery/mixins/singleActions.js
  containers/Compute/views/image-recovery/sidepage/index.vue
  containers/Compute/views/server-recovery/components/List.vue
  containers/Compute/views/server-recovery/mixins/columns.js
  containers/Compute/views/server-recovery/sidepage/index.vue
Labels: size/L

#5534 feat(4587): update navbar icon
  src/components/Icon/assets/cloudshell.svg
  src/components/Icon/assets/daping.svg
  src/components/Icon/assets/dollar.svg
  src/components/Icon/assets/navbar-notify.svg
  src/components/Icon/assets/navbar-process.svg
  src/components/Icon/assets/res-commonalert.svg
Labels: size/S

#5536 feat(4500): bucket policy support mutiple cloud
  containers/Storage/locales/en.json
  containers/Storage/locales/zh-CN.json
  containers/Storage/views/bucket/sidepage/CrossDomainRules.vue
  containers/Storage/views/bucket/sidepage/Policies.vue
Labels: size/M

#5540 fix(9397): fix v-charts error
  src/main.js
Labels: size/XS

#5541 Automated cherry pick of #5540: fix(9397): fix v-charts error
  src/main.js
Labels: size/XS

#5542 Automated cherry pick of #5540: fix(9397): fix v-charts error
  src/main.js
Labels: size/XS

#5537 feat(4590): 设置VMware IP子网的附属二层网络
  containers/Cloudenv/views/cloudaccount/create/form/components/BaiduCloud.vue
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/dialogs/SetAdditionalWiresDialog.vue
  containers/Network/views/network/mixins/singleActions.js
  containers/Network/views/network/sidepage/Detail.vue
Labels: size/L

#5544 Automated cherry pick of #5537: feat(4590): 设置VMware IP子网的附属二层网络
  containers/Cloudenv/views/cloudaccount/create/form/components/BaiduCloud.vue
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/dialogs/SetAdditionalWiresDialog.vue
  containers/Network/views/network/mixins/singleActions.js
  containers/Network/views/network/sidepage/Detail.vue
Labels: size/L

#5538 fix(9395): 新增云账号后，应该主动刷新 capability 接口
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: size/XS

#5545 Automated cherry pick of #5538: fix(9395): 新增云账号后，应该主动刷新 capability 接口
  containers/Cloudenv/views/cloudaccount/create/index.vue
Labels: size/XS

#5539 fix(9394): VMware主机应允许更换IP地址
  containers/Compute/views/networks/mixins/singleActions.js
Labels: size/XS

#5543 fix(9393): VMware主机详情的”（可补IP）“点击设置后没有效果
  src/sections/IpSupplement/index.vue
Labels: size/XS

#5547 Automated cherry pick of #5543: fix(9393): VMware主机详情的”（可补IP）“点击设置后没有效果
  src/sections/IpSupplement/index.vue
Labels: size/XS

#5548 Automated cherry pick of #5543: fix(9393): VMware主机详情的”（可补IP）“点击设置后没有效果
  src/sections/IpSupplement/index.vue
Labels: size/XS

#5549 feat(4590): 设置VMware IP子网的附属二层网络，调整设置按钮样式及数据过滤处理
  containers/Network/views/network/dialogs/SetAdditionalWiresDialog.vue
  containers/Network/views/network/sidepage/Detail.vue
Labels: size/M

#5550 Automated cherry pick of #5549: feat(4590): 设置VMware IP子网的附属二层网络，调整设置按钮样式及数据过滤处理
  containers/Network/views/network/dialogs/SetAdditionalWiresDialog.vue
  containers/Network/views/network/sidepage/Detail.vue
Labels: size/M

#5551 fix: 防止列表初始设置过滤条件时报错
  src/components/SearchBox/Tag.vue
Labels: size/XS
