Repository yunionio/dashboard, pull requests merged in 2023-01, with the labels that each got.

#3926 feat: #4093 blockstorage detail add schedtag info
  containers/Storage/views/blockstorage/sidepage/Detail.vue
Labels: area/storage, size/S

#3927 Automated cherry pick of #3926: feat: #4093 blockstorage detail add schedtag info
  containers/Storage/views/blockstorage/sidepage/Detail.vue
Labels: size/S

#3928 Automated cherry pick of #3926: feat: #4093 blockstorage detail add schedtag info
  containers/Storage/views/blockstorage/sidepage/Detail.vue
Labels: size/S

#3929 Automated cherry pick of #3926: feat: #4093 blockstorage detail add schedtag info
  containers/Storage/views/blockstorage/sidepage/Detail.vue
Labels: size/S

#3924 fix: cloudaccount details show account_id
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: size/S

#3925 Automated cherry pick of #3924: fix: cloudaccount details show account_id
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: size/S

#3930 feat: #4082 cloudaccount detail add lake_of_permissions export
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: area/cloudenv, size/S

#3931 Automated cherry pick of #3930: feat: #4082 cloudaccount detail add lake_of_permissions export
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: size/S

#3932 Automated cherry pick of #3930: feat: #4082 cloudaccount detail add lake_of_permissions export
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
Labels: size/S

#3933 feat: #4093 blockstorage set schedtag(multiple)
  containers/Storage/views/blockstorage/dialogs/UpdateTags.vue
Labels: area/storage, size/XS

#3934 Automated cherry pick of #3933: feat: #4093 blockstorage set schedtag(multiple)
  containers/Storage/views/blockstorage/dialogs/UpdateTags.vue
Labels: size/XS

#3935 Automated cherry pick of #3933: feat: #4093 blockstorage set schedtag(multiple)
  containers/Storage/views/blockstorage/dialogs/UpdateTags.vue
Labels: size/XS

#3936 feat: #3721 LB资源增加状态概览
  containers/Network/views/lb/index.vue
  src/constants/statisticsRes.js
  src/mixins/list.js
  src/sections/ResStatusTab/index.vue
Labels: size/M

#3937 Automated cherry pick of #3936: feat: #3721 LB资源增加状态概览
  containers/Network/views/lb/index.vue
  src/constants/statisticsRes.js
  src/mixins/list.js
  src/sections/ResStatusTab/index.vue
Labels: size/M

#3938 Automated cherry pick of #3936: feat: #3721 LB资源增加状态概览
  containers/Network/views/lb/index.vue
  src/constants/statisticsRes.js
  src/mixins/list.js
  src/sections/ResStatusTab/index.vue
Labels: size/M

#3939 feat: 更新资源状态Key值
  containers/Compute/views/disk/index.vue
  containers/Compute/views/host-image/index.vue
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/index.vue
  containers/Compute/views/image/index.vue
  containers/Compute/views/physicalmachine/components/List.vue
  containers/Compute/views/physicalmachine/index.vue
  containers/Compute/views/snapshot-instance/index.vue
  containers/Compute/views/snapshot/index.vue
  containers/DB/views/mongodb/index.vue
  containers/DB/views/rds/index.vue
  containers/DB/views/redis/index.vue
  containers/Network/views/cdn/index.vue
  containers/Network/views/eip/index.vue
  containers/Network/views/network/index.vue
  containers/Network/views/vpc/index.vue
  containers/Network/views/wire/index.vue
  src/mixins/resStatusFilterMixin.js
Labels: size/M

#3940 Automated cherry pick of #3939: feat: 更新资源状态Key值
  containers/Compute/views/disk/index.vue
  containers/Compute/views/host-image/index.vue
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/index.vue
  containers/Compute/views/image/index.vue
  containers/Compute/views/physicalmachine/components/List.vue
  containers/Compute/views/physicalmachine/index.vue
  containers/Compute/views/snapshot-instance/index.vue
  containers/Compute/views/snapshot/index.vue
  containers/DB/views/mongodb/index.vue
  containers/DB/views/rds/index.vue
  containers/DB/views/redis/index.vue
  containers/Network/views/cdn/index.vue
  containers/Network/views/eip/index.vue
  containers/Network/views/network/index.vue
  containers/Network/views/vpc/index.vue
  containers/Network/views/wire/index.vue
  src/mixins/resStatusFilterMixin.js
Labels: size/M

#3941 Automated cherry pick of #3939: feat: 更新资源状态Key值
  containers/Compute/views/disk/index.vue
  containers/Compute/views/host-image/index.vue
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/index.vue
  containers/Compute/views/image/index.vue
  containers/Compute/views/physicalmachine/components/List.vue
  containers/Compute/views/physicalmachine/index.vue
  containers/Compute/views/snapshot-instance/index.vue
  containers/Compute/views/snapshot/index.vue
  containers/DB/views/mongodb/index.vue
  containers/DB/views/rds/index.vue
  containers/DB/views/redis/index.vue
  containers/Network/views/cdn/index.vue
  containers/Network/views/eip/index.vue
  containers/Network/views/network/index.vue
  containers/Network/views/vpc/index.vue
  containers/Network/views/wire/index.vue
  src/mixins/resStatusFilterMixin.js
Labels: size/M

#3942 fix: monitor unit scale error
  src/utils/utils.js
Labels: size/XS

#3943 Automated cherry pick of #3942: fix: monitor unit scale error
  src/utils/utils.js
Labels: size/XS

#3945 fix: 回收站状态列不显示查看日志
  containers/Compute/views/disk-recovery/mixins/columns.js
  containers/Compute/views/image-recovery/mixins/columns.js
  containers/Compute/views/server-recovery/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/S

#3946 Automated cherry pick of #3945: fix: 回收站状态列不显示查看日志
  containers/Compute/views/disk-recovery/mixins/columns.js
  containers/Compute/views/image-recovery/mixins/columns.js
  containers/Compute/views/server-recovery/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/S

#3948 Automated cherry pick of #3945: fix: 回收站状态列不显示查看日志
  containers/Compute/views/disk-recovery/mixins/columns.js
  containers/Compute/views/image-recovery/mixins/columns.js
  containers/Compute/views/server-recovery/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/S

#3947 Automated cherry pick of #3945: fix: 回收站状态列不显示查看日志
  containers/Compute/views/disk-recovery/mixins/columns.js
  containers/Compute/views/image-recovery/mixins/columns.js
  containers/Compute/views/server-recovery/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/S

#3949 Feat/glb to 3.9/compute
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/utils.js
Labels: area/compute, size/L

#3950 Automated cherry pick of #3949: feat: #4100 vmware support transfer in status running
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/utils.js
Labels: size/L

#3952 Automated cherry pick of #3951: feat: 存储桶增加资源状态概览
  containers/Storage/views/bucket/index.vue
  src/constants/statisticsRes.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/ResStatusTab/index.vue
Labels: size/M

#3953 Automated cherry pick of #3951: feat: 存储桶增加资源状态概览
  containers/Storage/views/bucket/index.vue
  src/constants/statisticsRes.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/ResStatusTab/index.vue
Labels: size/M

#3954 feat: #4110 date time component support set time from localstorage
  src/components/DateTime/index.vue
  src/styles/less/global.less
  src/utils/list.js
Labels: size/M

#3955 Automated cherry pick of #3954: feat: list component expend
  src/components/DateTime/index.vue
  src/styles/less/global.less
  src/utils/list.js
Labels: size/M

#3956 fix(scope): use monitorresourcealerts api
  scope/store/modules/app.js
Labels: size/XS

#3957 Automated cherry pick of #3956: fix(scope): use monitorresourcealerts api
  scope/store/modules/app.js
Labels: size/XS

#3958 Automated cherry pick of #3956: fix(scope): use monitorresourcealerts api
  scope/store/modules/app.js
Labels: size/XS

#3959 Automated cherry pick of #3956: fix(scope): use monitorresourcealerts api
  scope/store/modules/app.js
Labels: size/XS

#3960 feat: #4086 账单汇总订阅新增账单数据范围和新通知类型角色
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/RangeScope/index.vue
Labels: size/L

#3961 Automated cherry pick of #3960: feat: #4086 账单汇总订阅新增账单数据范围和新通知类型角色
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/RangeScope/index.vue
Labels: size/L

#3964 fix: range scope select
  src/sections/RangeScope/index.vue
Labels: size/XS

#3965 Automated cherry pick of #3964: fix: range scope select
  src/sections/RangeScope/index.vue
Labels: size/XS

#3966 fix: range scope i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#3968 fix: range scope extra
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/RangeScope/index.vue
  src/utils/common/tableColumn.js
Labels: size/S

#3969 Automated cherry pick of #3968: fix: range scope extra
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/RangeScope/index.vue
  src/utils/common/tableColumn.js
Labels: size/S

#3970 fix: 修复详情页面刷新无效问题
  src/components/BaseSidePage/index.vue
  src/mixins/sidePage.js
Labels: size/XS

#3971 Automated cherry pick of #3970: fix: 修复详情页面刷新无效问题
  src/components/BaseSidePage/index.vue
  src/mixins/sidePage.js
Labels: size/XS

#3973 fix: 修复选择域及项目时的传参问题
  src/sections/RangeScope/index.vue
  src/sections/ScopeRadio/index.vue
  src/utils/rangeScope.js
Labels: size/M

#3974 Automated cherry pick of #3973: fix: 修复选择域及项目时的传参问题
  src/sections/RangeScope/index.vue
  src/sections/ScopeRadio/index.vue
  src/utils/rangeScope.js
Labels: size/M

#3977 fix: 账单汇总订阅归属选择域，数据范围选择域整体，设置其他域新建后最终都会归属到default域
  src/sections/RangeScope/index.vue
Labels: size/S

#3978 Automated cherry pick of #3977: fix: 账单汇总订阅归属选择域，数据范围选择域整体，设置其他域新建后最终都会归属到default域
  src/sections/RangeScope/index.vue
Labels: size/S

#3975 feat: #4110 datetime select change to date-ranger
  src/components/DateTime/CustomDate.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableFilter.js
Labels: size/L

#3976 Automated cherry pick of #3975: feat: expend utils
  src/components/DateTime/CustomDate.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableFilter.js
Labels: size/L

#3979 fix: 数据范围选择项目时域值联动问题
  src/sections/RangeScope/index.vue
Labels: size/S

#3981 feat: #4100 vmware support transfer
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
  containers/Compute/views/vminstance/utils.js
Labels: size/S

#3982 feat: #4100 vmtransfer add manager filter for hosts
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: area/compute, size/S

#3983 Automated cherry pick of #3982: feat: #4100 vmtransfer add manager filter for hosts
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/S

#3985 fix: remove apply_resource_order code
  src/components/Icon/assets/select-switch.svg
  src/locales/en.json
  src/locales/zh-CN.json
  src/router/routes.js
  src/views/workflow-apply-internal-resource/components/WorkflowLabel.vue
  src/views/workflow-apply-internal-resource/components/WorkflowTips.vue
  src/views/workflow-apply-internal-resource/components/form/BasicSecurityServices.vue
  src/views/workflow-apply-internal-resource/components/form/CloudSecurityTable.vue
  src/views/workflow-apply-internal-resource/components/form/ContractorInfo.vue
  src/views/workflow-apply-internal-resource/components/form/Ecs.vue
  src/views/workflow-apply-internal-resource/components/form/ProjectInfo.vue
  src/views/workflow-apply-internal-resource/components/form/Rds.vue
  src/views/workflow-apply-internal-resource/components/form/Server.vue
  src/views/workflow-apply-internal-resource/components/form/unitInfo.vue
  src/views/workflow-apply-internal-resource/constants.js
  src/views/workflow-apply-internal-resource/dialogs/AddInfo.vue
  src/views/workflow-apply-internal-resource/index.vue
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/XXL

#3987 feat: #4125 IP地址新增mac地址维护表
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/dialogs/ImportNetworkIpMacs.vue
  containers/Network/views/network/dialogs/NetworkIpMacsCreate.vue
  containers/Network/views/network/sidepage/NetworkIpMacs.vue
  containers/Network/views/network/sidepage/index.vue
Labels: size/XL

#3988 Automated cherry pick of #3987: feat: #4125 IP地址新增mac地址维护表
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/dialogs/ImportNetworkIpMacs.vue
  containers/Network/views/network/dialogs/NetworkIpMacsCreate.vue
  containers/Network/views/network/sidepage/NetworkIpMacs.vue
  containers/Network/views/network/sidepage/index.vue
Labels: size/XL

#3989 fix: #8755 接收人管理域过滤失效
  containers/IAM/views/contact/components/List.vue
Labels: size/XS

#3990 Automated cherry pick of #3989: fix: #8755 接收人管理域过滤失效
  containers/IAM/views/contact/components/List.vue
Labels: size/XS

#3991 feat: IP地址新增mac地址维护表问题处理
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/dialogs/NetworkIpMacsCreate.vue
  containers/Network/views/network/sidepage/NetworkIpMacs.vue
  containers/Network/views/network/sidepage/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#3992 Automated cherry pick of #3991: feat: IP地址新增mac地址维护表问题处理
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/dialogs/NetworkIpMacsCreate.vue
  containers/Network/views/network/sidepage/NetworkIpMacs.vue
  containers/Network/views/network/sidepage/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#3993 fix: 修复组件params值而非引用更改后重新拉取数据的问题
  src/components/OcSelect/index.vue
Labels: size/S

#3997 Automated cherry pick of #3993: fix: 修复组件params值而非引用更改后重新拉取数据的问题
  src/components/OcSelect/index.vue
Labels: size/S

#3995 fix(qcloud): loadbalancer listener
  containers/Network/views/loadbalancerlistener/constants.js
  containers/Network/views/loadbalancerlistener/create/form/qcloud/Healthcheck.vue
Labels: size/M

#3996 Automated cherry pick of #3995: fix(qcloud): loadbalancer listener
  containers/Network/views/loadbalancerlistener/constants.js
  containers/Network/views/loadbalancerlistener/create/form/qcloud/Healthcheck.vue
Labels: size/M

#3999 feat: add qga exec command failed status i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#4003 fix: #8763 监控top5使用平台过滤无效
  containers/Dashboard/extends/Top5/index.vue
Labels: size/XS

#4004 Automated cherry pick of #4003: fix: #8763 监控top5使用平台过滤无效
  containers/Dashboard/extends/Top5/index.vue
Labels: size/XS

#4006 fix: #8740 调整资源权限的位置
  containers/IAM/views/policy/components/Form/PolicyRuleCheckbox/index.vue
Labels: size/S

#3998 fix(network): wrong lbagent yum repo url
  containers/Network/views/agent/dialogs/Deploy.vue
Labels: size/S

#4011 feat: workflow
  src/sections/Navbar/components/WorkOrderPopover.vue
  src/views/workflow/utils/columns.js
Labels: size/M

#4014 Automated cherry pick of #4013: feat: #4126 网络选择空间交互优化：vpc区分经典网络和VPC网络
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  src/components/OcSelect/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#4017 Automated cherry pick of #4016: fix: #8368 OpenStack迁移找不到可用宿主机问题
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#4019 fix: 修复宿主机批量操作时无法操作，提示共享宿主机不支持该操作
  containers/Compute/views/host/components/List.vue
Labels: size/XS

#4020 Automated cherry pick of #4019: fix: 修复宿主机批量操作时无法操作，提示共享宿主机不支持该操作
  containers/Compute/views/host/components/List.vue
Labels: size/XS

#4022 Automated cherry pick of #4021: feat: add workflow paramter parse func
  src/mixins/workflow.js
  src/utils/utils.js
  src/views/workflow/components/ApplyInternalResource.vue
  src/views/workflow/me-process/mixins/singleActions.js
  src/views/workflow/utils/columns.js
Labels: size/M

#4023 feat: apply-resource-order add details info
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/L

#4029 feat: modify workflow detail info
  src/locales/en.json
  src/locales/zh-CN.json
  src/views/workflow/all-process/sidepage/Detail.vue
  src/views/workflow/approval-start/dialogs/RejectDialog.vue
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/approved-done/sidepage/Detail.vue
  src/views/workflow/components/ApplyInternalResource.vue
  src/views/workflow/me-partake/sidepage/Detail.vue
  src/views/workflow/me-process/sidepage/Detail.vue
Labels: size/S

#4030 Automated cherry pick of #4029: feat: modify workflow detail info
  src/locales/en.json
  src/locales/zh-CN.json
  src/views/workflow/all-process/sidepage/Detail.vue
  src/views/workflow/approval-start/dialogs/RejectDialog.vue
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/approved-done/sidepage/Detail.vue
  src/views/workflow/components/ApplyInternalResource.vue
  src/views/workflow/me-partake/sidepage/Detail.vue
  src/views/workflow/me-process/sidepage/Detail.vue
Labels: size/S

#4033 fix: #8752 monitor exploer update pager when data refresh
  containers/Monitor/sections/MonitorLine/index.vue
Labels: size/XS

#4036 Automated cherry pick of #4008: fix: #8739 新增的消息topic 应该翻译成中文
  containers/IAM/constants/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/S

#4038 Automated cherry pick of #4037: fix: 新增的消息topic 应该翻译成中文
  containers/IAM/constants/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/S

#4039 Automated cherry pick of #4037: fix: 新增的消息topic 应该翻译成中文
  containers/IAM/constants/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/S

#4040 fix: 修复消息订阅复制英文问题
  containers/IAM/views/notify-topic/mixins/columns.js
Labels: size/XS

#4041 Automated cherry pick of #4040: fix: 修复消息订阅复制英文问题
  containers/IAM/views/notify-topic/mixins/columns.js
Labels: size/XS

#4042 Automated cherry pick of #4040: fix: 修复消息订阅复制英文问题
  containers/IAM/views/notify-topic/mixins/columns.js
Labels: size/XS

#4043 fix: #8703 k8s-chart create add influxdb default value
  containers/Helm/views/chart/create/index.vue
  src/components/JsonSchemaForm/control/Control.js
  src/components/JsonSchemaForm/form/Form.js
  src/components/JsonSchemaForm/mixins/index.js
Labels: size/M

#4044 Automated cherry pick of #4043: fix: #8703 k8s-chart create add influxdb default value
  containers/Helm/views/chart/create/index.vue
  src/components/JsonSchemaForm/control/Control.js
  src/components/JsonSchemaForm/form/Form.js
  src/components/JsonSchemaForm/mixins/index.js
Labels: size/M

#4045 feat: update modelarts icon
  src/components/Icon/assets/._res-modelarts.svg
  src/components/Icon/assets/res-modelarts.svg
Labels: size/M

#4048 Automated cherry pick of #4047: fix: 修复订阅列表数据范围文案显示问题
  src/utils/rangeScope.js
Labels: size/XS

#4049 support: vmware rebuild root by template
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/XS

#4051 fix: cloudaccount sync_net_failed status
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#4052 Automated cherry pick of #4051: fix: cloudaccount sync_net_failed status
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#4053 fix(lb): remove useless field
  containers/Network/views/loadbalancerbackend/mixins/columns.js
  containers/Network/views/loadbalancerbackendgroup/mixins/columns.js
  containers/Network/views/loadbalancerlistener/mixins/columns.js
Labels: size/XS

#4054 Automated cherry pick of #4053: fix(lb): remove useless field
  containers/Network/views/loadbalancerbackend/mixins/columns.js
  containers/Network/views/loadbalancerbackendgroup/mixins/columns.js
  containers/Network/views/loadbalancerlistener/mixins/columns.js
Labels: size/XS

#4055 feat: #4099 大页内存标识增加
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/mixins/columns.js
  src/components/Icon/assets/._res-modelarts.svg
  src/components/Icon/assets/large-page-memory.svg
Labels: size/S

#4056 Automated cherry pick of #4055: feat: #4099 大页内存标识增加
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/mixins/columns.js
  src/components/Icon/assets/._res-modelarts.svg
  src/components/Icon/assets/large-page-memory.svg
Labels: size/S

#4058 Automated cherry pick of #4057: feat: #4143 add i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/components/DateTime/index.vue
Labels: size/S

#4059 feat: 修改大页内存文案信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
Labels: size/XS

#4060 Automated cherry pick of #4059: feat: 修改大页内存文案信息
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
Labels: size/XS

#4061 feat: #4130 纳管的私有云和cloudpods账号也可以重跑账单
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/S

#4063 feat: #4130 云账号菜单分类
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XL

#4067 feat: #4043 add global-search (dns-recordset)
  containers/Network/views/dns-recordset/components/List.vue
  src/constants/globalSearch.js
  src/sections/Navbar/index.vue
  src/views/global-search-result/index.vue
Labels: size/M

#4068 Automated cherry pick of #4067: feat: #4043 add global-search (dns-recordset)
  containers/Network/views/dns-recordset/components/List.vue
  src/constants/globalSearch.js
  src/sections/Navbar/index.vue
  src/views/global-search-result/index.vue
Labels: size/M

#4069 Automated cherry pick of #4067: feat: #4043 add global-search (dns-recordset)
  containers/Network/views/dns-recordset/components/List.vue
  src/constants/globalSearch.js
  src/sections/Navbar/index.vue
  src/views/global-search-result/index.vue
Labels: size/M

#4070 feat: #3908 tag-value is required
  containers/Cloudenv/views/projectmapping/components/Tag.vue
  containers/Cloudenv/views/server-price-comparator/create/components/Tag.vue
  containers/Compute/views/vminstance/create/components/Tag.vue
  src/sections/DialogManager/components/SetTag.vue
  src/sections/Tag/index.vue
Labels: size/S

#4071 Automated cherry pick of #4070: feat: #3908 tag-value is required
  containers/Cloudenv/views/projectmapping/components/Tag.vue
  containers/Cloudenv/views/server-price-comparator/create/components/Tag.vue
  containers/Compute/views/vminstance/create/components/Tag.vue
  src/sections/DialogManager/components/SetTag.vue
  src/sections/Tag/index.vue
Labels: size/S

#4072 feat(4103): 虚拟机操作归属优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XL

#4073 Automated cherry pick of #4072: feat(4103): 虚拟机操作归属优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XL

#4074 feat: 宿主机详情网络优化
  containers/Compute/views/host/sidepage/index.vue
Labels: size/S

#4075 Automated cherry pick of #4074: feat: 宿主机详情网络优化
  containers/Compute/views/host/sidepage/index.vue
Labels: size/S

#4076 feat(4148): add i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#4077 Automated cherry pick of #4076: feat(4148): add i18n
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#4080 Automated cherry pick of #4074: feat: 宿主机详情网络优化
  containers/Compute/views/host/sidepage/index.vue
Labels: size/S

#4079 feat: 宿主机及物理机详情网络设置二层网络刷新详情信息
  containers/Compute/views/physicalmachine/dialogs/Setwire.vue
  containers/Compute/views/physicalmachine/sidepage/Network.vue
Labels: size/S

#4081 Automated cherry pick of #4079: feat: 宿主机及物理机详情网络设置二层网络刷新详情信息
  containers/Compute/views/physicalmachine/dialogs/Setwire.vue
  containers/Compute/views/physicalmachine/sidepage/Network.vue
Labels: size/S

#4082 Automated cherry pick of #4079: feat: 宿主机及物理机详情网络设置二层网络刷新详情信息
  containers/Compute/views/physicalmachine/dialogs/Setwire.vue
  containers/Compute/views/physicalmachine/sidepage/Network.vue
Labels: size/S

#4078 feat(build,test): 新增 dry_run 模式以便夜间测试
  scripts/docker_push.sh
Labels: size/XS

#4084 feat(build,test): 新增 dry_run 模式以便夜间测试2
  scripts/docker_push.sh
Labels: size/XS

#4085 Automated cherry pick of #4084: feat(build,test): 新增 dry_run 模式以便夜间测试2
  scripts/docker_push.sh
Labels: size/XS
