Repository yunionio/dashboard, pull requests merged in 2023-02, with the labels that each got.

#4087 fix: minor fixes of lb cluster and agent
  containers/Network/views/agent/mixins/singleActions.js
  containers/Network/views/agent/sidepage/Detail.vue
  containers/Network/views/loadbalancercluster/mixins/columns.js
Labels: size/S

#4088 Automated cherry pick of #4087: fix: minor fixes of lb cluster and agent
  containers/Network/views/agent/mixins/singleActions.js
  containers/Network/views/agent/sidepage/Detail.vue
  containers/Network/views/loadbalancercluster/mixins/columns.js
Labels: size/S

#4086 feat(build,test): 新增 dry_run 模式以便夜间测试 for 3.9
  scripts/docker-push.sh
Labels: size/XS

#4090 Automated cherry pick of #4089: feat(4117): extend workflow detail info
  src/views/workflow/components/ApplyInternalResource.vue
Labels: size/M

#4093 feat(4043): dns recordset add owner domain name column
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/dns-recordset/mixins/columns.js
  src/constants/globalSearch.js
  src/views/global-search-result/index.vue
Labels: area/network, size/S

#4094 Automated cherry pick of #4093: feat(4043): dns recordset add owner domain name column
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/dns-recordset/mixins/columns.js
  src/constants/globalSearch.js
  src/views/global-search-result/index.vue
Labels: size/S

#4095 Automated cherry pick of #4093: feat(4043): dns recordset add owner domain name column
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/dns-recordset/mixins/columns.js
  src/constants/globalSearch.js
  src/views/global-search-result/index.vue
Labels: size/S

#4096 feat: #4154 集群改进增加修改
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/loadbalancercluster/mixins/singleActions.js
  containers/Network/views/loadbalancercluster/update/index.vue
Labels: size/L

#4097 Automated cherry pick of #4096: feat: #4154 集群改进增加修改
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/loadbalancercluster/mixins/singleActions.js
  containers/Network/views/loadbalancercluster/update/index.vue
Labels: size/L

#4098 feat: 节点增加关联集群操作
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/agent/dialogs/AssociatedCluster.vue
  containers/Network/views/agent/mixins/singleActions.js
Labels: size/L

#4099 Automated cherry pick of #4098: feat: 节点增加关联集群操作
  containers/Network/locales/en.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/agent/dialogs/AssociatedCluster.vue
  containers/Network/views/agent/mixins/singleActions.js
Labels: size/L

#4102 feat: LB节点功能改进
  containers/Network/views/agent/components/List.vue
  containers/Network/views/agent/dialogs/AssociatedCluster.vue
  containers/Network/views/agent/form/index.vue
  containers/Network/views/agent/mixins/singleActions.js
Labels: size/L

#4103 Automated cherry pick of #4102: feat: LB节点功能改进
  containers/Network/views/agent/components/List.vue
  containers/Network/views/agent/dialogs/AssociatedCluster.vue
  containers/Network/views/agent/form/index.vue
  containers/Network/views/agent/mixins/singleActions.js
Labels: size/L

#4105 Automated cherry pick of #4104: feat: change logo
  scope/images/cloudpod_login_logo.png
  scope/images/cloudpod_login_logo.svg
  scope/images/cloudpod_logo.png
  scope/images/cloudpod_logo.svg
  scope/store/modules/app.js
Labels: size/XXL

#4106 Automated cherry pick of #4104: feat: change logo
  scope/images/cloudpod_login_logo.png
  scope/images/cloudpod_login_logo.svg
  scope/images/cloudpod_logo.png
  scope/images/cloudpod_logo.svg
  scope/store/modules/app.js
Labels: size/XXL

#4107 feat(4158): monitor support select group function
  containers/Compute/sections/monitor/BaseMonitor.vue
  containers/Compute/views/host/sidepage/Monitor.vue
  containers/DB/views/rds/sidepage/Monitor.vue
  containers/DB/views/redis/sidepage/Monitor.vue
  containers/Monitor/views/commonalert/components/alert/index.vue
  containers/Monitor/views/dashboard/create/index.vue
  containers/Monitor/views/explorer/components/index.vue
  containers/Network/views/lb/sidepage/Monitor.vue
  containers/Network/views/loadbalancerlistener/sidepage/dashboard/MonitorControl.vue
  containers/Network/views/wire/sidepage/Monitor.vue
  containers/Storage/views/blockstorage/sidepage/Monitor.vue
  containers/Storage/views/bucket/sidepage/Monitor.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Monitor/Header.vue
  src/sections/Monitor/index.vue
  src/utils/monitor.js
Labels: area/monitor, size/L

#4108 Automated cherry pick of #4107: feat(4158): monitor support select group function
  containers/Compute/sections/monitor/BaseMonitor.vue
  containers/Compute/views/host/sidepage/Monitor.vue
  containers/DB/views/rds/sidepage/Monitor.vue
  containers/DB/views/redis/sidepage/Monitor.vue
  containers/Monitor/views/commonalert/components/alert/index.vue
  containers/Monitor/views/dashboard/create/index.vue
  containers/Monitor/views/explorer/components/index.vue
  containers/Network/views/lb/sidepage/Monitor.vue
  containers/Network/views/loadbalancerlistener/sidepage/dashboard/MonitorControl.vue
  containers/Network/views/wire/sidepage/Monitor.vue
  containers/Storage/views/blockstorage/sidepage/Monitor.vue
  containers/Storage/views/bucket/sidepage/Monitor.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/Monitor/Header.vue
  src/sections/Monitor/index.vue
  src/utils/monitor.js
Labels: size/L

#4109 feat(4138): monitor query config save to storage
  containers/Compute/sections/monitor/AgentMonitor.vue
  containers/Compute/sections/monitor/BaseMonitor.vue
  containers/Compute/views/host/sidepage/Monitor.vue
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  containers/DB/views/rds/sidepage/Monitor.vue
  containers/DB/views/redis/sidepage/Monitor.vue
  containers/Monitor/views/monitorresource/sidepage/Monitor.vue
  containers/Network/views/lb/sidepage/Monitor.vue
  containers/Network/views/wire/sidepage/Monitor.vue
  containers/Storage/views/blockstorage/sidepage/Monitor.vue
  containers/Storage/views/bucket/sidepage/Monitor.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/mixins/monitorTime.js
  src/sections/CustomDate/index.vue
  src/sections/Monitor/Header.vue
  src/sections/Monitor/index.vue
Labels: area/monitor, size/L

#4110 Automated cherry pick of #4109: feat(4138): monitor query config save to storage
  containers/Compute/sections/monitor/AgentMonitor.vue
  containers/Compute/sections/monitor/BaseMonitor.vue
  containers/Compute/views/host/sidepage/Monitor.vue
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  containers/DB/views/rds/sidepage/Monitor.vue
  containers/DB/views/redis/sidepage/Monitor.vue
  containers/Monitor/views/monitorresource/sidepage/Monitor.vue
  containers/Network/views/lb/sidepage/Monitor.vue
  containers/Network/views/wire/sidepage/Monitor.vue
  containers/Storage/views/blockstorage/sidepage/Monitor.vue
  containers/Storage/views/bucket/sidepage/Monitor.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/mixins/monitorTime.js
  src/sections/CustomDate/index.vue
  src/sections/Monitor/Header.vue
  src/sections/Monitor/index.vue
Labels: size/L

#4113 feat: #4153 自定义标签键除展示user类型外，同时展示ext类型标签
  src/sections/DialogManager/components/CustomList.vue
Labels: size/XS

#4114 Automated cherry pick of #4113: feat: #4153 自定义标签键除展示user类型外，同时展示ext类型标签
  src/sections/DialogManager/components/CustomList.vue
Labels: size/XS

#4111 feat(4151): list search support input in searchbar when query item is dropdown
  src/components/SearchBox/AutoCompleter.vue
Labels: size/XS

#4112 Automated cherry pick of #4111: feat(4151): list search support input in searchbar when query item is dropdown
  src/components/SearchBox/AutoCompleter.vue
Labels: size/XS

#4115 feat: #4115 详情页增加更改项目的快捷操作
  src/components/Detail/index.js
  src/components/Edit/index.js
  src/components/ListBodyCellWrap/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/ChangeOwenr.vue
Labels: size/M

#4116 Automated cherry pick of #4115: feat: 增加更改项目的快捷操作
  src/components/Detail/index.js
  src/components/Edit/index.js
  src/components/ListBodyCellWrap/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/ChangeOwenr.vue
Labels: size/M

#4119 feat: #4115 详情页增加主机名的快捷操作
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/utils/common/tableColumn.js
Labels: size/S

#4120 Automated cherry pick of #4119: feat: #4115 详情页增加主机名的快捷操作
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/utils/common/tableColumn.js
Labels: size/S

#4117 feat: add icon
  src/components/Icon/assets/res-report.svg
Labels: size/XS

#4118 Automated cherry pick of #4117: feat: add icon
  src/components/Icon/assets/res-report.svg
Labels: size/XS

#4121 feat: bill detail not support refresh
  src/components/BaseSidePage/index.vue
Labels: size/XS

#4123 feat: 主机详情页面系统镜像增加重装系统快捷操作
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/components/ListBodyCellWrap/index.vue
  src/utils/common/tableColumn.js
Labels: size/S

#4124 Automated cherry pick of #4123: feat: 主机详情页面系统镜像增加重装系统快捷操作
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/components/ListBodyCellWrap/index.vue
  src/utils/common/tableColumn.js
Labels: size/S

#4126 Automated cherry pick of #4125: feat: 主机详情页面系统镜像增加重装系统快捷操作权限控制
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#4125 feat: 主机详情页面系统镜像增加重装系统快捷操作权限控制
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#4128 Automated cherry pick of #4127: fix: k8s-cluster open sidepage error
  containers/K8S/views/cluster/components/List.vue
  containers/K8S/views/cluster/mixins/columns.js
Labels: size/S

#4129 Automated cherry pick of #4127: fix: k8s-cluster open sidepage error
  containers/K8S/views/cluster/components/List.vue
  containers/K8S/views/cluster/mixins/columns.js
Labels: size/S

#4127 fix: k8s-cluster open sidepage error
  containers/K8S/views/cluster/components/List.vue
  containers/K8S/views/cluster/mixins/columns.js
Labels: area/k8s, size/S

#4130 fix: #8797 物理机安装操作系统或转换宿主机 新建磁盘配置时，不应该只显示一个raid控制器
  containers/Compute/views/baremetal/dialogs/Create.vue
Labels: size/XS

#4132 Automated cherry pick of #4131: feat: #4171 CDN更改为项目资源
  containers/Network/views/cdn/components/List.vue
  containers/Network/views/cdn/create/index.vue
  containers/Network/views/cdn/mixins/columns.js
  containers/Network/views/cdn/mixins/singleActions.js
  src/constants/permission.js
Labels: size/M

#4133 fix: #8799 新建华为云主机，点击创建立刻展示失败
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/M

#4134 Automated cherry pick of #4133: fix: #8799 新建华为云主机，点击创建立刻展示失败
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/M

#4137 feat: #4171 CDN批量操作增加更改项目
  containers/Network/views/cdn/components/List.vue
Labels: size/S

#4138 Automated cherry pick of #4137: feat: #4171 CDN批量操作增加更改项目
  containers/Network/views/cdn/components/List.vue
Labels: size/S

#4135 feat(4151): list dropdown filter search-box is not scroll with filter items
  src/components/SearchBox/AutoCompleter.vue
Labels: size/S

#4136 Automated cherry pick of #4135: feat(4151): list dropdown filter search-box is not scroll with filter items
  src/components/SearchBox/AutoCompleter.vue
Labels: size/S

#4139 fix: qcloud support update bill
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#4141 fix: 迁移预调度跳过CPU内核检查
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#4142 Automated cherry pick of #4141: fix: 迁移预调度跳过CPU内核检查
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#4143 Automated cherry pick of #4141: fix: 迁移预调度跳过CPU内核检查
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#4144 fix: disk change owner error
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/XS

#4145 Automated cherry pick of #4144: fix: disk change owner error
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/XS

#4146 Automated cherry pick of #4144: fix: disk change owner error
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/XS

#4147 feat: #4178 新建虚拟机逻辑优化
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/S

#4148 Automated cherry pick of #4147: feat: #4178 新建虚拟机逻辑优化
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/S

#4149 Automated cherry pick of #4147: feat: #4178 新建虚拟机逻辑优化
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/S

#4150 feat: #4179 Offload网卡配置优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/views/networks/mixins/columns.js
Labels: size/L

#4151 Automated cherry pick of #4150: feat: #4179 Offload网卡配置优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/views/networks/mixins/columns.js
Labels: size/L

#4152 feat: #4177 存储桶上传文案优化
  containers/Storage/views/bucket/dialogs/ObjectsUploadFile.vue
Labels: size/XS

#4153 Automated cherry pick of #4152: feat: #4177 存储桶上传文案优化
  containers/Storage/views/bucket/dialogs/ObjectsUploadFile.vue
Labels: size/XS

#4155 feat(4117): workflow apply-internal-resource support reapply
  src/views/workflow/me-process/mixins/singleActions.js
  src/views/workflow/utils/columns.js
Labels: size/XS

#4157 feat: #4179 驱动需要更名为网卡类型
  containers/Compute/views/vminstance/dialogs/VmUpdateNetworkAttr.vue
Labels: size/XS

#4159 feat: #4182 调整同步状态按钮到批量操作前面位置
  containers/Compute/views/vminstance/components/List.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
  containers/Network/views/lb/components/List.vue
Labels: size/L

#4160 Automated cherry pick of #4159: feat: #4182 调整同步状态按钮到批量操作前面位置
  containers/Compute/views/vminstance/components/List.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
  containers/Network/views/lb/components/List.vue
Labels: size/L

#4161 feat: #4182 VNC优化优先根据电源状态判断，若电源状态是未知，则根据状态判断
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#4162 Automated cherry pick of #4161: feat: #4182 VNC优化优先根据电源状态判断，若电源状态是未知，则根据状态判断
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#4163 feat: LB同步状态批量操作时如果选择单条数据则条件限制与单条操作逻辑保持一致
  containers/Network/views/lb/components/List.vue
Labels: size/XS

#4164 Automated cherry pick of #4163: feat: LB同步状态批量操作时如果选择单条数据则条件限制与单条操作逻辑保持一致
  containers/Network/views/lb/components/List.vue
Labels: size/XS

#4165 feat(4167): project detail add admin user
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/projects/sidepage/Detail.vue
  src/locales/help-en.js
  src/locales/help-zh-CN.js
Labels: size/M

#4167 feat(4181): vminstance export add value formatter
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: area/compute, size/L

#4175 Automated cherry pick of #4173: feat: #4070 迁移宿主机选择框优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  src/components/SimpleTable/index.vue
  src/sections/DialogManager/components/ListSelect.vue
  src/sections/ListSelect/index.vue
Labels: size/L

#4173 feat: #4070 迁移宿主机选择框优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  src/components/SimpleTable/index.vue
  src/sections/DialogManager/components/ListSelect.vue
  src/sections/ListSelect/index.vue
Labels: size/L

#4174 Automated cherry pick of #4173: feat: #4070 迁移宿主机选择框优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Transfer.vue
  src/components/SimpleTable/index.vue
  src/sections/DialogManager/components/ListSelect.vue
  src/sections/ListSelect/index.vue
Labels: size/L

#4168 feat(4040): instance group attach vip support specify ip
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/instance-group/dialogs/AttachNetwork.vue
  containers/Compute/views/instance-group/sidepage/index.vue
Labels: size/M, area/compute

#4169 Automated cherry pick of #4168: feat(4040): instance group attach vip support specify ip
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/instance-group/dialogs/AttachNetwork.vue
  containers/Compute/views/instance-group/sidepage/index.vue
Labels: size/M

#4171 Automated cherry pick of #4167: feat(4181): vminstance export add value formatter
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  src/utils/common/tableColumn.js
Labels: size/L

#4170 Automated cherry pick of #4168: feat(4040): instance group attach vip support specify ip
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/instance-group/dialogs/AttachNetwork.vue
  containers/Compute/views/instance-group/sidepage/index.vue
Labels: size/M

#4177 fix: vm create calc price error for kvm local-medimu disk
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
Labels: size/M, area/compute

#4178 Automated cherry pick of #4177: fix: vm create calc price error for kvm local-medimu disk
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
Labels: size/M

#4179 Automated cherry pick of #4177: fix: vm create calc price error for kvm local-medimu disk
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
Labels: size/M

#4183 feat(4187): 硬盘选择除展示类型外，还需展示磁盘介质
  containers/Compute/constants/index.js
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/M

#4185 Automated cherry pick of #4183: feat(4187): 虚拟机新建，硬盘选择除展示类型外，还需展示磁盘介质
  containers/Compute/constants/index.js
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/M

#4180 feat(3762): dashboard add instance number card
  containers/Dashboard/extends/ResourceCount/index.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  src/components/Icon/assets/dashboard-resource-count.svg
  src/components/Icon/assets/dashboard-server-number.svg
Labels: area/dashboard, size/L

#4181 Automated cherry pick of #4180: feat(3762): dashboard add instance number card
  containers/Dashboard/extends/ResourceCount/index.vue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/zh-CN.json
  src/components/Icon/assets/dashboard-resource-count.svg
  src/components/Icon/assets/dashboard-server-number.svg
Labels: size/L

#4182 fix(8813): monitor overview export pdf empty
  containers/Monitor/components/MonitorCard/OverviewCard/index.vue
Labels: area/monitor, size/XS

#4184 Automated cherry pick of #4182: fix(8813): monitor overview export pdf empty
  containers/Monitor/components/MonitorCard/OverviewCard/index.vue
Labels: size/XS

#4187 feat(4190): monitor overview add export columns for vminstance
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  containers/Monitor/components/MonitorCard/sections/table/index.vue
Labels: area/monitor

#4204 fix(8819): vminstance adjust config system disk size error
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/XS

#4205 Automated cherry pick of #4204: fix(8819): vminstance adjust config system disk size error
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/XS

#4206 Automated cherry pick of #4204: fix(8819): vminstance adjust config system disk size error
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
Labels: size/XS

#4207 fix(8820): 删除主机的网卡时，主机状态一直在”部署中“，除非手动刷新列表
  containers/Compute/views/vminstance/dialogs/DetachNetwork.vue
Labels: size/XS

#4208 Automated cherry pick of #4207: fix(8820): 删除主机的网卡时，主机状态一直在”部署中“，除非手动刷新列表
  containers/Compute/views/vminstance/dialogs/DetachNetwork.vue
Labels: size/XS

#4209 Automated cherry pick of #4207: fix(8820): 删除主机的网卡时，主机状态一直在”部署中“，除非手动刷新列表
  containers/Compute/views/vminstance/dialogs/DetachNetwork.vue
Labels: size/XS

#4210 feat(4186): 将当前登录用户从当前项目删除时，应该提示用户可能存在删除后无法使用系统的风险
  containers/IAM/views/user/dialogs/EditRolesDialog.vue
Labels: size/XS

#4211 Automated cherry pick of #4210: feat(4186): 将当前登录用户从当前项目删除时，应该提示用户可能存在删除后无法使用系统的风险
  containers/IAM/views/user/dialogs/EditRolesDialog.vue
Labels: size/XS

#4212 fix(8817): vminstnace price total on week period
  containers/Cloudenv/views/server-price-comparator/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  src/utils/common/price.js
Labels: area/compute, size/S

#4213 Automated cherry pick of #4212: fix(8817): vminstnace price total on week period
  containers/Cloudenv/views/server-price-comparator/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  src/utils/common/price.js
Labels: size/S

#4214 Automated cherry pick of #4212: fix(8817): vminstnace price total on week period
  containers/Cloudenv/views/server-price-comparator/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  src/utils/common/price.js
Labels: size/S

#4215 Automated cherry pick of #4109: feat(4138): monitor query config save to storage
  containers/Compute/sections/monitor/AgentMonitor.vue
  containers/Compute/sections/monitor/BaseMonitor.vue
  containers/Compute/views/host/sidepage/Monitor.vue
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  containers/DB/views/rds/sidepage/Monitor.vue
  containers/DB/views/redis/sidepage/Monitor.vue
  containers/Monitor/views/monitorresource/sidepage/Monitor.vue
  containers/Network/views/lb/sidepage/Monitor.vue
  containers/Storage/views/bucket/sidepage/Monitor.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/mixins/monitorTime.js
  src/sections/CustomDate/index.vue
  src/sections/Monitor/Header.vue
  src/sections/Monitor/index.vue
Labels: size/L

#4217 Revert "Automated cherry pick of #4109: feat(4138): monitor query config save to storage"
  containers/Compute/sections/monitor/AgentMonitor.vue
  containers/Compute/sections/monitor/BaseMonitor.vue
  containers/Compute/views/host/sidepage/Monitor.vue
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  containers/DB/views/rds/sidepage/Monitor.vue
  containers/DB/views/redis/sidepage/Monitor.vue
  containers/Monitor/views/monitorresource/sidepage/Monitor.vue
  containers/Network/views/lb/sidepage/Monitor.vue
  containers/Storage/views/bucket/sidepage/Monitor.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/mixins/monitorTime.js
  src/sections/CustomDate/index.vue
  src/sections/Monitor/Header.vue
  src/sections/Monitor/index.vue
Labels: size/L

#4219 Automated cherry pick of #4218: fix: ignore tags which is not startwith user | ext
  src/sections/TagSelect/index.vue
Labels: size/XS

#4220 Automated cherry pick of #4218: fix: ignore tags which is not startwith user | ext
  src/sections/TagSelect/index.vue
Labels: size/XS

#4221 fix: conflict error
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
Labels: area/compute, size/XS

#4222 fix(8816): price comparator delete error
  containers/Cloudenv/views/server-price-comparator/components/List.vue
  containers/Cloudenv/views/server-price-comparator/create/form/mixin.js
Labels: area/cloudenv, size/XS

#4223 Automated cherry pick of #4222: fix(8816): price comparator delete error
  containers/Cloudenv/views/server-price-comparator/components/List.vue
  containers/Cloudenv/views/server-price-comparator/create/form/mixin.js
Labels: size/XS

#4224 Automated cherry pick of #4222: fix(8816): price comparator delete error
  containers/Cloudenv/views/server-price-comparator/components/List.vue
  containers/Cloudenv/views/server-price-comparator/create/form/mixin.js
Labels: size/XS

#4225 feat(4190): vminstance add elastic ip column
  containers/Cloudenv/views/scheduledtask/mixins/resourceProps.js
  containers/Compute/views/gpu/sidepage/Servers.vue
  containers/Compute/views/instance-group/sidepage/VMInstanceListForInstanceGroup.vue
  containers/Compute/views/scaling-group/sidepage/ServerList.vue
  containers/Compute/views/secgroup/mixins/serverListPropsForSetServer.js
  containers/Compute/views/secgroup/mixins/serverProps.js
  containers/Compute/views/server-recovery/mixins/columns.js
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
  containers/Compute/views/vminstance/dialogs/AttachUsb.vue
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/L

#4226 Automated cherry pick of #4225: feat(4190): vminstance add elastic ip column
  containers/Cloudenv/views/scheduledtask/mixins/resourceProps.js
  containers/Compute/views/gpu/sidepage/Servers.vue
  containers/Compute/views/instance-group/sidepage/VMInstanceListForInstanceGroup.vue
  containers/Compute/views/scaling-group/sidepage/ServerList.vue
  containers/Compute/views/secgroup/mixins/serverListPropsForSetServer.js
  containers/Compute/views/secgroup/mixins/serverProps.js
  containers/Compute/views/server-recovery/mixins/columns.js
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/dialogs/AttachGpu.vue
  containers/Compute/views/vminstance/dialogs/AttachUsb.vue
  containers/Compute/views/vminstance/mixins/columns.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/L

#4228 Automated cherry pick of #4227: feat: list data export accuracy
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#4229 Automated cherry pick of #4227: feat: list data export accuracy
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#4230 feat(4186): 将当前登录用户从当前项目删除时，应该提示用户可能存在删除后无法使用系统的风险
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/user/dialogs/ProjectLeave.vue
Labels: size/XS

#4231 Automated cherry pick of #4230: feat(4186): 将当前登录用户从当前项目删除时，应该提示用户可能存在删除后无法使用系统的风险
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/user/dialogs/ProjectLeave.vue
Labels: size/XS
