Repository yunionio/dashboard, pull requests merged in 2023-07, with the labels that each got.

#4865 feat(4415): 云上项目状态优化
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/externalproject/components/List.vue
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/S

#4866 Automated cherry pick of #4865: feat(4415): 云上项目状态优化
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/externalproject/components/List.vue
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
Labels: size/S

#4863 feat: base-select component accuracy
  src/components/BaseSelect/index.vue
Labels: size/XS

#4864 Automated cherry pick of #4863: feat: base-select component accuracy
  src/components/BaseSelect/index.vue
Labels: size/XS

#4867 fix(9150): 虚拟机导出系统列需与列表查看展示一致
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#4868 Automated cherry pick of #4867: fix(9150): 虚拟机导出系统列需与列表查看展示一致
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#4869 Automated cherry pick of #4867: fix(9150): 虚拟机导出系统列需与列表查看展示一致
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#4870 fix(9145): 同步策略优化
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
Labels: size/S

#4871 Automated cherry pick of #4870: fix(9145): 同步策略优化
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
Labels: size/S

#4872 fix(9150): 虚拟机导出系统列增加版本信息
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/S

#4873 Automated cherry pick of #4872: fix(9150): 虚拟机导出系统列增加版本信息
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/S

#4874 Automated cherry pick of #4872: fix(9150): 虚拟机导出系统列增加版本信息
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/S

#4875 feat: add brand expand column and filter
  src/constants/permission.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/utils/common/tableColumn.js
  src/utils/common/tableFilter.js
Labels: size/M

#4876 fix(9156): add local export params for export all datas
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#4880 feat(4358): pve 支持新建
  containers/Compute/sections/ServerNetwork/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/Private.vue
Labels: size/S

#4877 fix: Login prompt timer setting upper limit time
  src/mixins/logout.js
Labels: size/XS

#4878 Automated cherry pick of #4877: fix: Login prompt timer setting upper limit time
  src/mixins/logout.js
Labels: size/XS

#4879 Automated cherry pick of #4877: fix: Login prompt timer setting upper limit time
  src/mixins/logout.js
Labels: size/XS

#4882 feat: brand column expand
  src/utils/common/tableColumn.js
  src/utils/common/tableFilter.js
Labels: size/XS

#4883 feat(4391): 主机列表支持隐藏列表项
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  src/permission.js
  src/utils/common/tableColumn.js
Labels: size/L

#4884 Automated cherry pick of #4883: feat(4391): 主机列表支持隐藏列表项
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/mixins/columns.js
  src/permission.js
  src/utils/common/tableColumn.js
Labels: size/L

#4885 fix(9162): 选择vmware平台镜像，磁盘支持容量变更
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/S

#4886 Automated cherry pick of #4885: fix(9162): 选择vmware平台镜像，磁盘支持容量变更
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/S

#4887 fix(9162): 阿里云磁盘类型增加及VMware磁盘容量范围变更
  src/constants/compute.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/M

#4889 fix(9162): 阿里云磁盘容量范围变更
  src/constants/compute.js
Labels: size/S

#4893 feat(4391): 硬盘快照列表支持隐藏列表项
  containers/Compute/views/snapshot/mixins/columns.js
  containers/Compute/views/snapshot/utils/columns.js
Labels: size/M

#4895 feat(4391): EIP列表支持隐藏列表项
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/utils/columns.js
Labels: size/M

#4896 Automated cherry pick of #4895: feat(4391): EIP列表支持隐藏列表项
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/utils/columns.js
Labels: size/M

#4897 feat(4391): Bucket列表支持隐藏列表项
  containers/Storage/views/bucket/mixins/columns.js
Labels: size/M

#4898 Automated cherry pick of #4897: feat(4391): Bucket列表支持隐藏列表项
  containers/Storage/views/bucket/mixins/columns.js
Labels: size/M

#4899 feat(4391): RDS、Redis、MongoDB列表支持隐藏列表项
  containers/DB/views/mongodb/mixins/columns.js
  containers/DB/views/rds/mixins/columns.js
  containers/DB/views/redis/mixins/columns.js
Labels: size/L

#4901 feat(4391): 负载均衡列表支持隐藏列表项
  containers/Network/views/lb/mixins/columns.js
Labels: size/M

#4903 feat(4391): VPC列表支持隐藏列表项
  containers/Network/views/vpc/mixins/columns.js
Labels: size/M

#4904 Automated cherry pick of #4903: feat(4391): VPC列表支持隐藏列表项
  containers/Network/views/vpc/mixins/columns.js
Labels: size/M

#4905 fix(9167): ldp hide alert text
  containers/IAM/views/idp/components/List.vue
Labels: size/XS

#4906 Automated cherry pick of #4905: fix(9167): ldp hide alert text
  containers/IAM/views/idp/components/List.vue
Labels: size/XS

#4907 Automated cherry pick of #4905: fix(9167): ldp hide alert text
  containers/IAM/views/idp/components/List.vue
Labels: size/XS

#4908 fix(9171): 产品激活申请license隐藏线上申请路径
  src/sections/DialogManager/components/UpdateLicense.vue
Labels: size/XS

#4909 Automated cherry pick of #4908: fix(9171): 产品激活申请license隐藏线上申请路径
  src/sections/DialogManager/components/UpdateLicense.vue
Labels: size/XS

#4910 Automated cherry pick of #4908: fix(9171): 产品激活申请license隐藏线上申请路径
  src/sections/DialogManager/components/UpdateLicense.vue
Labels: size/XS

#4911 feat: 消息订阅增加消息名称翻译
  containers/IAM/constants/index.js
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/S

#4913 feat: notify topic i18n
  containers/IAM/constants/index.js
Labels: size/XS

#4914 Automated cherry pick of #4913: feat: notify topic i18n
  containers/IAM/constants/index.js
Labels: size/XS

#4915 feat(4352): 项目和域选择控件应该记忆用户的选择
  src/sections/DomainProject/index.vue
  src/store/modules/storage.js
Labels: size/M

#4916 Automated cherry pick of #4915: feat(4352): 项目和域选择控件应该记忆用户的选择
  src/sections/DomainProject/index.vue
  src/store/modules/storage.js
Labels: size/M

#4917 feat(4403): 在线修改密码需先探测QGA状态
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/ResetPassword.vue
Labels: size/M

#4920 feat(4435): workflow list add changeResourceInfo and deleteResourceInfo
  src/views/workflow/utils/columns.js
Labels: size/S

#4919 fix(9186): account set project mapping add project params
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
Labels: area/cloudenv, size/XS

#4922 feat(4409): 云账号同步支持屏蔽资源类型
  containers/Cloudenv/constants/index.js
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/BlockedResources.vue
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/BingoCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/H3C.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCS.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSOP.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/InCloudSphere.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Nutanix.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Proxmox.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/RemoteFile.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/S3CephXsky.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
  containers/Cloudenv/views/cloudaccount/utils/columns.js
Labels: size/L

#4923 Automated cherry pick of #4922: feat(4409): 云账号同步支持屏蔽资源类型
  containers/Cloudenv/constants/index.js
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/BlockedResources.vue
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/BingoCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/H3C.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCS.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSOP.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/InCloudSphere.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Nutanix.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Proxmox.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/RemoteFile.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/S3CephXsky.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
  containers/Cloudenv/views/cloudaccount/utils/columns.js
Labels: size/L

#4924 fix: remove console
  containers/Cloudenv/views/cloudaccount/utils/columns.js
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#4926 fix: openresource instance id empty
  src/views/workflow/utils/columns.js
Labels: size/XS

#4927 Automated cherry pick of #4926: fix: openresource instance id empty
  src/views/workflow/utils/columns.js
Labels: size/XS

#4928 feat(4433): 热迁移取消”快速收敛“选项，默认开启快速收敛
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/S

#4931 fix: 修复扩展列导出最后一条数据可能丢失折叠行数据问题
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/S

#4932 Automated cherry pick of #4931: fix: 修复扩展列导出最后一条数据可能丢失折叠行数据问题
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/S

#4930 feat(4434): 如果虚拟机所在宿主机为禁用且离线状态，则虚拟机迁移默认启用 rescue-mode 迁移
  containers/Compute/views/vminstance/dialogs/Transfer.vue
Labels: size/XS

#4934 fix(9181): 新建容器集群，最下方的按钮无法选择
  containers/K8S/views/cluster/create/index.vue
Labels: size/L

#4935 Automated cherry pick of #4934: fix(9181): 新建容器集群，最下方的按钮无法选择
  containers/K8S/views/cluster/create/index.vue
Labels: size/L

#4936 feat(4439): 容器集群导入支持指定域
  containers/K8S/views/cluster/import/index.vue
Labels: size/M

#4938 Automated cherry pick of #4936: feat(4439): 容器集群导入支持指定域
  containers/K8S/views/cluster/import/index.vue
Labels: size/M

#4940 fix(9191): workflow accuracy
  src/sections/Navbar/components/WorkOrderPopover.vue
  src/views/workflow-technical-support/all-process/sidepage/Detail.vue
  src/views/workflow-technical-support/approval-start/sidepage/Detail.vue
  src/views/workflow-technical-support/approved-done/mixins/columns.js
  src/views/workflow-technical-support/approved-done/sidepage/Detail.vue
  src/views/workflow-technical-support/me-process/sidepage/Detail.vue
  src/views/workflow-technical-support/third-process/sidepage/Detail.vue
  src/views/workflow/all-process/sidepage/Detail.vue
  src/views/workflow/approval-start/mixins/columns.js
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/approved-done/mixins/columns.js
  src/views/workflow/approved-done/sidepage/Detail.vue
  src/views/workflow/me-partake/mixins/columns.js
  src/views/workflow/me-partake/sidepage/Detail.vue
  src/views/workflow/me-process/sidepage/Detail.vue
Labels: size/M

#4941 Automated cherry pick of #4940: fix(9191): workflow accuracy
  src/sections/Navbar/components/WorkOrderPopover.vue
  src/views/workflow-technical-support/all-process/sidepage/Detail.vue
  src/views/workflow-technical-support/approval-start/sidepage/Detail.vue
  src/views/workflow-technical-support/approved-done/mixins/columns.js
  src/views/workflow-technical-support/approved-done/sidepage/Detail.vue
  src/views/workflow-technical-support/me-process/sidepage/Detail.vue
  src/views/workflow-technical-support/third-process/sidepage/Detail.vue
  src/views/workflow/all-process/sidepage/Detail.vue
  src/views/workflow/approval-start/mixins/columns.js
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/approved-done/mixins/columns.js
  src/views/workflow/approved-done/sidepage/Detail.vue
  src/views/workflow/me-partake/mixins/columns.js
  src/views/workflow/me-partake/sidepage/Detail.vue
  src/views/workflow/me-process/sidepage/Detail.vue
Labels: size/M

#4942 feat: dictionary add rateset
  src/constants/index.js
Labels: size/XS

#4939 fix: set project mapping add ignoreBlockResources check
  containers/Cloudenv/views/cloudaccount/dialogs/SetProjectmapping.vue
Labels: area/cloudenv, size/S

#4943 feat(4436): 新建阿里云EIP支持路线类型
  containers/Compute/sections/EipConfig/index.vue
  containers/Network/views/eip/create/index.vue
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/sidepage/Detail.vue
  containers/Network/views/eip/utils/columns.js
  src/constants/network.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#4944 Automated cherry pick of #4943: feat(4436): 新建阿里云EIP支持路线类型
  containers/Compute/sections/EipConfig/index.vue
  containers/Network/views/eip/create/index.vue
  containers/Network/views/eip/mixins/columns.js
  containers/Network/views/eip/sidepage/Detail.vue
  containers/Network/views/eip/utils/columns.js
  src/constants/network.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/L

#4945 feat(4428): 机器人增加zoom机器人
  containers/IAM/views/robots/dialogs/Create.vue
Labels: size/M

#4946 fix(9193): 云账号屏蔽资源失败
  containers/Cloudenv/constants/index.js
Labels: size/S

#4947 Automated cherry pick of #4946: fix(9193): 云账号屏蔽资源失败
  containers/Cloudenv/constants/index.js
Labels: size/S

#4948 feat: vmware and private cacheimages interface add project_domain params
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
Labels: size/XS

#4950 fix(9180): 磁盘使用率图表优化
  src/sections/Charts/Lines.vue
Labels: size/XS

#4951 Automated cherry pick of #4950: fix(9180): 磁盘使用率图表优化
  src/sections/Charts/Lines.vue
Labels: size/XS

#4953 fix(9200): 新建vmware，镜像过滤请求发送俩次，且过滤条件不一样
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#4954 Automated cherry pick of #4953: fix(9200): 新建vmware，镜像过滤请求发送俩次，且过滤条件不一样
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#4958 Automated cherry pick of #4957: fix(monitor): skip_check_series when dimentionId is tenant_id or domain_id
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/XS

#4959 feat: add org tag
  src/constants/permission.js
  src/sections/TagTableColumn/index.vue
  src/utils/common/tableColumn.js
  src/utils/common/tag.js
Labels: size/M

#4960 fix(8852): 新建虚拟机切换私有云账号时因为页面缓存导致磁盘价格报错
  containers/Compute/views/vminstance/create/components/BottomBar.vue
Labels: size/XS

#4961 Automated cherry pick of #4960: fix(8852): 新建虚拟机切换私有云账号时因为页面缓存导致磁盘价格报错
  containers/Compute/views/vminstance/create/components/BottomBar.vue
Labels: size/XS

#4962 feat: add organization dictionary i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#4965 feat(4403): 仅开机状态的机器支持QGA状态探测
  containers/Compute/views/vminstance/dialogs/ResetPassword.vue
Labels: size/S

#4966 Automated cherry pick of #4965: feat(4403): 仅开机状态的机器支持QGA状态探测
  containers/Compute/views/vminstance/dialogs/ResetPassword.vue
Labels: size/S

#4963 feat(4443): ssh show login error message
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/constants/actions.js
  src/sections/DialogManager/components/SshAuth.vue
Labels: area/compute, size/S

#4964 Automated cherry pick of #4963: feat(4443): ssh show login error message
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/constants/actions.js
  src/sections/DialogManager/components/SshAuth.vue
Labels: size/S

#4967 feat(4436): 优化：新建阿里云EIP支持路线类型
  containers/Network/views/eip/create/index.vue
  containers/Network/views/eip/utils/columns.js
Labels: size/S

#4969 feat(4436): 调整区域列与项目列对齐
  src/sections/AreaSelects/index.js
Labels: size/XS

#4971 feat(4451): Daemon虚拟机文案修改为自动启动，同时增加备注
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Update.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/S

#4972 Automated cherry pick of #4971: feat(4451): Daemon虚拟机文案修改为自动启动，同时增加备注
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Update.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/S

#4973 Automated cherry pick of #4971: feat(4451): Daemon虚拟机文案修改为自动启动，同时增加备注
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Update.vue
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/S

#4974 fix: support aws redis create
  containers/DB/sections/ItemArea.vue
Labels: size/XS

#4975 feat(4457): 更新vmware账号信息时允许设置host和port
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/dialogs/Update.vue
Labels: size/S

#4976 Automated cherry pick of #4975: feat(4457): 更新vmware账号信息时允许设置host和port
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/dialogs/Update.vue
Labels: size/S

#4979 feat(4457): update parse access_url host to hostname
  containers/Cloudenv/views/cloudaccount/dialogs/Update.vue
Labels: size/XS

#4980 Automated cherry pick of #4979: feat(4457): update parse access_url host to hostname
  containers/Cloudenv/views/cloudaccount/dialogs/Update.vue
Labels: size/XS

#4981 fix(9215): vpc数量磁贴统计错误
  containers/Dashboard/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#4982 Automated cherry pick of #4981: fix(9215): vpc数量磁贴统计错误
  containers/Dashboard/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#4983 fix(9191): workflow apply accuracy
  src/sections/Navbar/components/WorkOrderPopover.vue
Labels: size/XS

#4989 feat(4451): Daemon虚拟机详情页增加备注信息
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/components/Detail/index.js
Labels: size/XS

#4990 Automated cherry pick of #4989: feat(4451): Daemon虚拟机详情页增加备注信息
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/components/Detail/index.js
Labels: size/XS

#4984 Automated cherry pick of #4983: fix(9191): workflow apply accuracy
  src/sections/Navbar/components/WorkOrderPopover.vue
Labels: size/XS

#4985 fix(9191): workflow apply accuracy
  src/sections/Navbar/components/WorkOrderPopover.vue
Labels: size/XS

#4986 fix(9120): image select error
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#4987 Automated cherry pick of #4986: fix(9120): image select error
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#4988 Automated cherry pick of #4986: fix(9120): image select error
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#4996 fix(9221): rds和redis新建出现了包周期分摊类型
  src/components/ClearingRadios/index.js
Labels: size/S

#4997 Automated cherry pick of #4996: fix(9221): rds和redis新建出现了包周期分摊类型
  src/components/ClearingRadios/index.js
Labels: size/S

#4991 fix(9153): monitor dashboard export accuracy
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
Labels: size/M

#4992 Automated cherry pick of #4991: fix(9153): monitor dashboard export accuracy
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
Labels: size/M

#4995 Automated cherry pick of #4994: fix(9217): update locales
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#4998 fix(9225): all platform support delete billing data when delete cloud account
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: area/cloudenv, size/XS

#4999 Automated cherry pick of #4998: fix(9225): all platform support delete billing data when delete cloud account
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#5000 feat(4461): 镜像最小磁盘要求增加说明
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/dialogs/EditAttributes.vue
Labels: size/XS

#5001 Automated cherry pick of #5000: feat(4461): 镜像最小磁盘要求增加说明
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/dialogs/EditAttributes.vue
Labels: size/XS

#5002 Automated cherry pick of #5000: feat(4461): 镜像最小磁盘要求增加说明
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/dialogs/EditAttributes.vue
Labels: size/XS

#5005 Automated cherry pick of #5004: fix(9207): workflow filter
  src/views/workflow/components/ApplyInternalResource.vue
  src/views/workflow/utils/columns.js
  src/views/workflow/utils/index.js
Labels: size/L

#5006 fix(9228): 云订阅过滤项目失效
  containers/Cloudenv/views/cloudprovider/components/List.vue
Labels: size/XS

#5007 Automated cherry pick of #5006: fix(9228): 云订阅过滤项目失效
  containers/Cloudenv/views/cloudprovider/components/List.vue
Labels: size/XS

#5011 feat: remove workflow
  src/router/routes.js
  src/views/no-project/Status.vue
  src/views/workflow-technical-support/all-process/sidepage/Detail.vue
  src/views/workflow-technical-support/approval-start/sidepage/Detail.vue
  src/views/workflow-technical-support/approved-done/mixins/columns.js
  src/views/workflow-technical-support/approved-done/sidepage/Detail.vue
  src/views/workflow-technical-support/me-process/sidepage/Detail.vue
  src/views/workflow-technical-support/third-process/sidepage/Detail.vue
  src/views/workflow/all-process/sidepage/Detail.vue
  src/views/workflow/approval-start/mixins/columns.js
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/approved-done/mixins/columns.js
  src/views/workflow/approved-done/sidepage/Detail.vue
  src/views/workflow/components/ApplyInternalResource.vue
  src/views/workflow/me-partake/mixins/columns.js
  src/views/workflow/me-partake/sidepage/Detail.vue
  src/views/workflow/me-process/sidepage/Detail.vue
  src/views/workflow/utils/columns.js
  src/views/workflow/utils/index.js
Labels: size/XXL

#5012 Automated cherry pick of #5011: feat: remove workflow
  src/router/routes.js
  src/views/no-project/Status.vue
  src/views/workflow-technical-support/all-process/sidepage/Detail.vue
  src/views/workflow-technical-support/approval-start/sidepage/Detail.vue
  src/views/workflow-technical-support/approved-done/mixins/columns.js
  src/views/workflow-technical-support/approved-done/sidepage/Detail.vue
  src/views/workflow-technical-support/me-process/sidepage/Detail.vue
  src/views/workflow-technical-support/third-process/sidepage/Detail.vue
  src/views/workflow/all-process/sidepage/Detail.vue
  src/views/workflow/approval-start/mixins/columns.js
  src/views/workflow/approval-start/sidepage/Detail.vue
  src/views/workflow/approved-done/mixins/columns.js
  src/views/workflow/approved-done/sidepage/Detail.vue
  src/views/workflow/components/ApplyInternalResource.vue
  src/views/workflow/me-partake/mixins/columns.js
  src/views/workflow/me-partake/sidepage/Detail.vue
  src/views/workflow/me-process/sidepage/Detail.vue
  src/views/workflow/utils/columns.js
  src/views/workflow/utils/index.js
Labels: size/XXL

#5013 feat(4459): 支持将多个镜像组合成一个主机镜像
  containers/Compute/views/host-image/mixins/columns.js
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/dialogs/MergeMirror.vue
  containers/Compute/views/image/locales/en.json
  containers/Compute/views/image/locales/zh-CN.json
  containers/Compute/views/image/mixins/columns.js
Labels: size/L

#5014 Automated cherry pick of #5013: feat(4459): 支持将多个镜像组合成一个主机镜像
  containers/Compute/views/host-image/mixins/columns.js
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/dialogs/MergeMirror.vue
  containers/Compute/views/image/locales/en.json
  containers/Compute/views/image/locales/zh-CN.json
  containers/Compute/views/image/mixins/columns.js
Labels: size/L

#5015 Automated cherry pick of #5013: feat(4459): 支持将多个镜像组合成一个主机镜像
  containers/Compute/views/host-image/mixins/columns.js
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/dialogs/MergeMirror.vue
  containers/Compute/views/image/locales/en.json
  containers/Compute/views/image/locales/zh-CN.json
  containers/Compute/views/image/mixins/columns.js
Labels: size/L

#5016 feat: add cloudshell switch
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  src/sections/Navbar/index.vue
Labels: size/S

#5018 feat(3968): 增加关机不收费的标识字段
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/M

#5019 feat(4405): 监控查询及告警磁盘文案优化
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: size/S

#5020 Automated cherry pick of #5019: feat(4405): 监控查询及告警磁盘文案优化
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: size/S

#5021 Automated cherry pick of #5019: feat(4405): 监控查询及告警磁盘文案优化
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
Labels: size/S

#5024 feat(4382): 云平台图标优化
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/index.vue
  src/assets/images/providers/h3c.svg
  src/components/Icon/assets/h3c.svg
  src/components/Icon/assets/hcs.svg
  src/components/Icon/assets/hcso.svg
Labels: size/S

#5022 fix(9237): change project support remote filter
  src/sections/DialogManager/components/ChangeProject.vue
Labels: size/XS

#5023 Automated cherry pick of #5022: fix(9237): change project support remote filter
  src/sections/DialogManager/components/ChangeProject.vue
Labels: size/XS

#5025 fix: 项目视图下选择操作系统报错
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#5026 Automated cherry pick of #5025: fix: 项目视图下选择操作系统报错
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#5027 fix: 域信息从选择的当前域或项目获取
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#5028 Automated cherry pick of #5027: fix: 域信息从选择的当前域或项目获取
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#5030 Automated cherry pick of #5029: fix: 切换镜像磁盘大小范围错误
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/M
