Repository yunionio/dashboard, pull requests merged in 2024-06, with the labels that each got.

#6622 fix: remove qcloud useless app id
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/dialogs/Update.vue
Labels: size/S

#6623 Automated cherry pick of #6622: fix: remove qcloud useless app id
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/dialogs/Update.vue
Labels: size/S

#6624 feat(v3.11/4903): extend enabled table column export info
  src/utils/common/tableColumn.js
Labels: size/XS

#6625 Automated cherry pick of #6624: feat(v3.11/4903): extend enabled table column export info
  src/utils/common/tableColumn.js
Labels: size/XS

#6626 Automated cherry pick of #6624: feat(v3.11/4903): extend enabled table column export info
  src/utils/common/tableColumn.js
Labels: size/XS

#6630 fix(container): wrong translated text
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#6627 fix(v3.11/9903): custom list config remove ext tags
  src/sections/DialogManager/components/CustomList.vue
Labels: size/XS

#6628 Automated cherry pick of #6627: fix(v3.11/9903): custom list config remove ext tags
  src/sections/DialogManager/components/CustomList.vue
Labels: size/XS

#6629 Automated cherry pick of #6627: fix(v3.11/9903): custom list config remove ext tags
  src/sections/DialogManager/components/CustomList.vue
Labels: size/XS

#6631 feat(v3.11/4903): user export list add project info
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/projects/dialogs/Add.vue
  containers/IAM/views/user/components/List.vue
  containers/IAM/views/user/dialogs/GroupJoin.vue
  containers/IAM/views/user/dialogs/ProjectJoin.vue
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/waf/sidepage/Detail.vue
  src/components/BaseSelect/index.vue
Labels: size/L

#6632 Automated cherry pick of #6631: feat(v3.11/4903): user export list add project info
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/projects/dialogs/Add.vue
  containers/IAM/views/user/components/List.vue
  containers/IAM/views/user/dialogs/GroupJoin.vue
  containers/IAM/views/user/dialogs/ProjectJoin.vue
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/waf/sidepage/Detail.vue
  src/components/BaseSelect/index.vue
Labels: size/L

#6633 Automated cherry pick of #6631: feat(v3.11/4903): user export list add project info
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/projects/dialogs/Add.vue
  containers/IAM/views/user/components/List.vue
  containers/IAM/views/user/dialogs/GroupJoin.vue
  containers/IAM/views/user/dialogs/ProjectJoin.vue
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/waf/sidepage/Detail.vue
  src/components/BaseSelect/index.vue
Labels: size/L

#6634 feat(v3.11/4916): user add project refresh self
  containers/IAM/views/projects/dialogs/Add.vue
  containers/IAM/views/user/components/List.vue
  containers/IAM/views/user/dialogs/GroupJoin.vue
  containers/IAM/views/user/dialogs/ProjectJoin.vue
  containers/Network/views/waf/sidepage/Detail.vue
Labels: size/M

#6635 Automated cherry pick of #6634: feat(v3.11/4916): user add project refresh self
  containers/IAM/views/projects/dialogs/Add.vue
  containers/IAM/views/user/components/List.vue
  containers/IAM/views/user/dialogs/GroupJoin.vue
  containers/IAM/views/user/dialogs/ProjectJoin.vue
  containers/Network/views/waf/sidepage/Detail.vue
Labels: size/M

#6636 Automated cherry pick of #6634: feat(v3.11/4916): user add project refresh self
  containers/IAM/views/projects/dialogs/Add.vue
  containers/IAM/views/user/components/List.vue
  containers/IAM/views/user/dialogs/GroupJoin.vue
  containers/IAM/views/user/dialogs/ProjectJoin.vue
  containers/Network/views/waf/sidepage/Detail.vue
Labels: size/M

#6637 feat: change license to AGPL
  LICENSE
Labels: size/XL

#6638 Automated cherry pick of #6637: feat: change license to AGPL
  LICENSE
Labels: size/XL

#6639 Automated cherry pick of #6637: feat: change license to AGPL
  LICENSE
Labels: size/XL

#6640 Automated cherry pick of #6637: feat: change license to AGPL
  LICENSE
Labels: size/XL

#6641 Automated cherry pick of #6637: feat: change license to AGPL
  LICENSE
Labels: size/XL

#6642 Automated cherry pick of #6637: feat: change license to AGPL
  LICENSE
Labels: size/XL

#6643 Automated cherry pick of #6637: feat: change license to AGPL
  LICENSE
Labels: size/XL

#6644 Automated cherry pick of #6637: feat: change license to AGPL
  LICENSE
Labels: size/XL

#6645 Automated cherry pick of #6637: feat: change license to AGPL
  LICENSE
Labels: size/XL

#6647 fix(v3.10/9933): hasSetupKey method extension
  src/utils/auth.js
Labels: size/S

#6648 Automated cherry pick of #6647: fix(v3.10/9933): hasSetupKey method extension
  src/utils/auth.js
Labels: size/S

#6649 Automated cherry pick of #6647: fix(v3.10/9933): hasSetupKey method extension
  src/utils/auth.js
Labels: size/S

#6650 Automated cherry pick of #6647: fix(v3.10/9933): hasSetupKey method extension
  src/utils/auth.js
Labels: size/S

#6651 feat(3.11/4925): 虚拟机修改属性增加禁用 USB 键盘的开关
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/M

#6652 Automated cherry pick of #6651: feat(3.11/4925): 虚拟机修改属性增加禁用 USB 键盘的开关
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/M

#6653 Automated cherry pick of #6651: feat(3.11/4925): 虚拟机修改属性增加禁用 USB 键盘的开关
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/M

#6654 feat(3.11/4925): 增加USB键盘i18n
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/S

#6655 Automated cherry pick of #6654: feat(3.11/4925): 增加USB键盘i18n
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/S

#6656 Automated cherry pick of #6654: feat(3.11/4925): 增加USB键盘i18n
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/Update.vue
Labels: size/S

#6657 feat(3.10/4927): vpc带宽调整优化
  containers/Compute/views/vminstance/dialogs/ChangeBandwidth.vue
Labels: size/XS

#6658 Automated cherry pick of #6657: feat(3.10/4927): vpc带宽调整优化
  containers/Compute/views/vminstance/dialogs/ChangeBandwidth.vue
Labels: size/XS

#6660 Automated cherry pick of #6657: feat(3.10/4927): vpc带宽调整优化
  containers/Compute/views/vminstance/dialogs/ChangeBandwidth.vue
Labels: size/XS

#6659 Automated cherry pick of #6657: feat(3.10/4927): vpc带宽调整优化
  containers/Compute/views/vminstance/dialogs/ChangeBandwidth.vue
Labels: size/XS

#6661 feat(v3.9/4917): mongodb status add processing i18n
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#6665 Automated cherry pick of #6661: feat(v3.9/4917): mongodb status add processing i18n
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/XS

#6664 Automated cherry pick of #6661: feat(v3.9/4917): mongodb status add processing i18n
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#6663 Automated cherry pick of #6661: feat(v3.9/4917): mongodb status add processing i18n
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#6666 fix(3.10/9924): 新建告警策略，通知类型为角色或告警机器人时，角色或告警机器人选择框为必填项
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
Labels: size/S

#6667 Automated cherry pick of #6666: fix(3.10/9924): 新建告警策略，通知类型为角色或告警机器人时，角色或告警机器人选择框为必填项
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
Labels: size/S

#6669 Automated cherry pick of #6666: fix(3.10/9924): 新建告警策略，通知类型为角色或告警机器人时，角色或告警机器人选择框为必填项
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
Labels: size/S

#6668 Automated cherry pick of #6666: fix(3.10/9924): 新建告警策略，通知类型为角色或告警机器人时，角色或告警机器人选择框为必填项
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
Labels: size/S

#6670 fix(3.10/9928): 虚拟机--告警详情页，新建报警提示信息不一致
  containers/Compute/views/node-alert/components/Form.vue
Labels: size/XS

#6671 Automated cherry pick of #6670: fix(3.10/9928): 虚拟机--告警详情页，新建报警提示信息不一致
  containers/Compute/views/node-alert/components/Form.vue
Labels: size/XS

#6672 Automated cherry pick of #6670: fix(3.10/9928): 虚拟机--告警详情页，新建报警提示信息不一致
  containers/Compute/views/node-alert/components/Form.vue
Labels: size/XS

#6673 Automated cherry pick of #6670: fix(3.10/9928): 虚拟机--告警详情页，新建报警提示信息不一致
  containers/Compute/views/node-alert/components/Form.vue
Labels: size/XS

#6675 fix(3.11/9657): 用户绑定组织架构后，点击虚拟机scriptapplyrecords接口报错
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#6677 Automated cherry pick of #6675: fix(3.11/9657): 用户绑定组织架构后，点击虚拟机scriptapplyrecords接口报错
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#6678 feat(v3.12/4824): support does not equal filtering
  src/components/PageList/index.vue
  src/components/SearchBox/AutoCompleter.vue
  src/components/SearchBox/Tag.vue
  src/components/SearchBox/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/common/tableFilter.js
  src/utils/list.js
Labels: size/L

#6679 Automated cherry pick of #6678: feat(v3.12/4824): support does not equal filtering
  src/components/PageList/index.vue
  src/components/SearchBox/AutoCompleter.vue
  src/components/SearchBox/Tag.vue
  src/components/SearchBox/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/common/tableFilter.js
  src/utils/list.js
Labels: size/L

#6680 fix(v3.12): vm adjust config show disk info empty
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#6681 Automated cherry pick of #6680: fix(v3.12): vm adjust config show disk info empty
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#6684 fix(v3.11/9921): scheduled task set default time
  containers/Cloudenv/sections/ScheduledTaskTime/index.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
  containers/Compute/views/scaling-group/dialogs/RuleListCreate.vue
Labels: size/XS

#6686 Automated cherry pick of #6684: fix(v3.11/9921): scheduled task set default time
  containers/Cloudenv/sections/ScheduledTaskTime/index.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
  containers/Compute/views/scaling-group/dialogs/RuleListCreate.vue
Labels: size/XS

#6687 Automated cherry pick of #6684: fix(v3.11/9921): scheduled task set default time
  containers/Cloudenv/sections/ScheduledTaskTime/index.vue
  containers/Cloudenv/views/scheduledtask/create/index.vue
  containers/Compute/views/scaling-group/dialogs/RuleListCreate.vue
Labels: size/XS

#6682 feat(3.11/4928): 转换宿主机时候添加磁盘的挂载路径只能是 /opt/cloud/workspace 开头的目录
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/dialogs/DiskOptionsUpdate.vue
  containers/Compute/views/physicalmachine/dialogs/Convert.vue
Labels: size/M

#6683 Automated cherry pick of #6682: feat(3.11/4928): 转换宿主机时候添加磁盘的挂载路径只能是 /opt/cloud/workspace 开头的目录
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/dialogs/DiskOptionsUpdate.vue
  containers/Compute/views/physicalmachine/dialogs/Convert.vue
Labels: size/M

#6685 Automated cherry pick of #6682: feat(3.11/4928): 转换宿主机时候添加磁盘的挂载路径只能是 /opt/cloud/workspace 开头的目录
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/dialogs/DiskOptionsUpdate.vue
  containers/Compute/views/physicalmachine/dialogs/Convert.vue
Labels: size/M

#6689 fix(v3.10/9927): Add mobile phone number verification to SMS notification channels
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/notifyconfig/create/index.vue
  containers/IAM/views/notifyconfig/dialogs/TestMobile.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/L

#6690 Automated cherry pick of #6689: fix(v3.10/9927): Add mobile phone number verification to SMS notification channels
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/notifyconfig/create/index.vue
  containers/IAM/views/notifyconfig/dialogs/TestMobile.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/L

#6691 Automated cherry pick of #6689: fix(v3.10/9927): Add mobile phone number verification to SMS notification channels
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/notifyconfig/create/index.vue
  containers/IAM/views/notifyconfig/dialogs/TestMobile.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/L

#6692 Automated cherry pick of #6689: fix(v3.10/9927): Add mobile phone number verification to SMS notification channels
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/notifyconfig/create/index.vue
  containers/IAM/views/notifyconfig/dialogs/TestMobile.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/L

#6693 fix(v3.11/9938): Creating a bucket object list and using an ID to cre…
  containers/Storage/views/bucket/sidepage/Objects.vue
Labels: size/XS

#6694 Automated cherry pick of #6693: fix(v3.11/9938): Creating a bucket object list and using an ID to create resources
  containers/Storage/views/bucket/sidepage/Objects.vue
Labels: size/XS

#6695 Automated cherry pick of #6693: fix(v3.11/9938): Creating a bucket object list and using an ID to create resources
  containers/Storage/views/bucket/sidepage/Objects.vue
Labels: size/XS

#6698 fix: move port mapping to server-network-list
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/networks/mixins/columns.js
Labels: size/M

#6699 feat: 主机抽屉网络列表辅助IP、端口映射支持通过弹窗查看详细信息
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/networks/dialogs/ViewContent.vue
  containers/Compute/views/networks/mixins/columns.js
Labels: size/L

#6705 feat: 容器主机支持终端
  containers/Compute/views/vminstance-container/constants/actions.js
  containers/Compute/views/vminstance-container/mixins/singleActions.js
Labels: size/M

#6707 Automated cherry pick of #6706: fix(3.11/9949): 物理机转宿主机时，磁盘分区挂载点可以有多个/opt/cloud/workspace
  containers/Compute/views/baremetal/dialogs/DiskOptionsUpdate.vue
Labels: size/XS

#6708 Automated cherry pick of #6706: fix(3.11/9949): 物理机转宿主机时，磁盘分区挂载点可以有多个/opt/cloud/workspace
  containers/Compute/views/baremetal/dialogs/DiskOptionsUpdate.vue
Labels: size/XS

#6703 Automated cherry pick of #6702: feat(v3.10): 增加深信服超融合
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Sangfor.vue
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/utils/index.js
  containers/Compute/views/scaling-group/create/index.vue
  containers/Compute/views/secgroup/Create.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/utils.js
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/rds/create/index.vue
  containers/DB/views/redis/create/components/BottomBar.vue
  containers/DB/views/redis/create/index.vue
  containers/IAM/views/domains/create/index.vue
  containers/IAM/views/idp/edit/index.vue
  containers/IAM/views/projects/create/index.vue
  containers/IAM/views/user/create/index.vue
  containers/Network/views/dns-zone/create/index.vue
  containers/Network/views/eip/create/components/BottomBar.vue
  containers/Network/views/eip/create/index.vue
  containers/Network/views/global-vpc/create/index.vue
  containers/Network/views/nats/create/components/BottomBar.vue
  containers/Network/views/nats/create/index.vue
  containers/Network/views/network/Create.vue
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/mixins/singleActions.js
  containers/Network/views/vpc/components/List.vue
  containers/Network/views/vpc/create/index.vue
  containers/Network/views/vpc/mixins/singleActions.js
  containers/Storage/views/bucket/create/index.vue
  containers/Storage/views/file-system/create/components/BottomBar.vue
  containers/Storage/views/file-system/create/form/IDC.vue
  containers/Storage/views/file-system/create/form/Public.vue
  containers/Storage/views/file-system/create/form/mixin.js
  src/assets/images/providers/sangfor.svg
  src/components/Icon/assets/sangfor.svg
  src/constants/compute.js
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6704 Automated cherry pick of #6702: feat(v3.10): 增加深信服超融合
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Sangfor.vue
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/utils/index.js
  containers/Compute/views/scaling-group/create/index.vue
  containers/Compute/views/secgroup/Create.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/utils.js
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/rds/create/index.vue
  containers/DB/views/redis/create/components/BottomBar.vue
  containers/DB/views/redis/create/index.vue
  containers/IAM/views/domains/create/index.vue
  containers/IAM/views/idp/edit/index.vue
  containers/IAM/views/projects/create/index.vue
  containers/IAM/views/user/create/index.vue
  containers/Network/views/dns-zone/create/index.vue
  containers/Network/views/eip/create/components/BottomBar.vue
  containers/Network/views/eip/create/index.vue
  containers/Network/views/global-vpc/create/index.vue
  containers/Network/views/nats/create/components/BottomBar.vue
  containers/Network/views/nats/create/index.vue
  containers/Network/views/network/Create.vue
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/mixins/singleActions.js
  containers/Network/views/vpc/components/List.vue
  containers/Network/views/vpc/create/index.vue
  containers/Network/views/vpc/mixins/singleActions.js
  containers/Storage/views/bucket/create/index.vue
  containers/Storage/views/file-system/create/components/BottomBar.vue
  src/assets/images/providers/sangfor.svg
  src/components/Icon/assets/sangfor.svg
  src/constants/compute.js
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6709 Automated cherry pick of #6702: feat(v3.10): 增加深信服超融合
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Sangfor.vue
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/create/index.vue
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/utils/index.js
  containers/Compute/views/scaling-group/create/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/utils.js
  containers/DB/views/rds/create/components/BottomBar.vue
  containers/DB/views/rds/create/index.vue
  containers/DB/views/redis/create/components/BottomBar.vue
  containers/DB/views/redis/create/index.vue
  containers/IAM/views/domains/create/index.vue
  containers/IAM/views/idp/edit/index.vue
  containers/IAM/views/projects/create/index.vue
  containers/IAM/views/user/create/index.vue
  containers/Network/views/dns-zone/create/index.vue
  containers/Network/views/eip/create/components/BottomBar.vue
  containers/Network/views/eip/create/index.vue
  containers/Network/views/global-vpc/create/index.vue
  containers/Network/views/nats/create/components/BottomBar.vue
  containers/Network/views/nats/create/index.vue
  containers/Network/views/network/Create.vue
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/mixins/singleActions.js
  containers/Network/views/vpc/components/List.vue
  containers/Network/views/vpc/create/index.vue
  containers/Network/views/vpc/mixins/singleActions.js
  containers/Storage/views/bucket/create/index.vue
  containers/Storage/views/file-system/create/components/BottomBar.vue
  src/assets/images/providers/sangfor.svg
  src/components/Icon/assets/sangfor.svg
  src/constants/compute.js
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6710 fix(v3.10): remove debug info
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#6711 Automated cherry pick of #6710: fix(v3.10): remove debug info
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#6713 Automated cherry pick of #6710: fix(v3.10): remove debug info
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#6712 Automated cherry pick of #6710: fix(v3.10): remove debug info
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#6716 fix(v3.11): add sangfor bugfix
  src/constants/index.js
  src/locales/index.js
Labels: size/XS

#6715 fix(v3.10): add sangfor bugfix
  containers/Compute/sections/OsSelect/ImageSelect.vue
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XXL

#6717 feat: 调整主机模版逻辑控制
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#6718 Automated cherry pick of #6717: feat: 调整主机模版逻辑控制
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#6721 Automated cherry pick of #6717: feat: 调整主机模版逻辑控制
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#6720 Automated cherry pick of #6717: feat: 调整主机模版逻辑控制
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#6719 Automated cherry pick of #6717: feat: 调整主机模版逻辑控制
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#6723 feat(v3.10): add sangfor set server-password check
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#6724 Automated cherry pick of #6723: feat(v3.10): add sangfor set server-password check
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#6726 Automated cherry pick of #6723: feat(v3.10): add sangfor set server-password check
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#6725 Automated cherry pick of #6723: feat(v3.10): add sangfor set server-password check
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/XS

#6730 Automated cherry pick of #6729: fix(v3.10/9955): sangfor bugfix
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/components/Sangfor.vue
  containers/Compute/views/host/sidepage/Detail.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/Network/views/network/mixins/singleActions.js
Labels: size/S

#6729 fix(v3.10/9955): sangfor bugfix
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/components/Sangfor.vue
  containers/Compute/views/host/sidepage/Detail.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/Network/views/network/mixins/singleActions.js
Labels: size/S

#6731 Automated cherry pick of #6729: fix(v3.10/9955): sangfor bugfix
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/components/Sangfor.vue
  containers/Compute/views/host/sidepage/Detail.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/Network/views/network/mixins/singleActions.js
Labels: size/S

#6732 Automated cherry pick of #6729: fix(v3.10/9955): sangfor bugfix
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/components/Sangfor.vue
  containers/Compute/views/host/sidepage/Detail.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/Network/views/network/mixins/singleActions.js
Labels: size/S

#6727 fix: default region id
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OracleCloud.vue
Labels: size/M

#6728 Automated cherry pick of #6727: fix: default region id
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OracleCloud.vue
Labels: size/M

#6733 fix: volcengine vm stop charge
  containers/Compute/views/vminstance/dialogs/ShutDown.vue
Labels: size/XS

#6735 Automated cherry pick of #6733: fix: volcengine vm stop charge
  containers/Compute/views/vminstance/dialogs/ShutDown.vue
Labels: size/XS

#6734 Automated cherry pick of #6733: fix: volcengine vm stop charge
  containers/Compute/views/vminstance/dialogs/ShutDown.vue
Labels: size/XS

#6736 fix: remove sangfor
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Sangfor.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/utils/index.js
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/sidepage/index.vue
  containers/Compute/views/vminstance/utils.js
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/mixins/singleActions.js
  containers/Network/views/vpc/components/List.vue
  containers/Network/views/vpc/mixins/singleActions.js
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6737 fix: remove sangfor
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Sangfor.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/utils/index.js
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/utils.js
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/mixins/singleActions.js
  containers/Network/views/vpc/components/List.vue
  containers/Network/views/vpc/mixins/singleActions.js
  src/constants/index.js
  src/locales/en.json
  src/locales/zh-CN.json
  src/store/modules/globalSetting.js
Labels: size/L

#6738 fix(v3.9): Operation logs display resource type from _i18n
  src/sections/EventList/index.vue
Labels: size/S

#6739 Automated cherry pick of #6738: fix(v3.9): Operation logs display resource type from _i18n
  src/sections/EventList/index.vue
Labels: size/S

#6740 Automated cherry pick of #6738: fix(v3.9): Operation logs display resource type from _i18n
  src/sections/EventList/index.vue
Labels: size/S

#6741 Automated cherry pick of #6738: fix(v3.9): Operation logs display resource type from _i18n
  src/sections/EventList/index.vue
Labels: size/S

#6742 Automated cherry pick of #6738: fix(v3.9): Operation logs display resource type from _i18n
  src/sections/EventList/index.vue
Labels: size/S

#6747 fix(v3.12/9955): 新建云账号默认开启代理请求
  containers/Cloudenv/views/cloudaccount/components/ProxySetting.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#6748 Automated cherry pick of #6747: fix(v3.12/9955): 新建云账号默认开启代理请求
  containers/Cloudenv/views/cloudaccount/components/ProxySetting.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XS

#6750 fix(3.11/9958): 物理机安装操作系统或新建裸金属时，磁盘分区去掉/opt/cloud/workspace的限制
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/dialogs/DiskOptionsUpdate.vue
  containers/Compute/views/physicalmachine/dialogs/Convert.vue
Labels: size/M

#6751 Automated cherry pick of #6750: fix(3.11/9958): 物理机安装操作系统或新建裸金属时，磁盘分区去掉/opt/cloud/workspace的限制
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/dialogs/DiskOptionsUpdate.vue
  containers/Compute/views/physicalmachine/dialogs/Convert.vue
Labels: size/M

#6752 Automated cherry pick of #6750: fix(3.11/9958): 物理机安装操作系统或新建裸金属时，磁盘分区去掉/opt/cloud/workspace的限制
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/baremetal/dialogs/DiskOptionsUpdate.vue
  containers/Compute/views/physicalmachine/dialogs/Convert.vue
Labels: size/M

#6754 feat(v3.12): add sangfor license item
  src/constants/feature.js
Labels: size/XS

#6755 Automated cherry pick of #6754: feat(v3.12): add sangfor license item
  src/constants/feature.js
Labels: size/XS

#6756 fix(v3.10/9927): 新建通知渠道,切换归属时切换检查通知渠道类型及时切换表单
  containers/IAM/views/notifyconfig/create/index.vue
Labels: size/S

#6757 Automated cherry pick of #6756: fix(v3.10/9927): 新建通知渠道,切换归属时切换检查通知渠道类型及时切换表单
  containers/IAM/views/notifyconfig/create/index.vue
Labels: size/S

#6758 Automated cherry pick of #6756: fix(v3.10/9927): 新建通知渠道,切换归属时切换检查通知渠道类型及时切换表单
  containers/IAM/views/notifyconfig/create/index.vue
Labels: size/S

#6759 Automated cherry pick of #6756: fix(v3.10/9927): 新建通知渠道,切换归属时切换检查通知渠道类型及时切换表单
  containers/IAM/views/notifyconfig/create/index.vue
Labels: size/S

#6760 fix(v3.11/9763): 云上id取用字典值
  src/locales/en.json
  src/locales/ja-JP.json
Labels: size/XS

#6761 Automated cherry pick of #6760: fix(v3.11/9763): 云上id取用字典值
  src/locales/en.json
  src/locales/ja-JP.json
Labels: size/XS

#6762 Automated cherry pick of #6760: fix(v3.11/9763): 云上id取用字典值
  src/locales/en.json
  src/locales/ja-JP.json
Labels: size/XS

#6763 fix(v3.11/9952): onecloud 平台创建ssh代理节点请求cloudregions参数错误
  containers/Network/views/ssh-proxy/form/index.vue
Labels: size/XS

#6764 Automated cherry pick of #6763: fix(v3.11/9952): onecloud 平台创建ssh代理节点请求cloudregions参数错误
  containers/Network/views/ssh-proxy/form/index.vue
Labels: size/XS

#6765 Automated cherry pick of #6763: fix(v3.11/9952): onecloud 平台创建ssh代理节点请求cloudregions参数错误
  containers/Network/views/ssh-proxy/form/index.vue
Labels: size/XS

#6766 feat(3.12/4861): 调整新建硬盘
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/create/index.vue
  src/sections/HypervisorRadio/index.vue
Labels: size/L

#6768 feat(3.9): 新建硬盘去掉指定虚拟机
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/create/components/HostServer.vue
  containers/Compute/views/disk/create/index.vue
Labels: size/L

#6769 Automated cherry pick of #6768: feat(3.9): 新建硬盘去掉指定虚拟机
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/create/components/HostServer.vue
  containers/Compute/views/disk/create/index.vue
Labels: size/L

#6770 Automated cherry pick of #6768: feat(3.9): 新建硬盘去掉指定虚拟机
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/create/components/HostServer.vue
  containers/Compute/views/disk/create/index.vue
Labels: size/L

#6771 Automated cherry pick of #6768: feat(3.9): 新建硬盘去掉指定虚拟机
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/create/components/HostServer.vue
  containers/Compute/views/disk/create/index.vue
Labels: size/L

#6772 Automated cherry pick of #6768: feat(3.9): 新建硬盘去掉指定虚拟机
  containers/Compute/views/disk/create/components/BottomBar.vue
  containers/Compute/views/disk/create/index.vue
Labels: size/M

#6773 fix(v3.10/9944):增加 资源新建的取消按钮,统一大小
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Compute/views/baremetal/create/BottomBar.vue
  containers/Compute/views/baremetal/create/index.vue
  containers/Compute/views/physicalmachine/add/index.vue
  containers/Compute/views/servertemplate/CreateServer.vue
  containers/Compute/views/vminstance-container/create/components/BottomBar.vue
  containers/Compute/views/vminstance-container/create/form/IDC.vue
  containers/Compute/views/vminstance-container/create/form/mixin.js
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Network/views/agent/form/index.vue
  containers/Network/views/loadbalancercluster/update/index.vue
  containers/Network/views/network/BatchEditAttributes.vue
  containers/Network/views/network/EditAttributes.vue
Labels: size/M

#6774 Automated cherry pick of #6773: fix(v3.10/9944):增加 资源新建的取消按钮,统一大小
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Compute/views/baremetal/create/BottomBar.vue
  containers/Compute/views/baremetal/create/index.vue
  containers/Compute/views/physicalmachine/add/index.vue
  containers/Compute/views/servertemplate/CreateServer.vue
  containers/Compute/views/vminstance-container/create/components/BottomBar.vue
  containers/Compute/views/vminstance-container/create/form/IDC.vue
  containers/Compute/views/vminstance-container/create/form/mixin.js
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Network/views/agent/form/index.vue
  containers/Network/views/loadbalancercluster/update/index.vue
  containers/Network/views/network/BatchEditAttributes.vue
  containers/Network/views/network/EditAttributes.vue
Labels: size/M

#6775 Automated cherry pick of #6773: fix(v3.10/9944):增加 资源新建的取消按钮,统一大小
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Compute/views/baremetal/create/BottomBar.vue
  containers/Compute/views/baremetal/create/index.vue
  containers/Compute/views/physicalmachine/add/index.vue
  containers/Compute/views/servertemplate/CreateServer.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Network/views/agent/form/index.vue
  containers/Network/views/loadbalancercluster/update/index.vue
  containers/Network/views/network/BatchEditAttributes.vue
  containers/Network/views/network/EditAttributes.vue
Labels: size/M

#6776 Automated cherry pick of #6773: fix(v3.10/9944):增加 资源新建的取消按钮,统一大小
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
  containers/Compute/views/baremetal/create/BottomBar.vue
  containers/Compute/views/baremetal/create/index.vue
  containers/Compute/views/physicalmachine/add/index.vue
  containers/Compute/views/servertemplate/CreateServer.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Network/views/agent/form/index.vue
  containers/Network/views/loadbalancercluster/update/index.vue
  containers/Network/views/network/BatchEditAttributes.vue
  containers/Network/views/network/EditAttributes.vue
Labels: size/M

#6777 fix(v3.12): 修复VMware平台禁用并提示默认值
  src/sections/HypervisorRadio/index.vue
Labels: size/XS

#6779 fix(3.10/9961): 虚拟机agent监控，会出现重复的监控条目
  containers/Monitor/views/alertresource/dialogs/Monitor.vue
Labels: size/S

#6780 Automated cherry pick of #6779: fix(3.10/9961): 虚拟机agent监控，会出现重复的监控条目
  containers/Monitor/views/alertresource/dialogs/Monitor.vue
Labels: size/S

#6782 Automated cherry pick of #6779: fix(3.10/9961): 虚拟机agent监控，会出现重复的监控条目
  containers/Monitor/views/alertresource/dialogs/Monitor.vue
Labels: size/S

#6781 Automated cherry pick of #6779: fix(3.10/9961): 虚拟机agent监控，会出现重复的监控条目
  containers/Monitor/views/alertresource/dialogs/Monitor.vue
Labels: size/S

#6783 fix(v3.11/9963): 功能选择底部操作条铺满屏幕
  src/components/PageFooter/index.vue
Labels: size/XS

#6784 Automated cherry pick of #6783: fix(v3.11/9963): 功能选择底部操作条铺满屏幕
  src/components/PageFooter/index.vue
Labels: size/XS

#6785 Automated cherry pick of #6783: fix(v3.11/9963): 功能选择底部操作条铺满屏幕
  src/components/PageFooter/index.vue
Labels: size/XS

#6786 feat(v3.11): VMware云账号新建增加区域参数信息
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
Labels: size/M

#6787 Automated cherry pick of #6786: feat(v3.11): VMware云账号新建增加区域参数信息
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
Labels: size/M

#6788 Automated cherry pick of #6786: feat(v3.11): VMware云账号新建增加区域参数信息
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
Labels: size/M

#6789 fix(v3.11/9938): Bucket operation based on ID
  containers/Storage/views/bucket/dialogs/ObecjtsDelete.vue
  containers/Storage/views/bucket/dialogs/ObjectsUpdateHttp.vue
  containers/Storage/views/bucket/dialogs/ObjectsUploadFile.vue
  containers/Storage/views/bucket/sidepage/Objects.vue
Labels: size/S

#6791 Automated cherry pick of #6789: fix(v3.11/9938): Bucket operation based on ID
  containers/Storage/views/bucket/dialogs/ObecjtsDelete.vue
  containers/Storage/views/bucket/dialogs/ObjectsUpdateHttp.vue
  containers/Storage/views/bucket/dialogs/ObjectsUploadFile.vue
  containers/Storage/views/bucket/sidepage/Objects.vue
Labels: size/S

#6792 fix: Increase the judgment of whether it is SaaS or not
  src/permission.js
  src/utils/utils.js
Labels: size/XS

#6793 Automated cherry pick of #6792: fix: Increase the judgment of whether it is SaaS or not
  src/permission.js
  src/utils/utils.js
Labels: size/XS
