Repository yunionio/dashboard, pull requests merged in 2024-10, with the labels that each got.

#7210 fix: allow auto alloc hostlocal nic, host mem cmt bound over 1, etc.
  containers/Compute/views/host/dialogs/AdjustOversoldRatio.vue
  containers/Network/views/network/mixins/singleActions.js
  src/sections/NameRepeated/index.vue
Labels: size/S

#7212 Automated cherry pick of #7211: fix: 系统初始化上传license后功能选择未成功更新
  src/components/FeatureSelector/index.vue
Labels: size/S

#7213 feat: 增加翻译
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7216 Automated cherry pick of #7215: fix: 虚拟机清除多余的项目过滤
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#7217 Automated cherry pick of #7215: fix: 虚拟机清除多余的项目过滤
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#7218 Automated cherry pick of #7215: fix: 虚拟机清除多余的项目过滤
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#7223 fix: 主机模板删除加入购物车功能
  containers/Compute/views/vminstance/create/components/BottomBar.vue
Labels: size/XS

#7224 Automated cherry pick of #7223: fix: 主机模板删除加入购物车功能
  containers/Compute/views/vminstance/create/components/BottomBar.vue
Labels: size/XS

#7225 Automated cherry pick of #7223: fix: 主机模板删除加入购物车功能
  containers/Compute/views/vminstance/create/components/BottomBar.vue
Labels: size/XS

#7226 fix: 开源删除创建云账号关于功能选择提示信息
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
Labels: size/XS

#7227 Automated cherry pick of #7226: fix: 开源删除创建云账号关于功能选择提示信息
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
Labels: size/XS

#7228 Automated cherry pick of #7226: fix: 开源删除创建云账号关于功能选择提示信息
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
Labels: size/XS

#7229 fix: 块存储修改属性调整参数结构
  containers/Storage/views/blockstorage/components/FormItems.vue
  containers/Storage/views/blockstorage/dialogs/UpdateStorage.vue
Labels: size/M

#7230 Automated cherry pick of #7229: fix: 块存储修改属性调整参数结构
  containers/Storage/views/blockstorage/components/FormItems.vue
  containers/Storage/views/blockstorage/dialogs/UpdateStorage.vue
Labels: size/M

#7231 Automated cherry pick of #7229: fix: 块存储修改属性调整参数结构
  containers/Storage/views/blockstorage/components/FormItems.vue
  containers/Storage/views/blockstorage/dialogs/UpdateStorage.vue
Labels: size/M

#7234 Automated cherry pick of #7233: fix: 扩展权限,单个操作可能由多个权限控制,权限都可配置
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/constants/actions.js
  src/constants/permission.js
  src/utils/policy/policy-options.js
Labels: size/M

#7235 Automated cherry pick of #7233: fix: 扩展权限,单个操作可能由多个权限控制,权限都可配置
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/constants/actions.js
  src/constants/permission.js
  src/utils/policy/policy-options.js
Labels: size/M

#7237 Automated cherry pick of #7236: fix: 修复数字图磁贴切换主机/容器时闪烁
  containers/Dashboard/extends/NumberCard/index.vue
Labels: size/XS

#7238 Automated cherry pick of #7236: fix: 修复数字图磁贴切换主机/容器时闪烁
  containers/Dashboard/extends/NumberCard/index.vue
Labels: size/XS

#7239 feat: ip使用情况搜索框样式优化
  containers/Network/views/network/sidepage/IPList.vue
Labels: size/S

#7241 Automated cherry pick of #7239: feat: ip使用情况搜索框样式优化
  containers/Network/views/network/sidepage/IPList.vue
Labels: size/S

#7242 feat: 域-项目选择框组件扩展
  src/constants/permission.js
  src/sections/DomainProject/model.vue
Labels: size/L

#7243 Automated cherry pick of #7242: feat: 域-项目选择框组件扩展
  src/constants/permission.js
  src/sections/DomainProject/model.vue
Labels: size/L

#7245 Automated cherry pick of #7244: fix: 价格清单系统盘参数错误
  containers/Cloudenv/views/server-price-comparator/create/components/BottomBar.vue
Labels: size/XS

#7246 fix: task details exception
  src/sections/SidePageManager/components/TaskSidePage/Detail.vue
Labels: size/S

#7247 feat: 资源修改配置保留资源列表状态
  containers/Cloudenv/router/index.js
  containers/Cloudenv/views/cloudaccount/create/BillFileIndex.vue
  containers/Cloudenv/views/cloudaccount/index.vue
  containers/Compute/router/index.js
  containers/Compute/views/vminstance-container/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance-container/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/create/index.vue
  containers/Compute/views/vminstance/index.vue
  containers/IAM/router/index.js
  containers/IAM/views/idp/edit/index.vue
  containers/IAM/views/idp/index.vue
  containers/IAM/views/policy/Update.vue
  containers/IAM/views/policy/index.vue
  containers/K8S/router/index.js
  containers/K8S/views/kube-component/index.vue
  containers/K8S/views/kube-component/update/index.vue
  containers/Monitor/router/index.js
  containers/Monitor/views/commonalert/components/new-alert/index.vue
  containers/Monitor/views/commonalert/index.vue
  containers/Network/router/index.js
  containers/Network/views/agent/form/index.vue
  containers/Network/views/agent/index.vue
  containers/Network/views/loadbalancercluster/index.vue
  containers/Network/views/loadbalancercluster/update/index.vue
  containers/Network/views/network/BatchEditAttributes.vue
  containers/Network/views/network/EditAttributes.vue
  containers/Network/views/network/index.vue
  src/layouts/RouterView/index.vue
  src/mixins/keepAlive.js
  src/permission.js
  src/store/modules/keepAlive.js
  src/utils/list.js
Labels: size/L

#7252 feat: 增加翻译
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
Labels: size/S

#7253 Automated cherry pick of #7252: feat: 增加翻译
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
Labels: size/S

#7254 feat: 扩展组件,sidePageTrigger允许获取自定义配置
  src/components/SidePageTrigger/config/index.js
Labels: size/S

#7256 feat: 组件优化,导出表格增加币种支持
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/filters/index.js
  src/sections/DialogManager/components/ExportListData.vue
  src/utils/xlsx.js
Labels: size/M

#7257 Automated cherry pick of #7256: feat: 组件优化,导出表格增加币种支持
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/filters/index.js
  src/sections/DialogManager/components/ExportListData.vue
  src/utils/xlsx.js
Labels: size/M
