Repository yunionio/dashboard, pull requests merged in 2024-04, with the labels that each got.

#6311 fix(v3.10/9781): codemirror support search
  src/components/CodeMirror/index.vue
Labels: size/S

#6312 Automated cherry pick of #6311: fix(v3.10/9781): codemirror support search
  src/components/CodeMirror/index.vue
Labels: size/S

#6313 Automated cherry pick of #6311: fix(v3.10/9781): codemirror support search
  src/components/CodeMirror/index.vue
Labels: size/S

#6314 fix: i18n
  src/locales/en.json
  src/locales/ja-JP.json
Labels: size/XS

#6315 Automated cherry pick of #6314: fix: i18n
  src/locales/en.json
  src/locales/ja-JP.json
Labels: size/XS

#6316 Automated cherry pick of #6314: fix: i18n
  src/locales/en.json
  src/locales/ja-JP.json
Labels: size/XS

#6320 feat(v3.10/4831): 裸金属详情页增加属性信息
  containers/Compute/views/baremetal/sidepage/Detail.vue
Labels: size/M

#6321 Automated cherry pick of #6320: feat(v3.10/4831): 裸金属详情页增加属性信息
  containers/Compute/views/baremetal/sidepage/Detail.vue
Labels: size/M

#6322 Automated cherry pick of #6320: feat(v3.10/4831): 裸金属详情页增加属性信息
  containers/Compute/views/baremetal/sidepage/Detail.vue
Labels: size/M

#6323 Automated cherry pick of #6320: feat(v3.10/4831): 裸金属详情页增加属性信息
  containers/Compute/views/baremetal/sidepage/Detail.vue
Labels: size/M

#6317 feat: optimize translation
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#6318 Automated cherry pick of #6317: feat: optimize translation
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#6319 Automated cherry pick of #6317: feat: optimize translation
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#6324 feat(v3.11/4756): Azure中国支持EA和存储桶
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
Labels: size/XS

#6325 Automated cherry pick of #6324: feat(v3.11/4756): Azure中国支持EA和存储桶
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
Labels: size/XS

#6326 Automated cherry pick of #6324: feat(v3.11/4756): Azure中国支持EA和存储桶
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
Labels: size/XS

#6328 Automated cherry pick of #6327: feat(v3.12/4819): 容器主机优化
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Labels/index.vue
  containers/Compute/views/vminstance-container/components/List.vue
  containers/Compute/views/vminstance-container/constants/actions.js
  containers/Compute/views/vminstance-container/create/components/BastionHost.vue
  containers/Compute/views/vminstance-container/create/components/BottomBar.vue
  containers/Compute/views/vminstance-container/create/components/CustomData.vue
  containers/Compute/views/vminstance-container/create/components/Servertemplate.vue
  containers/Compute/views/vminstance-container/create/components/SystemDisk.vue
  containers/Compute/views/vminstance-container/create/form/IDC.vue
  containers/Compute/views/vminstance-container/create/form/mixin.js
  containers/Compute/views/vminstance-container/dialogs/Delete.vue
  containers/Compute/views/vminstance-container/locales/en.json
  containers/Compute/views/vminstance-container/locales/ja-JP.json
  containers/Compute/views/vminstance-container/locales/zh-CN.json
  containers/Compute/views/vminstance-container/mixins/columns.js
  containers/Compute/views/vminstance-container/sidepage/Detail.vue
  containers/Compute/views/vminstance-container/sidepage/DiskList.vue
  containers/Compute/views/vminstance-container/utils/createServer.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XXL

#6329 feat(v3.12/4819): 容器主机优化
  containers/Compute/views/vminstance-container/constants.js
  containers/Compute/views/vminstance-container/create/form/SetupSSHForm.vue
  containers/Compute/views/vminstance-container/dialogs/ContainerShutDown.vue
  containers/Compute/views/vminstance-container/locales/en.json
  containers/Compute/views/vminstance-container/locales/ja-JP.json
  containers/Compute/views/vminstance-container/locales/zh-CN.json
  containers/Compute/views/vminstance-container/mixins/resourceProps.js
  containers/Compute/views/vminstance-container/mixins/storageResourceProps.js
  containers/Compute/views/vminstance-container/sidepage/Alert.vue
  containers/Compute/views/vminstance-container/sidepage/Container.vue
  containers/Compute/views/vminstance-container/sidepage/Disk.vue
  containers/Compute/views/vminstance-container/sidepage/Monitor.vue
  containers/Compute/views/vminstance-container/sidepage/Snapshot.vue
  containers/Compute/views/vminstance-container/sidepage/index.vue
Labels: size/XXL

#6330 Automated cherry pick of #6329: feat(v3.12/4819): 容器主机优化
  containers/Compute/views/vminstance-container/constants.js
  containers/Compute/views/vminstance-container/create/form/SetupSSHForm.vue
  containers/Compute/views/vminstance-container/dialogs/ContainerShutDown.vue
  containers/Compute/views/vminstance-container/locales/en.json
  containers/Compute/views/vminstance-container/locales/ja-JP.json
  containers/Compute/views/vminstance-container/locales/zh-CN.json
  containers/Compute/views/vminstance-container/mixins/resourceProps.js
  containers/Compute/views/vminstance-container/mixins/storageResourceProps.js
  containers/Compute/views/vminstance-container/sidepage/Alert.vue
  containers/Compute/views/vminstance-container/sidepage/Container.vue
  containers/Compute/views/vminstance-container/sidepage/Disk.vue
  containers/Compute/views/vminstance-container/sidepage/Monitor.vue
  containers/Compute/views/vminstance-container/sidepage/Snapshot.vue
  containers/Compute/views/vminstance-container/sidepage/index.vue
Labels: size/XXL

#6334 feat(v3.11/4835): 主机列表添加镜像图标
  src/components/ImageIcon/constants.js
Labels: size/XS

#6335 Automated cherry pick of #6334: feat(v3.11/4835): 主机列表添加镜像图标
  src/components/ImageIcon/constants.js
Labels: size/XS

#6336 Automated cherry pick of #6334: feat(v3.11/4835): 主机列表添加镜像图标
  src/components/ImageIcon/constants.js
Labels: size/XS

#6331 fix: image min disk show error
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
Labels: size/XS

#6332 Automated cherry pick of #6331: fix: image min disk show error
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
Labels: size/XS

#6333 Automated cherry pick of #6331: fix: image min disk show error
  containers/Compute/sections/OsSelect/ImageSelectTemplate.vue
Labels: size/XS

#6337 fix(v3.10/9741): 关闭镜像回收站后发现菜单没有隐藏
  containers/Compute/router/index.js
  src/store/modules/common.js
Labels: size/S

#6338 Automated cherry pick of #6337: fix(v3.10/9741): 关闭镜像回收站后发现菜单没有隐藏
  containers/Compute/router/index.js
  src/store/modules/common.js
Labels: size/S

#6340 Automated cherry pick of #6337: fix(v3.10/9741): 关闭镜像回收站后发现菜单没有隐藏
  containers/Compute/router/index.js
  src/store/modules/common.js
Labels: size/S

#6339 Automated cherry pick of #6337: fix(v3.10/9741): 关闭镜像回收站后发现菜单没有隐藏
  containers/Compute/router/index.js
  src/store/modules/common.js
Labels: size/S

#6341 feat(v3.11/4612): add oracle cloud
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/UploadJsonFile.vue
  containers/Cloudenv/views/cloudaccount/components/UploadPemFile.vue
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OracleCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  src/assets/images/providers/oraclecloud.svg
  src/components/Icon/assets/oraclecloud.svg
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6342 Automated cherry pick of #6341: feat(v3.11/4612): add oracle cloud
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/UploadJsonFile.vue
  containers/Cloudenv/views/cloudaccount/components/UploadPemFile.vue
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OracleCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  src/assets/images/providers/oraclecloud.svg
  src/components/Icon/assets/oraclecloud.svg
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6343 Automated cherry pick of #6341: feat(v3.11/4612): add oracle cloud
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/UploadJsonFile.vue
  containers/Cloudenv/views/cloudaccount/components/UploadPemFile.vue
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OracleCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  src/assets/images/providers/oraclecloud.svg
  src/components/Icon/assets/oraclecloud.svg
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6347 feat: vmware的镜像分类增加rocky
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/S

#6348 Automated cherry pick of #6347: feat: vmware的镜像分类增加rocky
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/S

#6349 Automated cherry pick of #6347: feat: vmware的镜像分类增加rocky
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/S

#6344 fix: update nic of bonding
  containers/Compute/views/vminstance/dialogs/VmUpdateNetworkAttr.vue
  src/utils/manager.js
Labels: size/S

#6345 Automated cherry pick of #6344: fix: update nic of bonding
  containers/Compute/views/vminstance/dialogs/VmUpdateNetworkAttr.vue
  src/utils/manager.js
Labels: size/S

#6346 Automated cherry pick of #6344: fix: update nic of bonding
  containers/Compute/views/vminstance/dialogs/VmUpdateNetworkAttr.vue
  src/utils/manager.js
Labels: size/S

#6354 feat(v3.11/4811): 支持包年包月主机转换为按量付费且同步删除
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
Labels: size/S

#6355 Automated cherry pick of #6354: feat(v3.11/4811): 支持包年包月主机转换为按量付费且同步删除
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
Labels: size/S

#6356 Automated cherry pick of #6354: feat(v3.11/4811): 支持包年包月主机转换为按量付费且同步删除
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
Labels: size/S

#6351 Automated cherry pick of #6350: fix(v3.10/9783): remove copyright 40 max chars limit
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#6352 Automated cherry pick of #6350: fix(v3.10/9783): remove copyright 40 max chars limit
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#6353 Automated cherry pick of #6350: fix(v3.10/9783): remove copyright 40 max chars limit
  containers/IAM/locales/en.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#6357 feat(v3.11/4612): oracle cloud增加文档指引
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/components/OracleCloud.vue
Labels: size/XS

#6358 Automated cherry pick of #6357: feat(v3.11/4612): oracle cloud增加文档指引
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/Cloudenv/views/cloudaccount/create/form/components/OracleCloud.vue
Labels: size/XS

#6360 feat(v3.11/4815): 私有云平台云账号和云可用区关联联动
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#6361 Automated cherry pick of #6360: feat(v3.11/4815): 私有云平台云账号和云可用区关联联动
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#6362 Automated cherry pick of #6360: feat(v3.11/4815): 私有云平台云账号和云可用区关联联动
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#6363 feat(v3.11/4612): Oracle云支持更改账号
  containers/Cloudenv/views/cloudaccount/dialogs/Update.vue
Labels: size/M

#6364 Automated cherry pick of #6363: feat(v3.11/4612): Oracle云支持更改账号
  containers/Cloudenv/views/cloudaccount/dialogs/Update.vue
Labels: size/M

#6365 Automated cherry pick of #6363: feat(v3.11/4612): Oracle云支持更改账号
  containers/Cloudenv/views/cloudaccount/dialogs/Update.vue
Labels: size/M

#6367 feat(4844): 增加云手机状态及图标
  src/components/Icon/assets/menu-phone.svg
  src/components/Icon/assets/res-phone.svg
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#6373 feat(v3.12/4816): Chart prompt box occlusion issue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/ja-JP.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/views/dashboard/components/Header.vue
  src/utils/echart.js
Labels: size/S

#6374 Automated cherry pick of #6373: feat(v3.12/4816): Chart prompt box occlusion issue
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/ja-JP.json
  containers/Dashboard/locales/zh-CN.json
  containers/Dashboard/views/dashboard/components/Header.vue
  src/utils/echart.js
Labels: size/S

#6368 fix: support associate host and backup storage
  containers/Compute/views/vminstance/dialogs/BackupCreate.vue
  containers/Storage/views/backup-storage/dialogs/HostAttachBackupStorageDialog.vue
  containers/Storage/views/backup-storage/dialogs/HostDetachBackupStorageDialog.vue
  containers/Storage/views/backup-storage/sidepage/index.vue
Labels: size/L

#6369 Automated cherry pick of #6368: fix: support associate host and backup storage
  containers/Compute/views/vminstance/dialogs/BackupCreate.vue
  containers/Storage/views/backup-storage/dialogs/HostAttachBackupStorageDialog.vue
  containers/Storage/views/backup-storage/dialogs/HostDetachBackupStorageDialog.vue
  containers/Storage/views/backup-storage/sidepage/index.vue
Labels: size/L

#6371 Automated cherry pick of #6368: fix: support associate host and backup storage
  containers/Compute/views/vminstance/dialogs/BackupCreate.vue
  containers/Storage/views/backup-storage/dialogs/HostAttachBackupStorageDialog.vue
  containers/Storage/views/backup-storage/dialogs/HostDetachBackupStorageDialog.vue
  containers/Storage/views/backup-storage/sidepage/index.vue
Labels: size/L

#6372 Automated cherry pick of #6368: fix: support associate host and backup storage
  containers/Compute/views/vminstance/dialogs/BackupCreate.vue
  containers/Storage/views/backup-storage/dialogs/HostAttachBackupStorageDialog.vue
  containers/Storage/views/backup-storage/dialogs/HostDetachBackupStorageDialog.vue
  containers/Storage/views/backup-storage/sidepage/index.vue
Labels: size/L

#6379 fix: 兼容开源版自定义路由模块加载
  src/router/routes.js
Labels: size/XS

#6377 feat: change i18n
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/ja-JP.json
  containers/Dashboard/locales/zh-CN.json
Labels: size/XS

#6378 Automated cherry pick of #6377: feat: change i18n
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/ja-JP.json
  containers/Dashboard/locales/zh-CN.json
Labels: size/XS

#6381 fix(9726): IP子网列表增加IPv6起止IP过滤器
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/components/List.vue
Labels: size/M

#6382 Automated cherry pick of #6381: fix(9726): IP子网列表增加IPv6起止IP过滤器
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/components/List.vue
Labels: size/M

#6383 Automated cherry pick of #6381: fix(9726): IP子网列表增加IPv6起止IP过滤器
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/components/List.vue
Labels: size/M

#6384 fix(9816): 新建弹性伸缩选择平台上同时选择了云联和pod
  containers/Compute/views/scaling-group/create/index.vue
Labels: size/XS

#6386 fix(9815): 新建硬盘前端传参hypervisor=pod报错输入参数错误
  src/constants/index.js
Labels: size/XS

#6387 Automated cherry pick of #6386: fix(9815): 新建硬盘前端传参hypervisor=pod报错输入参数错误
  src/constants/index.js
Labels: size/XS

#6388 feat: 功能选择私有云平台增加Pod
  src/constants/feature.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#6389 Automated cherry pick of #6388: feat: 功能选择私有云平台增加Pod
  src/constants/feature.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#6390 feat: add pod icon
  src/assets/images/features/pod.svg
  src/assets/images/providers/pod.svg
Labels: size/XS

#6392 fix(v3.10/9819): 监控--虚拟机详情页，告警策略展示有问题
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/XS

#6393 Automated cherry pick of #6392: fix(v3.10/9819): 监控--虚拟机详情页，告警策略展示有问题
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/XS

#6395 Automated cherry pick of #6392: fix(v3.10/9819): 监控--虚拟机详情页，告警策略展示有问题
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/XS

#6394 Automated cherry pick of #6392: fix(v3.10/9819): 监控--虚拟机详情页，告警策略展示有问题
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/XS

#6396 feat(v3.11/4842): 虚拟机列表导出，增加到期时间字段
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#6397 Automated cherry pick of #6396: feat(v3.11/4842): 虚拟机列表导出，增加到期时间字段
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#6398 Automated cherry pick of #6396: feat(v3.11/4842): 虚拟机列表导出，增加到期时间字段
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#6399 fix(v3.10/9819): 监控--虚拟机详情页，告警策略展示有问题
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/XS

#6400 Automated cherry pick of #6399: fix(v3.10/9819): 监控--虚拟机详情页，告警策略展示有问题
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/XS

#6402 Automated cherry pick of #6399: fix(v3.10/9819): 监控--虚拟机详情页，告警策略展示有问题
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/XS

#6401 Automated cherry pick of #6399: fix(v3.10/9819): 监控--虚拟机详情页，告警策略展示有问题
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/XS

#6403 feat(v3.11/4842): 虚拟机列表导出，调整到期时间字段
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#6404 Automated cherry pick of #6403: feat(v3.11/4842): 虚拟机列表导出，调整到期时间字段
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#6405 Automated cherry pick of #6403: feat(v3.11/4842): 虚拟机列表导出，调整到期时间字段
  containers/Compute/views/vminstance/components/List.vue
Labels: size/XS

#6406 feat(v3.10/4758): 告警策略优化
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/Filters/index.vue
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/commonalert/components/alert/form/Condition.vue
  containers/Monitor/views/commonalert/components/new-alert/form/Condition.vue
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
  containers/Monitor/views/commonalert/components/new-alert/form/thresholdInput.js
  containers/Monitor/views/commonalert/components/new-alert/index.vue
  containers/Monitor/views/commonalert/create/index.vue
  containers/Monitor/views/commonalert/sidepage/Detail.vue
  containers/Monitor/views/commonalert/update/index.vue
  containers/Monitor/views/commonalert/utils/index.js
  src/components/ContainerTitle/index.vue
Labels: size/XXL

#6407 Automated cherry pick of #6406: feat(v3.10/4758): 告警策略优化
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/Filters/index.vue
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/commonalert/components/alert/form/Condition.vue
  containers/Monitor/views/commonalert/components/new-alert/form/Condition.vue
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
  containers/Monitor/views/commonalert/components/new-alert/form/thresholdInput.js
  containers/Monitor/views/commonalert/components/new-alert/index.vue
  containers/Monitor/views/commonalert/create/index.vue
  containers/Monitor/views/commonalert/sidepage/Detail.vue
  containers/Monitor/views/commonalert/update/index.vue
  containers/Monitor/views/commonalert/utils/index.js
  src/components/ContainerTitle/index.vue
Labels: size/XXL

#6409 Automated cherry pick of #6406: feat(v3.10/4758): 告警策略优化
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/Filters/index.vue
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/commonalert/components/alert/form/Condition.vue
  containers/Monitor/views/commonalert/components/new-alert/form/Condition.vue
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
  containers/Monitor/views/commonalert/components/new-alert/form/thresholdInput.js
  containers/Monitor/views/commonalert/components/new-alert/index.vue
  containers/Monitor/views/commonalert/create/index.vue
  containers/Monitor/views/commonalert/sidepage/Detail.vue
  containers/Monitor/views/commonalert/update/index.vue
  containers/Monitor/views/commonalert/utils/index.js
  src/components/ContainerTitle/index.vue
Labels: size/XXL

#6408 Automated cherry pick of #6406: feat(v3.10/4758): 告警策略优化
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/Filters/index.vue
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/commonalert/components/alert/form/Condition.vue
  containers/Monitor/views/commonalert/components/new-alert/form/Condition.vue
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
  containers/Monitor/views/commonalert/components/new-alert/form/thresholdInput.js
  containers/Monitor/views/commonalert/components/new-alert/index.vue
  containers/Monitor/views/commonalert/create/index.vue
  containers/Monitor/views/commonalert/sidepage/Detail.vue
  containers/Monitor/views/commonalert/update/index.vue
  containers/Monitor/views/commonalert/utils/index.js
  src/components/ContainerTitle/index.vue
Labels: size/XXL

#6410 feat(v3.10/4758): 告警记录策略详情优化
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/commonalert/utils/index.js
Labels: size/M

#6411 Automated cherry pick of #6410: feat(v3.10/4758): 告警记录策略详情优化
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/commonalert/utils/index.js
Labels: size/M

#6413 Automated cherry pick of #6410: feat(v3.10/4758): 告警记录策略详情优化
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/commonalert/utils/index.js
Labels: size/M

#6412 Automated cherry pick of #6410: feat(v3.10/4758): 告警记录策略详情优化
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/commonalert/utils/index.js
Labels: size/M

#6414 feat(v3.12): add i18n
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/ja-JP.json
  containers/Dashboard/locales/zh-CN.json
Labels: size/M

#6415 Automated cherry pick of #6414: feat(v3.12): add i18n
  containers/Dashboard/locales/en.json
  containers/Dashboard/locales/ja-JP.json
  containers/Dashboard/locales/zh-CN.json
Labels: size/M

#6417 feat(v3.11/4842): RDS、Redis列表导出，增加到期时间字段
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
Labels: size/M

#6418 Automated cherry pick of #6417: feat(v3.11/4842): RDS、Redis列表导出，增加到期时间字段
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
Labels: size/M

#6420 fix: add container single actions
  containers/Compute/views/vminstance-container/components/List.vue
  containers/Compute/views/vminstance-container/constants/actions.js
  src/components/SidePageTrigger/config/index.js
Labels: size/M

#6421 feat(v3.10/9834): 修复告警策略相关问题
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
  containers/Monitor/views/commonalert/utils/index.js
Labels: size/L

#6422 Automated cherry pick of #6421: feat(v3.10/9834): 修复告警策略相关问题
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
  containers/Monitor/views/commonalert/utils/index.js
Labels: size/L

#6423 Automated cherry pick of #6421: feat(v3.10/9834): 修复告警策略相关问题
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
  containers/Monitor/views/commonalert/utils/index.js
Labels: size/L

#6424 Automated cherry pick of #6421: feat(v3.10/9834): 修复告警策略相关问题
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
  containers/Monitor/views/commonalert/utils/index.js
Labels: size/L

#6425 fix(v3.10/9826): 新建rds/redis，项目选择框与下面间距不一致
  containers/DB/views/rds/create/index.vue
  containers/DB/views/redis/create/index.vue
Labels: size/XS

#6426 Automated cherry pick of #6425: fix(v3.10/9826): 新建rds/redis，项目选择框与下面间距不一致
  containers/DB/views/rds/create/index.vue
  containers/DB/views/redis/create/index.vue
Labels: size/XS

#6427 Automated cherry pick of #6425: fix(v3.10/9826): 新建rds/redis，项目选择框与下面间距不一致
  containers/DB/views/rds/create/index.vue
  containers/DB/views/redis/create/index.vue
Labels: size/XS

#6428 Automated cherry pick of #6425: fix(v3.10/9826): 新建rds/redis，项目选择框与下面间距不一致
  containers/DB/views/rds/create/index.vue
  containers/DB/views/redis/create/index.vue
Labels: size/XS

#6429 fix(v3.10/classic): 修复经典网路判断依据
  src/components/OcSelect/index.vue
Labels: size/XS

#6430 Automated cherry pick of #6429: fix(v3.10/classic): 修复经典网路判断依据
  src/components/OcSelect/index.vue
Labels: size/XS

#6432 Automated cherry pick of #6429: fix(v3.10/classic): 修复经典网路判断依据
  src/components/OcSelect/index.vue
Labels: size/XS

#6433 fix(v3.10/classic): 还原经典网路判断依据
  src/components/OcSelect/index.vue
Labels: size/XS

#6434 Automated cherry pick of #6433: fix(v3.10/classic): 还原经典网路判断依据
  src/components/OcSelect/index.vue
Labels: size/XS

#6436 Automated cherry pick of #6433: fix(v3.10/classic): 还原经典网路判断依据
  src/components/OcSelect/index.vue
Labels: size/XS

#6435 Automated cherry pick of #6433: fix(v3.10/classic): 还原经典网路判断依据
  src/components/OcSelect/index.vue
Labels: size/XS

#6437 feat(v3.10/4848): 自定义设备类型支持自动探测
  containers/Compute/views/pci/dialogs/create.vue
  containers/Compute/views/pci/locales/en.json
  containers/Compute/views/pci/locales/ja-JP.json
  containers/Compute/views/pci/locales/zh-CN.json
  containers/Compute/views/pci/mixins/columns.js
  containers/Compute/views/pci/mixins/singleActions.js
  containers/Compute/views/pci/utils/columns.js
Labels: size/M

#6438 Automated cherry pick of #6437: feat(v3.10/4848): 自定义设备类型支持自动探测
  containers/Compute/views/pci/dialogs/create.vue
  containers/Compute/views/pci/locales/en.json
  containers/Compute/views/pci/locales/ja-JP.json
  containers/Compute/views/pci/locales/zh-CN.json
  containers/Compute/views/pci/mixins/columns.js
  containers/Compute/views/pci/mixins/singleActions.js
  containers/Compute/views/pci/utils/columns.js
Labels: size/M

#6440 Automated cherry pick of #6437: feat(v3.10/4848): 自定义设备类型支持自动探测
  containers/Compute/views/pci/dialogs/create.vue
  containers/Compute/views/pci/locales/en.json
  containers/Compute/views/pci/locales/zh-CN.json
  containers/Compute/views/pci/mixins/columns.js
  containers/Compute/views/pci/mixins/singleActions.js
  containers/Compute/views/pci/utils/columns.js
Labels: size/M

#6439 Automated cherry pick of #6437: feat(v3.10/4848): 自定义设备类型支持自动探测
  containers/Compute/views/pci/dialogs/create.vue
  containers/Compute/views/pci/locales/en.json
  containers/Compute/views/pci/locales/ja-JP.json
  containers/Compute/views/pci/locales/zh-CN.json
  containers/Compute/views/pci/mixins/columns.js
  containers/Compute/views/pci/mixins/singleActions.js
  containers/Compute/views/pci/utils/columns.js
Labels: size/M
