Repository yunionio/dashboard, pull requests merged in 2024-07, with the labels that each got.

#6856 feat(v3.11/4947): extdb 支持重跑未来账单
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
  containers/Cloudenv/views/cloudaccount/dialogs/ReRunBill.vue
Labels: size/XS

#6863 fix: adjust host details storage columes widths
  containers/Compute/views/host/sidepage/Detail.vue
  containers/Compute/views/physicalmachine/sidepage/Detail.vue
Labels: size/S

#6864 Automated cherry pick of #6863: fix: adjust host details storage columes widths
  containers/Compute/views/host/sidepage/Detail.vue
  containers/Compute/views/physicalmachine/sidepage/Detail.vue
Labels: size/S

#6865 Automated cherry pick of #6863: fix: adjust host details storage columes widths
  containers/Compute/views/host/sidepage/Detail.vue
  containers/Compute/views/physicalmachine/sidepage/Detail.vue
Labels: size/S

#6869 fix: 虚拟机调整配置适配disk_type=swap的数据盘展示
  containers/Compute/locales/en.json
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#6870 Automated cherry pick of #6869: fix: 虚拟机调整配置适配disk_type=swap的数据盘展示
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#6871 Automated cherry pick of #6869: fix: 虚拟机调整配置适配disk_type=swap的数据盘展示
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#6872 Automated cherry pick of #6869: fix: 虚拟机调整配置适配disk_type=swap的数据盘展示
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#6854 feat(v3.12/4611): cloudpods select ios iamges
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/dialogs/SnapshotCreate.vue
Labels: size/XS

#6855 Automated cherry pick of #6854: feat(v3.12/4611): cloudpods select ios iamges
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/dialogs/SnapshotCreate.vue
Labels: size/XS

#6859 fix: baremetal create image list empty
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#6860 Automated cherry pick of #6859: fix: baremetal create image list empty
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#6861 Automated cherry pick of #6859: fix: baremetal create image list empty
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#6862 Automated cherry pick of #6859: fix: baremetal create image list empty
  containers/Compute/sections/OsSelect/ImageSelect.vue
Labels: size/XS

#6866 fix: Make the file comply with the eslint specification
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/ChinaUnion.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ksyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qingcloud.vue
  containers/Cloudenv/views/cloudgroup/sidepage/index.vue
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/server-price-comparator/create/form/mixin.js
  containers/Compute/views/image/dialogs/EditAttributes.vue
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Network/views/lbacls/sidepage/index.vue
  containers/Storage/views/access-group/components/AccessGroupRule.vue
  containers/Storage/views/access-group/components/List.vue
  containers/Storage/views/access-group/sidepage/index.vue
Labels: size/M

#6867 Automated cherry pick of #6866: fix: Make the file comply with the eslint specification
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/ChinaUnion.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ksyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qingcloud.vue
  containers/Cloudenv/views/cloudgroup/sidepage/index.vue
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/server-price-comparator/create/form/mixin.js
  containers/Compute/views/image/dialogs/EditAttributes.vue
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Network/views/lbacls/sidepage/index.vue
  containers/Storage/views/access-group/components/AccessGroupRule.vue
  containers/Storage/views/access-group/components/List.vue
  containers/Storage/views/access-group/sidepage/index.vue
Labels: size/M

#6868 Automated cherry pick of #6866: fix: Make the file comply with the eslint specification
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/ChinaUnion.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ksyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qingcloud.vue
  containers/Cloudenv/views/cloudgroup/sidepage/index.vue
  containers/Cloudenv/views/externalproject/components/List.vue
  containers/Cloudenv/views/server-price-comparator/create/form/mixin.js
  containers/Compute/views/image/dialogs/EditAttributes.vue
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Network/views/lbacls/sidepage/index.vue
  containers/Storage/views/access-group/components/AccessGroupRule.vue
  containers/Storage/views/access-group/components/List.vue
  containers/Storage/views/access-group/sidepage/index.vue
Labels: size/M

#6873 fix: 增加uos系统图标展示
  src/components/ImageIcon/constants.js
Labels: size/XS

#6874 Automated cherry pick of #6873: fix: 增加uos系统图标展示
  src/components/ImageIcon/constants.js
Labels: size/XS

#6875 Automated cherry pick of #6873: fix: 增加uos系统图标展示
  src/components/ImageIcon/constants.js
Labels: size/XS

#6876 Automated cherry pick of #6873: fix: 增加uos系统图标展示
  src/components/ImageIcon/constants.js
Labels: size/XS

#6877 fix: 云用户操作去除对健康状态的检查
  containers/Cloudenv/views/clouduser/mixins/singleActions.js
Labels: size/XS

#6878 Automated cherry pick of #6877: fix: 云用户操作去除对健康状态的检查
  containers/Cloudenv/views/clouduser/mixins/singleActions.js
Labels: size/XS

#6879 Automated cherry pick of #6877: fix: 云用户操作去除对健康状态的检查
  containers/Cloudenv/views/clouduser/mixins/singleActions.js
Labels: size/XS

#6880 fix(v3.11/4769): 公有云安全组规则入方向和出方向来源限制不允许为空
  containers/Compute/views/secgroup-rule/components/List.vue
  containers/Compute/views/secgroup-rule/mixins/singleActions.js
  containers/Compute/views/secgroup/dialogs/EditRules.vue
Labels: size/M

#6881 Automated cherry pick of #6880: fix(v3.11/4769): 公有云安全组规则入方向和出方向来源限制不允许为空
  containers/Compute/views/secgroup-rule/components/List.vue
  containers/Compute/views/secgroup-rule/mixins/singleActions.js
  containers/Compute/views/secgroup/dialogs/EditRules.vue
Labels: size/M

#6882 Automated cherry pick of #6880: fix(v3.11/4769): 公有云安全组规则入方向和出方向来源限制不允许为空
  containers/Compute/views/secgroup-rule/components/List.vue
  containers/Compute/views/secgroup-rule/mixins/singleActions.js
  containers/Compute/views/secgroup/dialogs/EditRules.vue
Labels: size/M

#6883 fix: remove useless cache code
  containers/IAM/views/policy/constants.js
  containers/Network/views/dns-zone/sidepage/index.vue
  containers/Network/views/dns-zonecache/components/List.vue
  containers/Network/views/dns-zonecache/dialogs/Create.vue
  containers/Network/views/dns-zonecache/index.vue
  containers/Network/views/dns-zonecache/mixins/columns.js
  containers/Network/views/dns-zonecache/mixins/singleActions.js
  containers/Network/views/dns-zonecache/sidepage/Detail.vue
  containers/Network/views/dns-zonecache/sidepage/index.vue
  containers/Network/views/dns-zonecache/utils/index.js
  src/components/SidePageTrigger/config/index.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6884 Automated cherry pick of #6883: fix: remove useless cache code
  containers/IAM/views/policy/constants.js
  containers/Network/views/dns-zone/sidepage/index.vue
  containers/Network/views/dns-zonecache/components/List.vue
  containers/Network/views/dns-zonecache/dialogs/Create.vue
  containers/Network/views/dns-zonecache/index.vue
  containers/Network/views/dns-zonecache/mixins/columns.js
  containers/Network/views/dns-zonecache/mixins/singleActions.js
  containers/Network/views/dns-zonecache/sidepage/Detail.vue
  containers/Network/views/dns-zonecache/sidepage/index.vue
  containers/Network/views/dns-zonecache/utils/index.js
  src/components/SidePageTrigger/config/index.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6885 Automated cherry pick of #6883: fix: remove useless cache code
  containers/IAM/views/policy/constants.js
  containers/Network/views/dns-zone/sidepage/index.vue
  containers/Network/views/dns-zonecache/components/List.vue
  containers/Network/views/dns-zonecache/dialogs/Create.vue
  containers/Network/views/dns-zonecache/index.vue
  containers/Network/views/dns-zonecache/mixins/columns.js
  containers/Network/views/dns-zonecache/mixins/singleActions.js
  containers/Network/views/dns-zonecache/sidepage/Detail.vue
  containers/Network/views/dns-zonecache/sidepage/index.vue
  containers/Network/views/dns-zonecache/utils/index.js
  src/components/SidePageTrigger/config/index.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6889 feat(v3.12/4611): cloudpods support select ios images to create vm
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/dialogs/SnapshotCreate.vue
Labels: size/M

#6890 Automated cherry pick of #6889: feat(v3.12/4611): cloudpods support select ios images to create vminstance
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/dialogs/SnapshotCreate.vue
Labels: size/M

#6891 Automated cherry pick of #6889: feat(v3.12/4611): cloudpods support select ios images to create vminstance
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
Labels: size/M

#6886 fix(v3.11): 私有云场景移除部分菜单展示
  containers/Network/router/index.js
  scope/layouts/Navbar/index.vue
Labels: size/S

#6887 Automated cherry pick of #6886: fix(v3.11): 私有云场景移除部分菜单展示
  containers/Network/router/index.js
  scope/layouts/Navbar/index.vue
Labels: size/S

#6888 Automated cherry pick of #6886: fix(v3.11): 私有云场景移除部分菜单展示
  containers/Network/router/index.js
  scope/layouts/Navbar/index.vue
Labels: size/S

#6892 fix: remove useless code
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Compute/views/secgroup/sidepage/Cache.vue
  containers/Compute/views/secgroup/sidepage/Detail.vue
  containers/Compute/views/secgroup/sidepage/index.vue
  src/constants/expectStatus.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6893 Automated cherry pick of #6892: fix: remove useless code
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Compute/views/secgroup/sidepage/Cache.vue
  containers/Compute/views/secgroup/sidepage/Detail.vue
  containers/Compute/views/secgroup/sidepage/index.vue
  src/constants/expectStatus.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6894 Automated cherry pick of #6892: fix: remove useless code
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Compute/views/secgroup/sidepage/Cache.vue
  containers/Compute/views/secgroup/sidepage/Detail.vue
  containers/Compute/views/secgroup/sidepage/index.vue
  src/constants/expectStatus.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6895 feat(v3.11): IP子网支持配置dhcp_relay信息
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/Create.vue
  containers/Network/views/network/EditAttributes.vue
  containers/Network/views/network/sidepage/Detail.vue
Labels: size/M

#6897 Automated cherry pick of #6895: feat(v3.11): IP子网支持配置dhcp_relay信息
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/Create.vue
  containers/Network/views/network/EditAttributes.vue
  containers/Network/views/network/sidepage/Detail.vue
Labels: size/M

#6898 feat(v3.11): 新建物理机增加对管理口mac地址的校验
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/physicalmachine/add/index.vue
Labels: size/S

#6899 Automated cherry pick of #6898: feat(v3.11): 新建物理机增加对管理口mac地址的校验
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/physicalmachine/add/index.vue
Labels: size/S

#6900 Automated cherry pick of #6898: feat(v3.11): 新建物理机增加对管理口mac地址的校验
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/physicalmachine/add/index.vue
Labels: size/S

#6901 fix: vmware account init zone not need to be usable
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  src/sections/CloudregionZone/index.vue
Labels: size/S

#6902 Automated cherry pick of #6901: fix: vmware account init zone not need to be usable
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  src/sections/CloudregionZone/index.vue
Labels: size/S

#6903 Automated cherry pick of #6901: fix: vmware account init zone not need to be usable
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  src/sections/CloudregionZone/index.vue
Labels: size/S

#6904 fix: 批量操作完善权限验证规则
  src/components/PageList/Actions/ActionButton.vue
Labels: size/XS

#6905 Automated cherry pick of #6904: fix: 批量操作完善权限验证规则
  src/components/PageList/Actions/ActionButton.vue
Labels: size/XS

#6906 Automated cherry pick of #6904: fix: 批量操作完善权限验证规则
  src/components/PageList/Actions/ActionButton.vue
Labels: size/XS

#6907 feat: 扩展标签获取参数判断方法
  src/components/PageList/TagFilter.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/sections/TagSelect/index.vue
Labels: size/S

#6908 Automated cherry pick of #6907: feat: 扩展标签获取参数判断方法
  src/components/PageList/TagFilter.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/sections/TagSelect/index.vue
Labels: size/S

#6909 Automated cherry pick of #6907: feat: 扩展标签获取参数判断方法
  src/components/PageList/TagFilter.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/sections/TagSelect/index.vue
Labels: size/S

#6910 feat(v3.11): 虚拟机网卡支持设置辅助IP
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/networks/dialogs/ChangeSubIp.vue
  containers/Compute/views/networks/mixins/columns.js
  containers/Compute/views/networks/mixins/singleActions.js
Labels: size/L

#6911 Automated cherry pick of #6910: feat(v3.11): 虚拟机网卡支持设置辅助IP
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/networks/dialogs/ChangeSubIp.vue
  containers/Compute/views/networks/mixins/columns.js
  containers/Compute/views/networks/mixins/singleActions.js
Labels: size/L

#6913 fix: 增加权限检查
  containers/Compute/views/image/locales/en.json
  containers/Compute/views/image/locales/ja-JP.json
  containers/Compute/views/image/locales/zh-CN.json
  containers/Compute/views/image/mixins/singleActions.js
  containers/IAM/views/policy/constants.js
  src/components/PageList/Actions/ActionButton.vue
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6914 Automated cherry pick of #6913: fix: 增加权限检查
  containers/Compute/views/image/locales/en.json
  containers/Compute/views/image/locales/ja-JP.json
  containers/Compute/views/image/locales/zh-CN.json
  containers/Compute/views/image/mixins/singleActions.js
  containers/IAM/views/policy/constants.js
  src/components/PageList/Actions/ActionButton.vue
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6915 Automated cherry pick of #6913: fix: 增加权限检查
  containers/Compute/views/image/locales/en.json
  containers/Compute/views/image/locales/ja-JP.json
  containers/Compute/views/image/locales/zh-CN.json
  containers/Compute/views/image/mixins/singleActions.js
  containers/IAM/views/policy/constants.js
  src/components/PageList/Actions/ActionButton.vue
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6916 Automated cherry pick of #6913: fix: 增加权限检查
  containers/Compute/views/image/locales/en.json
  containers/Compute/views/image/locales/ja-JP.json
  containers/Compute/views/image/locales/zh-CN.json
  containers/Compute/views/image/mixins/singleActions.js
  containers/IAM/views/policy/constants.js
  src/components/PageList/Actions/ActionButton.vue
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6917 feat(v3.11/4822): 云用户显示云订阅信息
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/dialogs/SetAuth.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
  containers/Cloudenv/views/cloudgroup/components/List.vue
  containers/Cloudenv/views/cloudgroup/dialogs/Create.vue
  containers/Cloudenv/views/cloudgroup/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/sidepage/index.vue
  containers/Cloudenv/views/clouduser/components/List.vue
  containers/Cloudenv/views/clouduser/dialogs/Create.vue
  containers/Cloudenv/views/clouduser/dialogs/SetPassword.vue
  containers/Cloudenv/views/clouduser/mixins/columns.js
  containers/Cloudenv/views/clouduser/mixins/singleActions.js
  containers/Cloudenv/views/samlprovider/components/List.vue
  containers/Cloudenv/views/samlprovider/mixins/columns.js
  containers/Cloudenv/views/samlprovider/mixins/singleActions.js
  containers/Cloudenv/views/samlprovider/sidepage/index.vue
  containers/Cloudenv/views/samluser/components/List.vue
  containers/Cloudenv/views/samluser/mixins/columns.js
  src/components/Icon/assets/res-saml-provider.svg
  src/components/LiquidFill/index.vue
Labels: size/XL

#6918 Automated cherry pick of #6917: feat(v3.11/4822): 云用户显示云订阅信息
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/dialogs/SetAuth.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
  containers/Cloudenv/views/cloudgroup/components/List.vue
  containers/Cloudenv/views/cloudgroup/dialogs/Create.vue
  containers/Cloudenv/views/cloudgroup/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/sidepage/index.vue
  containers/Cloudenv/views/clouduser/components/List.vue
  containers/Cloudenv/views/clouduser/dialogs/Create.vue
  containers/Cloudenv/views/clouduser/dialogs/SetPassword.vue
  containers/Cloudenv/views/clouduser/mixins/columns.js
  containers/Cloudenv/views/clouduser/mixins/singleActions.js
  containers/Cloudenv/views/samlprovider/components/List.vue
  containers/Cloudenv/views/samlprovider/mixins/columns.js
  containers/Cloudenv/views/samlprovider/mixins/singleActions.js
  containers/Cloudenv/views/samlprovider/sidepage/index.vue
  containers/Cloudenv/views/samluser/components/List.vue
  containers/Cloudenv/views/samluser/mixins/columns.js
  src/components/Icon/assets/res-saml-provider.svg
  src/components/LiquidFill/index.vue
Labels: size/XL

#6919 Automated cherry pick of #6917: feat(v3.11/4822): 云用户显示云订阅信息
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/dialogs/SetAuth.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  containers/Cloudenv/views/cloudaccount/sidepage/Detail.vue
  containers/Cloudenv/views/cloudgroup/components/List.vue
  containers/Cloudenv/views/cloudgroup/dialogs/Create.vue
  containers/Cloudenv/views/cloudgroup/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/sidepage/index.vue
  containers/Cloudenv/views/clouduser/components/List.vue
  containers/Cloudenv/views/clouduser/dialogs/Create.vue
  containers/Cloudenv/views/clouduser/dialogs/SetPassword.vue
  containers/Cloudenv/views/clouduser/mixins/columns.js
  containers/Cloudenv/views/clouduser/mixins/singleActions.js
  containers/Cloudenv/views/samlprovider/components/List.vue
  containers/Cloudenv/views/samlprovider/mixins/columns.js
  containers/Cloudenv/views/samlprovider/mixins/singleActions.js
  containers/Cloudenv/views/samlprovider/sidepage/index.vue
  containers/Cloudenv/views/samluser/components/List.vue
  containers/Cloudenv/views/samluser/mixins/columns.js
  src/components/Icon/assets/res-saml-provider.svg
  src/components/LiquidFill/index.vue
Labels: size/XL

#6920 feat(compute): add netio pps metrics
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/node-alert/constants.js
  containers/Compute/views/vminstance/constants.js
Labels: size/M

#6921 Automated cherry pick of #6920: feat(compute): add netio pps metrics
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/node-alert/constants.js
  containers/Compute/views/vminstance/constants.js
Labels: size/M

#6922 Automated cherry pick of #6920: feat(compute): add netio pps metrics
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/node-alert/constants.js
  containers/Compute/views/vminstance/constants.js
Labels: size/M

#6923 Automated cherry pick of #6920: feat(compute): add netio pps metrics
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/node-alert/constants.js
  containers/Compute/views/vminstance/constants.js
Labels: size/M

#6925 feat(v3.10/4792): 资源导出增加云上ID
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
  containers/Network/views/lb/components/List.vue
Labels: size/XS

#6926 Automated cherry pick of #6925: feat(v3.10/4792): 资源导出增加云上ID
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
  containers/Network/views/lb/components/List.vue
Labels: size/XS

#6927 Automated cherry pick of #6925: feat(v3.10/4792): 资源导出增加云上ID
  containers/DB/views/rds/components/List.vue
  containers/DB/views/redis/components/List.vue
  containers/Network/views/lb/components/List.vue
Labels: size/XS

#6928 feat(v3.10/4836): 虚拟机重装系统提示信息优化
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/M

#6929 Automated cherry pick of #6928: feat(v3.10/4836): 虚拟机重装系统提示信息优化
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/M

#6930 Automated cherry pick of #6928: feat(v3.10/4836): 虚拟机重装系统提示信息优化
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/M

#6931 Automated cherry pick of #6928: feat(v3.10/4836): 虚拟机重装系统提示信息优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/dialogs/RebuildRoot.vue
Labels: size/M

#6932 feat(monitor): add p95 and p50 query of monitor
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/Monitor/Header.vue
  src/utils/monitor.js
Labels: size/S

#6933 Automated cherry pick of #6932: feat(monitor): add p95 and p50 query of monitor
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/Monitor/Header.vue
  src/utils/monitor.js
Labels: size/S

#6934 Automated cherry pick of #6932: feat(monitor): add p95 and p50 query of monitor
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/Monitor/Header.vue
  src/utils/monitor.js
Labels: size/S

#6935 Automated cherry pick of #6932: feat(monitor): add p95 and p50 query of monitor
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/Monitor/Header.vue
  src/utils/monitor.js
Labels: size/S

#6936 feat(v3.11): cloudid一对一映射
  containers/Cloudenv/views/cloudgroup/components/List.vue
  containers/Cloudenv/views/cloudgroup/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/sidepage/index.vue
  containers/Cloudenv/views/clouduser/components/List.vue
  containers/Cloudenv/views/clouduser/dialogs/SetGroups.vue
  containers/Cloudenv/views/clouduser/mixins/columns.js
  containers/Cloudenv/views/samluser/components/List.vue
  containers/Cloudenv/views/samluser/dialogs/Create.vue
  containers/Cloudenv/views/samluser/mixins/columns.js
Labels: size/L

#6937 Automated cherry pick of #6936: feat(v3.11): cloudid一对一映射
  containers/Cloudenv/views/cloudgroup/components/List.vue
  containers/Cloudenv/views/cloudgroup/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/sidepage/index.vue
  containers/Cloudenv/views/clouduser/components/List.vue
  containers/Cloudenv/views/clouduser/dialogs/SetGroups.vue
  containers/Cloudenv/views/clouduser/mixins/columns.js
  containers/Cloudenv/views/samluser/components/List.vue
  containers/Cloudenv/views/samluser/dialogs/Create.vue
  containers/Cloudenv/views/samluser/mixins/columns.js
Labels: size/L

#6938 Automated cherry pick of #6936: feat(v3.11): cloudid一对一映射
  containers/Cloudenv/views/cloudgroup/components/List.vue
  containers/Cloudenv/views/cloudgroup/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/sidepage/index.vue
  containers/Cloudenv/views/clouduser/components/List.vue
  containers/Cloudenv/views/clouduser/dialogs/SetGroups.vue
  containers/Cloudenv/views/clouduser/mixins/columns.js
  containers/Cloudenv/views/samluser/components/List.vue
  containers/Cloudenv/views/samluser/dialogs/Create.vue
  containers/Cloudenv/views/samluser/mixins/columns.js
Labels: size/L

#6939 Automated cherry pick of #6936: feat(v3.11): cloudid一对一映射
  containers/Cloudenv/views/cloudgroup/components/List.vue
  containers/Cloudenv/views/cloudgroup/mixins/columns.js
  containers/Cloudenv/views/cloudprovider/sidepage/index.vue
  containers/Cloudenv/views/clouduser/components/List.vue
  containers/Cloudenv/views/clouduser/dialogs/SetGroups.vue
  containers/Cloudenv/views/clouduser/mixins/columns.js
  containers/Cloudenv/views/samluser/components/List.vue
  containers/Cloudenv/views/samluser/dialogs/Create.vue
  containers/Cloudenv/views/samluser/mixins/columns.js
Labels: size/L

#6940 feat(v3.11): 云用户组使用manager_id过滤
  containers/Cloudenv/views/cloudgroup/components/List.vue
Labels: size/XS

#6941 Automated cherry pick of #6940: feat(v3.11): 云用户组使用manager_id过滤
  containers/Cloudenv/views/cloudgroup/components/List.vue
Labels: size/XS

#6942 Automated cherry pick of #6940: feat(v3.11): 云用户组使用manager_id过滤
  containers/Cloudenv/views/cloudgroup/components/List.vue
Labels: size/XS

#6943 Automated cherry pick of #6940: feat(v3.11): 云用户组使用manager_id过滤
  containers/Cloudenv/views/cloudgroup/components/List.vue
Labels: size/XS

#6947 fix(v3.10): numerify函数适配科学计数法
  src/filters/index.js
Labels: size/XS

#6948 Automated cherry pick of #6947: fix(v3.10): numerify函数适配科学计数法
  src/filters/index.js
Labels: size/XS

#6949 Automated cherry pick of #6947: fix(v3.10): numerify函数适配科学计数法
  src/filters/index.js
Labels: size/XS

#6950 Automated cherry pick of #6947: fix(v3.10): numerify函数适配科学计数法
  src/filters/index.js
Labels: size/XS

#6951 feat(monitor): add inodes usage
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
Labels: size/XS

#6952 Automated cherry pick of #6951: feat(monitor): add inodes usage
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
Labels: size/XS

#6953 Automated cherry pick of #6951: feat(monitor): add inodes usage
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
Labels: size/XS

#6954 Automated cherry pick of #6951: feat(monitor): add inodes usage
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
Labels: size/XS

#6955 feat(v3.11): 裸金属网络移除带宽限制展示
  containers/Compute/views/baremetal/sidepage/Network.vue
Labels: size/S

#6956 Automated cherry pick of #6955: feat(v3.11): 裸金属网络移除带宽限制展示
  containers/Compute/views/baremetal/sidepage/Network.vue
Labels: size/S

#6957 Automated cherry pick of #6955: feat(v3.11): 裸金属网络移除带宽限制展示
  containers/Compute/views/baremetal/sidepage/Network.vue
Labels: size/S

#6958 Automated cherry pick of #6955: feat(v3.11): 裸金属网络移除带宽限制展示
  containers/Compute/views/baremetal/sidepage/Network.vue
Labels: size/S

#6945 Automated cherry pick of #6944: feat(v3.11): 增加状态映射
  src/components/Detail/index.js
  src/components/Icon/assets/res-resource-tag.svg
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#6946 Automated cherry pick of #6944: feat(v3.11): 增加状态映射
  src/components/Detail/index.js
  src/components/Icon/assets/res-resource-tag.svg
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#6959 fix: 优化wmware平台userdata提示文字
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/create/components/CustomData.vue
Labels: size/XS

#6960 Automated cherry pick of #6959: fix: 优化wmware平台userdata提示文字
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/create/components/CustomData.vue
Labels: size/XS

#6961 Automated cherry pick of #6959: fix: 优化wmware平台userdata提示文字
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/create/components/CustomData.vue
Labels: size/XS

#6962 Automated cherry pick of #6959: fix: 优化wmware平台userdata提示文字
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/create/components/CustomData.vue
Labels: size/XS

#6967 fix: 虚拟机批量调整配置按cpu核数最大的来做限制
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/M

#6968 Automated cherry pick of #6967: fix: 虚拟机批量调整配置按cpu核数最大的来做限制
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/M

#6969 Automated cherry pick of #6967: fix: 虚拟机批量调整配置按cpu核数最大的来做限制
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/M

#6971 Automated cherry pick of #6967: fix: 虚拟机批量调整配置按cpu核数最大的来做限制
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/M

#6972 fix: 过滤cpu可选项,需设置了cpu_sockets时生效
  containers/Compute/sections/CpuRadio/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#6973 Automated cherry pick of #6972: fix: 过滤cpu可选项,需设置了cpu_sockets时生效
  containers/Compute/sections/CpuRadio/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#6974 Automated cherry pick of #6972: fix: 过滤cpu可选项,需设置了cpu_sockets时生效
  containers/Compute/sections/CpuRadio/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#6975 Automated cherry pick of #6972: fix: 过滤cpu可选项,需设置了cpu_sockets时生效
  containers/Compute/sections/CpuRadio/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#6976 feat: eip展示类型
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/mixins/columns.js
Labels: size/M

#6977 Automated cherry pick of #6976: feat: eip展示类型
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/mixins/columns.js
Labels: size/M

#6980 feat(monitor): query net pps metric
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
Labels: area/monitor, size/XS

#6981 Automated cherry pick of #6980: feat(monitor): query net pps metric
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
Labels: size/XS

#6982 Automated cherry pick of #6980: feat(monitor): query net pps metric
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
Labels: size/XS

#6979 Automated cherry pick of #6978: feat(v3.12): 公网IP禁用解绑操作
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/eip/mixins/singleActions.js
Labels: size/S

#6984 feat: 告警资源增加详情和告警记录
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/views/alertresource/components/List.vue
  containers/Monitor/views/alertresource/mixins/singleActions.js
  containers/Monitor/views/alertresource/sidepage/Detail.vue
  containers/Monitor/views/alertresource/sidepage/index.vue
Labels: size/L

#6985 Automated cherry pick of #6984: feat: 告警资源增加详情和告警记录
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/views/alertresource/components/List.vue
  containers/Monitor/views/alertresource/mixins/singleActions.js
  containers/Monitor/views/alertresource/sidepage/Detail.vue
  containers/Monitor/views/alertresource/sidepage/index.vue
Labels: size/L

#6986 Automated cherry pick of #6984: feat: 告警资源增加详情和告警记录
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/views/alertresource/components/List.vue
  containers/Monitor/views/alertresource/mixins/singleActions.js
  containers/Monitor/views/alertresource/sidepage/Detail.vue
  containers/Monitor/views/alertresource/sidepage/index.vue
Labels: size/L

#6987 Automated cherry pick of #6984: feat: 告警资源增加详情和告警记录
  containers/Monitor/locales/en.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/views/alertresource/components/List.vue
  containers/Monitor/views/alertresource/mixins/singleActions.js
  containers/Monitor/views/alertresource/sidepage/Detail.vue
  containers/Monitor/views/alertresource/sidepage/index.vue
Labels: size/L

#6988 feat: 告警资源详情优化
  containers/Monitor/views/alertresource/sidepage/Detail.vue
Labels: size/S

#6989 Automated cherry pick of #6988: feat: 告警资源详情优化
  containers/Monitor/views/alertresource/sidepage/Detail.vue
Labels: size/S

#6990 Automated cherry pick of #6988: feat: 告警资源详情优化
  containers/Monitor/views/alertresource/sidepage/Detail.vue
Labels: size/S

#6991 Automated cherry pick of #6988: feat: 告警资源详情优化
  containers/Monitor/views/alertresource/sidepage/Detail.vue
Labels: size/S

#6992 feat: 告警资源详情展示优化
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/XS

#6993 Automated cherry pick of #6992: feat: 告警资源详情展示优化
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/XS

#6994 Automated cherry pick of #6992: feat: 告警资源详情展示优化
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/XS

#6995 Automated cherry pick of #6992: feat: 告警资源详情展示优化
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/XS

#6996 feat: dateTime 组件增加限制参数
  src/components/DateTime/index.vue
Labels: size/XS

#6997 Automated cherry pick of #6996: feat: dateTime 组件增加限制参数
  src/components/DateTime/index.vue
Labels: size/XS

#6998 Automated cherry pick of #6996: feat: dateTime 组件增加限制参数
  src/components/DateTime/index.vue
Labels: size/XS

#6999 feat: 告警状态翻译优化
  scope/layouts/Navbar/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7000 Automated cherry pick of #6999: feat: 告警状态翻译优化
  scope/layouts/Navbar/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7001 Automated cherry pick of #6999: feat: 告警状态翻译优化
  scope/layouts/Navbar/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7002 Automated cherry pick of #6999: feat: 告警状态翻译优化
  scope/layouts/Navbar/index.vue
  src/locales/en.json
  src/locales/zh-CN.json
Labels: size/S

#7003 feat: 告警状态翻译优化
  containers/Monitor/views/alertresource/sidepage/Detail.vue
  src/constants/expectStatus.js
Labels: size/XS

#7004 Automated cherry pick of #7003: feat: 告警状态翻译优化
  containers/Monitor/views/alertresource/sidepage/Detail.vue
  src/constants/expectStatus.js
Labels: size/XS

#7005 Automated cherry pick of #7003: feat: 告警状态翻译优化
  containers/Monitor/views/alertresource/sidepage/Detail.vue
  src/constants/expectStatus.js
Labels: size/XS

#7006 Automated cherry pick of #7003: feat: 告警状态翻译优化
  containers/Monitor/views/alertresource/sidepage/Detail.vue
  src/constants/expectStatus.js
Labels: size/XS

#7007 fix: remove error commit
  src/components/DateTime/index.vue
Labels: size/XS

#7008 Automated cherry pick of #7007: fix: remove error commit
  src/components/DateTime/index.vue
Labels: size/XS

#7009 Automated cherry pick of #7007: fix: remove error commit
  src/components/DateTime/index.vue
Labels: size/XS
