Repository yunionio/dashboard, pull requests merged in 2024-05, with the labels that each got.

#6442 Automated cherry pick of #6441: fix(v3.10): monitor params
  containers/Monitor/views/commonalert/components/new-alert/index.vue
Labels: size/XS

#6443 Automated cherry pick of #6441: fix(v3.10): monitor params
  containers/Monitor/views/commonalert/components/new-alert/index.vue
Labels: size/XS

#6444 fix: i18n get method error
  containers/Compute/views/vminstance-container/constants/actions.js
Labels: size/XS

#6445 fix(3.12/http): 从镜像仓库创建的镜像，将协议去掉
  containers/Compute/views/vminstance-container/utils/createServer.js
Labels: size/XS

#6447 fix: 移除未使用变量导致的ESLint错误校验提示信息
  src/components/OcSelect/index.vue
Labels: size/XS

#6448 Automated cherry pick of #6447: fix: 移除未使用变量导致的ESLint错误校验提示信息
  src/components/OcSelect/index.vue
Labels: size/XS

#6450 Automated cherry pick of #6447: fix: 移除未使用变量导致的ESLint错误校验提示信息
  src/components/OcSelect/index.vue
Labels: size/XS

#6449 Automated cherry pick of #6447: fix: 移除未使用变量导致的ESLint错误校验提示信息
  src/components/OcSelect/index.vue
Labels: size/XS

#6451 fix(v3.10/9851): excel export data format number error
  src/utils/xlsx.js
Labels: size/XS

#6452 Automated cherry pick of #6451: fix(v3.10/9851): excel export data format number error
  src/utils/xlsx.js
Labels: size/XS

#6453 Automated cherry pick of #6451: fix(v3.10/9851): excel export data format number error
  src/utils/xlsx.js
Labels: size/XS

#6454 Automated cherry pick of #6451: fix(v3.10/9851): excel export data format number error
  src/utils/xlsx.js
Labels: size/XS

#6455 feat: add icon
  src/components/Icon/assets/dashboard-bar.svg
Labels: size/XS

#6456 Automated cherry pick of #6455: feat: add icon
  src/components/Icon/assets/dashboard-bar.svg
Labels: size/XS

#6457 feat(4853): 容器主机支持终端查询
  containers/Compute/views/vminstance-container/constants/actions.js
  containers/Compute/views/vminstance-container/locales/en.json
  containers/Compute/views/vminstance-container/locales/ja-JP.json
  containers/Compute/views/vminstance-container/locales/zh-CN.json
  containers/Compute/views/vminstance-container/sidepage/Terminal.vue
  containers/Compute/views/vminstance-container/sidepage/index.vue
Labels: size/L

#6458 fix(v3.11/9852): 监控面板导出的列表内容，数据不全，只有第1列有数据
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
Labels: size/XS

#6459 Automated cherry pick of #6458: fix(v3.11/9852): 监控面板导出的列表内容，数据不全，只有第1列有数据
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
Labels: size/XS

#6460 Automated cherry pick of #6458: fix(v3.11/9852): 监控面板导出的列表内容，数据不全，只有第1列有数据
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
Labels: size/XS

#6463 feat(v3.12): add currency EUR
  containers/Cloudenv/views/server-price-comparator/create/form/mixin.js
  containers/DB/views/rds/create/components/SKU/components/List.vue
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  src/constants/currency.js
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/common/price.js
Labels: size/M

#6464 Automated cherry pick of #6463: feat(v3.12): add currency EUR
  containers/Cloudenv/views/server-price-comparator/create/form/mixin.js
  containers/DB/views/rds/create/components/SKU/components/List.vue
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  src/constants/currency.js
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/common/price.js
Labels: size/M

#6465 fix(9838): 指定宿主机新建容器主机时，获取宿主机的接口报错
  containers/Compute/views/vminstance-container/create/form/IDC.vue
Labels: size/XS

#6474 fix: more host details
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/host/sidepage/Detail.vue
  containers/Compute/views/host/sidepage/VminstanceList.vue
  containers/Compute/views/host/sidepage/index.vue
  containers/Compute/views/vminstance-container/components/List.vue
  containers/Compute/views/vminstance-container/sidepage/index.vue
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/L

#6467 feat(v3.11/4789): external project support set priority
  containers/Cloudenv/views/externalproject/dialogs/SetPriority.vue
Labels: size/XS

#6468 Automated cherry pick of #6467: feat(v3.11/4789): external project support set priority
  containers/Cloudenv/views/externalproject/dialogs/SetPriority.vue
Labels: size/XS

#6470 fix(v3.10/9857): fetch user uneffect in domain mode
  containers/IAM/views/contact/dialogs/Create.vue
Labels: size/XS

#6471 Automated cherry pick of #6470: fix(v3.10/9857): fetch user uneffect in domain mode
  containers/IAM/views/contact/dialogs/Create.vue
Labels: size/XS

#6469 Automated cherry pick of #6467: feat(v3.11/4789): external project support set priority
  containers/Cloudenv/views/externalproject/dialogs/SetPriority.vue
Labels: size/XS

#6472 Automated cherry pick of #6470: fix(v3.10/9857): fetch user uneffect in domain mode
  containers/IAM/views/contact/dialogs/Create.vue
Labels: size/XS

#6473 Automated cherry pick of #6470: fix(v3.10/9857): fetch user uneffect in domain mode
  containers/IAM/views/contact/dialogs/Create.vue
Labels: size/XS

#6476 feat(v3.11/4872): 调整费用预测开关字段
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#6479 Automated cherry pick of #6476: feat(4872): 调整费用预测开关字段
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#6481 Automated cherry pick of #6476: feat(4872): 调整费用预测开关字段
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
Labels: size/XS

#6477 fix(v3.11/9862): Platform filtering optimization
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/common/tableFilter.js
Labels: size/XS

#6478 Automated cherry pick of #6477: fix(v3.11/9862): Platform filtering optimization
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/common/tableFilter.js
Labels: size/XS

#6480 Automated cherry pick of #6477: fix(v3.11/9862): Platform filtering optimization
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/common/tableFilter.js
Labels: size/XS

#6482 fix(3.11/9860): 镜像other linux系统默认展示linux图标
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/M

#6483 Automated cherry pick of #6482: fix(3.11/9860): 镜像other linux系统默认展示linux图标
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/M

#6484 Automated cherry pick of #6482: fix(3.11/9860): 镜像other linux系统默认展示linux图标
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/M

#6485 fix(v3.10/9701): EIP支持批量修改项目
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/mixins/singleActions.js
Labels: size/S

#6486 Automated cherry pick of #6485: fix(v3.10/9701): EIP支持批量修改项目
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/mixins/singleActions.js
Labels: size/S

#6488 Automated cherry pick of #6485: fix(v3.10/9701): EIP支持批量修改项目
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/mixins/singleActions.js
Labels: size/S

#6487 Automated cherry pick of #6485: fix(v3.10/9701): EIP支持批量修改项目
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/mixins/singleActions.js
Labels: size/S

#6489 fix(v3.11/9841): The selected features add filtering supported of license
  src/permission.js
  src/store/modules/globalSetting.js
  src/utils/auth.js
Labels: size/M

#6490 Automated cherry pick of #6489: fix(v3.11/9841): The selected features add filtering supported of license
  src/permission.js
  src/store/modules/globalSetting.js
  src/utils/auth.js
Labels: size/M

#6491 Automated cherry pick of #6489: fix(v3.11/9841): The selected features add filtering supported of license
  src/permission.js
  src/store/modules/globalSetting.js
  src/utils/auth.js
Labels: size/M

#6492 fix(v3.11/4847): export compute disk/mem delete unit
  containers/Compute/views/vminstance/components/List.vue
Labels: size/S

#6493 Automated cherry pick of #6492: fix(v3.11/4847): export compute disk/mem delete unit
  containers/Compute/views/vminstance/components/List.vue
Labels: size/S

#6494 Automated cherry pick of #6492: fix(v3.11/4847): export compute disk/mem delete unit
  containers/Compute/views/vminstance/components/List.vue
Labels: size/S

#6495 feat(4874): 容器主机增加监控
  containers/Compute/views/node-alert/constants.js
  containers/Compute/views/vminstance-container/constants.js
  containers/Compute/views/vminstance-container/locales/en.json
  containers/Compute/views/vminstance-container/locales/ja-JP.json
  containers/Compute/views/vminstance-container/locales/zh-CN.json
  containers/Compute/views/vminstance-container/sidepage/Monitor.vue
  src/sections/Charts/Lines.vue
  src/utils/utils.js
Labels: size/L

#6496 fix: update azure web app field
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/webapp/components/List.vue
  containers/Compute/views/webapp/constants/index.js
  containers/Compute/views/webapp/mixins/columns.js
  containers/Compute/views/webapp/sidepage/Detail.vue
  containers/Compute/views/webapp/sidepage/EnvironmentsList.vue
  containers/Compute/views/webapp/utils/columns.js
Labels: size/L

#6497 Automated cherry pick of #6496: fix: update azure web app field
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/webapp/components/List.vue
  containers/Compute/views/webapp/constants/index.js
  containers/Compute/views/webapp/mixins/columns.js
  containers/Compute/views/webapp/sidepage/Detail.vue
  containers/Compute/views/webapp/sidepage/EnvironmentsList.vue
  containers/Compute/views/webapp/utils/columns.js
Labels: size/L

#6498 Automated cherry pick of #6496: fix: update azure web app field
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/webapp/components/List.vue
  containers/Compute/views/webapp/constants/index.js
  containers/Compute/views/webapp/mixins/columns.js
  containers/Compute/views/webapp/sidepage/Detail.vue
  containers/Compute/views/webapp/sidepage/EnvironmentsList.vue
  containers/Compute/views/webapp/utils/columns.js
Labels: size/L

#6499 fix(v3.11/9786): scope provider i18n
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/IAM/sections/Quota/index.vue
  containers/Network/views/dns-recordset/constants/index.js
  containers/Network/views/vpc-peer-connect/constants.js
  scope/locales/en.json
  scope/locales/ja-JP.json
  scope/locales/zh-CN.json
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/index.js
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/plugins/i18n.js
  src/sections/AreaSelects/index.js
Labels: size/L

#6500 Automated cherry pick of #6499: fix(v3.11/9786): scope provider i18n
  containers/Cloudenv/views/cloudaccount/constants.js
  containers/IAM/sections/Quota/index.vue
  containers/Network/views/dns-recordset/constants/index.js
  containers/Network/views/vpc-peer-connect/constants.js
  scope/locales/en.json
  scope/locales/ja-JP.json
  scope/locales/zh-CN.json
  src/constants/feature.js
  src/constants/index.js
  src/locales/en.json
  src/locales/index.js
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/plugins/i18n.js
  src/sections/AreaSelects/index.js
Labels: size/L

#6503 fix(v3.11/9689): 监控告警新建no data条件时，新建策略失败
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
  containers/Monitor/views/commonalert/components/new-alert/index.vue
Labels: size/S

#6504 Automated cherry pick of #6503: fix(v3.11/9689): 监控告警新建no data条件时，新建策略失败
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
  containers/Monitor/views/commonalert/components/new-alert/index.vue
Labels: size/S

#6505 Automated cherry pick of #6503: fix(v3.11/9689): 监控告警新建no data条件时，新建策略失败
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
  containers/Monitor/views/commonalert/components/new-alert/index.vue
Labels: size/S

#6506 fix(v3.11/9872): 当公有云触发告警后，查看告警详情页面没对齐
  containers/Monitor/views/alertrecord/dialogs/ViewAlertrecordDetail.vue
Labels: size/S

#6507 Automated cherry pick of #6506: fix(v3.11/9872): 当公有云触发告警后，查看告警详情页面没对齐
  containers/Monitor/views/alertrecord/dialogs/ViewAlertrecordDetail.vue
Labels: size/S

#6508 Automated cherry pick of #6506: fix(v3.11/9872): 当公有云触发告警后，查看告警详情页面没对齐
  containers/Monitor/views/alertrecord/dialogs/ViewAlertrecordDetail.vue
Labels: size/S

#6509 Automated cherry pick of #6503: fix(v3.11/9689): 监控告警新建no data条件时，新建策略失败
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
  containers/Monitor/views/commonalert/components/new-alert/index.vue
Labels: size/S

#6510 Automated cherry pick of #6506: fix(v3.11/9872): 当公有云触发告警后，查看告警详情页面没对齐
  containers/Monitor/views/alertrecord/dialogs/ViewAlertrecordDetail.vue
Labels: size/S

#6511 fix(v3.10/9874): 修改告警策略切换所属时触发条件一直添加
  containers/Monitor/views/commonalert/components/new-alert/form/Condition.vue
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
Labels: size/XS

#6512 Automated cherry pick of #6511: fix(v3.10/9874): 修改告警策略切换所属时触发条件一直添加
  containers/Monitor/views/commonalert/components/new-alert/form/Condition.vue
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
Labels: size/XS

#6514 Automated cherry pick of #6511: fix(v3.10/9874): 修改告警策略切换所属时触发条件一直添加
  containers/Monitor/views/commonalert/components/new-alert/form/Condition.vue
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
Labels: size/XS

#6513 Automated cherry pick of #6511: fix(v3.10/9874): 修改告警策略切换所属时触发条件一直添加
  containers/Monitor/views/commonalert/components/new-alert/form/Condition.vue
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
Labels: size/XS

#6516 Automated cherry pick of #6515: feat(v3.11/4876): webapp add custom domains
  containers/Compute/router/index.js
  containers/Compute/views/webapp/sidepage/BackupList.vue
  containers/Compute/views/webapp/sidepage/CertificateList.vue
  containers/Compute/views/webapp/sidepage/Detail.vue
  containers/Compute/views/webapp/sidepage/DomainList.vue
  containers/Compute/views/webapp/sidepage/index.vue
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6517 Automated cherry pick of #6515: feat(v3.11/4876): webapp add custom domains
  containers/Compute/router/index.js
  containers/Compute/views/webapp/sidepage/BackupList.vue
  containers/Compute/views/webapp/sidepage/CertificateList.vue
  containers/Compute/views/webapp/sidepage/Detail.vue
  containers/Compute/views/webapp/sidepage/DomainList.vue
  containers/Compute/views/webapp/sidepage/index.vue
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6518 feat(v3.11/4772): add image market in ce
  containers/Compute/router/index.js
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/image-import-ce/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6519 Automated cherry pick of #6518: feat(v3.11/4772): add image market in ce
  containers/Compute/router/index.js
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/image-import-ce/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6520 Automated cherry pick of #6518: feat(v3.11/4772): add image market in ce
  containers/Compute/router/index.js
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/image-import-ce/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#6521 feat(v3.12/4774): 支持CephFS本地IDC新建
  containers/Storage/views/file-system/components/List.vue
  containers/Storage/views/file-system/create/components/BottomBar.vue
  containers/Storage/views/file-system/create/components/SKU/components/List.vue
  containers/Storage/views/file-system/create/components/SKU/index.vue
  containers/Storage/views/file-system/create/form/IDC.vue
  containers/Storage/views/file-system/create/form/Public.vue
  containers/Storage/views/file-system/create/form/mixin.js
  containers/Storage/views/file-system/create/index.vue
  containers/Storage/views/file-system/index.vue
  src/sections/NetworkSelects/index.js
Labels: size/XXL

#6522 Automated cherry pick of #6521: feat(v3.12/4774): 支持CephFS本地IDC新建
  containers/Storage/views/file-system/components/List.vue
  containers/Storage/views/file-system/create/components/BottomBar.vue
  containers/Storage/views/file-system/create/components/SKU/components/List.vue
  containers/Storage/views/file-system/create/components/SKU/index.vue
  containers/Storage/views/file-system/create/form/IDC.vue
  containers/Storage/views/file-system/create/form/Public.vue
  containers/Storage/views/file-system/create/form/mixin.js
  containers/Storage/views/file-system/create/index.vue
  containers/Storage/views/file-system/index.vue
  src/sections/NetworkSelects/index.js
Labels: size/XXL

#6526 feat(4883): 容器主机支持VPC网络
  containers/Compute/views/vminstance-container/create/form/IDC.vue
Labels: size/XS

#6524 Automated cherry pick of #6523: feat(v3.11/4878): xlsx export set date formatter
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/xlsx.js
Labels: size/M

#6525 Automated cherry pick of #6523: feat(v3.11/4878): xlsx export set date formatter
  src/constants/index.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/xlsx.js
Labels: size/M

#6527 feat(v3.11/4772): add image market in ce
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/image-import-ce/index.vue
  containers/Compute/views/image/image-import-ce/openimages.yaml
  src/assets/images/os-images/almalinux.svg
  src/assets/images/os-images/anolis.svg
  src/assets/images/os-images/archlinux.svg
  src/assets/images/os-images/fedora.svg
  src/assets/images/os-images/opencloudos.svg
  src/assets/images/os-images/openeuler.svg
  src/assets/images/os-images/rockylinux.svg
  src/constants/error.js
  src/locales/help-en.js
  src/locales/help-ja-JP.js
  src/locales/help-zh-CN.js
Labels: size/XL

#6528 Automated cherry pick of #6527: feat(v3.11/4772): add image market in ce
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/image-import-ce/index.vue
  containers/Compute/views/image/image-import-ce/openimages.yaml
  src/assets/images/os-images/almalinux.svg
  src/assets/images/os-images/anolis.svg
  src/assets/images/os-images/archlinux.svg
  src/assets/images/os-images/fedora.svg
  src/assets/images/os-images/opencloudos.svg
  src/assets/images/os-images/openeuler.svg
  src/assets/images/os-images/rockylinux.svg
  src/constants/error.js
  src/locales/help-en.js
  src/locales/help-ja-JP.js
  src/locales/help-zh-CN.js
Labels: size/XL

#6529 Automated cherry pick of #6527: feat(v3.11/4772): add image market in ce
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/image-import-ce/index.vue
  containers/Compute/views/image/image-import-ce/openimages.yaml
  src/assets/images/os-images/almalinux.svg
  src/assets/images/os-images/anolis.svg
  src/assets/images/os-images/archlinux.svg
  src/assets/images/os-images/fedora.svg
  src/assets/images/os-images/opencloudos.svg
  src/assets/images/os-images/openeuler.svg
  src/assets/images/os-images/rockylinux.svg
  src/constants/error.js
  src/locales/help-en.js
  src/locales/help-ja-JP.js
  src/locales/help-zh-CN.js
Labels: size/XL

#6530 fix(v3.11): 磁铁展示优化,边界值处理
  containers/Dashboard/extends/Ring/components/Server.vue
Labels: size/XS

#6531 Automated cherry pick of #6530: fix(v3.11): 磁铁展示优化,边界值处理
  containers/Dashboard/extends/Ring/components/Server.vue
Labels: size/XS

#6532 Automated cherry pick of #6530: fix(v3.11): 磁铁展示优化,边界值处理
  containers/Dashboard/extends/Ring/components/Server.vue
Labels: size/XS

#6536 feat(v3.11/4787): time range filter add utc check
  src/utils/common/tableFilter.js
Labels: size/XS

#6537 Automated cherry pick of #6536: feat(v3.11/4787): time range filter add utc check
  src/utils/common/tableFilter.js
Labels: size/XS

#6538 Automated cherry pick of #6536: feat(v3.11/4787): time range filter add utc check
  src/utils/common/tableFilter.js
Labels: size/XS

#6540 Automated cherry pick of #6539: fix(v3.11/9866): 费用预测关闭时 ，费用-云账号-账单任务-新建，前端增加限制
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
Labels: size/XS

#6541 Automated cherry pick of #6539: fix(v3.11/9866): 费用预测关闭时 ，费用-云账号-账单任务-新建，前端增加限制
  containers/Cloudenv/views/billtasks/dialogs/Create.vue
Labels: size/XS

#6543 Automated cherry pick of #6542: feat(v3.11/4876): webapp certificate add status
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/webapp/sidepage/CertificateList.vue
Labels: size/M

#6544 Automated cherry pick of #6542: feat(v3.11/4876): webapp certificate add status
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/webapp/sidepage/CertificateList.vue
Labels: size/M

#6546 Automated cherry pick of #6545: feat(v3.11/4785): waf add source ips
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/waf/components/List.vue
  containers/Network/views/waf/mixins/columns.js
  containers/Network/views/waf/sidepage/Detail.vue
Labels: size/L

#6547 Automated cherry pick of #6545: feat(v3.11/4785): waf add source ips
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/router/index.js
  containers/Network/views/waf/components/List.vue
  containers/Network/views/waf/mixins/columns.js
  containers/Network/views/waf/sidepage/Detail.vue
Labels: size/L

#6549 Automated cherry pick of #6548: fix(v3.12/4774): 修复Ceph标签获取已有标签报错
  containers/Storage/views/file-system/mixins/columns.js
Labels: size/XS

#6552 feat: i18n 功能扩展
  src/locales/index.js
  src/plugins/i18n.js
Labels: size/S

#6553 fix: support host local network server_type
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/network/Create.vue
  containers/Storage/views/blockstorage/components/FormItems.vue
  containers/Storage/views/file-system/mixins/singleActions.js
  containers/Storage/views/file-system/sidepage/Detail.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#6554 feat: 优化子任务组件
  src/components/TaskDrawer/index.vue
  src/sections/SidePageManager/components/ChildrenTaskSidePage/Detail.vue
  src/sections/SidePageManager/components/ChildrenTaskSidePage/index.vue
  src/sections/SidePageManager/components/TaskSidePage/Detail.vue
  src/sections/SidePageManager/components/TaskSidePage/index.vue
  src/sections/TaskList/index.vue
  src/utils/common/tableColumn.js
Labels: size/L

#6558 feat: 调整任务组件参数
  src/components/TaskDrawer/index.vue
  src/sections/TaskList/index.vue
Labels: size/XS

#6555 feat(v3.11): 优化图表tooltip位置展示
  src/components/BaseSidePage/index.vue
  src/utils/echart.js
Labels: size/S

#6556 Automated cherry pick of #6555: feat(v3.11): 优化图表tooltip位置展示
  src/components/BaseSidePage/index.vue
  src/utils/echart.js
Labels: size/S

#6557 Automated cherry pick of #6555: feat(v3.11): 优化图表tooltip位置展示
  src/components/BaseSidePage/index.vue
  src/utils/echart.js
Labels: size/S

#6559 feat(v3.11/4772): add open image market
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/image-import-ce/index.vue
  containers/Compute/views/image/image-import-ce/openimages.yaml
Labels: size/XL

#6560 Automated cherry pick of #6559: feat(v3.11/4772): add open image market
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/image-import-ce/index.vue
  containers/Compute/views/image/image-import-ce/openimages.yaml
Labels: size/XL

#6561 Automated cherry pick of #6559: feat(v3.11/4772): add open image market
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/image-import-ce/index.vue
  containers/Compute/views/image/image-import-ce/openimages.yaml
Labels: size/XL

#6563 feat(v3.11): expand distinct field method
  src/utils/common/tableFilter.js
  src/utils/list.js
Labels: size/M

#6564 Automated cherry pick of #6563: feat(v3.11): expand distinct field method
  src/utils/common/tableFilter.js
  src/utils/list.js
Labels: size/M

#6565 Automated cherry pick of #6563: feat(v3.11): expand distinct field method
  src/utils/common/tableFilter.js
  src/utils/list.js
Labels: size/M

#6568 fix(v3.10/9857): fetch users domain param error
  containers/IAM/views/contact/dialogs/Create.vue
Labels: size/XS

#6569 Automated cherry pick of #6568: fix(v3.10/9857): fetch users domain param error
  containers/IAM/views/contact/dialogs/Create.vue
Labels: size/XS

#6571 Automated cherry pick of #6568: fix(v3.10/9857): fetch users domain param error
  containers/IAM/views/contact/dialogs/Create.vue
Labels: size/XS

#6570 Automated cherry pick of #6568: fix(v3.10/9857): fetch users domain param error
  containers/IAM/views/contact/dialogs/Create.vue
Labels: size/XS

#6572 fix(v3.10/9857): fetch users domain param error
  containers/IAM/views/contact/dialogs/Create.vue
Labels: size/S

#6573 Automated cherry pick of #6572: fix(v3.10/9857): fetch users domain param error
  containers/IAM/views/contact/dialogs/Create.vue
Labels: size/S

#6574 Automated cherry pick of #6572: fix(v3.10/9857): fetch users domain param error
  containers/IAM/views/contact/dialogs/Create.vue
Labels: size/S

#6575 Automated cherry pick of #6572: fix(v3.10/9857): fetch users domain param error
  containers/IAM/views/contact/dialogs/Create.vue
Labels: size/S

#6576 fix(v3.11/9895): export list data add ignore format columns
  src/sections/DialogManager/components/ExportListData.vue
  src/utils/xlsx.js
Labels: size/S

#6577 Automated cherry pick of #6576: fix(v3.11/9895): export list data add ignore format columns
  src/sections/DialogManager/components/ExportListData.vue
  src/utils/xlsx.js
Labels: size/S

#6578 Automated cherry pick of #6576: fix(v3.11/9895): export list data add ignore format columns
  src/sections/DialogManager/components/ExportListData.vue
  src/utils/xlsx.js
Labels: size/S

#6581 fix: task add subtask count
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/ChildrenTaskList/index.vue
  src/sections/SidePageManager/components/TaskSidePage/Detail.vue
  src/sections/SidePageManager/components/TaskSidePage/index.vue
  src/sections/TaskList/index.vue
  src/utils/common/tableColumn.js
Labels: size/L

#6582 feat: 增加webconsole debug控制环境变量
  containers/Compute/views/pod-container/components/List.vue
  containers/Compute/views/vminstance/mixins/singleActions.js
Labels: size/XS

#6585 fix(v3.11/9884): fix ext resources service
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#6586 Automated cherry pick of #6585: fix(v3.11/9884): fix ext resources service
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#6587 Automated cherry pick of #6585: fix(v3.11/9884): fix ext resources service
  containers/IAM/views/policy/constants.js
  src/constants/permission.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#6588 feat(v3.11/4897): 社区镜像导入后返回列表
  containers/Compute/views/image/image-import-ce/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#6589 Automated cherry pick of #6588: feat(v3.11/4897): 社区镜像导入后返回列表
  containers/Compute/views/image/image-import-ce/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#6590 Automated cherry pick of #6588: feat(v3.11/4897): 社区镜像导入后返回列表
  containers/Compute/views/image/image-import-ce/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#6591 fix(v3.11/9904): open image info add build
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/image-import-ce/index.vue
Labels: size/XS

#6593 Automated cherry pick of #6591: fix(v3.11/9904): open image info add build
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/image-import-ce/index.vue
Labels: size/XS

#6594 feat(v3.10): global settings add userDefinedKeys param
  src/store/modules/globalSetting.js
Labels: size/S

#6595 Automated cherry pick of #6594: feat(v3.10): global settings add userDefinedKeys param
  src/store/modules/globalSetting.js
Labels: size/S

#6596 Automated cherry pick of #6594: feat(v3.10): global settings add userDefinedKeys param
  src/store/modules/globalSetting.js
Labels: size/S

#6597 Automated cherry pick of #6594: feat(v3.10): global settings add userDefinedKeys param
  src/store/modules/globalSetting.js
Labels: size/S

#6598 feat: page card list add title info
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  src/components/PageCardList/HorizontalCard.vue
  src/components/PageCardList/VerticalCard.vue
Labels: size/S

#6599 Automated cherry pick of #6598: feat: page card list add title info
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  src/components/PageCardList/HorizontalCard.vue
  src/components/PageCardList/VerticalCard.vue
Labels: size/S

#6600 Automated cherry pick of #6598: feat: page card list add title info
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  src/components/PageCardList/HorizontalCard.vue
  src/components/PageCardList/VerticalCard.vue
Labels: size/S

#6601 fix(9836): 新建多个容器主机报部署失败
  containers/Compute/sections/Labels/index.vue
  containers/Compute/views/vminstance-container/create/form/IDC.vue
  containers/Compute/views/vminstance-container/locales/en.json
  containers/Compute/views/vminstance-container/locales/ja-JP.json
  containers/Compute/views/vminstance-container/locales/zh-CN.json
Labels: size/M

#6602 fix(v3.11/9870): 全局强制删除增加提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/dialogs/Delete.vue
Labels: size/S

#6603 Automated cherry pick of #6602: fix(v3.11/9870): 全局强制删除增加提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/dialogs/Delete.vue
Labels: size/S

#6604 Automated cherry pick of #6602: fix(v3.11/9870): 全局强制删除增加提示信息
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/dialogs/Delete.vue
Labels: size/S

#6605 fix(3.10/9819): 虚拟机详情页，告警策略展示有问题
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/XS

#6606 Automated cherry pick of #6605: fix(3.10/9819): 虚拟机详情页，告警策略展示有问题
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/XS

#6607 Automated cherry pick of #6605: fix(3.10/9819): 虚拟机详情页，告警策略展示有问题
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/XS

#6608 Automated cherry pick of #6605: fix(3.10/9819): 虚拟机详情页，告警策略展示有问题
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/XS

#6609 feat(v3.11/4903): project export list add user info
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/projects/components/List.vue
Labels: size/M

#6610 Automated cherry pick of #6609: feat(v3.11/4903): project export list add user info
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/projects/components/List.vue
Labels: size/M

#6611 Automated cherry pick of #6609: feat(v3.11/4903): project export list add user info
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
  containers/IAM/views/projects/components/List.vue
Labels: size/M

#6615 fix(v3.10/9907): image cache show brand error
  containers/Compute/views/image/sidepage/Cache.vue
Labels: size/S

#6616 Automated cherry pick of #6615: fix(v3.10/9907): image cache show brand error
  containers/Compute/views/image/sidepage/Cache.vue
Labels: size/S

#6617 Automated cherry pick of #6615: fix(v3.10/9907): image cache show brand error
  containers/Compute/views/image/sidepage/Cache.vue
Labels: size/S

#6618 Automated cherry pick of #6615: fix(v3.10/9907): image cache show brand error
  containers/Compute/views/image/sidepage/Cache.vue
Labels: size/S

#6619 feat(v3.11/4903): user export list add project info
  containers/IAM/views/projects/components/List.vue
  containers/IAM/views/user/components/List.vue
Labels: size/L

#6620 Automated cherry pick of #6619: feat(v3.11/4903): user export list add project info
  containers/IAM/views/projects/components/List.vue
  containers/IAM/views/user/components/List.vue
Labels: size/L
