Repository yunionio/dashboard, pull requests merged in 2024-08, with the labels that each got.

#7013 fix: 监控面板查询参数scope更正
  containers/Monitor/views/dashboard/components/index.vue
Labels: size/XS

#7010 feat: 补充远程终端操作权限
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  src/constants/permission.js
Labels: size/XS

#7011 Automated cherry pick of #7010: feat: 补充远程终端操作权限
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  src/constants/permission.js
Labels: size/XS

#7012 Automated cherry pick of #7010: feat: 补充远程终端操作权限
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  src/constants/permission.js
Labels: size/XS

#7014 Automated cherry pick of #7013: fix: 监控面板查询参数scope更正
  containers/Monitor/views/dashboard/components/index.vue
Labels: size/XS

#7015 Automated cherry pick of #7013: fix: 监控面板查询参数scope更正
  containers/Monitor/views/dashboard/components/index.vue
Labels: size/XS

#7016 Automated cherry pick of #7013: fix: 监控面板查询参数scope更正
  containers/Monitor/views/dashboard/components/index.vue
Labels: size/XS

#7017 Automated cherry pick of #7013: fix: 监控面板查询参数scope更正
  containers/Monitor/views/dashboard/components/index.vue
Labels: size/XS

#7018 Automated cherry pick of #7013: fix: 监控面板查询参数scope更正
  containers/Monitor/views/dashboard/components/index.vue
Labels: size/XS

#7019 Automated cherry pick of #7010: feat: 补充远程终端操作权限
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  src/constants/permission.js
Labels: size/XS

#7022 feat: 宿主机增加远程终端权限控制
  containers/IAM/views/policy/constants.js
Labels: size/XS

#7023 Automated cherry pick of #7022: feat: 宿主机增加远程终端权限控制
  containers/IAM/views/policy/constants.js
Labels: size/XS

#7024 Automated cherry pick of #7022: feat: 宿主机增加远程终端权限控制
  containers/IAM/views/policy/constants.js
Labels: size/XS

#7025 fix: 补充翻译文案
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7026 Automated cherry pick of #7025: fix: 补充翻译文案
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7027 Automated cherry pick of #7025: fix: 补充翻译文案
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7028 feat: 监控大屏支持设置为自定义url
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
  src/sections/Navbar/index.vue
Labels: size/XS

#7029 Automated cherry pick of #7028: feat: 监控大屏支持设置为自定义url
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
  src/sections/Navbar/index.vue
Labels: size/XS

#7030 Automated cherry pick of #7028: feat: 监控大屏支持设置为自定义url
  containers/IAM/locales/en.json
  containers/IAM/locales/ja-JP.json
  containers/IAM/locales/zh-CN.json
  src/sections/Navbar/index.vue
Labels: size/XS

#7031 fix: 新建wmware云账号,去除cloudregion对compute_engine_brands参数的检查
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
Labels: size/XS

#7034 Automated cherry pick of #7031: fix: 新建wmware云账号,去除cloudregion对compute_engine_brands参数的检查
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
Labels: size/XS

#7032 Automated cherry pick of #7031: fix: 新建wmware云账号,去除cloudregion对compute_engine_brands参数的检查
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
Labels: size/XS

#7033 Automated cherry pick of #7031: fix: 新建wmware云账号,去除cloudregion对compute_engine_brands参数的检查
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
Labels: size/XS

#7035 fix: copy web-console files by dockerfile
  Dockerfile
Labels: size/XS

#7040 Automated cherry pick of #7021: 列表请求优化,合并资源总数请求
  containers/Compute/views/baremetal/components/List.vue
  containers/Compute/views/baremetal/index.vue
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/index.vue
  containers/Compute/views/host-image/components/List.vue
  containers/Compute/views/host-image/index.vue
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/index.vue
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/index.vue
  containers/Compute/views/physicalmachine/components/List.vue
  containers/Compute/views/physicalmachine/index.vue
  containers/Compute/views/snapshot-instance/components/List.vue
  containers/Compute/views/snapshot-instance/index.vue
  containers/Compute/views/snapshot/components/List.vue
  containers/Compute/views/snapshot/index.vue
  containers/Compute/views/vminstance-container/components/List.vue
  containers/Compute/views/vminstance-container/index.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/index.vue
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/mongodb/index.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/index.vue
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/index.vue
  containers/Network/views/cdn/components/List.vue
  containers/Network/views/cdn/index.vue
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/index.vue
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/index.vue
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/index.vue
  containers/Network/views/vpc/components/List.vue
  containers/Network/views/vpc/index.vue
  containers/Network/views/wire/components/List.vue
  containers/Network/views/wire/index.vue
  containers/Storage/views/bucket/components/List.vue
  containers/Storage/views/bucket/index.vue
  src/mixins/list.js
  src/mixins/resStatisticsV2Mixin.js
  src/permission.js
  src/utils/list.js
Labels: size/L

#7041 Automated cherry pick of #7021: 列表请求优化,合并资源总数请求
  containers/Compute/views/baremetal/components/List.vue
  containers/Compute/views/baremetal/index.vue
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/index.vue
  containers/Compute/views/host-image/components/List.vue
  containers/Compute/views/host-image/index.vue
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/index.vue
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/index.vue
  containers/Compute/views/physicalmachine/components/List.vue
  containers/Compute/views/physicalmachine/index.vue
  containers/Compute/views/snapshot-instance/components/List.vue
  containers/Compute/views/snapshot-instance/index.vue
  containers/Compute/views/snapshot/components/List.vue
  containers/Compute/views/snapshot/index.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/index.vue
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/mongodb/index.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/index.vue
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/index.vue
  containers/Network/views/cdn/components/List.vue
  containers/Network/views/cdn/index.vue
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/index.vue
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/index.vue
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/index.vue
  containers/Network/views/vpc/components/List.vue
  containers/Network/views/vpc/index.vue
  containers/Network/views/wire/components/List.vue
  containers/Network/views/wire/index.vue
  containers/Storage/views/bucket/components/List.vue
  containers/Storage/views/bucket/index.vue
  src/mixins/list.js
  src/mixins/resStatisticsV2Mixin.js
  src/permission.js
  src/utils/list.js
Labels: size/L

#7042 Automated cherry pick of #7021: 列表请求优化,合并资源总数请求
  containers/Compute/views/baremetal/components/List.vue
  containers/Compute/views/baremetal/index.vue
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/disk/index.vue
  containers/Compute/views/host-image/components/List.vue
  containers/Compute/views/host-image/index.vue
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/index.vue
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/index.vue
  containers/Compute/views/physicalmachine/components/List.vue
  containers/Compute/views/physicalmachine/index.vue
  containers/Compute/views/snapshot-instance/components/List.vue
  containers/Compute/views/snapshot-instance/index.vue
  containers/Compute/views/snapshot/components/List.vue
  containers/Compute/views/snapshot/index.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/index.vue
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/mongodb/index.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/index.vue
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/index.vue
  containers/Network/views/cdn/components/List.vue
  containers/Network/views/cdn/index.vue
  containers/Network/views/eip/components/List.vue
  containers/Network/views/eip/index.vue
  containers/Network/views/lb/components/List.vue
  containers/Network/views/lb/index.vue
  containers/Network/views/network/components/List.vue
  containers/Network/views/network/index.vue
  containers/Network/views/vpc/components/List.vue
  containers/Network/views/vpc/index.vue
  containers/Network/views/wire/components/List.vue
  containers/Network/views/wire/index.vue
  containers/Storage/views/bucket/components/List.vue
  containers/Storage/views/bucket/index.vue
  src/mixins/list.js
  src/mixins/resStatisticsV2Mixin.js
  src/permission.js
  src/utils/list.js
Labels: size/L

#7043 Automated cherry pick of #7036: feat: 列表请求分页渲染
  src/utils/list.js
Labels: size/M

#7044 Automated cherry pick of #7036: feat: 列表请求分页渲染
  src/utils/list.js
Labels: size/M

#7045 Automated cherry pick of #7036: feat: 列表请求分页渲染
  src/utils/list.js
Labels: size/M

#7046 Automated cherry pick of #7036: feat: 列表请求分页渲染
  src/utils/list.js
Labels: size/M

#7047 Automated cherry pick of #7037: feat: 列表加载优化
  src/utils/list.js
Labels: size/XS

#7048 Automated cherry pick of #7037: feat: 列表加载优化
  src/utils/list.js
Labels: size/XS

#7049 Automated cherry pick of #7037: feat: 列表加载优化
  src/utils/list.js
Labels: size/XS

#7050 Automated cherry pick of #7037: feat: 列表加载优化
  src/utils/list.js
Labels: size/XS

#7051 Automated cherry pick of #7038: feat: 列表加载优化
  src/utils/list.js
Labels: size/XS

#7052 Automated cherry pick of #7038: feat: 列表加载优化
  src/utils/list.js
Labels: size/XS

#7053 Automated cherry pick of #7038: feat: 列表加载优化
  src/utils/list.js
Labels: size/XS

#7054 Automated cherry pick of #7038: feat: 列表加载优化
  src/utils/list.js
Labels: size/XS

#7055 fix: 宿主机透传设备列表展示优化
  containers/Compute/views/gpu/components/List.vue
Labels: size/XS

#7056 Automated cherry pick of #7055: fix: 宿主机透传设备列表展示优化
  containers/Compute/views/gpu/components/List.vue
Labels: size/XS

#7057 Automated cherry pick of #7055: fix: 宿主机透传设备列表展示优化
  containers/Compute/views/gpu/components/List.vue
Labels: size/XS

#7058 Automated cherry pick of #7055: fix: 宿主机透传设备列表展示优化
  containers/Compute/views/gpu/components/List.vue
Labels: size/XS

#7064 Automated cherry pick of #7061: feat: 列表扩展标签展示优化
  src/components/PageList/components/Table.vue
Labels: size/XS

#7065 fix: container host sync status
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/vminstance-container/constants/actions.js
Labels: size/S

#7071 Automated cherry pick of #7070: fix: 修复对字符串数组排序,数字未按预期排序问题
  src/utils/utils.js
Labels: size/XS

#7072 Automated cherry pick of #7070: fix: 修复对字符串数组排序,数字未按预期排序问题
  src/utils/utils.js
Labels: size/XS

#7073 feat: 列表优化,列表刷新清空列表数据时,同时清空附带信息
  src/mixins/resStatisticsMixin.js
  src/mixins/resStatisticsV2Mixin.js
  src/utils/list.js
Labels: size/S

#7074 Automated cherry pick of #7073: feat: 列表优化,列表刷新清空列表数据时,同时清空附带信息
  src/mixins/resStatisticsMixin.js
  src/mixins/resStatisticsV2Mixin.js
  src/utils/list.js
Labels: size/S

#7075 Automated cherry pick of #7073: feat: 列表优化,列表刷新清空列表数据时,同时清空附带信息
  src/mixins/resStatisticsMixin.js
  src/mixins/resStatisticsV2Mixin.js
  src/utils/list.js
Labels: size/S

#7077 feat: 字典增加原始值以供使用
  src/App.vue
  src/locales/en.json
  src/locales/index.js
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7078 Automated cherry pick of #7077: feat: 字典增加原始值以供使用
  src/App.vue
  src/locales/en.json
  src/locales/index.js
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7079 Automated cherry pick of #7077: feat: 字典增加原始值以供使用
  src/App.vue
  src/locales/en.json
  src/locales/index.js
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7080 fix: dns解析设置共享去除三级权限是否开启的检查
  containers/Network/views/dns-zone/mixins/singleActions.js
  src/locales/index.js
  src/utils/common/tableActions.js
Labels: size/S

#7081 Automated cherry pick of #7080: fix: dns解析设置共享去除三级权限是否开启的检查
  containers/Network/views/dns-zone/mixins/singleActions.js
  src/locales/index.js
  src/utils/common/tableActions.js
Labels: size/S

#7082 Automated cherry pick of #7080: fix: dns解析设置共享去除三级权限是否开启的检查
  containers/Network/views/dns-zone/mixins/singleActions.js
  src/locales/index.js
  src/utils/common/tableActions.js
Labels: size/S

#7084 fix(monitor): list and show alerting status
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/XS

#7085 Automated cherry pick of #7084: fix(monitor): list and show alerting status
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/XS

#7086 Automated cherry pick of #7084: fix(monitor): list and show alerting status
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/XS

#7087 Automated cherry pick of #7084: fix(monitor): list and show alerting status
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/XS

#7088 feat: 大屏使用率磁贴支持跳转资源
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/vminstance-container/create/index.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Dashboard/constants/index.js
  containers/Dashboard/extends/Ring/components/K8s.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/sections/K8sConfig/index.vue
  containers/K8S/views/cluster/components/List.vue
  containers/K8S/views/nodes/components/List.vue
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/eip/components/List.vue
  src/utils/common/tableFilter.js
Labels: size/L

#7089 Automated cherry pick of #7088: feat: 大屏使用率磁贴支持跳转资源
  containers/Compute/views/disk/components/List.vue
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/vminstance-container/create/index.vue
  containers/Compute/views/vminstance/components/List.vue
  containers/Dashboard/constants/index.js
  containers/Dashboard/extends/Ring/components/K8s.vue
  containers/Dashboard/extends/Ring/components/Server.vue
  containers/Dashboard/sections/K8sConfig/index.vue
  containers/K8S/views/cluster/components/List.vue
  containers/K8S/views/nodes/components/List.vue
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/eip/components/List.vue
  src/utils/common/tableFilter.js
Labels: size/L

#7091 feat: 监控查询支持结果聚合函数
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/ExplorerForm/form.vue
  containers/Monitor/sections/ExplorerForm/index.vue
  containers/Monitor/sections/MonitorLine/index.vue
  containers/Monitor/views/dashboard/create/index.vue
  containers/Monitor/views/explorer/components/index.vue
Labels: size/L

#7092 Automated cherry pick of #7091: feat: 监控查询支持结果聚合函数
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/ExplorerForm/form.vue
  containers/Monitor/sections/ExplorerForm/index.vue
  containers/Monitor/sections/MonitorLine/index.vue
  containers/Monitor/views/dashboard/create/index.vue
  containers/Monitor/views/explorer/components/index.vue
Labels: size/L

#7093 Automated cherry pick of #7091: feat: 监控查询支持结果聚合函数
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/ExplorerForm/form.vue
  containers/Monitor/sections/ExplorerForm/index.vue
  containers/Monitor/sections/MonitorLine/index.vue
  containers/Monitor/views/dashboard/create/index.vue
  containers/Monitor/views/explorer/components/index.vue
Labels: size/L

#7097 fix(host): checkMac when isPxeSingleAdd
  containers/Compute/views/physicalmachine/add/index.vue
Labels: size/XS

#7039 Automated cherry pick of #7035: fix: copy web-console files by dockerfile
  Dockerfile
Labels: size/XS

#7102 Automated cherry pick of #7100: feat: 监控查询增加 p95/p50 和时间粒度
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/sections/chart/common.js
  containers/Monitor/components/MonitorCard/sections/chart/line.vue
  containers/Monitor/sections/ExplorerForm/form.vue
  containers/Monitor/sections/MonitorLine/index.vue
  containers/Monitor/views/dashboard/create/index.vue
  containers/Monitor/views/explorer/components/index.vue
  src/sections/Monitor/Header.vue
Labels: size/L
