Repository yunionio/dashboard, pull requests merged in 2024-09, with the labels that each got.

#7106 feat(v3.11): 监控面板图表与监控查询统一
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/DashboardCards/index.vue
  containers/Monitor/sections/MonitorLine/index.vue
  containers/Monitor/views/explorer/components/index.vue
  src/sections/Monitor/Header.vue
Labels: size/L

#7107 Automated cherry pick of #7106: feat(v3.11): 监控面板图表与监控查询统一
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/DashboardCards/index.vue
  containers/Monitor/sections/MonitorLine/index.vue
  containers/Monitor/views/explorer/components/index.vue
  src/sections/Monitor/Header.vue
Labels: size/L

#7108 Automated cherry pick of #7106: feat(v3.11): 监控面板图表与监控查询统一
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/DashboardCards/index.vue
  containers/Monitor/sections/MonitorLine/index.vue
  containers/Monitor/views/explorer/components/index.vue
  src/sections/Monitor/Header.vue
Labels: size/L

#7103 fix: more host details
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/sidepage/Detail.vue
Labels: size/L

#7104 Automated cherry pick of #7103: fix: more host details
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/sidepage/Detail.vue
Labels: size/L

#7105 Automated cherry pick of #7103: fix: more host details
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/sidepage/Detail.vue
Labels: size/L

#7112 fix: 域过滤由domain字段改为project_domain
  containers/K8S/views/cluster/components/List.vue
  containers/K8S/views/nodes/components/List.vue
  containers/Network/views/waf/components/List.vue
Labels: size/S

#7114 Automated cherry pick of #7112: fix: 域过滤由domain字段改为project_domain
  containers/K8S/views/cluster/components/List.vue
  containers/K8S/views/nodes/components/List.vue
  containers/Network/views/waf/components/List.vue
Labels: size/S

#7113 Automated cherry pick of #7112: fix: 域过滤由domain字段改为project_domain
  containers/K8S/views/cluster/components/List.vue
  containers/K8S/views/nodes/components/List.vue
  containers/Network/views/waf/components/List.vue
Labels: size/S

#7111 Automated cherry pick of #7109: feat(v3.11): ckuster select add name filter
  containers/K8S/sections/ClusterSelect/index.vue
Labels: size/XS

#7110 Automated cherry pick of #7109: feat(v3.11): ckuster select add name filter
  containers/K8S/sections/ClusterSelect/index.vue
Labels: size/XS

#7116 Automated cherry pick of #7115: feat(v3.11): 补充监控面板时间选择自定义选项
  containers/Monitor/components/MonitorCard/DashboardCards/index.vue
Labels: size/XS

#7117 Automated cherry pick of #7115: feat(v3.11): 补充监控面板时间选择自定义选项
  containers/Monitor/components/MonitorCard/DashboardCards/index.vue
Labels: size/XS

#7119 Automated cherry pick of #7118: feat(v3.11): 监控面板图表与监控查询统一
  containers/Monitor/sections/MonitorLine/index.vue
Labels: size/XS

#7120 Automated cherry pick of #7118: feat(v3.11): 监控面板图表与监控查询统一
  containers/Monitor/sections/MonitorLine/index.vue
Labels: size/XS

#7121 feat: 组件扩展
  src/components/BaseChart/index.vue
  src/utils/echart.js
Labels: size/M

#7122 Automated cherry pick of #7121: feat: 组件扩展
  src/components/BaseChart/index.vue
  src/utils/echart.js
Labels: size/M

#7123 Automated cherry pick of #7121: feat: 组件扩展
  src/components/BaseChart/index.vue
  src/utils/echart.js
Labels: size/M

#7124 feat(v3.11): mfa 认证工具推荐使用宁盾令牌
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/Auth/BindSecret.vue
  src/sections/Auth/assets/nington-qrcode-android.png
  src/sections/Auth/assets/nington-qrcode-ios.png
Labels: size/M

#7125 Automated cherry pick of #7124: feat(v3.11): mfa 认证工具推荐使用宁盾令牌
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/Auth/BindSecret.vue
  src/sections/Auth/assets/nington-qrcode-android.png
  src/sections/Auth/assets/nington-qrcode-ios.png
Labels: size/M

#7126 Automated cherry pick of #7124: feat(v3.11): mfa 认证工具推荐使用宁盾令牌
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/Auth/BindSecret.vue
  src/sections/Auth/assets/nington-qrcode-android.png
  src/sections/Auth/assets/nington-qrcode-ios.png
Labels: size/M

#7127 feat(v3.11): mfa认证优化
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/Auth/BindSecret.vue
Labels: size/S

#7128 Automated cherry pick of #7127: feat(v3.11): mfa认证优化
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/Auth/BindSecret.vue
Labels: size/S

#7130 feat(v3.11): 增加外部数据图标
  src/components/Icon/assets/menu-extdb.svg
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7131 Automated cherry pick of #7130: feat(v3.11): 增加外部数据图标
  src/components/Icon/assets/menu-extdb.svg
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7132 Automated cherry pick of #7130: feat(v3.11): 增加外部数据图标
  src/components/Icon/assets/menu-extdb.svg
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7133 fix: 离线下载参数为数组时解析错误
  src/components/Icon/assets/res-offline-export.svg
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/S

#7135 fix(container): add scope parameter in query when viewing log
  containers/Compute/views/pod-container/sidepage/Log.vue
Labels: size/XS

#7136 feat(v3.11): 云账号支持克隆
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/BlockedResources.vue
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/components/ProxySetting.vue
  containers/Cloudenv/views/cloudaccount/components/ReadOnly.vue
  containers/Cloudenv/views/cloudaccount/components/ShareMode.vue
  containers/Cloudenv/views/cloudaccount/components/SkipDuplicateAccountCheck.vue
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/BaiduCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/BingoCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/CephFS.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/ChinaUnion.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/H3C.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCS.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/InCloudSphere.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ksyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Nutanix.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OracleCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Proxmox.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qingcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/RemoteFile.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/S3CephXsky.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Sangfor.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VolcEngine.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/create/index.vue
  containers/Cloudenv/views/cloudaccount/dialogs/UpdateProxySetting.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XXL

#7137 Automated cherry pick of #7136: feat(v3.11): 云账号支持克隆
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/BlockedResources.vue
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/components/ProxySetting.vue
  containers/Cloudenv/views/cloudaccount/components/ReadOnly.vue
  containers/Cloudenv/views/cloudaccount/components/ShareMode.vue
  containers/Cloudenv/views/cloudaccount/components/SkipDuplicateAccountCheck.vue
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/BaiduCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/BingoCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/CephFS.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/ChinaUnion.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/H3C.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCS.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/InCloudSphere.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ksyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Nutanix.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OracleCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Proxmox.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qingcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/RemoteFile.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/S3CephXsky.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Sangfor.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VolcEngine.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/create/index.vue
  containers/Cloudenv/views/cloudaccount/dialogs/UpdateProxySetting.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XXL

#7138 Automated cherry pick of #7136: feat(v3.11): 云账号支持克隆
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/cloudaccount/components/BlockedResources.vue
  containers/Cloudenv/views/cloudaccount/components/DomainProject.vue
  containers/Cloudenv/views/cloudaccount/components/ProxySetting.vue
  containers/Cloudenv/views/cloudaccount/components/ReadOnly.vue
  containers/Cloudenv/views/cloudaccount/components/ShareMode.vue
  containers/Cloudenv/views/cloudaccount/components/SkipDuplicateAccountCheck.vue
  containers/Cloudenv/views/cloudaccount/create/form/CreateCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Aliyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Apsara.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/AwsHuawei.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Azure.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/BaiduCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/BingoCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/ChinaUnion.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Cloudpods.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Google.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/H3C.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCS.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/HCSO.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/InCloudSphere.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ksyun.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Nutanix.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OpenstackZstack.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/OracleCloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Proxmox.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Qingcloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/RemoteFile.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/S3CephXsky.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/Ucloud.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VMware.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/VolcEngine.vue
  containers/Cloudenv/views/cloudaccount/create/form/components/createMixin.js
  containers/Cloudenv/views/cloudaccount/create/index.vue
  containers/Cloudenv/views/cloudaccount/dialogs/UpdateProxySetting.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
Labels: size/XXL

#7139 feat(v3.11): 资源监控图表切换未echart图表
  src/sections/Charts/Line.vue
  src/sections/Monitor/Header.vue
  src/sections/Monitor/List.vue
  src/sections/Monitor/index.vue
  src/utils/monitor.js
Labels: size/M

#7140 Automated cherry pick of #7139: feat(v3.11): 资源监控图表切换未echart图表
  src/sections/Charts/Line.vue
  src/sections/Monitor/Header.vue
  src/sections/Monitor/List.vue
  src/sections/Monitor/index.vue
  src/utils/monitor.js
Labels: size/M

#7141 Automated cherry pick of #7139: feat(v3.11): 资源监控图表切换未echart图表
  src/sections/Charts/Line.vue
  src/sections/Monitor/Header.vue
  src/sections/Monitor/List.vue
  src/sections/Monitor/index.vue
  src/utils/monitor.js
Labels: size/M

#7142 feat(v3.11): 告警资源增加ip展示
  containers/Monitor/views/alertresource/components/List.vue
  containers/Monitor/views/commonalert/utils/index.js
  src/utils/common/tableColumn.js
Labels: size/M

#7143 Automated cherry pick of #7142: feat(v3.11): 告警资源增加ip展示
  containers/Monitor/views/alertresource/components/List.vue
  containers/Monitor/views/commonalert/utils/index.js
  src/utils/common/tableColumn.js
Labels: size/M

#7144 Automated cherry pick of #7142: feat(v3.11): 告警资源增加ip展示
  containers/Monitor/views/alertresource/components/List.vue
  containers/Monitor/views/commonalert/utils/index.js
  src/utils/common/tableColumn.js
Labels: size/M

#7145 feat(v3.11): 告警资源增加ip展示
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/XS

#7146 Automated cherry pick of #7145: feat(v3.11): 告警资源增加ip展示
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/XS

#7147 Automated cherry pick of #7145: feat(v3.11): 告警资源增加ip展示
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/XS

#7148 feat(v3.11): 告警资源增加ip搜索
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/XS

#7149 Automated cherry pick of #7148: feat(v3.11): 告警资源增加ip搜索
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/XS

#7150 Automated cherry pick of #7148: feat(v3.11): 告警资源增加ip搜索
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/XS

#7184 feat: 堡垒机增加网域信息
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/components/BastionHost.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/dialogs/VmAddBastionHostDialog.vue
Labels: size/M

#7185 Automated cherry pick of #7184: feat: 堡垒机增加网域信息
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/components/BastionHost.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/dialogs/VmAddBastionHostDialog.vue
Labels: size/M

#7186 Automated cherry pick of #7184: feat: 堡垒机增加网域信息
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/components/BastionHost.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/dialogs/VmAddBastionHostDialog.vue
Labels: size/M

#7187 Automated cherry pick of #7184: feat: 堡垒机增加网域信息
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/components/BastionHost.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/dialogs/VmAddBastionHostDialog.vue
Labels: size/M

#7188 fix: 补充监控翻译信息
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  src/constants/monitor.js
Labels: size/M

#7189 Automated cherry pick of #7188: fix: 补充监控翻译信息
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  src/constants/monitor.js
Labels: size/M

#7190 Automated cherry pick of #7188: fix: 补充监控翻译信息
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  src/constants/monitor.js
Labels: size/M

#7191 Automated cherry pick of #7188: fix: 补充监控翻译信息
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  src/constants/monitor.js
Labels: size/M

#7192 feat: 容器主机增加网络监控指标
  containers/Compute/views/node-alert/constants.js
  containers/Compute/views/vminstance-container/constants.js
  containers/Compute/views/vminstance-container/locales/en.json
  containers/Compute/views/vminstance-container/locales/ja-JP.json
  containers/Compute/views/vminstance-container/locales/zh-CN.json
Labels: size/M

#7193 fix: 监控图表同时展示两个指标问题修复
  containers/Compute/views/vminstance-container/constants.js
  containers/Compute/views/vminstance-container/locales/en.json
  containers/Compute/views/vminstance-container/locales/ja-JP.json
  containers/Compute/views/vminstance-container/locales/zh-CN.json
  src/sections/Monitor/index.vue
  src/utils/monitor.js
Labels: size/L

#7196 fix: 监控图表数据优化
  src/sections/Charts/Line.vue
  src/sections/Monitor/index.vue
Labels: size/S

#7197 Automated cherry pick of #7196: fix: 监控图表数据优化
  src/sections/Charts/Line.vue
  src/sections/Monitor/index.vue
Labels: size/S

#7198 Automated cherry pick of #7196: fix: 监控图表数据优化
  src/sections/Charts/Line.vue
  src/sections/Monitor/index.vue
Labels: size/S

#7199 Automated cherry pick of #7196: fix: 监控图表数据优化
  src/sections/Charts/Line.vue
  src/sections/Monitor/index.vue
Labels: size/S

#7200 fix: 监控图表展示多个监控指标展示优化
  src/sections/Monitor/index.vue
Labels: size/XS

#7201 Automated cherry pick of #7200: fix: 监控图表展示多个监控指标展示优化
  src/sections/Monitor/index.vue
Labels: size/XS

#7202 Automated cherry pick of #7200: fix: 监控图表展示多个监控指标展示优化
  src/sections/Monitor/index.vue
Labels: size/XS

#7203 fix: host details revisit 20240928
  containers/Compute/views/host/sidepage/Detail.vue
Labels: size/L

#7204 Automated cherry pick of #7203: fix: host details revisit 20240928
  containers/Compute/views/host/sidepage/Detail.vue
Labels: size/L

#7205 fix: host details enable_ksm
  containers/Compute/views/host/sidepage/Detail.vue
Labels: size/XS

#7206 Automated cherry pick of #7205: fix: host details enable_ksm
  containers/Compute/views/host/sidepage/Detail.vue
Labels: size/XS
