Repository yunionio/dashboard, pull requests merged in 2024-12, with the labels that each got.

#7355 Feat/glb zettakit
  containers/Compute/sections/PCI/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/S

#7358 feat: 请求优化,合并系统初始化时对全局配置信息的请求
  src/permission.js
  src/store/modules/common.js
Labels: size/M

#7359 Automated cherry pick of #7358: feat: 请求优化,合并系统初始化时对全局配置信息的请求
  src/permission.js
  src/store/modules/common.js
Labels: size/M

#7362 feat: 宿主机补充资源统计信息
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/constants.js
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/host/sidepage/Dashboard.vue
  containers/Compute/views/host/utils/index.js
  src/permission.js
  src/store/modules/common.js
Labels: size/L

#7363 Automated cherry pick of #7362: feat: 宿主机补充资源统计信息
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/constants.js
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/host/sidepage/Dashboard.vue
  containers/Compute/views/host/utils/index.js
  src/permission.js
  src/store/modules/common.js
Labels: size/L

#7364 Automated cherry pick of #7363: feat: 宿主机补充资源统计信息
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/constants.js
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/host/sidepage/Dashboard.vue
  containers/Compute/views/host/utils/index.js
  src/permission.js
  src/store/modules/common.js
Labels: size/L

#7365 feat: 调整翻译
  containers/Compute/views/host/sidepage/Dashboard.vue
Labels: size/XS

#7366 Automated cherry pick of #7365: feat: 调整翻译
  containers/Compute/views/host/sidepage/Dashboard.vue
Labels: size/XS

#7369 feat: 请求优化,合并系统初始化时对全局配置信息的请求
  src/permission.js
  src/store/modules/common.js
Labels: size/L

#7372 feat: 补充翻译
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#7373 Automated cherry pick of #7372: feat: 补充翻译
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#7374 Automated cherry pick of #7373: feat: 补充翻译
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#7375 fix: 虚拟机调度失败时宿主机不应该再展示请求中的状态
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#7376 Automated cherry pick of #7375: fix: 虚拟机调度失败时宿主机不应该再展示请求中的状态
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#7377 Automated cherry pick of #7375: fix: 虚拟机调度失败时宿主机不应该再展示请求中的状态
  containers/Compute/views/vminstance/mixins/columns.js
Labels: size/XS

#7378 fix: allow monitor panel fold
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/DashboardCards/index.vue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/ExplorerForm/form.vue
  containers/Monitor/sections/Filters/index.vue
  containers/Monitor/sections/MonitorLine/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/Monitor/CustomDate.vue
  src/sections/Monitor/Header.vue
  src/utils/validate.js
Labels: size/L

#7380 Automated cherry pick of #7378: fix: allow monitor panel fold
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/DashboardCards/index.vue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/ExplorerForm/form.vue
  containers/Monitor/sections/Filters/index.vue
  containers/Monitor/sections/MonitorLine/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/Monitor/CustomDate.vue
  src/sections/Monitor/Header.vue
  src/utils/validate.js
Labels: size/L

#7379 Automated cherry pick of #7378: fix: allow monitor panel fold
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/DashboardCards/index.vue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/ExplorerForm/form.vue
  containers/Monitor/sections/Filters/index.vue
  containers/Monitor/sections/MonitorLine/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/Monitor/CustomDate.vue
  src/sections/Monitor/Header.vue
  src/utils/validate.js
Labels: size/L

#7381 fix: 被缓存的页面手动清除sidepage
  src/layouts/RouterView/index.vue
  src/mixins/keepAlive.js
Labels: size/XS

#7382 feat: 虚拟机数据复制中状态展示优化,增加进度条,加快请求频率
  src/components/Status/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/styles/less/global.less
  src/utils/list.js
Labels: size/M

#7383 Automated cherry pick of #7382: feat: 虚拟机数据复制中状态展示优化,增加进度条,加快请求频率
  src/components/Status/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/styles/less/global.less
  src/utils/list.js
Labels: size/M

#7384 Automated cherry pick of #7383: feat: 虚拟机数据复制中状态展示优化,增加进度条,加快请求频率
  src/components/Status/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/styles/less/global.less
  src/utils/list.js
Labels: size/M

#7386 feat: 支持loongarch64架构
  containers/Cloudenv/views/server-price-comparator/create/form/IDC.vue
  containers/Compute/views/vminstance-container/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  src/components/JsonSchemaForm/JComponents/JImageList/JImageList.vue
  src/constants/compute.js
Labels: size/M

#7387 Automated cherry pick of #7386: feat: 支持loongarch64架构
  containers/Cloudenv/views/server-price-comparator/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  src/components/JsonSchemaForm/JComponents/JImageList/JImageList.vue
  src/constants/compute.js
Labels: size/M

#7388 Automated cherry pick of #7386: feat: 支持loongarch64架构
  containers/Cloudenv/views/server-price-comparator/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  src/components/JsonSchemaForm/JComponents/JImageList/JImageList.vue
  src/constants/compute.js
Labels: size/M

#7389 feat: 授权信息控制多语言
  scope/layouts/Navbar/index.vue
  src/layouts/Auth/index.vue
Labels: size/M

#7390 Automated cherry pick of #7389: feat: 授权信息控制多语言
  scope/layouts/Navbar/index.vue
  src/layouts/Auth/index.vue
Labels: size/M

#7392 fix: 监控告警优化
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/overview/components/index.vue
Labels: size/M

#7393 Automated cherry pick of #7392: fix: 监控告警优化
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/overview/components/index.vue
Labels: size/M

#7394 Automated cherry pick of #7392: fix: 监控告警优化
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/overview/components/index.vue
Labels: size/M

#7396 feat: 选择网络展示server_type
  src/components/BaseSelect/OptionLabel.js
Labels: size/XS

#7397 Automated cherry pick of #7396: feat: 选择网络展示server_type
  src/components/BaseSelect/OptionLabel.js
Labels: size/XS

#7398 Automated cherry pick of #7396: feat: 选择网络展示server_type
  src/components/BaseSelect/OptionLabel.js
Labels: size/XS

#7399 feat: 深信服虚拟机支持重启操作
  containers/Compute/views/vminstance/utils.js
Labels: size/XS

#7400 fix: monitor minor adjustment 20241212
  containers/Compute/views/host/constants.js
  containers/Compute/views/host/sidepage/Monitor.vue
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/sections/MonitorLine/index.vue
  src/sections/Monitor/Header.vue
  src/sections/Monitor/index.vue
Labels: size/L

#7401 Automated cherry pick of #7400: fix: monitor minor adjustment 20241212
  containers/Compute/views/host/constants.js
  containers/Compute/views/host/sidepage/Monitor.vue
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/sections/MonitorLine/index.vue
  src/sections/Monitor/Header.vue
  src/sections/Monitor/index.vue
Labels: size/L

#7402 Automated cherry pick of #7400: fix: monitor minor adjustment 20241212
  containers/Compute/views/host/constants.js
  containers/Compute/views/host/sidepage/Monitor.vue
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/sections/MonitorLine/index.vue
  src/sections/Monitor/Header.vue
  src/sections/Monitor/index.vue
Labels: size/L

#7403 feat: 监控面板支持更改名称,样式展示优化
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/DashboardCards/index.vue
  containers/Monitor/components/MonitorCard/layout/index.vue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/MonitorLine/index.vue
  containers/Monitor/views/dashboard/components/index.vue
  containers/Monitor/views/dashboard/dialogs/changeName.vue
Labels: size/L

#7404 Automated cherry pick of #7403: feat: 监控面板支持更改名称,样式展示优化
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/DashboardCards/index.vue
  containers/Monitor/components/MonitorCard/layout/index.vue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/MonitorLine/index.vue
  containers/Monitor/views/dashboard/components/index.vue
  containers/Monitor/views/dashboard/dialogs/changeName.vue
Labels: size/L

#7405 Automated cherry pick of #7403: feat: 监控面板支持更改名称,样式展示优化
  containers/Monitor/components/MonitorCard/DashboardCard/index.vue
  containers/Monitor/components/MonitorCard/DashboardCards/index.vue
  containers/Monitor/components/MonitorCard/layout/index.vue
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/MonitorLine/index.vue
  containers/Monitor/views/dashboard/components/index.vue
  containers/Monitor/views/dashboard/dialogs/changeName.vue
Labels: size/L

#7407 feat: 监控优化,支持选择图表展示折线
  containers/Monitor/sections/MonitorLine/index.vue
  src/components/Icon/assets/checkbox-empty.svg
  src/components/Icon/assets/checkbox-fill.svg
Labels: size/L

#7408 Automated cherry pick of #7407: feat: 监控优化,支持选择图表展示折线
  containers/Monitor/sections/MonitorLine/index.vue
  src/components/Icon/assets/checkbox-empty.svg
  src/components/Icon/assets/checkbox-fill.svg
Labels: size/L

#7409 Automated cherry pick of #7407: feat: 监控优化,支持选择图表展示折线
  containers/Monitor/sections/MonitorLine/index.vue
  src/components/Icon/assets/checkbox-empty.svg
  src/components/Icon/assets/checkbox-fill.svg
Labels: size/L

#7410 fix: 撤销对龙芯的支持
  containers/Cloudenv/views/server-price-comparator/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  src/components/JsonSchemaForm/JComponents/JImageList/JImageList.vue
  src/constants/compute.js
Labels: size/M

#7411 fix: IP子网创建传参错误
  containers/Network/views/network/Create.vue
Labels: size/M

#7412 Automated cherry pick of #7411: fix: IP子网创建传参错误
  containers/Network/views/network/Create.vue
Labels: size/M

#7414 feat: ssh失败回填用户名密码
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/constants/actions.js
  src/sections/DialogManager/components/SshAuth.vue
Labels: size/M

#7415 Automated cherry pick of #7414: feat: ssh失败回填用户名密码
  containers/Compute/views/baremetal/mixins/singleActions.js
  containers/Compute/views/host/mixins/singleActions.js
  containers/Compute/views/physicalmachine/mixins/singleActions.js
  containers/Compute/views/vminstance/constants/actions.js
  src/sections/DialogManager/components/SshAuth.vue
Labels: size/M

#7418 fix: globalsettings更新前增加判断
  src/components/FeatureSelector/index.vue
  src/store/modules/globalSetting.js
Labels: size/XS

#7419 Automated cherry pick of #7418: fix: globalsettings更新前增加判断
  src/components/FeatureSelector/index.vue
  src/store/modules/globalSetting.js
Labels: size/XS

#7420 Automated cherry pick of #7418: fix: globalsettings更新前增加判断
  src/components/FeatureSelector/index.vue
  src/store/modules/globalSetting.js
Labels: size/XS

#7422 Automated cherry pick of #7421: feat: 监控图表选中优化,允许全部取消选中
  containers/Monitor/sections/MonitorLine/index.vue
  src/components/Icon/assets/checkbox-fill.svg
  src/components/Icon/assets/checkbox-some.svg
Labels: size/M

#7429 Automated cherry pick of #7428: feat: 主机克隆数据复制中状态展示优化
  src/components/Status/index.vue
  src/utils/common/tableColumn.js
Labels: size/XS

#7436 Automated cherry pick of #7434: feat: 火山引擎支持单独授权费用
  containers/Cloudenv/views/cloudaccount/create/form/SelectCloudaccount.vue
  containers/Cloudenv/views/cloudaccount/mixins/singleActions.js
  src/utils/auth.js
Labels: size/M

#7437 fix: 主机组翻译改为反亲和组
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
Labels: size/XS

#7442 feat: 调整宿主机资源过滤参数
  containers/Compute/views/host/mixins/columns.js
Labels: size/XS

#7443 Automated cherry pick of #7442: feat: 调整宿主机资源过滤参数
  containers/Compute/views/host/mixins/columns.js
Labels: size/XS

#7447 Automated cherry pick of #7446: feat: 云联壹云平台修改为内置虚拟化
  src/config/setting.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#7454 feat: 允许打包注入当前平台信息
  scope/views/licenses/index.vue
  src/config/setting.js
  src/main.js
  vue.config.js
Labels: size/S

#7455 Automated cherry pick of #7454: feat: 允许打包注入当前平台信息
  scope/views/licenses/index.vue
  src/config/setting.js
  src/main.js
  vue.config.js
Labels: size/S

#7456 Automated cherry pick of #7454: feat: 允许打包注入当前平台信息
  scope/views/licenses/index.vue
  src/config/setting.js
  src/main.js
  vue.config.js
Labels: size/S

#7457 Automated cherry pick of #7456: feat: 允许打包注入当前平台信息
  scope/views/licenses/index.vue
  src/config/setting.js
  src/main.js
  vue.config.js
Labels: size/S

#7458 feat: 修改宿主机和存储设置超售比api
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/dialogs/AdjustOversoldRatio.vue
  containers/Compute/views/host/mixins/singleActions.js
  containers/Storage/views/blockstorage/components/List.vue
  containers/Storage/views/blockstorage/dialogs/UpdateCommitBound.vue
  containers/Storage/views/blockstorage/mixins/singleActions.js
  src/constants/permission.js
Labels: size/S

#7459 Automated cherry pick of #7458: feat: 修改宿主机和存储设置超售比api
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/dialogs/AdjustOversoldRatio.vue
  containers/Compute/views/host/mixins/singleActions.js
  containers/Storage/views/blockstorage/components/List.vue
  containers/Storage/views/blockstorage/dialogs/UpdateCommitBound.vue
  containers/Storage/views/blockstorage/mixins/singleActions.js
  src/constants/permission.js
Labels: size/S

#7460 Automated cherry pick of #7458: feat: 修改宿主机和存储设置超售比api
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/dialogs/AdjustOversoldRatio.vue
  containers/Compute/views/host/mixins/singleActions.js
  containers/Storage/views/blockstorage/components/List.vue
  containers/Storage/views/blockstorage/dialogs/UpdateCommitBound.vue
  containers/Storage/views/blockstorage/mixins/singleActions.js
  src/constants/permission.js
Labels: size/S

#7461 Automated cherry pick of #7460: feat: 修改宿主机和存储设置超售比api
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/dialogs/AdjustOversoldRatio.vue
  containers/Compute/views/host/mixins/singleActions.js
  containers/Storage/views/blockstorage/components/List.vue
  containers/Storage/views/blockstorage/dialogs/UpdateCommitBound.vue
  containers/Storage/views/blockstorage/mixins/singleActions.js
  src/constants/permission.js
Labels: size/S

#7465 Automated cherry pick of #7464: fix: 解决监控列表选择时卡顿问题
  containers/Monitor/sections/MonitorLine/index.vue
Labels: size/M

#7468 fix: 主机数据复制中状态进度条只展示在主机列表
  containers/Compute/views/vminstance/mixins/columns.js
  src/components/Status/index.vue
  src/utils/common/tableColumn.js
Labels: size/S

#7469 Automated cherry pick of #7468: fix: 主机数据复制中状态进度条只展示在主机列表
  containers/Compute/views/vminstance/mixins/columns.js
  src/components/Status/index.vue
  src/utils/common/tableColumn.js
Labels: size/S

#7471 fix: 开源版移除管理员注册页面路由
  scope/router/routes.js
Labels: size/XS

#7472 Automated cherry pick of #7471: fix: 开源版移除管理员注册页面路由
  scope/router/routes.js
Labels: size/XS

#7473 Automated cherry pick of #7471: fix: 开源版移除管理员注册页面路由
  scope/router/routes.js
Labels: size/XS

#7474 Automated cherry pick of #7471: fix: 开源版移除管理员注册页面路由
  scope/router/routes.js
Labels: size/XS

#7476 Automated cherry pick of #7475: fix: 已经注册过管理员之后,不再展示注册页面
  src/layouts/Auth/index.vue
Labels: size/XS

#7477 Automated cherry pick of #7475: fix: 已经注册过管理员之后,不再展示注册页面
  src/layouts/Auth/index.vue
Labels: size/XS

#7478 Automated cherry pick of #7475: fix: 已经注册过管理员之后,不再展示注册页面
  src/layouts/Auth/index.vue
Labels: size/XS

#7479 fix: add icon to hide monitor metric table grid
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/host/utils/index.js
  containers/Monitor/sections/MonitorLine/index.vue
  src/components/MultipleProgress/index.vue
Labels: size/M

#7485 Automated cherry pick of #7484: fix: 硬盘更换块存储参数错误
  containers/Compute/views/disk/dialogs/ChangeBlockStorage.vue
Labels: size/XS

#7486 Automated cherry pick of #7484: fix: 硬盘更换块存储参数错误
  containers/Compute/views/disk/dialogs/ChangeBlockStorage.vue
Labels: size/XS

#7487 Automated cherry pick of #7484: fix: 硬盘更换块存储参数错误
  containers/Compute/views/disk/dialogs/ChangeBlockStorage.vue
Labels: size/XS

#7482 fix: create vpc ipv6 network
  containers/Network/views/network/Create.vue
  containers/Network/views/network/dialogs/ReversedIP.vue
  containers/Network/views/network/sidepage/Detail.vue
Labels: size/S

#7483 Automated cherry pick of #7482: fix: create vpc ipv6 network
  containers/Network/views/network/Create.vue
  containers/Network/views/network/dialogs/ReversedIP.vue
  containers/Network/views/network/sidepage/Detail.vue
Labels: size/S

#7480 Automated cherry pick of #7479: fix: add icon to hide monitor metric table grid
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/host/utils/index.js
  containers/Monitor/sections/MonitorLine/index.vue
  src/components/MultipleProgress/index.vue
Labels: size/M

#7488 fix: task list improvements
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/SidePageManager/components/.gitignore
  src/sections/TaskList/index.vue
  src/sections/TaskPage/components/List.vue
  src/sections/TaskPage/index.vue
  src/utils/list.js
Labels: size/L

#7490 fix: add more columns to isolated-devices
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/gpu/mixins/columns.js
  src/sections/SidePageManager/components/TaskSidePage/index.vue
  src/utils/common/tableColumn.js
Labels: size/L

#7491 Automated cherry pick of #7490: fix: add more columns to isolated-devices
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/gpu/components/List.vue
  containers/Compute/views/gpu/mixins/columns.js
Labels: size/L
