Repository yunionio/dashboard, pull requests merged in 2025-09, with the labels that each got.

#8368 Automated cherry pick of #8367: fix: 优化全局资源搜索
  containers/DB/views/mongodb/components/List.vue
  src/constants/globalSearch.js
Labels: size/S

#8369 Automated cherry pick of #8367: fix: 优化全局资源搜索
  containers/DB/views/mongodb/components/List.vue
  src/constants/globalSearch.js
Labels: size/S

#8371 fix: capability 接口参数使用优化
  containers/Compute/views/secgroup/sidepage/RDS.vue
  containers/Compute/views/secgroup/sidepage/Redis.vue
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/index.vue
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/index.vue
  containers/Network/views/lb/index.vue
  containers/Network/views/lbacls/components/List.vue
  containers/Network/views/lbcerts/components/List.vue
  containers/Network/views/wire/index.vue
Labels: size/S

#8373 Automated cherry pick of #8371: fix: capability 接口参数使用优化
  containers/Compute/views/secgroup/sidepage/RDS.vue
  containers/Compute/views/secgroup/sidepage/Redis.vue
  containers/DB/views/mongodb/components/List.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/index.vue
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/index.vue
  containers/Network/views/lb/index.vue
  containers/Network/views/lbacls/components/List.vue
  containers/Network/views/lbcerts/components/List.vue
  containers/Network/views/wire/index.vue
Labels: size/S

#8375 fix: network details show ipv6 usage
  containers/Network/views/network/mixins/columns.js
  containers/Network/views/network/sidepage/Detail.vue
Labels: size/XS

#8377 Automated cherry pick of #8375: fix: network details show ipv6 usage
  containers/Network/views/network/mixins/columns.js
  containers/Network/views/network/sidepage/Detail.vue
Labels: size/XS

#8379 fix: mongodb 平台过滤参数
  containers/DB/views/mongodb/components/List.vue
Labels: size/XS

#8382 Automated cherry pick of #8379: fix: mongodb 平台过滤参数
  containers/DB/views/mongodb/components/List.vue
Labels: size/XS

#8383 feat: 扩展status自定义方式
  src/components/Icon/assets/menu-game.svg
  src/components/Status/index.vue
  src/constants/expectStatus.js
  src/mixins/resStatisticsV2Mixin.js
  src/utils/common/tableFilter.js
Labels: size/M

#8385 Automated cherry pick of #8383: feat: 扩展status自定义方式
  src/components/Icon/assets/menu-game.svg
  src/components/Status/index.vue
  src/constants/expectStatus.js
  src/mixins/resStatisticsV2Mixin.js
  src/utils/common/tableFilter.js
Labels: size/M

#8386 fix: fix conflict
  src/constants/expectStatus.js
Labels: size/XS

#8387 Automated cherry pick of #8386: fix: fix conflict
  src/constants/expectStatus.js
Labels: size/XS

#8392 feat: 秘钥支持ED25519/ECDSA格式
  containers/Compute/views/keypair/dialogs/Create.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/S

#8395 Automated cherry pick of #8392: feat: 秘钥支持ED25519/ECDSA格式
  containers/Compute/views/keypair/dialogs/Create.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/validate.js
Labels: size/S

#8397 Automated cherry pick of #8396: feat: 虚拟机调整配置套餐使用架构过滤
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#8398 Automated cherry pick of #8396: feat: 虚拟机调整配置套餐使用架构过滤
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#8399 Automated cherry pick of #8396: feat: 虚拟机调整配置套餐使用架构过滤
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS

#8400 feat: capability参数优化
  containers/Compute/views/secgroup/sidepage/RDS.vue
  containers/Compute/views/secgroup/sidepage/Redis.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/index.vue
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/index.vue
  containers/Network/views/lb/index.vue
  containers/Network/views/lbacls/components/List.vue
  containers/Network/views/lbcerts/components/List.vue
Labels: size/S

#8403 Automated cherry pick of #8400: feat: capability参数优化
  containers/Compute/views/secgroup/sidepage/RDS.vue
  containers/Compute/views/secgroup/sidepage/Redis.vue
  containers/DB/views/rds/components/List.vue
  containers/DB/views/rds/index.vue
  containers/DB/views/redis/components/List.vue
  containers/DB/views/redis/index.vue
  containers/Network/views/lb/index.vue
  containers/Network/views/lbacls/components/List.vue
  containers/Network/views/lbcerts/components/List.vue
Labels: size/S

#8407 Automated cherry pick of #8405: fix: 修复 虚拟机详情操作日志丢失问题
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/S

#8408 Automated cherry pick of #8405: fix: 修复 虚拟机详情操作日志丢失问题
  containers/Compute/views/vminstance/sidepage/index.vue
Labels: size/S

#8409 fix: 虚拟机调整配置套餐使用架构过滤
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/S

#8410 Automated cherry pick of #8409: fix: 虚拟机调整配置套餐使用架构过滤
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/S

#8412 Automated cherry pick of #8409: fix: 虚拟机调整配置套餐使用架构过滤
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/S

#8413 feat: google增加磁盘类型
  containers/Compute/constants/index.js
  src/constants/compute.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#8414 Automated cherry pick of #8413: feat: google增加磁盘类型
  containers/Compute/constants/index.js
  src/constants/compute.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#8418 Automated cherry pick of #8417: fix: 监控总览展示优化
  containers/Dashboard/extends/Top5/index.vue
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/M

#8419 Automated cherry pick of #8417: fix: 监控总览展示优化
  containers/Dashboard/extends/Top5/index.vue
  containers/Monitor/components/MonitorCard/OverviewCard/filterForm.vue
Labels: size/M

#8422 Automated cherry pick of #8421: fix: 监控图y轴数值展示优化
  containers/Monitor/sections/MonitorLine/index.vue
Labels: size/XS

#8439 Automated cherry pick of #8438: fix: 修复 虚拟机加入堡垒机传参
  containers/Compute/views/vminstance/dialogs/AddBastion.vue
Labels: size/XS

#8441 Automated cherry pick of #8438: fix: 修复 虚拟机加入堡垒机传参
  containers/Compute/views/vminstance/dialogs/AddBastion.vue
Labels: size/XS

#8446 Automated cherry pick of #8445: feat: 工单支持修改
  containers/Compute/constants/index.js
  containers/Compute/sections/Backup/index.vue
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/sections/EipConfig/index.vue
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/sections/SKU/index.vue
  containers/Compute/sections/SchedPolicy/PolicySchedtag.vue
  containers/Compute/sections/SchedPolicy/index.vue
  containers/Compute/sections/SecgroupConfig/index.vue
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/sections/ServerNetwork/NetworkSchedtag.vue
  containers/Compute/sections/ServerNetwork/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/baremetal/create/BottomBar.vue
  containers/Compute/views/baremetal/create/IDC.vue
  containers/Compute/views/baremetal/create/Private.vue
  containers/Compute/views/baremetal/create/index.vue
  containers/Compute/views/baremetal/create/mixins.js
  containers/Compute/views/disk-backup/components/List.vue
  containers/Compute/views/vminstance-container/create/components/BottomBar.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BastionHost.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Compute/views/vminstance/create/components/CustomData.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/create/index.vue
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
  containers/Compute/views/vminstance/dialogs/Restart.vue
  containers/Compute/views/vminstance/dialogs/ShutDown.vue
  containers/Compute/views/vminstance/dialogs/Start.vue
  src/constants/compute.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/mixins/workflow.js
  src/sections/CloudregionZone/index.vue
  src/sections/DialogManager/components/ApplyDomainQuota.vue
  src/sections/DialogManager/components/ApplyJoinProject.vue
  src/sections/DomainProject/index.vue
Labels: size/XXL

#8447 Automated cherry pick of #8445: feat: 工单支持修改
  containers/Compute/constants/index.js
  containers/Compute/sections/Backup/index.vue
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/sections/EipConfig/index.vue
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/sections/SKU/index.vue
  containers/Compute/sections/SchedPolicy/PolicySchedtag.vue
  containers/Compute/sections/SchedPolicy/index.vue
  containers/Compute/sections/SecgroupConfig/index.vue
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/sections/ServerNetwork/NetworkSchedtag.vue
  containers/Compute/sections/ServerNetwork/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/baremetal/create/BottomBar.vue
  containers/Compute/views/baremetal/create/IDC.vue
  containers/Compute/views/baremetal/create/Private.vue
  containers/Compute/views/baremetal/create/index.vue
  containers/Compute/views/baremetal/create/mixins.js
  containers/Compute/views/disk-backup/components/List.vue
  containers/Compute/views/vminstance-container/create/components/BottomBar.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/create/components/BastionHost.vue
  containers/Compute/views/vminstance/create/components/BottomBar.vue
  containers/Compute/views/vminstance/create/components/CustomData.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/mixin.js
  containers/Compute/views/vminstance/create/index.vue
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
  containers/Compute/views/vminstance/dialogs/Restart.vue
  containers/Compute/views/vminstance/dialogs/ShutDown.vue
  containers/Compute/views/vminstance/dialogs/Start.vue
  src/constants/compute.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/mixins/workflow.js
  src/sections/CloudregionZone/index.vue
  src/sections/DialogManager/components/ApplyDomainQuota.vue
  src/sections/DialogManager/components/ApplyJoinProject.vue
  src/sections/DomainProject/index.vue
Labels: size/XXL

#8449 feat: 工单支持修改
  containers/Compute/sections/ServerNetwork/NetworkConfig.vue
  containers/Compute/views/baremetal/create/index.vue
Labels: size/L

#8450 feat: 裸金属规格必填限制
  containers/Compute/views/baremetal/create/mixins.js
Labels: size/XS

#8451 Automated cherry pick of #8450: feat: 裸金属规格必填限制
  containers/Compute/views/baremetal/create/mixins.js
Labels: size/XS

#8452 Automated cherry pick of #8450: feat: 裸金属规格必填限制
  containers/Compute/views/baremetal/create/mixins.js
Labels: size/XS

#8459 Automated cherry pick of #8458: fix: 告警策略告警机器人使用项目过滤
  containers/Monitor/views/commonalert/components/alert/form/index.vue
  containers/Monitor/views/commonalert/components/new-alert/form/index.vue
  src/sections/NotifyTypes/index.vue
Labels: size/S

#8463 Automated cherry pick of #8462: feat: 虚拟机panicked 展示截图
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/EventLog.vue
Labels: size/L

#8466 Automated cherry pick of #8462: feat: 虚拟机panicked 展示截图
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/DialogManager/components/EventLog.vue
Labels: size/L

#8468 Automated cherry pick of #8467: feat: 修改工单虚拟机表单回填优化
  containers/Compute/utils/createServer.js
Labels: size/XS

#8470 Automated cherry pick of #8467: feat: 修改工单虚拟机表单回填优化
  containers/Compute/utils/createServer.js
Labels: size/XS

#8473 Automated cherry pick of #8471: fix: 修复资源任务参数问题
  src/components/TaskDrawer/index.vue
  src/sections/TaskPage/index.vue
Labels: size/XS

#8477 Automated cherry pick of #8476: fix: 修复资源列表统计过滤与列表状态过滤项不统一问题
  containers/Compute/views/secgroup/dialogs/EditRules.vue
  src/mixins/resStatisticsV2Mixin.js
Labels: size/S

#8487 Automated cherry pick of #8485: feat: 操作日志展示服务类型
  src/sections/DialogManager/components/EventLog.vue
  src/sections/EventList/index.vue
Labels: size/S
