Repository yunionio/dashboard, pull requests merged in 2025-04, with the labels that each got.

#7817 Automated cherry pick of #7816: feat: 监控支持not in过滤
  containers/Monitor/sections/ExplorerForm/form.vue
  containers/Monitor/sections/Filters/index.vue
Labels: size/S

#7818 Automated cherry pick of #7816: feat: 监控支持not in过滤
  containers/Monitor/sections/ExplorerForm/form.vue
  containers/Monitor/sections/Filters/index.vue
Labels: size/S

#7820 Automated cherry pick of #7819: fix: 列表导出功能增加限制规则
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#7821 Automated cherry pick of #7819: fix: 列表导出功能增加限制规则
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#7822 Automated cherry pick of #7819: fix: 列表导出功能增加限制规则
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#7827 fix: storage uncache image not effect
  containers/Compute/views/image/dialogs/DeleteCache.vue
  containers/Storage/views/blockstorage/dialogs/UncacheImage.vue
  containers/Storage/views/blockstorage/sidepage/CachedImages.vue
Labels: size/S

#7833 feat: 列表扩展,支持月份过滤
  src/components/SearchBox/AutoCompleter.vue
  src/components/SearchBox/MonthSelect.vue
  src/components/SearchBox/Tag.vue
  src/components/SearchBox/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/utils/common/tableFilter.js
  src/utils/list.js
Labels: size/L

#7836 Automated cherry pick of #7835: feat: 列表扩展,自定义列表导出
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/XS

#7839 fix: 更正控制面板gpu指标
  src/constants/generalUsage.js
Labels: size/XS

#7840 Automated cherry pick of #7839: fix: 更正控制面板gpu指标
  src/constants/generalUsage.js
Labels: size/XS

#7849 Automated cherry pick of #7848: feat: v2v迁移支持磁盘
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/components/Storage.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/dialogs/V2vTransfer.vue
Labels: size/XL

#7850 Automated cherry pick of #7824: fix: 修复对oem版本的判断
  src/config/setting.js
Labels: size/XS

#7851 Automated cherry pick of #7824: fix: 修复对oem版本的判断
  src/config/setting.js
Labels: size/XS

#7852 fix: 修复列表检查状态对参数值为空的参数的判断
  src/utils/list.js
Labels: size/XS

#7858 Automated cherry pick of #7856: fix: 虚拟机详情磁盘解析错误
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#7859 Automated cherry pick of #7856: fix: 虚拟机详情磁盘解析错误
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/XS

#7860 fix: 虚拟机加入堡垒机操作验证紧急模式
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/S

#7864 Automated cherry pick of #7863: feat: 补充解密算法
  src/utils/crypto.js
Labels: size/M

#7866 Automated cherry pick of #7865: feat: 全局配置输入框允许非必填字段
  src/sections/DialogManager/components/GlobalSettingUpdate.vue
Labels: size/XS

#7873 Automated cherry pick of #7872: feat: DNS解析导出增加云订阅
  containers/Network/views/dns-zone/components/List.vue
Labels: size/XS

#7876 feat: 增加图标
  src/components/Icon/assets/res-topology.svg
Labels: size/XS

#7878 Automated cherry pick of #7877: feat: 优化监控展示字段
  containers/Monitor/constants/index.js
  containers/Monitor/locales/en.json
  containers/Monitor/locales/ja-JP.json
  containers/Monitor/locales/zh-CN.json
  containers/Monitor/sections/ExplorerForm/form.vue
  containers/Monitor/sections/Filters/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#7879 feat: 堡垒机集成验证堡垒机服务是否可用
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
  containers/Compute/views/vminstance/create/form/mixin.js
Labels: size/S

#7889 fix: 修复状态翻译
  src/components/SearchBox/AutoCompleter.vue
  src/utils/common/tableFilter.js
Labels: size/S

#7890 Automated cherry pick of #7889: fix: 修复状态翻译
  src/components/SearchBox/AutoCompleter.vue
  src/utils/common/tableFilter.js
Labels: size/S
