Repository yunionio/dashboard, pull requests merged in 2025-03, with the labels that each got.

#7638 Automated cherry pick of #7637: feat: 云用户支持设置启用禁用控制台登录
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/clouduser/dialogs/SetPassword.vue
  containers/Cloudenv/views/clouduser/mixins/singleActions.js
  src/constants/permission.js
Labels: size/M

#7639 Automated cherry pick of #7637: feat: 云用户支持设置启用禁用控制台登录
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/clouduser/dialogs/SetPassword.vue
  containers/Cloudenv/views/clouduser/mixins/singleActions.js
  src/constants/permission.js
Labels: size/M

#7641 Automated cherry pick of #7640: feat: eip标识是否为静态公网IP
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/eip/utils/columns.js
Labels: size/S

#7642 Automated cherry pick of #7640: feat: eip标识是否为静态公网IP
  containers/Network/locales/en.json
  containers/Network/locales/ja-JP.json
  containers/Network/locales/zh-CN.json
  containers/Network/views/eip/utils/columns.js
Labels: size/S

#7643 fix: 补充IDP类型
  containers/IAM/views/idp/edit/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#7644 Automated cherry pick of #7643: fix: 补充IDP类型
  containers/IAM/views/idp/edit/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#7645 Automated cherry pick of #7643: fix: 补充IDP类型
  containers/IAM/views/idp/edit/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#7647 Automated cherry pick of #7646: feat: IDP类型取值优化
  containers/IAM/views/idp/constants.js
  containers/IAM/views/idp/edit/index.vue
Labels: size/S

#7648 Automated cherry pick of #7646: feat: IDP类型取值优化
  containers/IAM/views/idp/constants.js
  containers/IAM/views/idp/edit/index.vue
Labels: size/S

#7650 Automated cherry pick of #7649: feat: 监控总览支持In查询
  containers/Monitor/sections/ExplorerForm/form.vue
  containers/Monitor/sections/Filters/index.vue
Labels: size/S

#7651 Automated cherry pick of #7649: feat: 监控总览支持In查询
  containers/Monitor/sections/ExplorerForm/form.vue
  containers/Monitor/sections/Filters/index.vue
Labels: size/S

#7654 Automated cherry pick of #7652: feat: 修改翻译
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Cloudenv/views/clouduser/components/List.vue
Labels: size/M

#7656 fix: simplify some errors 20250305
  src/locales/help-en.js
  src/locales/help-ja-JP.js
  src/locales/help-zh-CN.js
  src/utils/error.js
Labels: size/M

#7658 Automated cherry pick of #7656: fix: simplify some errors 20250305
  src/locales/help-en.js
  src/locales/help-ja-JP.js
  src/locales/help-zh-CN.js
  src/utils/error.js
Labels: size/M

#7657 Automated cherry pick of #7656: fix: simplify some errors 20250305
  src/locales/help-en.js
  src/locales/help-ja-JP.js
  src/locales/help-zh-CN.js
  src/utils/error.js
Labels: size/M

#7659 fix: kvm机器选择windows镜像同时选择GPU-VGA增加限制需支持uefi
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#7660 Automated cherry pick of #7659: fix: kvm机器选择windows镜像同时选择GPU-VGA增加限制需支持uefi
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#7661 Automated cherry pick of #7659: fix: kvm机器选择windows镜像同时选择GPU-VGA增加限制需支持uefi
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/XS

#7664 Automated cherry pick of #7663: fix: windows && GPU-VGA 要求镜像支持 UEFI
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/M

#7665 Automated cherry pick of #7663: fix: windows && GPU-VGA 要求镜像支持 UEFI
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/M

#7666 Automated cherry pick of #7663: fix: windows && GPU-VGA 要求镜像支持 UEFI
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/OsSelect/ImageSelect.vue
  containers/Compute/sections/OsSelect/index.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
Labels: size/M

#7671 Automated cherry pick of #7670: feat: 本地导出支持重新生成过滤参数
  src/components/PageList/components/Header.vue
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/S

#7675 Automated cherry pick of #7674: feat: 扩展列表导出,支持自定义过滤参数
  src/sections/DialogManager/components/EventLog.vue
Labels: size/S

#7677 feat: 虚拟机监控,只有kvm默认展示agent监控
  containers/Compute/views/vminstance/sidepage/Monitor.vue
Labels: size/XS

#7678 Automated cherry pick of #7677: feat: 虚拟机监控,只有kvm默认展示agent监控
  containers/Compute/views/vminstance/sidepage/Monitor.vue
Labels: size/XS

#7679 Automated cherry pick of #7677: feat: 虚拟机监控,只有kvm默认展示agent监控
  containers/Compute/views/vminstance/sidepage/Monitor.vue
Labels: size/XS

#7681 feat: 重启重置磁盘功能只限制在kvm
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/S

#7682 Automated cherry pick of #7681: feat: 重启重置磁盘功能只限制在kvm
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/S

#7683 Automated cherry pick of #7681: feat: 重启重置磁盘功能只限制在kvm
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/S

#7684 Automated cherry pick of #7681: feat: 重启重置磁盘功能只限制在kvm
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/S

#7685 Automated cherry pick of #7681: feat: 重启重置磁盘功能只限制在kvm
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/S

#7687 Automated cherry pick of #7686: feat: 详情页扩展,增加最小宽度校验,防止打开详情框太小
  src/components/SidePageTrigger/index.vue
Labels: size/XS

#7688 Automated cherry pick of #7686: feat: 详情页扩展,增加最小宽度校验,防止打开详情框太小
  src/components/SidePageTrigger/index.vue
Labels: size/XS

#7689 feat: 资源删除扩展,支持删除前二次确认
  src/sections/DialogManager/components/DeleteRes.vue
Labels: size/XS

#7690 Automated cherry pick of #7689: feat: 资源删除扩展,支持删除前二次确认
  src/sections/DialogManager/components/DeleteRes.vue
Labels: size/XS

#7691 Automated cherry pick of #7689: feat: 资源删除扩展,支持删除前二次确认
  src/sections/DialogManager/components/DeleteRes.vue
Labels: size/XS

#7693 Automated cherry pick of #7692: feat: 增加组件SelectOrInput, 列表tabs组件优化
  src/components/PageHeader/index.vue
  src/components/SelectOrInput/index.vue
Labels: size/L

#7695 fix: 虚拟机密码获取弹框展开和收起增加setTimeout函数防止弹框位置偏移
  containers/Compute/sections/PasswordFetcher/index.vue
Labels: size/S

#7696 Automated cherry pick of #7695: fix: 虚拟机密码获取弹框展开和收起增加setTimeout函数防止弹框位置偏移
  containers/Compute/sections/PasswordFetcher/index.vue
Labels: size/S

#7699 fix: 云账号更新账单地址去除前后空格
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/M

#7701 Automated cherry pick of #7699: fix: 云账号更新账单地址去除前后空格
  containers/Cloudenv/views/cloudaccount/create/form/BigQueryBillForm.vue
  containers/Cloudenv/views/cloudaccount/create/form/BillForm.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/M

#7707 fix: remove error commit
  src/permission.js
  src/router/routes.js
Labels: size/S

#7709 Automated cherry pick of #7707: fix: remove error commit
  src/permission.js
  src/router/routes.js
Labels: size/S

#7711 feat: 移除权限可视化视图
  containers/IAM/views/policy/components/Form/index.vue
Labels: size/S

#7712 Automated cherry pick of #7711: feat: 移除权限可视化视图
  containers/IAM/views/policy/components/Form/index.vue
Labels: size/S

#7713 Automated cherry pick of #7711: feat: 移除权限可视化视图
  containers/IAM/views/policy/components/Form/index.vue
Labels: size/S

#7714 fix: 解决告警策略条件监听造成页面重复渲染至崩溃的问题
  containers/Monitor/sections/Filters/index.vue
Labels: size/S

#7715 Automated cherry pick of #7714: fix: 解决告警策略条件监听造成页面重复渲染至崩溃的问题
  containers/Monitor/sections/Filters/index.vue
Labels: size/S

#7716 Automated cherry pick of #7714: fix: 解决告警策略条件监听造成页面重复渲染至崩溃的问题
  containers/Monitor/sections/Filters/index.vue
Labels: size/S

#7717 Automated cherry pick of #7714: fix: 解决告警策略条件监听造成页面重复渲染至崩溃的问题
  containers/Monitor/sections/Filters/index.vue
Labels: size/S

#7719 feat: 控制面板资源跳转按钮增加权限校验
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/S

#7720 Automated cherry pick of #7719: feat: 控制面板资源跳转按钮增加权限校验
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/S

#7721 Automated cherry pick of #7719: feat: 控制面板资源跳转按钮增加权限校验
  containers/Dashboard/extends/NumberCard/components/Server.vue
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/S

#7718 fix: cache image in batch
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/image/dialogs/BatchCreateCache.vue
  containers/Compute/views/image/dialogs/CreateCache.vue
  containers/Compute/views/image/dialogs/Delete.vue
  containers/Compute/views/image/sidepage/Cache.vue
  containers/Compute/views/image/sidepage/index.vue
  containers/Compute/views/secgroup/Create.vue
  containers/Compute/views/secgroup/dialogs/SetServer.vue
  containers/Compute/views/secgroup/mixins/serverListPropsForSetServer.js
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/components/UsedPercent/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#7722 fix: cache image customized create action
  containers/Compute/views/image/sidepage/Cache.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/L

#7723 feat: 列表分页展示优化
  containers/Compute/views/image/dialogs/Delete.vue
  containers/Compute/views/image/sidepage/Cache.vue
  containers/Compute/views/image/sidepage/CachedImageEventList.vue
  containers/Compute/views/image/sidepage/index.vue
  src/components/PageList/components/Header.vue
  src/components/PageList/components/Table.vue
  src/components/PageList/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/styles/less/global.less
Labels: size/L

#7725 feat: 告警状态支持排序
  containers/Monitor/views/monitorresource/mixins/columns.js
Labels: size/XS

#7726 Automated cherry pick of #7725: feat: 告警状态支持排序
  containers/Monitor/views/monitorresource/mixins/columns.js
Labels: size/XS

#7727 Automated cherry pick of #7725: feat: 告警状态支持排序
  containers/Monitor/views/monitorresource/mixins/columns.js
Labels: size/XS

#7728 Automated cherry pick of #7710: feat: 页面标题展示当前页面名称
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/router/index.js
  src/router/routes.js
Labels: size/M

#7729 Automated cherry pick of #7728: feat: 页面标题展示当前页面名称
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/router/index.js
  src/router/routes.js
Labels: size/M

#7732 feat: aws磁盘增加最大最小值限制
  containers/Compute/constants/index.js
  src/constants/compute.js
Labels: size/S

#7733 Automated cherry pick of #7732: feat: aws磁盘增加最大最小值限制
  containers/Compute/constants/index.js
  src/constants/compute.js
Labels: size/S

#7734 Automated cherry pick of #7732: feat: aws磁盘增加最大最小值限制
  containers/Compute/constants/index.js
  src/constants/compute.js
Labels: size/S

#7735 feat: 补充aws磁盘规格
  src/constants/compute.js
Labels: size/XS

#7736 Automated cherry pick of #7735: feat: 补充aws磁盘规格
  src/constants/compute.js
Labels: size/XS

#7737 Automated cherry pick of #7735: feat: 补充aws磁盘规格
  src/constants/compute.js
Labels: size/XS

#7740 Automated cherry pick of #7739: feat: 磁盘关机自动重置只有kvm支持
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/S

#7741 Automated cherry pick of #7739: feat: 磁盘关机自动重置只有kvm支持
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/S

#7742 Automated cherry pick of #7739: feat: 磁盘关机自动重置只有kvm支持
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/S

#7743 Automated cherry pick of #7739: feat: 磁盘关机自动重置只有kvm支持
  containers/Compute/views/disk/mixins/singleActions.js
Labels: size/S

#7744 feat: gpu卡关联/取消关联虚拟机增加平台校验
  containers/Compute/views/gpu/mixins/singleActions.js
  containers/Compute/views/vminstance/utils.js
Labels: size/XS

#7745 Automated cherry pick of #7744: feat: gpu卡关联/取消关联虚拟机增加平台校验
  containers/Compute/views/gpu/mixins/singleActions.js
  containers/Compute/views/vminstance/utils.js
Labels: size/XS

#7747 fix: 切换cpu/内存时,sku自动选择一个展示
  containers/Compute/sections/SKU/index.vue
Labels: size/XS

#7748 Automated cherry pick of #7747: fix: 切换cpu/内存时,sku自动选择一个展示
  containers/Compute/sections/SKU/index.vue
Labels: size/XS

#7749 Automated cherry pick of #7747: fix: 切换cpu/内存时,sku自动选择一个展示
  containers/Compute/sections/SKU/index.vue
Labels: size/XS

#7751 fix: 虚拟机操作错误引用已删除的dstack变量报错
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/S

#7752 Automated cherry pick of #7751: fix: 虚拟机操作错误引用已删除的dstack变量报错
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/S

#7757 Automated cherry pick of #7756: fix: fix error manager word
  containers/Cloudenv/views/clouduser/dialogs/SetGroups.vue
Labels: size/XS

#7758 Automated cherry pick of #7756: fix: fix error manager word
  containers/Cloudenv/views/clouduser/dialogs/SetGroups.vue
Labels: size/XS

#7760 Automated cherry pick of #7759: feat: 新建云账号配置区域列表为空
  containers/Cloudenv/views/cloudaccount/create/form/SelectRegion.vue
Labels: size/XS

#7761 Automated cherry pick of #7759: feat: 新建云账号配置区域列表为空
  containers/Cloudenv/views/cloudaccount/create/form/SelectRegion.vue
Labels: size/XS

#7762 Automated cherry pick of #7759: feat: 新建云账号配置区域列表为空
  containers/Cloudenv/views/cloudaccount/create/form/SelectRegion.vue
Labels: size/XS

#7763 feat: 告警记录增加过滤信息
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/commonalert/utils/index.js
  containers/Monitor/views/monitorresource/mixins/columns.js
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/L

#7765 Automated cherry pick of #7763: feat: 告警记录增加过滤信息
  containers/Monitor/views/alertrecord/components/List.vue
  containers/Monitor/views/commonalert/utils/index.js
  containers/Monitor/views/monitorresource/mixins/columns.js
  containers/Monitor/views/monitorresource/sidepage/index.vue
Labels: size/L

#7766 feat: 虚拟机磁盘关机自动重置优化
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/dialogs/SetAutoResetDialog.vue
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/components/Icon/assets/auto-set.svg
  src/components/ListBodyCellWrap/index.vue
  src/utils/common/tableColumn.js
Labels: size/M

#7767 Automated cherry pick of #7766: feat: 虚拟机磁盘关机自动重置优化
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/dialogs/SetAutoResetDialog.vue
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/components/Icon/assets/auto-set.svg
  src/components/ListBodyCellWrap/index.vue
  src/utils/common/tableColumn.js
Labels: size/M

#7769 Automated cherry pick of #7766: feat: 虚拟机磁盘关机自动重置优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/dialogs/SetAutoResetDialog.vue
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/components/Icon/assets/auto-set.svg
  src/components/ListBodyCellWrap/index.vue
  src/utils/common/tableColumn.js
Labels: size/M

#7770 Automated cherry pick of #7766: feat: 虚拟机磁盘关机自动重置优化
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/disk/dialogs/SetAutoResetDialog.vue
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
  src/components/Icon/assets/auto-set.svg
  src/components/ListBodyCellWrap/index.vue
  src/utils/common/tableColumn.js
Labels: size/M

#7772 Automated cherry pick of #7771: feat: 补充翻译
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
Labels: size/XS

#7773 Automated cherry pick of #7772: feat: 补充翻译
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
Labels: size/XS

#7775 Automated cherry pick of #7774: feat: 告警历史支持时间过滤
  containers/Monitor/views/alertrecord/components/List.vue
Labels: size/M

#7777 feat: 虚拟机支持加入/从堡垒机移除
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/dialogs/AddBastion.vue
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
  containers/Compute/views/vminstance/dialogs/RemoveBastion.vue
  src/constants/permission.js
Labels: size/L

#7778 Automated cherry pick of #7777: feat: 虚拟机支持加入/从堡垒机移除
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/dialogs/AddBastion.vue
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
  containers/Compute/views/vminstance/dialogs/RemoveBastion.vue
  src/constants/permission.js
Labels: size/L

#7779 Automated cherry pick of #7778: feat: 虚拟机支持加入/从堡垒机移除
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/constants/actions.js
  containers/Compute/views/vminstance/dialogs/AddBastion.vue
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
  containers/Compute/views/vminstance/dialogs/RemoveBastion.vue
  src/constants/permission.js
Labels: size/L

#7780 feat: 虚拟机加入/移除堡垒机增加条件限制
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#7781 Automated cherry pick of #7780: feat: 虚拟机加入/移除堡垒机增加条件限制
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#7782 Automated cherry pick of #7781: feat: 虚拟机加入/移除堡垒机增加条件限制
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#7783 feat: 添加样式
  src/styles/less/global.less
Labels: size/XS

#7784 Automated cherry pick of #7783: feat: 添加样式
  src/styles/less/global.less
Labels: size/XS

#7785 Automated cherry pick of #7783: feat: 添加样式
  src/styles/less/global.less
Labels: size/XS

#7786 feat: 补充样式
  src/styles/less/global.less
Labels: size/S

#7787 Automated cherry pick of #7786: feat: 补充样式
  src/styles/less/global.less
Labels: size/S

#7788 Automated cherry pick of #7786: feat: 补充样式
  src/styles/less/global.less
Labels: size/S

#7789 feat: 主机删除工单补充参数
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
Labels: size/M

#7790 Automated cherry pick of #7789: feat: 主机删除工单补充参数
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
Labels: size/M

#7791 Automated cherry pick of #7789: feat: 主机删除工单补充参数
  containers/Compute/views/vminstance/dialogs/DeleteVm.vue
Labels: size/M

#7793 Automated cherry pick of #7792: feat: 虚拟机加入堡垒机名称参数修改为generate_name
  containers/Compute/views/vminstance/dialogs/AddBastion.vue
Labels: size/XS

#7794 Automated cherry pick of #7792: feat: 虚拟机加入堡垒机名称参数修改为generate_name
  containers/Compute/views/vminstance/dialogs/AddBastion.vue
Labels: size/XS

#7798 Automated cherry pick of #7796: feat: 扩大日志展示框大小
  src/sections/DialogManager/components/EventLog.vue
Labels: size/XS

#7800 Automated cherry pick of #7799: fix: 虚拟机关机不收费禁用操作只在虚拟机为关机状态才验证
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#7801 Automated cherry pick of #7799: fix: 虚拟机关机不收费禁用操作只在虚拟机为关机状态才验证
  containers/Compute/views/vminstance/components/List.vue
  containers/Compute/views/vminstance/constants/actions.js
Labels: size/XS

#7803 fix: 修复列表分页渲染顺序问题
  src/utils/list.js
Labels: size/XS

#7804 Automated cherry pick of #7803: fix: 修复列表分页渲染顺序问题
  src/utils/list.js
Labels: size/XS

#7805 Automated cherry pick of #7804: fix: 修复列表分页渲染顺序问题
  src/utils/list.js
Labels: size/XS

#7809 Automated cherry pick of #7807: fix: 虚拟机调整配置套餐未找到时增加提示
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/SKU/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/S

#7811 Automated cherry pick of #7810: fix: 虚拟机调整配置匹配套餐修正
  containers/Compute/locales/en.json
  containers/Compute/sections/SKU/index.vue
Labels: size/S
