Repository yunionio/dashboard, pull requests merged in 2025-02, with the labels that each got.

#7544 Automated cherry pick of #7543: feat: 扩展i18n取值方法,增加默认值为空字符串
  src/utils/i18n.js
Labels: size/XS

#7545 fix: pod support sync config etc.
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/image/sidepage/index.vue
  containers/Compute/views/node-alert/constants.js
  containers/Compute/views/vminstance-container/components/List.vue
  containers/Compute/views/vminstance-container/constants.js
  containers/Compute/views/vminstance-container/constants/actions.js
  containers/Compute/views/vminstance-container/locales/en.json
  containers/Compute/views/vminstance-container/locales/ja-JP.json
  containers/Compute/views/vminstance-container/locales/zh-CN.json
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/SidePageManager/components/TaskSidePage/Detail.vue
  src/sections/TaskList/index.vue
  src/utils/common/tableColumn.js
Labels: size/L

#7546 fix: locale for s3 sign_alg_version
  containers/Cloudenv/locales/en.json
  containers/Cloudenv/locales/ja-JP.json
  containers/Cloudenv/locales/zh-CN.json
Labels: size/XS

#7549 fix: 导航栏告警只展示告警记录
  scope/layouts/Navbar/index.vue
Labels: size/S

#7550 Automated cherry pick of #7549: fix: 导航栏告警只展示告警记录
  scope/layouts/Navbar/index.vue
Labels: size/S

#7559 Automated cherry pick of #7558: feat: 更换导航栏告警图标
  src/components/Icon/assets/res-commonalert.svg
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/Navbar/components/Alertresource.vue
  src/sections/Navbar/index.vue
Labels: size/S

#7560 Automated cherry pick of #7559: feat: 更换导航栏告警图标
  src/components/Icon/assets/res-commonalert.svg
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
  src/sections/Navbar/components/Alertresource.vue
  src/sections/Navbar/index.vue
Labels: size/S

#7551 fix: physical server ipmi match scope
  containers/Compute/views/physicalmachine/add/index.vue
Labels: size/XS

#7552 Automated cherry pick of #7551: fix: physical server ipmi match scope
  containers/Compute/views/physicalmachine/add/index.vue
Labels: size/XS

#7553 Automated cherry pick of #7551: fix: physical server ipmi match scope
  containers/Compute/views/physicalmachine/add/index.vue
Labels: size/XS

#7557 Automated cherry pick of #7551: fix: physical server ipmi match scope
  containers/Compute/views/physicalmachine/add/index.vue
Labels: size/XS

#7561 feat: remove dstack
  containers/Cloudenv/views/cloudaccount/constants.js
  src/constants/feature.js
  src/constants/index.js
Labels: size/S

#7562 Automated cherry pick of #7561: feat: remove dstack
  containers/Cloudenv/views/cloudaccount/constants.js
  src/constants/feature.js
  src/constants/index.js
Labels: size/S

#7565 Automated cherry pick of #7564: feat: 列表翻页优化
  src/components/PageList/components/Table.vue
  src/components/PageList/components/Table_fixed.vue
Labels: size/XS

#7566 Automated cherry pick of #7564: feat: 列表翻页优化
  src/components/PageList/components/Table.vue
  src/components/PageList/components/Table_fixed.vue
Labels: size/XS

#7568 fix: set time column format
  src/utils/common/tableColumn.js
Labels: size/XS

#7569 Automated cherry pick of #7568: fix: set time column format
  src/utils/common/tableColumn.js
Labels: size/XS

#7570 Automated cherry pick of #7568: fix: set time column format
  src/utils/common/tableColumn.js
Labels: size/XS

#7572 Automated cherry pick of #7571: feat: 宿主机列表字段优化
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/host/sidepage/Dashboard.vue
  containers/Monitor/views/alertresource/components/List.vue
Labels: size/M

#7577 Automated cherry pick of #7575: fix: 优化资源使用率组件
  src/components/UsedPercent/index.vue
Labels: size/XS

#7579 Automated cherry pick of #7578: feat: 虚拟机详情展示手动续费/自动续费
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/vminstance/sidepage/Detail.vue
Labels: size/M

#7582 feat: 列表选中导出支持指定id filter
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/sections/DialogManager/components/ExportListData.vue
  src/utils/list.js
Labels: size/S

#7583 Automated cherry pick of #7582: feat: 列表选中导出支持指定id filter
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/sections/DialogManager/components/ExportListData.vue
  src/utils/list.js
Labels: size/S

#7584 Automated cherry pick of #7583: feat: 列表选中导出支持指定id filter
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/sections/DialogManager/components/ExportListData.vue
  src/utils/list.js
Labels: size/S

#7586 feat: vpc增加隐藏逻辑
  containers/Network/router/index.js
Labels: size/XS

#7590 Automated cherry pick of #7589: feat: 磁贴增加到透传设备的跳转链接
  containers/Dashboard/extends/NumberCard/components/Server.vue
Labels: size/XS

#7597 feat: 调度日志改用yaml格式展示
  src/sections/DialogManager/components/SchedulerLog.vue
  src/styles/less/global.less
Labels: size/M

#7598 Automated cherry pick of #7597: feat: 调度日志改用yaml格式展示
  src/sections/DialogManager/components/SchedulerLog.vue
  src/styles/less/global.less
Labels: size/M

#7599 Automated cherry pick of #7597: feat: 调度日志改用yaml格式展示
  src/sections/DialogManager/components/SchedulerLog.vue
  src/styles/less/global.less
Labels: size/M

#7601 Automated cherry pick of #7600: fix: 增加权限默认值,避免初始化报错
  src/utils/auth.js
Labels: size/XS

#7602 Automated cherry pick of #7600: fix: 增加权限默认值,避免初始化报错
  src/utils/auth.js
Labels: size/XS

#7604 Automated cherry pick of #7603: feat: 虚拟机监控优先展示agent监控
  containers/Compute/views/vminstance/sidepage/Monitor.vue
Labels: size/S

#7605 Automated cherry pick of #7603: feat: 虚拟机监控优先展示agent监控
  containers/Compute/views/vminstance/sidepage/Monitor.vue
Labels: size/S

#7607 Automated cherry pick of #7606: feat: 部分平台机器支持开机调整配置
  containers/Compute/sections/SKU/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/dialogs/Start.vue
  containers/Compute/views/vminstance/utils.js
  src/constants/workflow.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#7608 Automated cherry pick of #7607: feat: 部分平台机器支持开机调整配置
  containers/Compute/sections/SKU/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
  containers/Compute/views/vminstance/dialogs/Start.vue
  containers/Compute/views/vminstance/utils.js
  src/constants/workflow.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/M

#7612 Automated cherry pick of #7611: feat: 虚拟机强制关机增加平台限制
  containers/Compute/views/vminstance/dialogs/ShutDown.vue
Labels: size/S

#7613 Automated cherry pick of #7611: feat: 虚拟机强制关机增加平台限制
  containers/Compute/views/vminstance/dialogs/ShutDown.vue
Labels: size/S

#7616 feat: 磁贴增加监控指标
  containers/Dashboard/constants/index.js
  containers/Dashboard/sections/QuotaConfig/index.vue
Labels: size/S

#7621 Automated cherry pick of #7619: feat: 主机调整配置工单增加详细信息
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/S

#7622 feat: 云账号同步增加镜像类型
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/XS

#7623 Automated cherry pick of #7622: feat: 云账号同步增加镜像类型
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/XS

#7624 Automated cherry pick of #7622: feat: 云账号同步增加镜像类型
  src/sections/DialogManager/components/FullSyncResource.vue
Labels: size/XS

#7625 feat: 磁盘支持设置关机自动重置
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/dialogs/SetAutoResetDialog.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/L

#7626 Automated cherry pick of #7625: feat: 磁盘支持设置关机自动重置
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/dialogs/SetAutoResetDialog.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/L

#7627 Automated cherry pick of #7626: feat: 磁盘支持设置关机自动重置
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/dialogs/SetAutoResetDialog.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/L

#7628 Automated cherry pick of #7626: feat: 磁盘支持设置关机自动重置
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/dialogs/SetAutoResetDialog.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/L

#7629 Automated cherry pick of #7628: feat: 磁盘支持设置关机自动重置
  containers/Compute/locales/en.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/sections/DataDisk/index.vue
  containers/Compute/sections/Disk/index.vue
  containers/Compute/utils/createServer.js
  containers/Compute/views/disk/dialogs/SetAutoResetDialog.vue
  containers/Compute/views/disk/mixins/columns.js
  containers/Compute/views/disk/mixins/singleActions.js
  containers/Compute/views/disk/sidepage/Detail.vue
  containers/Compute/views/vminstance/create/components/SystemDisk.vue
  containers/Compute/views/vminstance/create/form/IDC.vue
  containers/Compute/views/vminstance/create/form/Private.vue
  containers/Compute/views/vminstance/create/form/Public.vue
Labels: size/L

#7631 feat: 虚拟机工单详情信息修正
  containers/Compute/sections/SKU/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/S

#7632 Automated cherry pick of #7631: feat: 虚拟机工单详情信息修正
  containers/Compute/sections/SKU/index.vue
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/S

#7635 Automated cherry pick of #7634: feat: 虚拟机工单详情信息修正
  containers/Compute/views/vminstance/components/AdjustConfigForm.vue
Labels: size/XS
