Repository yunionio/dashboard, pull requests merged in 2025-01, with the labels that each got.

#7494 fix: remove ee content from iam
  containers/IAM/sections/Quota/components/QuotaMessage.vue
  containers/IAM/sections/Quota/components/QuotaProgress.vue
  containers/IAM/sections/Quota/constants.js
  containers/IAM/sections/Quota/index.vue
  containers/IAM/sections/Quota/mixins/domainQuota.js
  containers/IAM/sections/Quota/mixins/hostQuota.js
  containers/IAM/sections/Quota/mixins/identityQuota.js
  containers/IAM/sections/Quota/mixins/imageQuota.js
  containers/IAM/sections/Quota/mixins/infrasQuota.js
  containers/IAM/sections/Quota/mixins/projectQuota.js
  containers/IAM/sections/Quota/mixins/quotaTableAction.js
  containers/IAM/sections/Quota/mixins/regionQuota.js
  containers/IAM/sections/Quota/utils.js
  containers/IAM/sections/QuotaSet.vue
  containers/IAM/views/domains/create/index.vue
  containers/IAM/views/domains/mixins/singleActions.js
  containers/IAM/views/domains/sidepage/Quota.vue
  containers/IAM/views/domains/sidepage/index.vue
  containers/IAM/views/idp/components/List.vue
  containers/IAM/views/idp/edit/AzureADSAML.vue
  containers/IAM/views/idp/edit/AzureOidc.vue
  containers/IAM/views/idp/edit/CAS.vue
  containers/IAM/views/idp/edit/Dingtalk.vue
  containers/IAM/views/idp/edit/Feishu.vue
  containers/IAM/views/idp/edit/Github.vue
  containers/IAM/views/idp/edit/Google.vue
  containers/IAM/views/idp/edit/OIDC.vue
  containers/IAM/views/idp/edit/SAML.vue
  containers/IAM/views/idp/edit/Wechat.vue
  containers/IAM/views/idp/edit/index.vue
  containers/IAM/views/policy/Create.vue
  containers/IAM/views/policy/Update.vue
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/components/FormV2/PolicySelect/index.vue
  containers/IAM/views/policy/components/FormV2/index.vue
  containers/IAM/views/policy/mixins/columns.js
  containers/IAM/views/policy/sidepage/Detail.vue
  containers/IAM/views/projects/create/form/CreateProject.vue
  containers/IAM/views/projects/mixins/singleActions.js
  containers/IAM/views/projects/sidepage/Quota.vue
  containers/IAM/views/projects/sidepage/index.vue
  containers/IAM/views/user/sidepage/ClouduserList.vue
  containers/IAM/views/user/sidepage/SamluserList.vue
  containers/IAM/views/user/sidepage/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XXL

#7495 Automated cherry pick of #7494: fix: remove ee content from iam
  containers/IAM/sections/Quota/components/QuotaMessage.vue
  containers/IAM/sections/Quota/components/QuotaProgress.vue
  containers/IAM/sections/Quota/constants.js
  containers/IAM/sections/Quota/index.vue
  containers/IAM/sections/Quota/mixins/domainQuota.js
  containers/IAM/sections/Quota/mixins/hostQuota.js
  containers/IAM/sections/Quota/mixins/identityQuota.js
  containers/IAM/sections/Quota/mixins/imageQuota.js
  containers/IAM/sections/Quota/mixins/infrasQuota.js
  containers/IAM/sections/Quota/mixins/projectQuota.js
  containers/IAM/sections/Quota/mixins/quotaTableAction.js
  containers/IAM/sections/Quota/mixins/regionQuota.js
  containers/IAM/sections/Quota/utils.js
  containers/IAM/sections/QuotaSet.vue
  containers/IAM/views/domains/create/index.vue
  containers/IAM/views/domains/mixins/singleActions.js
  containers/IAM/views/domains/sidepage/Quota.vue
  containers/IAM/views/domains/sidepage/index.vue
  containers/IAM/views/idp/components/List.vue
  containers/IAM/views/idp/edit/AzureADSAML.vue
  containers/IAM/views/idp/edit/AzureOidc.vue
  containers/IAM/views/idp/edit/CAS.vue
  containers/IAM/views/idp/edit/Dingtalk.vue
  containers/IAM/views/idp/edit/Feishu.vue
  containers/IAM/views/idp/edit/Github.vue
  containers/IAM/views/idp/edit/Google.vue
  containers/IAM/views/idp/edit/OIDC.vue
  containers/IAM/views/idp/edit/SAML.vue
  containers/IAM/views/idp/edit/Wechat.vue
  containers/IAM/views/idp/edit/index.vue
  containers/IAM/views/policy/Create.vue
  containers/IAM/views/policy/Update.vue
  containers/IAM/views/policy/components/Form/index.vue
  containers/IAM/views/policy/components/FormV2/PolicySelect/index.vue
  containers/IAM/views/policy/components/FormV2/index.vue
  containers/IAM/views/policy/mixins/columns.js
  containers/IAM/views/policy/sidepage/Detail.vue
  containers/IAM/views/projects/create/form/CreateProject.vue
  containers/IAM/views/projects/mixins/singleActions.js
  containers/IAM/views/projects/sidepage/Quota.vue
  containers/IAM/views/projects/sidepage/index.vue
  containers/IAM/views/user/sidepage/ClouduserList.vue
  containers/IAM/views/user/sidepage/SamluserList.vue
  containers/IAM/views/user/sidepage/index.vue
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XXL

#7498 fix: more pod monitor
  containers/Compute/sections/monitor/BaseMonitor.vue
  containers/Compute/views/node-alert/constants.js
  containers/Compute/views/vminstance-container/constants.js
  containers/Compute/views/vminstance-container/locales/en.json
  containers/Compute/views/vminstance-container/locales/ja-JP.json
  containers/Compute/views/vminstance-container/locales/zh-CN.json
  containers/Compute/views/vminstance-container/sidepage/Monitor.vue
  src/sections/TaskList/index.vue
Labels: size/M

#7499 fix: rename pod monitor redId to monitorResId
  containers/Compute/views/vminstance-container/sidepage/Monitor.vue
Labels: size/XS

#7502 fix: image list add default disk format filter
  containers/Compute/views/image/components/List.vue
  containers/Compute/views/image/index.vue
Labels: size/S

#7505 Automated cherry pick of #7504: feat: 基础企业版
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/XS

#7507 Automated cherry pick of #7506: fix: 虚拟机关机工单不收费参数错误
  containers/Compute/views/vminstance/dialogs/ShutDown.vue
Labels: size/XS

#7508 fix: host list ignore topo info
  containers/Compute/views/host/components/List.vue
  src/utils/common/tableColumn.js
Labels: size/S

#7512 Automated cherry pick of #7511: fix: 宿主机列表资源使用率监控查询参数错误
  containers/Compute/views/host/components/List.vue
Labels: size/S

#7515 fix: list with summary statistics
  containers/Network/views/network/sidepage/Detail.vue
  src/utils/list.js
Labels: size/XS

#7516 Automated cherry pick of #7515: fix: list with summary statistics
  containers/Network/views/network/sidepage/Detail.vue
  src/utils/list.js
Labels: size/XS

#7518 feat: 补充状态翻译
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7519 Automated cherry pick of #7518: feat: 补充状态翻译
  src/constants/expectStatus.js
  src/locales/en.json
  src/locales/ja-JP.json
  src/locales/zh-CN.json
Labels: size/S

#7530 Automated cherry pick of #7529: feat: 忽略监控查询403报错
  src/store/modules/monitor.js
Labels: size/XS

#7532 feat: 优化导出功能,支持自定义列顺序导出
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/L

#7533 Automated cherry pick of #7532: feat: 优化导出功能,支持自定义列顺序导出
  src/components/PageList/components/Header.vue
  src/components/PageList/index.vue
  src/sections/DialogManager/components/ExportListData.vue
Labels: size/L

#7524 Automated cherry pick of #7508: fix: host list ignore topo info
  containers/Compute/views/host/components/List.vue
  src/utils/common/tableColumn.js
Labels: size/S

#7540 Automated cherry pick of #7539: feat: 宿主机列表资源使用率展示优化
  containers/Compute/locales/en.json
  containers/Compute/locales/ja-JP.json
  containers/Compute/locales/zh-CN.json
  containers/Compute/views/host/components/List.vue
  containers/Compute/views/host/mixins/columns.js
  containers/Compute/views/host/sidepage/Dashboard.vue
  containers/Compute/views/host/sidepage/index.vue
  containers/Compute/views/host/utils/index.js
  containers/Compute/views/vminstance/constants.js
  containers/Compute/views/vminstance/sidepage/Detail.vue
  containers/Compute/views/vminstance/sidepage/Monitor.vue
  src/components/UsedPercent/index.vue
Labels: size/L
